# Import

In [1]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

import logging
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("curation.log"),
        logging.StreamHandler(),  # keep console output too
    ],
    force=True,
)

# Download the dataset

In [2]:
noncurated_path = "../non_curated/h5ad/adamson_2016_upr_perturb_seq.h5ad"
download_file(
    url="https://zenodo.org/record/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad",
    dest_path=noncurated_path
)

2026-04-28 11:10:57,386 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): zenodo.org:443
2026-04-28 11:10:57,475 DEBUG urllib3.connectionpool: https://zenodo.org:443 "GET /record/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad HTTP/1.1" 301 317
2026-04-28 11:10:57,556 DEBUG urllib3.connectionpool: https://zenodo.org:443 "GET /records/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad HTTP/1.1" 200 471286951

Downloaded https://zenodo.org/record/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad to ../non_curated/h5ad/adamson_2016_upr_perturb_seq.h5ad

# Initialise the dataset object

In [3]:
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

2026-04-28 11:12:14,784 DEBUG h5py._conv: Creating converter from 3 to 5

Loading data from ../non_curated/h5ad/adamson_2016_upr_perturb_seq.h5ad

In [4]:
cur_data.show_var()

Variable data:
DataFrame shape: (32738, 3)
--------------------------------------------------
                   ensembl_id  ncounts  ncells
gene_symbol
MIR1302-10    ENSG00000243485     11.0      11
FAM138A       ENSG00000237613      0.0       0
OR4F5         ENSG00000186092      0.0       0
RP11-34P13.7  ENSG00000238009      0.0       0
RP11-34P13.8  ENSG00000239945     43.0      43
...                       ...      ...     ...
AC145205.1    ENSG00000215635      0.0       0
BAGE5         ENSG00000268590      0.0       0
CU459201.1    ENSG00000251180      0.0       0
AC002321.2    ENSG00000215616      0.0       0
AC002321.1    ENSG00000215611      0.0       0

[32738 rows x 3 columns]
--------------------------------------------------

In [5]:
cur_data.adata.obs

,perturbation,read count,UMI count,tissue_type,cell_line,cancer,disease,perturbation_type,celltype,organism,ncounts,ngenes,percent_mito,percent_ribo,nperts
cell_barcode,,,,,,,,,,,,,,,
AAACATACAAGATG,63(mod)_pBA580,282.0,8.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,8866.0,2914,4.917663,21.306112,2
AAACATACACCTAG,OST4_pDS353,331.0,7.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,13785.0,3818,4.468626,19.492201,2
AAACATACTTCCCG,SEC61A1_pDS031,285.0,10.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,7569.0,2616,5.060113,23.199894,2
AAACATTGAAACAG,EIF2B4_pDS491,1036.0,30.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,13834.0,3488,5.052769,28.733555,2
AAACATTGCAGCTA,SRPR_pDS482,863.0,25.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,15507.0,3620,4.514091,26.729864,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGCATGCTTTAC,STT3A_pDS011,476.0,17.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,14524.0,3356,5.996971,22.679703,2
TTTGCATGGAGGAC,ARHGAP22_pDS458,539.0,19.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,11685.0,2961,4.612751,26.983313,2
TTTGCATGTAGAGA,63(mod)_pBA580,647.0,35.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,16610.0,3473,7.242625,26.207104,2
TTTGCATGTCAAGC,KCTD16_pDS096,98.0,4.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,14473.0,3431,7.296345,20.755890,2
TTTGCATGTGGAGG,SAMM50_pDS156,427.0,14.0,cell_line,K562,True,chronic myelogenous leukemia,CRISPR,lymphoblasts,human,16843.0,3719,5.919373,20.097370,2

# OBS slot curation

### Add cell barcodes to the obs slot

In [6]:
cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.astype(str)

print(cur_data.adata.obs[['cell_barcode']].head())

                  cell_barcode
cell_barcode
AAACATACAAGATG  AAACATACAAGATG
AAACATACACCTAG  AAACATACACCTAG
AAACATACTTCCCG  AAACATACTTCCCG
AAACATTGAAACAG  AAACATTGAAACAG
AAACATTGCAGCTA  AAACATTGCAGCTA

### Show unique perturbations

In [7]:
cur_data.show_unique(slot="obs", column="perturbation")

Unique values in adata.obs.perturbation: 115
--------------------------------------------------
{nan,
 '*',
 '62(mod)_pBA581',
 '63(mod)_pBA580',
 'AARS_pDS381',
 'AMIGO3_pDS434',
 'ARHGAP22_pDS458',
 'ASCC3_pDS051',
 'ASCC3_pDS052',
 'ATF4_pBA576',
 'ATF4_pBA577',
 'ATF4_pBA608',
 'ATF6_pBA586',
 'ATP5B_pDS055',
 'C7orf26_pDS004',
 'CAD_pDS468',
 'CARS_pDS460',
 'CCND3_pDS005',
 'CCND3_pDS006',
 'CHERP_pDS024',
 'COPB1_pDS065',
 'COPZ1_pDS462',
 'DAD1_pDS499',
 'DARS_pDS495',
 'DDOST_pDS382',
 'DDRGK1_pDS041',
 'DERL2_pDS042',
 'DHDDS_pDS383',
 'DNAJC19_pDS026',
 'DNAJC19_pDS074',
 'EIF2AK3_pBA572',
 'EIF2AK3_pBA573',
 'EIF2B2_pDS463',
 'EIF2B3_pDS508',
 'EIF2B4_pDS491',
 'EIF2S1_pDS386',
 'ERN1_pBA574',
 'ERN1_pBA575',
 'FARSB_pDS390',
 'FECH_pDS494',
 'GBF1_pDS043',
 'GBF1_pDS044',
 'GMPPB_pDS391',
 'GNPNAT1_pDS506',
 'Gal4-4(mod)_pBA582',
 'HARS_pDS466',
 'HSD17B12_pDS087',
 'HSPA5_pDS017',
 'HSPA5_pDS371',
 'HSPA9_pDS088',
 'HYOU1_pDS089',
 'IARS2_pDS090',
 'IARS2_pDS091',
 'IDH3A_pDS393',
 'IER3IP1_pDS002',
 'IER3IP1_pDS003',
 'IER3IP1_pDS110',
 'KCTD16_pDS096',
 'MANF_pDS027',
 'MARS_pDS394',
 'MRGBP_pDS124',
 'MRPL39_pDS498',
 'MTHFD1_pDS395',
 'NEDD8_pDS396',
 'OST4_pDS353',
 'P4HB_pDS397',
 'PDIA6_pDS029',
 'PPWD1_pDS398',
 'PSMA1_pDS007',
 'PSMD12_pDS008',
 'PSMD12_pDS009',
 'PSMD4_pDS488',
 'PTDSS1_pDS478',
 'QARS_pDS510',
 'SAMM50_pDS156',
 'SARS_pDS467',
 'SCYL1_pDS159',
 'SCYL1_pDS160',
 'SEC61A1_pDS031',
 'SEC61A1_pDS032',
 'SEC61B_pDS033',
 'SEC61B_pDS162',
 'SEC61G_pDS440',
 'SEC63_pDS218',
 'SEL1L_pDS373',
 'SLC35B1_pDS046',
 'SLC39A7_pDS219',
 'SLMO2_pDS433',
 'SOCS1_pDS479',
 'SPCS2_pDS401',
 'SPCS3_pDS402',
 'SRP68_pDS403',
 'SRP72_pDS505',
 'SRPRB_pDS404',
 'SRPR_pDS482',
 'STT3A_pDS010',
 'STT3A_pDS011',
 'SYVN1_pDS442',
 'TARS_pDS405',
 'TELO2_pDS496',
 'TIMM23_pDS284',
 'TIMM44_pDS430',
 'TMED10_pDS036',
 'TMED2_pDS175',
 'TMEM167A_pDS038',
 'TTI1_pDS407',
 'TTI2_pDS408',
 'UFL1_pDS410',
 'UFM1_pDS040',
 'XBP1_pBA578',
 'XBP1_pBA579',
 'XRN1_pDS411',
 'YIPF5_pDS001',
 'YIPF5_pDS186',
 'YIPF5_pDS226'}
--------------------------------------------------

### Drop NAs

In [8]:
cur_data.remove_na(slot="obs", column="perturbation")

Removed 2613 NA entries from column perturbation of adata.obs

### Drop "*" entries

In [9]:
cur_data.remove_entries(slot="obs", column="perturbation", to_remove=r"\*")

Removed 101 entries \* from column perturbation of adata.obs

In [10]:
cur_data.show_unique(slot="obs", column="perturbation")

Unique values in adata.obs.perturbation: 113
--------------------------------------------------
{'62(mod)_pBA581',
 '63(mod)_pBA580',
 'AARS_pDS381',
 'AMIGO3_pDS434',
 'ARHGAP22_pDS458',
 'ASCC3_pDS051',
 'ASCC3_pDS052',
 'ATF4_pBA576',
 'ATF4_pBA577',
 'ATF4_pBA608',
 'ATF6_pBA586',
 'ATP5B_pDS055',
 'C7orf26_pDS004',
 'CAD_pDS468',
 'CARS_pDS460',
 'CCND3_pDS005',
 'CCND3_pDS006',
 'CHERP_pDS024',
 'COPB1_pDS065',
 'COPZ1_pDS462',
 'DAD1_pDS499',
 'DARS_pDS495',
 'DDOST_pDS382',
 'DDRGK1_pDS041',
 'DERL2_pDS042',
 'DHDDS_pDS383',
 'DNAJC19_pDS026',
 'DNAJC19_pDS074',
 'EIF2AK3_pBA572',
 'EIF2AK3_pBA573',
 'EIF2B2_pDS463',
 'EIF2B3_pDS508',
 'EIF2B4_pDS491',
 'EIF2S1_pDS386',
 'ERN1_pBA574',
 'ERN1_pBA575',
 'FARSB_pDS390',
 'FECH_pDS494',
 'GBF1_pDS043',
 'GBF1_pDS044',
 'GMPPB_pDS391',
 'GNPNAT1_pDS506',
 'Gal4-4(mod)_pBA582',
 'HARS_pDS466',
 'HSD17B12_pDS087',
 'HSPA5_pDS017',
 'HSPA5_pDS371',
 'HSPA9_pDS088',
 'HYOU1_pDS089',
 'IARS2_pDS090',
 'IARS2_pDS091',
 'IDH3A_pDS393',
 'IER3IP1_pDS002',
 'IER3IP1_pDS003',
 'IER3IP1_pDS110',
 'KCTD16_pDS096',
 'MANF_pDS027',
 'MARS_pDS394',
 'MRGBP_pDS124',
 'MRPL39_pDS498',
 'MTHFD1_pDS395',
 'NEDD8_pDS396',
 'OST4_pDS353',
 'P4HB_pDS397',
 'PDIA6_pDS029',
 'PPWD1_pDS398',
 'PSMA1_pDS007',
 'PSMD12_pDS008',
 'PSMD12_pDS009',
 'PSMD4_pDS488',
 'PTDSS1_pDS478',
 'QARS_pDS510',
 'SAMM50_pDS156',
 'SARS_pDS467',
 'SCYL1_pDS159',
 'SCYL1_pDS160',
 'SEC61A1_pDS031',
 'SEC61A1_pDS032',
 'SEC61B_pDS033',
 'SEC61B_pDS162',
 'SEC61G_pDS440',
 'SEC63_pDS218',
 'SEL1L_pDS373',
 'SLC35B1_pDS046',
 'SLC39A7_pDS219',
 'SLMO2_pDS433',
 'SOCS1_pDS479',
 'SPCS2_pDS401',
 'SPCS3_pDS402',
 'SRP68_pDS403',
 'SRP72_pDS505',
 'SRPRB_pDS404',
 'SRPR_pDS482',
 'STT3A_pDS010',
 'STT3A_pDS011',
 'SYVN1_pDS442',
 'TARS_pDS405',
 'TELO2_pDS496',
 'TIMM23_pDS284',
 'TIMM44_pDS430',
 'TMED10_pDS036',
 'TMED2_pDS175',
 'TMEM167A_pDS038',
 'TTI1_pDS407',
 'TTI2_pDS408',
 'UFL1_pDS410',
 'UFM1_pDS040',
 'XBP1_pBA578',
 'XBP1_pBA579',
 'XRN1_pDS411',
 'YIPF5_pDS001',
 'YIPF5_pDS186',
 'YIPF5_pDS226'}
--------------------------------------------------

### Rename `perturbation` to `perturbation_name`

In [11]:
cur_data.rename_columns(slot="obs", name_dict={"perturbation": "perturbation_name"})

Renamed columns in adata.obs: {'perturbation': 'perturbation_name'}

### Add guide RNA information

In [12]:
# download the protospacer sequences data from supplementary information Table S1
# https://ars.els-cdn.com/content/image/1-s2.0-S0092867416316609-mmc1.xlsx

guides_df = pd.read_csv("../supplementary/adamson_2016_pilot.csv", header=1)
display(guides_df)

guides_dict_vecid = (
    guides_df[["Perturb-seq_Vector_ID", "Protospacer"]]
    .dropna()
    .set_index("Perturb-seq_Vector_ID", drop=True)["Protospacer"]
    .to_dict()
)

guides_dict_vecid

,Gene,Protospacer,Guide_ID (synonymous with sgGuide_ID),Perturb-seq_Vector_ID,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,AARS,GAGGGCGGCCTACCTCTCCT,NaN,pDS381,NaN,NaN,NaN
1,AMIGO3/GMPPB,GGAACGCGACACCGGGTAGA,NaN,pDS391,NaN,NaN,NaN
2,AMIGO3/GMPPB,GGGGCCAGCAGCCGTCTACC,NaN,pDS434,NaN,NaN,NaN
3,ARHGAP22,GGTCCGTCCGGAGCCAGGAG,NaN,pDS458,NaN,NaN,NaN
4,ASCC3,GACGCAAAGACGCACAGACC,NaN,pDS051,NaN,NaN,NaN
...,...,...,...,...,...,...,...
97,YIPF5,GTGACACGTAGCAACGGGGC,NaN,pDS226,NaN,NaN,NaN
98,NaN,GGCCAAACGTGCCCTGACGG,NegCtrl-1,NaN,NaN,NaN,NaN
99,NaN,GCGATGGGGGGGTGGGTAGC,NegCtrl-2,NaN,NaN,NaN,NaN
100,NaN,GACGACTAGTTAGGCGTGTA,NegCtrl-3,NaN,NaN,NaN,NaN
101,NaN,GCCTTGGCTAAACCGCTCCC,NegCtrl-hU6,NaN,NaN,NaN,NaN

{'pDS381': 'GAGGGCGGCCTACCTCTCCT',
 'pDS391': 'GGAACGCGACACCGGGTAGA',
 'pDS434': 'GGGGCCAGCAGCCGTCTACC',
 'pDS458': 'GGTCCGTCCGGAGCCAGGAG',
 'pDS051': 'GACGCAAAGACGCACAGACC',
 'pDS052': 'GCGCACAGACCCGGCGAGGA',
 'pDS055': 'GAGTCTCCGCAAGGCCCCGG',
 'pDS468': 'GTAGGAGCCTCGGGCGCGCT',
 'pDS460': 'GAGCCATGGCAGATTCCTCC',
 'pDS006': 'GCGACGTCCGAGCATTCCA',
 'pDS024': 'GCGCTGGTGGTCGATCGTG',
 'pDS065': 'GCGGCTATGAACCGCAGCAG',
 'pDS462': 'GGATGCTGTGGTGTCCACAG',
 'pDS499': 'GACCTTGCGTGCAGTTATGT',
 'pDS495': 'GTGAGACCCCAGGGTCGGGA',
 'pDS382': 'GTGGGTCCTTCGGCAGGAGG',
 'pDS041': 'GCGGTCCACAAAGGCTCAGA',
 'pDS042': 'GGTAGGCGCGGCTGACCGGT',
 'pDS383': 'GGCGCCCAGCGGAGCTAATC',
 'pDS026': 'GGGCGCCTGTGCTTGAGGTT',
 'pDS074': 'GCTTGCCTGGAACTCCTGTA',
 'pDS463': 'GTAGCTGCCTTCAGCCTTCAC',
 'pDS508': 'GCCATTGGGCTGTCAGTCAG',
 'pDS491': 'GCTGAGGGCGATGGCTGCTG',
 'pDS386': 'GAGACTTGCTTCCCCCTCAC',
 'pDS390': 'GTCACTGTAGGTGCGGCCCA',
 'pDS494': 'GGCAGCCTCGGCCCGAGTCC',
 'pDS043': 'GCAGGGCTCGCGCAGTTACC',
 'pDS506': 'GCAGGGCCGCGCGCAGGCGAG',
 'pDS466': 'GCTCAAGTGGACAGCCGGGA',
 'pDS087': 'GTCATCCTCACCGTCACGGC',
 'pDS017': 'GCGACGGTGAGGTCGACGC',
 'pDS371': 'GGCGACGGTGAGGTCGACGC',
 'pDS088': 'GGGATAAATGGAGGAGTACG',
 'pDS089': 'GGACAGCGTGCGAGCTCCGG',
 'pDS090': 'GGCGCGTGCGCCCTCTTACT',
 'pDS091': 'GCGGAGGACCCCGCTCTCAG',
 'pDS393': 'GGGGCCCGCGTGGATCTCTA',
 'pDS002': 'GGGCCGCGTGAGGGGACACCA',
 'pDS110': 'GGGGCCCCATCGGCTTCCGT',
 'pDS096': 'GGTTTCTCAGACCTAGGTGA',
 'pDS027': 'GACTTGGAGGCGGTGCGGCG',
 'pDS394': 'GCAGCACCGGCAAGCAACCC',
 'pDS124': 'GCGAGCAAGGAGCCCCCGGC',
 'pDS498': 'GTCTGGCTGGTCGCACCCGG',
 'pDS395': 'GGGCCAGTCCCTAAGCACGT',
 'pDS396': 'GCAGCGGCGACCGGAGCGGT',
 'pDS353': 'GGCTTGTTCGCTGGTGGCGT',
 'pDS397': 'GGGCGCCGCCGGGACAGCGG',
 'pDS029': 'GGGCAACCTAGCAGCTCCTC',
 'pDS398': 'GTTTTCAGCAGAGACGTAGA',
 'pDS488': 'GCCGTCCCGGAGACCCGGTC',
 'pDS478': 'GCTGGCGCCCAGCAAAGGCT',
 'pDS510': 'GCGCGCTCAGTGAGAGGAAA',
 'pDS156': 'GCTGCCTCGCAGAGCTGCCC',
 'pDS467': 'GGGCGCAGTGCGGCGGTCAC',
 'pDS159': 'GGCCGGAGGACCCGGAGCTA',
 'pDS160': 'GGCCTTAGCTCCGGGTCCTC',
 'pDS031': 'GCTGTGCAGTGGAACGCGCT',
 'pDS032': 'GTGCTAGCCCGGCGGCAAG',
 'pDS033': 'GTACGGAGCCCCCGAAAGAC',
 'pDS162': 'GGCGGACGGATAGAAAGTTA',
 'pDS440': 'GCTCCAGTGCTACGTGTCCC',
 'pDS218': 'GGTGCAGAGCGTGGTCGTGG',
 'pDS373': 'GGTGGTGGCTGAGTCCGTGG',
 'pDS046': 'GGTCGCATGCAGCTCCTATG',
 'pDS219': 'GCCGGGAAAGGAGAGGATCC',
 'pDS433': 'GAGATGTCCGGGTAGCGCCA',
 'pDS479': 'GCGGCGGACCCGGCCCTAGG',
 'pDS401': 'GTCAGACAAGTCGGAGGGGA',
 'pDS402': 'GGCCGGTCCGCCGCCGGAAC',
 'pDS403': 'GAGAAGCAGGTCCCAGGCGG',
 'pDS505': 'GCCTCCAAGATGGCGAGCGG',
 'pDS482': 'GGCGAACGCGGCCTGAATTCC',
 'pDS404': 'GGCCACCCGGCGCGAGTCCG',
 'pDS011': 'GGGAGCCCCGCGGATCGTTT',
 'pDS442': 'GGCGCTGGGTTCCTGGTGAGT',
 'pDS405': 'GGAGGAGCCAAGAGGCGGGT',
 'pDS496': 'GCCGCGGAGACCCGCCCCAG',
 'pDS284': 'GAAGTAGGCGCTGGCAACGC',
 'pDS430': 'GCGGCACCAGCCACTCCGCA',
 'pDS036': 'GAGACTCGTTCACCACCGA',
 'pDS175': 'GTGAGGCCGAAGCCAGGACC',
 'pDS038': 'GCAGCCACATCACCCTTCCG',
 'pDS407': 'GAAGGCTGGAAGACGAGGTA',
 'pDS408': 'GTCCGGATCCTGTTAGACAC',
 'pDS410': 'GTGACTCGCAGTAGACGCGG',
 'pDS040': 'GCGGTAAGCAAACACTTACA',
 'pDS411': 'GTCCGCGGAGCGACGACCGG',
 'pDS186': 'GGGTGCAGGGGACCGCGTCA',
 'pDS226': 'GTGACACGTAGCAACGGGGC'}

In [13]:
# extract vector IDs from perturbation_names
cur_data.create_columns(
    slot="obs",
    col_dict={
        "vector_id": cur_data.adata.obs["perturbation_name"].str.split("_").str[1]
    },
)

cur_data.show_unique(slot="obs", column="vector_id")

Column vector_id added to adata.obs
Unique values in adata.obs.vector_id: 113
--------------------------------------------------
{'pBA572',
 'pBA573',
 'pBA574',
 'pBA575',
 'pBA576',
 'pBA577',
 'pBA578',
 'pBA579',
 'pBA580',
 'pBA581',
 'pBA582',
 'pBA586',
 'pBA608',
 'pDS001',
 'pDS002',
 'pDS003',
 'pDS004',
 'pDS005',
 'pDS006',
 'pDS007',
 'pDS008',
 'pDS009',
 'pDS010',
 'pDS011',
 'pDS017',
 'pDS024',
 'pDS026',
 'pDS027',
 'pDS029',
 'pDS031',
 'pDS032',
 'pDS033',
 'pDS036',
 'pDS038',
 'pDS040',
 'pDS041',
 'pDS042',
 'pDS043',
 'pDS044',
 'pDS046',
 'pDS051',
 'pDS052',
 'pDS055',
 'pDS065',
 'pDS074',
 'pDS087',
 'pDS088',
 'pDS089',
 'pDS090',
 'pDS091',
 'pDS096',
 'pDS110',
 'pDS124',
 'pDS156',
 'pDS159',
 'pDS160',
 'pDS162',
 'pDS175',
 'pDS186',
 'pDS218',
 'pDS219',
 'pDS226',
 'pDS284',
 'pDS353',
 'pDS371',
 'pDS373',
 'pDS381',
 'pDS382',
 'pDS383',
 'pDS386',
 'pDS390',
 'pDS391',
 'pDS393',
 'pDS394',
 'pDS395',
 'pDS396',
 'pDS397',
 'pDS398',
 'pDS401',
 'pDS402',
 'pDS403',
 'pDS404',
 'pDS405',
 'pDS407',
 'pDS408',
 'pDS410',
 'pDS411',
 'pDS430',
 'pDS433',
 'pDS434',
 'pDS440',
 'pDS442',
 'pDS458',
 'pDS460',
 'pDS462',
 'pDS463',
 'pDS466',
 'pDS467',
 'pDS468',
 'pDS478',
 'pDS479',
 'pDS482',
 'pDS488',
 'pDS491',
 'pDS494',
 'pDS495',
 'pDS496',
 'pDS498',
 'pDS499',
 'pDS505',
 'pDS506',
 'pDS508',
 'pDS510'}
--------------------------------------------------

In [14]:
cur_data.map_values_from_column(
    ref_col="vector_id", target_col="guide_sequence", map_dict=guides_dict_vecid
)

Column guide_sequence created in adata.obs
Mapped value pDS381 in column vector_id to GAGGGCGGCCTACCTCTCCT in column guide_sequence of adata.obs
Mapped value pDS391 in column vector_id to GGAACGCGACACCGGGTAGA in column guide_sequence of adata.obs
Mapped value pDS434 in column vector_id to GGGGCCAGCAGCCGTCTACC in column guide_sequence of adata.obs
Mapped value pDS458 in column vector_id to GGTCCGTCCGGAGCCAGGAG in column guide_sequence of adata.obs
Mapped value pDS051 in column vector_id to GACGCAAAGACGCACAGACC in column guide_sequence of adata.obs
Mapped value pDS052 in column vector_id to GCGCACAGACCCGGCGAGGA in column guide_sequence of adata.obs
Mapped value pDS055 in column vector_id to GAGTCTCCGCAAGGCCCCGG in column guide_sequence of adata.obs
Mapped value pDS468 in column vector_id to GTAGGAGCCTCGGGCGCGCT in column guide_sequence of adata.obs
Mapped value pDS460 in column vector_id to GAGCCATGGCAGATTCCTCC in column guide_sequence of adata.obs
Mapped value pDS006 in column vector_id to GCGACGTCCGAGCATTCCA in column guide_sequence of adata.obs
Mapped value pDS024 in column vector_id to GCGCTGGTGGTCGATCGTG in column guide_sequence of adata.obs
Mapped value pDS065 in column vector_id to GCGGCTATGAACCGCAGCAG in column guide_sequence of adata.obs
Mapped value pDS462 in column vector_id to GGATGCTGTGGTGTCCACAG in column guide_sequence of adata.obs
Mapped value pDS499 in column vector_id to GACCTTGCGTGCAGTTATGT in column guide_sequence of adata.obs
Mapped value pDS495 in column vector_id to GTGAGACCCCAGGGTCGGGA in column guide_sequence of adata.obs
Mapped value pDS382 in column vector_id to GTGGGTCCTTCGGCAGGAGG in column guide_sequence of adata.obs
Mapped value pDS041 in column vector_id to GCGGTCCACAAAGGCTCAGA in column guide_sequence of adata.obs
Mapped value pDS042 in column vector_id to GGTAGGCGCGGCTGACCGGT in column guide_sequence of adata.obs
Mapped value pDS383 in column vector_id to GGCGCCCAGCGGAGCTAATC in column guide_sequence of adata.obs
Mapped value pDS026 in column vector_id to GGGCGCCTGTGCTTGAGGTT in column guide_sequence of adata.obs
Mapped value pDS074 in column vector_id to GCTTGCCTGGAACTCCTGTA in column guide_sequence of adata.obs
Mapped value pDS463 in column vector_id to GTAGCTGCCTTCAGCCTTCAC in column guide_sequence of adata.obs
Mapped value pDS508 in column vector_id to GCCATTGGGCTGTCAGTCAG in column guide_sequence of adata.obs
Mapped value pDS491 in column vector_id to GCTGAGGGCGATGGCTGCTG in column guide_sequence of adata.obs
Mapped value pDS386 in column vector_id to GAGACTTGCTTCCCCCTCAC in column guide_sequence of adata.obs
Mapped value pDS390 in column vector_id to GTCACTGTAGGTGCGGCCCA in column guide_sequence of adata.obs
Mapped value pDS494 in column vector_id to GGCAGCCTCGGCCCGAGTCC in column guide_sequence of adata.obs
Mapped value pDS043 in column vector_id to GCAGGGCTCGCGCAGTTACC in column guide_sequence of adata.obs
Mapped value pDS506 in column vector_id to GCAGGGCCGCGCGCAGGCGAG in column guide_sequence of adata.obs
Mapped value pDS466 in column vector_id to GCTCAAGTGGACAGCCGGGA in column guide_sequence of adata.obs
Mapped value pDS087 in column vector_id to GTCATCCTCACCGTCACGGC in column guide_sequence of adata.obs
Mapped value pDS017 in column vector_id to GCGACGGTGAGGTCGACGC in column guide_sequence of adata.obs
Mapped value pDS371 in column vector_id to GGCGACGGTGAGGTCGACGC in column guide_sequence of adata.obs
Mapped value pDS088 in column vector_id to GGGATAAATGGAGGAGTACG in column guide_sequence of adata.obs
Mapped value pDS089 in column vector_id to GGACAGCGTGCGAGCTCCGG in column guide_sequence of adata.obs
Mapped value pDS090 in column vector_id to GGCGCGTGCGCCCTCTTACT in column guide_sequence of adata.obs
Mapped value pDS091 in column vector_id to GCGGAGGACCCCGCTCTCAG in column guide_sequence of adata.obs
Mapped value pDS393 in column vector_id to GGGGCCCGCGTGGATCTCTA in column guide_sequence of adata.obs
Mapped value pDS002 in column vector_id to GGGCCGCGTGAGGGGACACCA in column guide_sequence of adata.obs
Mapped value pDS110 in column vector_id to GGGGCCCCATCGGCTTCCGT in column guide_sequence of adata.obs
Mapped value pDS096 in column vector_id to GGTTTCTCAGACCTAGGTGA in column guide_sequence of adata.obs
Mapped value pDS027 in column vector_id to GACTTGGAGGCGGTGCGGCG in column guide_sequence of adata.obs
Mapped value pDS394 in column vector_id to GCAGCACCGGCAAGCAACCC in column guide_sequence of adata.obs
Mapped value pDS124 in column vector_id to GCGAGCAAGGAGCCCCCGGC in column guide_sequence of adata.obs
Mapped value pDS498 in column vector_id to GTCTGGCTGGTCGCACCCGG in column guide_sequence of adata.obs
Mapped value pDS395 in column vector_id to GGGCCAGTCCCTAAGCACGT in column guide_sequence of adata.obs
Mapped value pDS396 in column vector_id to GCAGCGGCGACCGGAGCGGT in column guide_sequence of adata.obs
Mapped value pDS353 in column vector_id to GGCTTGTTCGCTGGTGGCGT in column guide_sequence of adata.obs
Mapped value pDS397 in column vector_id to GGGCGCCGCCGGGACAGCGG in column guide_sequence of adata.obs
Mapped value pDS029 in column vector_id to GGGCAACCTAGCAGCTCCTC in column guide_sequence of adata.obs
Mapped value pDS398 in column vector_id to GTTTTCAGCAGAGACGTAGA in column guide_sequence of adata.obs
Mapped value pDS488 in column vector_id to GCCGTCCCGGAGACCCGGTC in column guide_sequence of adata.obs
Mapped value pDS478 in column vector_id to GCTGGCGCCCAGCAAAGGCT in column guide_sequence of adata.obs
Mapped value pDS510 in column vector_id to GCGCGCTCAGTGAGAGGAAA in column guide_sequence of adata.obs
Mapped value pDS156 in column vector_id to GCTGCCTCGCAGAGCTGCCC in column guide_sequence of adata.obs
Mapped value pDS467 in column vector_id to GGGCGCAGTGCGGCGGTCAC in column guide_sequence of adata.obs
Mapped value pDS159 in column vector_id to GGCCGGAGGACCCGGAGCTA in column guide_sequence of adata.obs
Mapped value pDS160 in column vector_id to GGCCTTAGCTCCGGGTCCTC in column guide_sequence of adata.obs
Mapped value pDS031 in column vector_id to GCTGTGCAGTGGAACGCGCT in column guide_sequence of adata.obs
Mapped value pDS032 in column vector_id to GTGCTAGCCCGGCGGCAAG in column guide_sequence of adata.obs
Mapped value pDS033 in column vector_id to GTACGGAGCCCCCGAAAGAC in column guide_sequence of adata.obs
Mapped value pDS162 in column vector_id to GGCGGACGGATAGAAAGTTA in column guide_sequence of adata.obs
Mapped value pDS440 in column vector_id to GCTCCAGTGCTACGTGTCCC in column guide_sequence of adata.obs
Mapped value pDS218 in column vector_id to GGTGCAGAGCGTGGTCGTGG in column guide_sequence of adata.obs
Mapped value pDS373 in column vector_id to GGTGGTGGCTGAGTCCGTGG in column guide_sequence of adata.obs
Mapped value pDS046 in column vector_id to GGTCGCATGCAGCTCCTATG in column guide_sequence of adata.obs
Mapped value pDS219 in column vector_id to GCCGGGAAAGGAGAGGATCC in column guide_sequence of adata.obs
Mapped value pDS433 in column vector_id to GAGATGTCCGGGTAGCGCCA in column guide_sequence of adata.obs
Mapped value pDS479 in column vector_id to GCGGCGGACCCGGCCCTAGG in column guide_sequence of adata.obs
Mapped value pDS401 in column vector_id to GTCAGACAAGTCGGAGGGGA in column guide_sequence of adata.obs
Mapped value pDS402 in column vector_id to GGCCGGTCCGCCGCCGGAAC in column guide_sequence of adata.obs
Mapped value pDS403 in column vector_id to GAGAAGCAGGTCCCAGGCGG in column guide_sequence of adata.obs
Mapped value pDS505 in column vector_id to GCCTCCAAGATGGCGAGCGG in column guide_sequence of adata.obs
Mapped value pDS482 in column vector_id to GGCGAACGCGGCCTGAATTCC in column guide_sequence of adata.obs
Mapped value pDS404 in column vector_id to GGCCACCCGGCGCGAGTCCG in column guide_sequence of adata.obs
Mapped value pDS011 in column vector_id to GGGAGCCCCGCGGATCGTTT in column guide_sequence of adata.obs
Mapped value pDS442 in column vector_id to GGCGCTGGGTTCCTGGTGAGT in column guide_sequence of adata.obs
Mapped value pDS405 in column vector_id to GGAGGAGCCAAGAGGCGGGT in column guide_sequence of adata.obs
Mapped value pDS496 in column vector_id to GCCGCGGAGACCCGCCCCAG in column guide_sequence of adata.obs
Mapped value pDS284 in column vector_id to GAAGTAGGCGCTGGCAACGC in column guide_sequence of adata.obs
Mapped value pDS430 in column vector_id to GCGGCACCAGCCACTCCGCA in column guide_sequence of adata.obs
Mapped value pDS036 in column vector_id to GAGACTCGTTCACCACCGA in column guide_sequence of adata.obs
Mapped value pDS175 in column vector_id to GTGAGGCCGAAGCCAGGACC in column guide_sequence of adata.obs
Mapped value pDS038 in column vector_id to GCAGCCACATCACCCTTCCG in column guide_sequence of adata.obs
Mapped value pDS407 in column vector_id to GAAGGCTGGAAGACGAGGTA in column guide_sequence of adata.obs
Mapped value pDS408 in column vector_id to GTCCGGATCCTGTTAGACAC in column guide_sequence of adata.obs
Mapped value pDS410 in column vector_id to GTGACTCGCAGTAGACGCGG in column guide_sequence of adata.obs
Mapped value pDS040 in column vector_id to GCGGTAAGCAAACACTTACA in column guide_sequence of adata.obs
Mapped value pDS411 in column vector_id to GTCCGCGGAGCGACGACCGG in column guide_sequence of adata.obs
Mapped value pDS186 in column vector_id to GGGTGCAGGGGACCGCGTCA in column guide_sequence of adata.obs
Mapped value pDS226 in column vector_id to GTGACACGTAGCAACGGGGC in column guide_sequence of adata.obs

In [15]:
cur_data.adata.obs[['perturbation_name', 'guide_sequence']]

               perturbation_name         guide_sequence
cell_barcode
AAACATACAAGATG    63(mod)_pBA580                    nan
AAACATACACCTAG       OST4_pDS353   GGCTTGTTCGCTGGTGGCGT
AAACATACTTCCCG    SEC61A1_pDS031   GCTGTGCAGTGGAACGCGCT
AAACATTGAAACAG     EIF2B4_pDS491   GCTGAGGGCGATGGCTGCTG
AAACATTGCAGCTA       SRPR_pDS482  GGCGAACGCGGCCTGAATTCC
...                          ...                    ...
TTTGCATGCTTTAC      STT3A_pDS011   GGGAGCCCCGCGGATCGTTT
TTTGCATGGAGGAC   ARHGAP22_pDS458   GGTCCGTCCGGAGCCAGGAG
TTTGCATGTAGAGA    63(mod)_pBA580                    nan
TTTGCATGTCAAGC     KCTD16_pDS096   GGTTTCTCAGACCTAGGTGA
TTTGCATGTGGAGG     SAMM50_pDS156   GCTGCCTCGCAGAGCTGCCC

[62623 rows x 2 columns]

### Extract perturbation symbols

#### Add `perturbation_target_symbol` column based on the `perturbation_name`

In [16]:
cur_data.create_columns(
    slot="obs", col_dict={"perturbed_target_symbol_input": cur_data.adata.obs["perturbation_name"]},
    overwrite=True
)
cur_data.show_unique(slot = 'obs', column = 'perturbed_target_symbol_input')

Column perturbed_target_symbol_input added to adata.obs
Unique values in adata.obs.perturbed_target_symbol_input: 113
--------------------------------------------------
{'62(mod)_pBA581',
 '63(mod)_pBA580',
 'AARS_pDS381',
 'AMIGO3_pDS434',
 'ARHGAP22_pDS458',
 'ASCC3_pDS051',
 'ASCC3_pDS052',
 'ATF4_pBA576',
 'ATF4_pBA577',
 'ATF4_pBA608',
 'ATF6_pBA586',
 'ATP5B_pDS055',
 'C7orf26_pDS004',
 'CAD_pDS468',
 'CARS_pDS460',
 'CCND3_pDS005',
 'CCND3_pDS006',
 'CHERP_pDS024',
 'COPB1_pDS065',
 'COPZ1_pDS462',
 'DAD1_pDS499',
 'DARS_pDS495',
 'DDOST_pDS382',
 'DDRGK1_pDS041',
 'DERL2_pDS042',
 'DHDDS_pDS383',
 'DNAJC19_pDS026',
 'DNAJC19_pDS074',
 'EIF2AK3_pBA572',
 'EIF2AK3_pBA573',
 'EIF2B2_pDS463',
 'EIF2B3_pDS508',
 'EIF2B4_pDS491',
 'EIF2S1_pDS386',
 'ERN1_pBA574',
 'ERN1_pBA575',
 'FARSB_pDS390',
 'FECH_pDS494',
 'GBF1_pDS043',
 'GBF1_pDS044',
 'GMPPB_pDS391',
 'GNPNAT1_pDS506',
 'Gal4-4(mod)_pBA582',
 'HARS_pDS466',
 'HSD17B12_pDS087',
 'HSPA5_pDS017',
 'HSPA5_pDS371',
 'HSPA9_pDS088',
 'HYOU1_pDS089',
 'IARS2_pDS090',
 'IARS2_pDS091',
 'IDH3A_pDS393',
 'IER3IP1_pDS002',
 'IER3IP1_pDS003',
 'IER3IP1_pDS110',
 'KCTD16_pDS096',
 'MANF_pDS027',
 'MARS_pDS394',
 'MRGBP_pDS124',
 'MRPL39_pDS498',
 'MTHFD1_pDS395',
 'NEDD8_pDS396',
 'OST4_pDS353',
 'P4HB_pDS397',
 'PDIA6_pDS029',
 'PPWD1_pDS398',
 'PSMA1_pDS007',
 'PSMD12_pDS008',
 'PSMD12_pDS009',
 'PSMD4_pDS488',
 'PTDSS1_pDS478',
 'QARS_pDS510',
 'SAMM50_pDS156',
 'SARS_pDS467',
 'SCYL1_pDS159',
 'SCYL1_pDS160',
 'SEC61A1_pDS031',
 'SEC61A1_pDS032',
 'SEC61B_pDS033',
 'SEC61B_pDS162',
 'SEC61G_pDS440',
 'SEC63_pDS218',
 'SEL1L_pDS373',
 'SLC35B1_pDS046',
 'SLC39A7_pDS219',
 'SLMO2_pDS433',
 'SOCS1_pDS479',
 'SPCS2_pDS401',
 'SPCS3_pDS402',
 'SRP68_pDS403',
 'SRP72_pDS505',
 'SRPRB_pDS404',
 'SRPR_pDS482',
 'STT3A_pDS010',
 'STT3A_pDS011',
 'SYVN1_pDS442',
 'TARS_pDS405',
 'TELO2_pDS496',
 'TIMM23_pDS284',
 'TIMM44_pDS430',
 'TMED10_pDS036',
 'TMED2_pDS175',
 'TMEM167A_pDS038',
 'TTI1_pDS407',
 'TTI2_pDS408',
 'UFL1_pDS410',
 'UFM1_pDS040',
 'XBP1_pBA578',
 'XBP1_pBA579',
 'XRN1_pDS411',
 'YIPF5_pDS001',
 'YIPF5_pDS186',
 'YIPF5_pDS226'}
--------------------------------------------------

#### Clean up `perturbation_target_symbol` column

In [17]:
cur_data.replace_entries(
    slot="obs",
    column="perturbed_target_symbol_input",
    map_dict={
        r"62\(mod\).*": "control_nontargeting",
        r"63\(mod\).*": "control_nontargeting",
        r"Gal4-4.*": "control_nontargeting",
        r"_(pD|pB).*": "",
    }
)

cur_data.replace_entries(
    slot="obs",
    column="perturbed_target_symbol_input",
    map_dict={
        "CONTROL_NONTARGETING": "control_nontargeting"
    }
)

cur_data.show_unique(slot="obs", column="perturbed_target_symbol_input")

Replaced '62\(mod\).*' with 'control_nontargeting' in column perturbed_target_symbol_input of adata.obs
Replaced '63\(mod\).*' with 'control_nontargeting' in column perturbed_target_symbol_input of adata.obs
Replaced 'Gal4-4.*' with 'control_nontargeting' in column perturbed_target_symbol_input of adata.obs
Replaced '_(pD|pB).*' with '' in column perturbed_target_symbol_input of adata.obs
Replaced 'CONTROL_NONTARGETING' with 'control_nontargeting' in column perturbed_target_symbol_input of adata.obs
Unique values in adata.obs.perturbed_target_symbol_input: 91
--------------------------------------------------
{'AARS',
 'AMIGO3',
 'ARHGAP22',
 'ASCC3',
 'ATF4',
 'ATF6',
 'ATP5B',
 'C7ORF26',
 'CAD',
 'CARS',
 'CCND3',
 'CHERP',
 'COPB1',
 'COPZ1',
 'DAD1',
 'DARS',
 'DDOST',
 'DDRGK1',
 'DERL2',
 'DHDDS',
 'DNAJC19',
 'EIF2AK3',
 'EIF2B2',
 'EIF2B3',
 'EIF2B4',
 'EIF2S1',
 'ERN1',
 'FARSB',
 'FECH',
 'GBF1',
 'GMPPB',
 'GNPNAT1',
 'HARS',
 'HSD17B12',
 'HSPA5',
 'HSPA9',
 'HYOU1',
 'IARS2',
 'IDH3A',
 'IER3IP1',
 'KCTD16',
 'MANF',
 'MARS',
 'MRGBP',
 'MRPL39',
 'MTHFD1',
 'NEDD8',
 'OST4',
 'P4HB',
 'PDIA6',
 'PPWD1',
 'PSMA1',
 'PSMD12',
 'PSMD4',
 'PTDSS1',
 'QARS',
 'SAMM50',
 'SARS',
 'SCYL1',
 'SEC61A1',
 'SEC61B',
 'SEC61G',
 'SEC63',
 'SEL1L',
 'SLC35B1',
 'SLC39A7',
 'SLMO2',
 'SOCS1',
 'SPCS2',
 'SPCS3',
 'SRP68',
 'SRP72',
 'SRPR',
 'SRPRB',
 'STT3A',
 'SYVN1',
 'TARS',
 'TELO2',
 'TIMM23',
 'TIMM44',
 'TMED10',
 'TMED2',
 'TMEM167A',
 'TTI1',
 'TTI2',
 'UFL1',
 'UFM1',
 'XBP1',
 'XRN1',
 'YIPF5',
 'control_nontargeting'}
--------------------------------------------------

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:609: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  if df[column].str.upper().str.contains(old_val.upper()).any():

### Standardise perturbation targets

In [18]:
cur_data.standardize_genes(
    slot='obs',
    input_column='perturbed_target_symbol_input',
    input_column_type='gene_symbol',
    multiple_entries=False,
    # remove_version=True,
    # version_sep='.'
)

Mapping gene symbols: 100%|███████████████████████████████████████| 91/91 [00:00<00:00, 4549.41it/s]

--------------------------------------------------
Successfully mapped 91 out of 91 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: []
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Add `perturbed_target_number` column

In [19]:
cur_data.count_entries(
    slot="obs",
    input_column="perturbed_target_symbol",
    count_column_name="perturbed_target_number",
    sep="|",
)

Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [20]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

In [21]:
cur_data.show_obs(['perturbation_name', 'perturbed_target_chromosome_encoding'])

Observation data:
DataFrame shape: (62623, 2)
--------------------------------------------------
      perturbation_name  perturbed_target_chromosome_encoding
index
0        63(mod)_pBA580                                     0
1           OST4_pDS353                                     2
2        SEC61A1_pDS031                                     3
3         EIF2B4_pDS491                                     2
4           SRPR_pDS482                                    11
...                 ...                                   ...
62618      STT3A_pDS011                                    11
62619   ARHGAP22_pDS458                                    10
62620    63(mod)_pBA580                                     0
62621     KCTD16_pDS096                                     5
62622     SAMM50_pDS156                                    22

[62623 rows x 2 columns]
--------------------------------------------------

### Add metadata

In [22]:
cur_data.create_columns(
    slot="obs",
    col_dict={
        "dataset_id": cur_data.dataset_id,
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        # treatment
        "treatment_label": None, 
        "treatment_id": None,
        # perturbation type
        "perturbation_type_label": "CRISPRi", 
        "perturbation_type_id": None,
        "data_modality": "CRISPR screen",
        "significant": None,
        "significance_criteria": None,
        "score_interpretation": None,
        # model system
        "model_system_label": "cell_line",
        "model_system_id": None,
        # replicates
        "technical_replicate": None,
        "biological_replicate": None,
        
        'tissue': 'blood',
        "timepoint": "P0DT0H0M0S",
        
        "species": "Homo sapiens",
        "sex_label": "female", 
        "sex_id": None,
        "developmental_stage_label": "adult", 
        "developmental_stage_id": None,

        "study_title": "A Multiplexed Single-Cell CRISPR Screening Platform Enables Systematic Dissection of the Unfolded Protein Response",
        "study_uri": "https://doi.org/10.1016/j.cell.2016.11.048",
        "study_year": 2016,
        "first_author": "Britt Adamson",
        "last_author": "Jonathan Weissman",
        
        "experiment_title": "63000 chronic myeloid leukemia (K562) cells transfected with a UPR sensor gene-targeting gRNAs.",
        "experiment_summary": "Perturb-seq was applied to a small CRISPRi library of 91 sgRNAs targeting UPR genes in K562 cells.",
        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],
        
        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",

        "library_generation_method_id": "EFO:0022895",
        "library_generation_method_label": "dCas9-KRAB",

        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "retrovirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",

        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",

        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",

        "library_name": "custom",
        "library_uri": None,

        "library_format_id": None,
        "library_format_label": "pooled",

        "library_scope_id": None,
        "library_scope_label": "focused",

        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "inhibition",
        
        "library_manufacturer": "Weissman",
        "library_lentiviral_generation": "3",
        "library_grnas_per_target": "1",
        "library_total_grnas": "91",
        "library_total_variants": None,
        
        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",

        "readout_type_id": None,
        "readout_type_label": "transcriptomic",

        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",

        "method_name_id": None,
        "method_name_label": "Perturb-seq",

        "method_uri": None,

        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "10x Genomics Single Cell 3-prime",

        "sequencing_platform_id": None,
        "sequencing_platform_label": "Illumina HiSeq 4000",

        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",

        "software_counts_id": None,
        "software_counts_label": "CellRanger",

        "software_analysis_id": None,
        "software_analysis_label": "MAGeCK",

        "reference_genome_id": None,
        "reference_genome_label": "GRCh37",
        
        "license_label": "CC BY 4.0",
        "license_id": "SWO:1000065",

        "associated_datasets": json.dumps([
            {
                "dataset_accession": "GSM2406677",
                "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2406681",
                "dataset_description": "Barcode, cell identities, raw gene expression matrix",
                "dataset_file_name": "GSM2406677_10X010",
            },
            {
                "dataset_accession": "GSM2406677_10X005",
                "dataset_uri": "https://zenodo.org/records/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad",
                "dataset_description": "Processed .h5ad file",
                "dataset_file_name": "AdamsonWeissman2016_GSM2406681_10X010.h5ad",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column treatment_label added to adata.obs
Column treatment_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Column tissue added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_manufacturer added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

In [23]:
cur_data.adata.obs

,tissue_type,percent_ribo,read count,cell_line,perturbation_type,vector_id,nperts,celltype,disease,perturbed_target_symbol_input,...,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,reference_genome_id,reference_genome_label,license_label,license_id,associated_datasets
index,,,,,,,,,,,,,,,,,,,,,
0,cell_line,21.306112,282.0,K562,CRISPR,pBA580,2,lymphoblasts,chronic myelogenous leukemia,control_nontargeting,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
1,cell_line,19.492201,331.0,K562,CRISPR,pDS353,2,lymphoblasts,chronic myelogenous leukemia,OST4,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
2,cell_line,23.199894,285.0,K562,CRISPR,pDS031,2,lymphoblasts,chronic myelogenous leukemia,SEC61A1,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
3,cell_line,28.733555,1036.0,K562,CRISPR,pDS491,2,lymphoblasts,chronic myelogenous leukemia,EIF2B4,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
4,cell_line,26.729864,863.0,K562,CRISPR,pDS482,2,lymphoblasts,chronic myelogenous leukemia,SRPR,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62618,cell_line,22.679703,476.0,K562,CRISPR,pDS011,2,lymphoblasts,chronic myelogenous leukemia,STT3A,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
62619,cell_line,26.983313,539.0,K562,CRISPR,pDS458,2,lymphoblasts,chronic myelogenous leukemia,ARHGAP22,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
62620,cell_line,26.207104,647.0,K562,CRISPR,pBA580,2,lymphoblasts,chronic myelogenous leukemia,control_nontargeting,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
62621,cell_line,20.755890,98.0,K562,CRISPR,pDS096,2,lymphoblasts,chronic myelogenous leukemia,KCTD16,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."
62622,cell_line,20.097370,427.0,K562,CRISPR,pDS156,2,lymphoblasts,chronic myelogenous leukemia,SAMM50,...,barcode sequencing,None,CellRanger,None,MAGeCK,None,GRCh37,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSM2406677"", ""dataset_..."

### Curate tissue information

In [24]:

cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower     ontology_id
0        blood              blood      blood  UBERON:0000178
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [25]:
cur_data.standardize_ontology(
    input_column='celltype',
    column_type='term_name',
    ontology_type='cell_type'
)

Mapped 1 cell_type ontology terms from `celltype` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
   input_column input_column_lower    name_lower ontology_id
0  lymphoblasts       lymphoblasts  lymphoblasts  CL:0017005
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell line information

In [26]:
cur_data.standardize_ontology(
    input_column='cell_line',
    column_type='term_name',
    ontology_type='cell_line'
)

Mapped 1 cell_line ontology terms from `cell_line` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower  ontology_id
0         K562               k562       k562  CLO:0007050
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [27]:
cur_data.standardize_ontology(
    input_column='disease',
    column_type='term_name',
    ontology_type='disease'
)

Mapped 1 disease ontology terms from `disease` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
                   input_column            input_column_lower  \
0  chronic myelogenous leukemia  chronic myelogenous leukemia

                     name_lower    ontology_id
0  chronic myelogenous leukemia  MONDO:0011996
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Match schema column order

In [28]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [29]:
cur_data.validate_data(slot='obs')

2026-04-28 11:17:35,517 DEBUG curation_tools.curation_tools: Applying dtype casting on adata.obs for columns: ['dataset_id', 'sample_id', 'cell_barcode', 'data_modality', 'significant', 'significance_criteria', 'perturbation_name', 'perturbed_target_coord', 'perturbed_target_chromosome', 'perturbed_target_chromosome_encoding', 'perturbed_target_number', 'perturbed_target_ensg', 'perturbed_target_symbol', 'perturbed_target_biotype', 'guide_sequence', 'perturbation_type_label', 'perturbation_type_id', 'timepoint', 'treatment_label', 'treatment_id', 'technical_replicate', 'biological_replicate', 'model_system_label', 'model_system_id', 'species', 'tissue_label', 'tissue_id', 'cell_type_label', 'cell_type_id', 'cell_line_label', 'cell_line_id', 'sex_label', 'sex_id', 'developmental_stage_label', 'developmental_stage_id', 'disease_label', 'disease_id', 'study_title', 'study_uri', 'study_year', 'first_author', 'last_author', 'experiment_title', 'experiment_summary', 'number_of_perturbed_targets', 'number_of_perturbed_samples', 'library_generation_type_id', 'library_generation_type_label', 'library_generation_method_id', 'library_generation_method_label', 'enzyme_delivery_method_id', 'enzyme_delivery_method_label', 'library_delivery_method_id', 'library_delivery_method_label', 'enzyme_integration_state_id', 'enzyme_integration_state_label', 'library_integration_state_id', 'library_integration_state_label', 'enzyme_expression_control_id', 'enzyme_expression_control_label', 'library_expression_control_id', 'library_expression_control_label', 'library_name', 'library_uri', 'library_format_id', 'library_format_label', 'library_scope_id', 'library_scope_label', 'library_perturbation_type_id', 'library_perturbation_type_label', 'library_manufacturer', 'library_lentiviral_generation', 'library_grnas_per_target', 'library_total_grnas', 'library_total_variants', 'readout_dimensionality_id', 'readout_dimensionality_label', 'readout_type_id', 'readout_type_label', 'readout_technology_id', 'readout_technology_label', 'method_name_id', 'method_name_label', 'method_uri', 'sequencing_library_kit_id', 'sequencing_library_kit_label', 'sequencing_platform_id', 'sequencing_platform_label', 'sequencing_strategy_id', 'sequencing_strategy_label', 'software_counts_id', 'software_counts_label', 'software_analysis_id', 'software_analysis_label', 'score_interpretation', 'reference_genome_id', 'reference_genome_label', 'associated_datasets', 'license_label', 'license_id']
2026-04-28 11:17:37,337 INFO curation_tools.curation_tools: adata.obs is valid according to the obs_schema.
2026-04-28 11:17:37,355 DEBUG curation_tools.curation_tools: Validated adata.obs preview (shape=(62623, 100)):
                     dataset_id sample_id    cell_barcode  data_modality significant significance_criteria perturbation_name        perturbed_target_coord perturbed_target_chromosome  perturbed_target_chromosome_encoding  perturbed_target_number perturbed_target_ensg perturbed_target_symbol perturbed_target_biotype         guide_sequence perturbation_type_label perturbation_type_id   timepoint treatment_label treatment_id technical_replicate biological_replicate model_system_label model_system_id       species tissue_label       tissue_id cell_type_label cell_type_id cell_line_label cell_line_id sex_label sex_id developmental_stage_label developmental_stage_id                                    disease_label     disease_id                                                                                                         study_title                                   study_uri  study_year   first_author        last_author                                                                                 experiment_title                                                                                  experiment_summary number_of_perturbed_targets number_of_perturbed_samples library_generation_type_id library_generation_type_label library_generation_method_id library_generation_method_label enzyme_delivery_method_id enzyme_delivery_method_label library_delivery_method_id library_delivery_method_label enzyme_integration_state_id enzyme_integration_state_label library_integration_state_id library_integration_state_label enzyme_expression_control_id    enzyme_expression_control_label library_expression_control_id   library_expression_control_label library_name library_uri library_format_id library_format_label library_scope_id library_scope_label library_perturbation_type_id library_perturbation_type_label library_manufacturer library_lentiviral_generation library_grnas_per_target library_total_grnas  library_total_variants readout_dimensionality_id readout_dimensionality_label readout_type_id readout_type_label readout_technology_id readout_technology_label method_name_id method_name_label method_uri sequencing_library_kit_id      sequencing_library_kit_label sequencing_platform_id sequencing_platform_label sequencing_strategy_id sequencing_strategy_label software_counts_id software_counts_label software_analysis_id software_analysis_label score_interpretation reference_genome_id reference_genome_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 associated_datasets license_label   license_id
0  adamson_2016_upr_perturb_seq         1  AAACATACAAGATG  CRISPR screen        <NA>                  <NA>    63(mod)_pBA580          control_nontargeting        control_nontargeting                                     0                        1  control_nontargeting    control_nontargeting     control_nontargeting                    nan                 CRISPRi                 <NA>  P0DT0H0M0S            <NA>         <NA>                <NA>                 <NA>          cell_line            <NA>  Homo sapiens        blood  UBERON:0000178     lymphoblast   CL:0017005      K 562 cell  CLO:0007050    female   <NA>                     adult                   <NA>  chronic myelogenous leukemia, BCR-ABL1 positive  MONDO:0011996  A Multiplexed Single-Cell CRISPR Screening Platform Enables Systematic Dissection of the Unfolded Protein Response  https://doi.org/10.1016/j.cell.2016.11.048        2016  Britt Adamson  Jonathan Weissman  63000 chronic myeloid leukemia (K562) cells transfected with a UPR sensor gene-targeting gRNAs.  Perturb-seq was applied to a small CRISPRi library of 91 sgRNAs targeting UPR genes in K562 cells.                          91                       62623                EFO:0022868                    endogenous                  EFO:0022895                      dCas9-KRAB                      <NA>      retrovirus transduction                       <NA>       lentivirus transduction                        <NA>       random locus integration                         <NA>        random locus integration                         <NA>  constitutive transgene expression                          <NA>  constitutive transgene expression       custom        <NA>              <NA>               pooled             <NA>             focused                         <NA>                      inhibition             Weissman                             3                        1                  91                    <NA>                      <NA>       high-dimensional assay            <NA>     transcriptomic                  <NA>      single-cell rna-seq           <NA>       Perturb-seq       <NA>                      <NA>  10x Genomics Single Cell 3-prime                   <NA>       Illumina HiSeq 4000                   <NA>        barcode sequencing               <NA>            CellRanger                 <NA>                  MAGeCK                 <NA>                <NA>                 GRCh37  [{"dataset_accession": "GSM2406677", "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2406681", "dataset_description": "Barcode, cell identities, raw gene expression matrix", "dataset_file_name": "GSM2406677_10X010"}, {"dataset_accession": "GSM2406677_10X005", "dataset_uri": "https://zenodo.org/records/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad", "dataset_description": "Processed .h5ad file", "dataset_file_name": "AdamsonWeissman2016_GSM2406681_10X010.h5ad"}]     CC BY 4.0  SWO:1000065
1  adamson_2016_upr_perturb_seq         2  AAACATACACCTAG  CRISPR screen        <NA>                  <NA>       OST4_pDS353     chr2:27070470-27071685;-1                           2                                     2                        1       ENSG00000228474                    OST4           protein_coding   GGCTTGTTCGCTGGTGGCGT                 CRISPRi                 <NA>  P0DT0H0M0S            <NA>         <NA>                <NA>                 <NA>          cell_line            <NA>  Homo sapiens        blood  UBERON:0000178     lymphoblast   CL:0017005      K 562 cell  CLO:0007050    female   <NA>                     adult                   <NA>  chronic myelogenous leukemia, BCR-ABL1 positive  MONDO:0011996  A Multiplexed Single-Cell CRISPR Screening Platform Enables Systematic Dissection of the Unfolded Protein Response  https://doi.org/10.1016/j.cell.2016.11.048        2016  Britt Adamson  Jonathan Weissman  63000 chronic myeloid leukemia (K562) cells transfected with a UPR sensor gene-targeting gRNAs.  Perturb-seq was applied to a small CRISPRi library of 91 sgRNAs targeting UPR genes in K562 cells.                          91                       62623                EFO:0022868                    endogenous                  EFO:0022895                      dCas9-KRAB                      <NA>      retrovirus transduction                       <NA>       lentivirus transduction                        <NA>       random locus integration                         <NA>        random locus integration                         <NA>  constitutive transgene expression                          <NA>  constitutive transgene expression       custom        <NA>              <NA>               pooled             <NA>             focused                         <NA>                      inhibition             Weissman                             3                        1                  91                    <NA>                      <NA>       high-dimensional assay            <NA>     transcriptomic                  <NA>      single-cell rna-seq           <NA>       Perturb-seq       <NA>                      <NA>  10x Genomics Single Cell 3-prime                   <NA>       Illumina HiSeq 4000                   <NA>        barcode sequencing               <NA>            CellRanger                 <NA>                  MAGeCK                 <NA>                <NA>                 GRCh37  [{"dataset_accession": "GSM2406677", "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2406681", "dataset_description": "Barcode, cell identities, raw gene expression matrix", "dataset_file_name": "GSM2406677_10X010"}, {"dataset_accession": "GSM2406677_10X005", "dataset_uri": "https://zenodo.org/records/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad", "dataset_description": "Processed .h5ad file", "dataset_file_name": "AdamsonWeissman2016_GSM2406681_10X010.h5ad"}]     CC BY 4.0  SWO:1000065
2  adamson_2016_upr_perturb_seq         3  AAACATACTTCCCG  CRISPR screen        <NA>                  <NA>    SEC61A1_pDS031    chr3:128051641-128071705;1                           3                                     3                        1       ENSG00000058262                 SEC61A1           protein_coding   GCTGTGCAGTGGAACGCGCT                 CRISPRi                 <NA>  P0DT0H0M0S            <NA>         <NA>                <NA>                 <NA>          cell_line            <NA>  Homo sapiens        blood  UBERON:0000178     lymphoblast   CL:0017005      K 562 cell  CLO:0007050    female   <NA>                     adult                   <NA>  chronic myelogenous leukemia, BCR-ABL1 positive  MONDO:0011996  A Multiplexed Single-Cell CRISPR Screening Platform Enables Systematic Dissection of the Unfolded Protein Response  https://doi.org/10.1016/j.cell.2016.11.048        2016  Britt Adamson  Jonathan Weissman  63000 chronic myeloid leukemia (K562) cells transfected with a UPR sensor gene-targeting gRNAs.  Perturb-seq was applied to a small CRISPRi library of 91 sgRNAs targeting UPR genes in K562 cells.                          91                       62623                EFO:0022868                    endogenous                  EFO:0022895                      dCas9-KRAB                      <NA>      retrovirus transduction                       <NA>       lentivirus transduction                        <NA>       random locus integration                         <NA>        random locus integration                         <NA>  constitutive transgene expression                          <NA>  constitutive transgene expression       custom        <NA>              <NA>               pooled             <NA>             focused                         <NA>                      inhibition             Weissman                             3                        1                  91                    <NA>                      <NA>       high-dimensional assay            <NA>     transcriptomic                  <NA>      single-cell rna-seq           <NA>       Perturb-seq       <NA>                      <NA>  10x Genomics Single Cell 3-prime                   <NA>       Illumina HiSeq 4000                   <NA>        barcode sequencing               <NA>            CellRanger                 <NA>                  MAGeCK                 <NA>                <NA>                 GRCh37  [{"dataset_accession": "GSM2406677", "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2406681", "dataset_description": "Barcode, cell identities, raw gene expression matrix", "dataset_file_name": "GSM2406677_10X010"}, {"dataset_accession": "GSM2406677_10X005", "dataset_uri": "https://zenodo.org/records/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad", "dataset_description": "Processed .h5ad file", "dataset_file_name": "AdamsonWeissman2016_GSM2406681_10X010.h5ad"}]     CC BY 4.0  SWO:1000065
3  adamson_2016_upr_perturb_seq         4  AAACATTGAAACAG  CRISPR screen        <NA>                  <NA>     EIF2B4_pDS491     chr2:27363420-27370400;-1                           2                                     2                        1       ENSG00000115211                  EIF2B4           protein_coding   GCTGAGGGCGATGGCTGCTG                 CRISPRi                 <NA>  P0DT0H0M0S            <NA>         <NA>                <NA>                 <NA>          cell_line            <NA>  Homo sapiens        blood  UBERON:0000178     lymphoblast   CL:0017005      K 562 cell  CLO:0007050    female   <NA>                     adult                   <NA>  chronic myelogenous leukemia, BCR-ABL1 positive  MONDO:0011996  A Multiplexed Single-Cell CRISPR Screening Platform Enables Systematic Dissection of the Unfolded Protein Response  https://doi.org/10.1016/j.cell.2016.11.048        2016  Britt Adamson  Jonathan Weissman  63000 chronic myeloid leukemia (K562) cells transfected with a UPR sensor gene-targeting gRNAs.  Perturb-seq was applied to a small CRISPRi library of 91 sgRNAs targeting UPR genes in K562 cells.                          91                       62623                EFO:0022868                    endogenous                  EFO:0022895                      dCas9-KRAB                      <NA>      retrovirus transduction                       <NA>       lentivirus transduction                        <NA>       random locus integration                         <NA>        random locus integration                         <NA>  constitutive transgene expression                          <NA>  constitutive transgene expression       custom        <NA>              <NA>               pooled             <NA>             focused                         <NA>                      inhibition             Weissman                             3                        1                  91                    <NA>                      <NA>       high-dimensional assay            <NA>     transcriptomic                  <NA>      single-cell rna-seq           <NA>       Perturb-seq       <NA>                      <NA>  10x Genomics Single Cell 3-prime                   <NA>       Illumina HiSeq 4000                   <NA>        barcode sequencing               <NA>            CellRanger                 <NA>                  MAGeCK                 <NA>                <NA>                 GRCh37  [{"dataset_accession": "GSM2406677", "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2406681", "dataset_description": "Barcode, cell identities, raw gene expression matrix", "dataset_file_name": "GSM2406677_10X010"}, {"dataset_accession": "GSM2406677_10X005", "dataset_uri": "https://zenodo.org/records/7041849/files/AdamsonWeissman2016_GSM2406681_10X010.h5ad", "dataset_description": "Processed .h5ad file", "dataset_file_name": "AdamsonWeissman2016_GSM2406681_10X010.h5ad"}]     CC BY 4.0  SWO:1000065

,dataset_id,sample_id,cell_barcode,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,adamson_2016_upr_perturb_seq,1,AAACATACAAGATG,CRISPR screen,<NA>,<NA>,63(mod)_pBA580,control_nontargeting,control_nontargeting,0,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
1,adamson_2016_upr_perturb_seq,2,AAACATACACCTAG,CRISPR screen,<NA>,<NA>,OST4_pDS353,chr2:27070470-27071685;-1,2,2,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
2,adamson_2016_upr_perturb_seq,3,AAACATACTTCCCG,CRISPR screen,<NA>,<NA>,SEC61A1_pDS031,chr3:128051641-128071705;1,3,3,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
3,adamson_2016_upr_perturb_seq,4,AAACATTGAAACAG,CRISPR screen,<NA>,<NA>,EIF2B4_pDS491,chr2:27363420-27370400;-1,2,2,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
4,adamson_2016_upr_perturb_seq,5,AAACATTGCAGCTA,CRISPR screen,<NA>,<NA>,SRPR_pDS482,chr11:126262912-126269144;-1,11,11,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62618,adamson_2016_upr_perturb_seq,62619,TTTGCATGCTTTAC,CRISPR screen,<NA>,<NA>,STT3A_pDS011,chr11:125591712-125625215;1,11,11,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
62619,adamson_2016_upr_perturb_seq,62620,TTTGCATGGAGGAC,CRISPR screen,<NA>,<NA>,ARHGAP22_pDS458,chr10:48446036-48656265;-1,10,10,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
62620,adamson_2016_upr_perturb_seq,62621,TTTGCATGTAGAGA,CRISPR screen,<NA>,<NA>,63(mod)_pBA580,control_nontargeting,control_nontargeting,0,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
62621,adamson_2016_upr_perturb_seq,62622,TTTGCATGTCAAGC,CRISPR screen,<NA>,<NA>,KCTD16_pDS096,chr5:144170873-144485686;1,5,5,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065
62622,adamson_2016_upr_perturb_seq,62623,TTTGCATGTGGAGG,CRISPR screen,<NA>,<NA>,SAMM50_pDS156,chr22:43955399-44010531;1,22,22,...,<NA>,CellRanger,<NA>,MAGeCK,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""GSM2406677"", ""dataset_...",CC BY 4.0,SWO:1000065

# VAR slot curation

### Standardise genes

In [30]:
cur_data.show_var()

Variable data:
DataFrame shape: (32738, 3)
--------------------------------------------------
                   ensembl_id  ncounts  ncells
gene_symbol
MIR1302-10    ENSG00000243485     11.0      11
FAM138A       ENSG00000237613      0.0       0
OR4F5         ENSG00000186092      0.0       0
RP11-34P13.7  ENSG00000238009      0.0       0
RP11-34P13.8  ENSG00000239945     43.0      43
...                       ...      ...     ...
AC145205.1    ENSG00000215635      0.0       0
BAGE5         ENSG00000268590      0.0       0
CU459201.1    ENSG00000251180      0.0       0
AC002321.2    ENSG00000215616      0.0       0
AC002321.1    ENSG00000215611      0.0       0

[32738 rows x 3 columns]
--------------------------------------------------

In [31]:
cur_data.standardize_genes(
    slot="var",
    input_column="ensembl_id",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

2026-04-28 11:17:54,895 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rest.ensembl.org:443

Missing Ensembl IDs: ['ENSG00000163113', 'ENSG00000225070', 'ENSG00000261470', 'ENSG00000242687', 'ENSG00000268217', 'ENSG00000227468', 'ENSG00000260951', 'ENSG00000215642', 'ENSG00000228561', 'ENSG00000243012', 'ENSG00000255160', 'ENSG00000270168', 'ENSG00000242924', 'ENSG00000270949', 'ENSG00000227021', 'ENSG00000231054', 'ENSG00000260982', 'ENSG00000225085', 'ENSG00000273266', 'ENSG00000272971', 'ENSG00000240355', 'ENSG00000171282', 'ENSG00000269402', 'ENSG00000165390', 'ENSG00000250174', 'ENSG00000272675', 'ENSG00000267531', 'ENSG00000269554', 'ENSG00000254148', 'ENSG00000260071', 'ENSG00000255318', 'ENSG00000254427', 'ENSG00000235475', 'ENSG00000213865', 'ENSG00000237461', 'ENSG00000255208', 'ENSG00000254998', 'ENSG00000214871', 'ENSG00000267906', 'ENSG00000229481', 'ENSG00000215764', 'ENSG00000269866', 'ENSG00000272524', 'ENSG00000272658', 'ENSG00000258268', 'ENSG00000198750', 'ENSG00000268397', 'ENSG00000256892', 'ENSG00000206176', 'ENSG00000233798', 'ENSG00000268046', 'ENSG00000269290', 'ENSG00000228255', 'ENSG00000265091', 'ENSG00000235822', 'ENSG00000155282', 'ENSG00000248478', 'ENSG00000268730', 'ENSG00000221995', 'ENSG00000258946', 'ENSG00000203886', 'ENSG00000254082', 'ENSG00000224819', 'ENSG00000268519', 'ENSG00000251314', 'ENSG00000267279', 'ENSG00000267380', 'ENSG00000270160', 'ENSG00000006075', 'ENSG00000254286', 'ENSG00000223907', 'ENSG00000240440', 'ENSG00000232498', 'ENSG00000229628', 'ENSG00000180081', 'ENSG00000269282', 'ENSG00000271649', 'ENSG00000234810', 'ENSG00000254364', 'ENSG00000269679', 'ENSG00000273366', 'ENSG00000174093', 'ENSG00000267848', 'ENSG00000261445', 'ENSG00000228682', 'ENSG00000256923', 'ENSG00000255740', 'ENSG00000249335', 'ENSG00000253839', 'ENSG00000233517', 'ENSG00000253891', 'ENSG00000220023', 'ENSG00000264072', 'ENSG00000116883', 'ENSG00000243944', 'ENSG00000226377', 'ENSG00000272369', 'ENSG00000238091', 'ENSG00000271911', 'ENSG00000230055', 'ENSG00000181689', 'ENSG00000204513', 'ENSG00000267683', 'ENSG00000263975', 'ENSG00000259606', 'ENSG00000261273', 'ENSG00000234449', 'ENSG00000236166', 'ENSG00000267981', 'ENSG00000267988', 'ENSG00000262890', 'ENSG00000233342', 'ENSG00000204377', 'ENSG00000240240', 'ENSG00000272070', 'ENSG00000256530', 'ENSG00000161570', 'ENSG00000272644', 'ENSG00000235209', 'ENSG00000242631', 'ENSG00000183086', 'ENSG00000230156', 'ENSG00000235398', 'ENSG00000130201', 'ENSG00000225597', 'ENSG00000233074', 'ENSG00000139656', 'ENSG00000268000', 'ENSG00000236008', 'ENSG00000256725', 'ENSG00000260396', 'ENSG00000237291', 'ENSG00000248986', 'ENSG00000272102', 'ENSG00000238106', 'ENSG00000257877', 'ENSG00000257164', 'ENSG00000230058', 'ENSG00000272225', 'ENSG00000272993', 'ENSG00000272341', 'ENSG00000224638', 'ENSG00000242185', 'ENSG00000268355', 'ENSG00000233840', 'ENSG00000228704', 'ENSG00000236262', 'ENSG00000258808', 'ENSG00000251532', 'ENSG00000268781', 'ENSG00000250269', 'ENSG00000271788', 'ENSG00000224867', 'ENSG00000269339', 'ENSG00000227192', 'ENSG00000259820', 'ENSG00000138293', 'ENSG00000181013', 'ENSG00000224218', 'ENSG00000235733', 'ENSG00000235999', 'ENSG00000230998', 'ENSG00000225278', 'ENSG00000230610', 'ENSG00000233094', 'ENSG00000230381', 'ENSG00000267667', 'ENSG00000248753', 'ENSG00000266927', 'ENSG00000137259', 'ENSG00000249643', 'ENSG00000244522', 'ENSG00000229964', 'ENSG00000268861', 'ENSG00000237658', 'ENSG00000270067', 'ENSG00000226524', 'ENSG00000268662', 'ENSG00000128802', 'ENSG00000258927', 'ENSG00000236082', 'ENSG00000196355', 'ENSG00000215067', 'ENSG00000254120', 'ENSG00000239265', 'ENSG00000231997', 'ENSG00000230493', 'ENSG00000268091', 'ENSG00000239446', 'ENSG00000215700', 'ENSG00000269979', 'ENSG00000268050', 'ENSG00000253369', 'ENSG00000257654', 'ENSG00000251554', 'ENSG00000257742', 'ENSG00000249677', 'ENSG00000253872', 'ENSG00000230939', 'ENSG00000017373', 'ENSG00000273481', 'ENSG00000214921', 'ENSG00000231616', 'ENSG00000224303', 'ENSG00000256763', 'ENSG00000224201', 'ENSG00000227925', 'ENSG00000267020', 'ENSG00000215298', 'ENSG00000272040', 'ENSG00000268948', 'ENSG00000271751', 'ENSG00000269215', 'ENSG00000225667', 'ENSG00000242284', 'ENSG00000175393', 'ENSG00000251506', 'ENSG00000272521', 'ENSG00000233501', 'ENSG00000267037', 'ENSG00000217258', 'ENSG00000270009', 'ENSG00000267935', 'ENSG00000196226', 'ENSG00000168242', 'ENSG00000234298', 'ENSG00000258297', 'ENSG00000233255', 'ENSG00000214645', 'ENSG00000233143', 'ENSG00000268332', 'ENSG00000273081', 'ENSG00000271815', 'ENSG00000223795', 'ENSG00000269640', 'ENSG00000233988', 'ENSG00000264868', 'ENSG00000232018', 'ENSG00000253426', 'ENSG00000268735', 'ENSG00000181464', 'ENSG00000235704', 'ENSG00000231774', 'ENSG00000261521', 'ENSG00000260052', 'ENSG00000262668', 'ENSG00000269358', 'ENSG00000256321', 'ENSG00000231816', 'ENSG00000172653', 'ENSG00000230836', 'ENSG00000250284', 'ENSG00000244260', 'ENSG00000262089', 'ENSG00000264080', 'ENSG00000270265', 'ENSG00000268155', 'ENSG00000173876', 'ENSG00000230565', 'ENSG00000269267', 'ENSG00000259616', 'ENSG00000272955', 'ENSG00000214314', 'ENSG00000198518', 'ENSG00000249731', 'ENSG00000223562', 'ENSG00000272389', 'ENSG00000255145', 'ENSG00000240875', 'ENSG00000225135', 'ENSG00000204508', 'ENSG00000268791', 'ENSG00000232784', 'ENSG00000133149', 'ENSG00000170215', 'ENSG00000235665', 'ENSG00000269410', 'ENSG00000253459', 'ENSG00000235852', 'ENSG00000135213', 'ENSG00000268328', 'ENSG00000198307', 'ENSG00000255945', 'ENSG00000264443', 'ENSG00000183130', 'ENSG00000265964', 'ENSG00000267950', 'ENSG00000235504', 'ENSG00000228798', 'ENSG00000237374', 'ENSG00000261135', 'ENSG00000272286', 'ENSG00000268457', 'ENSG00000271769', 'ENSG00000168260', 'ENSG00000273009', 'ENSG00000233005', 'ENSG00000231518', 'ENSG00000182912', 'ENSG00000231145', 'ENSG00000237721', 'ENSG00000255651', 'ENSG00000267070', 'ENSG00000228334', 'ENSG00000226894', 'ENSG00000267381', 'ENSG00000234245', 'ENSG00000230641', 'ENSG00000187145', 'ENSG00000185044', 'ENSG00000269605', 'ENSG00000258714', 'ENSG00000184886', 'ENSG00000262395', 'ENSG00000249381', 'ENSG00000250588', 'ENSG00000214306', 'ENSG00000260506', 'ENSG00000261833', 'ENSG00000249269', 'ENSG00000251144', 'ENSG00000226362', 'ENSG00000253484', 'ENSG00000197445', 'ENSG00000269804', 'ENSG00000214325', 'ENSG00000227603', 'ENSG00000233137', 'ENSG00000273307', 'ENSG00000183653', 'ENSG00000182611', 'ENSG00000260359', 'ENSG00000231734', 'ENSG00000239801', 'ENSG00000254318', 'ENSG00000259549', 'ENSG00000230600', 'ENSG00000273373', 'ENSG00000181935', 'ENSG00000224441', 'ENSG00000196644', 'ENSG00000231632', 'ENSG00000267839', 'ENSG00000228353', 'ENSG00000198946', 'ENSG00000262558', 'ENSG00000269999', 'ENSG00000272796', 'ENSG00000241978', 'ENSG00000272709', 'ENSG00000232348', 'ENSG00000250777', 'ENSG00000268192', 'ENSG00000072444', 'ENSG00000269831', 'ENSG00000224235', 'ENSG00000260095', 'ENSG00000108292', 'ENSG00000261589', 'ENSG00000233863', 'ENSG00000241180', 'ENSG00000240224', 'ENSG00000260065', 'ENSG00000251044', 'ENSG00000230177', 'ENSG00000213240', 'ENSG00000268788', 'ENSG00000229463', 'ENSG00000236524', 'ENSG00000229454', 'ENSG00000236947', 'ENSG00000130723', 'ENSG00000215611', 'ENSG00000260487', 'ENSG00000108272', 'ENSG00000269871', 'ENSG00000255854', 'ENSG00000270147', 'ENSG00000232698', 'ENSG00000240401', 'ENSG00000267588', 'ENSG00000268413', 'ENSG00000108294', 'ENSG00000255863', 'ENSG00000230633', 'ENSG00000259243', 'ENSG00000237422', 'ENSG00000242384', 'ENSG00000251331', 'ENSG00000249184', 'ENSG00000204844', 'ENSG00000256715', 'ENSG00000233022', 'ENSG00000132139', 'ENSG00000184040', 'ENSG00000259063', 'ENSG00000227164', 'ENSG00000226849', 'ENSG00000258216', 'ENSG00000232224', 'ENSG00000259747', 'ENSG00000244268', 'ENSG00000268280', 'ENSG00000273097', 'ENSG00000253350', 'ENSG00000226785', 'ENSG00000265780', 'ENSG00000257613', 'ENSG00000256101', 'ENSG00000250232', 'ENSG00000260470', 'ENSG00000248359', 'ENSG00000258612', 'ENSG00000270030', 'ENSG00000266935', 'ENSG00000272177', 'ENSG00000270604', 'ENSG00000241990', 'ENSG00000229583', 'ENSG00000260793', 'ENSG00000272005', 'ENSG00000228214', 'ENSG00000272515', 'ENSG00000237726', 'ENSG00000257918', 'ENSG00000224532', 'ENSG00000264790', 'ENSG00000267668', 'ENSG00000272216', 'ENSG00000132130', 'ENSG00000233878', 'ENSG00000258642', 'ENSG00000175898', 'ENSG00000233368', 'ENSG00000249365', 'ENSG00000258088', 'ENSG00000130489', 'ENSG00000269415', 'ENSG00000257962', 'ENSG00000259799', 'ENSG00000253929', 'ENSG00000258882', 'ENSG00000215394', 'ENSG00000271970', 'ENSG00000183657', 'ENSG00000230850', 'ENSG00000112096', 'ENSG00000196936', 'ENSG00000267812', 'ENSG00000205147', 'ENSG00000214109', 'ENSG00000269746', 'ENSG00000250411', 'ENSG00000270237', 'ENSG00000197263', 'ENSG00000249069', 'ENSG00000230906', 'ENSG00000108264', 'ENSG00000237021', 'ENSG00000241732', 'ENSG00000214597', 'ENSG00000272233', 'ENSG00000259806', 'ENSG00000267880', 'ENSG00000244247', 'ENSG00000236249', 'ENSG00000132832', 'ENSG00000263508', 'ENSG00000226786', 'ENSG00000272066', 'ENSG00000224460', 'ENSG00000268387', 'ENSG00000261428', 'ENSG00000268352', 'ENSG00000182242', 'ENSG00000263214', 'ENSG00000261720', 'ENSG00000269047', 'ENSG00000214841', 'ENSG00000256373', 'ENSG00000272761', 'ENSG00000272448', 'ENSG00000268965', 'ENSG00000268953', 'ENSG00000231217', 'ENSG00000227185', 'ENSG00000223469', 'ENSG00000243452', 'ENSG00000246331', 'ENSG00000214970', 'ENSG00000259762', 'ENSG00000234248', 'ENSG00000269928', 'ENSG00000269391', 'ENSG00000247810', 'ENSG00000268265', 'ENSG00000268822', 'ENSG00000267913', 'ENSG00000250530', 'ENSG00000257277', 'ENSG00000257088', 'ENSG00000205047', 'ENSG00000264469', 'ENSG00000235815', 'ENSG00000273488', 'ENSG00000272520', 'ENSG00000263182', 'ENSG00000231242', 'ENSG00000260923', 'ENSG00000225742', 'ENSG00000269963', 'ENSG00000224226', 'ENSG00000255823', 'ENSG00000244567', 'ENSG00000272403', 'ENSG00000204365', 'ENSG00000267918', 'ENSG00000268313', 'ENSG00000230857', 'ENSG00000212998', 'ENSG00000257999', 'ENSG00000273116', 'ENSG00000157828', 'ENSG00000269510', 'ENSG00000260929', 'ENSG00000231255', 'ENSG00000226381', 'ENSG00000231435', 'ENSG00000272792', 'ENSG00000259641', 'ENSG00000148828', 'ENSG00000269753', 'ENSG00000240510', 'ENSG00000244252', 'ENSG00000239498', 'ENSG00000267963', 'ENSG00000273065', 'ENSG00000212857', 'ENSG00000230567', 'ENSG00000268024', 'ENSG00000254140', 'ENSG00000271308', 'ENSG00000214844', 'ENSG00000232753', 'ENSG00000269185', 'ENSG00000255546', 'ENSG00000235795', 'ENSG00000122718', 'ENSG00000243300', 'ENSG00000255944', 'ENSG00000268716', 'ENSG00000213494', 'ENSG00000171129', 'ENSG00000273389', 'ENSG00000266614', 'ENSG00000268470', 'ENSG00000197463', 'ENSG00000259942', 'ENSG00000267118', 'ENSG00000273181', 'ENSG00000261462', 'ENSG00000222022', 'ENSG00000236856', 'ENSG00000233788', 'ENSG00000188424', 'ENSG00000173088', 'ENSG00000247270', 'ENSG00000150165', 'ENSG00000267047', 'ENSG00000250670', 'ENSG00000233404', 'ENSG00000233895', 'ENSG00000268085', 'ENSG00000197697', 'ENSG00000205148', 'ENSG00000270109', 'ENSG00000215405', 'ENSG00000254967', 'ENSG00000270028', 'ENSG00000269998', 'ENSG00000273170', 'ENSG00000260787', 'ENSG00000212768', 'ENSG00000237534', 'ENSG00000268126', 'ENSG00000185254', 'ENSG00000270041', 'ENSG00000244063', 'ENSG00000124693', 'ENSG00000249430', 'ENSG00000267954', 'ENSG00000241317', 'ENSG00000238033', 'ENSG00000232417', 'ENSG00000273466', 'ENSG00000269515', 'ENSG00000242013', 'ENSG00000161326', 'ENSG00000198327', 'ENSG00000256001', 'ENSG00000254757', 'ENSG00000237404', 'ENSG00000228439', 'ENSG00000270810', 'ENSG00000269728', 'ENSG00000253844', 'ENSG00000262031', 'ENSG00000230880', 'ENSG00000102080', 'ENSG00000141140', 'ENSG00000260760', 'ENSG00000270173', 'ENSG00000186117', 'ENSG00000248371', 'ENSG00000269966', 'ENSG00000248467', 'ENSG00000260548', 'ENSG00000251654', 'ENSG00000234007', 'ENSG00000258785', 'ENSG00000269690', 'ENSG00000239665', 'ENSG00000227112', 'ENSG00000258914', 'ENSG00000268898', 'ENSG00000268656', 'ENSG00000186807', 'ENSG00000269531', 'ENSG00000233415', 'ENSG00000258919', 'ENSG00000161573', 'ENSG00000263198', 'ENSG00000121848', 'ENSG00000250237', 'ENSG00000272940', 'ENSG00000248828', 'ENSG00000258921', 'ENSG00000228512', 'ENSG00000198444', 'ENSG00000253197', 'ENSG00000226747', 'ENSG00000215462', 'ENSG00000203863', 'ENSG00000264263', 'ENSG00000269049', 'ENSG00000263388', 'ENSG00000271020', 'ENSG00000162290', 'ENSG00000253264', 'ENSG00000266045', 'ENSG00000268856', 'ENSG00000265114', 'ENSG00000225353', 'ENSG00000269601', 'ENSG00000262194', 'ENSG00000268164', 'ENSG00000241481', 'ENSG00000270113', 'ENSG00000254353', 'ENSG00000236948', 'ENSG00000269936', 'ENSG00000203849', 'ENSG00000263553', 'ENSG00000228434', 'ENSG00000186275', 'ENSG00000258918', 'ENSG00000269417', 'ENSG00000269909', 'ENSG00000214854', 'ENSG00000262758', 'ENSG00000266958', 'ENSG00000233889', 'ENSG00000272030', 'ENSG00000259209', 'ENSG00000268341', 'ENSG00000234407', 'ENSG00000231121', 'ENSG00000260006', 'ENSG00000237133', 'ENSG00000249708', 'ENSG00000221961', 'ENSG00000250418', 'ENSG00000253701', 'ENSG00000163386', 'ENSG00000235037', 'ENSG00000270163', 'ENSG00000267884', 'ENSG00000266002', 'ENSG00000253371', 'ENSG00000250061', 'ENSG00000263136', 'ENSG00000241636', 'ENSG00000267747', 'ENSG00000268333', 'ENSG00000234214', 'ENSG00000198106', 'ENSG00000257194', 'ENSG00000269751', 'ENSG00000197851', 'ENSG00000268111', 'ENSG00000234734', 'ENSG00000258664', 'ENSG00000198366', 'ENSG00000230525', 'ENSG00000254115', 'ENSG00000268028', 'ENSG00000171471', 'ENSG00000253584', 'ENSG00000250446', 'ENSG00000254199', 'ENSG00000259886', 'ENSG00000253766', 'ENSG00000266601', 'ENSG00000204683', 'ENSG00000239815', 'ENSG00000171484', 'ENSG00000272827', 'ENSG00000272482', 'ENSG00000258276', 'ENSG00000233438', 'ENSG00000240907', 'ENSG00000232941', 'ENSG00000255599', 'ENSG00000244349', 'ENSG00000255257', 'ENSG00000268602', 'ENSG00000223821', 'ENSG00000259423', 'ENSG00000269920', 'ENSG00000135847', 'ENSG00000272093', 'ENSG00000253379', 'ENSG00000258885', 'ENSG00000225640', 'ENSG00000214733', 'ENSG00000230090', 'ENSG00000241043', 'ENSG00000267581', 'ENSG00000253737', 'ENSG00000196326', 'ENSG00000271722', 'ENSG00000259159', 'ENSG00000198558', 'ENSG00000196374', 'ENSG00000271904', 'ENSG00000236938', 'ENSG00000267018', 'ENSG00000204119', 'ENSG00000205662', 'ENSG00000215527', 'ENSG00000270005', 'ENSG00000182646', 'ENSG00000261193', 'ENSG00000250948', 'ENSG00000272511', 'ENSG00000261737', 'ENSG00000271721', 'ENSG00000272962', 'ENSG00000227844', 'ENSG00000269766', 'ENSG00000124578', 'ENSG00000229352', 'ENSG00000272367', 'ENSG00000077809', 'ENSG00000225782', 'ENSG00000273486', 'ENSG00000230372', 'ENSG00000176274', 'ENSG00000204502', 'ENSG00000267012', 'ENSG00000261190', 'ENSG00000261712', 'ENSG00000235566', 'ENSG00000268923', 'ENSG00000006074', 'ENSG00000166748', 'ENSG00000258631', 'ENSG00000233376', 'ENSG00000259618', 'ENSG00000236501', 'ENSG00000243558', 'ENSG00000205081', 'ENSG00000204488', 'ENSG00000227637', 'ENSG00000214479', 'ENSG00000272218', 'ENSG00000233214', 'ENSG00000187456', 'ENSG00000270154', 'ENSG00000204495', 'ENSG00000254695', 'ENSG00000107623', 'ENSG00000244650', 'ENSG00000233193', 'ENSG00000233224', 'ENSG00000184258', 'ENSG00000259610', 'ENSG00000273281', 'ENSG00000226277', 'ENSG00000269279', 'ENSG00000215046', 'ENSG00000229746', 'ENSG00000237352', 'ENSG00000253640', 'ENSG00000108278', 'ENSG00000147382', 'ENSG00000225860', 'ENSG00000236451', 'ENSG00000272486', 'ENSG00000167970', 'ENSG00000143140', 'ENSG00000272444', 'ENSG00000272201', 'ENSG00000213132', 'ENSG00000269494', 'ENSG00000204775', 'ENSG00000231566', 'ENSG00000214986', 'ENSG00000249428', 'ENSG00000259279', 'ENSG00000236412', 'ENSG00000227895', 'ENSG00000232680', 'ENSG00000235117', 'ENSG00000204957', 'ENSG00000236716', 'ENSG00000234083', 'ENSG00000229191', 'ENSG00000260869', 'ENSG00000267730', 'ENSG00000272565', 'ENSG00000244214', 'ENSG00000265717', 'ENSG00000152042', 'ENSG00000152726', 'ENSG00000241770', 'ENSG00000255103', 'ENSG00000257715', 'ENSG00000236886', 'ENSG00000260637', 'ENSG00000266490', 'ENSG00000273283', 'ENSG00000235477', 'ENSG00000224167', 'ENSG00000254010', 'ENSG00000268640', 'ENSG00000272016', 'ENSG00000228865', 'ENSG00000266949', 'ENSG00000246448', 'ENSG00000244545', 'ENSG00000214732', 'ENSG00000236016', 'ENSG00000228216', 'ENSG00000168787', 'ENSG00000129277', 'ENSG00000090920', 'ENSG00000234405', 'ENSG00000271167', 'ENSG00000269117', 'ENSG00000188474', 'ENSG00000232336', 'ENSG00000262222', 'ENSG00000255394', 'ENSG00000231465', 'ENSG00000147402', 'ENSG00000272268', 'ENSG00000268708', 'ENSG00000253931', 'ENSG00000269923', 'ENSG00000182230', 'ENSG00000170590', 'ENSG00000249091', 'ENSG00000271090', 'ENSG00000229974', 'ENSG00000256342', 'ENSG00000228614', 'ENSG00000271738', 'ENSG00000259760', 'ENSG00000265629', 'ENSG00000243135', 'ENSG00000267616', 'ENSG00000261685', 'ENSG00000177764', 'ENSG00000220032', 'ENSG00000270172', 'ENSG00000269464', 'ENSG00000160844', 'ENSG00000270016', 'ENSG00000241528', 'ENSG00000224037', 'ENSG00000266411', 'ENSG00000268211', 'ENSG00000237069', 'ENSG00000241912', 'ENSG00000234306', 'ENSG00000203520', 'ENSG00000196987', 'ENSG00000138294', 'ENSG00000122497', 'ENSG00000254731', 'ENSG00000237543', 'ENSG00000267596', 'ENSG00000197681', 'ENSG00000256686', 'ENSG00000155640', 'ENSG00000273119', 'ENSG00000183103', 'ENSG00000248240', 'ENSG00000249988', 'ENSG00000267958', 'ENSG00000268553', 'ENSG00000197910', 'ENSG00000272065', 'ENSG00000230394', 'ENSG00000253774', 'ENSG00000228858', 'ENSG00000268657', 'ENSG00000266118', 'ENSG00000230410', 'ENSG00000230427', 'ENSG00000256542', 'ENSG00000260183', 'ENSG00000254267', 'ENSG00000255354', 'ENSG00000230205', 'ENSG00000237184', 'ENSG00000237359', 'ENSG00000255098', 'ENSG00000212999', 'ENSG00000260687', 'ENSG00000264433', 'ENSG00000271593', 'ENSG00000185945', 'ENSG00000205775', 'ENSG00000268344', 'ENSG00000269305', 'ENSG00000237262', 'ENSG00000254281', 'ENSG00000226155', 'ENSG00000268549', 'ENSG00000248461', 'ENSG00000234035', 'ENSG00000197723', 'ENSG00000229387', 'ENSG00000258131', 'ENSG00000197502', 'ENSG00000242021', 'ENSG00000268537', 'ENSG00000272053', 'ENSG00000259972', 'ENSG00000184348', 'ENSG00000267893', 'ENSG00000269630', 'ENSG00000270599', 'ENSG00000253983', 'ENSG00000225554', 'ENSG00000234113', 'ENSG00000264660', 'ENSG00000258302', 'ENSG00000269781', 'ENSG00000269591', 'ENSG00000259730', 'ENSG00000233207', 'ENSG00000254420', 'ENSG00000261797', 'ENSG00000237998', 'ENSG00000269686', 'ENSG00000237697', 'ENSG00000241475', 'ENSG00000264067', 'ENSG00000253139', 'ENSG00000266956', 'ENSG00000253985', 'ENSG00000272579', 'ENSG00000258395', 'ENSG00000259855', 'ENSG00000270114', 'ENSG00000267785', 'ENSG00000255989', 'ENSG00000231173', 'ENSG00000228358', 'ENSG00000271043', 'ENSG00000255518', 'ENSG00000268846', 'ENSG00000223401', 'ENSG00000204788', 'ENSG00000250078', 'ENSG00000235934', 'ENSG00000269962', 'ENSG00000182368', 'ENSG00000231599', 'ENSG00000273439', 'ENSG00000256927', 'ENSG00000197846', 'ENSG00000204375', 'ENSG00000231838', 'ENSG00000148362', 'ENSG00000203815', 'ENSG00000268509', 'ENSG00000198082', 'ENSG00000215635', 'ENSG00000227920', 'ENSG00000228951', 'ENSG00000255767', 'ENSG00000228273', 'ENSG00000231877', 'ENSG00000269393', 'ENSG00000259455', 'ENSG00000259839', 'ENSG00000269496', 'ENSG00000188971', 'ENSG00000229458', 'ENSG00000270898', 'ENSG00000182109', 'ENSG00000267896', 'ENSG00000249837', 'ENSG00000269363', 'ENSG00000260837', 'ENSG00000229881', 'ENSG00000272370', 'ENSG00000261044', 'ENSG00000257061', 'ENSG00000260432', 'ENSG00000259594', 'ENSG00000258386', 'ENSG00000234252', 'ENSG00000231429', 'ENSG00000196661', 'ENSG00000244291', 'ENSG00000257040', 'ENSG00000272981', 'ENSG00000249463', 'ENSG00000269071', 'ENSG00000260655', 'ENSG00000224849', 'ENSG00000269808', 'ENSG00000253444', 'ENSG00000254039', 'ENSG00000226852', 'ENSG00000234540', 'ENSG00000250511', 'ENSG00000254744', 'ENSG00000260591', 'ENSG00000182217', 'ENSG00000236392', 'ENSG00000250410', 'ENSG00000229874', 'ENSG00000231595', 'ENSG00000268556', 'ENSG00000238068', 'ENSG0000

2026-04-28 11:19:03,558 DEBUG urllib3.connectionpool: https://rest.ensembl.org:443 "POST /archive/id HTTP/1.1" 200 94247
2026-04-28 11:19:03,564 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rest.ensembl.org:443

Processing IDs 501 to 1000...

2026-04-28 11:20:15,769 DEBUG urllib3.connectionpool: https://rest.ensembl.org:443 "POST /archive/id HTTP/1.1" 200 94715
2026-04-28 11:20:15,778 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rest.ensembl.org:443

Processing IDs 1001 to 1500...

2026-04-28 11:21:06,568 DEBUG urllib3.connectionpool: https://rest.ensembl.org:443 "POST /archive/id HTTP/1.1" 200 93868
2026-04-28 11:21:06,573 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rest.ensembl.org:443

Processing IDs 1501 to 2000...

2026-04-28 11:21:59,688 DEBUG urllib3.connectionpool: https://rest.ensembl.org:443 "POST /archive/id HTTP/1.1" 200 94315
2026-04-28 11:21:59,697 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rest.ensembl.org:443

Processing IDs 2001 to 2500...

2026-04-28 11:22:28,178 DEBUG urllib3.connectionpool: https://rest.ensembl.org:443 "POST /archive/id HTTP/1.1" 200 95135
2026-04-28 11:22:28,186 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rest.ensembl.org:443

Processing IDs 2501 to 2577...

2026-04-28 11:22:43,853 DEBUG urllib3.connectionpool: https://rest.ensembl.org:443 "POST /archive/id HTTP/1.1" 200 14286

Fetched latest Ensembl IDs: {'ENSG00000163113': nan, 'ENSG00000225070': nan, 'ENSG00000261470': 'ENSG00000261749', 'ENSG00000242687': nan, 'ENSG00000268217': nan, 'ENSG00000227468': nan, 'ENSG00000260951': 'ENSG00000233824', 'ENSG00000215642': nan, 'ENSG00000228561': 'ENSG00000228221', 'ENSG00000243012': nan, 'ENSG00000255160': 'ENSG00000255308', 'ENSG00000270168': nan, 'ENSG00000242924': nan, 'ENSG00000270949': nan, 'ENSG00000227021': 'ENSG00000223874', 'ENSG00000231054': nan, 'ENSG00000260982': nan, 'ENSG00000225085': 'ENSG00000290551', 'ENSG00000273266': nan, 'ENSG00000272971': 'ENSG00000229953', 'ENSG00000240355': 'ENSG00000230680', 'ENSG00000171282': nan, 'ENSG00000269402': nan, 'ENSG00000165390': 'ENSG00000265190', 'ENSG00000250174': 'ENSG00000239523', 'ENSG00000272675': nan, 'ENSG00000267531': nan, 'ENSG00000269554': nan, 'ENSG00000254148': nan, 'ENSG00000260071': 'ENSG00000261617', 'ENSG00000255318': nan, 'ENSG00000254427': 'ENSG00000255267', 'ENSG00000235475': nan, 'ENSG00000213865': nan, 'ENSG00000237461': 'ENSG00000271086', 'ENSG00000255208': nan, 'ENSG00000254998': nan, 'ENSG00000214871': nan, 'ENSG00000267906': nan, 'ENSG00000229481': nan, 'ENSG00000215764': nan, 'ENSG00000269866': nan, 'ENSG00000272524': nan, 'ENSG00000272658': nan, 'ENSG00000258268': nan, 'ENSG00000198750': nan, 'ENSG00000268397': nan, 'ENSG00000256892': nan, 'ENSG00000206176': nan, 'ENSG00000233798': nan, 'ENSG00000268046': nan, 'ENSG00000269290': nan, 'ENSG00000228255': 'ENSG00000225233', 'ENSG00000265091': 'ENSG00000264575', 'ENSG00000235822': nan, 'ENSG00000155282': nan, 'ENSG00000248478': nan, 'ENSG00000268730': nan, 'ENSG00000221995': 'ENSG00000196535', 'ENSG00000258946': nan, 'ENSG00000203886': nan, 'ENSG00000254082': nan, 'ENSG00000224819': 'ENSG00000288902', 'ENSG00000268519': nan, 'ENSG00000251314': 'ENSG00000153113', 'ENSG00000267279': 'ENSG00000267175', 'ENSG00000267380': nan, 'ENSG00000270160': nan, 'ENSG00000006075': nan, 'ENSG00000254286': nan, 'ENSG00000223907': nan, 'ENSG00000240440': 'ENSG00000223725', 'ENSG00000232498': nan, 'ENSG00000229628': 'ENSG00000237471', 'ENSG00000180081': nan, 'ENSG00000269282': nan, 'ENSG00000271649': nan, 'ENSG00000234810': 'ENSG00000233079', 'ENSG00000254364': 'ENSG00000253666', 'ENSG00000269679': nan, 'ENSG00000273366': nan, 'ENSG00000174093': nan, 'ENSG00000267848': nan, 'ENSG00000261445': 'ENSG00000290413', 'ENSG00000228682': nan, 'ENSG00000256923': nan, 'ENSG00000255740': nan, 'ENSG00000249335': 'ENSG00000249352', 'ENSG00000253839': nan, 'ENSG00000233517': 'ENSG00000272568', 'ENSG00000253891': 'ENSG00000253535', 'ENSG00000220023': nan, 'ENSG00000264072': 'ENSG00000266604', 'ENSG00000116883': nan, 'ENSG00000243944': 'ENSG00000244541', 'ENSG00000226377': 'ENSG00000236377', 'ENSG00000272369': 'ENSG00000257261', 'ENSG00000238091': nan, 'ENSG00000271911': 'ENSG00000271727', 'ENSG00000230055': nan, 'ENSG00000181689': nan, 'ENSG00000204513': nan, 'ENSG00000267683': 'ENSG00000267339', 'ENSG00000263975': nan, 'ENSG00000259606': nan, 'ENSG00000261273': 'ENSG00000260420', 'ENSG00000234449': nan, 'ENSG00000236166': 'ENSG00000228495', 'ENSG00000267981': nan, 'ENSG00000267988': nan, 'ENSG00000262890': nan, 'ENSG00000233342': 'ENSG00000231863', 'ENSG00000204377': nan, 'ENSG00000240240': 'ENSG00000290718', 'ENSG00000272070': 'ENSG00000288095', 'ENSG00000256530': nan, 'ENSG00000161570': 'ENSG00000271503', 'ENSG00000272644': nan, 'ENSG00000235209': 'ENSG00000288106', 'ENSG00000242631': nan, 'ENSG00000183086': nan, 'ENSG00000230156': 'ENSG00000272274', 'ENSG00000235398': nan, 'ENSG00000130201': nan, 'ENSG00000225597': nan, 'ENSG00000233074': nan, 'ENSG00000139656': 'ENSG00000226519', 'ENSG00000268000': nan, 'ENSG00000236008': 'ENSG00000236790', 'ENSG00000256725': nan, 'ENSG00000260396': nan, 'ENSG00000237291': nan, 'ENSG00000248986': nan, 'ENSG00000272102': nan, 'ENSG00000238106': nan, 'ENSG00000257877': nan, 'ENSG00000257164': 'ENSG00000257114', 'ENSG00000230058': nan, 'ENSG00000272225': nan, 'ENSG00000272993': nan, 'ENSG00000272341': 'ENSG00000229931', 'ENSG00000224638': nan, 'ENSG00000242185': nan, 'ENSG00000268355': 'ENSG00000270164', 'ENSG00000233840': 'ENSG00000225263', 'ENSG00000228704': nan, 'ENSG00000236262': 'ENSG00000226627', 'ENSG00000258808': 'ENSG00000258537', 'ENSG00000251532': 'ENSG00000291079', 'ENSG00000268781': nan, 'ENSG00000250269': nan, 'ENSG00000271788': 'ENSG00000177738', 'ENSG00000224867': nan, 'ENSG00000269339': nan, 'ENSG00000227192': 'ENSG00000229017', 'ENSG00000259820': 'ENSG00000289405', 'ENSG00000138293': 'ENSG00000266412', 'ENSG00000181013': nan, 'ENSG00000224218': 'ENSG00000233860', 'ENSG00000235733': nan, 'ENSG00000235999': 'ENSG00000263590', 'ENSG00000230998': nan, 'ENSG00000225278': nan, 'ENSG00000230610': nan, 'ENSG00000233094': nan, 'ENSG00000230381': 'ENSG00000233154', 'ENSG00000267667': nan, 'ENSG00000248753': 'ENSG00000224186', 'ENSG00000266927': nan, 'ENSG00000137259': 'ENSG00000278677', 'ENSG00000249643': nan, 'ENSG00000244522': nan, 'ENSG00000229964': 'ENSG00000276407', 'ENSG00000268861': nan, 'ENSG00000237658': nan, 'ENSG00000270067': nan, 'ENSG00000226524': nan, 'ENSG00000268662': nan, 'ENSG00000128802': 'ENSG00000263761', 'ENSG00000258927': 'ENSG00000187621', 'ENSG00000236082': nan, 'ENSG00000196355': nan, 'ENSG00000215067': 'ENSG00000267532', 'ENSG00000254120': 'ENSG00000254119', 'ENSG00000239265': 'ENSG00000244265', 'ENSG00000231997': nan, 'ENSG00000230493': nan, 'ENSG00000268091': nan, 'ENSG00000239446': nan, 'ENSG00000215700': nan, 'ENSG00000269979': nan, 'ENSG00000268050': nan, 'ENSG00000253369': 'ENSG00000237807', 'ENSG00000257654': 'ENSG00000257883', 'ENSG00000251554': nan, 'ENSG00000257742': nan, 'ENSG00000249677': nan, 'ENSG00000253872': 'ENSG00000253773', 'ENSG00000230939': nan, 'ENSG00000017373': nan, 'ENSG00000273481': 'ENSG00000237976', 'ENSG00000214921': nan, 'ENSG00000231616': 'ENSG00000226877', 'ENSG00000224303': nan, 'ENSG00000256763': nan, 'ENSG00000224201': nan, 'ENSG00000227925': 'ENSG00000232679', 'ENSG00000267020': nan, 'ENSG00000215298': nan, 'ENSG00000272040': nan, 'ENSG00000268948': nan, 'ENSG00000271751': 'ENSG00000272186', 'ENSG00000269215': nan, 'ENSG00000225667': nan, 'ENSG00000242284': nan, 'ENSG00000175393': nan, 'ENSG00000251506': 'ENSG00000251426', 'ENSG00000272521': nan, 'ENSG00000233501': nan, 'ENSG00000267037': nan, 'ENSG00000217258': nan, 'ENSG00000270009': nan, 'ENSG00000267935': nan, 'ENSG00000196226': 'ENSG00000278588', 'ENSG00000168242': 'ENSG00000278588', 'ENSG00000234298': nan, 'ENSG00000258297': nan, 'ENSG00000233255': nan, 'ENSG00000214645': nan, 'ENSG00000233143': 'ENSG00000223874', 'ENSG00000268332': nan, 'ENSG00000273081': nan, 'ENSG00000271815': nan, 'ENSG00000223795': 'ENSG00000228877', 'ENSG00000269640': nan, 'ENSG00000233988': nan, 'ENSG00000264868': nan, 'ENSG00000232018': nan, 'ENSG00000253426': nan, 'ENSG00000268735': nan, 'ENSG00000181464': nan, 'ENSG00000235704': nan, 'ENSG00000231774': nan, 'ENSG00000261521': nan, 'ENSG00000260052': nan, 'ENSG00000262668': 'ENSG00000168124', 'ENSG00000269358': nan, 'ENSG00000256321': 'ENSG00000256995', 'ENSG00000231816': nan, 'ENSG00000172653': 'ENSG00000270379', 'ENSG00000230836': 'ENSG00000204792', 'ENSG00000250284': 'ENSG00000249803', 'ENSG00000244260': 'ENSG00000240687', 'ENSG00000262089': 'ENSG00000267532', 'ENSG00000264080': 'ENSG00000266602', 'ENSG00000270265': 'ENSG00000251611', 'ENSG00000268155': nan, 'ENSG00000230565': 'ENSG00000228426', 'ENSG00000269267': nan, 'ENSG00000259616': 'ENSG00000259675', 'ENSG00000272955': nan, 'ENSG00000214314': nan, 'ENSG00000198518': nan, 'ENSG00000249731': 'ENSG00000248994', 'ENSG00000223562': nan, 'ENSG00000272389': nan, 'ENSG00000255145': 'ENSG00000271086', 'ENSG00000240875': 'ENSG00000243926', 'ENSG00000225135': nan, 'ENSG00000204508': nan, 'ENSG00000268791': nan, 'ENSG00000232784': nan, 'ENSG00000133149': nan, 'ENSG00000170215': nan, 'ENSG00000235665': 'ENSG00000236790', 'ENSG00000269410': nan, 'ENSG00000253459': nan, 'ENSG00000235852': 'ENSG00000228509', 'ENSG00000135213': nan, 'ENSG00000268328': nan, 'ENSG00000198307': 'ENSG00000277858', 'ENSG00000255945': 'ENSG00000286922', 'ENSG00000264443': 'ENSG00000286061', 'ENSG00000183130': nan, 'ENSG00000265964': 'ENSG00000265547', 'ENSG00000267950': nan, 'ENSG00000235504': nan, 'ENSG00000228798': nan, 'ENSG00000237374': nan, 'ENSG00000261135': 'ENSG00000224174', 'ENSG00000272286': nan, 'ENSG00000268457': nan, 'ENSG00000271769': nan, 'ENSG00000168260': nan, 'ENSG00000273009': nan, 'ENSG00000233005': 'ENSG00000231204', 'ENSG00000231518': nan, 'ENSG00000182912': 'ENSG00000235890', 'ENSG00000231145': nan, 'ENSG00000237721': nan, 'ENSG00000255651': nan, 'ENSG00000267070': 'ENSG00000285567', 'ENSG00000228334': 'ENSG00000217455', 'ENSG00000226894': nan, 'ENSG00000267381': nan, 'ENSG00000234245': nan, 'ENSG00000230641': 'ENSG00000232162', 'ENSG00000187145': nan, 'ENSG00000185044': nan, 'ENSG00000269605': nan, 'ENSG00000258714': nan, 'ENSG00000184886': nan, 'ENSG00000262395': nan, 'ENSG00000249381': 'ENSG00000251372', 'ENSG00000250588': nan, 'ENSG00000214306': nan, 'ENSG00000260506': nan, 'ENSG00000261833': nan, 'ENSG00000249269': 'ENSG00000251619', 'ENSG00000251144': 'ENSG00000251670', 'ENSG00000226362': 'ENSG00000290726', 'ENSG00000253484': 'ENSG00000289095', 'ENSG00000197445': nan, 'ENSG00000269804': nan, 'ENSG00000214325': nan, 'ENSG00000227603': nan, 'ENSG00000233137': nan, 'ENSG00000273307': nan, 'ENSG00000183653': nan, 'ENSG00000182611': 'ENSG00000278677', 'ENSG00000260359': nan, 'ENSG00000231734': nan, 'ENSG00000239801': 'ENSG00000174840', 'ENSG00000254318': nan, 'ENSG00000259549': nan, 'ENSG00000230600': 'ENSG00000232817', 'ENSG00000273373': 'ENSG00000224699', 'ENSG00000181935': nan, 'ENSG00000224441': nan, 'ENSG00000196644': nan, 'ENSG00000231632': nan, 'ENSG00000267839': nan, 'ENSG00000228353': 'ENSG00000229672', 'ENSG00000198946': nan, 'ENSG00000262558': 'ENSG00000262294', 'ENSG00000269999': nan, 'ENSG00000272796': nan, 'ENSG00000241978': nan, 'ENSG00000272709': nan, 'ENSG00000232348': nan, 'ENSG00000250777': 'ENSG00000250126', 'ENSG00000268192': nan, 'ENSG00000072444': nan, 'ENSG00000269831': nan, 'ENSG00000224235': nan, 'ENSG00000260095': 'ENSG00000260874', 'ENSG00000108292': nan, 'ENSG00000261589': nan, 'ENSG00000233863': nan, 'ENSG00000241180': 'ENSG00000272438', 'ENSG00000240224': 'ENSG00000288705', 'ENSG00000260065': nan, 'ENSG00000251044': nan, 'ENSG00000230177': nan, 'ENSG00000213240': nan, 'ENSG00000268788': nan, 'ENSG00000229463': nan, 'ENSG00000236524': nan, 'ENSG00000229454': 'ENSG00000230303', 'ENSG00000236947': nan, 'ENSG00000130723': nan, 'ENSG00000215611': nan, 'ENSG00000260487': 'ENSG00000261346', 'ENSG00000108272': nan, 'ENSG00000269871': nan, 'ENSG00000255854': nan, 'ENSG00000270147': 'ENSG00000269921', 'ENSG00000232698': nan, 'ENSG00000240401': 'ENSG00000293422', 'ENSG00000267588': nan, 'ENSG00000268413': nan, 'ENSG00000108294': nan, 'ENSG00000255863': nan, 'ENSG00000230633': nan, 'ENSG00000259243': nan, 'ENSG00000237422': 'ENSG00000230537', 'ENSG00000242384': nan, 'ENSG00000251331': nan, 'ENSG00000249184': 'ENSG00000251249', 'ENSG00000204844': nan, 'ENSG00000256715': nan, 'ENSG00000233022': nan, 'ENSG00000132139': 'ENSG00000270765', 'ENSG00000184040': nan, 'ENSG00000259063': nan, 'ENSG00000227164': nan, 'ENSG00000226849': 'ENSG00000230337', 'ENSG00000258216': 'ENSG00000271614', 'ENSG00000232224': nan, 'ENSG00000259747': nan, 'ENSG00000244268': 'ENSG00000288787', 'ENSG00000268280': nan, 'ENSG00000273097': nan, 'ENSG00000253350': nan, 'ENSG00000226785': nan, 'ENSG00000265780': nan, 'ENSG00000257613': nan, 'ENSG00000256101': 'ENSG00000215241', 'ENSG00000250232': nan, 'ENSG00000260470': 'ENSG00000250432', 'ENSG00000248359': 'ENSG00000248884', 'ENSG00000258612': nan, 'ENSG00000270030': nan, 'ENSG00000266935': nan, 'ENSG00000272177': nan, 'ENSG00000270604': 'ENSG00000231074', 'ENSG00000241990': 'ENSG00000197182', 'ENSG00000229583': 'ENSG00000268994', 'ENSG00000260793': 'ENSG00000267394', 'ENSG00000272005': nan, 'ENSG00000228214': nan, 'ENSG00000272515': nan, 'ENSG00000237726': nan, 'ENSG00000257918': 'ENSG00000257545', 'ENSG00000224532': 'ENSG00000226281', 'ENSG00000264790': 'ENSG00000265374', 'ENSG00000267668': nan, 'ENSG00000272216': nan, 'ENSG00000132130': nan, 'ENSG00000233878': nan, 'ENSG00000258642': 'ENSG00000259130', 'ENSG00000175898': nan, 'ENSG00000233368': nan, 'ENSG00000249365': nan, 'ENSG00000258088': 'ENSG00000258077', 'ENSG00000130489': nan, 'ENSG00000269415': nan, 'ENSG00000257962': 'ENSG00000258256', 'ENSG00000259799': nan, 'ENSG00000253929': nan, 'ENSG00000258882': nan, 'ENSG00000215394': nan, 'ENSG00000271970': nan, 'ENSG00000183657': nan, 'ENSG00000230850': nan, 'ENSG00000112096': 'ENSG00000291237', 'ENSG00000196936': nan, 'ENSG00000267812': nan, 'ENSG00000205147': nan, 'ENSG00000214109': nan, 'ENSG00000269746': nan, 'ENSG00000250411': nan, 'ENSG00000270237': nan, 'ENSG00000197263': nan, 'ENSG00000249069': nan, 'ENSG00000230906': nan, 'ENSG00000108264': nan, 'ENSG00000237021': nan, 'ENSG00000241732': nan, 'ENSG00000214597': nan, 'ENSG00000272233': nan, 'ENSG00000259806': nan, 'ENSG00000267880': nan, 'ENSG00000244247': 'ENSG00000241098', 'ENSG00000236249': nan, 'ENSG00000132832': 'ENSG00000244558', 'ENSG00000263508': 'ENSG00000263400', 'ENSG00000226786': nan, 'ENSG00000272066': nan, 'ENSG00000224460': nan, 'ENSG00000268387': nan, 'ENSG00000261428': nan, 'ENSG00000268352': nan, 'ENSG00000182242': nan, 'ENSG00000263214': nan, 'ENSG00000261720': 'ENSG00000292430', 'ENSG00000269047': nan, 'ENSG00000214841': nan, 'ENSG00000256373': nan, 'ENSG00000272761': nan, 'ENSG00000272448': nan, 'ENSG00000268965': nan, 'ENSG00000268953': nan, 'ENSG00000231217': nan, 'ENSG00000227185': nan, 'ENSG00000223469': 'ENSG00000283215', 'ENSG00000243452': nan, 'ENSG00000246331': 'ENSG00000285517', 'ENSG00000214970': 'ENSG00000272975', 'ENSG00000259762': 'ENSG00000259416', 'ENSG00000234248': nan, 'ENSG00000269928': nan, 'ENSG00000269391': 'ENSG00000233570', 'ENSG00000247810': 'ENSG00000261761', 'ENSG00000268265': nan, 'ENSG00000268822': nan, 'ENSG00000267913': nan, 'ENSG00000250530': nan, 'ENSG00000257277': 'ENSG00000231758', 'ENSG00000257088': nan, 'ENSG00000205047': nan, 'ENSG00000264469': nan, 'ENSG00000235815': 'ENSG00000289090', 'ENSG00000273488': nan, 'ENSG00000272520': nan, 'ENSG00000263182': nan, 'ENSG00000231242': nan, 'ENSG00000260923': 'ENSG00000260528', 'ENSG00000225742': 'ENSG00000214145', 'ENSG00000269963': nan, 'ENSG00000224226': nan, 'ENSG00000255823': nan, 'ENSG00000244567': nan, 'ENSG00000272403': nan, 'ENSG00000204365': nan, 'ENSG00000267918': nan, 'ENSG00000268313': nan, 'ENSG00000230857': nan, 'ENSG00000212998': nan, 'ENSG00000257999': nan, 'ENSG00000273116': nan, 'ENSG00000157828': 'ENSG00000280146', 'ENSG00000269510': nan, 'ENSG00000260929': nan, 'ENSG00000231255': 'ENSG00000233073', 'ENSG00000226381': nan, 'ENSG00000231435': nan, 'ENSG00000272792': nan, 'ENSG00000259641': nan, 'ENSG00000148828': nan, 'ENSG00000269753': nan, 'ENSG00000240510': nan, 'ENSG00000244252': nan, 'ENSG00000239498': 'ENSG00000288902', 'ENSG00000267963': nan, 'ENSG00000273065': nan, 'ENSG00000212857': nan, 'ENSG00000230567': nan, 'ENSG00000268024': nan, 'ENSG00000254140': nan, 'ENSG00000271308': nan, 'ENSG00000214844': nan, 'ENSG00000232753': nan, 'ENSG00000269185': nan, 'ENSG00000255546': nan, 'ENSG00000235795': nan, 'ENSG00000122718': nan, 'ENSG00000243300': nan, 'ENSG00000255944': 'ENSG00000256128', 'ENSG00000268716': nan, 'ENSG00000213494': nan, 'ENSG00000171129': nan, 'ENSG00000273389': nan, 'ENSG00000266614': 'ENSG00000266014', 'ENSG00000268470': nan, 'ENSG00000197463': 'ENSG00000268902', 'ENSG00000259942': nan, 'ENSG00000267118': nan, 'ENSG00000273181': 'ENSG00000272721', 'ENSG00000261462': 'ENSG00000307585', 'ENSG00000222022': 'ENSG00000222032', 'ENSG00000236856': 'ENSG00000233684', 'ENSG00000233788': nan, 'ENSG00000188424': nan, 'ENSG00000173088': nan, 'ENSG00000247270': nan, 'ENSG00000150165': nan, 'ENSG00000267047': 'ENSG00000267532', 'ENSG00000250670': 'ENSG00000245384', 'ENSG00000233404': nan, 'ENSG00000233895': nan, 'ENSG00000268085': nan, 'ENSG00000197697': 'ENSG00000278588', 'ENSG00000205148': nan, 'ENSG00000270109': nan, 'ENSG00000215405': nan, 'ENSG00000254967': nan, 'ENSG00000270028': nan, 'ENSG00000269998': nan, 'ENSG00000273170': nan, 'ENSG00000260787': nan, 'ENSG00000212768': nan, 'ENSG00000237534': nan, 'ENSG00000268126': nan, 'ENSG00000185254': nan, 'ENSG00000270041': nan, 'ENSG00000244063': 'ENSG00000228857', 'ENSG00000124693': 'ENSG00000278272', 'ENSG00000249430': nan, 'ENSG00000241317': 'ENSG00000293221', 'ENSG00000238033': nan, 'ENSG00000232417': 'ENSG00000269096', 'ENSG00000273466': nan, 'ENSG00000269515': nan, 'ENSG00000242013': nan, 'ENSG00000161326': nan, 'ENSG00000198327': 'ENSG00000278637', 'ENSG00000256001': 'ENSG00000249345', 'ENSG00000254757': 'ENSG00000287312', 'ENSG00000237404': nan, 'ENSG00000228439': nan, 'ENSG00000270810': nan, 'ENSG00000269728': nan, 'ENSG00000253844': 'ENSG00000228801', 'ENSG00000262031': 'ENSG00000261886', 'ENSG00000230880': nan, 'ENSG00000102080': nan, 'ENSG00000141140': nan, 'ENSG00000260760': nan, 'ENSG00000270173': nan, 'ENSG00000186117': nan, 'ENSG00000248371': 'ENSG00000249085', 'ENSG00000269966': 'ENSG00000233237', 'ENSG00000248467': nan, 'ENSG00000260548': nan, 'ENSG00000251654': 'ENSG00000248605', 'ENSG00000234007': nan, 'ENSG00000258785': 'ENSG00000258476', 'ENSG00000269690': nan, 'ENSG00000239665': 'ENSG00000165630', 'ENSG00000227112': nan, 'ENSG00000258914': nan, 'ENSG00000268898': nan, 'ENSG00000268656': nan, 'ENSG00000186807': nan, 'ENSG00000269531': nan, 'ENSG00000233415': 'ENSG00000237767', 'ENSG00000258919': 'ENSG00000258404', 'ENSG00000161573': nan, 'ENSG00000263198': nan, 'ENSG00000121848': nan, 'ENSG00000250237': 'ENSG00000248884', 'ENSG00000272940': 'ENSG00000205559', 'ENSG00000248828': nan, 'ENSG00000258921': nan, 'ENSG00000228512': nan, 'ENSG00000198444': 'ENSG00000277203', 'ENSG00000253197': 'ENSG00000253577', 'ENSG00000226747': 'ENSG00000231646', 'ENSG00000215462': nan, 'ENSG00000203863': nan, 'ENSG00000264263': nan, 'ENSG00000269049': nan, 'ENSG00000263388': 'ENSG00000272975', 'ENSG00000271020': nan, 'ENSG00000162290': nan, 'ENSG00000253264': nan, 'ENSG00000266045': nan, 'ENSG00000268856': nan, 'ENSG00000265114': nan, 'ENSG00000225353': nan, 'ENSG00000269601': nan, 'ENSG00000262194': nan, 'ENSG00000268164': nan, 'ENSG00000241481': nan, 'ENSG00000270113': nan, 'ENSG00000254353': nan, 'ENSG00000236948': 'ENSG00000289893', 'ENSG00000269936': nan, 'ENSG00000203849': nan, 'ENSG00000263553': nan, 'ENSG00000228434': 'ENSG00000290758', 'ENSG00000186275': nan, 'ENSG00000258918': 'ENSG00000259130', 'ENSG00000269417': nan, 'ENSG00000269909': nan, 'ENSG00000214854': nan, 'ENSG00000262758': nan, 'ENSG00000266958': nan, 'ENSG00000233889': nan, 'ENSG00000272030': 'ENSG00000189171', 'ENSG00000259209': 'ENSG00000259768', 'ENSG00000268341': nan, 'ENSG00000234407': nan, 'ENSG00000231121': nan, 'ENSG00000260006': nan, 'ENSG00000237133': nan, 'ENSG00000249708': nan, 'ENSG00000221961': nan, 'ENSG00000250418': nan, 'ENSG00000253701': nan, 'ENSG00000163386': nan, 'ENSG00000235037': nan, 'ENSG00000270163': nan, 'ENSG00000267884': nan, 'ENSG00000266002': 'ENSG00000265313', 'ENSG00000253371': nan, 'ENSG00000250061': nan, 'ENSG00000263136': 'ENSG00000280789', 'ENSG00000241636': 'ENSG00000241767', 'ENSG00000267747': nan, 'ENSG00000268333': 'ENSG00000235590', 'ENSG00000234214': nan, 'ENSG00000198106': 'ENSG00000103472', 'ENSG00000257194': nan, 'ENSG00000269751': nan, 'ENSG00000197851': nan, 'ENSG00000268111': nan, 'ENSG00000234734': nan, 'ENSG00000258664': nan, 'ENSG00000198366': 'ENSG00000278272', 'ENSG00000230525': 'ENSG00000232046', 'ENSG00000254115': 'ENSG00000253778', 'ENSG00000268028': nan, 'ENSG00000171471': nan, 'ENSG00000253584': 'ENSG00000251574', 'ENSG00000250446': 'ENSG00000248673', 'ENSG00000254199': nan, 'ENSG00000259886': nan, 'ENSG00000253766': 'ENSG00000291102', 'ENSG00000266601': 'ENSG000002344

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

Because such a large number of ENSG are unmapped, replace the unmapped ones with the original IDs

In [34]:
cur_data.adata.var

,ncounts,ensembl_id,ncells,ensembl_gene_id,gene_symbol,original_index
index,,,,,,
0,11.0,ENSG00000243485,11,ENSG00000243485,MIR1302-2HG,MIR1302-10
1,0.0,ENSG00000237613,0,ENSG00000237613,FAM138A,FAM138A
2,0.0,ENSG00000186092,0,ENSG00000186092,OR4F5,OR4F5
3,0.0,ENSG00000238009,0,ENSG00000241860,RP11-34P13.7,RP11-34P13.7
4,43.0,ENSG00000239945,43,ENSG00000239945,RP11-34P13.8,RP11-34P13.8
...,...,...,...,...,...,...
32733,0.0,ENSG00000215635,0,ENSG00000215635,AC145205.1,AC145205.1
32734,0.0,ENSG00000268590,0,ENSG00000268590,BAGE5,BAGE5
32735,0.0,ENSG00000251180,0,ENSG00000251180,CU459201.1,CU459201.1
32736,0.0,ENSG00000215616,0,ENSG00000215616,AC002321.2,AC002321.2
32737,0.0,ENSG00000215611,0,ENSG00000215611,AC002321.1,AC002321.1

In [33]:
cur_data.adata.var.loc[cur_data.adata.var['gene_symbol'].isna(), 'gene_symbol'] = cur_data.adata.var.loc[
    cur_data.adata.var['gene_symbol'].isna(), 'original_index']

### Validate var metadata

In [35]:
cur_data.validate_data(slot="var")

2026-04-28 11:23:51,982 INFO curation_tools.curation_tools: adata.var is valid according to the var_schema.
2026-04-28 11:23:51,985 DEBUG curation_tools.curation_tools: Validated adata.var preview (shape=(32738, 2)):
       ensembl_gene_id   gene_symbol
index
0      ENSG00000243485   MIR1302-2HG
1      ENSG00000237613       FAM138A
2      ENSG00000186092         OR4F5
3      ENSG00000241860  RP11-34P13.7
4      ENSG00000239945  RP11-34P13.8

       ensembl_gene_id   gene_symbol
index
0      ENSG00000243485   MIR1302-2HG
1      ENSG00000237613       FAM138A
2      ENSG00000186092         OR4F5
3      ENSG00000241860  RP11-34P13.7
4      ENSG00000239945  RP11-34P13.8
...                ...           ...
32733  ENSG00000215635    AC145205.1
32734  ENSG00000268590         BAGE5
32735  ENSG00000251180    CU459201.1
32736  ENSG00000215616    AC002321.2
32737  ENSG00000215611    AC002321.1

[32738 rows x 2 columns]

# Save the dataset

In [36]:
cur_data.save_curated_data_h5ad()

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)
... storing 'dataset_id' as categorical
... storing 'data_modality' as categorical
... storing 'significance_criteria' as categorical
... storing 'perturbation_name' as categorical
... storing 'perturbed_target_coord' as categorical
... storing 'perturbed_target_chromosome' as categorical
... storing 'perturbed_target_ensg' as categorical
... storing 'perturbed_target_symbol' as categorical
... storing 'perturbed_target_biotype' as categorical
... storing 'guide_sequence' as categorical
... storing 'perturbation_type_label' as categorical
... storing 'perturbation_type_id' as categorical
... storing 'timepoint' as categorical
... storing 'treatment_label' as categorical
... storing 'treatment_id' as categorical
... storing 'technical_replicate' as categorical
... storing 'biological_replicate' as categorical
... storing 'model_system_label' as categorical
... storing 'model_system_id' as categorical
... storing 'species' as categorical
... storing 'tissue_label' as categorical
... storing 'tissue_id' as categorical
... storing 'cell_type_label' as categorical
... storing 'cell_type_id' as categorical
... storing 'cell_line_label' as categorical
... storing 'cell_line_id' as categorical
... storing 'sex_label' as categorical
... storing 'sex_id' as categorical
... storing 'developmental_stage_label' as categorical
... storing 'developmental_stage_id' as categorical
... storing 'disease_label' as categorical
... storing 'disease_id' as categorical
... storing 'study_title' as categorical
... storing 'study_uri' as categorical
... storing 'first_author' as categorical
... storing 'last_author' as categorical
... storing 'experiment_title' as categorical
... storing 'experiment_summary' as categorical
... storing 'number_of_perturbed_targets' as categorical
... storing 'number_of_perturbed_samples' as categorical
... storing 'library_generation_type_id' as categorical
... storing 'library_generation_type_label' as categorical
... storing 'library_generation_method_id' as categorical
... storing 'library_generation_method_label' as categorical
... storing 'enzyme_delivery_method_id' as categorical
... storing 'enzyme_delivery_method_label' as categorical
... storing 'library_delivery_method_id' as categorical
... storing 'library_delivery_method_label' as categorical
... storing 'enzyme_integration_state_id' as categorical
... storing 'enzyme_integration_state_label' as categorical
... storing 'library_integration_state_id' as categorical
... storing 'library_integration_state_label' as categorical
... storing 'enzyme_expression_control_id' as categorical
... storing 'enzyme_expression_control_label' as categorical
... storing 'library_expression_control_id' as categorical
... storing 'library_expression_control_label' as categorical
... storing 'library_name' as categorical
... storing 'library_uri' as categorical
... storing 'library_format_id' as categorical
... storing 'library_format_label' as categorical
... storing 'library_scope_id' as categorical
... storing 'library_scope_label' as categorical
... storing 'library_perturbation_type_id' as categorical
... storing 'library_perturbation_type_label' as categorical
... storing 'library_manufacturer' as categorical
... storing 'library_lentiviral_generation' as categorical
... storing 'library_grnas_per_target' as categorical
... storing 'library_total_grnas' as categorical
... storing 'readout_dimensionality_id' as categorical
... storing 'readout_dimensionality_label' as categorical
... storing 'readout_type_id' as categorical
... storing 'readout_type_label' as categorical
... storing 'readout_technology_id' as categorical
... storing 'readout_technology_label' as categorical
... storing 'method_name_id' as categorical
... storing 'method_name_label' as categorical
... storing 'method_uri' as categorical
... storing 'sequencing_library_kit_id' as categorical
... storing 'sequencing_library_kit_label' as categorical
... storing 'sequencing_platform_id' as categorical
... storing 'sequencing_platform_label' as categorical
... storing 'sequencing_strategy_id' as categorical
... storing 'sequencing_strategy_label' as categorical
... storing 'software_counts_id' as categorical
... storing 'software_counts_label' as categorical
... storing 'software_analysis_id' as categorical
... storing 'software_analysis_label' as categorical
... storing 'score_interpretation' as categorical
... storing 'reference_genome_id' as categorical
... storing 'reference_genome_label' as categorical
... storing 'associated_datasets' as categorical
... storing 'license_label' as categorical
... storing 'license_id' as categorical
... storing 'ensembl_gene_id' as categorical
... storing 'gene_symbol' as categorical
2026-04-28 11:23:57,849 DEBUG h5py._conv: Creating converter from 5 to 3

✅ Curated h5ad data saved to ../curated/h5ad/adamson_2016_upr_perturb_seq_curated.h5ad

In [37]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/adamson_2016_upr_perturb_seq_curated_metadata.parquet

# Upload to BigQuery

In [38]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/adamson_2016_upr_perturb_seq_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

2026-04-28 11:24:24,533 DEBUG google.auth._default: Checking '' for explicit credentials as part of auth process...
2026-04-28 11:24:24,533 DEBUG google.auth._default: Checking Cloud SDK credentials as part of auth process...
2026-04-28 11:24:25,511 DEBUG google.auth._default: Checking '' for explicit credentials as part of auth process...
2026-04-28 11:24:25,513 DEBUG google.auth._default: Checking Cloud SDK credentials as part of auth process...
2026-04-28 11:24:26,322 DEBUG google.cloud.bigquery.opentelemetry_tracing: This service is instrumented using OpenTelemetry. OpenTelemetry or one of its components could not be imported; please add compatible versions of opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data.
2026-04-28 11:24:26,324 DEBUG urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2026-04-28 11:24:26,328 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): oauth2.googleapis.com:443
2026-04-28 11:24:26,382 DEBUG urllib3.connectionpool: https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2026-04-28 11:24:26,385 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): bigquery.googleapis.com:443
2026-04-28 11:24:26,644 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata?prettyPrint=false HTTP/1.1" 200 None

Staging table: loading `.parquet` file ../curated/parquet/adamson_2016_upr_perturb_seq_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...

2026-04-28 11:24:27,122 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /upload/bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?uploadType=resumable HTTP/1.1" 200 0
2026-04-28 11:24:27,841 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "PUT /upload/bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?uploadType=resumable&upload_id=AAVLpEgjqmtD8nNasaEnVgbqDjsu3cqr9vRkd5NKsB6mh2G3TuNXOomhvxeDfLpP8bzjtDJ-8GwJKgNhReijHRZBxj5K9RDK2qsvXcen88OhfQ HTTP/1.1" 200 14124
2026-04-28 11:24:28,014 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/369bd0a1-fda7-4520-bc86-1b3f86f4407b?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:28,566 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/369bd0a1-fda7-4520-bc86-1b3f86f4407b?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:30,078 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/369bd0a1-fda7-4520-bc86-1b3f86f4407b?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:30,282 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata_staging?prettyPrint=false HTTP/1.1" 200 None

Staging table: loaded 62623 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

2026-04-28 11:24:32,335 DEBUG urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2026-04-28 11:24:32,337 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): oauth2.googleapis.com:443
2026-04-28 11:24:32,397 DEBUG urllib3.connectionpool: https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2026-04-28 11:24:32,399 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): bigquery.googleapis.com:443
2026-04-28 11:24:32,796 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:32,883 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/66b80c60-35b9-49f6-a575-7af478edce2c?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:33,006 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/66b80c60-35b9-49f6-a575-7af478edce2c?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:33,099 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/66b80c60-35b9-49f6-a575-7af478edce2c?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:33,436 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:33,547 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/a2c9eda6-de2f-4089-b423-b3cbd5ce89f3?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:33,711 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/a2c9eda6-de2f-4089-b423-b3cbd5ce89f3?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:33,837 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/a2c9eda6-de2f-4089-b423-b3cbd5ce89f3?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:34,480 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:34,598 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/47e97c66-7a66-41cd-8c43-d4ac0028dd5c?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:37,248 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/47e97c66-7a66-41cd-8c43-d4ac0028dd5c?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:37,395 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/47e97c66-7a66-41cd-8c43-d4ac0028dd5c?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:37,592 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata?prettyPrint=false HTTP/1.1" 200 None

Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

2026-04-28 11:24:37,728 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata?prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:38,221 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:38,376 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/f8007782-fb43-4559-9d96-7792e7fe4326?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:42,664 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/f8007782-fb43-4559-9d96-7792e7fe4326?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:42,735 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/f8007782-fb43-4559-9d96-7792e7fe4326?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-28 11:24:42,914 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "DELETE /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata_staging?prettyPrint=false HTTP/1.1" 204 0

Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [39]:
!gcloud storage cp ../curated/h5ad/adamson_2016_upr_perturb_seq_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/adamson_2016_upr_perturb_seq_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/adamson_2016_upr_perturb_seq_curated.h5ad
  Completed files 32/1 | 1.7GiB/1.7GiB | 273.4MiB/s

Average throughput: 303.7MiB/s