# Import

In [1]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("curation.log"),
        logging.StreamHandler(),  # keep console output too
    ],
    force=True,
)

# Download data

In [11]:
noncurated_path = "../non_curated/h5ad/arce_2025.h5ad"
noncurated_dir = "../supplementary/arce_2025/"
download_file(
    url="https://ftp.ncbi.nlm.nih.gov/geo/series/GSE278nnn/GSE278572/suppl/GSE278572%5Fbarcodes.tsv.gz",
    dest_path=noncurated_dir+"GSE278572_barcodes.tsv.gz"
)
download_file(
    url="https://ftp.ncbi.nlm.nih.gov/geo/series/GSE278nnn/GSE278572/suppl/GSE278572%5Ffeatures.tsv.gz",
    dest_path=noncurated_dir+"GSE278572_features.tsv.gz"
)
download_file(
    url="https://ftp.ncbi.nlm.nih.gov/geo/series/GSE278nnn/GSE278572/suppl/GSE278572%5Fmatrix.mtx.gz",
    dest_path=noncurated_dir+"GSE278572_matrix.mtx.gz"
)
download_file(
    url="https://zenodo.org/records/13924126/files/data_tables.zip?download=1",
    dest_path=noncurated_dir+"GSE278572_supplementary_tables.zip",
    unarchive=True
)
download_file(
    url="https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE278572&format=file&file=GSE278572%5Fprotospacer%5Fcalls%5Fper%5Fcell%2Ecsv%2Egz",
    dest_path=noncurated_dir+"GSE278572_protospacer_calls_per_cell.csv.gz",
    unarchive=False
)
!mv ../supplementary/arce_2025/data_tables ../supplementary/arce_2025/supplementary_tables

File ../supplementary/arce_2025/GSE278572_barcodes.tsv.gz already exists. Skipping download.
File ../supplementary/arce_2025/GSE278572_features.tsv.gz already exists. Skipping download.
File ../supplementary/arce_2025/GSE278572_matrix.mtx.gz already exists. Skipping download.
File ../supplementary/arce_2025/GSE278572_supplementary_tables.zip already exists. Skipping download.
File ../supplementary/arce_2025/GSE278572_protospacer_calls_per_cell.csv.gz already exists. Skipping download.
mv: cannot stat '../supplementary/arce_2025/data_tables': No such file or directory

# Convert to h5ad

Uncomment if running for the first time

In [ ]:
# import scanpy as sc
# adata = sc.read_10x_mtx(
#     noncurated_dir,
#     var_names='gene_symbols',
#     make_unique=False,
#     gex_only=True,
#     prefix="GSE278572_"
# )

# # write to h5ad
# adata.write_h5ad(noncurated_path)

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/.venv/lib/python3.12/site-packages/anndata/_core/anndata.py:1793: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
... storing 'feature_types' as categorical

# Initialise the dataset object

In [4]:
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/arce_2025.h5ad

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/.venv/lib/python3.12/site-packages/anndata/_core/anndata.py:1793: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

### Add cell barcodes to the obs slot

In [6]:
cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.astype(str)

print(cur_data.adata.obs[['cell_barcode']].head())

                          cell_barcode
AAACCTGAGAACAACT-1  AAACCTGAGAACAACT-1
AAACCTGAGAAGAAGC-1  AAACCTGAGAAGAAGC-1
AAACCTGAGAGAACAG-1  AAACCTGAGAGAACAG-1
AAACCTGAGAGAGCTC-1  AAACCTGAGAGAGCTC-1
AAACCTGAGAGCTATA-1  AAACCTGAGAGCTATA-1

# OBS slot curation

### Show unique perturbations

In [6]:
# cur_data.rename_columns(slot = 'obs', name_dict = {'sgID_AB': 'perturbation_name'})

### Add guide RNA information

Orignal guideRNA metadata referenced in the paper cannot be unambiguously mapped. Requested updated metadata from the authors - it is contained within the `data_exploration/Perturbseq/supplementary/arce_2025/feature_reference_name_key.csv` folder.

In [8]:
supp_guides = pd.read_csv("../supplementary/arce_2025/feature_reference_name_key.csv")
supp_guides["guide_sequence"] = supp_guides["sgRNA_long"].str.split("_").str[1]
supp_guides = supp_guides[
    ["id", "target_gene_id", "target_gene_name", "guide_sequence"]
]
supp_guides = supp_guides.replace(
    {"target_gene_id": {"Non-Targeting": "control_nontargeting"},
     "target_gene_name": {"Non-Targeting": "control_nontargeting"}}
)
supp_guides

,id,target_gene_id,target_gene_name,guide_sequence
0,BACH2_1_CRISPRi,ENSG00000112182,BACH2,GCGCTGTGCGACCGCAGCCC
1,BACH2_2_CRISPRi,ENSG00000112182,BACH2,CAGCAGCGGCCGTGCACGCC
2,BATF_1_CRISPRi,ENSG00000156127,BATF,CCTGCGTCCTCCTCACTCTG
3,BATF_2_CRISPRi,ENSG00000156127,BATF,TCCCTCTGCACCCCAGAGTG
4,BPTF_1_CRISPRi,ENSG00000171634,BPTF,AAGGCTCAATCCGAATTGCT
...,...,...,...,...
60,Non-Targeting_5_CRISPRi,control_nontargeting,control_nontargeting,ACGCCTCCTCAAATTAGCTC
61,Non-Targeting_6_CRISPRi,control_nontargeting,control_nontargeting,GAAACGAGAAGTTTGTACTA
62,Non-Targeting_7_CRISPRi,control_nontargeting,control_nontargeting,TAATGCTGCACACGCCGAAT
63,Non-Targeting_8_CRISPRi,control_nontargeting,control_nontargeting,GGCTGGTTGACGACTCCTGA
64,Non-Targeting_9_CRISPRi,control_nontargeting,control_nontargeting,TAACCGATACTCCCCACATT

In [12]:
# read in the guide RNA spreadsheet
# guides for the essential library are in "ST20" sheet
guide_info_df = pd.read_csv(
    "../supplementary/arce_2025/GSE278572_protospacer_calls_per_cell.csv.gz"
)
guide_info_df = guide_info_df.rename(columns={"feature_call": "perturbation_name"})
guide_info_df = (
    guide_info_df[["cell_barcode", "perturbation_name"]]
    .drop_duplicates()
    .assign(perturbation_name=guide_info_df["perturbation_name"].str.split("|"))
    .explode("perturbation_name")
    .merge(supp_guides, how="left", left_on="perturbation_name", right_on="id")
    .drop(columns=["id"])
    .groupby("cell_barcode", as_index=False)
    .agg({
        "perturbation_name": lambda x: "|".join(x),
        "target_gene_name": lambda x: "|".join(x),
        "target_gene_id": lambda x: "|".join(x),
        "guide_sequence": lambda x: "|".join(x)
    })
)
guide_info_df

,cell_barcode,perturbation_name,target_gene_name,target_gene_id,guide_sequence
0,AAACCTGAGAAACCTA-2,IRF1_2_CRISPRi,IRF1,ENSG00000125347,CGGCCGGCGTGGACTGGGCA
1,AAACCTGAGAAAGTGG-4,MED11_2_CRISPRi|USP22_1_CRISPRi,MED11|USP22,ENSG00000161920|ENSG00000124422,GTAGGTAGCCATTATCACTC|GCGCCGAGAACAAAGCGCGG
2,AAACCTGAGAACAACT-1,IRF1_1_CRISPRi|MED11_1_CRISPRi|MED12_2_CRISPRi,IRF1|MED11|MED12,ENSG00000125347|ENSG00000161920|ENSG00000184634,GCCCGAGCCCCGCCGAACCG|GAACAAGCGTCGCGTTTCTG|GGCG...
3,AAACCTGAGAACAACT-8,KLF13_1_CRISPRi,KLF13,ENSG00000169926,CCGGTTCTAAGGATGCCGAG
4,AAACCTGAGAACTCGG-3,BPTF_2_CRISPRi|IRF4_2_CRISPRi|MEF2D_1_CRISPRi|...,BPTF|IRF4|MEF2D|KLF2,ENSG00000171634|ENSG00000137265|ENSG0000011660...,GATGGCGGCTGAAGGCGATC|TCGGAGCTGAGGGCAGCGGT|GCCG...
...,...,...,...,...,...
191615,TTTGTCATCTTAGAGC-4,Non-Targeting_4_CRISPRi,control_nontargeting,control_nontargeting,GCTGTTCCGAAGTTGAGAAT
191616,TTTGTCATCTTGAGAC-5,BACH2_1_CRISPRi|CBFB_1_CRISPRi|NFKB2_2_CRISPRi,BACH2|CBFB|NFKB2,ENSG00000112182|ENSG00000067955|ENSG00000077150,GCGCTGTGCGACCGCAGCCC|GCGGCAGGCAACGGCTGAGG|CGGA...
191617,TTTGTCATCTTGAGGT-8,BATF_2_CRISPRi|ATXN7L3_1_CRISPRi,BATF|ATXN7L3,ENSG00000156127|ENSG00000087152,TCCCTCTGCACCCCAGAGTG|ACTGCTCGCGCCTGCTAGAA
191618,TTTGTCATCTTGTATC-1,CBFB_2_CRISPRi,CBFB,ENSG00000067955,GGCAACGGCTGAGGCGGCGG
191619,TTTGTCATCTTGTTTG-2,CBFB_1_CRISPRi|IRF1_1_CRISPRi,CBFB|IRF1,ENSG00000067955|ENSG00000125347,GCGGCAGGCAACGGCTGAGG|GCCCGAGCCCCGCCGAACCG

In [13]:
cur_data.adata.obs = cur_data.adata.obs.merge(
    guide_info_df,
    how='left',
    left_on='cell_barcode',
    right_on='cell_barcode'
)
cur_data.adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

,cell_barcode,perturbation_name,target_gene_name,target_gene_id,guide_sequence
0,AAACCTGAGAACAACT-1,IRF1_1_CRISPRi|MED11_1_CRISPRi|MED12_2_CRISPRi,IRF1|MED11|MED12,ENSG00000125347|ENSG00000161920|ENSG00000184634,GCCCGAGCCCCGCCGAACCG|GAACAAGCGTCGCGTTTCTG|GGCG...
1,AAACCTGAGAAGAAGC-1,CBFB_2_CRISPRi|Non-Targeting_6_CRISPRi,CBFB|control_nontargeting,ENSG00000067955|control_nontargeting,GGCAACGGCTGAGGCGGCGG|GAAACGAGAAGTTTGTACTA
2,AAACCTGAGAGAACAG-1,NaN,NaN,NaN,NaN
3,AAACCTGAGAGAGCTC-1,NaN,NaN,NaN,NaN
4,AAACCTGAGAGCTATA-1,IRF4_2_CRISPRi|KLF13_1_CRISPRi|MYB_1_CRISPRi,IRF4|KLF13|MYB,ENSG00000137265|ENSG00000169926|ENSG00000118513,TCGGAGCTGAGGGCAGCGGT|CCGGTTCTAAGGATGCCGAG|GGAG...
...,...,...,...,...,...
249794,TTTGTCATCGGATGGA-8,PRDM1_2_CRISPRi|TAF5L_2_CRISPRi|Non-Targeting_...,PRDM1|TAF5L|control_nontargeting,ENSG00000057657|ENSG00000135801|control_nontar...,GGCCCTCCAGTGTTGCGGAG|CGGCCGCCCAGAGCGGCGGC|TAAT...
249795,TTTGTCATCTCAAGTG-8,MED12_1_CRISPRi,MED12,ENSG00000184634,ACGGCGGCCGAGAGACAACA
249796,TTTGTCATCTCCGGTT-8,KLF13_1_CRISPRi,KLF13,ENSG00000169926,CCGGTTCTAAGGATGCCGAG
249797,TTTGTCATCTTGAGGT-8,BATF_2_CRISPRi|ATXN7L3_1_CRISPRi,BATF|ATXN7L3,ENSG00000156127|ENSG00000087152,TCCCTCTGCACCCCAGAGTG|ACTGCTCGCGCCTGCTAGAA
249798,TTTGTCATCTTTAGTC-8,NaN,NaN,NaN,NaN

### Replace NaNs with control_casonly

In [14]:
cur_data.adata.obs[cur_data.adata.obs.isna()] = 'control_casonly'
cur_data.adata.obs

,cell_barcode,perturbation_name,target_gene_name,target_gene_id,guide_sequence
0,AAACCTGAGAACAACT-1,IRF1_1_CRISPRi|MED11_1_CRISPRi|MED12_2_CRISPRi,IRF1|MED11|MED12,ENSG00000125347|ENSG00000161920|ENSG00000184634,GCCCGAGCCCCGCCGAACCG|GAACAAGCGTCGCGTTTCTG|GGCG...
1,AAACCTGAGAAGAAGC-1,CBFB_2_CRISPRi|Non-Targeting_6_CRISPRi,CBFB|control_nontargeting,ENSG00000067955|control_nontargeting,GGCAACGGCTGAGGCGGCGG|GAAACGAGAAGTTTGTACTA
2,AAACCTGAGAGAACAG-1,control_casonly,control_casonly,control_casonly,control_casonly
3,AAACCTGAGAGAGCTC-1,control_casonly,control_casonly,control_casonly,control_casonly
4,AAACCTGAGAGCTATA-1,IRF4_2_CRISPRi|KLF13_1_CRISPRi|MYB_1_CRISPRi,IRF4|KLF13|MYB,ENSG00000137265|ENSG00000169926|ENSG00000118513,TCGGAGCTGAGGGCAGCGGT|CCGGTTCTAAGGATGCCGAG|GGAG...
...,...,...,...,...,...
249794,TTTGTCATCGGATGGA-8,PRDM1_2_CRISPRi|TAF5L_2_CRISPRi|Non-Targeting_...,PRDM1|TAF5L|control_nontargeting,ENSG00000057657|ENSG00000135801|control_nontar...,GGCCCTCCAGTGTTGCGGAG|CGGCCGCCCAGAGCGGCGGC|TAAT...
249795,TTTGTCATCTCAAGTG-8,MED12_1_CRISPRi,MED12,ENSG00000184634,ACGGCGGCCGAGAGACAACA
249796,TTTGTCATCTCCGGTT-8,KLF13_1_CRISPRi,KLF13,ENSG00000169926,CCGGTTCTAAGGATGCCGAG
249797,TTTGTCATCTTGAGGT-8,BATF_2_CRISPRi|ATXN7L3_1_CRISPRi,BATF|ATXN7L3,ENSG00000156127|ENSG00000087152,TCCCTCTGCACCCCAGAGTG|ACTGCTCGCGCCTGCTAGAA
249798,TTTGTCATCTTTAGTC-8,control_casonly,control_casonly,control_casonly,control_casonly

### Standardise perturbation targets

In [15]:
cur_data.standardize_genes(
    slot='obs',
    input_column='target_gene_id',
    input_column_type='ensembl_gene_id',
    multiple_entries=True,
    remove_version=False,
    multiple_entries_sep='|'
    # version_sep='.'
)

--------------------------------------------------
Successfully mapped 30 out of 30 Ensembl IDs.
--------------------------------------------------
Collapsed column positional_index using separator |

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [16]:
cur_data.adata.obs.head()

,cell_barcode,target_gene_name,guide_sequence,target_gene_id,perturbation_name,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index
index,,,,,,,,,,,
0,AAACCTGAGAACAACT-1,IRF1|MED11|MED12,GCCCGAGCCCCGCCGAACCG|GAACAAGCGTCGCGTTTCTG|GGCG...,ENSG00000125347|ENSG00000161920|ENSG00000184634,IRF1_1_CRISPRi|MED11_1_CRISPRi|MED12_2_CRISPRi,ENSG00000125347|ENSG00000161920|ENSG00000184634,IRF1|MED11|MED12,protein_coding|protein_coding|protein_coding,chr5:132440440-132508719;-1|chr17:4731428-4733...,5|17|X,0|0|0
1,AAACCTGAGAAGAAGC-1,CBFB|control_nontargeting,GGCAACGGCTGAGGCGGCGG|GAAACGAGAAGTTTGTACTA,ENSG00000067955|control_nontargeting,CBFB_2_CRISPRi|Non-Targeting_6_CRISPRi,ENSG00000067955|control_nontargeting,CBFB|control_nontargeting,protein_coding|control_nontargeting,chr16:67028984-67101058;1|control_nontargeting,16|control_nontargeting,1|1
2,AAACCTGAGAGAACAG-1,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,2
3,AAACCTGAGAGAGCTC-1,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,3
4,AAACCTGAGAGCTATA-1,IRF4|KLF13|MYB,TCGGAGCTGAGGGCAGCGGT|CCGGTTCTAAGGATGCCGAG|GGAG...,ENSG00000137265|ENSG00000169926|ENSG00000118513,IRF4_2_CRISPRi|KLF13_1_CRISPRi|MYB_1_CRISPRi,ENSG00000137265|ENSG00000169926|ENSG00000118513,IRF4|KLF13|MYB,protein_coding|protein_coding|protein_coding,chr6:391739-411443;1|chr15:31326706-31435665;1...,6|15|6,4|4|4

### Add `perturbed_target_number` column

In [17]:
cur_data.count_entries(
    slot='obs',
    input_column='perturbed_target_symbol',
    count_column_name='perturbed_target_number',
    sep='|'
)

Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [18]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

In [19]:
cur_data.show_obs(['perturbation_name', 'perturbed_target_chromosome_encoding'])

Observation data:
DataFrame shape: (249799, 2)
--------------------------------------------------
                                        perturbation_name  \
index
0          IRF1_1_CRISPRi|MED11_1_CRISPRi|MED12_2_CRISPRi
1                  CBFB_2_CRISPRi|Non-Targeting_6_CRISPRi
2                                         control_casonly
3                                         control_casonly
4            IRF4_2_CRISPRi|KLF13_1_CRISPRi|MYB_1_CRISPRi
...                                                   ...
249794  PRDM1_2_CRISPRi|TAF5L_2_CRISPRi|Non-Targeting_...
249795                                    MED12_1_CRISPRi
249796                                    KLF13_1_CRISPRi
249797                   BATF_2_CRISPRi|ATXN7L3_1_CRISPRi
249798                                    control_casonly

        perturbed_target_chromosome_encoding
index
0                                          0
1                                          0
2                                          0
3                                          0
4                                          0
...                                      ...
249794                                     0
249795                                    23
249796                                    15
249797                                     0
249798                                     0

[249799 rows x 2 columns]
--------------------------------------------------

### Add metadata information from supplementary table 14

In [20]:
supp_s14 = pd.read_excel(
    "../supplementary/arce_2025/supplementary_tables/S14_metadata_Treg_Teff_perturbseq.xlsx",
    sheet_name="metadata_Treg_total_Teff_total_",
)
supp_s14 = supp_s14[["cell", "donor", "HTO_classification"]]
supp_s14 = supp_s14.rename(
    columns={"cell": "cell_barcode", "donor": "biological_replicate"}
)
supp_s14

              cell_barcode biological_replicate HTO_classification
0       AAACCTGAGTCTCCTC-1                    B       Resting-Teff
1       AAACCTGCAACCGCCA-1                    B       Resting-Teff
2       AAACCTGCACCCAGTG-1                    A       Resting-Teff
3       AAACCTGGTCCAAGTT-1                    A       Resting-Teff
4       AAACCTGGTGCACGAA-1                    A       Resting-Teff
...                    ...                  ...                ...
100082  TTTGTCAGTCCTAGCG-8                    A    Stimulated-Treg
100083  TTTGTCAGTGATAAAC-8                    A    Stimulated-Treg
100084  TTTGTCAGTGCCTGCA-8                    A    Stimulated-Treg
100085  TTTGTCAGTTCGTTGA-8                    A    Stimulated-Treg
100086  TTTGTCATCTCCGGTT-8                    A    Stimulated-Treg

[100087 rows x 3 columns]

In [21]:
cur_data.adata.obs = cur_data.adata.obs.merge(supp_s14, how="left", on="cell_barcode")

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Drop unmatched cells - these don't have metadata

In [22]:
cur_data.adata = cur_data.adata[cur_data.adata.obs['biological_replicate'].notna(),:]

In [23]:
cur_data.adata.obs

,cell_barcode,target_gene_name,guide_sequence,target_gene_id,perturbation_name,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding,biological_replicate,HTO_classification
14,AAACCTGAGTCTCCTC-1,DNMT1,GGGCAGCGAGATGGCCGGGA,ENSG00000130816,DNMT1_1_CRISPRi,ENSG00000130816,DNMT1,protein_coding,chr19:10133342-10231286;-1,19,14,1,19,B,Resting-Teff
15,AAACCTGCAAAGGAAG-1,USP22,GCGCCGAGAACAAAGCGCGG,ENSG00000124422,USP22_1_CRISPRi,ENSG00000124422,USP22,protein_coding,chr17:20999596-21043760;-1,17,15,1,17,A,Stimulated-Treg
16,AAACCTGCAACCGCCA-1,MYC,AGGCAGAGGGAGCGAGCGGG,ENSG00000136997,MYC_1_CRISPRi,ENSG00000136997,MYC,protein_coding,chr8:127735434-127742951;1,8,16,1,8,B,Resting-Teff
19,AAACCTGCAACTGGCC-1,STAT5B,CCAGCGCAGGCAACTCCGCG,ENSG00000173757,STAT5B_2_CRISPRi,ENSG00000173757,STAT5B,protein_coding,chr17:42199176-42288633;-1,17,19,1,17,B,Stimulated-Treg
21,AAACCTGCAAGCCCAC-1,PRDM1,GGCCCTCCAGTGTTGCGGAG,ENSG00000057657,PRDM1_2_CRISPRi,ENSG00000057657,PRDM1,protein_coding,chr6:105993463-106109939;1,6,21,1,6,B,Resting-Treg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249785,TTTGTCATCAGTTAGC-8,USP22,GCGCCGAGAACAAAGCGCGG,ENSG00000124422,USP22_1_CRISPRi,ENSG00000124422,USP22,protein_coding,chr17:20999596-21043760;-1,17,249785,1,17,B,Stimulated-Teff
249787,TTTGTCATCATGTGGT-8,ATXN7L3,GAGCGCGTGCATCTGCCCCG,ENSG00000087152,ATXN7L3_2_CRISPRi,ENSG00000087152,ATXN7L3,protein_coding,chr17:44191805-44200961;-1,17,249787,1,17,A,Resting-Teff
249788,TTTGTCATCCACGAAT-8,PRDM1,AGAGGCAAGAGCAGCGACCG,ENSG00000057657,PRDM1_1_CRISPRi,ENSG00000057657,PRDM1,protein_coding,chr6:105993463-106109939;1,6,249788,1,6,B,Resting-Treg
249795,TTTGTCATCTCAAGTG-8,MED12,ACGGCGGCCGAGAGACAACA,ENSG00000184634,MED12_1_CRISPRi,ENSG00000184634,MED12,protein_coding,chrX:71118543-71144103;1,X,249795,1,23,B,Resting-Teff
249796,TTTGTCATCTCCGGTT-8,KLF13,CCGGTTCTAAGGATGCCGAG,ENSG00000169926,KLF13_1_CRISPRi,ENSG00000169926,KLF13,protein_coding,chr15:31326706-31435665;1,15,249796,1,15,A,Stimulated-Treg

### Add metadata

In [24]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        "dataset_id": cur_data.dataset_id,
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        # perturbation type
        "perturbation_type_label": "CRISPRi",
        "perturbation_type_id": None,
        "data_modality": "Perturb-seq",
        "significant": None,
        "significance_criteria": None,
        "score_interpretation": None,

        # treatment
        # "treatment_label": None,
        # "treatment_id": None,
        # replicates
        "technical_replicate": None,
        # "biological_replicate": None,
        # model system
        "model_system_label": "primary_cell",
        "model_system_id": None,
        "tissue": "lymphoid tissue",
        "cell_line_label": None,
        "cell_line_id": None,
        # "cell_type_label": None,
        "disease_label": "healthy",
        "disease_id": None,

        "timepoint": "P10DT0H0M0S",
        "species": "Homo sapiens",
        "sex_label": None,
        "sex_id": None,
        "developmental_stage_label": None,
        "developmental_stage_id": None,

        "study_title": "Central control of dynamic gene circuits governs T cell rest and activation",
        "study_uri": "https://doi.org/10.1038/s41586-024-08314-y",
        "study_year": 2025,
        "first_author": "Maya M. Arce",
        "last_author": "Alexander Marson",

        "experiment_title": "Perturb-seq of primary human CD4+ T regulatory and T effector cells under resting and stimulated conditions",
        "experiment_summary": """
            Isolated human Tregs and Teffs from two healthy donors were stimulated with ImmunoCult CD3/CD28/CD2 activator and sequentially transduced with dCas9-KRAB-Zim3 lentivirus (24 hours post-stimulation) and a Perturb-seq guide library (48 hours post-stimulation, MOI 0.3). The library consisted of 28 regulators of IL-2Rα which were subset from Dolcetto library. Cells underwent continuous blasticidin selection starting 48 hours after the first transduction. On day 8, half of the cultures were restimulated using ImmunoCult CD3/CD28/CD2 activator. On day 10, cells were pooled by condition, sorted for live GFP+ expression, and stained with a TotalSeq™-C Universal Cocktail containing hashtag antibodies to distinguish cell types (CD4+ T-effector and T-regulatory) and stimulation conditions (Resting vs. Stimulated). The samples were subsequently processed using the 10x Genomics Chromium Next GEM Single Cell 5' HT v2 platform with Feature Barcode technology and sequenced on an Illumina NovaSeqX.
        """,

        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],

        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",

        "library_generation_method_id": None,
        "library_generation_method_label": "dCas9-KRAB-Zim3",

        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "lentivirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",

        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",

        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",

        "library_name": "Human CRISPR Inhibition Pooled Library (Dolcetto)",
        "library_uri": "https://www.addgene.org/pooled-library/broadgpp-human-crispri-dolcetto/",

        "library_format_id": None,
        "library_format_label": "pooled",

        "library_scope_id": None,
        "library_scope_label": "focused",

        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "inhibition",

        "library_manufacturer": "Doench lab",
        "library_lentiviral_generation": "3",
        "library_grnas_per_target": "2",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()),
        "library_total_variants": None,

        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",

        "readout_type_id": None,
        "readout_type_label": "transcriptomic",

        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",

        "method_name_id": None,
        "method_name_label": "Perturb-seq",

        "method_uri": None,

        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "10x Genomics Chromium Next GEM Single Cell 5-prime HT Kit v2",

        "sequencing_platform_id": None,
        "sequencing_platform_label": "Illumina NovaSeq X",

        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",

        "software_counts_id": None,
        "software_counts_label": "CellRanger",

        "software_analysis_id": None,
        "software_analysis_label": "Seurat",

        "reference_genome_id": None,
        "reference_genome_label": "GRCh38",
        
        "license_label": "free to use license",
        "license_id": "SWO:1000061",

        "associated_datasets": json.dumps([
            {
                "dataset_accession": "GSE278572",
                "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE278572",
                "dataset_description": "Raw counts; matrix.mtx, features.tsv, barcodes.tsv",
                "dataset_file_name": "GSE278572_*.*",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column technical_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_line_id added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_manufacturer added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/.venv/lib/python3.12/site-packages/anndata/_core/anndata.py:1793: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

### Curate tissue information

In [25]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
      input_column input_column_lower       name_lower     ontology_id
0  lymphoid tissue    lymphoid tissue  lymphoid tissue  UBERON:0001744
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [26]:
cur_data.adata.obs["cell_type"] = cur_data.adata.obs["HTO_classification"].replace(
    {
        "Resting-Teff": "effector CD4-positive, alpha-beta T cell",
        "Stimulated-Teff": "effector CD4-positive, alpha-beta T cell",
        "Resting-Treg": "CD4-positive, CD25-positive, alpha-beta regulatory T cell",
        "Stimulated-Treg": "CD4-positive, CD25-positive, alpha-beta regulatory T cell"
    }
)

In [27]:
cur_data.standardize_ontology(
    input_column='cell_type',
    column_type='term_name',
    ontology_type='cell_type',
    overwrite=True
)

Mapped 2 cell_type ontology terms from `cell_type` column to ontology terms
DataFrame shape: (2, 4)
--------------------------------------------------
                                        input_column  \
0           effector CD4-positive, alpha-beta T cell
1  CD4-positive, CD25-positive, alpha-beta regula...

                                  input_column_lower  \
0           effector cd4-positive, alpha-beta t cell
1  cd4-positive, cd25-positive, alpha-beta regula...

                                          name_lower ontology_id
0           effector cd4-positive, alpha-beta t cell  CL:0001044
1  cd4-positive, cd25-positive, alpha-beta regula...  CL:0000792
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell line information

In [28]:
# cur_data.standardize_ontology(
#     input_column='cell_line_label',
#     column_type='term_name',
#     ontology_type='cell_line',
#     overwrite=True
# )

### Curate disease information

In [29]:
cur_data.standardize_ontology(
    input_column='disease_label',
    column_type='term_name',
    ontology_type='disease',
    overwrite=True
)

Warning: No disease ontology terms could be mapped from `disease_label` column to ontology terms. Map the terms manually or check the input column for errors.

### Curate treatment information

In [30]:
cur_data.adata.obs["treatment_label"] = cur_data.adata.obs["HTO_classification"].replace(
    {
        "Resting-Teff": "Untreated Control",
        "Resting-Treg": "Untreated Control",
        "Stimulated-Teff": "anti-CD3 antibody|anti-CD28 antibody|anti-CD2 antibody",
        "Stimulated-Treg": "anti-CD3 antibody|anti-CD28 antibody|anti-CD2 antibody",
    }
)
cur_data.adata.obs["treatment_id"] = cur_data.adata.obs["HTO_classification"].replace(
    {
        "Resting-Teff": "NCIT:C184729",
        "Resting-Treg": "NCIT:C184729",
        "Stimulated-Teff": "EFO:0003317|EFO:0003304|NCIT:C184729",
        "Stimulated-Treg": "EFO:0003317|EFO:0003304|NCIT:C184729",
    }
)

### Match schema column order

In [31]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [32]:
cur_data.validate_data(slot='obs', verbose=True)

2026-04-28 13:29:51,226 INFO curation_tools.curation_tools: adata.obs is valid according to the obs_schema.

,dataset_id,sample_id,cell_barcode,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,arce_2025,1,AAACCTGAGTCTCCTC-1,Perturb-seq,<NA>,<NA>,DNMT1_1_CRISPRi,chr19:10133342-10231286;-1,19,19,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
1,arce_2025,2,AAACCTGCAAAGGAAG-1,Perturb-seq,<NA>,<NA>,USP22_1_CRISPRi,chr17:20999596-21043760;-1,17,17,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
2,arce_2025,3,AAACCTGCAACCGCCA-1,Perturb-seq,<NA>,<NA>,MYC_1_CRISPRi,chr8:127735434-127742951;1,8,8,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
3,arce_2025,4,AAACCTGCAACTGGCC-1,Perturb-seq,<NA>,<NA>,STAT5B_2_CRISPRi,chr17:42199176-42288633;-1,17,17,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
4,arce_2025,5,AAACCTGCAAGCCCAC-1,Perturb-seq,<NA>,<NA>,PRDM1_2_CRISPRi,chr6:105993463-106109939;1,6,6,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100082,arce_2025,100083,TTTGTCATCAGTTAGC-8,Perturb-seq,<NA>,<NA>,USP22_1_CRISPRi,chr17:20999596-21043760;-1,17,17,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
100083,arce_2025,100084,TTTGTCATCATGTGGT-8,Perturb-seq,<NA>,<NA>,ATXN7L3_2_CRISPRi,chr17:44191805-44200961;-1,17,17,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
100084,arce_2025,100085,TTTGTCATCCACGAAT-8,Perturb-seq,<NA>,<NA>,PRDM1_1_CRISPRi,chr6:105993463-106109939;1,6,6,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
100085,arce_2025,100086,TTTGTCATCTCAAGTG-8,Perturb-seq,<NA>,<NA>,MED12_1_CRISPRi,chrX:71118543-71144103;1,X,23,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061
100086,arce_2025,100087,TTTGTCATCTCCGGTT-8,Perturb-seq,<NA>,<NA>,KLF13_1_CRISPRi,chr15:31326706-31435665;1,15,15,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE278572"", ""dataset_u...",free to use license,SWO:1000061

# VAR slot curation

### Standardise genes

In [33]:
cur_data.show_var()

Variable data:
DataFrame shape: (36601, 2)
--------------------------------------------------
                    gene_ids    feature_types
MIR1302-2HG  ENSG00000243485  Gene Expression
FAM138A      ENSG00000237613  Gene Expression
OR4F5        ENSG00000186092  Gene Expression
AL627309.1   ENSG00000238009  Gene Expression
AL627309.3   ENSG00000239945  Gene Expression
...                      ...              ...
AC141272.1   ENSG00000277836  Gene Expression
AC023491.2   ENSG00000278633  Gene Expression
AC007325.1   ENSG00000276017  Gene Expression
AC007325.4   ENSG00000278817  Gene Expression
AC007325.2   ENSG00000277196  Gene Expression

[36601 rows x 2 columns]
--------------------------------------------------

In [34]:
cur_data.standardize_genes(
    slot="var",
    input_column="gene_ids",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

Missing Ensembl IDs: ['ENSG00000273203', 'ENSG00000272979', 'ENSG00000267243', 'ENSG00000261470', 'ENSG00000237954', 'ENSG00000258170', 'ENSG00000243179', 'ENSG00000278878', 'ENSG00000228334', 'ENSG00000275249', 'ENSG00000263316', 'ENSG00000273301', 'ENSG00000229628', 'ENSG00000231255', 'ENSG00000235450', 'ENSG00000286997', 'ENSG00000251679', 'ENSG00000237975', 'ENSG00000229694', 'ENSG00000287906', 'ENSG00000182584', 'ENSG00000264078', 'ENSG00000250431', 'ENSG00000251518', 'ENSG00000286895', 'ENSG00000272592', 'ENSG00000228216', 'ENSG00000229964', 'ENSG00000249069', 'ENSG00000224228', 'ENSG00000215159', 'ENSG00000288436', 'ENSG00000235665', 'ENSG00000274307', 'ENSG00000248359', 'ENSG00000224247', 'ENSG00000286792', 'ENSG00000249125', 'ENSG00000229160', 'ENSG00000272146', 'ENSG00000230699', 'ENSG00000267637', 'ENSG00000270178', 'ENSG00000232597', 'ENSG00000277010', 'ENSG00000259436', 'ENSG00000236451', 'ENSG00000258196', 'ENSG00000236453', 'ENSG00000286564', 'ENSG00000241084', 'ENSG00000204805', 'ENSG00000225932', 'ENSG00000203441', 'ENSG00000256222', 'ENSG00000179082', 'ENSG00000280767', 'ENSG00000254731', 'ENSG00000231054', 'ENSG00000244693', 'ENSG00000224532', 'ENSG00000243220', 'ENSG00000258131', 'ENSG00000231846', 'ENSG00000231575', 'ENSG00000272482', 'ENSG00000272948', 'ENSG00000283633', 'ENSG00000287139', 'ENSG00000226079', 'ENSG00000256101', 'ENSG00000273123', 'ENSG00000267070', 'ENSG00000232692', 'ENSG00000286817', 'ENSG00000224525', 'ENSG00000254290', 'ENSG00000229912', 'ENSG00000225527', 'ENSG00000264790', 'ENSG00000235242', 'ENSG00000272923', 'ENSG00000278633', 'ENSG00000233005', 'ENSG00000272872', 'ENSG00000272137', 'ENSG00000267776', 'ENSG00000285759', 'ENSG00000253735', 'ENSG00000226822', 'ENSG00000233818', 'ENSG00000273119', 'ENSG00000266588', 'ENSG00000272369', 'ENSG00000236262', 'ENSG00000255568', 'ENSG00000272567', 'ENSG00000285155', 'ENSG00000271409', 'ENSG00000248346', 'ENSG00000255169', 'ENSG00000248671', 'ENSG00000176659', 'ENSG00000253197', 'ENSG00000261120', 'ENSG00000286778', 'ENSG00000237327', 'ENSG00000275294', 'ENSG00000258919', 'ENSG00000225085', 'ENSG00000263698', 'ENSG00000285424', 'ENSG00000255945', 'ENSG00000250670', 'ENSG00000253369', 'ENSG00000251654', 'ENSG00000262089', 'ENSG00000259604', 'ENSG00000227920', 'ENSG00000249984', 'ENSG00000288055', 'ENSG00000256739', 'ENSG00000272971', 'ENSG00000250948', 'ENSG00000272009', 'ENSG00000227683', 'ENSG00000261445', 'ENSG00000274444', 'ENSG00000240355', 'ENSG00000244063', 'ENSG00000267787', 'ENSG00000214732', 'ENSG00000264080', 'ENSG00000240996', 'ENSG00000285922', 'ENSG00000238266', 'ENSG00000259209', 'ENSG00000233415', 'ENSG00000259761', 'ENSG00000285584', 'ENSG00000241792', 'ENSG00000287798', 'ENSG00000286859', 'ENSG00000236094', 'ENSG00000270394', 'ENSG00000273923', 'ENSG00000286420', 'ENSG00000278674', 'ENSG00000272519', 'ENSG00000277501', 'ENSG00000272736', 'ENSG00000249159', 'ENSG00000259222', 'ENSG00000287875', 'ENSG00000271156', 'ENSG00000253414', 'ENSG00000250012', 'ENSG00000287176', 'ENSG00000226403', 'ENSG00000259618', 'ENSG00000253444', 'ENSG00000272085', 'ENSG00000273554', 'ENSG00000259760', 'ENSG00000226362', 'ENSG00000261438', 'ENSG00000227917', 'ENSG00000238102', 'ENSG00000281920', 'ENSG00000255823', 'ENSG00000269899', 'ENSG00000228008', 'ENSG00000233776', 'ENSG00000235337', 'ENSG00000254420', 'ENSG00000287884', 'ENSG00000258918', 'ENSG00000286330', 'ENSG00000277666', 'ENSG00000229401', 'ENSG00000280560', 'ENSG00000283440', 'ENSG00000241317', 'ENSG00000272049', 'ENSG00000261720', 'ENSG00000287346', 'ENSG00000277475', 'ENSG00000287811', 'ENSG00000253584', 'ENSG00000273164', 'ENSG00000261159', 'ENSG00000274847', 'ENSG00000257879', 'ENSG00000270147', 'ENSG00000224167', 'ENSG00000258844', 'ENSG00000271870', 'ENSG00000241280', 'ENSG00000249684', 'ENSG00000260090', 'ENSG00000287682', 'ENSG00000253139', 'ENSG00000272440', 'ENSG00000225742', 'ENSG00000258772', 'ENSG00000240240', 'ENSG00000275216', 'ENSG00000258345', 'ENSG00000259038', 'ENSG00000214970', 'ENSG00000253931', 'ENSG00000255015', 'ENSG00000269894', 'ENSG00000287313', 'ENSG00000232325', 'ENSG00000234283', 'ENSG00000268509', 'ENSG00000262890', 'ENSG00000253859', 'ENSG00000260951', 'ENSG00000227029', 'ENSG00000287941', 'ENSG00000270157', 'ENSG00000287753', 'ENSG00000231305', 'ENSG00000251506', 'ENSG00000258342', 'ENSG00000265091', 'ENSG00000251454', 'ENSG00000248533', 'ENSG00000266614', 'ENSG00000257277', 'ENSG00000250511', 'ENSG00000222022', 'ENSG00000272240', 'ENSG00000249708', 'ENSG00000248518', 'ENSG00000258777', 'ENSG00000279949', 'ENSG00000259274', 'ENSG00000223808', 'ENSG00000257454', 'ENSG00000273289', 'ENSG00000233143', 'ENSG00000260030', 'ENSG00000170152', 'ENSG00000288046', 'ENSG00000258216', 'ENSG00000214955', 'ENSG00000236008', 'ENSG00000235578', 'ENSG00000287492', 'ENSG00000251652', 'ENSG00000277196', 'ENSG00000267697', 'ENSG00000259664', 'ENSG00000274791', 'ENSG00000256045', 'ENSG00000231633', 'ENSG00000251379', 'ENSG00000188525', 'ENSG00000283003', 'ENSG00000258301', 'ENSG00000286911', 'ENSG00000265943', 'ENSG00000267537', 'ENSG00000237585', 'ENSG00000213029', 'ENSG00000270154', 'ENSG00000260409', 'ENSG00000256732', 'ENSG00000272551', 'ENSG00000282863', 'ENSG00000277901', 'ENSG00000253381', 'ENSG00000286941', 'ENSG00000233213', 'ENSG00000233937', 'ENSG00000269072', 'ENSG00000270114', 'ENSG00000224621', 'ENSG00000283164', 'ENSG00000233844', 'ENSG00000230156', 'ENSG00000259762', 'ENSG00000250360', 'ENSG00000286687', 'ENSG00000287954', 'ENSG00000287564', 'ENSG00000286094', 'ENSG00000261044', 'ENSG00000231877', 'ENSG00000257715', 'ENSG00000233193', 'ENSG00000232056', 'ENSG00000261502', 'ENSG00000238158', 'ENSG00000273388', 'ENSG00000260060', 'ENSG00000260276', 'ENSG00000232243', 'ENSG00000231140', 'ENSG00000262039', 'ENSG00000259587', 'ENSG00000251678', 'ENSG00000268333', 'ENSG00000257164', 'ENSG00000230381', 'ENSG00000258885', 'ENSG00000267388', 'ENSG00000253766', 'ENSG00000239462', 'ENSG00000287865', 'ENSG00000258831', 'ENSG00000259855', 'ENSG00000285399', 'ENSG00000260071', 'ENSG00000251416', 'ENSG00000224819', 'ENSG00000236412', 'ENSG00000225916', 'ENSG00000229463', 'ENSG00000282440', 'ENSG00000273374', 'ENSG00000233970', 'ENSG00000225836', 'ENSG00000236938', 'ENSG00000255279', 'ENSG00000274652', 'ENSG00000253842', 'ENSG00000276760', 'ENSG00000223795', 'ENSG00000241520', 'ENSG00000263508', 'ENSG00000273888', 'ENSG00000228113', 'ENSG00000237422', 'ENSG00000255272', 'ENSG00000228561', 'ENSG00000276649', 'ENSG00000273771', 'ENSG00000263588', 'ENSG00000250237', 'ENSG00000236129', 'ENSG00000228951', 'ENSG00000273748', 'ENSG00000272564', 'ENSG00000257918', 'ENSG00000258808', 'ENSG00000280095', 'ENSG00000272644', 'ENSG00000273373', 'ENSG00000286504', 'ENSG00000225643', 'ENSG00000286189', 'ENSG00000275636', 'ENSG00000270195', 'ENSG00000233852', 'ENSG00000282080', 'ENSG00000278704', 'ENSG00000183729', 'ENSG00000248646', 'ENSG00000227021', 'ENSG00000278198', 'ENSG00000286499', 'ENSG00000204398', 'ENSG00000223797', 'ENSG00000237513', 'ENSG00000259126', 'ENSG00000271895', 'ENSG00000272354', 'ENSG00000259998', 'ENSG00000272953', 'ENSG00000269933', 'ENSG00000233376', 'ENSG00000286906', 'ENSG00000284930', 'ENSG00000251613', 'ENSG00000262668', 'ENSG00000235285', 'ENSG00000251144', 'ENSG00000237356', 'ENSG00000233906', 'ENSG00000272732', 'ENSG00000276471', 'ENSG00000241770', 'ENSG00000267517', 'ENSG00000270055', 'ENSG00000286996', 'ENSG00000286978', 'ENSG00000287487', 'ENSG00000253805', 'ENSG00000237262', 'ENSG00000227011', 'ENSG00000244545', 'ENSG00000260517', 'ENSG00000267521', 'ENSG00000257962', 'ENSG00000286228', 'ENSG00000268423', 'ENSG00000223910', 'ENSG00000225329', 'ENSG00000260461', 'ENSG00000261273', 'ENSG00000286511', 'ENSG00000272954', 'ENSG00000272840', 'ENSG00000228135', 'ENSG00000231483', 'ENSG00000286825', 'ENSG00000288111', 'ENSG00000287361', 'ENSG00000255479', 'ENSG00000254740', 'ENSG00000286534', 'ENSG00000249335', 'ENSG00000277203', 'ENSG00000228906', 'ENSG00000239674', 'ENSG00000258386', 'ENSG00000230600', 'ENSG00000131484', 'ENSG00000228393', 'ENSG00000264212', 'ENSG00000282021', 'ENSG00000268615', 'ENSG00000226849', 'ENSG00000255599', 'ENSG00000286293', 'ENSG00000230427', 'ENSG00000267131', 'ENSG00000254143', 'ENSG00000230205', 'ENSG00000238042', 'ENSG00000258861', 'ENSG00000272593', 'ENSG00000287974', 'ENSG00000284700', 'ENSG00000260780', 'ENSG00000285766', 'ENSG00000286439', 'ENSG00000273370', 'ENSG00000274956', 'ENSG00000274902', 'ENSG00000267702', 'ENSG00000262031', 'ENSG00000243176', 'ENSG00000286824', 'ENSG00000263388', 'ENSG00000256686', 'ENSG00000257711', 'ENSG00000258092', 'ENSG00000287729', 'ENSG00000255495', 'ENSG00000285535', 'ENSG00000243944', 'ENSG00000146521', 'ENSG00000273765', 'ENSG00000259594', 'ENSG00000250777', 'ENSG00000272583', 'ENSG00000280366', 'ENSG00000261797', 'ENSG00000183791', 'ENSG00000182230', 'ENSG00000237548', 'ENSG00000251218', 'ENSG00000224342', 'ENSG00000286475', 'ENSG00000260182', 'ENSG00000254427', 'ENSG00000249203', 'ENSG00000285877', 'ENSG00000225655', 'ENSG00000261773', 'ENSG00000272308', 'ENSG00000273890', 'ENSG00000235209', 'ENSG00000286919', 'ENSG00000269888', 'ENSG00000287702', 'ENSG00000287316', 'ENSG00000257226', 'ENSG00000254821', 'ENSG00000234306', 'ENSG00000254814', 'ENSG00000261650', 'ENSG00000244650', 'ENSG00000222030', 'ENSG00000244349', 'ENSG00000232680', 'ENSG00000259972', 'ENSG00000287712', 'ENSG00000269391', 'ENSG00000253960', 'ENSG00000228434', 'ENSG00000237133', 'ENSG00000276250', 'ENSG00000287248', 'ENSG00000286572', 'ENSG00000285656', 'ENSG00000276075', 'ENSG00000225058', 'ENSG00000224745', 'ENSG00000254120', 'ENSG00000283689', 'ENSG00000231173', 'ENSG00000264067', 'ENSG00000250284', 'ENSG00000235271', 'ENSG00000287686', 'ENSG00000234698', 'ENSG00000261135', 'ENSG00000223811', 'ENSG00000259995', 'ENSG00000285808', 'ENSG00000232749', 'ENSG00000232294', 'ENSG00000255325', 'ENSG00000248991', 'ENSG00000286761', 'ENSG00000286466', 'ENSG00000261666', 'ENSG00000232411', 'ENSG00000267279', 'ENSG00000265174', 'ENSG00000286519', 'ENSG00000285447', 'ENSG00000259616', 'ENSG00000263081', 'ENSG00000227305', 'ENSG00000280374', 'ENSG00000284602', 'ENSG00000273211', 'ENSG00000272444', 'ENSG00000287523', 'ENSG00000287446', 'ENSG00000253844', 'ENSG00000248240', 'ENSG00000256892', 'ENSG00000286977', 'ENSG00000203812', 'ENSG00000235852', 'ENSG00000237838', 'ENSG00000233256', 'ENSG00000276278', 'ENSG00000286213', 'ENSG00000284824', 'ENSG00000253985', 'ENSG00000250415', 'ENSG00000285106', 'ENSG00000272341', 'ENSG00000280987', 'ENSG00000287386', 'ENSG00000273038', 'ENSG00000235795', 'ENSG00000276269', 'ENSG00000204683', 'ENSG00000283480', 'ENSG00000274897', 'ENSG00000233517', 'ENSG00000236856', 'ENSG00000272382', 'ENSG00000272370', 'ENSG00000139656', 'ENSG00000279159', 'ENSG00000250158', 'ENSG00000287569', 'ENSG00000276345', 'ENSG00000112096', 'ENSG00000233029', 'ENSG00000277352', 'ENSG00000272468', 'ENSG00000253774', 'ENSG00000276790', 'ENSG00000263574', 'ENSG00000233536', 'ENSG00000235215', 'ENSG00000261193', 'ENSG00000267406', 'ENSG00000229458', 'ENSG00000250046', 'ENSG00000261068', 'ENSG00000257654', 'ENSG00000260793', 'ENSG00000258414', 'ENSG00000250174', 'ENSG00000256050', 'ENSG00000287211', 'ENSG00000273496', 'ENSG00000267105', 'ENSG00000270265', 'ENSG00000286931', 'ENSG00000272218', 'ENSG00000232949', 'ENSG00000226751', 'ENSG00000272070', 'ENSG00000234223', 'ENSG00000264608', 'ENSG00000236716', 'ENSG00000257194', 'ENSG00000233840', 'ENSG00000238009', 'ENSG00000277423', 'ENSG00000266002', 'ENSG00000275063', 'ENSG00000267683', 'ENSG00000263264', 'ENSG00000283886', 'ENSG00000235047', 'ENSG00000279987', 'ENSG00000263688', 'ENSG00000287858', 'ENSG00000223704', 'ENSG00000251044', 'ENSG00000286699', 'ENSG00000287440', 'ENSG00000266248', 'ENSG00000230565', 'ENSG00000265717', 'ENSG00000249122', 'ENSG00000239265', 'ENSG00000256257', 'ENSG00000258949', 'ENSG00000286542', 'ENSG00000169763', 'ENSG00000287263', 'ENSG00000273466', 'ENSG00000243135', 'ENSG00000250957', 'ENSG00000260141', 'ENSG00000247810', 'ENSG00000274367', 'ENSG00000221995', 'ENSG00000225986', 'ENSG00000257603', 'ENSG00000223469', 'ENSG00000278514', 'ENSG00000263443', 'ENSG00000271751', 'ENSG00000272304', 'ENSG00000256694', 'ENSG00000286133', 'ENSG00000277999', 'ENSG00000239801', 'ENSG00000286397', 'ENSG00000253983', 'ENSG00000286016', 'ENSG00000249381', 'ENSG00000274744', 'ENSG00000287168', 'ENSG00000233799', 'ENSG00000287411', 'ENSG00000261305', 'ENSG00000228538', 'ENSG00000234134', 'ENSG00000259939', 'ENSG00000234296', 'ENSG00000271904', 'ENSG00000223821', 'ENSG00000287837', 'ENSG00000235736', 'ENSG00000249008', 'ENSG00000286462', 'ENSG00000241572', 'ENSG00000230506', 'ENSG00000268674', 'ENSG00000258028', 'ENSG00000276017', 'ENSG00000286262', 'ENSG00000278782', 'ENSG00000261386', 'ENSG00000277761', 'ENSG00000260100', 'ENSG00000236501', 'ENSG00000259298', 'ENSG00000248432', 'ENSG00000249604', 'ENSG00000282965', 'ENSG00000256542', 'ENSG00000203520', 'ENSG00000258631', 'ENSG00000226380', 'ENSG00000251314', 'ENSG00000234677', 'ENSG00000260983', 'ENSG00000255944', 'ENSG00000224218', 'ENSG00000278384', 'ENSG00000223458', 'ENSG00000270030', 'ENSG00000273481', 'ENSG00000265964', 'ENSG00000229454', 'ENSG00000234936', 'ENSG00000212978', 'ENSG00000231883', 'ENSG00000269028', 'ENSG00000250551', 'ENSG00000228452', 'ENSG00000232311', 'ENSG00000287622', 'ENSG00000224739', 'ENSG00000261775', 'ENSG00000277050', 'ENSG00000224884', 'ENSG00000249091', 'ENSG00000254306', 'ENSG00000286472', 'ENSG00000227540', 'ENSG00000267643', 'ENSG00000241636', 'ENSG00000251336', 'ENSG00000235994', 'ENSG00000286949', 'ENSG00000288380', 'ENSG00000261039', 'ENSG00000268955', 'ENSG00000287649', 'ENSG00000229352', 'ENSG00000287824', 'ENSG00000272746', 'ENSG00000272880', 'ENSG00000250156', 'ENSG00000239498', 'ENSG00000253878', 'ENSG00000262292', 'ENSG00000234083', 'ENSG00000264334', 'ENSG00000273486', 'ENSG00000287368', 'ENSG00000225790', 'ENSG00000234405', 'ENSG00000270016', 'ENSG00000239665', 'ENSG00000277559', 'ENSG00000224959', 'ENSG00000249269', 'ENSG00000240440', 'ENSG00000283907', 'ENSG00000228353', 'ENSG00000255394', 'ENSG00000226078', 'ENSG00000272030', 'ENSG00000260095', 'ENSG00000258642', 'ENSG00000266450', 'ENSG00000268355', 'ENSG00000278927', 'ENSG00000232386', 'ENSG00000272040', 'ENSG00000272755', 'ENSG00000229403', 'ENSG00000244247', 'ENSG00000261490', 'ENSG00000230090', 'ENSG00000286265', 'ENSG00000230836', 'ENSG00000286329', 'ENSG00000273403', 'ENSG00000286889', 'ENSG00000278817', 'ENSG00000169807', 'ENSG00000248942', 'ENSG00000249860', 'ENSG00000248265', 'ENSG00000235815', 'ENSG00000250078', 'ENSG00000271911', 'ENSG00000268050', 'ENSG00000206129', 'ENSG00000288101', 'ENSG00000287127', 'ENSG00000269927', 'ENSG00000263464', 'ENSG00000259255', 'ENSG00000285162', 'ENSG00000267636', 'ENSG00000250060', 'ENSG00000254651', 'ENSG00000229191', 'ENSG00000285933', 'ENSG00000276631', 'ENSG00000258407', 'ENSG00000237845', 'ENSG00000286863', 'ENSG00000239467', 'ENSG00000273733', 'ENSG00000256427', 'ENSG00000228890', 'ENSG00000259834', 'ENSG00000169789', 'ENSG00000254180', 'ENSG00000239332', 'ENSG00000288002', 'ENSG00000249492', 'ENSG00000228421', 'ENSG00000261190', 'ENSG00000236714', 'ENSG00000255160', 'ENSG00000231128', 'ENSG00000286494', 'ENSG00000273729', 'ENSG00000286755', 'ENSG00000287788', 'ENSG00000236673', 'ENSG00000266601', 'ENSG00000286633', 'ENSG00000258137', 'ENSG00000237461', 'ENSG00000255028', 'ENSG00000262558', 'ENSG00000283255', 'ENSG00000242021', 'ENSG00000286827', 'ENSG00000250686', 'ENSG00000229646', 'ENSG00000253762', 'ENSG00000223504', 'ENSG00000269900', 'ENSG00000278923', 'ENSG00000215271', 'ENSG00000260581', 'ENSG00000260511', 'ENSG00000254619', 'ENSG00000232034', 'ENSG00000234166', 'ENSG00000258921', 'ENSG00000276854', 'ENSG00000258473', 'ENSG00000226747', 'ENSG00000280710', 'ENSG00000234141', 'ENSG00000236166', 'ENSG00000223379', 'ENSG00000228478', 'ENSG00000227925', 'ENSG00000287388', 'ENSG00000254587', 'ENSG00000236839', 'ENSG00000273576', 'ENSG00000257477', 'ENSG00000228358', 'ENSG00000250418', 'ENSG00000286603', 'ENSG00000254615', 'ENSG00000280273', 'ENSG00000224481', 'ENSG00000254039', 'ENSG00000286362', 'ENSG00000242396', 'ENSG00000276397', 'ENSG00000271788', 'ENSG00000258081', 'ENSG00000258600', 'ENSG00000286374', 'ENSG00000260470', 'ENSG00000248202', 'ENSG00000285875', 'ENSG00000278955', 'ENSG00000130723', 'ENSG00000246627', 'ENSG00000233214', 'ENSG00000264443', 'ENSG00000256001', 'ENSG00000249638', 'ENSG00000232196', 'ENSG00000277400', 'ENSG00000273319', 'ENSG00000204092', 'ENSG00000270019', 'ENSG00000228106', 'ENSG00000276256', 'ENSG00000248311', 'ENSG00000256374', 'ENSG00000225640', 'ENSG00000254561', 'ENSG00000228648', 'ENSG00000248103', 'ENSG00000268262', 'ENSG00000286351', 'ENSG00000262180', 'ENSG00000228503', 'ENSG00000286087', 'ENSG00000236996', 'ENSG00000234540', 'ENSG00000276814', 'ENSG00000276348', 'ENSG00000266908', 'ENSG00000250234', 'ENSG00000286601', 'ENSG00000233342', 'ENSG00000267058', 'ENSG00000272267', 'ENSG00000235245', 'ENSG00000249731', 'ENSG00000274031', 'ENSG00000270105', 'ENSG00000226377', 'ENSG00000250310', 'ENSG00000265975', 'ENSG00000261222', 'ENSG00000240875', 'ENSG00000249463', 'ENSG00000283648', 'ENSG00000225163', 'ENSG00000282887', 'ENSG00000235491', 'ENSG00000258785', 'ENSG00000255644', 'ENSG00000233408', 'ENSG00000255817', 'ENSG00000278266', 'ENSG00000285660', 'ENSG00000286079', 'ENSG00000287101', 'ENSG00000268364', 'ENSG00000277836', 'ENSG00000248787', 'ENSG00000244952', 'ENSG00000258088', 'ENSG00000271254', 'ENSG00000277630', 'ENSG00000232295', 'ENSG00000259123', 'ENSG00000274175', 'ENSG00000253891', 'ENSG00000259359', 'ENSG00000235934', 'ENSG00000242375', 'ENSG00000253737', 'ENSG00000234998', 'ENSG00000263677', 'ENSG00000255328', 'ENSG00000273837', 'ENSG00000256271', 'ENSG00000274828', 'ENSG00000244268', 'ENSG00000257183', 'ENSG00000285782', 'ENSG00000254364', 'ENSG00000286723', 'ENSG00000244620', 'ENSG00000253671', 'ENSG00000234902', 'ENSG00000287843', 'ENSG00000259407', 'ENSG00000254927', 'ENSG00000254138', 'ENSG00000260759', 'ENSG00000259423', 'ENSG00000286854', 'ENSG00000269926', 'ENSG00000274792', 'ENSG00000232636', 'ENSG00000276251', 'ENSG00000267420', 'ENSG00000239216', 'ENSG00000286080', 'ENSG00000148362', 'ENSG00000250410', 'ENSG00000286501', 'ENSG00000261218', 'ENSG00000241180', 'ENSG00000258265', 'ENSG00000259376', 'ENSG00000253484', 'ENSG00000264421', 'ENSG00000242753', 'ENSG00000267115', 'ENSG00000278011', 'ENSG00000273181', 'ENSG00000258927', 'ENSG00000241912', 'ENSG00000264660', 'ENSG00000287350', 'ENSG00000253256', 'ENSG00000278626', 'ENSG00000286571', 'ENSG00000257613', 'ENSG00000272922', 'ENSG00000236760', 'ENSG00000259306', 'ENSG00000260163', 'ENSG00000182912', 'ENSG00000227220', 'ENSG00000249184', 'ENSG00000287868', 'ENSG00000254028', 'ENSG00000250716', 'ENSG00000229881', 'ENSG00000237352', 'ENSG00000272541', 'ENSG00000286103', 'ENSG00000274312', 'ENSG00000261462', 'ENSG00000287944', 'ENSG00000267316', 'ENSG00000260183', 'ENSG00000288019', 'ENSG00000230525', 'ENSG00000254695', 'ENSG00000261534', 'ENSG00000240401', 'ENSG00000271955', 'ENSG00000238358', 'ENSG00000229611', 'ENSG00000286292', 'ENSG00000184258', 'ENSG00000287438', 'ENSG00000278107', 'ENSG00000286915', 'ENSG00000271734', 'ENSG00000285719', 'ENSG00000237359', 'ENSG00000265671', 'ENSG00000230641', 'ENSG00000272650', 'ENSG00000264920', 'ENSG00000264072', 'ENSG00000254095', 'ENSG00000267449', 'ENSG00000236263', 'ENSG00000259820', 'ENSG00000256287', 'ENSG00000230971', 'ENSG00000263331', 'ENSG00000269873', 'ENSG00000224204', 'ENSG00000237940', 'ENSG00000253115', 'ENSG00000249988', 'ENSG00000234229', 'ENSG00000236948', 'ENSG00000259166', 'ENSG00000250446', 'ENSG00000275869', 'ENSG00000258998', 'ENSG00000267399', 'ENSG00000283504', 'ENSG00000228255', 'ENSG00000224758', 'ENSG00000261737', 'ENSG00000239407', 'ENSG00000249166', 'ENSG00000270038', 'ENSG00000287557', 'ENSG00000285191', 'ENSG00000270188', 'ENSG00000241475', 'ENSG00000286815', 'ENSG0000

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [35]:
cur_data.show_var()

Variable data:
DataFrame shape: (36601, 5)
--------------------------------------------------
         feature_types         gene_ids  ensembl_gene_id  gene_symbol  \
index
0      Gene Expression  ENSG00000243485  ENSG00000243485  MIR1302-2HG
1      Gene Expression  ENSG00000237613  ENSG00000237613      FAM138A
2      Gene Expression  ENSG00000186092  ENSG00000186092        OR4F5
3      Gene Expression  ENSG00000238009  ENSG00000241860          NaN
4      Gene Expression  ENSG00000239945  ENSG00000239945         None
...                ...              ...              ...          ...
36596  Gene Expression  ENSG00000277836  ENSG00000277836          NaN
36597  Gene Expression  ENSG00000278633  ENSG00000278633          NaN
36598  Gene Expression  ENSG00000276017  ENSG00000276017          NaN
36599  Gene Expression  ENSG00000278817  ENSG00000278817          NaN
36600  Gene Expression  ENSG00000277196  ENSG00000277196          NaN

      original_index
index
0        MIR1302-2HG
1            FAM138A
2              OR4F5
3         AL627309.1
4         AL627309.3
...              ...
36596     AC141272.1
36597     AC023491.2
36598     AC007325.1
36599     AC007325.4
36600     AC007325.2

[36601 rows x 5 columns]
--------------------------------------------------

### Replace unmapped gene symbols with original gene symbols

In [37]:
cur_data.adata.var['gene_symbol'] = cur_data.adata.var['gene_symbol'].fillna(
    cur_data.adata.var['original_index']
)

In [38]:
cur_data.adata.var

,feature_types,gene_ids,ensembl_gene_id,gene_symbol,original_index
index,,,,,
0,Gene Expression,ENSG00000243485,ENSG00000243485,MIR1302-2HG,MIR1302-2HG
1,Gene Expression,ENSG00000237613,ENSG00000237613,FAM138A,FAM138A
2,Gene Expression,ENSG00000186092,ENSG00000186092,OR4F5,OR4F5
3,Gene Expression,ENSG00000238009,ENSG00000241860,AL627309.1,AL627309.1
4,Gene Expression,ENSG00000239945,ENSG00000239945,AL627309.3,AL627309.3
...,...,...,...,...,...
36596,Gene Expression,ENSG00000277836,ENSG00000277836,AC141272.1,AC141272.1
36597,Gene Expression,ENSG00000278633,ENSG00000278633,AC023491.2,AC023491.2
36598,Gene Expression,ENSG00000276017,ENSG00000276017,AC007325.1,AC007325.1
36599,Gene Expression,ENSG00000278817,ENSG00000278817,AC007325.4,AC007325.4
36600,Gene Expression,ENSG00000277196,ENSG00000277196,AC007325.2,AC007325.2

### Validate var metadata

In [39]:
cur_data.validate_data(slot='var')

2026-04-28 13:40:38,754 INFO curation_tools.curation_tools: adata.var is valid according to the var_schema.

       ensembl_gene_id  gene_symbol
index
0      ENSG00000243485  MIR1302-2HG
1      ENSG00000237613      FAM138A
2      ENSG00000186092        OR4F5
3      ENSG00000241860   AL627309.1
4      ENSG00000239945   AL627309.3
...                ...          ...
36596  ENSG00000277836   AC141272.1
36597  ENSG00000278633   AC023491.2
36598  ENSG00000276017   AC007325.1
36599  ENSG00000278817   AC007325.4
36600  ENSG00000277196   AC007325.2

[36601 rows x 2 columns]

# Save the dataset

In [40]:
cur_data.save_curated_data_h5ad()

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)
... storing 'dataset_id' as categorical
... storing 'data_modality' as categorical
... storing 'significance_criteria' as categorical
... storing 'perturbation_name' as categorical
... storing 'perturbed_target_coord' as categorical
... storing 'perturbed_target_chromosome' as categorical
... storing 'perturbed_target_ensg' as categorical
... storing 'perturbed_target_symbol' as categorical
... storing 'perturbed_target_biotype' as categorical
... storing 'guide_sequence' as categorical
... storing 'perturbation_type_label' as categorical
... storing 'perturbation_type_id' as categorical
... storing 'timepoint' as categorical
... storing 'treatment_label' as categorical
... storing 'treatment_id' as categorical
... storing 'technical_replicate' as categorical
... storing 'biological_replicate' as categorical
... storing 'model_system_label' as categorical
... storing 'model_system_id' as categorical
... storing 'species' as categorical
... storing 'tissue_label' as categorical
... storing 'tissue_id' as categorical
... storing 'cell_type_label' as categorical
... storing 'cell_type_id' as categorical
... storing 'cell_line_label' as categorical
... storing 'cell_line_id' as categorical
... storing 'sex_label' as categorical
... storing 'sex_id' as categorical
... storing 'developmental_stage_label' as categorical
... storing 'developmental_stage_id' as categorical
... storing 'disease_label' as categorical
... storing 'disease_id' as categorical
... storing 'study_title' as categorical
... storing 'study_uri' as categorical
... storing 'first_author' as categorical
... storing 'last_author' as categorical
... storing 'experiment_title' as categorical
... storing 'experiment_summary' as categorical
... storing 'number_of_perturbed_targets' as categorical
... storing 'number_of_perturbed_samples' as categorical
... storing 'library_generation_type_id' as categorical
... storing 'library_generation_type_label' as categorical
... storing 'library_generation_method_id' as categorical
... storing 'library_generation_method_label' as categorical
... storing 'enzyme_delivery_method_id' as categorical
... storing 'enzyme_delivery_method_label' as categorical
... storing 'library_delivery_method_id' as categorical
... storing 'library_delivery_method_label' as categorical
... storing 'enzyme_integration_state_id' as categorical
... storing 'enzyme_integration_state_label' as categorical
... storing 'library_integration_state_id' as categorical
... storing 'library_integration_state_label' as categorical
... storing 'enzyme_expression_control_id' as categorical
... storing 'enzyme_expression_control_label' as categorical
... storing 'library_expression_control_id' as categorical
... storing 'library_expression_control_label' as categorical
... storing 'library_name' as categorical
... storing 'library_uri' as categorical
... storing 'library_format_id' as categorical
... storing 'library_format_label' as categorical
... storing 'library_scope_id' as categorical
... storing 'library_scope_label' as categorical
... storing 'library_perturbation_type_id' as categorical
... storing 'library_perturbation_type_label' as categorical
... storing 'library_manufacturer' as categorical
... storing 'library_lentiviral_generation' as categorical
... storing 'library_grnas_per_target' as categorical
... storing 'library_total_grnas' as categorical
... storing 'readout_dimensionality_id' as categorical
... storing 'readout_dimensionality_label' as categorical
... storing 'readout_type_id' as categorical
... storing 'readout_type_label' as categorical
... storing 'readout_technology_id' as categorical
... storing 'readout_technology_label' as categorical
... storing 'method_name_id' as categorical
... storing 'method_name_label' as categorical
... storing 'method_uri' as categorical
... storing 'sequencing_library_kit_id' as categorical
... storing 'sequencing_library_kit_label' as categorical
... storing 'sequencing_platform_id' as categorical
... storing 'sequencing_platform_label' as categorical
... storing 'sequencing_strategy_id' as categorical
... storing 'sequencing_strategy_label' as categorical
... storing 'software_counts_id' as categorical
... storing 'software_counts_label' as categorical
... storing 'software_analysis_id' as categorical
... storing 'software_analysis_label' as categorical
... storing 'score_interpretation' as categorical
... storing 'reference_genome_id' as categorical
... storing 'reference_genome_label' as categorical
... storing 'associated_datasets' as categorical
... storing 'license_label' as categorical
... storing 'license_id' as categorical
... storing 'ensembl_gene_id' as categorical
... storing 'gene_symbol' as categorical

✅ Curated h5ad data saved to ../curated/h5ad/arce_2025_curated.h5ad

In [41]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/arce_2025_curated_metadata.parquet

# Upload to BigQuery

In [42]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/arce_2025_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

Staging table: loading `.parquet` file ../curated/parquet/arce_2025_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...
Staging table: loaded 100087 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [43]:
!gcloud storage cp ../curated/h5ad/arce_2025_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/arce_2025_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/arce_2025_curated.h5ad
  Completed files 32/1 | 3.3GiB/3.3GiB | 313.9MiB/s

Average throughput: 328.3MiB/s