In [3]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

# import logging
# logging.basicConfig(
#     level=logging.DEBUG,
#     format="%(asctime)s %(levelname)s %(name)s: %(message)s",
#     handlers=[
#         logging.FileHandler("curation.log"),
#         logging.StreamHandler(),  # keep console output too
#     ],
#     force=True,
# )

/usr/local/lib/python3.12/dist-packages/pandera/_pandas_deprecated.py:157: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

# Download data

In [4]:
noncurated_path = "../non_curated/h5ad/frangieh_2021_raw.h5ad"
download_file(
    url="https://exampledata.scverse.org/pertpy/frangieh_2021_raw.h5ad",
    dest_path=noncurated_path
)

File ../non_curated/h5ad/frangieh_2021_raw.h5ad already exists. Skipping download.

# Initialise the dataset object

In [24]:
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/frangieh_2021_raw.h5ad

Filter the data on MOI == 1. This keeps only cells targeted with 1 guideRNA.

In [29]:
cur_data.adata = cur_data.adata[cur_data.adata.obs['MOI'] == "1"]

# OBS slot curation

### Rename sgRNA to perturbation_name

In [30]:
cur_data.rename_columns(slot = 'obs', name_dict = {'sgRNA': 'perturbation_name'})
cur_data.adata.obs

Renamed columns in adata.obs: {'sgRNA': 'perturbation_name'}

,library_preparation_protocol,condition,MOI,perturbation_name,UMI_count
cell_ID,,,,,
CELL_1,10X 3' v3 sequencing,Control,1,HLA-B_2,10832.0
CELL_3,10X 3' v3 sequencing,Control,1,HLA-B_2,28821.0
CELL_6,10X 3' v3 sequencing,Control,1,IFNGR1_1,8810.0
CELL_8,10X 3' v3 sequencing,Control,1,CDKN1A_3,8491.0
CELL_9,10X 3' v3 sequencing,Control,1,EMP1_3,7478.0
...,...,...,...,...,...
CELL_218323,10X 3' v3 sequencing,Co-culture,1,SLC22A18_2,15823.0
CELL_218325,10X 3' v3 sequencing,Co-culture,1,SLC19A1_2,30696.0
CELL_218326,10X 3' v3 sequencing,Co-culture,1,AHNAK_2,16010.0
CELL_218330,10X 3' v3 sequencing,Co-culture,1,CDKN2B_3,17941.0
CELL_218331,10X 3' v3 sequencing,Co-culture,1,NO_SITE_694,7968.0

### Show unique perturbations

In [31]:
cur_data.show_unique(slot = 'obs', column = 'perturbation_name')

Unique values in adata.obs.perturbation_name: 818
--------------------------------------------------
{'A2M_1',
 'A2M_2',
 'A2M_3',
 'ACSL3_1',
 'ACSL3_2',
 'ACSL3_3',
 'ACTA2_1',
 'ACTA2_2',
 'ACTA2_3',
 'AEBP1_1',
 'AEBP1_2',
 'AEBP1_3',
 'AGA_1',
 'AGA_2',
 'AGA_3',
 'AHCY_1',
 'AHCY_2',
 'AHCY_3',
 'AHNAK_1',
 'AHNAK_2',
 'AHNAK_3',
 'APOC2_1',
 'APOC2_2',
 'APOC2_3',
 'APOD_1',
 'APOD_2',
 'APOD_3',
 'APOE_1',
 'APOE_2',
 'APOE_3',
 'ARMC6_1',
 'ARMC6_2',
 'ARMC6_3',
 'ATP1A1_1',
 'ATP1A1_2',
 'ATP1A1_3',
 'ATP1B1_1',
 'ATP1B1_2',
 'ATP1B1_3',
 'ATP5MD_1',
 'ATP5MD_2',
 'ATP5MD_3',
 'B2M_1',
 'B2M_2',
 'B2M_3',
 'BOLA2B_1',
 'BOLA2B_2',
 'BOLA2B_3',
 'BOLA2_1',
 'BOLA2_2',
 'BOLA2_3',
 'BZW2_1',
 'BZW2_2',
 'BZW2_3',
 'C19orf48_1',
 'C19orf48_2',
 'C19orf48_3',
 'C1QBP_1',
 'C1QBP_2',
 'C1QBP_3',
 'C6orf226_1',
 'C6orf226_2',
 'C6orf226_3',
 'CCND1_1',
 'CCND1_2',
 'CCND1_3',
 'CCND2_1',
 'CCND2_2',
 'CCND2_3',
 'CCR10_1',
 'CCR10_2',
 'CCR10_3',
 'CCT3_1',
 'CCT3_2',
 'CCT3_3',
 'CCT6A_1',
 'CCT6A_2',
 'CCT6A_3',
 'CD151_1',
 'CD151_2',
 'CD151_3',
 'CD274_1',
 'CD274_2',
 'CD274_3',
 'CD44_1',
 'CD44_2',
 'CD44_3',
 'CD47_1',
 'CD47_2',
 'CD47_3',
 'CD58_1',
 'CD58_2',
 'CD58_3',
 'CD59_1',
 'CD59_2',
 'CD59_3',
 'CD63_1',
 'CD63_2',
 'CD63_3',
 'CDC123_1',
 'CDC123_2',
 'CDC123_3',
 'CDH19_1',
 'CDH19_2',
 'CDH19_3',
 'CDK4_1',
 'CDK4_2',
 'CDK4_3',
 'CDK6_1',
 'CDK6_2',
 'CDK6_3',
 'CDKN1A_1',
 'CDKN1A_2',
 'CDKN1A_3',
 'CDKN2A_1',
 'CDKN2A_2',
 'CDKN2A_3',
 'CDKN2B_1',
 'CDKN2B_2',
 'CDKN2B_3',
 'CGAS_1',
 'CGAS_2',
 'CGAS_3',
 'CHCHD2_1',
 'CHCHD2_2',
 'CHCHD2_3',
 'CITED1_1',
 'CITED1_2',
 'CITED1_3',
 'CKS1B_1',
 'CKS1B_2',
 'CKS1B_3',
 'CMSS1_1',
 'CMSS1_2',
 'CMSS1_3',
 'CORO1A_1',
 'CORO1A_2',
 'CORO1A_3',
 'CSPG4_1',
 'CSPG4_2',
 'CSPG4_3',
 'CST3_1',
 'CST3_2',
 'CST3_3',
 'CTPS1_1',
 'CTPS1_2',
 'CTPS1_3',
 'CTSA_1',
 'CTSA_2',
 'CTSA_3',
 'CTSB_1',
 'CTSB_2',
 'CTSB_3',
 'CTSD_1',
 'CTSD_2',
 'CTSD_3',
 'CTSL_1',
 'CTSL_2',
 'CTSL_3',
 'CTSO_1',
 'CTSO_2',
 'CTSO_3',
 'CXCR4_1',
 'CXCR4_2',
 'CXCR4_3',
 'CYP27A1_1',
 'CYP27A1_2',
 'CYP27A1_3',
 'DAG1_1',
 'DAG1_2',
 'DAG1_3',
 'DDR1_1',
 'DDR1_2',
 'DDR1_3',
 'DDX17_1',
 'DDX17_2',
 'DDX17_3',
 'DDX39A_1',
 'DDX39A_2',
 'DDX39A_3',
 'DLL3_1',
 'DLL3_2',
 'DLL3_3',
 'DNAJC9_1',
 'DNAJC9_2',
 'DNAJC9_3',
 'DNMT1_1',
 'DNMT1_2',
 'DNMT1_3',
 'E2F1_1',
 'E2F1_2',
 'E2F1_3',
 'EEA1_1',
 'EEA1_2',
 'EEA1_3',
 'EEF1G_1',
 'EEF1G_2',
 'EEF1G_3',
 'EIF2S3_1',
 'EIF2S3_2',
 'EIF2S3_3',
 'EIF3K_1',
 'EIF3K_2',
 'EIF3K_3',
 'EIF4A1_1',
 'EIF4A1_2',
 'EIF4A1_3',
 'EMP1_1',
 'EMP1_2',
 'EMP1_3',
 'ENPP1_1',
 'ENPP1_2',
 'ENPP1_3',
 'EVA1A_1',
 'EVA1A_2',
 'EVA1A_3',
 'FARSA_1',
 'FARSA_2',
 'FARSA_3',
 'FBL_1',
 'FBL_2',
 'FBL_3',
 'FBXO32_1',
 'FBXO32_2',
 'FBXO32_3',
 'FGFR1_1',
 'FGFR1_2',
 'FGFR1_3',
 'FKBP4_1',
 'FKBP4_2',
 'FKBP4_3',
 'FMN1_1',
 'FMN1_2',
 'FMN1_3',
 'FOS_1',
 'FOS_2',
 'FOS_3',
 'FOXM1_1',
 'FOXM1_2',
 'FOXM1_3',
 'FRZB_1',
 'FRZB_2',
 'FRZB_3',
 'FSTL3_1',
 'FSTL3_2',
 'FSTL3_3',
 'FTH1_1',
 'FTH1_2',
 'FTH1_3',
 'GAA_1',
 'GAA_2',
 'GAA_3',
 'GAS5_1',
 'GAS5_2',
 'GAS5_3',
 'GPATCH4_1',
 'GPATCH4_2',
 'GPATCH4_3',
 'GPI_1',
 'GPI_2',
 'GPI_3',
 'GPNMB_1',
 'GPNMB_2',
 'GPNMB_3',
 'GRN_1',
 'GRN_2',
 'GRN_3',
 'GSEC_1',
 'GSEC_2',
 'GSEC_3',
 'GSN_1',
 'GSN_2',
 'GSN_3',
 'HASPIN_1',
 'HASPIN_2',
 'HASPIN_3',
 'HLA-A_1',
 'HLA-A_2',
 'HLA-A_3',
 'HLA-B_1',
 'HLA-B_2',
 'HLA-B_3',
 'HLA-C_1',
 'HLA-C_2',
 'HLA-C_3',
 'HLA-DRB5_1',
 'HLA-DRB5_2',
 'HLA-DRB5_3',
 'HLA-E_1',
 'HLA-E_2',
 'HLA-E_3',
 'HLA-F_1',
 'HLA-F_2',
 'HLA-F_3',
 'HLA-H_1',
 'HLA-H_2',
 'HLA-H_3',
 'HNRNPA1_1',
 'HNRNPA1_2',
 'HNRNPA1_3',
 'HNRNPC_1',
 'HNRNPC_2',
 'HNRNPC_3',
 'HSPA1A_1',
 'HSPA1A_2',
 'HSPA1A_3',
 'IDH2_1',
 'IDH2_2',
 'IDH2_3',
 'IDI2-AS1_1',
 'IDI2-AS1_2',
 'IDI2-AS1_3',
 'IFNGR1_1',
 'IFNGR1_2',
 'IFNGR1_3',
 'IFNGR2_1',
 'IFNGR2_2',
 'IFNGR2_3',
 'ILF2_1',
 'ILF2_2',
 'ILF2_3',
 'IRF3_1',
 'IRF3_2',
 'IRF3_3',
 'IRF4_1',
 'IRF4_2',
 'IRF4_3',
 'ISYNA1_1',
 'ISYNA1_2',
 'ISYNA1_3',
 'ITGA3_1',
 'ITGA3_2',
 'ITGA3_3',
 'JAK1_1',
 'JAK1_2',
 'JAK1_3',
 'JAK2_1',
 'JAK2_2',
 'JAK2_3',
 'JMJD7_1',
 'JMJD7_2',
 'JMJD7_3',
 'JPT1_1',
 'JPT1_2',
 'JPT1_3',
 'KCNN4_1',
 'KCNN4_2',
 'KCNN4_3',
 'KDR_1',
 'KDR_2',
 'KDR_3',
 'KLF4_1',
 'KLF4_2',
 'KLF4_3',
 'LAMP2_1',
 'LAMP2_2',
 'LAMP2_3',
 'LCP1_1',
 'LCP1_2',
 'LCP1_3',
 'LEF1-AS1_1',
 'LEF1-AS1_2',
 'LEF1-AS1_3',
 'LGALS3BP_1',
 'LGALS3BP_2',
 'LGALS3BP_3',
 'LGALS3_1',
 'LGALS3_2',
 'LGALS3_3',
 'LINC00518_1',
 'LINC00518_2',
 'LINC00518_3',
 'LRPAP1_1',
 'LRPAP1_2',
 'LRPAP1_3',
 'LRRC75A-AS1_1',
 'LRRC75A-AS1_2',
 'LRRC75A-AS1_3',
 'LY96_1',
 'LY96_2',
 'LY96_3',
 'MC1R_1',
 'MC1R_2',
 'MC1R_3',
 'MDH2_1',
 'MDH2_2',
 'MDH2_3',
 'MFGE8_1',
 'MFGE8_2',
 'MFGE8_3',
 'MIA_1',
 'MIA_2',
 'MIA_3',
 'MRPL47_1',
 'MRPL47_2',
 'MRPL47_3',
 'MT2A_1',
 'MT2A_2',
 'MT2A_3',
 'MYC_1',
 'MYC_2',
 'MYC_3',
 'NACA_1',
 'NACA_2',
 'NACA_3',
 'NCL_1',
 'NCL_2',
 'NCL_3',
 'NDUFA13_1',
 'NDUFA13_2',
 'NDUFA13_3',
 'NEAT1_1',
 'NEAT1_2',
 'NEAT1_3',
 'NGFR_1',
 'NGFR_2',
 'NGFR_3',
 'NME1_1',
 'NME1_2',
 'NME1_3',
 'NMRK1_1',
 'NMRK1_2',
 'NMRK1_3',
 'NOLC1_1',
 'NOLC1_2',
 'NOLC1_3',
 'NONO_1',
 'NONO_2',
 'NONO_3',
 'NO_SITE_107',
 'NO_SITE_136',
 'NO_SITE_146',
 'NO_SITE_172',
 'NO_SITE_187',
 'NO_SITE_205',
 'NO_SITE_229',
 'NO_SITE_23',
 'NO_SITE_304',
 'NO_SITE_355',
 'NO_SITE_36',
 'NO_SITE_38',
 'NO_SITE_386',
 'NO_SITE_40',
 'NO_SITE_411',
 'NO_SITE_47',
 'NO_SITE_505',
 'NO_SITE_544',
 'NO_SITE_547',
 'NO_SITE_599',
 'NO_SITE_605',
 'NO_SITE_628',
 'NO_SITE_664',
 'NO_SITE_678',
 'NO_SITE_694',
 'NO_SITE_706',
 'NO_SITE_707',
 'NO_SITE_716',
 'NO_SITE_736',
 'NO_SITE_81',
 'NO_SITE_812',
 'NO_SITE_820',
 'NO_SITE_836',
 'NO_SITE_913',
 'NO_SITE_915',
 'NO_SITE_960',
 'NO_SITE_963',
 'NPC1_1',
 'NPC1_2',
 'NPC1_3',
 'NPC2_1',
 'NPC2_2',
 'NPC2_3',
 'NSG1_1',
 'NSG1_2',
 'NSG1_3',
 'NT5E_1',
 'NT5E_2',
 'NT5E_3',
 'NUP50-AS1_1',
 'NUP50-AS1_2',
 'NUP50-AS1_3',
 'ONE_NON-GENE_SITE_157',
 'ONE_NON-GENE_SITE_177',
 'ONE_NON-GENE_SITE_2',
 'ONE_NON-GENE_SITE_202',
 'ONE_NON-GENE_SITE_217',
 'ONE_NON-GENE_SITE_231',
 'ONE_NON-GENE_SITE_241',
 'ONE_NON-GENE_SITE_249',
 'ONE_NON-GENE_SITE_250',
 'ONE_NON-GENE_SITE_263',
 'ONE_NON-GENE_SITE_290',
 'ONE_NON-GENE_SITE_293',
 'ONE_NON-GENE_SITE_328',
 'ONE_NON-GENE_SITE_409',
 'ONE_NON-GENE_SITE_422',
 'ONE_NON-GENE_SITE_531',
 'ONE_NON-GENE_SITE_570',
 'ONE_NON-GENE_SITE_594',
 'ONE_NON-GENE_SITE_598',
 'ONE_NON-GENE_SITE_636',
 'ONE_NON-GENE_SITE_640',
 'ONE_NON-GENE_SITE_658',
 'ONE_NON-GENE_SITE_670',
 'ONE_NON-GENE_SITE_672',
 'ONE_NON-GENE_SITE_675',
 'ONE_NON-GENE_SITE_714',
 'ONE_NON-GENE_SITE_724',
 'ONE_NON-GENE_SITE_736',
 'ONE_NON-GENE_SITE_813',
 'ONE_NON-GENE_SITE_84',
 'ONE_NON-GENE_SITE_848',
 'ONE_NON-GENE_SITE_859',
 'ONE_NON-GENE_SITE_869',
 'ONE_NON-GENE_SITE_892',
 'ONE_NON-GENE_SITE_915',
 'ONE_NON-GENE_SITE_931',
 'ONE_NON-GENE_SITE_993',
 'P2RX4_1',
 'P2RX4_2',
 'P2RX4_3',
 'PABPC1_1',
 'PABPC1_2',
 'PABPC1_3',
 'PAICS_1',
 'PAICS_2',
 'PAICS_3',
 'PET100_1',
 'PET100_2',
 'PET100_3',
 'PFDN4_1',
 'PFDN4_2',
 'PFDN4_3',
 'PFN1_1',
 'PFN1_2',
 'PFN1_3',
 'PIK3IP1_1',
 'PIK3IP1_2',
 'PIK3IP1_3',
 'POLD2_1',
 'POLD2_2',
 'POLD2_3',
 'PPA1_1',
 'PPA1_2',
 'PPA1_3',
 'PPIA_1',
 'PPIA_2',
 'PPIA_3',
 'PRELID3B_1',
 'PRELID3B_2',
 'PRELID3B_3',
 'PROS1_1',
 'PROS1_2',
 'PROS1_3',
 'PSAP_1',
 'PSAP_2',
 'PSAP_3',
 'PSMA7_1',
 'PSMA7_2',
 'PSMA7_3',
 'PSMB8-AS1_1',
 'PSMB8-AS1_2',
 'PSMB8-AS1_3',
 'PTMA_1',
 'PTMA_2',
 'PTMA_3',
 'PUF60_1',
 'PUF60_2',
 'PUF60_3',
 'PYGB_1',
 'PYGB_2',
 'PYGB_3',
 'RAB27A_1',
 'RAB27A_2',
 'RAB27A_3',
 'RACK1_1',
 'RACK1_2',
 'RACK1_3',
 'RB1_1',
 'RB1_2',
 'RB1_3',
 'RBP7_1',
 'RBP7_2',
 'RBP7_3',
 'RNASEH2A_1',
 'RNASEH2A_2',
 'RNASEH2A_3',
 'RNF213_1',
 'RNF213_2',
 'RNF213_3',
 'ROMO1_1',
 'ROMO1_2',
 'ROMO1_3',
 'RPSA_1',
 'RPSA_2',
 'RPSA_3',
 'RRS1_1',
 'RRS1_2',
 'RRS1_3',
 'RTP4_1',
 'RTP4_2',
 'RTP4_3',
 'RUVBL2_1',
 'RUVBL2_2',
 'RUVBL2_3',
 'S100A6_1',
 'S100A6_2',
 'S100A6_3',
 'S100B_1',
 'S100B_2',
 'S100B_3',
 'SAE1_1',
 'SAE1_2',
 'SAE1_3',
 'SAT1_1',
 'SAT1_2',
 'SAT1_3',
 'SCARB2_1',
 'SCARB2_2',
 'SCARB2_3',
 'SDC3_1',
 'SDC3_2',
 'SDC3_3',
 'SDCBP_1',
 'SDCBP_2',
 'SDCBP_3',
 'SEC11C_1',
 'SEC11C_2',
 'SEC11C_3',
 'SERPINA3_1',
 'SERPINA3_2',
 'SERPINA3_3',
 'SERPINE2_1',
 'SERPINE2_2',
 'SERPINE2_3',
 'SERPINF1_1',
 'SERPINF1_2',
 'SERPINF1_3',
 'SET_1',
 'SET_2',
 'SET_3',
 'SGK1_1',
 'SGK1_2',
 'SGK1_3',
 'SHMT2_1',
 'SHMT2_2',
 'SHMT2_3',
 'SINHCAF_1',
 'SINHCAF_2',
 'SINHCAF_3',
 'SLC19A1_1',
 'SLC19A1_2',
 'SLC19A1_3',
 'SLC22A18_1',
 'SLC22A18_2',
 'SLC22A18_3',
 'SLC25A13_1',
 'SLC25A13_2',
 'SLC25A13_3',
 'SLC26A2_1',
 'SLC26A2_2',
 'SLC26A2_3',
 'SLC5A3_1',
 'SLC5A3_2',
 'SLC5A3_3',
 'SLC7A5P1_1',
 'SLC7A5P1_2',
 'SLC7A5P1_3',
 'SLIRP_1',
 'SLIRP_2',
 'SLIRP_3',
 'SMAD3_1',
 'SMAD3_2',
 'SMAD3_3',
 'SMAD4_1',
 'SMAD4_2',
 'SMAD4_3',
 'SNHG6_1',
 'SNHG6_2',
 'SNHG6_3',
 'SNRPE_1',
 'SNRPE_2',
 'SNRPE_3',
 'SNRPF_1',
 'SNRPF_2',
 'SNRPF_3',
 'SNRPG_1',
 'SNRPG_2',
 'SNRPG_3',
 'SOX4_1',
 'SOX4_2',
 'SOX4_3',
 'SP100_1',
 'SP100_2',
 'SP100_3',
 'SPESP1_1',
 'SPESP1_2',
 'SPESP1_3',
 'SPINT1_1',
 'SPINT1_2',
 'SPINT1_3',
 'SSR2_1',
 'SSR2_2',
 'SSR2_3',
 'ST3GAL6-AS1_1',
 'ST3GAL6-AS1_2',
 'ST3GAL6-AS1_3',
 'ST6GALNAC2_1',
 'ST6GALNAC2_2',
 'ST6GALNAC2_3',
 'STAT1_1',
 'STAT1_2',
 'STAT1_3',
 'STAT3_1',
 'STAT3_2',
 'STAT3_3',
 'STOM_1',
 'STOM_2',
 'STOM_3',
 'STX7_1',
 'STX7_2',
 'STX7_3',
 'TAPBPL_1',
 'TAPBPL_2',
 'TAPBPL_3',
 'TAPBP_1',
 'TAPBP_2',
 'TAPBP_3',
 'TFAP2A_1',
 'TFAP2A_2',
 'TFAP2A_3',
 'TGFB1_1',
 'TGFB1_2',
 'TGFB1_3',
 'TIMM50_1',
 'TIMM50_2',
 'TIMM50_3',
 'TIMP1_1',
 'TIMP1_2',
 'TIMP1_3',
 'TIMP2_1',
 'TIMP2_2',
 'TIMP2_3',
 'TIMP3_1',
 'TIMP3_2',
 'TIMP3_3',
 'TM4SF1_1',
 'TM4SF1_2',
 'TM4SF1_3',
 'TMED10_1',
 'TMED10_2',
 'TMED10_3',
 'TMEM173_1',
 'TMEM173_2',
 'TMEM173_3',
 'TOP1MT_1',
 'TOP1MT_2',
 'TOP1MT_3',
 'TP53_1',
 'TP53_2',
 'TP53_3',
 'TPP1_1',
 'TPP1_2',
 'TPP1_3',
 'TPRKB_1',
 'TPRKB_2',
 'TPRKB_3',
 'TRIM22_1',
 'TRIM22_2',
 'TRIM22_3',
 'TSC22D3_1',
 'TSC22D3_2',
 'TSC22D3_3',
 'TTLL1_1',
 'TTLL1_2',
 'TTLL1_3',
 'TUBB_1',
 'TUBB_2',
 'TUBB_3',
 'TXNDC17_1',
 'TXNDC17_2',
 'TXNDC17_3',
 'TYR_1',
 'TYR_2',
 'TYR_3',
 'UBA52_1',
 'UBA52_2',
 'UBA52_3',
 'UBC_1',
 'UBC_2',
 'UBC_3',
 'UBL5_1',
 'UBL5_2',
 'UBL5_3',
 'UCN2_1',
 'UCN2_2',
 'UCN2_3',
 'UQCRFS1_1',
 'UQCRFS1_2',
 'UQCRFS1_3',
 'UQCRH_1',
 'UQCRH_2',
 'UQCRH_3',
 'VAT1_1',
 'VAT1_2',
 'VAT1_3',
 'VDAC2_1',
 'VDAC2_2',
 'VDAC2_3',
 'WBP2_1',
 'WBP2_2',
 'WBP2_3',
 'WNT7A_1',
 'WNT7A_2',
 'WNT7A_3',
 'XAGE1A_1',
 'XAGE1A_2',
 'XAGE1A_3'}
--------------------------------------------------

### Add guide RNA information

In [32]:
download_file(
    url="https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-021-00779-1/MediaObjects/41588_2021_779_MOESM3_ESM.xlsx",
    dest_path="../supplementary/frangieh_2021_supp.xlsx"
)

guide_info_df = pd.read_excel("../supplementary/frangieh_2021_supp.xlsx", sheet_name="Supplementary Table 1", skiprows=2)
guide_info_df = guide_info_df.rename(columns = {'Guide Name':'perturbation_name','sgRNA Sequence':'guide_sequence'})
guide_info_df

File ../supplementary/frangieh_2021_supp.xlsx already exists. Skipping download.

     perturbation_name        guide_sequence
0                A2M_1  TGAAATGAAACTTCACACTG
1                A2M_2  GGAAAAATGGCCCTTCACTG
2                A2M_3  ACTGCATCTGTGCAAACGGG
3              ACSL3_1  GTGGTGAAGAGTAACCAATG
4              ACSL3_2  TTTACTTACCTGTCGCACAG
...                ...                   ...
1498       NO_SITE_821  TGTACGCTCCCGTCGAACGA
1499       NO_SITE_898  AAGCGGTTGTACGACGCACG
1500       NO_SITE_132  TACTCGTCGTACGTCGTTCG
1501       NO_SITE_439  CGGGGTCGGCATACGATCGG
1502       NO_SITE_249  TGCTCGCCGTCAAACGGTAT

[1503 rows x 2 columns]

In [33]:
cur_data.adata.obs = cur_data.adata.obs.merge(guide_info_df, on='perturbation_name', how='left')
cur_data.adata.obs

/usr/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

,library_preparation_protocol,condition,MOI,perturbation_name,UMI_count,guide_sequence
0,10X 3' v3 sequencing,Control,1,HLA-B_2,10832.0,CTCCGCAGGGTAGAAACCCA
1,10X 3' v3 sequencing,Control,1,HLA-B_2,28821.0,CTCCGCAGGGTAGAAACCCA
2,10X 3' v3 sequencing,Control,1,IFNGR1_1,8810.0,GCCGCGAACGACGGTACCTG
3,10X 3' v3 sequencing,Control,1,CDKN1A_3,8491.0,AGTCGAAGTTCCATCGCTCA
4,10X 3' v3 sequencing,Control,1,EMP1_3,7478.0,CTCACAGCACACCAGTGTGG
...,...,...,...,...,...,...
126961,10X 3' v3 sequencing,Co-culture,1,SLC22A18_2,15823.0,GGCCTTCAGGTCGAACACAC
126962,10X 3' v3 sequencing,Co-culture,1,SLC19A1_2,30696.0,GGCCCGACAAGAACTTCACG
126963,10X 3' v3 sequencing,Co-culture,1,AHNAK_2,16010.0,CCCAGCTGCTGAACACCATG
126964,10X 3' v3 sequencing,Co-culture,1,CDKN2B_3,17941.0,CCGGTCGGGTGAGAGTGGCA
126965,10X 3' v3 sequencing,Co-culture,1,NO_SITE_694,7968.0,ATGGCGACCGTATCGTTACC

### Standardise perturbation targets

Two types of controls are used:
1. Non-targeting controls: `NO_SITE_*`
2. Controls targeting intergenic regions: `ONE_NON-GENE_SITE_*`

In [34]:
cur_data.adata.obs['target'] = (cur_data.adata.obs['perturbation_name']
    .str.replace('NO_SITE', 'control_nontargeting') # rename nontargeting control guides
    .str.replace('ONE_NON-GENE_SITE', 'control_intergenic') # rename intergenic control guides
    .str.replace(r"_\d+", "", regex=True) # remove guide number suffix
    .fillna('control_casonly')
)

In [35]:
cur_data.standardize_genes(
    slot='obs',
    input_column='target',
    input_column_type='gene_symbol',
    multiple_entries=False,
    # multiple_entries_sep='|'
)

Mapping gene symbols: 100%|████████████████████████████████████| 250/250 [00:00<00:00, 20653.86it/s]
/usr/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

--------------------------------------------------
Successfully mapped 250 out of 250 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: []
--------------------------------------------------

### Add `perturbed_target_number` column

In [36]:
cur_data.count_entries(
    slot='obs',
    input_column='perturbed_target_symbol',
    count_column_name='perturbed_target_number',
    sep='|'
)

Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [37]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

### Add treatment information

In [38]:
cur_data.adata.obs['treatment_label'] = cur_data.adata.obs['condition'].replace({
    'Control': 'untreated control',
    'IFNγ': 'Interferon gamma',
    'Co-culture': 'Interferon gamma|Tumor Infiltrating Lymphocyte'
})

cur_data.adata.obs['treatment_id'] = cur_data.adata.obs['condition'].replace({
    'Control': 'NCIT:C184729',
    'IFNγ': 'CHEMBL:3286073',
    'Co-culture': 'CHEMBL:3286073|NCIT:C12546'
})

/tmp/ipython-input-3727342723.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  cur_data.adata.obs['treatment_label'] = cur_data.adata.obs['condition'].replace({
/tmp/ipython-input-3727342723.py:7: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  cur_data.adata.obs['treatment_id'] = cur_data.adata.obs['condition'].replace({

### Add timepoint information

In [39]:
cur_data.adata.obs['timepoint'] = cur_data.adata.obs['condition'].replace({
    'Control': 'P14DT16H0M0S',
    'IFNγ': 'P14DT16H0M0S',
    'Co-culture': 'P17DT16H0M0S'
})

/tmp/ipython-input-2328709114.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  cur_data.adata.obs['timepoint'] = cur_data.adata.obs['condition'].replace({

### Add metadata

In [40]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        #----- dataset -----#
        "dataset_id": cur_data.dataset_id,
        #----- sample -----#
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        #----- perturbation type -----#
        "perturbation_type_label": "CRISPRn",
        "perturbation_type_id": None,
        #----- data modality -----#
        "data_modality": "Perturb-seq", # different from "method_name_label"; more general term - choice of CRISPR, MAVE and Perturb-seq
        #----- significance -----#
        "significant": None,
        "significance_criteria": None,
        #----- score interpretation -----#
        "score_interpretation": None,
        #----- treatment -----#
        # "treatment_label": None,
        # "treatment_id": None,
        #----- replicate -----#
        "technical_replicate": None,
        "biological_replicate": None,
        #----- model system -----#
        "model_system_label": "primary_cell",
        "model_system_id": None,
        #----- tissue -----#
        "tissue": "skin of body",
        #----- cell line -----#
        "cell_line_label": None,
        "cell_line_id": None,
        #----- cell type -----#
        "cell_type_label": "melanoma cell",
        "cell_type_id": "BTO:0000848",
        #----- disease -----#
        "disease_label": "melanoma",
        "disease_id": "MONDO:0005105",
        #----- timepoint -----#
        # "timepoint": "P7DT0H0M0S",
        #----- species -----#
        "species": "Homo sapiens",
        #----- sex -----#
        "sex_label": None,
        "sex_id": None,
        #----- developmental stage -----#
        "developmental_stage_label": None,
        "developmental_stage_id": None,
        #----- study metadata -----#
        "study_title": "Multimodal pooled Perturb-CITE-seq screens in patient models define mechanisms of cancer immune evasion",
        "study_uri": "https://doi.org/10.1038/s41588-021-00779-1",
        "study_year": 2021,
        #----- authors -----#
        "first_author": "Chris J. Frangieh",
        "last_author": "Benjamin Izar",
        #----- experiment metadata -----#
        "experiment_title": "Perturb-seq CRISPRko screen of primary melanoma cells in untreated, IFNg-stimulated and IFNg-stimulated + co-cultured with autologous tumor-infiltrating lymphocytes to explore cancer cell-intrinsic immune checkpoint inhibitor resistance mechanisms.",
        "experiment_summary": """
            Patient-derived melanoma cells stably expressing Cas9 were engineered by lentiviral transduction of a pooled CROPseq-mKate2 sgRNA library targeting 248 immunotherapy resistance genes. Transduced cells were cultured under antibiotic selection for 14 days, pre-treated with IFN-γ for 16 hours, and subsequently subjected to control, IFN-γ treatment, or co-culture with autologous tumor-infiltrating lymphocytes (TILs) conditions for 48 hours. At day 17, surviving cancer cells were harvested, stained with oligonucleotide-conjugated antibodies, sorted to remove TILs, processed using the Chromium Single Cell 3’ Library and Gel Bead kit v3, and sequenced on an Illumina HiSeq.
        """,
        #----- number of perturbed targets/samples -----#
        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],
        #----- library generation type -----#
        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",
        #----- library generation method -----#
        "library_generation_method_id": "EFO:0022876",
        "library_generation_method_label": "SpCas9",
        #----- enzyme and library delivery method -----#
        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "lentivirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",
        #----- enzyme and library integration state -----#
        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",
        #----- enzyme and library expression control -----#
        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",
        #----- library name and URI and manufacturer -----#
        "library_name": "custom",
        "library_uri": None,
        "library_manufacturer": "Izar lab",
        #----- library format -----#
        "library_format_id": None,
        "library_format_label": "pooled",
        #----- library scope -----#
        "library_scope_id": None,
        "library_scope_label": "focused",
        #----- library perturbation type -----#
        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "knockout",
        #----- library additional metadata -----#
        "library_lentiviral_generation": "2",
        "library_grnas_per_target": "3",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()), # for CRISPR/Perturb-seq
        "library_total_variants": None, # for MAVE
        #----- readout dimensionality -----#
        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",
        #---- readout type -----#
        "readout_type_id": None,
        "readout_type_label": "transcriptomic",
        #----- readout technology -----#
        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",
        #----- method -----#
        "method_name_id": None,
        "method_name_label": "Perturb-CITE-seq", # different from "data_modality"; more specific term - specific name of the technique
        "method_uri": None,
        #----- sequencing library kit -----#
        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "10x Genomics Single Cell 3-prime v3",
        #----- sequencing platform -----#
        "sequencing_platform_id": None,
        "sequencing_platform_label": "Illumina HiSeq 2500",
        #----- sequencing strategy -----#
        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",
        #----- software used for counts-----#
        "software_counts_id": None,
        "software_counts_label": "CellRanger",
        #----- software used for analysis -----#
        "software_analysis_id": None,
        "software_analysis_label": "MAST",
        #----- reference genome -----#
        "reference_genome_id": None,
        "reference_genome_label": "GRCh38",
        #----- license -----#
        "license_label": "MIT License",
        "license_id": "SWO:9000074",
        #----- external datasets -----#
        "associated_datasets": json.dumps([
            {
                "dataset_accession": "frangieh_2021_raw.h5ad",
                "dataset_uri": "https://scverse-exampledata.s3.eu-west-1.amazonaws.com/pertpy/frangieh_2021_raw.h5ad",
                "dataset_description": "Raw counts - .h5ad file from pertpy",
                "dataset_file_name": "frangieh_2021_raw.h5ad",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_line_id added to adata.obs
Column cell_type_label added to adata.obs
Column cell_type_id added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_manufacturer added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

### Curate tissue information

In [41]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
   input_column input_column_lower    name_lower     ontology_id
0  skin of body       skin of body  skin of body  UBERON:0002097
--------------------------------------------------

/usr/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Match schema column order

In [42]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [43]:
cur_data.validate_data(slot='obs', verbose=True)

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,frangieh_2021_raw,1,Perturb-seq,<NA>,<NA>,HLA-B_2,chr6:31353867-31367067;-1,6,6,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
1,frangieh_2021_raw,2,Perturb-seq,<NA>,<NA>,HLA-B_2,chr6:31353867-31367067;-1,6,6,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
2,frangieh_2021_raw,3,Perturb-seq,<NA>,<NA>,IFNGR1_1,chr6:137197483-137219449;-1,6,6,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
3,frangieh_2021_raw,4,Perturb-seq,<NA>,<NA>,CDKN1A_3,chr6:36676441-36687397;1,6,6,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
4,frangieh_2021_raw,5,Perturb-seq,<NA>,<NA>,EMP1_3,chr12:13196723-13219941;1,12,12,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126961,frangieh_2021_raw,126962,Perturb-seq,<NA>,<NA>,SLC22A18_2,chr11:2899718-2925247;1,11,11,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
126962,frangieh_2021_raw,126963,Perturb-seq,<NA>,<NA>,SLC19A1_2,chr21:45493572-45573564;-1,21,21,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
126963,frangieh_2021_raw,126964,Perturb-seq,<NA>,<NA>,AHNAK_2,chr11:62433542-62556235;-1,11,11,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
126964,frangieh_2021_raw,126965,Perturb-seq,<NA>,<NA>,CDKN2B_3,chr9:22002903-22009305;-1,9,9,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074
126965,frangieh_2021_raw,126966,Perturb-seq,<NA>,<NA>,NO_SITE_694,control_nontargeting,control_nontargeting,0,1,...,<NA>,CellRanger,<NA>,MAST,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""frangieh_2021_raw.h5ad...",MIT License,SWO:9000074

# VAR slot curation

### Standardise genes

In [48]:
cur_data.adata.var['gene_name'] = cur_data.adata.var.index
cur_data.adata.var

         gene_name
gene
A1BG          A1BG
A1BG-AS1  A1BG-AS1
A1CF          A1CF
A2M            A2M
A2M-AS1    A2M-AS1
...            ...
ZXDC          ZXDC
ZYG11A      ZYG11A
ZYG11B      ZYG11B
ZYX            ZYX
ZZEF1        ZZEF1

[23712 rows x 1 columns]

In [64]:
cur_data.standardize_genes(
    slot="var",
    input_column="gene_name",
    input_column_type="gene_symbol",
    remove_version=True,
    multiple_entries=False
)

Removed version numbers from gene_name

Mapping gene symbols: 100%|████████████████████████████████| 22474/22474 [00:02<00:00, 10987.32it/s]

--------------------------------------------------
Successfully mapped 21658 out of 22474 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['AC002074', 'AC002384', 'AC002386', 'AC002454', 'AC002463', 'AC003084', 'AC003092', 'AC003975', 'AC003984', 'AC003988', 'AC004012', 'AC004158', 'AC004556', 'AC004870', 'AC004930', 'AC004944', 'AC004947', 'AC005019', 'AC005050', 'AC005144', 'AC005150', 'AC005165', 'AC005186', 'AC005304', 'AC005307', 'AC005487', 'AC005523', 'AC005616', 'AC005699', 'AC006004', 'AC006058', 'AC006065', 'AC006148', 'AC006305', 'AC006504', 'AC006978', 'AC007064', 'AC007126', 'AC007325', 'AC007344', 'AC007364', 'AC007370', 'AC007388', 'AC007389', 'AC007423', 'AC007495', 'AC007611', 'AC007639', 'AC007681', 'AC007953', 'AC008033', 'AC008035', 'AC008109', 'AC008268', 'AC008549', 'AC008632', 'AC008663', 'AC008691', 'AC008703', 'AC008780', 'AC008825', 'AC008875', 'AC008892', 'AC009075', 'AC009081', 'AC009093', 'AC009226', 'AC009262', 'AC009264', 'AC009271', 'AC009275', 'AC009502', 'AC009518', 'AC009803', 'AC009804', 'AC010096', 'AC010099', 'AC010235', 'AC010280', 'AC010343', 'AC010424', 'AC010595', 'AC010601', 'AC010719', 'AC010737', 'AC010857', 'AC010904', 'AC010967', 'AC010983', 'AC011043', 'AC011239', 'AC011287', 'AC011294', 'AC011306', 'AC011416', 'AC011601', 'AC011632', 'AC012055', 'AC012349', 'AC012409', 'AC012506', 'AC012555', 'AC012593', 'AC012603', 'AC012625', 'AC012668', 'AC013401', 'AC013448', 'AC013652', 'AC013724', 'AC015574', 'AC015922', 'AC016205', 'AC016687', 'AC016710', 'AC016730', 'AC016831', 'AC016924', 'AC017048', 'AC017067', 'AC017071', 'AC017091', 'AC018645', 'AC018953', 'AC019155', 'AC019183', 'AC019209', 'AC019211', 'AC020551', 'AC020637', 'AC020905', 'AC020912', 'AC021218', 'AC021224', 'AC021351', 'AC021504', 'AC021683', 'AC021713', 'AC021851', 'AC022031', 'AC022034', 'AC022081', 'AC022126', 'AC022140', 'AC022239', 'AC022240', 'AC022274', 'AC022296', 'AC022639', 'AC022784', 'AC022874', 'AC022929', 'AC023034', 'AC023481', 'AC023946', 'AC024230', 'AC024337', 'AC024563', 'AC024581', 'AC024600', 'AC024901', 'AC024908', 'AC025159', 'AC025164', 'AC025219', 'AC025244', 'AC025252', 'AC025470', 'AC025524', 'AC025575', 'AC025674', 'AC026320', 'AC026355', 'AC026412', 'AC026414', 'AC026726', 'AC026765', 'AC026904', 'AC027277', 'AC027449', 'AC027763', 'AC034223', 'AC037486', 'AC040170', 'AC040918', 'AC055717', 'AC058791', 'AC062015', 'AC062028', 'AC063944', 'AC064807', 'AC067838', 'AC067956', 'AC068135', 'AC068305', 'AC068313', 'AC068418', 'AC068446', 'AC068491', 'AC068722', 'AC068756', 'AC068875', 'AC069061', 'AC069120', 'AC069277', 'AC069439', 'AC073023', 'AC073050', 'AC073115', 'AC073133', 'AC073365', 'AC073409', 'AC073429', 'AC073529', 'AC073848', 'AC074183', 'AC074237', 'AC074351', 'AC074386', 'AC074387', 'AC078785', 'AC078788', 'AC078820', 'AC078845', 'AC078850', 'AC078880', 'AC078906', 'AC078923', 'AC079209', 'AC079340', 'AC079466', 'AC079598', 'AC079760', 'AC079906', 'AC079949', 'AC080011', 'AC080129', 'AC083836', 'AC083843', 'AC084026', 'AC084116', 'AC084149', 'AC084768', 'AC084816', 'AC084819', 'AC087258', 'AC087354', 'AC087386', 'AC087430', 'AC087473', 'AC087477', 'AC087516', 'AC087564', 'AC087636', 'AC087667', 'AC087855', 'AC087857', 'AC090023', 'AC090092', 'AC090124', 'AC090152', 'AC090159', 'AC090204', 'AC090337', 'AC090377', 'AC090403', 'AC090409', 'AC090568', 'AC090578', 'AC090692', 'AC090791', 'AC090802', 'AC090825', 'AC090833', 'AC090921', 'AC091173', 'AC091212', 'AC091435', 'AC091493', 'AC091614', 'AC091891', 'AC091932', 'AC091946', 'AC091965', 'AC092059', 'AC092112', 'AC092162', 'AC092164', 'AC092265', 'AC092337', 'AC092378', 'AC092447', 'AC092580', 'AC092650', 'AC092683', 'AC092691', 'AC092745', 'AC092810', 'AC092902', 'AC092957', 'AC093206', 'AC093274', 'AC093277', 'AC093297', 'AC093426', 'AC093536', 'AC093702', 'AC093763', 'AC093772', 'AC093802', 'AC093833', 'AC093901', 'AC093904', 'AC095050', 'AC096577', 'AC096642', 'AC096711', 'AC096721', 'AC097065', 'AC097480', 'AC097487', 'AC097512', 'AC098828', 'AC098864', 'AC099062', 'AC099342', 'AC099398', 'AC099487', 'AC099499', 'AC099520', 'AC099541', 'AC099552', 'AC099554', 'AC099566', 'AC100773', 'AC100801', 'AC100818', 'AC100826', 'AC103718', 'AC103736', 'AC103746', 'AC103808', 'AC103853', 'AC104031', 'AC104035', 'AC104041', 'AC104051', 'AC104063', 'AC104073', 'AC104118', 'AC104123', 'AC104248', 'AC104435', 'AC104596', 'AC104640', 'AC104653', 'AC104777', 'AC104823', 'AC105105', 'AC105177', 'AC105277', 'AC105390', 'AC105411', 'AC105460', 'AC105999', 'AC106053', 'AC106712', 'AC106771', 'AC106795', 'AC106798', 'AC106869', 'AC106892', 'AC107029', 'AC107032', 'AC107057', 'AC107079', 'AC107204', 'AC107391', 'AC107419', 'AC107463', 'AC107958', 'AC108047', 'AC108062', 'AC108136', 'AC108174', 'AC108463', 'AC108704', 'AC108866', 'AC109439', 'AC109446', 'AC109466', 'AC109588', 'AC109809', 'AC109830', 'AC109927', 'AC110058', 'AC110741', 'AC111188', 'AC112178', 'AC112206', 'AC112491', 'AC112493', 'AC113145', 'AC113146', 'AC113346', 'AC113378', 'AC113383', 'AC113414', 'AC114284', 'AC114316', 'AC114321', 'AC114400', 'AC114550', 'AC114689', 'AC116049', 'AC116096', 'AC116563', 'AC116634', 'AC116667', 'AC117386', 'AC117394', 'AC117402', 'AC118757', 'AC118758', 'AC121333', 'AC122134', 'AC122138', 'AC123595', 'AC123786', 'AC124067', 'AC124254', 'AC124290', 'AC125616', 'AC125618', 'AC126175', 'AC126178', 'AC126365', 'AC126763', 'AC126768', 'AC128685', 'AC130352', 'AC131094', 'AC131254', 'AC133644', 'AC135012', 'AC135371', 'AC136489', 'AC136944', 'AC137761', 'AC137770', 'AC138035', 'AC138123', 'AC138150', 'AC138305', 'AC138393', 'AC138627', 'AC138761', 'AC139099', 'AC140912', 'AC144450', 'AC145212', 'AC145343', 'AC146944', 'AC226118', 'AC231981', 'AC233263', 'AC234772', 'AC239584', 'AC239800', 'AC239809', 'AC240274', 'AC243830', 'AC245100', 'AC245297', 'AC245595', 'AF064858', 'AF127936', 'AF165147', 'AF241725', 'AF279873', 'AJ009632', 'AJ011932', 'AJ239322', 'AKAP2', 'AL008638', 'AL008721', 'AL021368', 'AL021408', 'AL021877', 'AL022068', 'AL022324', 'AL023495', 'AL023755', 'AL023802', 'AL031590', 'AL031768', 'AL033504', 'AL033530', 'AL034376', 'AL035412', 'AL035446', 'AL049833', 'AL050344', 'AL050403', 'AL078587', 'AL078590', 'AL078604', 'AL078639', 'AL096799', 'AL096803', 'AL110292', 'AL110505', 'AL117329', 'AL121672', 'AL121718', 'AL121781', 'AL121820', 'AL121892', 'AL121904', 'AL132996', 'AL133216', 'AL133255', 'AL133329', 'AL133346', 'AL133383', 'AL133464', 'AL135937', 'AL136309', 'AL136317', 'AL136962', 'AL137786', 'AL137796', 'AL138694', 'AL138731', 'AL138737', 'AL138749', 'AL139023', 'AL139351', 'AL139383', 'AL139390', 'AL157702', 'AL157884', 'AL157888', 'AL157937', 'AL158042', 'AL158152', 'AL159169', 'AL161630', 'AL161719', 'AL161752', 'AL161938', 'AL162293', 'AL162414', 'AL162511', 'AL162574', 'AL162632', 'AL162718', 'AL353052', 'AL353581', 'AL353626', 'AL353740', 'AL353753', 'AL353803', 'AL353804', 'AL354694', 'AL354702', 'AL354732', 'AL354809', 'AL354822', 'AL354977', 'AL354984', 'AL355478', 'AL355596', 'AL355601', 'AL355607', 'AL355810', 'AL355981', 'AL356010', 'AL356108', 'AL356234', 'AL356258', 'AL356272', 'AL356277', 'AL356414', 'AL356512', 'AL356515', 'AL357055', 'AL357507', 'AL357558', 'AL357793', 'AL358335', 'AL358876', 'AL359232', 'AL359237', 'AL359378', 'AL359551', 'AL359682', 'AL359715', 'AL359834', 'AL359851', 'AL359915', 'AL360014', 'AL365259', 'AL365500', 'AL390037', 'AL390198', 'AL390729', 'AL390763', 'AL390835', 'AL390862', 'AL390957', 'AL391117', 'AL391261', 'AL391704', 'AL391832', 'AL391987', 'AL392023', 'AL441943', 'AL445250', 'AL445307', 'AL445470', 'AL445472', 'AL445647', 'AL450442', 'AL451137', 'AL512329', 'AL512380', 'AL512625', 'AL512634', 'AL513123', 'AL513283', 'AL513314', 'AL513321', 'AL513478', 'AL583808', 'AL589642', 'AL589684', 'AL589740', 'AL589743', 'AL589826', 'AL590004', 'AL590079', 'AL590399', 'AL590637', 'AL590652', 'AL590867', 'AL591030', 'AL591163', 'AL591222', 'AL591368', 'AL591441', 'AL591468', 'AL591501', 'AL591518', 'AL591885', 'AL592183', 'AL592494', 'AL596211', 'AL603840', 'AL627422', 'AL646090', 'AL662890', 'AL669831', 'AL683887', 'AL691420', 'AL691515', 'AL713851', 'AL713998', 'AL731661', 'AL731684', 'AL805961', 'AL807761', 'AL845472', 'AL935212', 'AP000146', 'AP000221', 'AP000233', 'AP000255', 'AP000265', 'AP000317', 'AP000402', 'AP000439', 'AP000446', 'AP000472', 'AP000527', 'AP000542', 'AP000550', 'AP000569', 'AP000695', 'AP000696', 'AP000797', 'AP000904', 'AP000997', 'AP001043', 'AP001056', 'AP001208', 'AP001341', 'AP001476', 'AP001615', 'AP001626', 'AP001628', 'AP002833', 'AP002989', 'AP003062', 'AP003063', 'AP003123', 'AP003500', 'AP003716', 'AP003900', 'AP004147', 'AP005057', 'AP005229', 'AP005230', 'AP005271', 'AP005328', 'AP005436', 'AP006295', 'ARF4-AS1', 'BX004987', 'BX005019', 'BX005266', 'BX088651', 'BX322559', 'BX323043', 'BX324167', 'BX537318', 'BX546450', 'BX547991', 'BX571846', 'BX640514', 'BX649601', 'BX664718', 'BX890604', 'C8orf49', 'C9orf106', 'CCL3L1', 'CR381653', 'CR786580', 'CU104787', 'CU633906', 'CU633967', 'CU633980', 'CU634019', 'CU638689', 'CU639417', 'CYP17A1-AS1', 'DENND6A-AS1', 'DLEU7-AS1', 'ERVMER61-1', 'FAM239A', 'FAM239B', 'FAM239C', 'FAM95C', 'FLJ45513', 'FP236241', 'FP236315', 'FP236383', 'FP325318', 'FP325330', 'FP565260', 'FP671120', 'FRMD6-AS1', 'GATD3B', 'HIF1A-AS1', 'HIF1A-AS2', 'KF456478', 'LINC00266-1', 'LINC00473', 'LINC00619', 'LINC00886', 'LINC01033', 'LINC01109', 'LINC01119', 'LINC01372', 'LINC01422', 'LINC01580', 'LINC01669', 'LINC02119', 'LINC02263', 'LINC02310', 'MAFIP', 'MIR5689HG', 'MTRNR2L1', 'MTRNR2L10', 'MTRNR2L11', 'MTRNR2L12', 'MTRNR2L3', 'MTRNR2L4', 'MTRNR2L6', 'MTRNR2L8', 'NAGPA-AS1', 'NPPA-AS1', 'OCLM', 'PALM2', 'PRR25', 'PWAR6', 'SIK1B', 'SMC5-AS1', 'SMIM11B', 'SMIM2', 'SMUG1-AS1', 'STT3A-AS1', 'TEMN3-AS1', 'TMX2-CTNND1', 'TTTY15', 'U2AF1L5', 'U95743', 'VASH1-AS1', 'Z68871', 'Z73429', 'Z82186', 'Z82217', 'Z85994', 'Z97192', 'Z97198', 'Z99774']
--------------------------------------------------

/usr/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [65]:
cur_data.adata.var

      gene_name  ensembl_gene_id gene_symbol original_index
index
0          A1BG  ENSG00000121410        A1BG              0
1      A1BG-AS1  ENSG00000268895    A1BG-AS1              1
2          A1CF  ENSG00000148584        A1CF              2
3           A2M  ENSG00000175899         A2M              3
4       A2M-AS1  ENSG00000245105     A2M-AS1              4
...         ...              ...         ...            ...
23707      ZXDC  ENSG00000070476        ZXDC          23707
23708    ZYG11A  ENSG00000203995      ZYG11A          23708
23709    ZYG11B  ENSG00000162378      ZYG11B          23709
23710       ZYX  ENSG00000159840         ZYX          23710
23711     ZZEF1  ENSG00000074755       ZZEF1          23711

[23712 rows x 4 columns]

### Validate var metadata

In [66]:
cur_data.validate_data(slot='var')

       ensembl_gene_id gene_symbol
index
0      ENSG00000121410        A1BG
1      ENSG00000268895    A1BG-AS1
2      ENSG00000148584        A1CF
3      ENSG00000175899         A2M
4      ENSG00000245105     A2M-AS1
...                ...         ...
23707  ENSG00000070476        ZXDC
23708  ENSG00000203995      ZYG11A
23709  ENSG00000162378      ZYG11B
23710  ENSG00000159840         ZYX
23711  ENSG00000074755       ZZEF1

[23712 rows x 2 columns]

# Save the dataset

In [67]:
cur_data.save_curated_data_h5ad()

/content/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/frangieh_2021_raw_curated.h5ad

In [68]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/frangieh_2021_raw_curated_metadata.parquet

# Upload to BigQuery

In [69]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/frangieh_2021_raw_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

Staging table: loading `.parquet` file ../curated/parquet/frangieh_2021_raw_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...
Staging table: loaded 126966 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [70]:
!gcloud storage cp ../curated/h5ad/frangieh_2021_raw_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/frangieh_2021_raw_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/frangieh_2021_raw_curated.h5ad

Average throughput: 881.2MiB/s