In [1]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

# import logging
# logging.basicConfig(
#     level=logging.DEBUG,
#     format="%(asctime)s %(levelname)s %(name)s: %(message)s",
#     handlers=[
#         logging.FileHandler("curation.log"),
#         logging.StreamHandler(),  # keep console output too
#     ],
#     force=True,
# )

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/.venv/lib/python3.12/site-packages/pandera/_pandas_deprecated.py:157: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

# Download data

In [2]:
noncurated_path = "../non_curated/h5ad/gasperini_2019_atscale.h5ad"
download_file(
    url="https://exampledata.scverse.org/pertpy/gasperini_2019_atscale.h5ad",
    dest_path=noncurated_path
)

File ../non_curated/h5ad/gasperini_2019_atscale.h5ad already exists. Skipping download.

# Initialise the dataset object

In [3]:
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/gasperini_2019_atscale.h5ad

# OBS slot curation

### Rename gene -> perturbation_name, barcode -> guide_sequence

In [4]:
cur_data.rename_columns(slot = 'obs',
                        name_dict = {"gene": "perturbation_name",
                                     "barcode": "guide_sequence"})
# add cell barcode
cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.astype(str)
cur_data.adata.obs

Renamed columns in adata.obs: {'gene': 'perturbation_name', 'barcode': 'guide_sequence'}

,sample,total_umis,Size_Factor,perturbation_name,all_gene,guide_sequence,read_count,umi_count,proportion,guide_count,...,perturbation_type,celltype,organism,perturbation,nperts,ngenes,ncounts,percent_mito,percent_ribo,cell_barcode
AAACCTGAGAGGTACC,1A_1_SI-GA-E2,17572,1.009682,chr10.845_top_two_chr1.11183_top_two_chr1.1129...,chr10.845_top_two_chr1.11183_top_two_chr1.1129...,AGAAAGCTCCTCCAGTTCAC_TGATCGCTTTGACTGTGACA_ACAA...,14135.0,964.0,0.969819,67.0,...,CRISPR,lymphoblasts,human,chr10.845_top_two_chr1.11183_top_two_chr1.1129...,195,3549,17566.0,0.0,30.507799,AAACCTGAGAGGTACC
AAACCTGAGTCAATAG,1A_1_SI-GA-E2,8923,0.939677,chr1.12695_top_two_chr11.3294_top_two_chr1.679...,chr1.12695_top_two_chr11.3294_top_two_chr1.679...,GTAGAGCCTCCAGAACTGTG_AGGTTTATCCAGATGAACTG_CATC...,4329.0,293.0,0.844380,26.0,...,CRISPR,lymphoblasts,human,chr1.12695_top_two_chr11.3294_top_two_chr1.679...,68,2543,8917.0,0.0,28.955927,AAACCTGAGTCAATAG
AAACCTGCAAACAACA,1A_1_SI-GA-E2,14637,0.990803,ALDH1A2_TSS_BRI3_TSS_chr10.1918_top_two_chr10....,ALDH1A2_TSS_BRI3_TSS_chr10.1918_top_two_chr10....,CCAAGGCGTCCTCAGACCAG_AGCTCCAGGAAGGACCCCCG_TCAC...,12362.0,884.0,0.950538,61.0,...,CRISPR,lymphoblasts,human,ALDH1A2_BRI3_chr10.1918_top_two_chr10.350_top_...,167,3191,14626.0,0.0,26.548612,AAACCTGCAAACAACA
AAACCTGCACTTCTGC,1A_1_SI-GA-E2,22798,1.036578,C16orf91_TSS_chr1.11332_top_two_chr1.1933_top_...,C16orf91_TSS_chr1.11332_top_two_chr1.1933_top_...,GGCGTCAGTCGAGGAGTCAG_GCCAGCACTTCAGCTCACCG_GCTG...,7459.0,544.0,0.939551,39.0,...,CRISPR,lymphoblasts,human,C16orf91_chr1.11332_top_two_chr1.1933_top_two_...,109,4539,22783.0,0.0,20.616249,AAACCTGCACTTCTGC
AAACCTGCATGTAGTC,1A_1_SI-GA-E2,10136,0.952844,chr10.185_top_two_chr10.484_top_two_chr11.4167...,chr10.185_top_two_chr10.484_top_two_chr11.4167...,ATAAGGCACTCACATCCACC_GCTTGTCCCTAACACTCAGA_GGGC...,14831.0,1054.0,0.959927,37.0,...,CRISPR,lymphoblasts,human,chr10.185_top_two_chr10.484_top_two_chr11.4167...,107,2605,10124.0,0.0,32.418017,AAACCTGCATGTAGTC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCAGTACCTACA,2B_8_SI-GA-H9,17938,1.011811,BRIX1_TSS_chr10.2059_top_two_chr10.350_top_two...,BRIX1_TSS_chr10.2059_top_two_chr10.350_top_two...,AGGAGGCCAAGAGCGCGGGG_TGATTGAAGGAGGCTCCCCA_GGTA...,4570.0,394.0,0.856522,31.0,...,CRISPR,lymphoblasts,human,BRIX1_chr10.2059_top_two_chr10.350_top_two_chr...,85,3451,17934.0,0.0,31.733021,TTTGTCAGTACCTACA
TTTGTCAGTATCACCA-1,2B_8_SI-GA-H9,16543,1.003448,chr10.221_top_two_chr11.3853_top_two_chr11.498...,chr10.221_top_two_chr11.3853_top_two_chr11.498...,CCTGCAACTGTCTATGGCCT_TCAGTGGGTGAGTCTTCAGG_TGAG...,4311.0,387.0,0.861915,33.0,...,CRISPR,lymphoblasts,human,chr10.221_top_two_chr11.3853_top_two_chr11.498...,92,3693,16542.0,0.0,24.694716,TTTGTCAGTATCACCA-1
TTTGTCAGTTCAGACT-1,2B_8_SI-GA-H9,15009,0.993396,chr12.3400_top_two_chr4.1281_second_two_ID3_TSS,chr12.3400_top_two_chr4.1281_second_two_ID3_TSS,CCAGTTGCTAGGCAGGACAG_CTTTCAGGCAGGAATCTGAG_TGGT...,669.0,57.0,0.876923,3.0,...,CRISPR,lymphoblasts,human,chr12.3400_top_two_chr4.1281_second_two_ID3,7,3162,14992.0,0.0,32.123799,TTTGTCAGTTCAGACT-1
TTTGTCAGTTCTGTTT,2B_8_SI-GA-H9,5149,0.882878,chr7.1014_top_two,chr7.1014_top_two,CACCCCCCAGAGATAAGAGA,77.0,7.0,0.086420,1.0,...,CRISPR,lymphoblasts,human,chr7.1014_top_two,3,1392,5149.0,0.0,35.074772,TTTGTCAGTTCTGTTT
TTTGTCATCAAAGTAG-1,2B_8_SI-GA-H9,9503,0.946182,chr11.2790_top_two_chr12.306_top_two_chr12.474...,chr11.2790_top_two_chr12.306_top_two_chr12.474...,AGTATGGGCCTGGAACACAG_AGATCTCCCCTGTCACCACG_CGTT...,4630.0,410.0,0.813492,35.0,...,CRISPR,lymphoblasts,human,chr11.2790_top_two_chr12.306_top_two_chr12.474...,99,2429,9499.0,0.0,36.624908,TTTGTCATCAAAGTAG-1

### Show unique perturbations

In [5]:
cur_data.show_unique(slot = 'obs', column = 'perturbation_name')

Unique values in adata.obs.perturbation_name: 203515
--------------------------------------------------
{

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

### Add guide RNA information

In [ ]:
import re

# define regex pattern for splitting
controls_regex_pattern = r"(top_two|second_two|TSS|bassik_mch|pos_control_HBE1_tss_Klann_mosaic|pos_control_HBE1_tss_Klann_mosaic|pos_control_HS2_Klann_mosaic|pos_control_Klannchr1_HBG1_HBG1_tss_both|pos_control_Klannchr1_HS3|pos_control_Klannchr1_HS4|pos_control_Klannchr_HS1|pos_control_KlannHS2g_HS2_A|pos_control_KlannHS2g_HS2_B|pos_control_mosaic_HB_HBE1_tss_A|pos_control_mosaic_HB_HBE1_tss_B|scrambled_\d+|random_\d+)"
# split the gene names based on the regex pattern
gene_split = [re.sub(controls_regex_pattern, r"\1\n", e).split('\n') for e in cur_data.adata.obs['perturbation_name']]
# clean up the split parts
gene_split = [[i.strip('_').replace('_TSS', '') for i in e if i != ''] for e in gene_split]
# join the split parts with '|'
gene_split = ['|'.join(e) for e in gene_split]

cur_data.adata.obs['gene_split'] = gene_split

cur_data.adata.obs['gene_split']

AAACCTGAGAGGTACC      chr10.845_top_two|chr1.11183_top_two|chr1.1129...
AAACCTGAGTCAATAG      chr1.12695_top_two|chr11.3294_top_two|chr1.679...
AAACCTGCAAACAACA      ALDH1A2|BRI3|chr10.1918_top_two|chr10.350_top_...
AAACCTGCACTTCTGC      C16orf91|chr1.11332_top_two|chr1.1933_top_two|...
AAACCTGCATGTAGTC      chr10.185_top_two|chr10.484_top_two|chr11.4167...
                                            ...
TTTGTCAGTACCTACA      BRIX1|chr10.2059_top_two|chr10.350_top_two|chr...
TTTGTCAGTATCACCA-1    chr10.221_top_two|chr11.3853_top_two|chr11.498...
TTTGTCAGTTCAGACT-1          chr12.3400_top_two|chr4.1281_second_two|ID3
TTTGTCAGTTCTGTTT                                      chr7.1014_top_two
TTTGTCATCAAAGTAG-1    chr11.2790_top_two|chr12.306_top_two|chr12.474...
Name: gene_split, Length: 207324, dtype: object

In [ ]:
# download supplementary files on at-scale guide annotations
download_file(
    url="https://ars.els-cdn.com/content/image/1-s2.0-S009286741831554X-mmc2.xlsx",
    dest_path="../supplementary/gasperini_2019_atscale_supp.xlsx"
)
download_file(
    url="https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE120861&format=file&file=GSE120861%5Fgrna%5Fgroups%2Eat%5Fscale%2Etxt%2Egz",
    dest_path="../supplementary/gasperini_2019_atscale_supp.txt.gz"
)
# load guide info
guide_info_df = pd.read_excel("../supplementary/gasperini_2019_atscale_supp.xlsx", sheet_name="S2A_AtScale_library_gRNA.cs", skiprows=0)
guide_info_df2 = pd.read_table("../supplementary/gasperini_2019_atscale_supp.txt.gz", sep='\t', header=None, names=['target', 'guide_sequence'])
# add coordinate info
guide_info_df['start.candidate_enhancer'] = guide_info_df['start.candidate_enhancer'].astype(str).str.replace('.0', '')
guide_info_df['stop.candidate_enhancer'] = guide_info_df['stop.candidate_enhancer'].astype(str).str.replace('.0', '')
guide_info_df['coord'] = (guide_info_df['chr.candidate_enhancer']+ ':' +
                              guide_info_df['start.candidate_enhancer'] + '-' +
                              guide_info_df['stop.candidate_enhancer'])
guide_info_df.loc[guide_info_df['coord'] == 'nan:nan-nan', 'coord'] = ''
guide_info_df = guide_info_df[['Spacer', 'coord']]#.fillna('')#.dropna()
# remove _TSS from target names
guide_info_df2['target'] = guide_info_df2['target'].str.replace('_TSS', '')
guide_info_df2 = guide_info_df2.merge(guide_info_df, left_on='guide_sequence', right_on='Spacer', how='left').drop(columns=['Spacer'])

guide_info_df2

File ../supplementary/gasperini_2019_atscale_supp.xlsx already exists. Skipping download.
File ../supplementary/gasperini_2019_atscale_supp.txt.gz already exists. Skipping download.

             target        guide_sequence coord
0          SH3BGRL3  AAACCGCTCCCGAGCACGGG   NaN
1          MTRNR2L8  AAATAGTGGGAAGATTCGTG   NaN
2            FAM83A  AACACACCACGGAGGAGTGG   NaN
3            ZNF593  AACAGCCCGGCCGGCCAAGG   NaN
4            ATPIF1  AACGAGAGACTGCTTGCTGG   NaN
...             ...                   ...   ...
13184      random_5  TTAATTCCTCTGGCGCCGCT   NaN
13185     random_14  TTAGCTTTGAAAACACACAC   NaN
13186      random_2  TTATCTCTATTTGACAGACG   NaN
13187  scrambled_23  TTGGGAATGCGAGGCAAAGG   NaN
13188     random_17  TTTCTCTGTAAGTTACCATG   NaN

[13189 rows x 3 columns]

In [8]:
# get gene ont
gene_ont = cur_data.gene_ont.dropna(subset='synonym')
# remove unnecessary mappings based on chr
gene_ont = gene_ont[gene_ont['chromosome_name'].isin(
    [str(i) for i in range(1, 23)] + ["X", "Y", "MT"]
)]

# create a mapping dict name:coord
enh_mapping_dict = (
    guide_info_df2[guide_info_df2['target'].str.startswith('chr')][['target', 'coord']]
    .drop_duplicates()
    .set_index('target')['coord']
    .to_dict()
)

# init enhancer mapping df
enh_mapping_df = pd.DataFrame(columns=gene_ont.columns)
enh_mapping_df['synonym'] = enh_mapping_dict.keys()
enh_mapping_df['ensembl_gene_id'] = enh_mapping_dict.keys()
enh_mapping_df['ensembl_gene_id'] = enh_mapping_df['ensembl_gene_id'].str.replace('chr', 'enh_chr_')
enh_mapping_df['gene_symbol'] = enh_mapping_df['ensembl_gene_id']
enh_mapping_df['gene_coord'] = enh_mapping_dict.values()
enh_mapping_df['chromosome_name'] = enh_mapping_df['gene_coord'].str.split(':').str[0].str.replace('chr', '')
enh_mapping_df['biotype'] = 'enhancer'
enh_mapping_df['synonym_type'] = 'symbol_syn'
enh_mapping_df['description'] = 'enhancer'

# concat to gene_ont df
gene_ont = pd.concat([gene_ont, enh_mapping_df], axis=0, ignore_index=True)

# replace cur_data.gene_ont with the updated one
cur_data.gene_ont = gene_ont

gene_ont.tail()

,ensembl_gene_id,gene_symbol,chromosome_name,gene_coord,biotype,description,synonym_type,synonym
520416,enh_chr_X.938_top_two,enh_chr_X.938_top_two,X,chrX:48489654-48490612,enhancer,enhancer,symbol_syn,chrX.938_top_two
520417,enh_chr_X.94_top_two,enh_chr_X.94_top_two,X,chrX:2953853-2954104,enhancer,enhancer,symbol_syn,chrX.94_top_two
520418,enh_chr_X.952_top_two,enh_chr_X.952_top_two,X,chrX:48641145-48641725,enhancer,enhancer,symbol_syn,chrX.952_top_two
520419,enh_chr_X.952_second_two,enh_chr_X.952_second_two,X,chrX:48641145-48641725,enhancer,enhancer,symbol_syn,chrX.952_second_two
520420,enh_chr_X.963_top_two,enh_chr_X.963_top_two,X,chrX:48726316-48726706,enhancer,enhancer,symbol_syn,chrX.963_top_two

In [9]:
# replace controls in gene_split with mappable ones
cur_data.adata.obs['gene_split'] = (
    cur_data.adata.obs['gene_split']
        .replace(
        {r'random_\d+': 'control_genedesert',
         r'scrambled_\d+': 'control_nontargeting',
         r'pos_control_\w+': 'control_positive'
         },
        regex=True
    )
)

In [12]:
cur_data.adata.obs

,Size_Factor,cancer,id,nperts,umi_count,within_batch_chip,perturbation_name,percent_mito,prep_batch,all_gene,...,percent.mito,sample_directory,cell_barcode,perturbation,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index
index,,,,,,,,,,,,,,,,,,,,,
0,1.009682,True,1A_1,195,964.0,within_batch_chip_A,chr10.845_top_two_chr1.11183_top_two_chr1.1129...,0.0,prep_batch_1,chr10.845_top_two_chr1.11183_top_two_chr1.1129...,...,0.058787,1A_1_SI-GA-E2,AAACCTGAGAGGTACC,chr10.845_top_two_chr1.11183_top_two_chr1.1129...,enh_chr_10.845_top_two|enh_chr_1.11183_top_two...,ENH_CHR_10.845_TOP_TWO|ENH_CHR_1.11183_TOP_TWO...,enhancer|enhancer|enhancer|enhancer|enhancer|e...,chr10:23344953-23345044|chr1:205720419-2057208...,10|1|1|11|1|1|11|12|12|12|13|14|14|1|15|15|15|...,AAACCTGAGAGGTACC|AAACCTGAGAGGTACC|AAACCTGAGAGG...
1,0.939677,True,1A_1,68,293.0,within_batch_chip_A,chr1.12695_top_two_chr11.3294_top_two_chr1.679...,0.0,prep_batch_1,chr1.12695_top_two_chr11.3294_top_two_chr1.679...,...,0.036087,1A_1_SI-GA-E2,AAACCTGAGTCAATAG,chr1.12695_top_two_chr11.3294_top_two_chr1.679...,enh_chr_1.12695_top_two|enh_chr_11.3294_top_tw...,ENH_CHR_1.12695_TOP_TWO|ENH_CHR_11.3294_TOP_TW...,enhancer|enhancer|enhancer|enhancer|enhancer|e...,chr1:237077735-237078115|chr11:65459793-654603...,1|11|1|17|20|20|2|2|2|2|3|3|5|6|6|6|6|6|6|7|7|...,AAACCTGAGTCAATAG|AAACCTGAGTCAATAG|AAACCTGAGTCA...
2,0.990803,True,1A_1,167,884.0,within_batch_chip_A,ALDH1A2_TSS_BRI3_TSS_chr10.1918_top_two_chr10....,0.0,prep_batch_1,ALDH1A2_TSS_BRI3_TSS_chr10.1918_top_two_chr10....,...,0.069823,1A_1_SI-GA-E2,AAACCTGCAAACAACA,ALDH1A2_BRI3_chr10.1918_top_two_chr10.350_top_...,ENSG00000128918|ENSG00000164713|enh_chr_10.191...,ALDH1A2|BRI3|ENH_CHR_10.1918_TOP_TWO|ENH_CHR_1...,protein_coding|protein_coding|enhancer|enhance...,chr15:57953424-58497866;-1|chr7:98252379-98310...,15|7|10|10|10|10|1|11|11|11|11|12|1|15|16|16|1...,AAACCTGCAAACAACA|AAACCTGCAAACAACA|AAACCTGCAAAC...
3,1.036578,True,1A_1,109,544.0,within_batch_chip_A,C16orf91_TSS_chr1.11332_top_two_chr1.1933_top_...,0.0,prep_batch_1,C16orf91_TSS_chr1.11332_top_two_chr1.1933_top_...,...,0.026187,1A_1_SI-GA-E2,AAACCTGCACTTCTGC,C16orf91_chr1.11332_top_two_chr1.1933_top_two_...,ENSG00000174109|enh_chr_1.11332_top_two|enh_ch...,UQCC4|ENH_CHR_1.11332_TOP_TWO|ENH_CHR_1.1933_T...,protein_coding|enhancer|enhancer|enhancer|enha...,chr16:1419752-1420756;-1|chr1:207378404-207378...,16|1|1|14|15|15|16|16|16|1|1|18|1|20|20|22|3|3...,AAACCTGCACTTCTGC|AAACCTGCACTTCTGC|AAACCTGCACTT...
4,0.952844,True,1A_1,107,1054.0,within_batch_chip_A,chr10.185_top_two_chr10.484_top_two_chr11.4167...,0.0,prep_batch_1,chr10.185_top_two_chr10.484_top_two_chr11.4167...,...,0.007991,1A_1_SI-GA-E2,AAACCTGCATGTAGTC,chr10.185_top_two_chr10.484_top_two_chr11.4167...,enh_chr_10.185_top_two|enh_chr_10.484_top_two|...,ENH_CHR_10.185_TOP_TWO|ENH_CHR_10.484_TOP_TWO|...,enhancer|enhancer|enhancer|enhancer|enhancer|e...,chr10:4983650-4984221|chr10:12105451-12105804|...,10|10|11|12|13|14|15|15|1|18|18|18|1|18|20|20|...,AAACCTGCATGTAGTC|AAACCTGCATGTAGTC|AAACCTGCATGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207319,1.011811,True,2B_8,85,394.0,within_batch_chip_B,BRIX1_TSS_chr10.2059_top_two_chr10.350_top_two...,0.0,prep_batch_2,BRIX1_TSS_chr10.2059_top_two_chr10.350_top_two...,...,0.060598,2B_8_SI-GA-H9,TTTGTCAGTACCTACA,BRIX1_chr10.2059_top_two_chr10.350_top_two_chr...,ENSG00000113460|enh_chr_10.2059_top_two|enh_ch...,BRIX1|ENH_CHR_10.2059_TOP_TWO|ENH_CHR_10.350_T...,protein_coding|enhancer|enhancer|enhancer|enha...,chr5:34915273-34926622;1|chr10:70821228-708218...,5|10|10|1|1|1|11|12|14|14|1|15|16|19|19|20|20|...,TTTGTCAGTACCTACA|TTTGTCAGTACCTACA|TTTGTCAGTACC...
207320,1.003448,True,2B_8,92,387.0,within_batch_chip_B,chr10.221_top_two_chr11.3853_top_two_chr11.498...,0.0,prep_batch_2,chr10.221_top_two_chr11.3853_top_two_chr11.498...,...,0.057789,2B_8_SI-GA-H9,TTTGTCAGTATCACCA-1,chr10.221_top_two_chr11.3853_top_two_chr11.498...,enh_chr_10.221_top_two|enh_chr_11.3853_top_two...,ENH_CHR_10.221_TOP_TWO|ENH_CHR_11.3853_TOP_TWO...,enhancer|enhancer|enhancer|enhancer|enhancer|e...,chr10:5520856-5520965|chr11:69796098-69797225|...,10|11|11|12|12|12|13|14|17|19|19|19|1|20|20|2|...,TTTGTCAGTATCACCA-1|TTTGTCAGTATCACCA-1|TTTGTCAG...
207321,0.993396,True,2B_8,7,57.0,within_batch_chip_B,chr12.3400_top_two_chr4.1281_second_two_ID3_TSS,0.0,prep_batch_2,chr12.3400_top_two_chr4.1281_second_two_ID3_TSS,...,0.049037,2B_8_SI-GA-H9,TTTGTCAGTTCAGACT-1,chr12.3400_top_two_chr4.1281_second_two_ID3,enh_chr_12.3400_top_two|enh_chr_4.1281_second_...,ENH_CHR_12.3400_TOP_TWO|ENH_CHR_4.1281_SECOND_...,enhancer|enhancer|protein_coding,chr12:108512970-108513426|chr4:38244351-382452...,12|4|1,TTTGTCAGTTCAGACT-1|TTTGTCAGTTCAGACT-1|TTTGTCAG...
207322,0.882878,True,2B_8,3,7.0,within_batch_chip_B,chr7.1014_top_two,0.0,prep_batch_2,chr7.1014_top_two,...,0.000971,2B_8_SI-GA-H9,TTTGTCAGTTCTGTTT,chr7.1014_top_two,enh_chr_7.1014_top_two,ENH_CHR_7.1014_TOP_TWO,enhancer,chr7:13888984-13889047,7,TTTGTCAGTTCTGTTT
207323,0.946182,True,2B_8,99,410.0,within_batch_chip_B,chr11.2790_top_two_chr12.306_top_two_chr12.474...,0.0,prep_batch_2,chr11.2790_top_two_chr12.306_top_two_chr12.474...,...,0.028623,2B_8_SI-GA-H9,TTTGTCATCAAAGTAG-1,chr11.2790_top_two_chr12.306_top_two_chr12.474...,enh_chr_11.2790_top_two|enh_chr_12.306_top_two...,ENH_CHR_11.2790_TOP_TWO|ENH_CHR_12.306_TOP_TWO...,enhancer|enhancer|enhancer|enhancer|enhancer|e...,chr11:62163630-62164619|chr12:6539348-6540130|...,11|12|12|1|14|15|16|16|1|1|17|17|17|1|19|19|19...,TTTGTCATCAAAGTAG-1|TTTGTCATCAAAGTAG-1|TTTGTCAT...

### Standardise perturbation targets

In [11]:
cur_data.standardize_genes(
    slot='obs',
    input_column='gene_split',
    input_column_type='gene_symbol',
    multiple_entries=True,
    multiple_entries_sep='|'
)

Mapping gene symbols: 100%|██████████████████████████████████| 6542/6542 [00:00<00:00, 46474.56it/s]

--------------------------------------------------
Successfully mapped 6540 out of 6542 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['bassik_mch', 'MTRNR2L8']
--------------------------------------------------
Collapsed column positional_index using separator |

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [14]:
# clean the mapped names ensg and symbol columns
controls_regex_pattern = r"(_top_two|_second_two)"

cur_data.adata.obs['perturbed_target_ensg'] = cur_data.adata.obs['perturbed_target_ensg'].str.replace(controls_regex_pattern, '', regex=True)
cur_data.adata.obs['perturbed_target_symbol'] = cur_data.adata.obs['perturbed_target_symbol'].str.replace(controls_regex_pattern.upper(), '', regex=True)

### Add `perturbed_target_number` column

In [17]:
cur_data.count_entries(
    slot='obs',
    input_column='perturbed_target_symbol',
    count_column_name='perturbed_target_number',
    sep='|'
)

Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [18]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

### Add replicate information

In [23]:
cur_data.adata.obs = cur_data.adata.obs.rename(
    columns={
        'prep_batch': 'technical_replicate'
    }
)

### Add guide sequence information

In [34]:
cur_data.adata.obs['guide_sequence'] = cur_data.adata.obs['guide_sequence'].str.replace('_', '|')

### Add metadata

In [25]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        #----- dataset -----#
        "dataset_id": cur_data.dataset_id,
        #----- sample -----#
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        #----- perturbation type -----#
        "perturbation_type_label": "CRISPRi",
        "perturbation_type_id": None,
        #----- data modality -----#
        "data_modality": "Perturb-seq", # different from "method_name_label"; more general term - choice of CRISPR, MAVE and Perturb-seq
        #----- significance -----#
        "significant": None,
        "significance_criteria": None,
        #----- score interpretation -----#
        "score_interpretation": None,
        #----- treatment -----#
        "treatment_label": None,
        "treatment_id": None,
        #----- replicate -----#
        # "technical_replicate": None,
        "biological_replicate": None,
        #----- model system -----#
        "model_system_label": "cell_line",
        "model_system_id": None,
        #----- tissue -----#
        "tissue": "blood",
        #----- cell line -----#
        "cell_line_label": "K 562 cell",
        # "cell_line_id": None,
        #----- cell type -----#
        "cell_type_label": "lymphoblast",
        # "cell_type_id": ,
        #----- disease -----#
        "disease_label": "chronic myelogenous leukemia, BCR-ABL1 positive",
        "disease_id": "MONDO:0011996",
        #----- timepoint -----#
        "timepoint": "P10DT0H0M0S",
        #----- species -----#
        "species": "Homo sapiens",
        #----- sex -----#
        "sex_label": "female",
        "sex_id": None,
        #----- developmental stage -----#
        "developmental_stage_label": "adult",
        "developmental_stage_id": None,
        #----- study metadata -----#
        "study_title": "A Genome-wide Framework for Mapping Gene Regulation via Cellular Genetic Screens",
        "study_uri": "https://doi.org/10.1016/j.cell.2018.11.029",
        "study_year": 2019,
        #----- authors -----#
        "first_author": "Molly Gasperini",
        "last_author": "Jay Shendure",
        #----- experiment metadata -----#
        "experiment_title": "Perturb-seq CRISPRi screen in K562 cells to explore the targets of over 5,779 candidate enhancers.",
        "experiment_summary": """
            Several methods were used to select a set of 5,799 candidate enhancers. GuideRNAs targeting these candidate enhancers, as well a selection of non-targeting , gene-desert and positive controls (targeting globin TSS and enhancers + 381 gene TSSs) were cloned into a CRISPRi-optimised CROP-seq vector. After producing the lentiviral library, K562 cells stably expressing the dCas9-BFP-KRAB were transduced with the library at A very high MOI=~28 (median 28 ± 15.3 gRNAs identified per cell) and cultured for 10 days, at which point the cells were harvested for sequencing using Illumina NovaSeq 6000.
        """,
        #----- number of perturbed targets/samples -----#
        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],
        #----- library generation type -----#
        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",
        #----- library generation method -----#
        "library_generation_method_id": "EFO:0022895",
        "library_generation_method_label": "dCas9-KRAB",
        #----- enzyme and library delivery method -----#
        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "lentivirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",
        #----- enzyme and library integration state -----#
        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",
        #----- enzyme and library expression control -----#
        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",
        #----- library name and URI and manufacturer -----#
        "library_name": "custom",
        "library_uri": None,
        "library_manufacturer": "Shendure lab",
        #----- library format -----#
        "library_format_id": None,
        "library_format_label": "pooled",
        #----- library scope -----#
        "library_scope_id": None,
        "library_scope_label": "focused",
        #----- library perturbation type -----#
        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "inhibition",
        #----- library additional metadata -----#
        "library_lentiviral_generation": "3",
        "library_grnas_per_target": "2",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()), # for CRISPR/Perturb-seq
        "library_total_variants": None, # for MAVE
        #----- readout dimensionality -----#
        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",
        #---- readout type -----#
        "readout_type_id": None,
        "readout_type_label": "transcriptomic",
        #----- readout technology -----#
        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",
        #----- method -----#
        "method_name_id": None,
        "method_name_label": "Perturb-seq", # different from "data_modality"; more specific term - specific name of the technique
        "method_uri": None,
        #----- sequencing library kit -----#
        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "10x Genomics Single Cell 3-prime v2",
        #----- sequencing platform -----#
        "sequencing_platform_id": None,
        "sequencing_platform_label": "Illumina NovaSeq 6000",
        #----- sequencing strategy -----#
        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",
        #----- software used for counts-----#
        "software_counts_id": None,
        "software_counts_label": "CellRanger",
        #----- software used for analysis -----#
        "software_analysis_id": None,
        "software_analysis_label": "Seurat",
        #----- reference genome -----#
        "reference_genome_id": None,
        "reference_genome_label": "GRCh37",
        #----- license -----#
        "license_label": "free to use license",
        "license_id": "SWO:1000061",
        #----- external datasets -----#
        "associated_datasets": json.dumps([
            {
                "dataset_accession": "gasperini_2019_atscale.h5ad",
                "dataset_uri": "https://exampledata.scverse.org/pertpy/gasperini_2019_atscale.h5ad",
                "dataset_description": "Raw counts - .h5ad file from pertpy",
                "dataset_file_name": "gasperini_2019_atscale.h5ad",
            },
            {
                "dataset_accession": "GSE120861",
                "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120861",
                "dataset_description": "Raw counts - GEO entry",
                "dataset_file_name": "GSE120861_at_scale_screen.*",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column treatment_label added to adata.obs
Column treatment_id added to adata.obs
Column biological_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_type_label added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_manufacturer added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

### Curate tissue information

In [26]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower     ontology_id
0        blood              blood      blood  UBERON:0000178
--------------------------------------------------

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [27]:
cur_data.standardize_ontology(
    input_column='cell_type_label',
    column_type='term_name',
    ontology_type='cell_type',
    overwrite=True
)

Mapped 1 cell_type ontology terms from `cell_type_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower   name_lower ontology_id
0  lymphoblast        lymphoblast  lymphoblast  CL:0017005
--------------------------------------------------
Overwriting column cell_type_label in adata.obs

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell line information

In [28]:
cur_data.standardize_ontology(
    input_column='cell_line_label',
    column_type='term_name',
    ontology_type='cell_line',
    overwrite=True
)

Mapped 1 cell_line ontology terms from `cell_line_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower  name_lower  ontology_id
0   K 562 cell         k 562 cell  k 562 cell  CLO:0007050
--------------------------------------------------
Overwriting column cell_line_label in adata.obs

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [29]:
cur_data.standardize_ontology(
    input_column='disease_label',
    column_type='term_name',
    ontology_type='disease',
    overwrite=True
)

Mapped 1 disease ontology terms from `disease_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
                                      input_column  \
0  chronic myelogenous leukemia, BCR-ABL1 positive

                                input_column_lower  \
0  chronic myelogenous leukemia, bcr-abl1 positive

                                        name_lower    ontology_id
0  chronic myelogenous leukemia, bcr-abl1 positive  MONDO:0011996
--------------------------------------------------
Overwriting column disease_label in adata.obs
Overwriting column disease_id in adata.obs

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Match schema column order

In [30]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [31]:
cur_data.validate_data(slot='obs', verbose=True)

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,gasperini_2019_atscale,1,Perturb-seq,<NA>,<NA>,chr10.845_top_two_chr1.11183_top_two_chr1.1129...,chr10:23344953-23345044|chr1:205720419-2057208...,10|1|1|11|1|1|11|12|12|12|13|14|14|1|15|15|15|...,0,67,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
1,gasperini_2019_atscale,2,Perturb-seq,<NA>,<NA>,chr1.12695_top_two_chr11.3294_top_two_chr1.679...,chr1:237077735-237078115|chr11:65459793-654603...,1|11|1|17|20|20|2|2|2|2|3|3|5|6|6|6|6|6|6|7|7|...,0,25,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
2,gasperini_2019_atscale,3,Perturb-seq,<NA>,<NA>,ALDH1A2_TSS_BRI3_TSS_chr10.1918_top_two_chr10....,chr15:57953424-58497866;-1|chr7:98252379-98310...,15|7|10|10|10|10|1|11|11|11|11|12|1|15|16|16|1...,0,61,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
3,gasperini_2019_atscale,4,Perturb-seq,<NA>,<NA>,C16orf91_TSS_chr1.11332_top_two_chr1.1933_top_...,chr16:1419752-1420756;-1|chr1:207378404-207378...,16|1|1|14|15|15|16|16|16|1|1|18|1|20|20|22|3|3...,0,39,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
4,gasperini_2019_atscale,5,Perturb-seq,<NA>,<NA>,chr10.185_top_two_chr10.484_top_two_chr11.4167...,chr10:4983650-4984221|chr10:12105451-12105804|...,10|10|11|12|13|14|15|15|1|18|18|18|1|18|20|20|...,0,37,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207319,gasperini_2019_atscale,207320,Perturb-seq,<NA>,<NA>,BRIX1_TSS_chr10.2059_top_two_chr10.350_top_two...,chr5:34915273-34926622;1|chr10:70821228-708218...,5|10|10|1|1|1|11|12|14|14|1|15|16|19|19|20|20|...,0,31,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
207320,gasperini_2019_atscale,207321,Perturb-seq,<NA>,<NA>,chr10.221_top_two_chr11.3853_top_two_chr11.498...,chr10:5520856-5520965|chr11:69796098-69797225|...,10|11|11|12|12|12|13|14|17|19|19|19|1|20|20|2|...,0,33,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
207321,gasperini_2019_atscale,207322,Perturb-seq,<NA>,<NA>,chr12.3400_top_two_chr4.1281_second_two_ID3_TSS,chr12:108512970-108513426|chr4:38244351-382452...,12|4|1,0,3,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
207322,gasperini_2019_atscale,207323,Perturb-seq,<NA>,<NA>,chr7.1014_top_two,chr7:13888984-13889047,7,7,1,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061
207323,gasperini_2019_atscale,207324,Perturb-seq,<NA>,<NA>,chr11.2790_top_two_chr12.306_top_two_chr12.474...,chr11:62163630-62164619|chr12:6539348-6540130|...,11|12|12|1|14|15|16|16|1|1|17|17|17|1|19|19|19...,0,35,...,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh37,"[{""dataset_accession"": ""gasperini_2019_atscale...",free to use license,SWO:1000061

# VAR slot curation

### Standardise genes

In [39]:
cur_data.adata.var['gene_name'] = cur_data.adata.var.index
cur_data.adata.var

                      ensembl_id   ncounts  ncells        gene_name
gene_symbol
ENSG00000238009  ENSG00000238009    4062.0    3970  ENSG00000238009
ENSG00000237683  ENSG00000237683   13643.0   12625  ENSG00000237683
ENSG00000228463  ENSG00000228463  135915.0   90115  ENSG00000228463
ENSG00000237094  ENSG00000237094    4796.0    4706  ENSG00000237094
ENSG00000235373  ENSG00000235373   10491.0   10072  ENSG00000235373
...                          ...       ...     ...              ...
ENSG00000215689  ENSG00000215689    6117.0    5943  ENSG00000215689
ENSG00000215781  ENSG00000215781   43665.0   36415  ENSG00000215781
ENSG00000220023  ENSG00000220023  201108.0  113584  ENSG00000220023
ENSG00000215615  ENSG00000215615   11583.0   10902  ENSG00000215615
ENSG00000215699  ENSG00000215699    2285.0    2264  ENSG00000215699

[13135 rows x 4 columns]

In [40]:
cur_data.standardize_genes(
    slot="var",
    input_column="ensembl_id",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

Missing Ensembl IDs: ['ENSG00000271976', 'ENSG00000223797', 'ENSG00000242861', 'ENSG00000272520', 'ENSG00000273314', 'ENSG00000206176', 'ENSG00000267283', 'ENSG00000232063', 'ENSG00000254690', 'ENSG00000269973', 'ENSG00000273295', 'ENSG00000273055', 'ENSG00000269936', 'ENSG00000215615', 'ENSG00000148362', 'ENSG00000162290', 'ENSG00000227540', 'ENSG00000267199', 'ENSG00000260267', 'ENSG00000261542', 'ENSG00000226377', 'ENSG00000206129', 'ENSG00000272969', 'ENSG00000272416', 'ENSG00000215066', 'ENSG00000225643', 'ENSG00000260500', 'ENSG00000272593', 'ENSG00000259959', 'ENSG00000269068', 'ENSG00000261158', 'ENSG00000251867', 'ENSG00000184886', 'ENSG00000272960', 'ENSG00000233903', 'ENSG00000236030', 'ENSG00000228779', 'ENSG00000237481', 'ENSG00000259799', 'ENSG00000271912', 'ENSG00000262967', 'ENSG00000257207', 'ENSG00000238261', 'ENSG00000272053', 'ENSG00000272827', 'ENSG00000262758', 'ENSG00000272579', 'ENSG00000271204', 'ENSG00000273271', 'ENSG00000248835', 'ENSG00000271308', 'ENSG00000236449', 'ENSG00000230258', 'ENSG00000267073', 'ENSG00000270147', 'ENSG00000272630', 'ENSG00000249166', 'ENSG00000269640', 'ENSG00000005955', 'ENSG00000272588', 'ENSG00000273477', 'ENSG00000161326', 'ENSG00000229278', 'ENSG00000259594', 'ENSG00000261159', 'ENSG00000242282', 'ENSG00000272172', 'ENSG00000197701', 'ENSG00000231360', 'ENSG00000271320', 'ENSG00000258053', 'ENSG00000268836', 'ENSG00000273226', 'ENSG00000251615', 'ENSG00000212734', 'ENSG00000235774', 'ENSG00000262089', 'ENSG00000272468', 'ENSG00000271359', 'ENSG00000268362', 'ENSG00000163486', 'ENSG00000236943', 'ENSG00000269890', 'ENSG00000171282', 'ENSG00000225889', 'ENSG00000272049', 'ENSG00000229178', 'ENSG00000196648', 'ENSG00000270574', 'ENSG00000271780', 'ENSG00000261584', 'ENSG00000273338', 'ENSG00000205147', 'ENSG00000233137', 'ENSG00000172660', 'ENSG00000183657', 'ENSG00000260077', 'ENSG00000247011', 'ENSG00000236008', 'ENSG00000259820', 'ENSG00000247121', 'ENSG00000261135', 'ENSG00000251085', 'ENSG00000197914', 'ENSG00000267964', 'ENSG00000198339', 'ENSG00000269910', 'ENSG00000259363', 'ENSG00000272667', 'ENSG00000266795', 'ENSG00000056661', 'ENSG00000254972', 'ENSG00000273374', 'ENSG00000154035', 'ENSG00000141141', 'ENSG00000261141', 'ENSG00000167765', 'ENSG00000138293', 'ENSG00000248664', 'ENSG00000272918', 'ENSG00000235477', 'ENSG00000273210', 'ENSG00000197846', 'ENSG00000232116', 'ENSG00000227895', 'ENSG00000239407', 'ENSG00000260404', 'ENSG00000235999', 'ENSG00000226381', 'ENSG00000269983', 'ENSG00000230055', 'ENSG00000198374', 'ENSG00000232336', 'ENSG00000272764', 'ENSG00000256045', 'ENSG00000271141', 'ENSG00000272341', 'ENSG00000272869', 'ENSG00000215271', 'ENSG00000239791', 'ENSG00000205664', 'ENSG00000263063', 'ENSG00000250838', 'ENSG00000264577', 'ENSG00000203325', 'ENSG00000225532', 'ENSG00000233818', 'ENSG00000130201', 'ENSG00000260563', 'ENSG00000267811', 'ENSG00000205047', 'ENSG00000260023', 'ENSG00000226899', 'ENSG00000263089', 'ENSG00000236255', 'ENSG00000272365', 'ENSG00000248223', 'ENSG00000255455', 'ENSG00000230325', 'ENSG00000269375', 'ENSG00000259071', 'ENSG00000273181', 'ENSG00000264548', 'ENSG00000243155', 'ENSG00000255389', 'ENSG00000197459', 'ENSG00000258667', 'ENSG00000236537', 'ENSG00000261788', 'ENSG00000235609', 'ENSG00000251131', 'ENSG00000168274', 'ENSG00000260495', 'ENSG00000175898', 'ENSG00000271971', 'ENSG00000232018', 'ENSG00000269947', 'ENSG00000266602', 'ENSG00000272862', 'ENSG00000256316', 'ENSG00000260507', 'ENSG00000269106', 'ENSG00000229729', 'ENSG00000251199', 'ENSG00000272016', 'ENSG00000273449', 'ENSG00000261732', 'ENSG00000229801', 'ENSG00000272005', 'ENSG00000203279', 'ENSG00000222043', 'ENSG00000272696', 'ENSG00000272799', 'ENSG00000171471', 'ENSG00000272146', 'ENSG00000270012', 'ENSG00000222030', 'ENSG00000224738', 'ENSG00000272308', 'ENSG00000255495', 'ENSG00000242180', 'ENSG00000263350', 'ENSG00000260060', 'ENSG00000271754', 'ENSG00000272356', 'ENSG00000174100', 'ENSG00000196331', 'ENSG00000269028', 'ENSG00000234147', 'ENSG00000260006', 'ENSG00000250501', 'ENSG00000272750', 'ENSG00000260273', 'ENSG00000270102', 'ENSG00000255328', 'ENSG00000272572', 'ENSG00000268211', 'ENSG00000264808', 'ENSG00000256164', 'ENSG00000273151', 'ENSG00000261526', 'ENSG00000124529', 'ENSG00000259806', 'ENSG00000257740', 'ENSG00000170647', 'ENSG00000240401', 'ENSG00000254082', 'ENSG00000242013', 'ENSG00000267327', 'ENSG00000260482', 'ENSG00000267069', 'ENSG00000260289', 'ENSG00000261613', 'ENSG00000266040', 'ENSG00000271918', 'ENSG00000272971', 'ENSG00000268397', 'ENSG00000226310', 'ENSG00000214248', 'ENSG00000255823', 'ENSG00000242349', 'ENSG00000260923', 'ENSG00000266378', 'ENSG00000273355', 'ENSG00000267649', 'ENSG00000253459', 'ENSG00000108270', 'ENSG00000269337', 'ENSG00000272452', 'ENSG00000272854', 'ENSG00000265100', 'ENSG00000112096', 'ENSG00000155984', 'ENSG00000239467', 'ENSG00000205246', 'ENSG00000230880', 'ENSG00000273192', 'ENSG00000213240', 'ENSG00000187156', 'ENSG00000068793', 'ENSG00000251259', 'ENSG00000271109', 'ENSG00000203258', 'ENSG00000233912', 'ENSG00000258593', 'ENSG00000163067', 'ENSG00000181039', 'ENSG00000260054', 'ENSG00000273448', 'ENSG00000272093', 'ENSG00000006114', 'ENSG00000272942', 'ENSG00000272792', 'ENSG00000250049', 'ENSG00000264066', 'ENSG00000229970', 'ENSG00000267785', 'ENSG00000272719', 'ENSG00000262227', 'ENSG00000226920', 'ENSG00000250400', 'ENSG00000269614', 'ENSG00000273014', 'ENSG00000129282', 'ENSG00000077809', 'ENSG00000272661', 'ENSG00000271989', 'ENSG00000225667', 'ENSG00000160844', 'ENSG00000273204', 'ENSG00000271781', 'ENSG00000263331', 'ENSG00000272010', 'ENSG00000271590', 'ENSG00000263826', 'ENSG00000226434', 'ENSG00000258486', 'ENSG00000174111', 'ENSG00000273141', 'ENSG00000214770', 'ENSG00000183558', 'ENSG00000271427', 'ENSG00000261098', 'ENSG00000235381', 'ENSG00000272070', 'ENSG00000163386', 'ENSG00000260274', 'ENSG00000261766', 'ENSG00000272906', 'ENSG00000272256', 'ENSG00000237188', 'ENSG00000271937', 'ENSG00000231856', 'ENSG00000116957', 'ENSG00000237311', 'ENSG00000267007', 'ENSG00000187456', 'ENSG00000203849', 'ENSG00000270052', 'ENSG00000261845', 'ENSG00000271895', 'ENSG00000268798', 'ENSG00000264067', 'ENSG00000203813', 'ENSG00000268536', 'ENSG00000265739', 'ENSG00000272106', 'ENSG00000271155', 'ENSG00000272434', 'ENSG00000236624', 'ENSG00000270346', 'ENSG00000241732', 'ENSG00000260126', 'ENSG00000270017', 'ENSG00000272092', 'ENSG00000257925', 'ENSG00000226266', 'ENSG00000260857', 'ENSG00000262049', 'ENSG00000257831', 'ENSG00000272554', 'ENSG00000116883', 'ENSG00000198477', 'ENSG00000227388', 'ENSG00000135847', 'ENSG00000261136', 'ENSG00000187990', 'ENSG00000271751', 'ENSG00000263470', 'ENSG00000264207', 'ENSG00000272715', 'ENSG00000166157', 'ENSG00000179294', 'ENSG00000267458', 'ENSG00000179837', 'ENSG00000256101', 'ENSG00000270018', 'ENSG00000174093', 'ENSG00000242553', 'ENSG00000267563', 'ENSG00000269423', 'ENSG00000258028', 'ENSG00000267941', 'ENSG00000271936', 'ENSG00000265254', 'ENSG00000271835', 'ENSG00000260621', 'ENSG00000253706', 'ENSG00000183308', 'ENSG00000108278', 'ENSG00000273329', 'ENSG00000203817', 'ENSG00000271964', 'ENSG00000270605', 'ENSG00000261252', 'ENSG00000267002', 'ENSG00000267062', 'ENSG00000261428', 'ENSG00000273391', 'ENSG00000272316', 'ENSG00000270127', 'ENSG00000254539', 'ENSG00000263823', 'ENSG00000272216', 'ENSG00000268573', 'ENSG00000273080', 'ENSG00000272050', 'ENSG00000259865', 'ENSG00000273456', 'ENSG00000196409', 'ENSG00000268030', 'ENSG00000269975', 'ENSG00000269921', 'ENSG00000242375', 'ENSG00000269175', 'ENSG00000269399', 'ENSG00000269514', 'ENSG00000268852', 'ENSG00000225173', 'ENSG00000235373', 'ENSG00000232194', 'ENSG00000244291', 'ENSG00000182912', 'ENSG00000271862', 'ENSG00000269979', 'ENSG00000108264', 'ENSG00000227681', 'ENSG00000272501', 'ENSG00000272444', 'ENSG00000272948', 'ENSG00000242687', 'ENSG00000262951', 'ENSG00000143466', 'ENSG00000228434', 'ENSG00000269963', 'ENSG00000236016', 'ENSG00000229728', 'ENSG00000177764', 'ENSG00000269846', 'ENSG00000237940', 'ENSG00000272821', 'ENSG00000225807', 'ENSG00000228265', 'ENSG00000271855', 'ENSG00000266490', 'ENSG00000270030', 'ENSG00000257742', 'ENSG00000221995', 'ENSG00000261353', 'ENSG00000179979', 'ENSG00000228327', 'ENSG00000268364', 'ENSG00000263320', 'ENSG00000255318', 'ENSG00000259001', 'ENSG00000261211', 'ENSG00000182109', 'ENSG00000254397', 'ENSG00000213863', 'ENSG00000259985', 'ENSG00000234449', 'ENSG00000260793', 'ENSG00000249604', 'ENSG00000255145', 'ENSG00000137259', 'ENSG00000271746', 'ENSG00000270172', 'ENSG00000249069', 'ENSG00000260651', 'ENSG00000138041', 'ENSG00000228463', 'ENSG00000271788', 'ENSG00000272953', 'ENSG00000270189', 'ENSG00000205663', 'ENSG00000250397', 'ENSG00000203441', 'ENSG00000259345', 'ENSG00000141720', 'ENSG00000272644', 'ENSG00000271011', 'ENSG00000267011', 'ENSG00000269604', 'ENSG00000272769', 'ENSG00000251487', 'ENSG00000260065', 'ENSG00000272991', 'ENSG00000273416', 'ENSG00000273139', 'ENSG00000272993', 'ENSG00000259605', 'ENSG00000272800', 'ENSG00000135213', 'ENSG00000272079', 'ENSG00000273248', 'ENSG00000270949', 'ENSG00000273175', 'ENSG00000271789', 'ENSG00000272201', 'ENSG00000272486', 'ENSG00000267167', 'ENSG00000237683', 'ENSG00000259915', 'ENSG00000270195', 'ENSG00000234936', 'ENSG00000260000', 'ENSG00000243452', 'ENSG00000226751', 'ENSG00000173566', 'ENSG00000261242', 'ENSG00000270081', 'ENSG00000271659', 'ENSG00000253200', 'ENSG00000141150', 'ENSG00000257613', 'ENSG00000121848', 'ENSG00000262873', 'ENSG00000267546', 'ENSG00000273010', 'ENSG00000228439', 'ENSG00000182368', 'ENSG00000272004', 'ENSG00000260588', 'ENSG00000073009', 'ENSG00000130723', 'ENSG00000188987', 'ENSG00000227230', 'ENSG00000271797', 'ENSG00000263105', 'ENSG00000244733', 'ENSG00000130489', 'ENSG00000266709', 'ENSG00000269089', 'ENSG00000268565', 'ENSG00000225075', 'ENSG00000264112', 'ENSG00000266538', 'ENSG00000225986', 'ENSG00000244310', 'ENSG00000273290', 'ENSG00000272009', 'ENSG00000258561', 'ENSG00000230233', 'ENSG00000272144', 'ENSG00000272760', 'ENSG00000259972', 'ENSG00000270638', 'ENSG00000196355', 'ENSG00000235078', 'ENSG00000271927', 'ENSG00000272986', 'ENSG00000186275', 'ENSG00000259264', 'ENSG00000250874', 'ENSG00000182500', 'ENSG00000184779', 'ENSG00000272592', 'ENSG00000259529', 'ENSG00000226471', 'ENSG00000244459', 'ENSG00000264194', 'ENSG00000232941', 'ENSG00000272405', 'ENSG00000272831', 'ENSG00000268858', 'ENSG00000226380', 'ENSG00000270681', 'ENSG00000187145', 'ENSG00000265242', 'ENSG00000255139', 'ENSG00000248103', 'ENSG00000213865', 'ENSG00000267010', 'ENSG00000236933', 'ENSG00000223474', 'ENSG00000226524', 'ENSG00000254859', 'ENSG00000256967', 'ENSG00000261589', 'ENSG00000256116', 'ENSG00000250186', 'ENSG00000253154', 'ENSG00000260879', 'ENSG00000263531', 'ENSG00000272817', 'ENSG00000272955', 'ENSG00000259901', 'ENSG00000233937', 'ENSG00000255046', 'ENSG00000267231', 'ENSG00000204377', 'ENSG00000268885', 'ENSG00000239665', 'ENSG00000258122', 'ENSG00000225411', 'ENSG00000253584', 'ENSG00000231599', 'ENSG00000227184', 'ENSG00000231196', 'ENSG00000272973', 'ENSG00000184348', 'ENSG00000270019', 'ENSG00000234261', 'ENSG00000268171', 'ENSG00000225335', 'ENSG00000257327', 'ENSG00000220023', 'ENSG00000230615', 'ENSG00000198518', 'ENSG00000270190', 'ENSG00000272218', 'ENSG00000231242', 'ENSG00000225490', 'ENSG00000215750', 'ENSG00000155640', 'ENSG00000174374', 'ENSG00000203832', 'ENSG00000232949', 'ENSG00000108272', 'ENSG00000272077', 'ENSG00000266086', 'ENSG00000256341', 'ENSG00000228393', 'ENSG00000141140', 'ENSG00000260196', 'ENSG00000267243', 'ENSG00000231903', 'ENSG00000271795', 'ENSG00000272030', 'ENSG00000227598', 'ENSG00000272156', 'ENSG00000232611', 'ENSG00000261005', 'ENSG00000272768', 'ENSG00000260360', 'ENSG00000273361', 'ENSG00000237094', 'ENSG00000241666', 'ENSG00000258634', 'ENSG00000152487', 'ENSG00000272829', 'ENSG00000268218', 'ENSG00000270175', 'ENSG00000267571', 'ENSG00000017621', 'ENSG00000260261', 'ENSG00000176274', 'ENSG00000272892', 'ENSG00000267892', 'ENSG00000261737', 'ENSG00000254615', 'ENSG00000229896', 'ENSG00000272432', 'ENSG00000267042', 'ENSG00000259886', 'ENSG00000272599', 'ENSG00000235806', 'ENSG00000232833', 'ENSG00000253642', 'ENSG00000198750', 'ENSG00000152726', 'ENSG00000248175', 'ENSG00000225278', 'ENSG00000253426', 'ENSG00000269990', 'ENSG00000267161', 'ENSG00000131795', 'ENSG00000215699', 'ENSG00000255509', 'ENSG00000261889', 'ENSG00000270143', 'ENSG00000261177', 'ENSG00000251606', 'ENSG00000272631', 'ENSG00000225135', 'ENSG00000272807', 'ENSG00000231025', 'ENSG00000230159', 'ENSG00000258297', 'ENSG00000253377', 'ENSG00000261200', 'ENSG00000273058', 'ENSG00000233280', 'ENSG00000272843', 'ENSG00000273254', 'ENSG00000271043', 'ENSG00000264198', 'ENSG00000232274', 'ENSG00000260655', 'ENSG00000261071', 'ENSG00000108296', 'ENSG00000264469', 'ENSG00000270557', 'ENSG00000136653', 'ENSG00000236266', 'ENSG00000272565', 'ENSG00000262580', 'ENSG00000163009', 'ENSG00000108294', 'ENSG00000174194', 'ENSG00000228989', 'ENSG00000185044', 'ENSG00000273063', 'ENSG00000230177', 'ENSG00000272449', 'ENSG00000184825', 'ENSG00000273373', 'ENSG00000269728', 'ENSG00000227917', 'ENSG00000229874', 'ENSG00000272017', 'ENSG00000225485', 'ENSG00000265287', 'ENSG00000242569', 'ENSG00000239415', 'ENSG00000138297', 'ENSG00000204790', 'ENSG00000147382', 'ENSG00000273466', 'ENSG00000273203', 'ENSG00000272735', 'ENSG00000234978', 'ENSG00000227192', 'ENSG00000266893', 'ENSG00000224746', 'ENSG00000212939', 'ENSG00000273486', 'ENSG00000258757', 'ENSG00000273199', 'ENSG00000262202', 'ENSG00000155130', 'ENSG00000255224', 'ENSG00000263272', 'ENSG00000117289', 'ENSG00000269600', 'ENSG00000261140', 'ENSG00000226252', 'ENSG00000223473', 'ENSG00000259891', 'ENSG00000133808', 'ENSG00000124693', 'ENSG00000268069', 'ENSG00000257553', 'ENSG00000259274', 'ENSG00000272540', 'ENSG00000270145', 'ENSG00000267067', 'ENSG00000250284', 'ENSG00000259758', 'ENSG00000269781', 'ENSG00000272277', 'ENSG00000267957', 'ENSG00000271993', 'ENSG00000153575', 'ENSG00000182021', 'ENSG00000269988', 'ENSG00000272688', 'ENSG00000250132', 'ENSG00000228106', 'ENSG00000260585', 'ENSG00000271020', 'ENSG00000108292', 'ENSG00000258081', 'ENSG00000260539', 'ENSG00000225205', 'ENSG00000256146', 'ENSG00000248268', 'ENSG00000204620', 'ENSG00000248884', 'ENSG00000261351', 'ENSG00000267939', 'ENSG00000188971', 'ENSG00000259937', 'ENSG00000270109', 'ENSG00000204957', 'ENSG00000257764', 'ENSG00000255103', 'ENSG00000242828', 'ENSG00000263731', 'ENSG00000230850', 'ENSG00000233255', 'ENSG00000152022', 'ENSG00000228389', 'ENSG00000262194', 'ENSG00000261474', 'ENSG00000273230', 'ENSG00000262050', 'ENSG00000198106', 'ENSG00000215781', 'ENSG00000233224', 'ENSG00000261519', 'ENSG00000269974', 'ENSG00000270022', 'ENSG00000069712', 'ENSG00000168614', 'ENSG00000269968', 'ENSG00000251434', 'ENSG00000273107', 'ENSG00000272335', 'ENSG00000223504', 'ENSG00000230074', 'ENSG00000272936', 'ENSG00000270696', 'ENSG00000272476', 'ENSG00000271870', 'ENSG00000272669', 'ENSG00000215067', 'ENSG00000152042', 'ENSG00000248475', 'ENSG00000163113', 'ENSG00000268603', 'ENSG00000272153', 'ENSG00000269996', 'ENSG00000257086', 'ENSG00000250453', 'ENSG00000261216', 'ENSG00000269176', 'ENSG00000261884', 'ENSG00000238033', 'ENSG00000269657', 'ENSG00000272524', 'ENSG00000248596', 'ENSG00000258944', 'ENSG00000260349', 'ENSG00000263214', 'ENSG00000271737', 'ENSG00000269937', 'ENSG00000215689', 'ENSG00000273004', 'ENSG00000272426', 'ENSG00000262877', 'ENSG00000260095', 'ENSG00000132142', 'ENSG00000268945', 'ENSG00000238009', 'ENSG00000273064', 'ENSG00000272754', 'ENSG00000255031', 'ENSG00000261770', 'ENSG00000268713', 'ENSG00000258927', 'ENSG00000269482', 'ENSG00000273319', 'ENSG00000272202', 'ENSG00000268568', 'ENSG00000261386', 'ENSG00000268172', 'ENSG00000258301', 'ENSG00000262768', 'ENSG00000223492', 'ENSG00000240033', 'ENSG00000272367', 'ENSG00000267268', 'ENSG00000224330', 'ENSG00000266753', 'ENSG00000267427', 'ENSG00000272338', 'ENSG00000268584', 'ENSG00000188206', 'ENSG00000265008', 'ENSG00000261088', 'ENSG00000228084', 'ENSG00000184674', 'ENSG00000266450', 'ENSG00000237857', 'ENSG00000271975', 'ENSG00000260872', 'ENSG00000225163', 'ENSG00000196176', 'ENSG00000267383', 'ENSG00000259460', 'ENSG00000271933']; attempting to fetch latest IDs...
852 unmapped ENSG IDs identified; splitting into chunks of 500.
Processing IDs 1 to 500...
Processing IDs 501 to 852...

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [41]:
cur_data.adata.var

,gene_name,ensembl_id,ncells,ncounts,ensembl_gene_id,gene_symbol,original_index
index,,,,,,,
0,ENSG00000238009,ENSG00000238009,3970,4062.0,ENSG00000241860,NaN,ENSG00000238009
1,ENSG00000237683,ENSG00000237683,12625,13643.0,ENSG00000237683,NaN,ENSG00000237683
2,ENSG00000228463,ENSG00000228463,90115,135915.0,ENSG00000228463,NaN,ENSG00000228463
3,ENSG00000237094,ENSG00000237094,4706,4796.0,ENSG00000237094,NaN,ENSG00000237094
4,ENSG00000235373,ENSG00000235373,10072,10491.0,ENSG00000235373,NaN,ENSG00000235373
...,...,...,...,...,...,...,...
13130,ENSG00000215689,ENSG00000215689,5943,6117.0,ENSG00000215689,NaN,ENSG00000215689
13131,ENSG00000215781,ENSG00000215781,36415,43665.0,ENSG00000215781,NaN,ENSG00000215781
13132,ENSG00000220023,ENSG00000220023,113584,201108.0,ENSG00000220023,NaN,ENSG00000220023
13133,ENSG00000215615,ENSG00000215615,10902,11583.0,ENSG00000215615,NaN,ENSG00000215615
13134,ENSG00000215699,ENSG00000215699,2264,2285.0,ENSG00000215699,NaN,ENSG00000215699

### Validate var metadata

In [42]:
cur_data.validate_data(slot='var')

       ensembl_gene_id gene_symbol
index
0      ENSG00000241860         NaN
1      ENSG00000237683         NaN
2      ENSG00000228463         NaN
3      ENSG00000237094         NaN
4      ENSG00000235373         NaN
...                ...         ...
13130  ENSG00000215689         NaN
13131  ENSG00000215781         NaN
13132  ENSG00000220023         NaN
13133  ENSG00000215615         NaN
13134  ENSG00000215699         NaN

[13135 rows x 2 columns]

# Save the dataset

In [43]:
cur_data.save_curated_data_h5ad()

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/gasperini_2019_atscale_curated.h5ad

In [44]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/gasperini_2019_atscale_curated_metadata.parquet

# Upload to BigQuery

In [46]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/gasperini_2019_atscale_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

Staging table: loading `.parquet` file ../curated/parquet/gasperini_2019_atscale_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...
Staging table: loaded 207324 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [45]:
!gcloud storage cp ../curated/h5ad/gasperini_2019_atscale_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/gasperini_2019_atscale_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/gasperini_2019_atscale_curated.h5ad
  Completed files 32/1 | 5.9GiB/5.9GiB | 11.5MiB/s

Average throughput: 19.5MiB/s


Updates are available for some Google Cloud CLI components.  To install them,
please run:
  $ gcloud components update



To take a quick anonymous survey, run:
  $ gcloud survey