# Import

In [1]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("curation.log"),
        logging.StreamHandler(),  # keep console output too
    ],
    force=True,
)

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/.venv/lib/python3.12/site-packages/pandera/_pandas_deprecated.py:157: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

# Download data

In [2]:
noncurated_path = "../non_curated/h5ad/norman_2019_raw.h5ad"
download_file(
    url="https://exampledata.scverse.org/pertpy/norman_2019_raw.h5ad",
    dest_path=noncurated_path
)

File ../non_curated/h5ad/norman_2019_raw.h5ad already exists. Skipping download.

# Initialise the dataset object

In [3]:
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/norman_2019_raw.h5ad

In [4]:
cur_data.adata.obs

,guide_identity,read_count,UMI_count,coverage,gemgroup,good_coverage,number_of_cells,guide_AHR,guide_ARID1A,guide_ARRDC3,...,guide_TP73,guide_TSC22D1,guide_UBASH3A,guide_UBASH3B,guide_ZBTB1,guide_ZBTB10,guide_ZBTB25,guide_ZC3HAV1,guide_ZNF318,guide_ids
index,,,,,,,,,,,,,,,,,,,,,
AAACCTGAGAAGAAGC-1,NegCtrl0_NegCtrl0__NegCtrl0_NegCtrl0,1252,67,18.686567,1,True,2,0,0,0,...,0,0,0,0,0,0,0,0,0,
AAACCTGAGGCATGTG-1,TSC22D1_NegCtrl0__TSC22D1_NegCtrl0,2151,104,20.682692,1,True,1,0,0,0,...,0,1,0,0,0,0,0,0,0,TSC22D1
AAACCTGAGGCCCTTG-1,KLF1_MAP2K6__KLF1_MAP2K6,1037,59,17.576271,1,True,1,0,0,0,...,0,0,0,0,0,0,0,0,0,"KLF1,MAP2K6"
AAACCTGCACGAAGCA-1,NegCtrl10_NegCtrl0__NegCtrl10_NegCtrl0,958,39,24.564103,1,True,1,0,0,0,...,0,0,0,0,0,0,0,0,0,
AAACCTGCAGACGTAG-1,CEBPE_RUNX1T1__CEBPE_RUNX1T1,244,14,17.428571,1,True,1,0,0,0,...,0,0,0,0,0,0,0,0,0,"CEBPE,RUNX1T1"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCATCAGTACGT-8,FOXA3_NegCtrl0__FOXA3_NegCtrl0,2068,95,21.768421,8,True,1,0,0,0,...,0,0,0,0,0,0,0,0,0,FOXA3
TTTGTCATCCACTCCA-8,CELF2_NegCtrl0__CELF2_NegCtrl0,829,33,25.121212,8,True,1,0,0,0,...,0,0,0,0,0,0,0,0,0,CELF2
TTTGTCATCCCAACGG-8,BCORL1_NegCtrl0__BCORL1_NegCtrl0,136,9,15.111111,8,True,1,0,0,0,...,0,0,0,0,0,0,0,0,0,BCORL1
TTTGTCATCCTCCTAG-8,ZBTB10_PTPN12__ZBTB10_PTPN12,1254,59,21.254237,8,True,3,0,0,0,...,0,0,0,0,0,1,0,0,0,"PTPN12,ZBTB10"
TTTGTCATCTGGCGAC-8,MAP4K3_NegCtrl0__MAP4K3_NegCtrl0,1226,59,20.779661,8,True,1,0,0,0,...,0,0,0,0,0,0,0,0,0,MAP4K3

# OBS slot curation

### Show unique perturbations

In [5]:
cur_data.show_unique(slot = 'obs', column = 'guide_identity')

Unique values in adata.obs.guide_identity: 290
--------------------------------------------------
{'AHR_FEV__AHR_FEV',
 'AHR_KLF1__AHR_KLF1',
 'AHR_NegCtrl0__AHR_NegCtrl0',
 'ARID1A_NegCtrl0__ARID1A_NegCtrl0',
 'ARRDC3_NegCtrl0__ARRDC3_NegCtrl0',
 'ATL1_NegCtrl0__ATL1_NegCtrl0',
 'BAK1_NegCtrl0__BAK1_NegCtrl0',
 'BCL2L11_BAK1__BCL2L11_BAK1',
 'BCL2L11_NegCtrl0__BCL2L11_NegCtrl0',
 'BCL2L11_TGFBR2__BCL2L11_TGFBR2',
 'BCORL1_NegCtrl0__BCORL1_NegCtrl0',
 'BPGM_NegCtrl0__BPGM_NegCtrl0',
 'BPGM_SAMD1__BPGM_SAMD1',
 'BPGM_ZBTB1__BPGM_ZBTB1',
 'C19orf26_NegCtrl0__C19orf26_NegCtrl0',
 'C3orf72_FOXL2__C3orf72_FOXL2',
 'C3orf72_NegCtrl0__C3orf72_NegCtrl0',
 'CBFA2T3_NegCtrl0__CBFA2T3_NegCtrl0',
 'CBL_CNN1__CBL_CNN1',
 'CBL_NegCtrl0__CBL_NegCtrl0',
 'CBL_PTPN12__CBL_PTPN12',
 'CBL_PTPN9__CBL_PTPN9',
 'CBL_TGFBR2__CBL_TGFBR2',
 'CBL_UBASH3A__CBL_UBASH3A',
 'CBL_UBASH3B__CBL_UBASH3B',
 'CDKN1A_NegCtrl0__CDKN1A_NegCtrl0',
 'CDKN1B_CDKN1A__CDKN1B_CDKN1A',
 'CDKN1B_NegCtrl0__CDKN1B_NegCtrl0',
 'CDKN1C_CDKN1A__CDKN1C_CDKN1A',
 'CDKN1C_CDKN1B__CDKN1C_CDKN1B',
 'CDKN1C_NegCtrl0__CDKN1C_NegCtrl0',
 'CEBPA_NegCtrl0__CEBPA_NegCtrl0',
 'CEBPB_CEBPA__CEBPB_CEBPA',
 'CEBPB_MAPK1__CEBPB_MAPK1',
 'CEBPB_NegCtrl0__CEBPB_NegCtrl0',
 'CEBPB_OSR2__CEBPB_OSR2',
 'CEBPB_PTPN12__CEBPB_PTPN12',
 'CEBPE_CEBPA__CEBPE_CEBPA',
 'CEBPE_CEBPB__CEBPE_CEBPB',
 'CEBPE_CNN1__CEBPE_CNN1',
 'CEBPE_KLF1__CEBPE_KLF1',
 'CEBPE_NegCtrl0__CEBPE_NegCtrl0',
 'CEBPE_PTPN12__CEBPE_PTPN12',
 'CEBPE_RUNX1T1__CEBPE_RUNX1T1',
 'CEBPE_SPI1__CEBPE_SPI1',
 'CELF2_NegCtrl0__CELF2_NegCtrl0',
 'CITED1_NegCtrl0__CITED1_NegCtrl0',
 'CKS1B_NegCtrl0__CKS1B_NegCtrl0',
 'CLDN6_NegCtrl0__CLDN6_NegCtrl0',
 'CNN1_MAPK1__CNN1_MAPK1',
 'CNN1_NegCtrl0__CNN1_NegCtrl0',
 'CNN1_UBASH3A__CNN1_UBASH3A',
 'CNNM4_NegCtrl0__CNNM4_NegCtrl0',
 'COL1A1_NegCtrl0__COL1A1_NegCtrl0',
 'COL2A1_NegCtrl0__COL2A1_NegCtrl0',
 'CSRNP1_NegCtrl0__CSRNP1_NegCtrl0',
 'DLX2_NegCtrl0__DLX2_NegCtrl0',
 'DUSP9_ETS2__DUSP9_ETS2',
 'DUSP9_IGDCC3__DUSP9_IGDCC3',
 'DUSP9_KLF1__DUSP9_KLF1',
 'DUSP9_MAPK1__DUSP9_MAPK1',
 'DUSP9_NegCtrl0__DUSP9_NegCtrl0',
 'DUSP9_PRTG__DUSP9_PRTG',
 'DUSP9_SNAI1__DUSP9_SNAI1',
 'EGR1_NegCtrl0__EGR1_NegCtrl0',
 'ELMSAN1_NegCtrl0__ELMSAN1_NegCtrl0',
 'ETS2_CEBPE__ETS2_CEBPE',
 'ETS2_CNN1__ETS2_CNN1',
 'ETS2_IGDCC3__ETS2_IGDCC3',
 'ETS2_IKZF3__ETS2_IKZF3',
 'ETS2_MAP7D1__ETS2_MAP7D1',
 'ETS2_MAPK1__ETS2_MAPK1',
 'ETS2_NegCtrl0__ETS2_NegCtrl0',
 'ETS2_PRTG__ETS2_PRTG',
 'FEV_CBFA2T3__FEV_CBFA2T3',
 'FEV_ISL2__FEV_ISL2',
 'FEV_MAP7D1__FEV_MAP7D1',
 'FEV_NegCtrl0__FEV_NegCtrl0',
 'FOSB_CEBPB__FOSB_CEBPB',
 'FOSB_CEBPE__FOSB_CEBPE',
 'FOSB_IKZF3__FOSB_IKZF3',
 'FOSB_NegCtrl0__FOSB_NegCtrl0',
 'FOSB_OSR2__FOSB_OSR2',
 'FOSB_PTPN12__FOSB_PTPN12',
 'FOSB_UBASH3B__FOSB_UBASH3B',
 'FOXA1_FOXF1__FOXA1_FOXF1',
 'FOXA1_FOXL2__FOXA1_FOXL2',
 'FOXA1_HOXB9__FOXA1_HOXB9',
 'FOXA1_NegCtrl0__FOXA1_NegCtrl0',
 'FOXA3_FOXA1__FOXA3_FOXA1',
 'FOXA3_FOXF1__FOXA3_FOXF1',
 'FOXA3_FOXL2__FOXA3_FOXL2',
 'FOXA3_HOXB9__FOXA3_HOXB9',
 'FOXA3_NegCtrl0__FOXA3_NegCtrl0',
 'FOXF1_FOXL2__FOXF1_FOXL2',
 'FOXF1_HOXB9__FOXF1_HOXB9',
 'FOXF1_NegCtrl0__FOXF1_NegCtrl0',
 'FOXL2_HOXB9__FOXL2_HOXB9',
 'FOXL2_MEIS1__FOXL2_MEIS1',
 'FOXL2_NegCtrl0__FOXL2_NegCtrl0',
 'FOXO4_NegCtrl0__FOXO4_NegCtrl0',
 'GLB1L2_NegCtrl0__GLB1L2_NegCtrl0',
 'HES7_NegCtrl0__HES7_NegCtrl0',
 'HK2_NegCtrl0__HK2_NegCtrl0',
 'HNF4A_NegCtrl0__HNF4A_NegCtrl0',
 'HOXA13_NegCtrl0__HOXA13_NegCtrl0',
 'HOXB9_NegCtrl0__HOXB9_NegCtrl0',
 'HOXC13_NegCtrl0__HOXC13_NegCtrl0_1',
 'HOXC13_NegCtrl0__HOXC13_NegCtrl0_2',
 'IER5L_NegCtrl0__IER5L_NegCtrl0',
 'IGDCC3_MAPK1__IGDCC3_MAPK1',
 'IGDCC3_NegCtrl0__IGDCC3_NegCtrl0',
 'IGDCC3_PRTG__IGDCC3_PRTG',
 'IGDCC3_ZBTB25__IGDCC3_ZBTB25',
 'IKZF3_NegCtrl0__IKZF3_NegCtrl0',
 'IRF1_NegCtrl0__IRF1_NegCtrl0',
 'IRF1_SET__IRF1_SET',
 'ISL2_NegCtrl0__ISL2_NegCtrl0',
 'JUN_CEBPA__JUN_CEBPA',
 'JUN_CEBPB__JUN_CEBPB',
 'JUN_NegCtrl0__JUN_NegCtrl0',
 'KIAA1804_NegCtrl0__KIAA1804_NegCtrl0',
 'KIF18B_KIF2C__KIF18B_KIF2C',
 'KIF18B_NegCtrl0__KIF18B_NegCtrl0',
 'KIF2C_NegCtrl0__KIF2C_NegCtrl0',
 'KLF1_BAK1__KLF1_BAK1',
 'KLF1_CEBPA__KLF1_CEBPA',
 'KLF1_CLDN6__KLF1_CLDN6',
 'KLF1_COL2A1__KLF1_COL2A1',
 'KLF1_FOXA1__KLF1_FOXA1',
 'KLF1_MAP2K6__KLF1_MAP2K6',
 'KLF1_NegCtrl0__KLF1_NegCtrl0',
 'KLF1_TGFBR2__KLF1_TGFBR2',
 'KMT2A_NegCtrl0__KMT2A_NegCtrl0',
 'LHX1_ELMSAN1__LHX1_ELMSAN1',
 'LHX1_NegCtrl0__LHX1_NegCtrl0',
 'LYL1_CEBPB__LYL1_CEBPB',
 'LYL1_IER5L__LYL1_IER5L',
 'LYL1_NegCtrl0__LYL1_NegCtrl0',
 'MAML2_NegCtrl0__MAML2_NegCtrl0',
 'MAP2K3_ELMSAN1__MAP2K3_ELMSAN1',
 'MAP2K3_IKZF3__MAP2K3_IKZF3',
 'MAP2K3_MAP2K6__MAP2K3_MAP2K6',
 'MAP2K3_NegCtrl0__MAP2K3_NegCtrl0',
 'MAP2K3_SLC38A2__MAP2K3_SLC38A2',
 'MAP2K6_ELMSAN1__MAP2K6_ELMSAN1',
 'MAP2K6_IKZF3__MAP2K6_IKZF3',
 'MAP2K6_NegCtrl0__MAP2K6_NegCtrl0',
 'MAP2K6_SPI1__MAP2K6_SPI1',
 'MAP4K3_NegCtrl0__MAP4K3_NegCtrl0',
 'MAP4K5_NegCtrl0__MAP4K5_NegCtrl0',
 'MAP7D1_NegCtrl0__MAP7D1_NegCtrl0',
 'MAPK1_IKZF3__MAPK1_IKZF3',
 'MAPK1_NegCtrl0__MAPK1_NegCtrl0',
 'MAPK1_PRTG__MAPK1_PRTG',
 'MAPK1_TGFBR2__MAPK1_TGFBR2',
 'MEIS1_NegCtrl0__MEIS1_NegCtrl0',
 'MIDN_NegCtrl0__MIDN_NegCtrl0',
 'NCL_NegCtrl0__NCL_NegCtrl0',
 'NIT1_NegCtrl0__NIT1_NegCtrl0',
 'NegCtrl0_BAK1__NegCtrl0_BAK1',
 'NegCtrl0_C19orf26__NegCtrl0_C19orf26',
 'NegCtrl0_CBFA2T3__NegCtrl0_CBFA2T3',
 'NegCtrl0_CDKN1A__NegCtrl0_CDKN1A',
 'NegCtrl0_CDKN1B__NegCtrl0_CDKN1B',
 'NegCtrl0_CEBPA__NegCtrl0_CEBPA',
 'NegCtrl0_CEBPB__NegCtrl0_CEBPB',
 'NegCtrl0_CEBPE__NegCtrl0_CEBPE',
 'NegCtrl0_CLDN6__NegCtrl0_CLDN6',
 'NegCtrl0_CNN1__NegCtrl0_CNN1',
 'NegCtrl0_COL2A1__NegCtrl0_COL2A1',
 'NegCtrl0_DLX2__NegCtrl0_DLX2',
 'NegCtrl0_ELMSAN1__NegCtrl0_ELMSAN1',
 'NegCtrl0_ETS2__NegCtrl0_ETS2',
 'NegCtrl0_FEV__NegCtrl0_FEV',
 'NegCtrl0_FOXA1__NegCtrl0_FOXA1',
 'NegCtrl0_FOXF1__NegCtrl0_FOXF1',
 'NegCtrl0_FOXL2__NegCtrl0_FOXL2',
 'NegCtrl0_HOXB9__NegCtrl0_HOXB9',
 'NegCtrl0_HOXC13__NegCtrl0_HOXC13',
 'NegCtrl0_IER5L__NegCtrl0_IER5L',
 'NegCtrl0_IGDCC3__NegCtrl0_IGDCC3',
 'NegCtrl0_IKZF3__NegCtrl0_IKZF3',
 'NegCtrl0_ISL2__NegCtrl0_ISL2',
 'NegCtrl0_KIF2C__NegCtrl0_KIF2C',
 'NegCtrl0_KLF1__NegCtrl0_KLF1',
 'NegCtrl0_MAP2K6__NegCtrl0_MAP2K6',
 'NegCtrl0_MAP7D1__NegCtrl0_MAP7D1',
 'NegCtrl0_MAPK1__NegCtrl0_MAPK1',
 'NegCtrl0_MEIS1__NegCtrl0_MEIS1',
 'NegCtrl0_NegCtrl0__NegCtrl0_NegCtrl0',
 'NegCtrl0_OSR2__NegCtrl0_OSR2',
 'NegCtrl0_PRTG__NegCtrl0_PRTG',
 'NegCtrl0_PTPN12__NegCtrl0_PTPN12',
 'NegCtrl0_PTPN9__NegCtrl0_PTPN9',
 'NegCtrl0_RUNX1T1__NegCtrl0_RUNX1T1',
 'NegCtrl0_SAMD1__NegCtrl0_SAMD1',
 'NegCtrl0_SET__NegCtrl0_SET',
 'NegCtrl0_SLC38A2__NegCtrl0_SLC38A2',
 'NegCtrl0_SNAI1__NegCtrl0_SNAI1',
 'NegCtrl0_SPI1__NegCtrl0_SPI1',
 'NegCtrl0_STIL__NegCtrl0_STIL',
 'NegCtrl0_TBX2__NegCtrl0_TBX2',
 'NegCtrl0_TBX3__NegCtrl0_TBX3',
 'NegCtrl0_TGFBR2__NegCtrl0_TGFBR2',
 'NegCtrl0_UBASH3A__NegCtrl0_UBASH3A',
 'NegCtrl0_UBASH3B__NegCtrl0_UBASH3B',
 'NegCtrl0_ZBTB1__NegCtrl0_ZBTB1',
 'NegCtrl0_ZBTB25__NegCtrl0_ZBTB25',
 'NegCtrl10_NegCtrl0__NegCtrl10_NegCtrl0',
 'NegCtrl11_NegCtrl0__NegCtrl11_NegCtrl0',
 'NegCtrl1_NegCtrl0__NegCtrl1_NegCtrl0',
 'OSR2_NegCtrl0__OSR2_NegCtrl0',
 'PLK4_NegCtrl0__PLK4_NegCtrl0',
 'PLK4_STIL__PLK4_STIL',
 'POU3F2_CBFA2T3__POU3F2_CBFA2T3',
 'POU3F2_FOXL2__POU3F2_FOXL2',
 'POU3F2_NegCtrl0__POU3F2_NegCtrl0',
 'PRDM1_CBFA2T3__PRDM1_CBFA2T3',
 'PRDM1_NegCtrl0__PRDM1_NegCtrl0',
 'PRTG_NegCtrl0__PRTG_NegCtrl0',
 'PTPN12_NegCtrl0__PTPN12_NegCtrl0',
 'PTPN12_OSR2__PTPN12_OSR2',
 'PTPN12_PTPN9__PTPN12_PTPN9',
 'PTPN12_SNAI1__PTPN12_SNAI1',
 'PTPN12_UBASH3A__PTPN12_UBASH3A',
 'PTPN12_ZBTB25__PTPN12_ZBTB25',
 'PTPN13_NegCtrl0__PTPN13_NegCtrl0',
 'PTPN1_NegCtrl0__PTPN1_NegCtrl0',
 'PTPN9_NegCtrl0__PTPN9_NegCtrl0',
 'RHOXF2_NegCtrl0__RHOXF2_NegCtrl0',
 'RHOXF2_SET__RHOXF2_SET',
 'RHOXF2_ZBTB25__RHOXF2_ZBTB25',
 'RREB1_NegCtrl0__RREB1_NegCtrl0',
 'RUNX1T1_NegCtrl0__RUNX1T1_NegCtrl0',
 'S1PR2_NegCtrl0__S1PR2_NegCtrl0',
 'SAMD1_NegCtrl0__SAMD1_NegCtrl0',
 'SAMD1_PTPN12__SAMD1_PTPN12',
 'SAMD1_TGFBR2__SAMD1_TGFBR2',
 'SAMD1_UBASH3B__SAMD1_UBASH3B',
 'SAMD1_ZBTB1__SAMD1_ZBTB1',
 'SET_CEBPE__SET_CEBPE',
 'SET_KLF1__SET_KLF1',
 'SET_NegCtrl0__SET_NegCtrl0',
 'SGK1_NegCtrl0__SGK1_NegCtrl0',
 'SGK1_S1PR2__SGK1_S1PR2',
 'SGK1_TBX2__SGK1_TBX2',
 'SGK1_TBX3__SGK1_TBX3',
 'SLC4A1_NegCtrl0__SLC4A1_NegCtrl0',
 'SLC6A9_NegCtrl0__SLC6A9_NegCtrl0',
 'SNAI1_DLX2__SNAI1_DLX2',
 'SNAI1_NegCtrl0__SNAI1_NegCtrl0',
 'SNAI1_UBASH3B__SNAI1_UBASH3B',
 'SPI1_NegCtrl0__SPI1_NegCtrl0',
 'STIL_NegCtrl0__STIL_NegCtrl0',
 'TBX2_NegCtrl0__TBX2_NegCtrl0',
 'TBX3_NegCtrl0__TBX3_NegCtrl0',
 'TBX3_TBX2__TBX3_TBX2',
 'TGFBR2_C19orf26__TGFBR2_C19orf26',
 'TGFBR2_ETS2__TGFBR2_ETS2',
 'TGFBR2_IGDCC3__TGFBR2_IGDCC3_1',
 'TGFBR2_IGDCC3__TGFBR2_IGDCC3_2',
 'TGFBR2_NegCtrl0__TGFBR2_NegCtrl0',
 'TGFBR2_PRTG__TGFBR2_PRTG',
 'TMSB4X_BAK1__TMSB4X_BAK1',
 'TMSB4X_NegCtrl0__TMSB4X_NegCtrl0',
 'TP73_NegCtrl0__TP73_NegCtrl0',
 'TSC22D1_NegCtrl0__TSC22D1_NegCtrl0',
 'UBASH3A_NegCtrl0__UBASH3A_NegCtrl0',
 'UBASH3B_CNN1__UBASH3B_CNN1',
 'UBASH3B_NegCtrl0__UBASH3B_NegCtrl0',
 'UBASH3B_OSR2__UBASH3B_OSR2',
 'UBASH3B_PTPN12__UBASH3B_PTPN12',
 'UBASH3B_PTPN9__UBASH3B_PTPN9',
 'UBASH3B_UBASH3A__UBASH3B_UBASH3A',
 'UBASH3B_ZBTB25__UBASH3B_ZBTB25',
 'ZBTB10_DLX2__ZBTB10_DLX2',
 'ZBTB10_ELMSAN1__ZBTB10_ELMSAN1',
 'ZBTB10_NegCtrl0__ZBTB10_NegCtrl0_1',
 'ZBTB10_NegCtrl0__ZBTB10_NegCtrl0_2',
 'ZBTB10_PTPN12__ZBTB10_PTPN12',
 'ZBTB10_SNAI1__ZBTB10_SNAI1',
 'ZBTB1_NegCtrl0__ZBTB1_NegCtrl0',
 'ZBTB25_NegCtrl0__ZBTB25_NegCtrl0',
 'ZC3HAV1_CEBPA__ZC3HAV1_CEBPA',
 'ZC3HAV1_CEBPE__ZC3HAV1_CEBPE',
 'ZC3HAV1_HOXC13__ZC3HAV1_HOXC13',
 'ZC3HAV1_NegCtrl0__ZC3HAV1_NegCtrl0',
 'ZNF318_FOXL2__ZNF318_FOXL2',
 'ZNF318_NegCtrl0__ZNF318_NegCtrl0'}
--------------------------------------------------

### Rename `guide_identity` to `perturbation_name`

In [6]:
cur_data.rename_columns(slot = 'obs', name_dict = {'guide_identity': 'perturbation_name'})

Renamed columns in adata.obs: {'guide_identity': 'perturbation_name'}

In [7]:
# split perturbation_name to keep the first part only
cur_data.adata.obs['perturbation_name'] = cur_data.adata.obs['perturbation_name'].str.split('__').str[0]
cur_data.adata.obs[['perturbation_name']]

                     perturbation_name
index
AAACCTGAGAAGAAGC-1   NegCtrl0_NegCtrl0
AAACCTGAGGCATGTG-1    TSC22D1_NegCtrl0
AAACCTGAGGCCCTTG-1         KLF1_MAP2K6
AAACCTGCACGAAGCA-1  NegCtrl10_NegCtrl0
AAACCTGCAGACGTAG-1       CEBPE_RUNX1T1
...                                ...
TTTGTCATCAGTACGT-8      FOXA3_NegCtrl0
TTTGTCATCCACTCCA-8      CELF2_NegCtrl0
TTTGTCATCCCAACGG-8     BCORL1_NegCtrl0
TTTGTCATCCTCCTAG-8       ZBTB10_PTPN12
TTTGTCATCTGGCGAC-8     MAP4K3_NegCtrl0

[111445 rows x 1 columns]

### Drop all columns starting with `guide_`

In [8]:
# drop all "guide_" columns
cur_data.adata.obs = cur_data.adata.obs.drop(list(cur_data.adata.obs.filter(regex='guide_', axis=1)), axis = 1)

In [9]:
cur_data.adata.obs

,perturbation_name,read_count,UMI_count,coverage,gemgroup,good_coverage,number_of_cells
index,,,,,,,
AAACCTGAGAAGAAGC-1,NegCtrl0_NegCtrl0,1252,67,18.686567,1,True,2
AAACCTGAGGCATGTG-1,TSC22D1_NegCtrl0,2151,104,20.682692,1,True,1
AAACCTGAGGCCCTTG-1,KLF1_MAP2K6,1037,59,17.576271,1,True,1
AAACCTGCACGAAGCA-1,NegCtrl10_NegCtrl0,958,39,24.564103,1,True,1
AAACCTGCAGACGTAG-1,CEBPE_RUNX1T1,244,14,17.428571,1,True,1
...,...,...,...,...,...,...,...
TTTGTCATCAGTACGT-8,FOXA3_NegCtrl0,2068,95,21.768421,8,True,1
TTTGTCATCCACTCCA-8,CELF2_NegCtrl0,829,33,25.121212,8,True,1
TTTGTCATCCCAACGG-8,BCORL1_NegCtrl0,136,9,15.111111,8,True,1
TTTGTCATCCTCCTAG-8,ZBTB10_PTPN12,1254,59,21.254237,8,True,3
TTTGTCATCTGGCGAC-8,MAP4K3_NegCtrl0,1226,59,20.779661,8,True,1

### Add guide RNA information

In [10]:
# download the guide RNA spreadsheet
download_file(
    url="http://www.science.org/doi/suppl/10.1126/science.aax4438/suppl_file/aax4438_tables2.xlsx",
    dest_path="../supplementary/norman_2019_guide_info.xlsx"
)

# read in the guide RNA spreadsheet
# guides for the K562 essential day 6 library are in "TabB_K562_day6_library"
guide_info_df = pd.read_excel("../supplementary/norman_2019_guide_info.xlsx", sheet_name="Perturbseq_sgRNA_info")

# create perturbation_name column in guide_info_df
guide_info_df['perturbation_name'] = guide_info_df['gene_A'] + '_' + guide_info_df['gene_B']
# check that all perturbation names in cur_data are in guide_info_df
print(f"All perturbation names in cur_data are in guide_info_df: {cur_data.adata.obs['perturbation_name'].isin(guide_info_df['perturbation_name']).all()}")
# create guide_sequence column in guide_info_df
guide_info_df['guide_sequence'] = guide_info_df['protospacer_sequence_A'] + '|' + guide_info_df['protospacer_sequence_B']
# subset for necessary columns
guide_info_df = guide_info_df[['perturbation_name', 'guide_sequence']]
# merge cur_data.adata.obs with guide_info_df on perturbation_name
cur_data.adata.obs = cur_data.adata.obs.merge(guide_info_df, on='perturbation_name', how='left')
# # check that there are no missing guide sequences
print(f"Number of missing guide sequences: {cur_data.adata.obs['guide_sequence'].isna().sum()}")

File ../supplementary/norman_2019_guide_info.xlsx already exists. Skipping download.
All perturbation names in cur_data are in guide_info_df: True
Number of missing guide sequences: 0

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Standardise perturbation targets

In [11]:
cur_data.adata.obs['target'] = cur_data.adata.obs['perturbation_name'].str.replace('_', '|').str.replace(r'NegCtrl\d+', 'control_nontargeting', regex=True)
cur_data.adata.obs[['target']]

                                           target
0       control_nontargeting|control_nontargeting
1                    TSC22D1|control_nontargeting
2                                     KLF1|MAP2K6
3       control_nontargeting|control_nontargeting
4                                   CEBPE|RUNX1T1
...                                           ...
111440                 FOXA3|control_nontargeting
111441                 CELF2|control_nontargeting
111442                BCORL1|control_nontargeting
111443                              ZBTB10|PTPN12
111444                MAP4K3|control_nontargeting

[111445 rows x 1 columns]

In [12]:
cur_data.standardize_genes(
    slot='obs',
    input_column='target',
    input_column_type='gene_symbol',
    multiple_entries=True,
    multiple_entries_sep='|'
)

Mapping gene symbols: 100%|████████████████████████████████████| 106/106 [00:00<00:00, 14293.40it/s]

--------------------------------------------------
Successfully mapped 106 out of 106 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: []
--------------------------------------------------
Collapsed column positional_index using separator |

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Add `perturbed_target_number` column

In [13]:
cur_data.count_entries(
    slot='obs',
    input_column='perturbed_target_symbol',
    count_column_name='perturbed_target_number',
    sep='|'
)

Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [14]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

### Assign replicates

In [15]:
cur_data.adata.obs = cur_data.adata.obs.rename(columns={'gemgroup': 'technical_replicate'})

In [16]:
cur_data.adata.obs

,number_of_cells,technical_replicate,read_count,perturbation_name,UMI_count,target,good_coverage,coverage,guide_sequence,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding
index,,,,,,,,,,,,,,,,,
0,2,1,1252,NegCtrl0_NegCtrl0,67,control_nontargeting|control_nontargeting,True,18.686567,GTCGCGCCCGCTCCAGGGAC|GTCGCGCCCGCTCCAGGGAC,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,0|0,1,0
1,1,1,2151,TSC22D1_NegCtrl0,104,TSC22D1|control_nontargeting,True,20.682692,GTCCCCGGAGCTGTGTCCCG|GTCGCGCCCGCTCCAGGGAC,ENSG00000102804|control_nontargeting,TSC22D1|control_nontargeting,protein_coding|control_nontargeting,chr13:44432143-44577316;-1|control_nontargeting,13|control_nontargeting,1|1,2,0
2,1,1,1037,KLF1_MAP2K6,59,KLF1|MAP2K6,True,17.576271,GGGGCTGTGGAGCCTCAATC|GGTTCTCCGGCGGAGTCCAC,ENSG00000105610|ENSG00000108984,KLF1|MAP2K6,protein_coding|protein_coding,chr19:12884422-12887201;-1|chr17:69414683-6955...,19|17,2|2,2,0
3,1,1,958,NegCtrl10_NegCtrl0,39,control_nontargeting|control_nontargeting,True,24.564103,GCTCGCGTCTGCCGCCAGAC|GTCGCGCCCGCTCCAGGGAC,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,3|3,1,0
4,1,1,244,CEBPE_RUNX1T1,14,CEBPE|RUNX1T1,True,17.428571,GCCCCTCAAAAAACAAACCC|GCGCCGGAGCCGGCCTGATG,ENSG00000092067|ENSG00000079102,CEBPE|RUNX1T1,protein_coding|protein_coding,chr14:23117036-23120256;-1|chr8:91954972-92103...,14|8,4|4,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111440,1,8,2068,FOXA3_NegCtrl0,95,FOXA3|control_nontargeting,True,21.768421,GAGACAGACCTCAGGCGCCG|GTCGCGCCCGCTCCAGGGAC,ENSG00000170608|control_nontargeting,FOXA3|control_nontargeting,protein_coding|control_nontargeting,chr19:45863989-45873798;1|control_nontargeting,19|control_nontargeting,111440|111440,2,0
111441,1,8,829,CELF2_NegCtrl0,33,CELF2|control_nontargeting,True,25.121212,GCTCCGCCCCGCGGGGACAC|GTCGCGCCCGCTCCAGGGAC,ENSG00000048740|control_nontargeting,CELF2|control_nontargeting,protein_coding|control_nontargeting,chr10:10798397-11336675;1|control_nontargeting,10|control_nontargeting,111441|111441,2,0
111442,1,8,136,BCORL1_NegCtrl0,9,BCORL1|control_nontargeting,True,15.111111,GGATCGCTGAGAGGACCGAG|GTCGCGCCCGCTCCAGGGAC,ENSG00000085185|control_nontargeting,BCORL1|control_nontargeting,protein_coding|control_nontargeting,chrX:129981107-130058071;1|control_nontargeting,X|control_nontargeting,111442|111442,2,0
111443,3,8,1254,ZBTB10_PTPN12,59,ZBTB10|PTPN12,True,21.254237,Ggcgccaggggaccgggaaa|GGCTAGCTGTGTTCCTGAgg,ENSG00000205189|ENSG00000127947,ZBTB10|PTPN12,protein_coding|protein_coding,chr8:80485596-80526265;1|chr7:77537295-77640072;1,8|7,111443|111443,2,0
111444,1,8,1226,MAP4K3_NegCtrl0,59,MAP4K3|control_nontargeting,True,20.779661,GCGGGTCCGCAGAAAAGCCG|GTCGCGCCCGCTCCAGGGAC,ENSG00000011566|control_nontargeting,MAP4K3|control_nontargeting,protein_coding|control_nontargeting,chr2:39249266-39437324;-1|control_nontargeting,2|control_nontargeting,111444|111444,2,0

### Add metadata

In [17]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        #----- dataset -----#
        "dataset_id": cur_data.dataset_id,
        #----- sample -----#
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        #----- perturbation type -----#
        "perturbation_type_label": "CRISPRa",
        "perturbation_type_id": None,
        #----- data modality -----#
        "data_modality": "Perturb-seq", # different from "method_name_label"; more general term - choice of CRISPR, MAVE and Perturb-seq
        #----- significance -----#
        "significant": None,
        "significance_criteria": None,
        #----- score interpretation -----#
        "score_interpretation": None,
        #----- treatment -----#
        "treatment_label": None,
        "treatment_id": None,
        #----- replicate -----#
        # "technical_replicate": None,
        "biological_replicate": None,
        #----- model system -----#
        "model_system_label": "cell_line",
        "model_system_id": None,
        #----- tissue -----#
        "tissue": "blood",
        #----- cell line -----#
        "cell_line_label": "K 562 cell",
        "cell_line_id": None,
        #----- cell type -----#
        "cell_type_label": "lymphoblast",
        "cell_type_id": None,
        #----- disease -----#
        "disease_label": "chronic myelogenous leukemia, BCR-ABL1 positive",
        "disease_id": None,
        #----- timepoint -----#
        "timepoint": "P7DT0H0M0S",
        #----- species -----#
        "species": "Homo sapiens",
        #----- sex -----#
        "sex_label": "female",
        "sex_id": None,
        #----- developmental stage -----#
        "developmental_stage_label": "adult",
        "developmental_stage_id": None,
        #----- study metadata -----#
        "study_title": "Exploring genetic interaction manifolds constructed from rich single-cell phenotypes",
        "study_uri": "https://doi.org/10.1126/science.aax4438",
        "study_year": 2019,
        #----- authors -----#
        "first_author": "Thomas M. Norman",
        "last_author": "Jonathan S. Weissman",
        #----- experiment metadata -----#
        "experiment_title": "Perturb-seq CRISPRa of K562 cells to explore genetic interaction manifolds",
        "experiment_summary": """
            K562 cells were engineered by lentiviral transduction of dox-inducible CRISPRa SunTag system. The sgRNA library consisting of 295 dual sgRNA vectors was packaged into lentiviral particles, spinfected into K562 cells. Cells were grown until day 7, at which point they were harvested, processed using Chromium Single Cell 3-prime Gel Beads v2 kit and sequenced on an Illumina NovaSeq 6000.
        """,
        #----- number of perturbed targets/samples -----#
        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],
        #----- library generation type -----#
        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",
        #----- library generation method -----#
        "library_generation_method_id": "EFO:0022898",
        "library_generation_method_label": "dCas9-Suntag",
        #----- enzyme and library delivery method -----#
        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "lentivirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",
        #----- enzyme and library integration state -----#
        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",
        #----- enzyme and library expression control -----#
        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "inducible transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",
        #----- library name and URI and manufacturer -----#
        "library_name": "custom",
        "library_uri": None,
        "library_manufacturer": "Weissman lab",
        #----- library format -----#
        "library_format_id": None,
        "library_format_label": "pooled",
        #----- library scope -----#
        "library_scope_id": None,
        "library_scope_label": "focused",
        #----- library perturbation type -----#
        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "activation",
        #----- library additional metadata -----#
        "library_lentiviral_generation": "3",
        "library_grnas_per_target": "1",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()), # for CRISPR/Perturb-seq
        "library_total_variants": None, # for MAVE
        #----- readout dimensionality -----#
        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",
        #---- readout type -----#
        "readout_type_id": None,
        "readout_type_label": "transcriptomic",
        #----- readout technology -----#
        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",
        #----- method -----#
        "method_name_id": None,
        "method_name_label": "Perturb-seq", # different from "data_modality"; more specific term - specific name of the technique
        "method_uri": None,
        #----- sequencing library kit -----#
        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "10x Genomics Single Cell 3-prime v2",
        #----- sequencing platform -----#
        "sequencing_platform_id": None,
        "sequencing_platform_label": "Illumina NovaSeq 6000",
        #----- sequencing strategy -----#
        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",
        #----- software used for counts-----#
        "software_counts_id": None,
        "software_counts_label": "CellRanger",
        #----- software used for analysis -----#
        "software_analysis_id": None,
        "software_analysis_label": "custom",
        #----- reference genome -----#
        "reference_genome_id": None,
        "reference_genome_label": "GRCh38",
        #----- license -----#
        "license_label": "free to use license",
        "license_id": "SWO:1000061",
        #----- external datasets -----#
        "associated_datasets": json.dumps([
            {
                "dataset_accession": "GSE133344",
                "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE133344",
                "dataset_description": "Raw counts; matrix.mtx, features.tsv, barcodes.tsv",
                "dataset_file_name": "GSE278572_*.*",
            },
            {
                "dataset_accession": "norman_2019_raw.h5ad",
                "dataset_uri": "https://exampledata.scverse.org/pertpy/norman_2019_raw.h5ad",
                "dataset_description": "Raw counts - .h5ad file from pertpy",
                "dataset_file_name": "norman_2019_raw.h5ad",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column treatment_label added to adata.obs
Column treatment_id added to adata.obs
Column biological_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_line_id added to adata.obs
Column cell_type_label added to adata.obs
Column cell_type_id added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_manufacturer added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

In [18]:
cur_data.adata.obs

,number_of_cells,technical_replicate,read_count,perturbation_name,UMI_count,target,good_coverage,coverage,guide_sequence,perturbed_target_ensg,...,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,reference_genome_id,reference_genome_label,license_label,license_id,associated_datasets
index,,,,,,,,,,,,,,,,,,,,,
0,2,1,1252,NegCtrl0_NegCtrl0,67,control_nontargeting|control_nontargeting,True,18.686567,GTCGCGCCCGCTCCAGGGAC|GTCGCGCCCGCTCCAGGGAC,control_nontargeting|control_nontargeting,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
1,1,1,2151,TSC22D1_NegCtrl0,104,TSC22D1|control_nontargeting,True,20.682692,GTCCCCGGAGCTGTGTCCCG|GTCGCGCCCGCTCCAGGGAC,ENSG00000102804|control_nontargeting,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
2,1,1,1037,KLF1_MAP2K6,59,KLF1|MAP2K6,True,17.576271,GGGGCTGTGGAGCCTCAATC|GGTTCTCCGGCGGAGTCCAC,ENSG00000105610|ENSG00000108984,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
3,1,1,958,NegCtrl10_NegCtrl0,39,control_nontargeting|control_nontargeting,True,24.564103,GCTCGCGTCTGCCGCCAGAC|GTCGCGCCCGCTCCAGGGAC,control_nontargeting|control_nontargeting,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
4,1,1,244,CEBPE_RUNX1T1,14,CEBPE|RUNX1T1,True,17.428571,GCCCCTCAAAAAACAAACCC|GCGCCGGAGCCGGCCTGATG,ENSG00000092067|ENSG00000079102,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111440,1,8,2068,FOXA3_NegCtrl0,95,FOXA3|control_nontargeting,True,21.768421,GAGACAGACCTCAGGCGCCG|GTCGCGCCCGCTCCAGGGAC,ENSG00000170608|control_nontargeting,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
111441,1,8,829,CELF2_NegCtrl0,33,CELF2|control_nontargeting,True,25.121212,GCTCCGCCCCGCGGGGACAC|GTCGCGCCCGCTCCAGGGAC,ENSG00000048740|control_nontargeting,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
111442,1,8,136,BCORL1_NegCtrl0,9,BCORL1|control_nontargeting,True,15.111111,GGATCGCTGAGAGGACCGAG|GTCGCGCCCGCTCCAGGGAC,ENSG00000085185|control_nontargeting,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
111443,3,8,1254,ZBTB10_PTPN12,59,ZBTB10|PTPN12,True,21.254237,Ggcgccaggggaccgggaaa|GGCTAGCTGTGTTCCTGAgg,ENSG00000205189|ENSG00000127947,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."
111444,1,8,1226,MAP4K3_NegCtrl0,59,MAP4K3|control_nontargeting,True,20.779661,GCGGGTCCGCAGAAAAGCCG|GTCGCGCCCGCTCCAGGGAC,ENSG00000011566|control_nontargeting,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,free to use license,SWO:1000061,"[{""dataset_accession"": ""GSE133344"", ""dataset_u..."

### Curate tissue information

In [19]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower     ontology_id
0        blood              blood      blood  UBERON:0000178
--------------------------------------------------

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [20]:
cur_data.standardize_ontology(
    input_column='cell_type_label',
    column_type='term_name',
    ontology_type='cell_type',
    overwrite=True
)

Mapped 1 cell_type ontology terms from `cell_type_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower   name_lower ontology_id
0  lymphoblast        lymphoblast  lymphoblast  CL:0017005
--------------------------------------------------
Overwriting column cell_type_label in adata.obs
Overwriting column cell_type_id in adata.obs

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell line information

In [21]:
cur_data.standardize_ontology(
    input_column='cell_line_label',
    column_type='term_name',
    ontology_type='cell_line',
    overwrite=True
)

Mapped 1 cell_line ontology terms from `cell_line_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower  name_lower  ontology_id
0   K 562 cell         k 562 cell  k 562 cell  CLO:0007050
--------------------------------------------------
Overwriting column cell_line_label in adata.obs
Overwriting column cell_line_id in adata.obs

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [22]:
cur_data.standardize_ontology(
    input_column='disease_label',
    column_type='term_name',
    ontology_type='disease',
    overwrite=True
)

Mapped 1 disease ontology terms from `disease_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
                                      input_column  \
0  chronic myelogenous leukemia, BCR-ABL1 positive

                                input_column_lower  \
0  chronic myelogenous leukemia, bcr-abl1 positive

                                        name_lower    ontology_id
0  chronic myelogenous leukemia, bcr-abl1 positive  MONDO:0011996
--------------------------------------------------
Overwriting column disease_label in adata.obs
Overwriting column disease_id in adata.obs

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Match schema column order

In [23]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [24]:
cur_data.validate_data(slot='obs', verbose=True)

2026-01-15 14:39:31,295 INFO curation_tools.curation_tools: adata.obs is valid according to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,norman_2019_raw,1,Perturb-seq,<NA>,<NA>,NegCtrl0_NegCtrl0,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,0,1,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
1,norman_2019_raw,2,Perturb-seq,<NA>,<NA>,TSC22D1_NegCtrl0,chr13:44432143-44577316;-1|control_nontargeting,13|control_nontargeting,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
2,norman_2019_raw,3,Perturb-seq,<NA>,<NA>,KLF1_MAP2K6,chr19:12884422-12887201;-1|chr17:69414683-6955...,19|17,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
3,norman_2019_raw,4,Perturb-seq,<NA>,<NA>,NegCtrl10_NegCtrl0,control_nontargeting|control_nontargeting,control_nontargeting|control_nontargeting,0,1,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
4,norman_2019_raw,5,Perturb-seq,<NA>,<NA>,CEBPE_RUNX1T1,chr14:23117036-23120256;-1|chr8:91954972-92103...,14|8,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111440,norman_2019_raw,111441,Perturb-seq,<NA>,<NA>,FOXA3_NegCtrl0,chr19:45863989-45873798;1|control_nontargeting,19|control_nontargeting,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
111441,norman_2019_raw,111442,Perturb-seq,<NA>,<NA>,CELF2_NegCtrl0,chr10:10798397-11336675;1|control_nontargeting,10|control_nontargeting,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
111442,norman_2019_raw,111443,Perturb-seq,<NA>,<NA>,BCORL1_NegCtrl0,chrX:129981107-130058071;1|control_nontargeting,X|control_nontargeting,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
111443,norman_2019_raw,111444,Perturb-seq,<NA>,<NA>,ZBTB10_PTPN12,chr8:80485596-80526265;1|chr7:77537295-77640072;1,8|7,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061
111444,norman_2019_raw,111445,Perturb-seq,<NA>,<NA>,MAP4K3_NegCtrl0,chr2:39249266-39437324;-1|control_nontargeting,2|control_nontargeting,0,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE133344"", ""dataset_u...",free to use license,SWO:1000061

# VAR slot curation

### Standardise genes

In [25]:
cur_data.show_var()

Variable data:
DataFrame shape: (33694, 1)
--------------------------------------------------
                 gene_symbols
index
ENSG00000243485  RP11-34P13.3
ENSG00000237613       FAM138A
ENSG00000186092         OR4F5
ENSG00000238009  RP11-34P13.7
ENSG00000239945  RP11-34P13.8
...                       ...
ENSG00000277856    AC233755.2
ENSG00000275063    AC233755.1
ENSG00000271254    AC240274.1
ENSG00000277475    AC213203.1
ENSG00000268674       FAM231B

[33694 rows x 1 columns]
--------------------------------------------------

In [26]:
cur_data.create_columns(
    slot = 'var',
    col_dict={'gene_ensembl_id': cur_data.adata.var.index},
    overwrite=True
)

Column gene_ensembl_id added to adata.var

In [27]:
cur_data.standardize_genes(
    slot="var",
    input_column="gene_ensembl_id",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

Missing Ensembl IDs: ['ENSG00000277856', 'ENSG00000251218', 'ENSG00000272354', 'ENSG00000266958', 'ENSG00000276250', 'ENSG00000182912', 'ENSG00000279510', 'ENSG00000266450', 'ENSG00000228135', 'ENSG00000280006', 'ENSG00000262668', 'ENSG00000263388', 'ENSG00000262601', 'ENSG00000260983', 'ENSG00000267517', 'ENSG00000249731', 'ENSG00000280329', 'ENSG00000236856', 'ENSG00000279210', 'ENSG00000255863', 'ENSG00000249069', 'ENSG00000259279', 'ENSG00000229611', 'ENSG00000279435', 'ENSG00000282955', 'ENSG00000225393', 'ENSG00000279765', 'ENSG00000256923', 'ENSG00000270168', 'ENSG00000281844', 'ENSG00000237658', 'ENSG00000272040', 'ENSG00000204092', 'ENSG00000226240', 'ENSG00000276256', 'ENSG00000231217', 'ENSG00000279282', 'ENSG00000224481', 'ENSG00000261550', 'ENSG00000277423', 'ENSG00000229191', 'ENSG00000263464', 'ENSG00000253929', 'ENSG00000278566', 'ENSG00000213863', 'ENSG00000279335', 'ENSG00000259752', 'ENSG00000277726', 'ENSG00000240224', 'ENSG00000229403', 'ENSG00000225554', 'ENSG00000230699', 'ENSG00000239446', 'ENSG00000274902', 'ENSG00000234871', 'ENSG00000237857', 'ENSG00000279916', 'ENSG00000228214', 'ENSG00000249166', 'ENSG00000254364', 'ENSG00000250410', 'ENSG00000186354', 'ENSG00000281042', 'ENSG00000274068', 'ENSG00000258088', 'ENSG00000261622', 'ENSG00000276397', 'ENSG00000255507', 'ENSG00000255823', 'ENSG00000255090', 'ENSG00000267667', 'ENSG00000244214', 'ENSG00000272922', 'ENSG00000232636', 'ENSG00000130723', 'ENSG00000228421', 'ENSG00000271788', 'ENSG00000250101', 'ENSG00000253931', 'ENSG00000280230', 'ENSG00000273547', 'ENSG00000273138', 'ENSG00000258386', 'ENSG00000235047', 'ENSG00000250237', 'ENSG00000272869', 'ENSG00000234283', 'ENSG00000280041', 'ENSG00000258345', 'ENSG00000257654', 'ENSG00000224050', 'ENSG00000232532', 'ENSG00000263688', 'ENSG00000270058', 'ENSG00000251628', 'ENSG00000234248', 'ENSG00000281656', 'ENSG00000238042', 'ENSG00000253400', 'ENSG00000256732', 'ENSG00000279921', 'ENSG00000254821', 'ENSG00000260141', 'ENSG00000255015', 'ENSG00000264421', 'ENSG00000230998', 'ENSG00000227683', 'ENSG00000267684', 'ENSG00000242349', 'ENSG00000266176', 'ENSG00000260071', 'ENSG00000259703', 'ENSG00000257183', 'ENSG00000261039', 'ENSG00000259664', 'ENSG00000267243', 'ENSG00000261720', 'ENSG00000280050', 'ENSG00000223821', 'ENSG00000269549', 'ENSG00000204365', 'ENSG00000273890', 'ENSG00000237764', 'ENSG00000233509', 'ENSG00000249008', 'ENSG00000268810', 'ENSG00000278882', 'ENSG00000278084', 'ENSG00000271324', 'ENSG00000273771', 'ENSG00000249463', 'ENSG00000276631', 'ENSG00000249837', 'ENSG00000254140', 'ENSG00000228334', 'ENSG00000279911', 'ENSG00000254173', 'ENSG00000267316', 'ENSG00000259616', 'ENSG00000248646', 'ENSG00000256271', 'ENSG00000257640', 'ENSG00000234177', 'ENSG00000260052', 'ENSG00000259594', 'ENSG00000248942', 'ENSG00000258131', 'ENSG00000254199', 'ENSG00000280603', 'ENSG00000280403', 'ENSG00000226786', 'ENSG00000253859', 'ENSG00000213029', 'ENSG00000271751', 'ENSG00000273119', 'ENSG00000204187', 'ENSG00000215067', 'ENSG00000279654', 'ENSG00000250234', 'ENSG00000254010', 'ENSG00000273237', 'ENSG00000271734', 'ENSG00000231465', 'ENSG00000282863', 'ENSG00000282827', 'ENSG00000264067', 'ENSG00000255740', 'ENSG00000251331', 'ENSG00000279007', 'ENSG00000270750', 'ENSG00000279538', 'ENSG00000267697', 'ENSG00000235475', 'ENSG00000265264', 'ENSG00000260793', 'ENSG00000233818', 'ENSG00000236714', 'ENSG00000233776', 'ENSG00000282960', 'ENSG00000261797', 'ENSG00000223704', 'ENSG00000267070', 'ENSG00000233415', 'ENSG00000278272', 'ENSG00000258302', 'ENSG00000217258', 'ENSG00000261120', 'ENSG00000146521', 'ENSG00000253735', 'ENSG00000268439', 'ENSG00000264527', 'ENSG00000259450', 'ENSG00000262477', 'ENSG00000224441', 'ENSG00000281267', 'ENSG00000280473', 'ENSG00000281674', 'ENSG00000273370', 'ENSG00000271870', 'ENSG00000255767', 'ENSG00000278610', 'ENSG00000230177', 'ENSG00000263588', 'ENSG00000279018', 'ENSG00000228106', 'ENSG00000271792', 'ENSG00000281602', 'ENSG00000270067', 'ENSG00000260411', 'ENSG00000225932', 'ENSG00000224638', 'ENSG00000280260', 'ENSG00000268355', 'ENSG00000225742', 'ENSG00000267268', 'ENSG00000281523', 'ENSG00000244567', 'ENSG00000249684', 'ENSG00000259761', 'ENSG00000236082', 'ENSG00000205663', 'ENSG00000266490', 'ENSG00000241572', 'ENSG00000276269', 'ENSG00000174942', 'ENSG00000250046', 'ENSG00000272308', 'ENSG00000237845', 'ENSG00000255479', 'ENSG00000256321', 'ENSG00000257613', 'ENSG00000264072', 'ENSG00000225745', 'ENSG00000269946', 'ENSG00000197445', 'ENSG00000281167', 'ENSG00000237404', 'ENSG00000270147', 'ENSG00000274791', 'ENSG00000278029', 'ENSG00000276649', 'ENSG00000256927', 'ENSG00000272382', 'ENSG00000224884', 'ENSG00000267521', 'ENSG00000272444', 'ENSG00000250431', 'ENSG00000276278', 'ENSG00000224460', 'ENSG00000213240', 'ENSG00000261273', 'ENSG00000268615', 'ENSG00000205662', 'ENSG00000223633', 'ENSG00000253444', 'ENSG00000251085', 'ENSG00000229454', 'ENSG00000239587', 'ENSG00000267034', 'ENSG00000235795', 'ENSG00000240050', 'ENSG00000273009', 'ENSG00000231294', 'ENSG00000254100', 'ENSG00000231518', 'ENSG00000203812', 'ENSG00000257141', 'ENSG00000272440', 'ENSG00000275063', 'ENSG00000251379', 'ENSG00000280253', 'ENSG00000248478', 'ENSG00000255599', 'ENSG00000262222', 'ENSG00000223910', 'ENSG00000233029', 'ENSG00000228890', 'ENSG00000273765', 'ENSG00000257962', 'ENSG00000260929', 'ENSG00000198877', 'ENSG00000233143', 'ENSG00000186400', 'ENSG00000268568', 'ENSG00000258831', 'ENSG00000241636', 'ENSG00000154537', 'ENSG00000259166', 'ENSG00000229458', 'ENSG00000231599', 'ENSG00000279850', 'ENSG00000251044', 'ENSG00000278849', 'ENSG00000272030', 'ENSG00000269926', 'ENSG00000276075', 'ENSG00000266601', 'ENSG00000272070', 'ENSG00000244650', 'ENSG00000257156', 'ENSG00000275175', 'ENSG00000226155', 'ENSG00000277400', 'ENSG00000258407', 'ENSG00000251041', 'ENSG00000239674', 'ENSG00000235491', 'ENSG00000261833', 'ENSG00000239462', 'ENSG00000222022', 'ENSG00000267045', 'ENSG00000181689', 'ENSG00000258265', 'ENSG00000281028', 'ENSG00000235884', 'ENSG00000283003', 'ENSG00000271970', 'ENSG00000250889', 'ENSG00000254731', 'ENSG00000269916', 'ENSG00000130201', 'ENSG00000271259', 'ENSG00000257603', 'ENSG00000273301', 'ENSG00000236760', 'ENSG00000258473', 'ENSG00000280240', 'ENSG00000232749', 'ENSG00000244063', 'ENSG00000272468', 'ENSG00000214733', 'ENSG00000203520', 'ENSG00000239353', 'ENSG00000267115', 'ENSG00000254757', 'ENSG00000242687', 'ENSG00000272299', 'ENSG00000227869', 'ENSG00000250400', 'ENSG00000277669', 'ENSG00000259264', 'ENSG00000272953', 'ENSG00000204293', 'ENSG00000262395', 'ENSG00000224758', 'ENSG00000249265', 'ENSG00000267105', 'ENSG00000259957', 'ENSG00000236938', 'ENSG00000233408', 'ENSG00000257226', 'ENSG00000256739', 'ENSG00000259939', 'ENSG00000253774', 'ENSG00000256694', 'ENSG00000244382', 'ENSG00000264263', 'ENSG00000255778', 'ENSG00000280221', 'ENSG00000226078', 'ENSG00000261470', 'ENSG00000228951', 'ENSG00000272250', 'ENSG00000234166', 'ENSG00000259834', 'ENSG00000254744', 'ENSG00000224247', 'ENSG00000204398', 'ENSG00000227363', 'ENSG00000260030', 'ENSG00000267787', 'ENSG00000258280', 'ENSG00000231842', 'ENSG00000272301', 'ENSG00000270604', 'ENSG00000173088', 'ENSG00000259998', 'ENSG00000258844', 'ENSG00000248371', 'ENSG00000256618', 'ENSG00000233342', 'ENSG00000283027', 'ENSG00000239498', 'ENSG00000279037', 'ENSG00000263931', 'ENSG00000261737', 'ENSG00000169807', 'ENSG00000196936', 'ENSG00000273389', 'ENSG00000280178', 'ENSG00000204566', 'ENSG00000270195', 'ENSG00000259604', 'ENSG00000226785', 'ENSG00000232348', 'ENSG00000198657', 'ENSG00000231883', 'ENSG00000215271', 'ENSG00000253235', 'ENSG00000241770', 'ENSG00000251652', 'ENSG00000255243', 'ENSG00000224525', 'ENSG00000257715', 'ENSG00000279533', 'ENSG00000270189', 'ENSG00000256427', 'ENSG00000238009', 'ENSG00000275216', 'ENSG00000278883', 'ENSG00000280316', 'ENSG00000281508', 'ENSG00000243179', 'ENSG00000233864', 'ENSG00000263331', 'ENSG00000185087', 'ENSG00000282080', 'ENSG00000235665', 'ENSG00000230600', 'ENSG00000281937', 'ENSG00000261775', 'ENSG00000254143', 'ENSG00000254967', 'ENSG00000261295', 'ENSG00000279473', 'ENSG00000253805', 'ENSG00000248346', 'ENSG00000228561', 'ENSG00000265717', 'ENSG00000248991', 'ENSG00000261222', 'ENSG00000238266', 'ENSG00000269908', 'ENSG00000261317', 'ENSG00000262089', 'ENSG00000237899', 'ENSG00000241978', 'ENSG00000254927', 'ENSG00000244247', 'ENSG00000248294', 'ENSG00000279219', 'ENSG00000276790', 'ENSG00000259423', 'ENSG00000273923', 'ENSG00000280112', 'ENSG00000242375', 'ENSG00000230345', 'ENSG00000224235', 'ENSG00000133808', 'ENSG00000221961', 'ENSG00000271649', 'ENSG00000258081', 'ENSG00000251506', 'ENSG00000277203', 'ENSG00000279767', 'ENSG00000279941', 'ENSG00000279808', 'ENSG00000229245', 'ENSG00000236947', 'ENSG00000279745', 'ENSG00000271955', 'ENSG00000232018', 'ENSG00000281781', 'ENSG00000214970', 'ENSG00000279287', 'ENSG00000259407', 'ENSG00000259123', 'ENSG00000224621', 'ENSG00000226079', 'ENSG00000259820', 'ENSG00000221870', 'ENSG00000155640', 'ENSG00000227305', 'ENSG00000228614', 'ENSG00000254869', 'ENSG00000254180', 'ENSG00000273903', 'ENSG00000270672', 'ENSG00000233255', 'ENSG00000250156', 'ENSG00000263677', 'ENSG00000251144', 'ENSG00000273554', 'ENSG00000253139', 'ENSG00000268333', 'ENSG00000281079', 'ENSG00000279963', 'ENSG00000253256', 'ENSG00000260163', 'ENSG00000167945', 'ENSG00000272053', 'ENSG00000131484', 'ENSG00000234902', 'ENSG00000224342', 'ENSG00000272519', 'ENSG00000224850', 'ENSG00000279238', 'ENSG00000250158', 'ENSG00000260409', 'ENSG00000263470', 'ENSG00000238033', 'ENSG00000254018', 'ENSG00000267537', 'ENSG00000272049', 'ENSG00000250012', 'ENSG00000282896', 'ENSG00000281370', 'ENSG00000277196', 'ENSG00000231200', 'ENSG00000227925', 'ENSG00000244952', 'ENSG00000203386', 'ENSG00000236839', 'ENSG00000273019', 'ENSG00000255275', 'ENSG00000253248', 'ENSG00000281472', 'ENSG00000249734', 'ENSG00000229729', 'ENSG00000281676', 'ENSG00000259274', 'ENSG00000265556', 'ENSG00000283088', 'ENSG00000248828', 'ENSG00000234449', 'ENSG00000268220', 'ENSG00000280684', 'ENSG00000261013', 'ENSG00000176879', 'ENSG00000232461', 'ENSG00000280298', 'ENSG00000249708', 'ENSG00000237940', 'ENSG00000179979', 'ENSG00000269900', 'ENSG00000277427', 'ENSG00000273585', 'ENSG00000172381', 'ENSG00000267327', 'ENSG00000267654', 'ENSG00000225836', 'ENSG00000280767', 'ENSG00000213865', 'ENSG00000271417', 'ENSG00000279471', 'ENSG00000228478', 'ENSG00000280427', 'ENSG00000116957', 'ENSG00000253844', 'ENSG00000250446', 'ENSG00000251518', 'ENSG00000275542', 'ENSG00000233878', 'ENSG00000223379', 'ENSG00000266908', 'ENSG00000250418', 'ENSG00000178193', 'ENSG00000275636', 'ENSG00000271109', 'ENSG00000269873', 'ENSG00000269888', 'ENSG00000260100', 'ENSG00000268050', 'ENSG00000281889', 'ENSG00000249483', 'ENSG00000226598', 'ENSG00000261218', 'ENSG00000258137', 'ENSG00000280301', 'ENSG00000281137', 'ENSG00000279363', 'ENSG00000269028', 'ENSG00000267636', 'ENSG00000261666', 'ENSG00000278343', 'ENSG00000269936', 'ENSG00000253588', 'ENSG00000272923', 'ENSG00000261650', 'ENSG00000244693', 'ENSG00000234936', 'ENSG00000112096', 'ENSG00000246448', 'ENSG00000254281', 'ENSG00000244268', 'ENSG00000227603', 'ENSG00000228113', 'ENSG00000265780', 'ENSG00000228434', 'ENSG00000254814', 'ENSG00000273481', 'ENSG00000256922', 'ENSG00000204683', 'ENSG00000116883', 'ENSG00000274175', 'ENSG00000271904', 'ENSG00000234998', 'ENSG00000280151', 'ENSG00000256248', 'ENSG00000254039', 'ENSG00000253766', 'ENSG00000236392', 'ENSG00000259126', 'ENSG00000241043', 'ENSG00000237647', 'ENSG00000248311', 'ENSG00000269072', 'ENSG00000253737', 'ENSG00000239332', 'ENSG00000278938', 'ENSG00000272551', 'ENSG00000278878', 'ENSG00000280675', 'ENSG00000278951', 'ENSG00000272979', 'ENSG00000279576', 'ENSG00000234296', 'ENSG00000232754', 'ENSG00000258297', 'ENSG00000279892', 'ENSG00000254427', 'ENSG00000272486', 'ENSG00000254144', 'ENSG00000270114', 'ENSG00000280817', 'ENSG00000273576', 'ENSG00000262890', 'ENSG00000226377', 'ENSG00000276026', 'ENSG00000256790', 'ENSG00000261598', 'ENSG00000277010', 'ENSG00000256763', 'ENSG00000228651', 'ENSG00000275249', 'ENSG00000255318', 'ENSG00000236948', 'ENSG00000223675', 'ENSG00000241317', 'ENSG00000272009', 'ENSG00000234290', 'ENSG00000272482', 'ENSG00000280671', 'ENSG00000181013', 'ENSG00000259760', 'ENSG00000223929', 'ENSG00000272659', 'ENSG00000254223', 'ENSG00000279857', 'ENSG00000261757', 'ENSG00000273030', 'ENSG00000254761', 'ENSG00000274312', 'ENSG00000248486', 'ENSG00000278626', 'ENSG00000255125', 'ENSG00000271815', 'ENSG00000223811', 'ENSG00000243251', 'ENSG00000276814', 'ENSG00000237152', 'ENSG00000279126', 'ENSG00000253891', 'ENSG00000279448', 'ENSG00000239407', 'ENSG00000243350', 'ENSG00000176659', 'ENSG00000278451', 'ENSG00000280363', 'ENSG00000230372', 'ENSG00000226277', 'ENSG00000260837', 'ENSG00000276348', 'ENSG00000235337', 'ENSG00000279244', 'ENSG00000234141', 'ENSG00000227135', 'ENSG00000270030', 'ENSG00000278384', 'ENSG00000179082', 'ENSG00000280544', 'ENSG00000235245', 'ENSG00000268352', 'ENSG00000280273', 'ENSG00000225058', 'ENSG00000272579', 'ENSG00000235209', 'ENSG00000280410', 'ENSG00000258777', 'ENSG00000256287', 'ENSG00000258268', 'ENSG00000250481', 'ENSG00000229151', 'ENSG00000254671', 'ENSG00000259859', 'ENSG00000272827', 'ENSG00000236451', 'ENSG00000234405', 'ENSG00000235949', 'ENSG00000254420', 'ENSG00000228648', 'ENSG00000241520', 'ENSG00000256101', 'ENSG00000261672', 'ENSG00000170590', 'ENSG00000243944', 'ENSG00000279646', 'ENSG00000275294', 'ENSG00000226849', 'ENSG00000231566', 'ENSG00000233376', 'ENSG00000223797', 'ENSG00000260470', 'ENSG00000272085', 'ENSG00000254306', 'ENSG00000224739', 'ENSG00000272644', 'ENSG00000237975', 'ENSG00000254138', 'ENSG00000250078', 'ENSG00000267388', 'ENSG00000254267', 'ENSG00000260487', 'ENSG00000269966', 'ENSG00000260687', 'ENSG00000281920', 'ENSG00000267131', 'ENSG00000230641', 'ENSG00000266893', 'ENSG00000263574', 'ENSG00000272524', 'ENSG00000253842', 'ENSG00000258785', 'ENSG00000233895', 'ENSG00000274652', 'ENSG00000237954', 'ENSG00000258941', 'ENSG00000214732', 'ENSG00000273388', 'ENSG00000278939', 'ENSG00000243300', 'ENSG00000270105', 'ENSG00000231140', 'ENSG00000169789', 'ENSG00000260090', 'ENSG00000238358', 'ENSG00000248864', 'ENSG00000270033', 'ENSG00000122718', 'ENSG00000248787', 'ENSG00000235994', 'ENSG00000249988', 'ENSG00000228439', 'ENSG00000272316', 'ENSG00000280095', 'ENSG00000231255', 'ENSG00000278500', 'ENSG00000259298', 'ENSG00000255465', 'ENSG00000228704', 'ENSG00000176937', 'ENSG00000256050', 'ENSG00000279547', 'ENSG00000250060', 'ENSG00000275557', 'ENSG00000228798', 'ENSG00000232294', 'ENSG00000270265', 'ENSG00000229323', 'ENSG00000237513', 'ENSG00000276144', 'ENSG00000281359', 'ENSG00000225302', 'ENSG00000260869', 'ENSG00000250411', 'ENSG00000248461', 'ENSG00000228512', 'ENSG00000274367', 'ENSG00000198106', 'ENSG00000281527', 'ENSG00000275217', 'ENSG00000227192', 'ENSG00000273289', 'ENSG00000271840', 'ENSG00000188206', 'ENSG00000148362', 'ENSG00000171484', 'ENSG00000272146', 'ENSG00000257061', 'ENSG00000249203', 'ENSG00000267194', 'ENSG00000260769', 'ENSG00000229160', 'ENSG00000225261', 'ENSG00000225643', 'ENSG00000255394', 'ENSG00000259445', 'ENSG00000279909', 'ENSG00000236263', 'ENSG00000239216', 'ENSG00000272650', 'ENSG00000225790', 'ENSG00000235822', 'ENSG00000281584', 'ENSG00000281873', 'ENSG00000272593', 'ENSG00000270898', 'ENSG00000279132', 'ENSG00000257322', 'ENSG00000236740', 'ENSG00000234083', 'ENSG00000235578', 'ENSG00000272948', 'ENSG00000258838', 'ENSG00000260548', 'ENSG00000270188', 'ENSG00000168787', 'ENSG00000270016', 'ENSG00000253872', 'ENSG00000258414', 'ENSG00000270038', 'ENSG00000268187', 'ENSG00000273615', 'ENSG00000261353', 'ENSG00000264790', 'ENSG00000279546', 'ENSG00000268991', 'ENSG00000239265', 'ENSG00000282682', 'ENSG00000225916', 'ENSG00000279556', 'ENSG00000170803', 'ENSG00000236983', 'ENSG00000237262', 'ENSG00000166748', 'ENSG00000233005', 'ENSG00000263812', 'ENSG00000264334', 'ENSG00000278266', 'ENSG00000229628', 'ENSG00000281657', 'ENSG00000267399', 'ENSG00000229352', 'ENSG00000184682', 'ENSG00000248173', 'ENSG00000224204', 'ENSG00000269051', 'ENSG00000277192', 'ENSG00000253426', 'ENSG00000279109', 'ENSG00000275149', 'ENSG00000248265', 'ENSG00000236673', 'ENSG00000281881', 'ENSG00000281855', 'ENSG00000240401', 'ENSG00000237847', 'ENSG00000253381', 'ENSG00000272583', 'ENSG00000260759', 'ENSG00000282940', 'ENSG00000227468', 'ENSG00000237563', 'ENSG00000232692', 'ENSG00000237069', 'ENSG00000240440', 'ENSG00000271762', 'ENSG00000259587', 'ENSG00000280308', 'ENSG00000256150', 'ENSG00000262621', 'ENSG00000272564', 'ENSG00000242753', 'ENSG00000267037', 'ENSG00000246016', 'ENSG00000227920', 'ENSG00000234698', 'ENSG00000228452', 'ENSG00000279084', 'ENSG00000258480', 'ENSG00000265263', 'ENSG00000259747', 'ENSG00000262031', 'ENSG00000276760', 'ENSG00000254651', 'ENSG00000228139', 'ENSG00000269391', 'ENSG00000235215', 'ENSG00000249984', 'ENSG00000282440', 'ENSG00000237548', 'ENSG00000222030', 'ENSG00000228156', 'ENSG00000270160', 'ENSG00000267528', 'ENSG00000236129', 'ENSG00000280188', 'ENSG00000279988', 'ENSG00000277761', 'ENSG00000267643', 'ENSG00000280141', 'ENSG00000274444', 'ENSG00000261193', 'ENSG00000267081', 'ENSG00000258631', 'ENSG00000231616', 'ENSG00000262227', 'ENSG00000267896', 'ENSG00000275784', 'ENSG00000280226', 'ENSG00000229881', 'ENSG00000232324', 'ENSG00000256045', 'ENSG00000232784', 'ENSG00000223401', 'ENSG00000264660', 'ENSG00000263553', 'ENSG00000251454', 'ENSG00000236453', 'ENSG00000273496', 'ENSG00000266411', 'ENSG00000274792', 'ENSG00000254142', 'ENSG00000243993', 'ENSG00000233840', 'ENSG00000273466', 'ENSG00000278772', 'ENSG00000232505', 'ENSG00000228358', 'ENSG00000265943', 'ENSG00000275147', 'ENSG00000231838', 'ENSG00000279992', 'ENSG00000259855', 'ENSG00000282359', 'ENSG00000254290', 'ENSG00000232386', 'ENSG00000188069', 'ENSG00000240875', 'ENSG00000253988', 'ENSG00000248518', 'ENSG00000239467', 'ENSG00000273403', 'ENSG00000282887', 'ENSG00000187695', 'ENSG00000254836', 'ENSG00000274847', 'ENSG00000258582', 'ENSG00000275966', 'ENSG00000272367', 'ENSG00000253762', 'ENSG00000249604', 'ENSG00000262558', 'ENSG00000206129', 'ENSG00000277352', 'ENSG00000280264', 'ENSG00000270544', 'ENSG00000258927', 'ENSG00000281608', 'ENSG00000272389', 'ENSG00000241990', 'ENSG00000267581', 'ENSG00000253369', 'ENSG00000276345', 'ENSG00000236166', 'ENSG00000281227', 'ENSG00000261135', 'ENSG00000275179', 'ENSG00000244620', 'ENSG00000264078', 'ENSG00000255279', 'ENSG00000272732', 'ENSG00000277420', 'ENSG00000227116', 'ENSG00000268714', 'ENSG00000231212', 'ENSG00000279824', 'ENSG00000275142', 'ENSG00000255944', 'ENSG00000230649', 'ENSG00000261685', 'ENSG00000254462', 'ENSG00000249365', 'ENSG00000274877', 'ENSG00000235733', 'ENSG00000270019', 'ENSG00000271167', 'ENSG00000280561', 'ENSG00000273181', 'ENSG00000267058', 'ENSG00000274245', 'ENSG00000237585', 'ENSG00000277697', 'ENSG00000272981', 'ENSG00000274961', 'ENSG00000278514', 'ENSG00000265091', 'ENSG00000256725', 'ENSG00000226202', 'ENSG00000249269', 'ENSG00000278888', 'ENSG00000261159', 'ENSG00000277501', 'ENSG00000223469', 'ENSG00000272267', 'ENSG00000261350', 'ENSG00000224871', 'ENSG00000279380', 'ENSG00000236412', 'ENSG00000272102', 'ENSG00000247810', 'ENSG00000257879', 'ENSG00000231483', 'ENSG00000225085', 'ENSG00000250174', 'ENSG00000263316', 'ENSG00000251603', 'ENSG00000264299', 'ENSG00000271911', 'ENSG00000250415', 'ENSG00000259306', 'ENSG00000249184', 'ENSG00000069712', 'ENSG00000251024', 'ENSG00000232224', 'ENSG00000232698', 'ENSG00000163009', 'ENSG00000279515', 'ENSG00000255328', 'ENSG00000183791', 'ENSG00000257999', 'ENSG00000267047', 'ENSG00000224911', 'ENSG00000267012', 'ENSG00000276073', 'ENSG00000233438', 'ENSG00000257711', 'ENSG00000215159', 'ENSG00000263443', 'ENSG00000255124', 'ENSG00000279257', 'ENSG00000249122', 'ENSG00000278448', 'ENSG00000278633', 'ENSG00000261171', 'ENSG00000258028', 'ENSG00000254615', 'ENSG00000273373', 'ENSG00000257151', 'ENSG00000232498', 'ENSG00000234165', 'ENSG0000

/Users/zakirov/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Replace unmapped gene symbols with original gene symbols

In [28]:
cur_data.adata.var['gene_symbol'] = cur_data.adata.var['gene_symbol'].fillna(
    cur_data.adata.var['gene_symbols']
)

### Validate var metadata

In [29]:
cur_data.validate_data(slot='var')

2026-01-15 14:39:56,946 INFO curation_tools.curation_tools: adata.var is valid according to the var_schema.

       ensembl_gene_id   gene_symbol
index
0      ENSG00000243485   MIR1302-2HG
1      ENSG00000237613       FAM138A
2      ENSG00000186092         OR4F5
3      ENSG00000241860  RP11-34P13.7
4      ENSG00000239945  RP11-34P13.8
...                ...           ...
33689  ENSG00000277856    AC233755.2
33690  ENSG00000275063    AC233755.1
33691  ENSG00000271254    AC240274.1
33692  ENSG00000277475    AC213203.1
33693  ENSG00000268674       FAM231B

[33694 rows x 2 columns]

# Save the dataset

In [30]:
cur_data.save_curated_data_h5ad()

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)
... storing 'dataset_id' as categorical
... storing 'data_modality' as categorical
... storing 'significance_criteria' as categorical
... storing 'perturbation_name' as categorical
... storing 'perturbed_target_coord' as categorical
... storing 'perturbed_target_chromosome' as categorical
... storing 'perturbed_target_ensg' as categorical
... storing 'perturbed_target_symbol' as categorical
... storing 'perturbed_target_biotype' as categorical
... storing 'guide_sequence' as categorical
... storing 'perturbation_type_label' as categorical
... storing 'perturbation_type_id' as categorical
... storing 'timepoint' as categorical
... storing 'treatment_label' as categorical
... storing 'treatment_id' as categorical
... storing 'technical_replicate' as categorical
... storing 'biological_replicate' as categorical
... storing 'model_system_label' as categorical
... storing 'model_system_id' as categorical
... storing 'species' as categorical
... storing 'tissue_label' as categorical
... storing 'tissue_id' as categorical
... storing 'cell_type_label' as categorical
... storing 'cell_type_id' as categorical
... storing 'cell_line_label' as categorical
... storing 'cell_line_id' as categorical
... storing 'sex_label' as categorical
... storing 'sex_id' as categorical
... storing 'developmental_stage_label' as categorical
... storing 'developmental_stage_id' as categorical
... storing 'disease_label' as categorical
... storing 'disease_id' as categorical
... storing 'study_title' as categorical
... storing 'study_uri' as categorical
... storing 'first_author' as categorical
... storing 'last_author' as categorical
... storing 'experiment_title' as categorical
... storing 'experiment_summary' as categorical
... storing 'number_of_perturbed_targets' as categorical
... storing 'number_of_perturbed_samples' as categorical
... storing 'library_generation_type_id' as categorical
... storing 'library_generation_type_label' as categorical
... storing 'library_generation_method_id' as categorical
... storing 'library_generation_method_label' as categorical
... storing 'enzyme_delivery_method_id' as categorical
... storing 'enzyme_delivery_method_label' as categorical
... storing 'library_delivery_method_id' as categorical
... storing 'library_delivery_method_label' as categorical
... storing 'enzyme_integration_state_id' as categorical
... storing 'enzyme_integration_state_label' as categorical
... storing 'library_integration_state_id' as categorical
... storing 'library_integration_state_label' as categorical
... storing 'enzyme_expression_control_id' as categorical
... storing 'enzyme_expression_control_label' as categorical
... storing 'library_expression_control_id' as categorical
... storing 'library_expression_control_label' as categorical
... storing 'library_name' as categorical
... storing 'library_uri' as categorical
... storing 'library_format_id' as categorical
... storing 'library_format_label' as categorical
... storing 'library_scope_id' as categorical
... storing 'library_scope_label' as categorical
... storing 'library_perturbation_type_id' as categorical
... storing 'library_perturbation_type_label' as categorical
... storing 'library_manufacturer' as categorical
... storing 'library_lentiviral_generation' as categorical
... storing 'library_grnas_per_target' as categorical
... storing 'library_total_grnas' as categorical
... storing 'readout_dimensionality_id' as categorical
... storing 'readout_dimensionality_label' as categorical
... storing 'readout_type_id' as categorical
... storing 'readout_type_label' as categorical
... storing 'readout_technology_id' as categorical
... storing 'readout_technology_label' as categorical
... storing 'method_name_id' as categorical
... storing 'method_name_label' as categorical
... storing 'method_uri' as categorical
... storing 'sequencing_library_kit_id' as categorical
... storing 'sequencing_library_kit_label' as categorical
... storing 'sequencing_platform_id' as categorical
... storing 'sequencing_platform_label' as categorical
... storing 'sequencing_strategy_id' as categorical
... storing 'sequencing_strategy_label' as categorical
... storing 'software_counts_id' as categorical
... storing 'software_counts_label' as categorical
... storing 'software_analysis_id' as categorical
... storing 'software_analysis_label' as categorical
... storing 'score_interpretation' as categorical
... storing 'reference_genome_id' as categorical
... storing 'reference_genome_label' as categorical
... storing 'associated_datasets' as categorical
... storing 'license_label' as categorical
... storing 'license_id' as categorical
... storing 'ensembl_gene_id' as categorical
... storing 'gene_symbol' as categorical

✅ Curated h5ad data saved to ../curated/h5ad/norman_2019_raw_curated.h5ad

In [31]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/norman_2019_raw_curated_metadata.parquet

# Upload to BigQuery

In [32]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/norman_2019_raw_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

Staging table: loading `.parquet` file ../curated/parquet/norman_2019_raw_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...
Staging table: loaded 111445 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [33]:
!gcloud storage cp ../curated/h5ad/norman_2019_raw_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/norman_2019_raw_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/norman_2019_raw_curated.h5ad
  Completed files 32/1 | 2.7GiB/2.7GiB | 37.2MiB/s

Average throughput: 36.2MiB/s


Updates are available for some Google Cloud CLI components.  To install them,
please run:
  $ gcloud components update