## Note that this notebook should be run in GCP Colab environment

Runtime requirements:
- min. 750 GB disk space
- min. 500 GB RAM

In [1]:
# !pwd

In [2]:
# !git clone https://github.com/EMBL-EBI-ABC/PerturbationCatalogue.git

In [3]:
# %cd PerturbationCatalogue/data_exploration/

In [4]:
# !git pull
# !git switch aleks/curate_nadig_2025

In [5]:
# !uv pip install -r requirements.txt

In [6]:
# !gcloud init --project "prj-ext-dev-pertcat-437314" --account "zakirov@ebi.ac.uk"

In [7]:
# !mkdir -p Perturbseq/non_curated/h5ad/
# !gcloud storage cp gs://perturbation-catalogue-lake/perturbseq/non_curated/orion_2025_hek293t.h5ad Perturbseq/non_curated/h5ad/

# Import

In [8]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

# import logging
# logging.basicConfig(
#     level=logging.DEBUG,
#     format="%(asctime)s %(levelname)s %(name)s: %(message)s",
#     handlers=[
#         logging.FileHandler("curation.log"),
#         logging.StreamHandler(),  # keep console output too
#     ],
#     force=True,
# )

# Pre-process the data

### Load the data and construct the dummy anndata object to explore the dataset offline

In [9]:
# from scipy.sparse import csr_matrix
# import numpy as np
# import scanpy as sc
# import snapatac2 as snap

# backed_data = snap.read('Perturbseq/non_curated/h5ad/orion_2025_hek293t.h5ad')

# obs = backed_data.obs[:].to_pandas()
# var = backed_data.var[:].to_pandas()

# N1 = obs.shape[0]  # Number of objects (e.g., cells)
# N2 = var.shape[0]  # Number of categories (e.g., genes)
# rows = np.arange(N1)
# cols = (np.floor(np.random.permutation(N1)/float(N1)*N2)).astype(int) # Randomly pick N1 objects and assign to N2 categories in almost equal proportion
# w = np.ones(N1)
# conn_matrix = csr_matrix((w, (rows, cols)), shape=(N1, N2), dtype=int)

# adata = sc.AnnData(X=conn_matrix, obs=obs, var=var)

# # save the non-curated AnnData object
# adata.write_h5ad("Perturbseq/non_curated/h5ad/orion_2025_hek293t_dummy.h5ad")

# Initialise the dataset object

In [10]:
noncurated_path = "../non_curated/h5ad/orion_2025_hek293t.h5ad"
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/orion_2025_hek293t.h5ad

In [11]:
cur_data.adata.obs = cur_data.adata.obs[['sample', 'guide_target', 'gene_target']]
cur_data.adata.obs.head()

,sample,guide_target,gene_target
AAACCAAAGAAGTAGC-HEK293T_Batch1,HEK293T_Batch1,FAM180A_P1P2-1|FAM180A_P1P2-2,FAM180A
AAACCAAAGAGTACGG-HEK293T_Batch1,HEK293T_Batch1,non-targeting_03016|non-targeting_03214,Non-Targeting
AAACCAAAGAGTGGGC-HEK293T_Batch1,HEK293T_Batch1,PCDHGC4_P1P2-1|PCDHGC4_P1P2-2,PCDHGC4
AAACCAAAGAGTGTAA-HEK293T_Batch1,HEK293T_Batch1,USP30_P1P2-1|USP30_P1P2-2,USP30
AAACCAAAGATACGGG-HEK293T_Batch1,HEK293T_Batch1,KLRD1_P1P2-1|KLRD1_P1P2-2,KLRD1

In [12]:
cur_data.adata.var['gene_symbol'] = cur_data.adata.var.index

In [13]:
cur_data.show_var()

Variable data:
DataFrame shape: (38606, 1)
--------------------------------------------------
                     gene_symbol
DDX11L2                  DDX11L2
MIR1302-2HG          MIR1302-2HG
FAM138A                  FAM138A
ENSG00000290826  ENSG00000290826
OR4F5                      OR4F5
...                          ...
ENSG00000277836  ENSG00000277836
ENSG00000278633  ENSG00000278633
ENSG00000276017  ENSG00000276017
ENSG00000278817  ENSG00000278817
ENSG00000277196  ENSG00000277196

[38606 rows x 1 columns]
--------------------------------------------------

# OBS slot curation

### Add cell barcodes to the obs slot

In [14]:
cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.astype(str)
cur_data.adata.obs[['cell_barcode']]

                                                        cell_barcode
AAACCAAAGAAGTAGC-HEK293T_Batch1      AAACCAAAGAAGTAGC-HEK293T_Batch1
AAACCAAAGAGTACGG-HEK293T_Batch1      AAACCAAAGAGTACGG-HEK293T_Batch1
AAACCAAAGAGTGGGC-HEK293T_Batch1      AAACCAAAGAGTGGGC-HEK293T_Batch1
AAACCAAAGAGTGTAA-HEK293T_Batch1      AAACCAAAGAGTGTAA-HEK293T_Batch1
AAACCAAAGATACGGG-HEK293T_Batch1      AAACCAAAGATACGGG-HEK293T_Batch1
...                                                              ...
GTTGTCCGTGGGATGG-HEK293T_Batch223  GTTGTCCGTGGGATGG-HEK293T_Batch223
GTTGTCTTCAACAGCC-HEK293T_Batch223  GTTGTCTTCAACAGCC-HEK293T_Batch223
GTTGTCTTCAGTACTG-HEK293T_Batch223  GTTGTCTTCAGTACTG-HEK293T_Batch223
GTTGTCTTCCGCCGTT-HEK293T_Batch223  GTTGTCTTCCGCCGTT-HEK293T_Batch223
GTTGTGCAGGCTTGCG-HEK293T_Batch223  GTTGTGCAGGCTTGCG-HEK293T_Batch223

[4534299 rows x 1 columns]

In [15]:
cur_data.adata.obs.isna().sum()

sample          0
guide_target    0
gene_target     0
cell_barcode    0
dtype: int64

### Extract perturbation symbols

### Rename `guide_target` to `perturbation_name`

In [16]:
cur_data.rename_columns(slot = 'obs', name_dict = {'guide_target': 'perturbation_name'})

Renamed columns in adata.obs: {'guide_target': 'perturbation_name'}

### Rename `gene_target` to `perturbed_target_symbol`

In [17]:
cur_data.rename_columns(slot = 'obs', name_dict = {'gene_target': 'input_perturbed_target_symbol'})

Renamed columns in adata.obs: {'gene_target': 'input_perturbed_target_symbol'}

#### Clean up `perturbed_target_symbol` column

In [18]:
cur_data.replace_entries(
    slot="obs",
    column="input_perturbed_target_symbol",
    map_dict={
        "Non-Targeting": "control_nontargeting"
    }
)

cur_data.show_unique(slot = 'obs', column = 'input_perturbed_target_symbol')

Replaced 'Non-Targeting' with 'control_nontargeting' in column input_perturbed_target_symbol of adata.obs

Unique values in adata.obs.input_perturbed_target_symbol: 18312
--------------------------------------------------
{'A1BG',
 'A1CF',
 'A2M',
 'A2ML1',
 'A3GALT2',
 'A4GALT',
 'A4GNT',
 'AAAS',
 'AACS',
 'AADAC',
 'AADACL2',
 'AADACL3',
 'AADACL4',
 'AADAT',
 'AAGAB',
 'AAK1',
 'AAMDC',
 'AAMP',
 'AANAT',
 'AAR2',
 'AARD',
 'AARS1',
 'AARS2',
 'AARSD1',
 'AASDH',
 'AASS',
 'AATF',
 'AATK',
 'ABAT',
 'ABCA1',
 'ABCA10',
 'ABCA12',
 'ABCA13',
 'ABCA2',
 'ABCA3',
 'ABCA4',
 'ABCA5',
 'ABCA6',
 'ABCA7',
 'ABCA8',
 'ABCA9',
 'ABCB1',
 'ABCB10',
 'ABCB11',
 'ABCB4',
 'ABCB5',
 'ABCB6',
 'ABCB7',
 'ABCB8',
 'ABCB9',
 'ABCC1',
 'ABCC10',
 'ABCC11',
 'ABCC12',
 'ABCC2',
 'ABCC3',
 'ABCC4',
 'ABCC5',
 'ABCC6',
 'ABCC8',
 'ABCC9',
 'ABCD1',
 'ABCD2',
 'ABCD3',
 'ABCD4',
 'ABCE1',
 'ABCF1',
 'ABCF2',
 'ABCF3',
 'ABCG1',
 'ABCG2',
 'ABCG4',
 'ABCG5',
 'ABCG8',
 'ABHD1',
 'ABHD10',
 'ABHD11',
 'ABHD12',
 'ABHD12B',
 'ABHD13',
 'ABHD14A',
 'ABHD14B',
 'ABHD15',
 'ABHD16A',
 'ABHD16B',
 'ABHD17A',
 'ABHD17B',
 'ABHD17C',
 'ABHD18',
 'ABHD2',
 'ABHD3',
 'ABHD4',
 'ABHD5',
 'ABHD6',
 'ABHD8',
 'ABI1',
 'ABI2',
 'ABI3',
 'ABI3BP',
 'ABITRAM',
 'ABL1',
 'ABL2',
 'ABLIM1',
 'ABLIM2',
 'ABLIM3',
 'ABO',
 'ABR',
 'ABRA',
 'ABRACL',
 'ABRAXAS1',
 'ABRAXAS2',
 'ABT1',
 'ABTB1',
 'ABTB2',
 'ABTB3',
 'ACAA1',
 'ACAA2',
 'ACACA',
 'ACACB',
 'ACAD10',
 'ACAD11',
 'ACAD8',
 'ACAD9',
 'ACADL',
 'ACADM',
 'ACADS',
 'ACADSB',
 'ACADVL',
 'ACAN',
 'ACAP1',
 'ACAP2',
 'ACAP3',
 'ACAT1',
 'ACAT2',
 'ACBD3',
 'ACBD4',
 'ACBD5',
 'ACBD6',
 'ACBD7',
 'ACCS',
 'ACCSL',
 'ACD',
 'ACE',
 'ACE2',
 'ACER1',
 'ACER2',
 'ACER3',
 'ACHE',
 'ACIN1',
 'ACKR1',
 'ACKR2',
 'ACKR3',
 'ACKR4',
 'ACLY',
 'ACMSD',
 'ACO1',
 'ACO2',
 'ACOD1',
 'ACOT1',
 'ACOT11',
 'ACOT12',
 'ACOT13',
 'ACOT2',
 'ACOT4',
 'ACOT6',
 'ACOT7',
 'ACOT8',
 'ACOT9',
 'ACOX1',
 'ACOX2',
 'ACOX3',
 'ACOXL',
 'ACP1',
 'ACP2',
 'ACP3',
 'ACP4',
 'ACP5',
 'ACP6',
 'ACP7',
 'ACR',
 'ACRBP',
 'ACRV1',
 'ACSBG1',
 'ACSBG2',
 'ACSF2',
 'ACSF3',
 'ACSL1',
 'ACSL3',
 'ACSL4',
 'ACSL5',
 'ACSL6',
 'ACSM1',
 'ACSM2A',
 'ACSM2B',
 'ACSM3',
 'ACSM4',
 'ACSM5',
 'ACSM6',
 'ACSS1',
 'ACSS2',
 'ACSS3',
 'ACTA1',
 'ACTA2',
 'ACTB',
 'ACTBL2',
 'ACTC1',
 'ACTG1',
 'ACTG2',
 'ACTL10',
 'ACTL6A',
 'ACTL6B',
 'ACTL7A',
 'ACTL7B',
 'ACTL8',
 'ACTL9',
 'ACTMAP',
 'ACTN1',
 'ACTN2',
 'ACTN3',
 'ACTN4',
 'ACTR10',
 'ACTR1A',
 'ACTR1B',
 'ACTR2',
 'ACTR3',
 'ACTR3B',
 'ACTR3C',
 'ACTR5',
 'ACTR6',
 'ACTR8',
 'ACTRT1',
 'ACTRT2',
 'ACTRT3',
 'ACVR1',
 'ACVR1B',
 'ACVR1C',
 'ACVR2A',
 'ACVR2B',
 'ACVRL1',
 'ACY1',
 'ACY3',
 'ACYP1',
 'ACYP2',
 'ADA',
 'ADA2',
 'ADAD1',
 'ADAD2',
 'ADAL',
 'ADAM10',
 'ADAM11',
 'ADAM12',
 'ADAM15',
 'ADAM17',
 'ADAM18',
 'ADAM19',
 'ADAM2',
 'ADAM20',
 'ADAM21',
 'ADAM22',
 'ADAM23',
 'ADAM28',
 'ADAM29',
 'ADAM30',
 'ADAM32',
 'ADAM33',
 'ADAM7',
 'ADAM8',
 'ADAM9',
 'ADAMDEC1',
 'ADAMTS1',
 'ADAMTS10',
 'ADAMTS12',
 'ADAMTS13',
 'ADAMTS14',
 'ADAMTS15',
 'ADAMTS16',
 'ADAMTS17',
 'ADAMTS18',
 'ADAMTS19',
 'ADAMTS2',
 'ADAMTS20',
 'ADAMTS3',
 'ADAMTS4',
 'ADAMTS5',
 'ADAMTS6',
 'ADAMTS7',
 'ADAMTS8',
 'ADAMTS9',
 'ADAMTSL1',
 'ADAMTSL2',
 'ADAMTSL3',
 'ADAMTSL4',
 'ADAMTSL5',
 'ADAP1',
 'ADAP2',
 'ADAR',
 'ADARB1',
 'ADARB2',
 'ADAT1',
 'ADAT2',
 'ADAT3',
 'ADCK1',
 'ADCK2',
 'ADCK5',
 'ADCY1',
 'ADCY10',
 'ADCY2',
 'ADCY3',
 'ADCY4',
 'ADCY5',
 'ADCY6',
 'ADCY7',
 'ADCY8',
 'ADCY9',
 'ADCYAP1',
 'ADCYAP1R1',
 'ADD1',
 'ADD2',
 'ADD3',
 'ADGB',
 'ADGRA1',
 'ADGRA2',
 'ADGRA3',
 'ADGRB1',
 'ADGRB2',
 'ADGRB3',
 'ADGRD1',
 'ADGRD2',
 'ADGRE1',
 'ADGRE2',
 'ADGRE3',
 'ADGRE5',
 'ADGRF1',
 'ADGRF3',
 'ADGRF4',
 'ADGRF5',
 'ADGRG1',
 'ADGRG2',
 'ADGRG3',
 'ADGRG4',
 'ADGRG5',
 'ADGRG6',
 'ADGRG7',
 'ADGRL1',
 'ADGRL2',
 'ADGRL3',
 'ADGRL4',
 'ADGRV1',
 'ADH1A',
 'ADH1B',
 'ADH1C',
 'ADH4',
 'ADH5',
 'ADH6',
 'ADH7',
 'ADHFE1',
 'ADI1',
 'ADIG',
 'ADIPOQ',
 'ADIPOR1',
 'ADIPOR2',
 'ADIRF',
 'ADISSP',
 'ADK',
 'ADM',
 'ADM2',
 'ADM5',
 'ADNP',
 'ADNP2',
 'ADO',
 'ADORA1',
 'ADORA2A',
 'ADORA2B',
 'ADORA3',
 'ADPGK',
 'ADPRH',
 'ADPRHL1',
 'ADPRM',
 'ADPRS',
 'ADRA1A',
 'ADRA1B',
 'ADRA1D',
 'ADRA2A',
 'ADRA2B',
 'ADRA2C',
 'ADRB1',
 'ADRB2',
 'ADRB3',
 'ADRM1',
 'ADSL',
 'ADSS1',
 'ADSS2',
 'ADTRP',
 'AEBP1',
 'AEBP2',
 'AEN',
 'AFAP1',
 'AFAP1L1',
 'AFAP1L2',
 'AFDN',
 'AFF1',
 'AFF2',
 'AFF3',
 'AFF4',
 'AFG1L',
 'AFG3L2',
 'AFM',
 'AFMID',
 'AFP',
 'AFTPH',
 'AGA',
 'AGAP1',
 'AGAP2',
 'AGAP3',
 'AGAP9',
 'AGBL1',
 'AGBL2',
 'AGBL3',
 'AGBL4',
 'AGBL5',
 'AGER',
 'AGFG1',
 'AGFG2',
 'AGGF1',
 'AGK',
 'AGL',
 'AGMAT',
 'AGMO',
 'AGO1',
 'AGO2',
 'AGO3',
 'AGO4',
 'AGPAT1',
 'AGPAT2',
 'AGPAT3',
 'AGPAT4',
 'AGPAT5',
 'AGPS',
 'AGR2',
 'AGR3',
 'AGRN',
 'AGRP',
 'AGT',
 'AGTPBP1',
 'AGTR1',
 'AGTR2',
 'AGTRAP',
 'AGXT',
 'AGXT2',
 'AHCTF1',
 'AHCY',
 'AHCYL1',
 'AHCYL2',
 'AHDC1',
 'AHI1',
 'AHNAK',
 'AHNAK2',
 'AHR',
 'AHRR',
 'AHSA1',
 'AHSG',
 'AHSP',
 'AICDA',
 'AIF1',
 'AIF1L',
 'AIFM1',
 'AIFM2',
 'AIFM3',
 'AIG1',
 'AIM2',
 'AIMP1',
 'AIMP2',
 'AIP',
 'AIPL1',
 'AIRE',
 'AJAP1',
 'AJM1',
 'AJUBA',
 'AK1',
 'AK2',
 'AK3',
 'AK4',
 'AK5',
 'AK7',
 'AK8',
 'AK9',
 'AKAIN1',
 'AKAP1',
 'AKAP10',
 'AKAP11',
 'AKAP12',
 'AKAP13',
 'AKAP14',
 'AKAP17A',
 'AKAP3',
 'AKAP4',
 'AKAP5',
 'AKAP6',
 'AKAP7',
 'AKAP8',
 'AKAP8L',
 'AKAP9',
 'AKIP1',
 'AKIRIN1',
 'AKIRIN2',
 'AKNA',
 'AKNAD1',
 'AKR1A1',
 'AKR1B1',
 'AKR1B10',
 'AKR1B15',
 'AKR1C2',
 'AKR1C3',
 'AKR1C4',
 'AKR1D1',
 'AKR1E2',
 'AKR7A2',
 'AKR7A3',
 'AKT1',
 'AKT1S1',
 'AKT2',
 'AKT3',
 'AKTIP',
 'ALAD',
 'ALAS1',
 'ALAS2',
 'ALB',
 'ALCAM',
 'ALDH16A1',
 'ALDH18A1',
 'ALDH1A1',
 'ALDH1A2',
 'ALDH1A3',
 'ALDH1B1',
 'ALDH1L1',
 'ALDH1L2',
 'ALDH2',
 'ALDH3A1',
 'ALDH3A2',
 'ALDH3B1',
 'ALDH3B2',
 'ALDH4A1',
 'ALDH5A1',
 'ALDH6A1',
 'ALDH7A1',
 'ALDH8A1',
 'ALDH9A1',
 'ALDOA',
 'ALDOB',
 'ALDOC',
 'ALG1',
 'ALG10',
 'ALG10B',
 'ALG12',
 'ALG13',
 'ALG14',
 'ALG2',
 'ALG3',
 'ALG5',
 'ALG6',
 'ALG8',
 'ALG9',
 'ALK',
 'ALKAL1',
 'ALKAL2',
 'ALKBH1',
 'ALKBH2',
 'ALKBH3',
 'ALKBH4',
 'ALKBH5',
 'ALKBH6',
 'ALKBH7',
 'ALKBH8',
 'ALLC',
 'ALMS1',
 'ALOX12',
 'ALOX12B',
 'ALOX15',
 'ALOX15B',
 'ALOX5',
 'ALOX5AP',
 'ALOXE3',
 'ALPG',
 'ALPI',
 'ALPK1',
 'ALPK2',
 'ALPK3',
 'ALPL',
 'ALPP',
 'ALS2',
 'ALS2CL',
 'ALX1',
 'ALX3',
 'ALX4',
 'ALYREF',
 'AMACR',
 'AMBN',
 'AMBP',
 'AMBRA1',
 'AMD1',
 'AMDHD1',
 'AMDHD2',
 'AMELX',
 'AMELY',
 'AMER1',
 'AMER2',
 'AMER3',
 'AMFR',
 'AMH',
 'AMHR2',
 'AMIGO1',
 'AMIGO2',
 'AMIGO3',
 'AMMECR1',
 'AMMECR1L',
 'AMN',
 'AMN1',
 'AMOT',
 'AMOTL1',
 'AMOTL2',
 'AMPD1',
 'AMPD2',
 'AMPD3',
 'AMPH',
 'AMT',
 'AMTN',
 'AMY1B',
 'AMY2A',
 'AMY2B',
 'AMZ1',
 'AMZ2',
 'ANAPC1',
 'ANAPC10',
 'ANAPC11',
 'ANAPC13',
 'ANAPC15',
 'ANAPC16',
 'ANAPC2',
 'ANAPC4',
 'ANAPC5',
 'ANAPC7',
 'ANGEL1',
 'ANGEL2',
 'ANGPT1',
 'ANGPT2',
 'ANGPT4',
 'ANGPTL1',
 'ANGPTL2',
 'ANGPTL3',
 'ANGPTL4',
 'ANGPTL5',
 'ANGPTL6',
 'ANGPTL7',
 'ANGPTL8',
 'ANHX',
 'ANK1',
 'ANK2',
 'ANK3',
 'ANKAR',
 'ANKDD1A',
 'ANKDD1B',
 'ANKEF1',
 'ANKFN1',
 'ANKFY1',
 'ANKH',
 'ANKHD1',
 'ANKIB1',
 'ANKK1',
 'ANKLE1',
 'ANKLE2',
 'ANKMY1',
 'ANKMY2',
 'ANKRA2',
 'ANKRD1',
 'ANKRD10',
 'ANKRD11',
 'ANKRD12',
 'ANKRD13A',
 'ANKRD13B',
 'ANKRD13C',
 'ANKRD13D',
 'ANKRD16',
 'ANKRD17',
 'ANKRD18A',
 'ANKRD18B',
 'ANKRD2',
 'ANKRD22',
 'ANKRD23',
 'ANKRD24',
 'ANKRD26',
 'ANKRD27',
 'ANKRD28',
 'ANKRD29',
 'ANKRD30A',
 'ANKRD30B',
 'ANKRD31',
 'ANKRD33',
 'ANKRD33B',
 'ANKRD34A',
 'ANKRD34B',
 'ANKRD34C',
 'ANKRD35',
 'ANKRD36',
 'ANKRD36C',
 'ANKRD37',
 'ANKRD39',
 'ANKRD40',
 'ANKRD42',
 'ANKRD44',
 'ANKRD45',
 'ANKRD46',
 'ANKRD49',
 'ANKRD50',
 'ANKRD52',
 'ANKRD53',
 'ANKRD54',
 'ANKRD55',
 'ANKRD6',
 'ANKRD60',
 'ANKRD61',
 'ANKRD62',
 'ANKRD63',
 'ANKRD65',
 'ANKRD66',
 'ANKRD7',
 'ANKRD9',
 'ANKS1A',
 'ANKS1B',
 'ANKS3',
 'ANKS4B',
 'ANKS6',
 'ANKUB1',
 'ANKZF1',
 'ANO1',
 'ANO10',
 'ANO2',
 'ANO3',
 'ANO4',
 'ANO5',
 'ANO6',
 'ANO7',
 'ANO8',
 'ANO9',
 'ANOS1',
 'ANP32A',
 'ANP32B',
 'ANP32D',
 'ANP32E',
 'ANPEP',
 'ANTKMT',
 'ANTXR1',
 'ANTXR2',
 'ANXA1',
 'ANXA10',
 'ANXA11',
 'ANXA13',
 'ANXA2',
 'ANXA2R',
 'ANXA3',
 'ANXA4',
 'ANXA5',
 'ANXA6',
 'ANXA7',
 'ANXA9',
 'AOAH',
 'AOC1',
 'AOC2',
 'AOC3',
 'AOPEP',
 'AOX1',
 'AP1AR',
 'AP1B1',
 'AP1G1',
 'AP1G2',
 'AP1M1',
 'AP1M2',
 'AP1S1',
 'AP1S2',
 'AP1S3',
 'AP2A1',
 'AP2A2',
 'AP2B1',
 'AP2M1',
 'AP2S1',
 'AP3B1',
 'AP3B2',
 'AP3D1',
 'AP3M1',
 'AP3M2',
 'AP3S1',
 'AP3S2',
 'AP4B1',
 'AP4E1',
 'AP4M1',
 'AP4S1',
 'AP5B1',
 'AP5M1',
 'AP5S1',
 'AP5Z1',
 'APAF1',
 'APBA1',
 'APBA2',
 'APBA3',
 'APBB1',
 'APBB1IP',
 'APBB2',
 'APBB3',
 'APC',
 'APC2',
 'APCDD1',
 'APCDD1L',
 'APCS',
 'APEH',
 'APEX1',
 'APEX2',
 'APH1A',
 'APH1B',
 'API5',
 'APIP',
 'APLF',
 'APLN',
 'APLNR',
 'APLP1',
 'APLP2',
 'APMAP',
 'APOA1',
 'APOA2',
 'APOA4',
 'APOA5',
 'APOB',
 'APOBEC1',
 'APOBEC2',
 'APOBEC3A',
 'APOBEC3B',
 'APOBEC3F',
 'APOBEC3G',
 'APOBEC3H',
 'APOBEC4',
 'APOBR',
 'APOC1',
 'APOC2',
 'APOC3',
 'APOC4',
 'APOD',
 'APOE',
 'APOF',
 'APOH',
 'APOL1',
 'APOL2',
 'APOL3',
 'APOL4',
 'APOL5',
 'APOL6',
 'APOLD1',
 'APOO',
 'APOOL',
 'APP',
 'APPBP2',
 'APPL1',
 'APPL2',
 'APRG1',
 'APRT',
 'APTX',
 'AQP1',
 'AQP10',
 'AQP11',
 'AQP12A',
 'AQP12B',
 'AQP2',
 'AQP3',
 'AQP4',
 'AQP5',
 'AQP6',
 'AQP7',
 'AQP8',
 'AQP9',
 'AQR',
 'AR',
 'ARAF',
 'ARAP1',
 'ARAP2',
 'ARAP3',
 'ARC',
 'ARCN1',
 'AREG',
 'AREL1',
 'ARF1',
 'ARF3',
 'ARF4',
 'ARF5',
 'ARF6',
 'ARFGAP1',
 'ARFGAP2',
 'ARFGAP3',
 'ARFGEF1',
 'ARFGEF2',
 'ARFGEF3',
 'ARFIP1',
 'ARFIP2',
 'ARFRP1',
 'ARG1',
 'ARG2',
 'ARGFX',
 'ARGLU1',
 'ARHGAP1',
 'ARHGAP10',
 'ARHGAP11A',
 'ARHGAP11B',
 'ARHGAP12',
 'ARHGAP15',
 'ARHGAP17',
 'ARHGAP18',
 'ARHGAP19',
 'ARHGAP20',
 'ARHGAP21',
 'ARHGAP22',
 'ARHGAP23',
 'ARHGAP24',
 'ARHGAP25',
 'ARHGAP26',
 'ARHGAP27',
 'ARHGAP28',
 'ARHGAP29',
 'ARHGAP30',
 'ARHGAP31',
 'ARHGAP32',
 'ARHGAP33',
 'ARHGAP35',
 'ARHGAP36',
 'ARHGAP39',
 'ARHGAP4',
 'ARHGAP40',
 'ARHGAP42',
 'ARHGAP44',
 'ARHGAP45',
 'ARHGAP5',
 'ARHGAP6',
 'ARHGAP8',
 'ARHGAP9',
 'ARHGDIA',
 'ARHGDIB',
 'ARHGDIG',
 'ARHGEF1',
 'ARHGEF10',
 'ARHGEF10L',
 'ARHGEF11',
 'ARHGEF12',
 'ARHGEF15',
 'ARHGEF16',
 'ARHGEF17',
 'ARHGEF18',
 'ARHGEF19',
 'ARHGEF2',
 'ARHGEF25',
 'ARHGEF26',
 'ARHGEF28',
 'ARHGEF3',
 'ARHGEF33',
 'ARHGEF35',
 'ARHGEF37',
 'ARHGEF38',
 'ARHGEF39',
 'ARHGEF4',
 'ARHGEF40',
 'ARHGEF5',
 'ARHGEF6',
 'ARHGEF7',
 'ARHGEF9',
 'ARID1A',
 'ARID1B',
 'ARID2',
 'ARID3A',
 'ARID3B',
 'ARID3C',
 'ARID4A',
 'ARID4B',
 'ARID5A',
 'ARID5B',
 'ARIH1',
 'ARIH2',
 'ARIH2OS',
 'ARL1',
 'ARL10',
 'ARL11',
 'ARL13A',
 'ARL13B',
 'ARL14',
 'ARL14EP',
 'ARL14EPL',
 'ARL15',
 'ARL16',
 'ARL2',
 'ARL2BP',
 'ARL3',
 'ARL4A',
 'ARL4C',
 'ARL4D',
 'ARL5A',
 'ARL5B',
 'ARL5C',
 'ARL6',
 'ARL6IP1',
 'ARL6IP4',
 'ARL6IP5',
 'ARL6IP6',
 'ARL8A',
 'ARL8B',
 'ARL9',
 'ARMC1',
 'ARMC10',
 'ARMC12',
 'ARMC2',
 'ARMC3',
 'ARMC5',
 'ARMC6',
 'ARMC7',
 'ARMC8',
 'ARMC9',
 'ARMCX1',
 'ARMCX2',
 'ARMCX3',
 'ARMCX4',
 'ARMCX6',
 'ARMH1',
 'ARMH3',
 'ARMH4',
 'ARMS2',
 'ARMT1',
 'ARNT',
 'ARNT2',
 'ARPC1A',
 'ARPC1B',
 'ARPC2',
 'ARPC3',
 'ARPC4',
 'ARPC5',
 'ARPC5L',
 'ARPIN',
 'ARPP19',
 'ARPP21',
 'ARR3',
 'ARRB1',
 'ARRB2',
 'ARRDC1',
 'ARRDC1-AS1',
 'ARRDC2',
 'ARRDC3',
 'ARRDC4',
 'ARRDC5',
 'ARSA',
 'ARSB',
 'ARSD',
 'ARSF',
 'ARSG',
 'ARSH',
 'ARSI',
 'ARSJ',
 'ARSK',
 'ARSL',
 'ART1',
 'ART3',
 'ART4',
 'ART5',
 'ARTN',
 'ARV1',
 'ARVCF',
 'ARX',
 'AS3MT',
 'ASAH1',
 'ASAH2',
 'ASAH2B',
 'ASAP1',
 'ASAP2',
 'ASAP3',
 'ASB1',
 'ASB10',
 'ASB11',
 'ASB12',
 'ASB13',
 'ASB14',
 'ASB15',
 'ASB16',
 'ASB17',
 'ASB18',
 'ASB2',
 'ASB4',
 'ASB5',
 'ASB6',
 'ASB7',
 'ASB8',
 'ASB9',
 'ASCC1',
 'ASCC2',
 'ASCC3',
 'ASCL1',
 'ASCL2',
 'ASCL3',
 'ASCL4',
 'ASCL5',
 'ASF1A',
 'ASF1B',
 'ASGR1',
 'ASGR2',
 'ASH1L',
 'ASH2L',
 'ASIC1',
 'ASIC2',
 'ASIC3',
 'ASIC4',
 'ASIC5',
 'ASIP',
 'ASL',
 'ASMT',
 'ASMTL',
 'ASNS',
 'ASNSD1',
 'ASPA',
 'ASPDH',
 'ASPG',
 'ASPH',
 'ASPHD1',
 'ASPHD2',
 'ASPM',
 'ASPN',
 'ASPRV1',
 'ASPSCR1',
 'ASRGL1',
 'ASS1',
 'ASTE1',
 'ASTL',
 'ASTN1',
 'ASTN2',
 'ASXL1',
 'ASXL2',
 'ASXL3',
 'ASZ1',
 'ATAD1',
 'ATAD2',
 'ATAD2B',
 'ATAD3A',
 'ATAD3B',
 'ATAD3C',
 'ATAD5',
 'ATAT1',
 'ATCAY',
 'ATE1',
 'ATF1',
 'ATF2',
 'ATF3',
 'ATF4',
 'ATF6',
 'ATF6B',
 'ATF7',
 'ATF7IP',
 'ATF7IP2',
 'ATG10',
 'ATG101',
 'ATG12',
 'ATG13',
 'ATG14',
 'ATG16L1',
 'ATG16L2',
 'ATG2A',
 'ATG2B',
 'ATG3',
 'ATG4A',
 'ATG4B',
 'ATG4C',
 'ATG4D',
 'ATG5',
 'ATG7',
 'ATG9A',
 'ATG9B',
 'ATIC',
 'ATL1',
 'ATL2',
 'ATL3',
 'ATM',
 'ATMIN',
 'ATN1',
 'ATOH1',
 'ATOH7',
 'ATOH8',
 'ATOSA',
 'ATOSB',
 'ATOX1',
 'ATP10A',
 'ATP10B',
 'ATP10D',
 'ATP11A',
 'ATP11AUN',
 'ATP11B',
 'ATP11C',
 'ATP12A',
 'ATP13A1',
 'ATP13A2',
 'ATP13A3',
 'ATP13A4',
 'ATP13A5',
 'ATP1A1',
 'ATP1A2',
 'ATP1A3',
 'ATP1A4',
 'ATP1B1',
 'ATP1B2',
 'ATP1B3',
 'ATP1B4',
 'ATP23',
 'ATP2A1',
 'ATP2A2',
 'ATP2A3',
 'ATP2B1',
 'ATP2B2',
 'ATP2B3',
 'ATP2B4',
 'ATP2C1',
 'ATP2C2',
 'ATP4A',
 'ATP4B',
 'ATP5F1A',
 'ATP5F1B',
 'ATP5F1C',
 'ATP5F1D',
 'ATP5F1E',
 'ATP5IF1',
 'ATP5MC1',
 'ATP5MC2',
 'ATP5MC3',
 'ATP5ME',
 'ATP5MG',
 'ATP5MGL',
 'ATP5MJ',
 'ATP5MK',
 'ATP5PB',
 'ATP5PD',
 'ATP5PO',
 'ATP6AP1',
 'ATP6AP2',
 'ATP6V0A1',
 'ATP6V0A2',
 'ATP6V0A4',
 'ATP6V0B',
 'ATP6V0C',
 'ATP6V0D1',
 'ATP6V0D2',
 'ATP6V0E1',
 'ATP6V0E2',
 'ATP6V1A',
 'ATP6V1B1',
 'ATP6V1B2',
 'ATP6V1C1',
 'ATP6V1C2',
 'ATP6V1D',
 'ATP6V1E1',
 'ATP6V1F',
 'ATP6V1G1',
 'ATP6V1G2',
 'ATP6V1G3',
 'ATP6V1H',
 'ATP7A',
 'ATP7B',
 'ATP8A1',
 'ATP8A2',
 'ATP8B1',
 'ATP8B2',
 'ATP8B3',
 'ATP8B4',
 'ATP9A',
 'ATP9B',
 'ATPAF1',
 'ATPAF2',
 'ATPSCKMT',
 'ATR',
 'ATRAID',
 'ATRIP',
 'ATRN',
 'ATRNL1',
 'ATRX',
 'ATXN1',
 'ATXN10',
 'ATXN1L',
 'ATXN2',
 'ATXN2L',
 'ATXN3',
 'ATXN3L',
 'ATXN7',
 'ATXN7L1',
 'ATXN7L2',
 'ATXN7L3',
 'ATXN7L3B',
 'AUH',
 'AUNIP',
 'AUP1',
 'AURKA',
 'AURKAIP1',
 'AURKB',
 'AURKC',
 'AUTS2',
 'AVEN',
 'AVIL',
 'AVL9',
 'AVP',
 'AVPI1',
 'AVPR1A',
 'AVPR1B',
 'AVPR2',
 'AWAT1',
 'AWAT2',
 'AXDND1',
 'AXIN1',
 'AXIN2',
 'AXL',
 'AZGP1',
 'AZI2',
 'AZIN1',
 'AZIN2',
 'AZU1',
 'B2M',
 'B3GALNT1',
 'B3GALNT2',
 'B3GALT1',
 'B3GALT2',
 'B3GALT4',
 'B3GALT5',
 'B3GALT6',
 'B3GAT1',
 'B3GAT2',
 'B3GAT3',
 'B3GLCT',
 'B3GNT2',
 'B3GNT3',
 'B3GNT4',
 'B3GNT5',
 'B3GNT6',
 'B3GNT7',
 'B3GNT8',
 'B3GNT9',
 'B3GNTL1',
 'B4GALNT1',
 'B4GALNT2',
 'B4GALNT3',
 'B4GALNT4',
 'B4GALT1',
 'B4GALT2',
 'B4GALT3',
 'B4GALT4',
 'B4GALT5',
 'B4GALT6',
 'B4GALT7',
 'B4GAT1',
 'B9D1',
 'B9D2',
 'BAALC',
 'BAAT',
 'BABAM1',
 'BABAM2',
 'BACE1',
 'BACE2',
 'BACH1',
 'BACH2',
 'BAD',
 'BAG1',
 'BAG2',
 'BAG3',
 'BAG4',
 'BAG5',
 'BAHCC1',
 'BAHD1',
 'BAIAP2',
 'BAIAP2L1',
 'BAIAP2L2',
 'BAIAP3',
 'BAK1',
 'BAMBI',
 'BANF1',
 'BANF2',
 'BANK1',
 'BANP',
 'BAP1',
 'BARD1',
 'BARHL1',
 'BARHL2',
 'BARX1',
 'BARX2',
 'BASP1',
 'BATF',
 'BATF2',
 'BATF3',
 'BAX',
 'BAZ1A',
 'BAZ1B',
 'BAZ2A',
 'BAZ2B',
 'BBC3',
 'BBIP1',
 'BBLN',
 'BBOF1',
 'BBOX1',
 'BBS1',
 'BBS10',
 'BBS12',
 'BBS2',
 'BBS4',
 'BBS5',
 'BBS7',
 'BBS9',
 'BBX',
 'BCAM',
 'BCAN',
 'BCAP29',
 'BCAP31',
 'BCAR1',
 'BCAR3',
 'BCAS1',
 'BCAS2',
 'BCAS3',
 'BCAS4',
 'BCAT1',
 'BCAT2',
 'BCCIP',
 'BCDIN3D',
 'BCHE',
 'BCKDHA',
 'BCKDHB',
 'BCKDK',
 'BCL10',
 'BCL11A',
 'BCL11B',
 'BCL2',
 'BCL2A1',
 'BCL2L1',
 'BCL2L10',
 'BCL2L11',
 'BCL2L12',
 'BCL2L13',
 'BCL2L14',
 'BCL2L15',
 'BCL2L2',
 'BCL3',
 'BCL6',
 'BCL6B',
 'BCL7A',
 'BCL7B',
 'BCL7C',
 'BCL9',
 'BCL9L',
 'BCLAF1',
 'BCLAF3',
 'BCO1',
 'BCO2',
 'BCOR',
 'BCORL1',
 'BCR',
 'BCS1L',
 'BDH1',
 'BDH2',
 'BDKRB1',
 'BDKRB2',
 'BDNF',
 'BDP1',
 'BEAN1',
 'BECN1',
 'BEGAIN',
 'BEND2',
 'BEND3',
 'BEND4',
 'BEND5',
 'BEND6',
 'BEND7',
 'BEST1',
 'BEST2',
 'BEST3',
 'BEST4',
 'BET1',
 'BET1L',
 'BEX1',
 'BEX2',
 'BEX3',
 'BEX4',
 'BEX5',
 'BFAR',
 'BFSP1',
 'BFSP2',
 'BGN',
 'BHLHA15',
 'BHLHA9',
 'BHLHE22',
 'BHLHE23',
 'BHLHE40',
 'BHLHE41',
 'BHMT',
 'BHMT2',
 'BICC1',
 'BICD1',
 'BICD2',
 'BICDL1',
 'BICDL2',
 'BICRA',
 'BICRAL',
 'BID',
 'BIK',
 'BIN1',
 'BIN2',
 'BIN3',
 'BIRC2',
 'BIRC3',
 'BIRC5',
 'BIRC6',
 'BIRC7',
 'BIVM',
 'BLCAP',
 'BLID',
 'BLK',
 'BLM',
 'BLMH',
 'BLNK',
 'BLOC1S1',
 'BLOC1S2',
 'BLOC1S3',
 'BLOC1S4',
 'BLOC1S5',
 'BLOC1S6',
 'BLTP1',
 'BLTP2',
 'BLTP3A',
 'BLTP3B',
 'BLVRA',
 'BLVRB',
 'BLZF1',
 'BMAL1',
 'BMAL2',
 'BMERB1',
 'BMF',
 'BMI1',
 'BMP1',
 'BMP10',
 'BMP15',
 'BMP2',
 'BMP2K',
 'BMP3',
 'BMP4',
 'BMP5',
 'BMP6',
 'BMP7',
 'BMP8A',
 'BMP8B',
 'BMPER',
 'BMPR1A',
 'BMPR1B',
 'BMPR2',
 'BMS1',
 'BMT2',
 'BMX',
 'BNC1',
 'BNC2',
 'BNIP1',
 'BNIP2',
 'BNIP3',
 'BNIP3L',
 'BNIP5',
 'BNIPL',
 'BOC',
 'BOD1',
 'BOD1L1',
 'BOD1L2',
 'BOK',
 'BOLA1',
 'BOLA3',
 'BOLL',
 'BOP1',
 'BORA',
 'BORCS5',
 'BORCS6',
 'BORCS7',
 'BORCS8',
 'BPGM',
 'BPHL',
 'BPI',
 'BPIFA1',
 'BPIFA2',
 'BPIFA3',
 'BPIFB1',
 'BPIFB2',
 'BPIFB3',
 'BPIFB4',
 'BPIFB6',
 'BPIFC',
 'BPNT1',
 'BPNT2',
 'BPTF',
 'BRAF',
 'BRAP',
 'BRAT1',
 'BRCA1',
 'BRCA2',
 'BRCC3',
 'BRD1',
 'BRD2',
 'BRD3',
 'BRD4',
 'BRD7',
 'BRD8',
 'BRD9',
 'BRDT',
 'BRF1',
 'BRF2',
 'BRI3',
 'BRI3BP',
 'BRICD5',
 'BRINP1',
 'BRINP2',
 'BRINP3',
 'BRIP1',
 'BRIX1',
 'BRK1',
 'BRME1',
 'BRMS1',
 'BRMS1L',
 'BRPF1',
 'BRPF3',
 'BRS3',
 'BRSK1',
 'BRSK2',
 'BRWD1',
 'BRWD3',
 'BSCL2',
 'BSDC1',
 'BSG',
 'BSN',
 'BSND',
 'BSPH1',
 'BSPRY',
 'BST1',
 'BST2',
 'BSX',
 'BTAF1',
 'BTBD1',
 'BTBD10',
 'BTBD16',
 'BTBD17',
 'BTBD18',
 'BTBD19',
 'BTBD2',
 'BTBD3',
 'BTBD6',
 'BTBD7',
 'BTBD8',
 'BTBD9',
 'BTC',
 'BTD',
 'BTF3',
 'BTF3L4',
 'BTG1',
 'BTG2',
 'BTG3',
 'BTG4',
 'BTK',
 'BTLA',
 'BTN1A1',
 'BTN2A1',
 'BTN2A2',
 'BTN3A1',
 'BTN3A2',
 'BTN3A3',
 'BTNL2',
 'BTNL3',
 'BTNL8',
 'BTNL9',
 'BTRC',
 'BUB1',
 'BUB1B',
 'BUB3',
 'BUD13',
 'BUD23',
 'BUD31',
 'BVES',
 'BYSL',
 'BZW1',
 'BZW2',
 'C10ORF105',
 'C10ORF120',
 'C10ORF53',
 'C10ORF55',
 'C10ORF62',
 'C10ORF67',
 'C10ORF71',
 'C10ORF88',
 'C10ORF90',
 'C10ORF95',
 'C11ORF16',
 'C11ORF21',
 'C11ORF24',
 'C11ORF40',
 'C11ORF42',
 'C11ORF52',
 'C11ORF54',
 'C11ORF58',
 'C11ORF65',
 'C11ORF68',
 'C11ORF71',
 'C11ORF86',
 'C11ORF87',
 'C11ORF91',
 'C11ORF96',
 'C11ORF98',
 'C12ORF4',
 'C12ORF40',
 'C12ORF42',
 'C12ORF43',
 'C12ORF50',
 'C12ORF54',
 'C12ORF56',
 'C12ORF57',
 'C12ORF60',
 'C12ORF71',
 'C12ORF75',
 'C12ORF76',
 'C14ORF119',
 'C14ORF132',
 'C14ORF178',
 'C14ORF180',
 'C14ORF28',
 'C14ORF39',
 'C14ORF93',
 'C15ORF32',
 'C15ORF39',
 'C15ORF40',
 'C15ORF48',
 'C15ORF61',
 'C15ORF62',
 'C16ORF46',
 'C16ORF54',
 'C16ORF74',
 'C16ORF78',
 'C16ORF82',
 'C16ORF86',
 'C16ORF87',
 'C16ORF89',
 'C16ORF90',
 'C16ORF92',
 'C16ORF95',
 'C16ORF96',
 'C17ORF100',
 'C17ORF107',
 'C17ORF49',
 'C17ORF50',
 'C17ORF58',
 'C17ORF67',
 'C17ORF75',
 'C17ORF78',
 'C17ORF80',
 'C17ORF99',
 'C18ORF21',
 'C18ORF32',
 'C18ORF54',
 'C18ORF63',
 'C19ORF12',
 'C19ORF18',
 'C19ORF25',
 'C19ORF33',
 'C19ORF38',
 'C19ORF44',
 'C19ORF47',
 'C19ORF53',
 'C19ORF67',
 'C19ORF73',
 'C19ORF81',
 'C1D',
 'C1GALT1',
 'C1GALT1C1',
 'C1ORF105',
 'C1ORF115',
 'C1ORF116',
 'C1ORF122',
 'C1ORF127',
 'C1ORF131',
 'C1ORF141',
 'C1ORF146',
 'C1ORF159',
 'C1ORF162',
 'C1ORF167',
 'C1ORF174',
 'C1ORF185',
 'C1ORF198',
 'C1ORF21',
 'C1ORF210',
 'C1ORF216',
 'C1ORF226',
 'C1ORF35',
 'C1ORF43',
 'C1ORF50',
 'C1ORF52',
 'C1ORF53',
 'C1ORF54',
 'C1ORF56',
 'C1ORF74',
 'C1ORF87',
 'C1ORF94',
 'C1QA',
 'C1QB',
 'C1QBP',
 'C1QC',
 'C1QL1',
 'C1QL2',
 'C1QL3',
 'C1QL4',
 'C1QTNF1',
 'C1QTNF12',
 'C1QTNF2',
 'C1QTNF3',
 'C1QTNF4',
 'C1QTNF5',
 'C1QTNF6',
 'C1QTNF7',
 'C1QTNF8',
 'C1QTNF9',
 'C1QTNF9B',
 'C1R',
 'C1RL',
 'C1S',
 'C2',
 'C20ORF144',
 'C20ORF173',
 'C20ORF202',
 'C20ORF203',
 'C20ORF96',
 'C21ORF58',
 'C21ORF62',
 'C21ORF91',
 'C22ORF15',
 'C22ORF23',
 'C22ORF31',
 'C22ORF42',
 'C2CD2',
 'C2CD2L',
 'C2CD3',
 'C2CD4A',
 'C2CD4B',
 'C2CD4C',
 'C2CD4D',
 'C2CD5',
 'C2CD6',
 'C2ORF16',
 'C2ORF27A',
 'C2ORF42',
 'C2ORF49',
 'C2ORF50',
 'C2ORF66',
 'C2ORF68',
 'C2ORF69',
 'C2ORF72',
 'C2ORF73',
 'C2ORF74',
 'C2ORF76',
 'C2ORF78',
 'C2ORF80',
 'C2ORF81',
 'C2ORF83',
 'C2ORF88',
 'C3',
 'C3AR1',
 'C3ORF18',
 'C3ORF20',
 'C3ORF22',
 'C3ORF33',
 'C3ORF36',
 'C3ORF38',
 'C3ORF52',
 'C3ORF62',
 'C3ORF70',
 'C3ORF80',
 'C3ORF84',
 'C4BPA',
 'C4BPB',

### Standardise perturbation targets

In [19]:
cur_data.standardize_genes(
    slot='obs',
    input_column='input_perturbed_target_symbol',
    input_column_type='gene_symbol',
    multiple_entries=False
)

Mapping gene symbols:   0%|                                               | 0/18312 [00:00<?, ?it/s]

Mapping gene symbols:  16%|█████▏                           | 2880/18312 [00:00<00:00, 28795.56it/s]

Mapping gene symbols:  32%|██████████▍                      | 5772/18312 [00:00<00:00, 28867.19it/s]

Mapping gene symbols:  48%|███████████████▋                 | 8703/18312 [00:00<00:00, 29069.20it/s]

Mapping gene symbols:  64%|████████████████████▌           | 11735/18312 [00:00<00:00, 29561.71it/s]

Mapping gene symbols:  81%|█████████████████████████▉      | 14837/18312 [00:00<00:00, 30085.70it/s]

Mapping gene symbols:  97%|███████████████████████████████▏| 17846/18312 [00:00<00:00, 30013.22it/s]

Mapping gene symbols: 100%|████████████████████████████████| 18312/18312 [00:00<00:00, 29621.49it/s]

--------------------------------------------------
Successfully mapped 18307 out of 18312 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['LINC02911', 'PRY2', 'SMIM2', 'PRY', 'LINC02913']
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Add `perturbed_target_number` column

In [20]:
# cur_data.adata.obs = cur_data.adata.obs.iloc[:,[0,1,2,3,4,5,6,7,8,9,11,12,13]]

In [21]:
cur_data.count_entries(
    slot='obs',
    input_column='perturbed_target_coord',
    count_column_name='perturbed_target_number',
    sep='|'
)

Counted entries in column perturbed_target_coord of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [22]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

In [23]:
cur_data.show_obs(['perturbation_name', 'perturbed_target_chromosome_encoding'])

Observation data:
DataFrame shape: (4534299, 2)
--------------------------------------------------
                               perturbation_name  \
index
0                  FAM180A_P1P2-1|FAM180A_P1P2-2
1        non-targeting_03016|non-targeting_03214
2                  PCDHGC4_P1P2-1|PCDHGC4_P1P2-2
3                      USP30_P1P2-1|USP30_P1P2-2
4                      KLRD1_P1P2-1|KLRD1_P1P2-2
...                                          ...
4534294  non-targeting_00183|non-targeting_01885
4534295              AKAP13_P1P2-1|AKAP13_P1P2-2
4534296                  TTF2_P1P2-1|TTF2_P1P2-2
4534297                  MMP7_P1P2-1|MMP7_P1P2-2
4534298                  AAK1_P1P2-1|AAK1_P1P2-2

         perturbed_target_chromosome_encoding
index
0                                           7
1                                           0
2                                           5
3                                          12
4                                          12
...                                       ...
4534294                                     0
4534295                                    15
4534296                                     1
4534297                                    11
4534298                                     2

[4534299 rows x 2 columns]
--------------------------------------------------

In [24]:
cur_data.adata.obs.head()

,sample,input_perturbed_target_symbol,perturbation_name,cell_barcode,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding
index,,,,,,,,,,,,
0,HEK293T_Batch1,FAM180A,FAM180A_P1P2-1|FAM180A_P1P2-2,AAACCAAAGAAGTAGC-HEK293T_Batch1,ENSG00000189320,FAM180A,protein_coding,chr7:135728348-135748813;-1,7,AAACCAAAGAAGTAGC-HEK293T_Batch1,1,7
1,HEK293T_Batch1,control_nontargeting,non-targeting_03016|non-targeting_03214,AAACCAAAGAGTACGG-HEK293T_Batch1,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,AAACCAAAGAGTACGG-HEK293T_Batch1,1,0
2,HEK293T_Batch1,PCDHGC4,PCDHGC4_P1P2-1|PCDHGC4_P1P2-2,AAACCAAAGAGTGGGC-HEK293T_Batch1,ENSG00000242419,PCDHGC4,protein_coding,chr5:141484997-141512975;1,5,AAACCAAAGAGTGGGC-HEK293T_Batch1,1,5
3,HEK293T_Batch1,USP30,USP30_P1P2-1|USP30_P1P2-2,AAACCAAAGAGTGTAA-HEK293T_Batch1,ENSG00000135093,USP30,protein_coding,chr12:109023089-109088023;1,12,AAACCAAAGAGTGTAA-HEK293T_Batch1,1,12
4,HEK293T_Batch1,KLRD1,KLRD1_P1P2-1|KLRD1_P1P2-2,AAACCAAAGATACGGG-HEK293T_Batch1,ENSG00000134539,KLRD1,protein_coding,chr12:10226058-10329608;1,12,AAACCAAAGATACGGG-HEK293T_Batch1,1,12

### Add guide RNA information

The original pre-print does not contain information about guide RNAs in the `obs` slot.

However, the pre-print references the source of the library - [Maximizing CRISPRi efficacy and accessibility with dual-sgRNA libraries and optimal effectors. Replogle et al 2022](https://doi.org/10.7554/eLife.81856).

Supplementary table s4 contains the information about guide RNAs used in the experiment:

Supplementary table S4: https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvODE4NTYvZWxpZmUtODE4NTYtc3VwcDQtdjIueGxzeA--/elife-81856-supp4-v2.xlsx?_hash=AmEXp%2BOl1z1Y4JCBAaVhST5ImQmKAGdfEjGhuJbSJ9Q%3D

In [25]:
cur_data.gene_ont[["synonym", "gene_symbol"]].drop_duplicates()

                    synonym         gene_symbol
0                      None                None
1                     LSAMP               LSAMP
2                      KNL1                KNL1
5                 LINC02000           LINC02000
7                  KRT18P53            KRT18P53
...                     ...                 ...
1039922         control_gsh         control_gsh
1039923  control_genedesert  control_genedesert
1039924    control_positive    control_positive
1039925   control_guideonly   control_guideonly
1039926     control_casonly     control_casonly

[540548 rows x 2 columns]

In [26]:
# get synonyms from the gene ontology
syn_df = cur_data.gene_ont[["synonym", "gene_symbol"]].drop_duplicates()
syn_df["gene_symbol"] = syn_df["gene_symbol"].fillna("")
syn_df["synonym"] = syn_df["synonym"].fillna("")
syn_df["all_genes"] = (
    (syn_df["gene_symbol"] + "|" + syn_df["synonym"]).str.lstrip("|").str.rstrip("|")
)
syn_df["all_genes_match"] = syn_df["all_genes"].str.split("|")
syn_df = syn_df.explode("all_genes_match")
syn_df["all_genes_match"] = syn_df["all_genes_match"].str.upper()

# read data from supplementary files
guide_ids_df = pd.read_csv(
    "../supplementary/orion_2025_weissman_dual_crispri_sgrnas.csv"
)
guide_ids_df["gene"] = guide_ids_df["gene"].str.upper()

guide_ids_df = guide_ids_df.merge(
    syn_df, left_on="gene", right_on="all_genes_match", how="left"
)

guide_ids_df["all_genes"] = guide_ids_df["all_genes"].str.split("|")
guide_ids_df = guide_ids_df.explode("all_genes").drop_duplicates()

# create a perturbation name column
guide_ids_df["perturbation_name"] = (
    guide_ids_df["all_genes"]
    + "_"
    + guide_ids_df["transcript"]
    + "|"
    + guide_ids_df["all_genes"]
    + "_"
    + guide_ids_df["transcript"]
)

guide_ids_df["perturbation_name"] = guide_ids_df["perturbation_name"].str.upper()

# replace commas with underscores in the perturbation name
guide_ids_df["perturbation_name"] = guide_ids_df["perturbation_name"].str.replace(
    ",", "_"
)

# create a dual guide RNA sequence column
guide_ids_df["dual_guide_sequence"] = (
    guide_ids_df["protospacer_A"] + "|" + guide_ids_df["protospacer_B"]
).str.upper()

guide_ids_df.loc[
    guide_ids_df["all_genes"].isna() & guide_ids_df["gene"].notna(), "perturbation_name"
] = (
    guide_ids_df.loc[
        guide_ids_df["all_genes"].isna() & guide_ids_df["gene"].notna(), "gene"
    ]
    + "_"
    + guide_ids_df.loc[
        guide_ids_df["all_genes"].isna() & guide_ids_df["gene"].notna(), "transcript"
    ]
    + "|"
    + guide_ids_df.loc[
        guide_ids_df["all_genes"].isna() & guide_ids_df["gene"].notna(), "gene"
    ]
    + "_"
    + guide_ids_df.loc[
        guide_ids_df["all_genes"].isna() & guide_ids_df["gene"].notna(), "transcript"
    ]
)

# replace NEGATIVE_CONTROL with actual non targeting guide names
guide_ids_df.loc[guide_ids_df["gene"] == "NEGATIVE_CONTROL", "perturbation_name"] = (
    guide_ids_df.loc[guide_ids_df["gene"] == "NEGATIVE_CONTROL", "sgID_AB"].str.upper()
)

# create dictionaries for guide sequences mapping
guide_ids_dict = (
    guide_ids_df[["perturbation_name", "dual_guide_sequence"]]
    .dropna()
    .drop_duplicates()
    .set_index("perturbation_name")["dual_guide_sequence"]
    .to_dict()
)

# add guide sequences to the obs dataframe
obj_df = cur_data.adata.obs.copy()

# remove the numeric suffices from the perturbation names
obj_df["perturbation_name_matching"] = obj_df["perturbation_name"].str.replace(
    r"-\d(?=\||$)", "", regex=True
)
obj_df["perturbation_name_matching"] = obj_df["perturbation_name_matching"].str.upper()

# map the guide sequences to the perturbation names
obj_df["guide_sequence"] = obj_df["perturbation_name_matching"].map(guide_ids_dict)

obj_df = obj_df[["guide_sequence"]]

obj_df

                                    guide_sequence
index
0        GGAGAGCGTCAAATGAAGAG|GGAGGCTGAAGGCTGCGTCC
1        GGAGGCTATCTGCTAGACTT|GTCCACATGCGGATAGACAC
2        GGGCCGAACCGCGCCAGAGC|GCGACCGAGAGGCACTGTGT
3        GTGCCGAAGAGGCCGGGACC|GACGACGGTTCCCGAGACAG
4        GATGTTCTTGAATCATCTAT|GGGTTCCTGGAACACTTCAG
...                                            ...
4534294  GGGGGAATCTGCAAGACCAT|GAGAAGGAGCGAGGCTAAAG
4534295  GGAGCACAGGCGCTTCACCG|GGGCAGTCTCGGCAGAGCAC
4534296  GAAGTTAGGTGTCCAGAGCA|GAGGTGTCCAGAGCACGGTA
4534297  GCTCCCGCCTCCTGAGGCAG|GTCCACTGCAATGCTAACAT
4534298  GGGCCTGCGACGCAGAGAAG|GCTGCGACGCAGAGAAGAGG

[4534299 rows x 1 columns]

In [27]:
# merge guide sequences with main
cur_data.adata.obs = cur_data.adata.obs.merge(
    obj_df,
    left_index=True,
    right_index=True,
    how="left",
)

cur_data.adata.obs

,sample,input_perturbed_target_symbol,perturbation_name,cell_barcode,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding,guide_sequence
index,,,,,,,,,,,,,
0,HEK293T_Batch1,FAM180A,FAM180A_P1P2-1|FAM180A_P1P2-2,AAACCAAAGAAGTAGC-HEK293T_Batch1,ENSG00000189320,FAM180A,protein_coding,chr7:135728348-135748813;-1,7,AAACCAAAGAAGTAGC-HEK293T_Batch1,1,7,GGAGAGCGTCAAATGAAGAG|GGAGGCTGAAGGCTGCGTCC
1,HEK293T_Batch1,control_nontargeting,non-targeting_03016|non-targeting_03214,AAACCAAAGAGTACGG-HEK293T_Batch1,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,AAACCAAAGAGTACGG-HEK293T_Batch1,1,0,GGAGGCTATCTGCTAGACTT|GTCCACATGCGGATAGACAC
2,HEK293T_Batch1,PCDHGC4,PCDHGC4_P1P2-1|PCDHGC4_P1P2-2,AAACCAAAGAGTGGGC-HEK293T_Batch1,ENSG00000242419,PCDHGC4,protein_coding,chr5:141484997-141512975;1,5,AAACCAAAGAGTGGGC-HEK293T_Batch1,1,5,GGGCCGAACCGCGCCAGAGC|GCGACCGAGAGGCACTGTGT
3,HEK293T_Batch1,USP30,USP30_P1P2-1|USP30_P1P2-2,AAACCAAAGAGTGTAA-HEK293T_Batch1,ENSG00000135093,USP30,protein_coding,chr12:109023089-109088023;1,12,AAACCAAAGAGTGTAA-HEK293T_Batch1,1,12,GTGCCGAAGAGGCCGGGACC|GACGACGGTTCCCGAGACAG
4,HEK293T_Batch1,KLRD1,KLRD1_P1P2-1|KLRD1_P1P2-2,AAACCAAAGATACGGG-HEK293T_Batch1,ENSG00000134539,KLRD1,protein_coding,chr12:10226058-10329608;1,12,AAACCAAAGATACGGG-HEK293T_Batch1,1,12,GATGTTCTTGAATCATCTAT|GGGTTCCTGGAACACTTCAG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4534294,HEK293T_Batch223,control_nontargeting,non-targeting_00183|non-targeting_01885,GTTGTCCGTGGGATGG-HEK293T_Batch223,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,GTTGTCCGTGGGATGG-HEK293T_Batch223,1,0,GGGGGAATCTGCAAGACCAT|GAGAAGGAGCGAGGCTAAAG
4534295,HEK293T_Batch223,AKAP13,AKAP13_P1P2-1|AKAP13_P1P2-2,GTTGTCTTCAACAGCC-HEK293T_Batch223,ENSG00000170776,AKAP13,protein_coding,chr15:85380571-85749358;1,15,GTTGTCTTCAACAGCC-HEK293T_Batch223,1,15,GGAGCACAGGCGCTTCACCG|GGGCAGTCTCGGCAGAGCAC
4534296,HEK293T_Batch223,TTF2,TTF2_P1P2-1|TTF2_P1P2-2,GTTGTCTTCAGTACTG-HEK293T_Batch223,ENSG00000116830,TTF2,protein_coding,chr1:117060294-117107453;1,1,GTTGTCTTCAGTACTG-HEK293T_Batch223,1,1,GAAGTTAGGTGTCCAGAGCA|GAGGTGTCCAGAGCACGGTA
4534297,HEK293T_Batch223,MMP7,MMP7_P1P2-1|MMP7_P1P2-2,GTTGTCTTCCGCCGTT-HEK293T_Batch223,ENSG00000137673,MMP7,protein_coding,chr11:102520508-102530853;-1,11,GTTGTCTTCCGCCGTT-HEK293T_Batch223,1,11,GCTCCCGCCTCCTGAGGCAG|GTCCACTGCAATGCTAACAT
4534298,HEK293T_Batch223,AAK1,AAK1_P1P2-1|AAK1_P1P2-2,GTTGTGCAGGCTTGCG-HEK293T_Batch223,ENSG00000115977,AAK1,protein_coding,chr2:69457997-69674349;-1,2,GTTGTGCAGGCTTGCG-HEK293T_Batch223,1,2,GGGCCTGCGACGCAGAGAAG|GCTGCGACGCAGAGAAGAGG

### Add metadata

In [28]:
cur_data.create_columns(
    slot="obs",
    overwrite=True,
    col_dict={
        "dataset_id": cur_data.dataset_id,
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        # treatment
        "treatment_label": None,
        "treatment_id": None,
        # perturbation type
        "perturbation_type_label": "CRISPRi",
        "perturbation_type_id": None,
        # model system
        "model_system_label": "cell_line",
        "model_system_id": None,

        "data_modality": "Perturb-seq",
        "significant": None,
        "significance_criteria": None,
        "score_interpretation": None,

        # replicates
        "technical_replicate": None,
        "biological_replicate": None,

        'tissue': 'kidney',
        'cell_type': 'kidney epithelial cell',
        'cell_line': 'HEK293T cell',
        "timepoint": "P0DT0H0M0S",
        'disease_label': 'healthy',
        'disease_id':None,

        "species": "Homo sapiens",
        "sex_label": "female",
        "sex_id": None,
        "developmental_stage_label": "embryonic",
        "developmental_stage_id": None,

        "study_title": "X-Atlas/Orion: Genome-wide Perturb-seq Datasets via a Scalable Fix-Cryopreserve Platform for Training Dose-Dependent Biological Foundation Models",
        "study_uri": "https://doi.org/10.1101/2025.06.11.659105",
        "study_year": 2025,
        "first_author": "Ann Huang",
        "last_author": "Ci Chu",

        "experiment_title": "Over 4.5 million HEK293T cells were transfected with dual gRNAs targeting the same gene, and whole genome CRISPRi Perturb-seq was performed.",
        "experiment_summary": "The researchers developed the Fix-Cryopreserve-ScRNAseq (FiCS) Perturb-seq platform to enable scalable and reproducible genome-wide perturbation screening in human cell lines. Using this platform, they generated a genome-wide dual-guide CRISPRi Perturb-seq dataset in HEK293T cells. The dataset includes over 4.5 million deeply sequenced cells, with each cell yielding over 16,000 unique molecular identifiers (UMIs).",
        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],

        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",

        "library_generation_method_id": "EFO:0022895",
        "library_generation_method_label": "dCas9-KRAB",

        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "nanoparticle-mediated transfection",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",

        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",

        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",

        "library_name": "custom",
        "library_uri": None,

        "library_format_id": None,
        "library_format_label": "pooled",

        "library_scope_id": None,
        "library_scope_label": "genome-wide",

        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "inhibition",

        "library_manufacturer": "Weissman",
        "library_lentiviral_generation": "3",
        "library_grnas_per_target": "2",
        "library_total_grnas": "20845",
        "library_total_variants": None,

        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",

        "readout_type_id": None,
        "readout_type_label": "transcriptomic",

        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",

        "method_name_id": None,
        "method_name_label": "Perturb-seq",

        "method_uri": None,

        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "10x Genomics Chromium GEM-X Single Cell 5-prime kit v3",

        "sequencing_platform_id": None,
        "sequencing_platform_label": "Illumina NovaSeq X Plus",

        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",

        "software_counts_id": None,
        "software_counts_label": "CellRanger",

        "software_analysis_id": None,
        "software_analysis_label": "custom",

        "reference_genome_id": None,
        "reference_genome_label": "GRCh38",

        "license_label": "CC BY-NC-SA 4.0",
        "license_id": "SWO:1000090",

        "associated_datasets": json.dumps([
            {
                "dataset_accession": "HEK293T_filtered_dual_guide_cells",
                "dataset_uri": "https://plus.figshare.com/ndownloader/files/55074802",
                "dataset_description": "Filtered raw counts",
                "dataset_file_name": "HEK293T_filtered_dual_guide_cells.h5ad",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column treatment_label added to adata.obs
Column treatment_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Column tissue added to adata.obs
Column cell_type added to adata.obs

Column cell_line added to adata.obs
Column timepoint added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs

Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs

Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs

Column library_manufacturer added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs

Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs

Column associated_datasets added to adata.obs

In [29]:
cur_data.adata.obs

,sample,input_perturbed_target_symbol,perturbation_name,cell_barcode,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,...,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,reference_genome_id,reference_genome_label,license_label,license_id,associated_datasets
index,,,,,,,,,,,,,,,,,,,,,
0,HEK293T_Batch1,FAM180A,FAM180A_P1P2-1|FAM180A_P1P2-2,AAACCAAAGAAGTAGC-HEK293T_Batch1,ENSG00000189320,FAM180A,protein_coding,chr7:135728348-135748813;-1,7,AAACCAAAGAAGTAGC-HEK293T_Batch1,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
1,HEK293T_Batch1,control_nontargeting,non-targeting_03016|non-targeting_03214,AAACCAAAGAGTACGG-HEK293T_Batch1,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,AAACCAAAGAGTACGG-HEK293T_Batch1,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
2,HEK293T_Batch1,PCDHGC4,PCDHGC4_P1P2-1|PCDHGC4_P1P2-2,AAACCAAAGAGTGGGC-HEK293T_Batch1,ENSG00000242419,PCDHGC4,protein_coding,chr5:141484997-141512975;1,5,AAACCAAAGAGTGGGC-HEK293T_Batch1,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
3,HEK293T_Batch1,USP30,USP30_P1P2-1|USP30_P1P2-2,AAACCAAAGAGTGTAA-HEK293T_Batch1,ENSG00000135093,USP30,protein_coding,chr12:109023089-109088023;1,12,AAACCAAAGAGTGTAA-HEK293T_Batch1,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
4,HEK293T_Batch1,KLRD1,KLRD1_P1P2-1|KLRD1_P1P2-2,AAACCAAAGATACGGG-HEK293T_Batch1,ENSG00000134539,KLRD1,protein_coding,chr12:10226058-10329608;1,12,AAACCAAAGATACGGG-HEK293T_Batch1,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4534294,HEK293T_Batch223,control_nontargeting,non-targeting_00183|non-targeting_01885,GTTGTCCGTGGGATGG-HEK293T_Batch223,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,GTTGTCCGTGGGATGG-HEK293T_Batch223,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
4534295,HEK293T_Batch223,AKAP13,AKAP13_P1P2-1|AKAP13_P1P2-2,GTTGTCTTCAACAGCC-HEK293T_Batch223,ENSG00000170776,AKAP13,protein_coding,chr15:85380571-85749358;1,15,GTTGTCTTCAACAGCC-HEK293T_Batch223,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
4534296,HEK293T_Batch223,TTF2,TTF2_P1P2-1|TTF2_P1P2-2,GTTGTCTTCAGTACTG-HEK293T_Batch223,ENSG00000116830,TTF2,protein_coding,chr1:117060294-117107453;1,1,GTTGTCTTCAGTACTG-HEK293T_Batch223,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
4534297,HEK293T_Batch223,MMP7,MMP7_P1P2-1|MMP7_P1P2-2,GTTGTCTTCCGCCGTT-HEK293T_Batch223,ENSG00000137673,MMP7,protein_coding,chr11:102520508-102530853;-1,11,GTTGTCTTCCGCCGTT-HEK293T_Batch223,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."
4534298,HEK293T_Batch223,AAK1,AAK1_P1P2-1|AAK1_P1P2-2,GTTGTGCAGGCTTGCG-HEK293T_Batch223,ENSG00000115977,AAK1,protein_coding,chr2:69457997-69674349;-1,2,GTTGTGCAGGCTTGCG-HEK293T_Batch223,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY-NC-SA 4.0,SWO:1000090,"[{""dataset_accession"": ""HEK293T_filtered_dual_..."

### Curate replicate information

In [30]:
cur_data.adata.obs['technical_replicate'] = cur_data.adata.obs['sample'].astype(str)

### Curate tissue information

In [31]:

cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower     ontology_id
0       kidney             kidney     kidney  UBERON:0002113
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [32]:
cur_data.standardize_ontology(
    input_column='cell_type',
    column_type='term_name',
    ontology_type='cell_type'
)

Mapped 1 cell_type ontology terms from `cell_type` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
             input_column      input_column_lower              name_lower  \
0  kidney epithelial cell  kidney epithelial cell  kidney epithelial cell

  ontology_id
0  CL:0002518
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell line information

In [33]:
cur_data.standardize_ontology(
    input_column='cell_line',
    column_type='term_name',
    ontology_type='cell_line'
)

Mapped 1 cell_line ontology terms from `cell_line` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
   input_column input_column_lower    name_lower  ontology_id
0  HEK293T cell       hek293t cell  hek293t cell  CLO:0037372
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [34]:
cur_data.standardize_ontology(
    input_column='disease_label',
    column_type='term_name',
    ontology_type='disease'
)

Warning: No disease ontology terms could be mapped from `disease_label` column to ontology terms. Map the terms manually or check the input column for errors.

### Match schema column order

In [35]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [36]:
sch = ObsSchema.to_schema()

for col in list(sch.columns.keys()):
    sch_subset = sch.select_columns([col])
    try:
        sch_subset.validate(cur_data.adata.obs[[col]], lazy=True)
        print(f"Validation successful for column {col}.")
    except Exception as e:
        print(f"Validation failed for column {col}: {e}")

Validation successful for column dataset_id.

Validation successful for column sample_id.

Validation successful for column cell_barcode.

Validation successful for column data_modality.

Validation successful for column significant.

Validation successful for column significance_criteria.
Validation successful for column perturbation_name.

Validation successful for column perturbed_target_coord.

Validation successful for column perturbed_target_chromosome.
Validation successful for column perturbed_target_chromosome_encoding.
Validation successful for column perturbed_target_number.

Validation successful for column perturbed_target_ensg.

Validation successful for column perturbed_target_symbol.

Validation successful for column perturbed_target_biotype.

Validation successful for column guide_sequence.

Validation successful for column perturbation_type_label.

Validation successful for column perturbation_type_id.

Validation successful for column timepoint.

Validation successful for column treatment_label.

Validation successful for column treatment_id.

Validation successful for column technical_replicate.

Validation successful for column biological_replicate.

Validation successful for column model_system_label.

Validation successful for column model_system_id.

Validation successful for column species.

Validation successful for column tissue_label.

Validation successful for column tissue_id.

Validation successful for column cell_type_label.

Validation successful for column cell_type_id.

Validation successful for column cell_line_label.

Validation successful for column cell_line_id.

Validation successful for column sex_label.

Validation successful for column sex_id.

Validation successful for column developmental_stage_label.

Validation successful for column developmental_stage_id.

Validation successful for column disease_label.

Validation successful for column disease_id.

Validation successful for column study_title.

Validation successful for column study_uri.
Validation successful for column study_year.

Validation successful for column first_author.

Validation successful for column last_author.

Validation successful for column experiment_title.

Validation successful for column experiment_summary.

Validation successful for column number_of_perturbed_targets.

Validation successful for column number_of_perturbed_samples.

Validation successful for column library_generation_type_id.

Validation successful for column library_generation_type_label.

Validation successful for column library_generation_method_id.

Validation successful for column library_generation_method_label.

Validation successful for column enzyme_delivery_method_id.

Validation successful for column enzyme_delivery_method_label.

Validation successful for column library_delivery_method_id.

Validation successful for column library_delivery_method_label.

Validation successful for column enzyme_integration_state_id.

Validation successful for column enzyme_integration_state_label.

Validation successful for column library_integration_state_id.

Validation successful for column library_integration_state_label.

Validation successful for column enzyme_expression_control_id.

Validation successful for column enzyme_expression_control_label.

Validation successful for column library_expression_control_id.

Validation successful for column library_expression_control_label.

Validation successful for column library_name.

Validation successful for column library_uri.

Validation successful for column library_format_id.

Validation successful for column library_format_label.

Validation successful for column library_scope_id.

Validation successful for column library_scope_label.

Validation successful for column library_perturbation_type_id.

Validation successful for column library_perturbation_type_label.

Validation successful for column library_manufacturer.

Validation successful for column library_lentiviral_generation.

Validation successful for column library_grnas_per_target.

Validation successful for column library_total_grnas.
Validation failed for column library_total_variants: {
    "SCHEMA": {
        "WRONG_DATATYPE": [
            {
                "schema": "ObsSchema",
                "column": "library_total_variants",
                "check": "dtype('int64')",
                "error": "expected series 'library_total_variants' to have type int64, got object"
            }
        ]
    }
}

Validation successful for column readout_dimensionality_id.

Validation successful for column readout_dimensionality_label.

Validation successful for column readout_type_id.

Validation successful for column readout_type_label.

Validation successful for column readout_technology_id.

Validation successful for column readout_technology_label.

Validation successful for column method_name_id.

Validation successful for column method_name_label.

Validation successful for column method_uri.

Validation successful for column sequencing_library_kit_id.

Validation successful for column sequencing_library_kit_label.

Validation successful for column sequencing_platform_id.

Validation successful for column sequencing_platform_label.

Validation successful for column sequencing_strategy_id.

Validation successful for column sequencing_strategy_label.

Validation successful for column software_counts_id.

Validation successful for column software_counts_label.

Validation successful for column software_analysis_id.

Validation successful for column software_analysis_label.

Validation successful for column score_interpretation.

Validation successful for column reference_genome_id.

Validation successful for column reference_genome_label.

Validation successful for column associated_datasets.

Validation successful for column license_label.

Validation successful for column license_id.

In [37]:
# cur_data.validate_data(slot='obs')

# VAR slot curation

### Standardise genes

In [38]:
cur_data.show_var()

Variable data:
DataFrame shape: (38606, 1)
--------------------------------------------------
                     gene_symbol
DDX11L2                  DDX11L2
MIR1302-2HG          MIR1302-2HG
FAM138A                  FAM138A
ENSG00000290826  ENSG00000290826
OR4F5                      OR4F5
...                          ...
ENSG00000277836  ENSG00000277836
ENSG00000278633  ENSG00000278633
ENSG00000276017  ENSG00000276017
ENSG00000278817  ENSG00000278817
ENSG00000277196  ENSG00000277196

[38606 rows x 1 columns]
--------------------------------------------------

In [39]:
cur_data.adata.var['ensembl_inputs'] = [e if e.startswith('ENSG') else None for e in cur_data.adata.var.index]
cur_data.adata.var['gene_inputs'] = [e if not e.startswith('ENSG') else '' for e in cur_data.adata.var.index]

var_df = cur_data.adata.var.copy()

In [40]:
var_df

                     gene_symbol   ensembl_inputs  gene_inputs
DDX11L2                  DDX11L2             None      DDX11L2
MIR1302-2HG          MIR1302-2HG             None  MIR1302-2HG
FAM138A                  FAM138A             None      FAM138A
ENSG00000290826  ENSG00000290826  ENSG00000290826
OR4F5                      OR4F5             None        OR4F5
...                          ...              ...          ...
ENSG00000277836  ENSG00000277836  ENSG00000277836
ENSG00000278633  ENSG00000278633  ENSG00000278633
ENSG00000276017  ENSG00000276017  ENSG00000276017
ENSG00000278817  ENSG00000278817  ENSG00000278817
ENSG00000277196  ENSG00000277196  ENSG00000277196

[38606 rows x 3 columns]

In [41]:
cur_data.create_columns(slot='var', col_dict={
    'genes':cur_data.adata.var.index
})

Column genes added to adata.var

In [42]:
cur_data.standardize_genes(
    slot="var", input_column="gene_inputs", input_column_type="gene_symbol"
)
var_symb = cur_data.adata.var.copy()

Mapping gene symbols:   0%|                                               | 0/25645 [00:00<?, ?it/s]

Mapping gene symbols:  10%|███▏                             | 2469/25645 [00:00<00:00, 24592.05it/s]

Mapping gene symbols:  20%|██████▍                          | 5048/25645 [00:00<00:00, 25293.96it/s]

Mapping gene symbols:  30%|█████████▉                       | 7748/25645 [00:00<00:00, 26068.12it/s]

Mapping gene symbols:  40%|█████████████▎                   | 10355/25645 [00:02<00:04, 3107.42it/s]

Mapping gene symbols:  50%|████████████████▍                | 12801/25645 [00:02<00:02, 4451.63it/s]

Mapping gene symbols:  61%|████████████████████             | 15627/25645 [00:02<00:01, 6416.02it/s]

Mapping gene symbols:  72%|███████████████████████▋         | 18414/25645 [00:02<00:00, 8675.31it/s]

Mapping gene symbols:  82%|██████████████████████████▏     | 21005/25645 [00:02<00:00, 10930.54it/s]

Mapping gene symbols:  93%|█████████████████████████████▌  | 23738/25645 [00:02<00:00, 13513.51it/s]

Mapping gene symbols: 100%|█████████████████████████████████| 25645/25645 [00:02<00:00, 8967.34it/s]

--------------------------------------------------
Successfully mapped 25586 out of 25645 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['', 'ARHGEF19-AS1', 'LYST-AS1', 'LINC01115-1', 'LINC01119', 'LSP1P5-1', 'LINC01889', 'UPP2-IT1', 'LINC01238-1', 'ARF4-AS1', 'DENND6A-AS1', 'PRICKLE2-AS1-1', 'SLC41A3-AS1', 'IFT122P3', 'LINC00886', 'LINC02263', 'TEMN3-AS1', 'CTD-2350J17.1', 'LINC02119', 'LINC01033', 'CTC-338M12.4', 'MIR5689HG', 'RAET1E-AS1-1', 'LINC03021-1', 'LINC03023-1', 'TNFRSF10A-DT-1', 'LINC01605-1', 'NCRNA00250', 'PTGER4P2-CDK2AP2P2', 'LINC03025-1', 'LINC00484-1', 'LINC02913', 'DNAJC9-AS1-1', 'LINC02722', 'LINC02398', 'GPR84-AS1-1', 'LINC02399', 'SPATA13-1', 'SMIM2', 'SMIM2-IT1', 'PCDH9-AS4', 'HIF1A-AS1', 'HIF1A-AS3', 'VASH1-AS1', 'GOLGA8M-1', 'LINC02256-1', 'LINC01580', 'DDX11L16-1', 'NPIPA9-1', 'LINC02911', 'MKKS-1', 'MKKS-2', 'D21S2088E', 'LINC01422', 'ELFN2-1', 'ARMCX5-GPRASP2-1', 'PRY2', 'PRY', 'MAFIP']
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [43]:
var_symb

,gene_inputs,genes,ensembl_inputs,ensembl_gene_id,gene_symbol,original_index
index,,,,,,
0,DDX11L2,DDX11L2,None,ENSG00000310539,DDX11L2,DDX11L2
1,MIR1302-2HG,MIR1302-2HG,None,ENSG00000243485,MIR1302-2HG,MIR1302-2HG
2,FAM138A,FAM138A,None,ENSG00000237613,FAM138A,FAM138A
3,,ENSG00000290826,ENSG00000290826,None,,ENSG00000290826
4,OR4F5,OR4F5,None,ENSG00000186092,OR4F5,OR4F5
...,...,...,...,...,...,...
38601,,ENSG00000277836,ENSG00000277836,None,,ENSG00000277836
38602,,ENSG00000278633,ENSG00000278633,None,,ENSG00000278633
38603,,ENSG00000276017,ENSG00000276017,None,,ENSG00000276017
38604,,ENSG00000278817,ENSG00000278817,None,,ENSG00000278817
38605,,ENSG00000277196,ENSG00000277196,None,,ENSG00000277196

In [44]:
cur_data.adata.var = var_df
cur_data.standardize_genes(
    slot="var", input_column="ensembl_inputs", input_column_type="ensembl_gene_id"
)
var_ensg = cur_data.adata.var.copy()

Missing Ensembl IDs: ['ENSG00000228255', 'ENSG00000242753', 'ENSG00000264660', 'ENSG00000271973', 'ENSG00000291188', 'ENSG00000260951', 'ENSG00000290593', 'ENSG00000258342', 'ENSG00000290407', 'ENSG00000289826', 'ENSG00000223795', 'ENSG00000287682', 'ENSG00000271904', 'ENSG00000265975', 'ENSG00000286466', 'ENSG00000258919', 'ENSG00000285933', 'ENSG00000290591', 'ENSG00000271156', 'ENSG00000230205', 'ENSG00000250101', 'ENSG00000270055', 'ENSG00000258600', 'ENSG00000267521', 'ENSG00000253671', 'ENSG00000291247', 'ENSG00000267399', 'ENSG00000232636', 'ENSG00000253115', 'ENSG00000272468', 'ENSG00000275557', 'ENSG00000272341', 'ENSG00000225790', 'ENSG00000290100', 'ENSG00000287702', 'ENSG00000284700', 'ENSG00000290818', 'ENSG00000286687', 'ENSG00000224481', 'ENSG00000261193', 'ENSG00000288810', 'ENSG00000233256', 'ENSG00000229881', 'ENSG00000283480', 'ENSG00000262089', 'ENSG00000287168', 'ENSG00000278633', 'ENSG00000249125', 'ENSG00000272218', 'ENSG00000288991', 'ENSG00000233970', 'ENSG00000250418', 'ENSG00000225655', 'ENSG00000261120', 'ENSG00000249166', 'ENSG00000272049', 'ENSG00000242396', 'ENSG00000255644', 'ENSG00000273486', 'ENSG00000291260', 'ENSG00000287564', 'ENSG00000227192', 'ENSG00000228421', 'ENSG00000291288', 'ENSG00000290514', 'ENSG00000267420', 'ENSG00000286016', 'ENSG00000277010', 'ENSG00000231616', 'ENSG00000285766', 'ENSG00000256001', 'ENSG00000283504', 'ENSG00000233193', 'ENSG00000263331', 'ENSG00000276867', 'ENSG00000284930', 'ENSG00000273481', 'ENSG00000290903', 'ENSG00000285660', 'ENSG00000272519', 'ENSG00000286080', 'ENSG00000287614', 'ENSG00000290974', 'ENSG00000288580', 'ENSG00000286499', 'ENSG00000278011', 'ENSG00000291299', 'ENSG00000254836', 'ENSG00000271792', 'ENSG00000253766', 'ENSG00000259616', 'ENSG00000286895', 'ENSG00000235242', 'ENSG00000288526', 'ENSG00000272650', 'ENSG00000267070', 'ENSG00000260071', 'ENSG00000258265', 'ENSG00000232325', 'ENSG00000256686', 'ENSG00000227917', 'ENSG00000290010', 'ENSG00000261159', 'ENSG00000270157', 'ENSG00000289635', 'ENSG00000269888', 'ENSG00000250670', 'ENSG00000289069', 'ENSG00000258216', 'ENSG00000223379', 'ENSG00000253256', 'ENSG00000264421', 'ENSG00000259582', 'ENSG00000288819', 'ENSG00000288772', 'ENSG00000266248', 'ENSG00000272732', 'ENSG00000286564', 'ENSG00000259604', 'ENSG00000259255', 'ENSG00000291259', 'ENSG00000236451', 'ENSG00000258092', 'ENSG00000288573', 'ENSG00000288850', 'ENSG00000267327', 'ENSG00000249604', 'ENSG00000271955', 'ENSG00000287523', 'ENSG00000289920', 'ENSG00000272872', 'ENSG00000272954', 'ENSG00000289590', 'ENSG00000257226', 'ENSG00000272085', 'ENSG00000233415', 'ENSG00000258386', 'ENSG00000287954', 'ENSG00000272444', 'ENSG00000235994', 'ENSG00000273211', 'ENSG00000241792', 'ENSG00000225489', 'ENSG00000265717', 'ENSG00000289512', 'ENSG00000244545', 'ENSG00000289467', 'ENSG00000272940', 'ENSG00000277501', 'ENSG00000286213', 'ENSG00000257322', 'ENSG00000237359', 'ENSG00000254927', 'ENSG00000261650', 'ENSG00000266490', 'ENSG00000234141', 'ENSG00000273119', 'ENSG00000255272', 'ENSG00000260060', 'ENSG00000251506', 'ENSG00000248753', 'ENSG00000233799', 'ENSG00000228503', 'ENSG00000286622', 'ENSG00000236948', 'ENSG00000227305', 'ENSG00000223808', 'ENSG00000286824', 'ENSG00000225836', 'ENSG00000225916', 'ENSG00000275063', 'ENSG00000260141', 'ENSG00000273138', 'ENSG00000286827', 'ENSG00000253960', 'ENSG00000263388', 'ENSG00000288950', 'ENSG00000267787', 'ENSG00000255599', 'ENSG00000285424', 'ENSG00000283003', 'ENSG00000288963', 'ENSG00000289619', 'ENSG00000286906', 'ENSG00000257277', 'ENSG00000286915', 'ENSG00000288808', 'ENSG00000259972', 'ENSG00000233029', 'ENSG00000270265', 'ENSG00000257715', 'ENSG00000289867', 'ENSG00000264212', 'ENSG00000287139', 'ENSG00000288554', 'ENSG00000289722', 'ENSG00000288565', 'ENSG00000249483', 'ENSG00000228648', 'ENSG00000243179', 'ENSG00000291107', 'ENSG00000286931', 'ENSG00000287557', 'ENSG00000248787', 'ENSG00000273374', 'ENSG00000235578', 'ENSG00000290594', 'ENSG00000291278', 'ENSG00000281920', 'ENSG00000274902', 'ENSG00000227920', 'ENSG00000270019', 'ENSG00000290029', 'ENSG00000286133', 'ENSG00000241317', 'ENSG00000254180', 'ENSG00000234698', 'ENSG00000254364', 'ENSG00000254420', 'ENSG00000287440', 'ENSG00000282863', 'ENSG00000250078', 'ENSG00000235795', 'ENSG00000290124', 'ENSG00000226079', 'ENSG00000225393', 'ENSG00000258345', 'ENSG00000253381', 'ENSG00000250284', 'ENSG00000267636', 'ENSG00000259126', 'ENSG00000253735', 'ENSG00000222022', 'ENSG00000262558', 'ENSG00000251314', 'ENSG00000257654', 'ENSG00000287569', 'ENSG00000267683', 'ENSG00000278817', 'ENSG00000278084', 'ENSG00000257194', 'ENSG00000291287', 'ENSG00000242021', 'ENSG00000276278', 'ENSG00000224884', 'ENSG00000236501', 'ENSG00000260052', 'ENSG00000231877', 'ENSG00000272583', 'ENSG00000204398', 'ENSG00000253484', 'ENSG00000261775', 'ENSG00000229458', 'ENSG00000271751', 'ENSG00000258642', 'ENSG00000288111', 'ENSG00000261720', 'ENSG00000253235', 'ENSG00000254695', 'ENSG00000290414', 'ENSG00000291291', 'ENSG00000272137', 'ENSG00000258473', 'ENSG00000255015', 'ENSG00000241180', 'ENSG00000203520', 'ENSG00000275869', 'ENSG00000231128', 'ENSG00000276790', 'ENSG00000288531', 'ENSG00000250567', 'ENSG00000241772', 'ENSG00000279159', 'ENSG00000290032', 'ENSG00000289184', 'ENSG00000263688', 'ENSG00000273181', 'ENSG00000234998', 'ENSG00000251679', 'ENSG00000250511', 'ENSG00000256732', 'ENSG00000289048', 'ENSG00000287350', 'ENSG00000254821', 'ENSG00000288954', 'ENSG00000286863', 'ENSG00000224525', 'ENSG00000287346', 'ENSG00000285535', 'ENSG00000286103', 'ENSG00000286534', 'ENSG00000261757', 'ENSG00000254744', 'ENSG00000285922', 'ENSG00000261135', 'ENSG00000265174', 'ENSG00000223469', 'ENSG00000268333', 'ENSG00000285759', 'ENSG00000229191', 'ENSG00000291246', 'ENSG00000291215', 'ENSG00000266908', 'ENSG00000286397', 'ENSG00000283517', 'ENSG00000260581', 'ENSG00000238009', 'ENSG00000291279', 'ENSG00000290856', 'ENSG00000253139', 'ENSG00000231255', 'ENSG00000276854', 'ENSG00000254138', 'ENSG00000267449', 'ENSG00000244620', 'ENSG00000266893', 'ENSG00000290183', 'ENSG00000255944', 'ENSG00000257879', 'ENSG00000290580', 'ENSG00000286919', 'ENSG00000233376', 'ENSG00000290440', 'ENSG00000286439', 'ENSG00000273765', 'ENSG00000249091', 'ENSG00000290680', 'ENSG00000290081', 'ENSG00000234540', 'ENSG00000230381', 'ENSG00000259166', 'ENSG00000290659', 'ENSG00000276251', 'ENSG00000260409', 'ENSG00000250060', 'ENSG00000291258', 'ENSG00000261218', 'ENSG00000251532', 'ENSG00000289524', 'ENSG00000250948', 'ENSG00000290510', 'ENSG00000289988', 'ENSG00000254651', 'ENSG00000289179', 'ENSG00000274652', 'ENSG00000286571', 'ENSG00000228334', 'ENSG00000263508', 'ENSG00000289563', 'ENSG00000290242', 'ENSG00000238158', 'ENSG00000269927', 'ENSG00000287248', 'ENSG00000287622', 'ENSG00000276345', 'ENSG00000291058', 'ENSG00000286262', 'ENSG00000255028', 'ENSG00000268810', 'ENSG00000237954', 'ENSG00000260100', 'ENSG00000258196', 'ENSG00000234810', 'ENSG00000237422', 'ENSG00000255479', 'ENSG00000287387', 'ENSG00000268509', 'ENSG00000233852', 'ENSG00000256923', 'ENSG00000289830', 'ENSG00000289486', 'ENSG00000263677', 'ENSG00000286329', 'ENSG00000258831', 'ENSG00000288816', 'ENSG00000235047', 'ENSG00000188525', 'ENSG00000228353', 'ENSG00000239216', 'ENSG00000290721', 'ENSG00000283648', 'ENSG00000248346', 'ENSG00000291055', 'ENSG00000289620', 'ENSG00000286472', 'ENSG00000232749', 'ENSG00000285622', 'ENSG00000283907', 'ENSG00000278704', 'ENSG00000287649', 'ENSG00000286087', 'ENSG00000251144', 'ENSG00000274444', 'ENSG00000235934', 'ENSG00000234677', 'ENSG00000277630', 'ENSG00000260095', 'ENSG00000273729', 'ENSG00000272922', 'ENSG00000258921', 'ENSG00000272009', 'ENSG00000286723', 'ENSG00000270016', 'ENSG00000272979', 'ENSG00000290066', 'ENSG00000260090', 'ENSG00000259274', 'ENSG00000259587', 'ENSG00000261470', 'ENSG00000248646', 'ENSG00000244650', 'ENSG00000287865', 'ENSG00000290384', 'ENSG00000289541', 'ENSG00000290449', 'ENSG00000232680', 'ENSG00000249008', 'ENSG00000287788', 'ENSG00000272971', 'ENSG00000261386', 'ENSG00000276269', 'ENSG00000265091', 'ENSG00000249708', 'ENSG00000286501', 'ENSG00000286603', 'ENSG00000241520', 'ENSG00000231883', 'ENSG00000291011', 'ENSG00000290709', 'ENSG00000244063', 'ENSG00000276348', 'ENSG00000254095', 'ENSG00000287386', 'ENSG00000272592', 'ENSG00000228538', 'ENSG00000287127', 'ENSG00000289082', 'ENSG00000260030', 'ENSG00000249463', 'ENSG00000287868', 'ENSG00000266957', 'ENSG00000233005', 'ENSG00000250158', 'ENSG00000287884', 'ENSG00000289840', 'ENSG00000237899', 'ENSG00000275636', 'ENSG00000272953', 'ENSG00000278514', 'ENSG00000278626', 'ENSG00000277196', 'ENSG00000287313', 'ENSG00000249492', 'ENSG00000286825', 'ENSG00000233408', 'ENSG00000246331', 'ENSG00000273363', 'ENSG00000271259', 'ENSG00000229912', 'ENSG00000261462', 'ENSG00000260183', 'ENSG00000251613', 'ENSG00000231140', 'ENSG00000258088', 'ENSG00000290396', 'ENSG00000267115', 'ENSG00000260517', 'ENSG00000253844', 'ENSG00000256542', 'ENSG00000289036', 'ENSG00000228561', 'ENSG00000289994', 'ENSG00000241280', 'ENSG00000284685', 'ENSG00000259209', 'ENSG00000254619', 'ENSG00000268615', 'ENSG00000290969', 'ENSG00000261222', 'ENSG00000257454', 'ENSG00000289917', 'ENSG00000290784', 'ENSG00000278107', 'ENSG00000244268', 'ENSG00000273554', 'ENSG00000273289', 'ENSG00000249335', 'ENSG00000226277', 'ENSG00000264334', 'ENSG00000270147', 'ENSG00000225058', 'ENSG00000249184', 'ENSG00000289531', 'ENSG00000286189', 'ENSG00000225643', 'ENSG00000287729', 'ENSG00000254039', 'ENSG00000256694', 'ENSG00000272736', 'ENSG00000248533', 'ENSG00000275249', 'ENSG00000238102', 'ENSG00000289135', 'ENSG00000256101', 'ENSG00000249159', 'ENSG00000289455', 'ENSG00000264790', 'ENSG00000286292', 'ENSG00000231212', 'ENSG00000274312', 'ENSG00000258302', 'ENSG00000282021', 'ENSG00000257711', 'ENSG00000289413', 'ENSG00000261445', 'ENSG00000289147', 'ENSG00000258918', 'ENSG00000289242', 'ENSG00000233906', 'ENSG00000264078', 'ENSG00000228008', 'ENSG00000272515', 'ENSG00000272240', 'ENSG00000233987', 'ENSG00000253985', 'ENSG00000287368', 'ENSG00000247810', 'ENSG00000287316', 'ENSG00000260983', 'ENSG00000289206', 'ENSG00000223675', 'ENSG00000286997', 'ENSG00000290101', 'ENSG00000248311', 'ENSG00000288982', 'ENSG00000272304', 'ENSG00000271788', 'ENSG00000286572', 'ENSG00000235271', 'ENSG00000239674', 'ENSG00000266588', 'ENSG00000257918', 'ENSG00000287875', 'ENSG00000253584', 'ENSG00000288002', 'ENSG00000276075', 'ENSG00000224228', 'ENSG00000254587', 'ENSG00000264080', 'ENSG00000229628', 'ENSG00000260163', 'ENSG00000289411', 'ENSG00000236856', 'ENSG00000287411', 'ENSG00000235852', 'ENSG00000277423', 'ENSG00000258844', 'ENSG00000229160', 'ENSG00000253444', 'ENSG00000224532', 'ENSG00000267643', 'ENSG00000226078', 'ENSG00000291342', 'ENSG00000286511', 'ENSG00000287858', 'ENSG00000290759', 'ENSG00000287400', 'ENSG00000254115', 'ENSG00000277400', 'ENSG00000225085', 'ENSG00000272382', 'ENSG00000287101', 'ENSG00000265671', 'ENSG00000267537', 'ENSG00000250046', 'ENSG00000288957', 'ENSG00000273748', 'ENSG00000287712', 'ENSG00000253842', 'ENSG00000288046', 'ENSG00000289905', 'ENSG00000214970', 'ENSG00000287263', 'ENSG00000273388', 'ENSG00000286633', 'ENSG00000224247', 'ENSG00000259123', 'ENSG00000255328', 'ENSG00000289142', 'ENSG00000236453', 'ENSG00000234296', 'ENSG00000233214', 'ENSG00000267243', 'ENSG00000249269', 'ENSG00000228113', 'ENSG00000258927', 'ENSG00000236938', 'ENSG00000269391', 'ENSG00000229151', 'ENSG00000289950', 'ENSG00000287843', 'ENSG00000233517', 'ENSG00000271911', 'ENSG00000287837', 'ENSG00000251454', 'ENSG00000228216', 'ENSG00000261797', 'ENSG00000274175', 'ENSG00000261273', 'ENSG00000259306', 'ENSG00000231173', 'ENSG00000268355', 'ENSG00000235337', 'ENSG00000288101', 'ENSG00000289448', 'ENSG00000255495', 'ENSG00000250431', 'ENSG00000236760', 'ENSG00000250360', 'ENSG00000239462', 'ENSG00000289315', 'ENSG00000276649', 'ENSG00000232386', 'ENSG00000290666', 'ENSG00000267388', 'ENSG00000250234', 'ENSG00000257603', 'ENSG00000272369', 'ENSG00000259407', 'ENSG00000290443', 'ENSG00000288972', 'ENSG00000286420', 'ENSG00000291290', 'ENSG00000289919', 'ENSG00000250481', 'ENSG00000224218', 'ENSG00000248991', 'ENSG00000249638', 'ENSG00000289307', 'ENSG00000261044', 'ENSG00000286462', 'ENSG00000234306', 'ENSG00000277999', 'ENSG00000290616', 'ENSG00000287492', 'ENSG00000229403', 'ENSG00000288583', 'ENSG00000287906', 'ENSG00000274792', 'ENSG00000287941', 'ENSG00000276256', 'ENSG00000290529', 'ENSG00000251654', 'ENSG00000290091', 'ENSG00000266450', 'ENSG00000286494', 'ENSG00000276760', 'ENSG00000289167', 'ENSG00000286374', 'ENSG00000223504', 'ENSG00000258885', 'ENSG00000287577', 'ENSG00000288889', 'ENSG00000237356', 'ENSG00000291272', 'ENSG00000270114', 'ENSG00000259038', 'ENSG00000286504', 'ENSG00000260511', 'ENSG00000270154', 'ENSG00000288754', 'ENSG00000283294', 'ENSG00000289194', 'ENSG00000251678', 'ENSG00000286475', 'ENSG00000253737', 'ENSG00000286778', 'ENSG00000255160', 'ENSG00000272316', 'ENSG00000263698', 'ENSG00000274828', 'ENSG00000261502', 'ENSG00000229454', 'ENSG00000272070', 'ENSG00000290828', 'ENSG00000230506', 'ENSG00000287708', 'ENSG00000232597', 'ENSG00000259594', 'ENSG00000273319', 'ENSG00000288019', 'ENSG00000286362', 'ENSG00000253762', 'ENSG00000279949', 'ENSG00000273733', 'ENSG00000288749', 'ENSG00000289862', 'ENSG00000277475', 'ENSG00000272465', 'ENSG00000276471', 'ENSG00000230649', 'ENSG00000253988', 'ENSG00000253197', 'ENSG00000251416', 'ENSG00000235215', 'ENSG00000248518', 'ENSG00000234405', 'ENSG00000285108', 'ENSG00000289321', 'ENSG00000287944', 'ENSG00000267406', 'ENSG00000261350', 'ENSG00000258028', 'ENSG00000264067', 'ENSG00000272030', 'ENSG00000285719', 'ENSG00000232692', 'ENSG00000235209', 'ENSG00000236839', 'ENSG00000225527', 'ENSG00000235450', 'ENSG00000286792', 'ENSG00000269072', 'ENSG00000258131', 'ENSG00000250310', 'ENSG00000259359', 'ENSG00000260182', 'ENSG00000249837', 'ENSG00000286164', 'ENSG00000285656', 'ENSG00000264072', 'ENSG00000235736', 'ENSG00000235815', 'ENSG00000287974', 'ENSG00000279987', 'ENSG00000290463', 'ENSG00000289255', 'ENSG00000291284', 'ENSG00000283255', 'ENSG00000290038', 'ENSG00000253891', 'ENSG00000289593', 'ENSG00000288789', 'ENSG00000286817', 'ENSG00000286978', 'ENSG00000259995', 'ENSG00000254306', 'ENSG00000253369', 'ENSG00000241770', 'ENSG00000285782', 'ENSG00000238358', 'ENSG00000286519', 'ENSG00000285155', 'ENSG00000289160', 'ENSG00000290412', 'ENSG00000267058', 'ENSG00000289465', 'ENSG00000282440', 'ENSG00000273123', 'ENSG00000214955', 'ENSG00000283164', 'ENSG00000289005', 'ENSG00000276017', 'ENSG00000237461', 'ENSG00000288574', 'ENSG00000286815', 'ENSG00000258949', 'ENSG00000258170', 'ENSG00000273203', 'ENSG00000254731', 'ENSG00000266614', 'ENSG00000226376', 'ENSG00000260780', 'ENSG00000256321', 'ENSG00000228156', 'ENSG00000261305', 'ENSG00000272564', 'ENSG00000282887', 'ENSG00000227029', 'ENSG00000232949', 'ENSG00000290905', 'ENSG00000267279', 'ENSG00000250777', 'ENSG00000231054', 'ENSG00000288788', 'ENSG00000273771', 'ENSG00000287361', 'ENSG00000268674', 'ENSG00000284602', 'ENSG00000269873', 'ENSG00000260487', 'ENSG00000239498', 'ENSG00000285584', 'ENSG00000288657', 'ENSG00000272840', 'ENSG00000272948', 'ENSG00000243176', 'ENSG00000283689', 'ENSG00000266601', 'ENSG00000287438', 'ENSG00000271254', 'ENSG00000230699', 'ENSG00000228434', 'ENSG00000249122', 'ENSG00000240401', 'ENSG00000290816', 'ENSG00000239407', 'ENSG00000291025', 'ENSG00000240240', 'ENSG00000287811', 'ENSG00000232056', 'ENSG00000229646', 'ENSG00000289614', 'ENSG00000290459', 'ENSG00000232034', 'ENSG00000254757', 'ENSG00000240996', 'ENSG00000254814', 'ENSG00000251652', 'ENSG00000270038', 'ENSG00000287798', 'ENSG00000251218', 'ENSG00000266002', 'ENSG00000259760', 'ENSG00000248359', 'ENSG00000287446', 'ENSG00000290958', 'ENSG00000236412', 'ENSG00000253859', 'ENSG00000262227', 'ENSG00000265964', 'ENSG00000248240', 'ENSG00000254290', 'ENSG00000289209', 'ENSG00000230090', 'ENSG00000273890', 'ENSG00000259423', 'ENSG00000286977', 'ENSG00000233342', 'ENSG00000260793', 'ENSG00000253400', 'ENSG00000273403', 'ENSG00000280273', 'ENSG00000287824', 'ENSG00000237262', 'ENSG00000223811', 'ENSG00000289636', 'ENSG00000285191', 'ENSG00000259762', 'ENSG00000259998', 'ENSG00000283886', 'ENSG00000254143', 'ENSG00000290078', 'ENSG00000232294', 'ENSG00000285877', 'ENSG00000288581', 'ENSG00000231979', 'ENSG00000287176', 'ENSG00000278266', 'ENSG00000288904', 'ENSG00000259222', 'ENSG00000258631', 'ENSG00000257183', 'ENSG00000286854', 'ENSG00000290004', 'ENSG00000263081', 'ENSG00000263316', 'ENSG00000275232', 'ENSG00000286755', 'ENSG00000272482', 'ENSG00000240355', 'ENSG00000263574', 'ENSG00000290884', 'ENSG00000258407', 'ENSG00000227683', 'ENSG00000249731', 'ENSG00000288806', 'ENSG00000267131', 'ENSG00000290843', 'ENSG00000267105', 'ENSG00000277901', 'ENSG00000232754', 'ENSG00000291298', 'ENSG00000286293', 'ENSG00000249984', 'ENSG00000289600', 'ENSG00000228478', 'ENSG00000233536', 'ENSG00000272541', 'ENSG00000269986', 'ENSG00000278878', 'ENSG00000277856', 'ENSG00000250237', 'ENSG00000253872', 'ENSG00000234902', 'ENSG00000286330', 'ENSG00000243944', 'ENSG00000286542', 'ENSG00000226849', 'ENSG00000236716', 'ENSG00000229964', 'ENSG00000274367', 'ENSG00000260470', 'ENSG00000224342', 'ENSG00000244260', 'ENSG00000286889', 'ENSG00000224819', 'ENSG00000234223', 'ENSG00000280767', 'ENSG00000290697', 'ENSG00000265943', 'ENSG00000251379', 'ENSG00000277559', 'ENSG00000260759', 'ENSG00000234134', 'ENSG00000255945', 'ENSG00000251399', 'ENSG00000289122', 'ENSG00000263588', 'ENSG00000288553', 'ENSG00000278923', 'ENSG00000287211', 'ENSG00000278384', 'ENSG00000276631', 'ENSG00000286599', 'ENSG00000263443', 'ENSG00000286351', 'ENSG00000276250', 'ENSG00000250415', 'ENSG00000241912', 'ENSG00000242375', 'ENSG00000256739', 'ENSG00000224621', 'ENSG00000286941', 'ENSG00000257962', 'ENSG00000288896', 'ENSG00000235111', 'ENSG00000280366', 'ENSG00000248103', 'ENSG00000289176', 'ENSG00000291273', 'ENSG00000236263', 'ENSG00000255325', 'ENSG00000283633', 'ENSG00000285769', 'ENSG00000277836', 'ENSG00000289975', 'ENSG00000255817', 'ENSG00000255279', 'ENSG00000230600', 'ENSG00000291026', 'ENSG00000267316', 'ENSG00000258772', 'ENSG00000272755', 'ENSG00000234083', 'ENSG00000259376', 'ENSG00000289958', 'ENSG00000234936', 'ENSG00000240440', 'ENSG00000249988', 'ENSG00000254028', 'ENSG00000258081', 'ENSG00000286111', 'ENSG00000236129', 'ENSG00000253774', 'ENSG00000253805', 'ENSG00000290105', 'ENSG00000241475', 'ENSG00000267081', 'ENSG00000290872', 'ENSG00000250957', 'ENSG00000253983', 'ENSG00000259730', 'ENSG00000289084', 'ENSG00000288986', 'ENSG00000288055', 'ENSG00000131484', 'ENSG00000244349', 'ENSG00000289329', 'ENSG00000286911', 'ENSG00000262039', 'ENSG00000291048', 'ENSG00000249684', 'ENSG00000289008', 'ENSG00000232411', 'ENSG00000286761']; attempting to fetch latest IDs...
986 unmapped ENSG IDs identified; splitting into chunks of 500.
Processing IDs 1 to 500...

Processing IDs 501 to 986...

Fetched latest Ensembl IDs: {'ENSG00000228255': 'ENSG00000225233', 'ENSG00000242753': 'ENSG00000233656', 'ENSG00000264660': 'ENSG00000233098', 'ENSG00000271973': 'ENSG00000228350', 'ENSG00000291188': 'ENSG00000103472', 'ENSG00000260951': 'ENSG00000233824', 'ENSG00000290593': 'ENSG00000267575', 'ENSG00000258342': 'ENSG00000257585', 'ENSG00000290407': 'ENSG00000291282', 'ENSG00000289826': 'ENSG00000293442', 'ENSG00000223795': 'ENSG00000228877', 'ENSG00000287682': 'ENSG00000214407', 'ENSG00000271904': 'ENSG00000245526', 'ENSG00000265975': 'ENSG00000266389', 'ENSG00000286466': 'ENSG00000225718', 'ENSG00000258919': 'ENSG00000258404', 'ENSG00000285933': 'ENSG00000290775', 'ENSG00000290591': 'ENSG00000286058', 'ENSG00000271156': 'ENSG00000286984', 'ENSG00000230205': 'ENSG00000287473', 'ENSG00000250101': 'ENSG00000291113', 'ENSG00000270055': nan, 'ENSG00000258600': 'ENSG00000258426', 'ENSG00000267521': 'ENSG00000267568', 'ENSG00000253671': 'ENSG00000253944', 'ENSG00000291247': 'ENSG00000290775', 'ENSG00000267399': 'ENSG00000267712', 'ENSG00000232636': 'ENSG00000228824', 'ENSG00000253115': 'ENSG00000254288', 'ENSG00000272468': nan, 'ENSG00000275557': 'ENSG00000291158', 'ENSG00000272341': 'ENSG00000229931', 'ENSG00000225790': 'ENSG00000231574', 'ENSG00000290100': 'ENSG00000236213', 'ENSG00000287702': 'ENSG00000287568', 'ENSG00000284700': 'ENSG00000225767', 'ENSG00000290818': 'ENSG00000244198', 'ENSG00000286687': 'ENSG00000287246', 'ENSG00000224481': 'ENSG00000238107', 'ENSG00000261193': 'ENSG00000205037', 'ENSG00000288810': 'ENSG00000225206', 'ENSG00000233256': 'ENSG00000286514', 'ENSG00000229881': nan, 'ENSG00000283480': 'ENSG00000280989', 'ENSG00000262089': 'ENSG00000267532', 'ENSG00000287168': 'ENSG00000288838', 'ENSG00000249125': 'ENSG00000251526', 'ENSG00000272218': 'ENSG00000250829', 'ENSG00000288991': nan, 'ENSG00000233970': 'ENSG00000227713', 'ENSG00000250418': nan, 'ENSG00000225655': 'ENSG00000291075', 'ENSG00000261120': 'ENSG00000258553', 'ENSG00000249166': nan, 'ENSG00000272049': 'ENSG00000245729', 'ENSG00000242396': 'ENSG00000233203', 'ENSG00000255644': nan, 'ENSG00000273486': nan, 'ENSG00000291260': 'ENSG00000291027', 'ENSG00000287564': 'ENSG00000272381', 'ENSG00000227192': 'ENSG00000229017', 'ENSG00000228421': 'ENSG00000272568', 'ENSG00000291288': 'ENSG00000223784', 'ENSG00000290514': 'ENSG00000310532', 'ENSG00000267420': 'ENSG00000261514', 'ENSG00000286016': 'ENSG00000286791', 'ENSG00000277010': 'ENSG00000196557', 'ENSG00000231616': 'ENSG00000226877', 'ENSG00000285766': 'ENSG00000227245', 'ENSG00000256001': 'ENSG00000249345', 'ENSG00000283504': 'ENSG00000287636', 'ENSG00000233193': 'ENSG00000233002', 'ENSG00000263331': 'ENSG00000289640', 'ENSG00000276867': nan, 'ENSG00000284930': 'ENSG00000133961', 'ENSG00000273481': 'ENSG00000237976', 'ENSG00000290903': 'ENSG00000226067', 'ENSG00000285660': 'ENSG00000241131', 'ENSG00000272519': nan, 'ENSG00000286080': 'ENSG00000266904', 'ENSG00000287614': 'ENSG00000227803', 'ENSG00000290974': nan, 'ENSG00000288580': 'ENSG00000253853', 'ENSG00000286499': 'ENSG00000287563', 'ENSG00000278011': nan, 'ENSG00000291299': 'ENSG00000228315', 'ENSG00000254836': 'ENSG00000254584', 'ENSG00000271792': 'ENSG00000249526', 'ENSG00000253766': 'ENSG00000291102', 'ENSG00000259616': 'ENSG00000259675', 'ENSG00000286895': 'ENSG00000215241', 'ENSG00000235242': 'ENSG00000286513', 'ENSG00000288526': 'ENSG00000234026', 'ENSG00000272650': nan, 'ENSG00000267070': 'ENSG00000285567', 'ENSG00000260071': 'ENSG00000261617', 'ENSG00000258265': 'ENSG00000257891', 'ENSG00000232325': 'ENSG00000287883', 'ENSG00000256686': 'ENSG00000256440', 'ENSG00000227917': 'ENSG00000231808', 'ENSG00000290010': 'ENSG00000294436', 'ENSG00000261159': nan, 'ENSG00000270157': 'ENSG00000244701', 'ENSG00000289635': 'ENSG00000255240', 'ENSG00000269888': nan, 'ENSG00000250670': 'ENSG00000245384', 'ENSG00000289069': 'ENSG00000242242', 'ENSG00000258216': 'ENSG00000271614', 'ENSG00000223379': 'ENSG00000231527', 'ENSG00000253256': 'ENSG00000253315', 'ENSG00000264421': 'ENSG00000266473', 'ENSG00000259582': nan, 'ENSG00000288819': nan, 'ENSG00000288772': 'ENSG00000229431', 'ENSG00000266248': 'ENSG00000264515', 'ENSG00000272732': nan, 'ENSG00000286564': 'ENSG00000285838', 'ENSG00000259604': 'ENSG00000272808', 'ENSG00000259255': 'ENSG00000287704', 'ENSG00000291259': 'ENSG00000291082', 'ENSG00000236451': 'ENSG00000288902', 'ENSG00000258092': 'ENSG00000258325', 'ENSG00000288573': 'ENSG00000237950', 'ENSG00000288850': 'ENSG00000260608', 'ENSG00000267327': 'ENSG00000267057', 'ENSG00000249604': 'ENSG00000245293', 'ENSG00000271955': 'ENSG00000233891', 'ENSG00000287523': 'ENSG00000228944', 'ENSG00000289920': 'ENSG00000225778', 'ENSG00000272872': 'ENSG00000206195', 'ENSG00000272954': 'ENSG00000207751', 'ENSG00000289590': 'ENSG00000258197', 'ENSG00000257226': 'ENSG00000231758', 'ENSG00000272085': 'ENSG00000254350', 'ENSG00000233415': 'ENSG00000237767', 'ENSG00000258386': 'ENSG00000258474', 'ENSG00000287954': 'ENSG00000230010', 'ENSG00000272444': nan, 'ENSG00000235994': 'ENSG00000229921', 'ENSG00000273211': 'ENSG00000223343', 'ENSG00000241792': 'ENSG00000241131', 'ENSG00000225489': 'ENSG00000236924', 'ENSG00000265717': 'ENSG00000266743', 'ENSG00000289512': 'ENSG00000225519', 'ENSG00000244545': nan, 'ENSG00000289467': nan, 'ENSG00000272940': 'ENSG00000205559', 'ENSG00000277501': 'ENSG00000277688', 'ENSG00000286213': 'ENSG00000228067', 'ENSG00000257322': 'ENSG00000257252', 'ENSG00000237359': 'ENSG00000232104', 'ENSG00000254927': 'ENSG00000254930', 'ENSG00000261650': 'ENSG00000214039', 'ENSG00000266490': 'ENSG00000290928', 'ENSG00000234141': 'ENSG00000233108', 'ENSG00000273119': 'ENSG00000267051', 'ENSG00000255272': 'ENSG00000254508', 'ENSG00000260060': nan, 'ENSG00000251506': 'ENSG00000251426', 'ENSG00000248753': 'ENSG00000224186', 'ENSG00000233799': 'ENSG00000249592', 'ENSG00000228503': 'ENSG00000234967', 'ENSG00000286622': 'ENSG00000260093', 'ENSG00000236948': 'ENSG00000289893', 'ENSG00000227305': 'ENSG00000234387', 'ENSG00000223808': 'ENSG00000234752', 'ENSG00000286824': nan, 'ENSG00000225836': nan, 'ENSG00000225916': 'ENSG00000229647', 'ENSG00000260141': 'ENSG00000291268', 'ENSG00000273138': 'ENSG00000233942', 'ENSG00000286827': 'ENSG00000243593', 'ENSG00000253960': 'ENSG00000246662', 'ENSG00000263388': 'ENSG00000272975', 'ENSG00000288950': 'ENSG00000286285', 'ENSG00000267787': 'ENSG00000267040', 'ENSG00000255599': 'ENSG00000255689', 'ENSG00000285424': 'ENSG00000284823', 'ENSG00000283003': 'ENSG00000261617', 'ENSG00000288963': 'ENSG00000232104', 'ENSG00000289619': nan, 'ENSG00000286906': 'ENSG00000226370', 'ENSG00000257277': 'ENSG00000231758', 'ENSG00000286915': 'ENSG00000261758', 'ENSG00000288808': 'ENSG00000259460', 'ENSG00000259972': 'ENSG00000290890', 'ENSG00000233029': 'ENSG00000291123', 'ENSG00000270265': 'ENSG00000251611', 'ENSG00000257715': 'ENSG00000257878', 'ENSG00000264212': 'ENSG00000266014', 'ENSG00000287139': 'ENSG00000300787', 'ENSG00000288554': 'ENSG00000261103', 'ENSG00000289722': 'ENSG00000162039', 'ENSG00000288565': 'ENSG00000233639', 'ENSG00000249483': 'ENSG00000287938', 'ENSG00000228648': 'ENSG00000280707', 'ENSG00000243179': 'ENSG00000234199', 'ENSG00000291107': 'ENSG00000284634', 'ENSG00000286931': 'ENSG00000291039', 'ENSG00000287557': 'ENSG00000286680', 'ENSG00000248787': 'ENSG00000241288', 'ENSG00000273374': 'ENSG00000296790', 'ENSG00000235578': 'ENSG00000290950', 'ENSG00000290594': 'ENSG00000287151', 'ENSG00000291278': 'ENSG00000286058', 'ENSG00000281920': 'ENSG00000204929', 'ENSG00000274902': 'ENSG00000257433', 'ENSG00000227920': 'ENSG00000204110', 'ENSG00000270019': 'ENSG00000228857', 'ENSG00000290029': 'ENSG00000236700', 'ENSG00000286133': 'ENSG00000287226', 'ENSG00000241317': 'ENSG00000293221', 'ENSG00000254180': 'ENSG00000253799', 'ENSG00000234698': nan, 'ENSG00000254364': 'ENSG00000253666', 'ENSG00000254420': 'ENSG00000288853', 'ENSG00000287440': 'ENSG00000250934', 'ENSG00000282863': 'ENSG00000230417', 'ENSG00000250078': 'ENSG00000250340', 'ENSG00000235795': nan, 'ENSG00000290124': 'ENSG00000290683', 'ENSG00000226079': 'ENSG00000232395', 'ENSG00000225393': 'ENSG00000224533', 'ENSG00000258345': nan, 'ENSG00000253381': 'ENSG00000253665', 'ENSG00000250284': 'ENSG00000249803', 'ENSG00000267636': 'ENSG00000267662', 'ENSG00000259126': 'ENSG00000258487', 'ENSG00000253735': 'ENSG00000254237', 'ENSG00000222022': 'ENSG00000222032', 'ENSG00000262558': 'ENSG00000262294', 'ENSG00000251314': 'ENSG00000153113', 'ENSG00000257654': 'ENSG00000257883', 'ENSG00000287569': 'ENSG00000125804', 'ENSG00000267683': 'ENSG00000267339', 'ENSG00000278084': 'ENSG00000256811', 'ENSG00000257194': nan, 'ENSG00000291287': 'ENSG00000290718', 'ENSG00000242021': 'ENSG00000228933', 'ENSG00000276278': nan, 'ENSG00000224884': 'ENSG00000227110', 'ENSG00000236501': 'ENSG00000229337', 'ENSG00000260052': nan, 'ENSG00000231877': 'ENSG00000234464', 'ENSG00000272583': 'ENSG00000228826', 'ENSG00000204398': 'ENSG00000215881', 'ENSG00000253484': 'ENSG00000289095', 'ENSG00000261775': 'ENSG00000247240', 'ENSG00000229458': 'ENSG00000225738', 'ENSG00000271751': 'ENSG00000272186', 'ENSG00000258642': 'ENSG00000259130', 'ENSG00000288111': 'ENSG00000249846', 'ENSG00000261720': 'ENSG00000292430', 'ENSG00000253235': 'ENSG00000250295', 'ENSG00000254695': 'ENSG00000254946', 'ENSG00000290414': nan, 'ENSG00000291291': nan, 'ENSG00000272137': 'ENSG00000198478', 'ENSG00000258473': 'ENSG00000258819', 'ENSG00000255015': 'ENSG00000255248', 'ENSG00000241180': 'ENSG00000272438', 'ENSG00000203520': 'ENSG00000256789', 'ENSG00000231128': 'ENSG00000226167', 'ENSG00000276790': 'ENSG00000263293', 'ENSG00000288531': 'ENSG00000228794', 'ENSG00000250567': 'ENSG00000293393', 'ENSG00000241772': 'ENSG00000144228', 'ENSG00000279159': nan, 'ENSG00000290032': nan, 'ENSG00000289184': 'ENSG00000287862', 'ENSG00000263688': 'ENSG00000285095', 'ENSG00000273181': 'ENSG00000272721', 'ENSG00000234998': 'ENSG00000291123', 'ENSG00000251679': 'ENSG00000250634', 'ENSG00000250511': 'ENSG00000250103', 'ENSG00000256732': 'ENSG00000256128', 'ENSG00000289048': 'ENSG00000254024', 'ENSG00000287350': 'ENSG00000258702', 'ENSG00000254821': 'ENSG00000234817', 'ENSG00000288954': 'ENSG00000226091', 'ENSG00000286863': 'ENSG00000227016', 'ENSG00000224525': 'ENSG00000272865', 'ENSG00000287346': 'ENSG00000258735', 'ENSG00000285535': 'ENSG00000267506', 'ENSG00000286103': 'ENSG00000293062', 'ENSG00000286534': 'ENSG00000267506', 'ENSG00000261757': nan, 'ENSG00000254744': 'ENSG00000259363', 'ENSG00000285922': 'ENSG00000225206', 'ENSG00000261135': 'ENSG00000224174', 'ENSG00000265174': 'ENSG00000265944', 'ENSG00000223469': 'ENSG00000283215', 'ENSG00000268333': 'ENSG00000235590', 'ENSG00000285759': 'ENSG00000229950', 'ENSG00000229191': 'ENSG00000234132', 'ENSG00000291246': 'ENSG00000290466', 'ENSG00000291215': 'ENSG00000225880', 'ENSG00000266908': 'ENSG00000230563', 'ENSG00000286397': 'ENSG00000228564', 'ENSG00000283517': 'ENSG00000228639', 'ENSG00000260581': 'ENSG00000288081', 'ENSG00000238009': 'ENSG00000241860', 'ENSG00000291279': 'ENSG00000284084', 'ENSG00000290856': 'ENSG00000273784', 'ENSG00000253139': 'ENSG00000246430', 'ENSG00000231255': 'ENSG00000233073', 'ENSG00000276854': 'ENSG00000227258', 'ENSG00000254138': 'ENSG00000289601', 'ENSG00000267449': nan, 'ENSG00000244620': 'ENSG00000226777', 'ENSG00000266893': 'ENSG00000290606', 'ENSG00000290183': 'ENSG00000006194', 'ENSG00000255944': 'ENSG00000256128', 'ENSG00000257879': 'ENSG00000257165', 'ENSG00000290580': 'ENSG00000249515', 'ENSG00000286919': 'ENSG00000289641', 'ENSG00000233376': 'ENSG00000229005', 'ENSG00000290440': 'ENSG00000228315', 'ENSG00000286439': 'ENSG00000270111', 'ENSG00000273765': nan, 'ENSG00000249091': 'ENSG00000248397', 'ENSG00000290680': 'ENSG00000103472', 'ENSG00000290081': 'ENSG00000225506', 'ENSG00000234540': 'ENSG00000286277', 'ENSG00000230381': 'ENSG00000233154', 'ENSG00000259166': 'ENSG00000259082', 'ENSG00000290659': 'ENSG00000273018', 'ENSG00000276251': 'ENSG00000267498', 'ENSG00000260409': 'ENSG00000310519', 'ENSG00000250060': 'ENSG00000250974', 'ENSG00000261218': 'ENSG00000197943', 'ENSG00000251532': 'ENSG00000291079', 'ENSG00000289524': 'ENSG00000243550', 'ENSG00000250948': 'ENSG00000248714', 'ENSG00000290510': 'ENSG00000223597', 'ENSG00000289988': 'ENSG00000296783', 'ENSG00000254651': 'ENSG00000255267', 'ENSG00000289179': 'ENSG00000248174', 'ENSG00000274652': nan, 'ENSG00000286571': 'ENSG00000287241', 'ENSG00000228334': 'ENSG00000217455', 'ENSG00000263508': 'ENSG00000263400', 'ENSG00000289563': 'ENSG00000260420', 'ENSG00000290242': nan, 'ENSG00000238158': 'ENSG00000233068', 'ENSG00000269927': 'ENSG00000286423', 'ENSG00000287248': 'ENSG00000267057', 'ENSG00000287622': 'ENSG00000286922', 'ENSG00000286262': 'ENSG00000223768', 'ENSG00000255028': 'ENSG00000254659', 'ENSG00000268810': 'ENSG00000269151', 'ENSG00000237954': 'ENSG00000230434', 'ENSG00000260100': 'ENSG00000232920', 'ENSG00000258196': 'ENSG00000257155', 'ENSG00000234810': 'ENSG00000233079', 'ENSG00000237422': 'ENSG00000230537', 'ENSG00000255479': 'ENSG00000255363', 'ENSG00000287387': 'ENSG00000279873', 'ENSG00000268509': 'ENSG00000233912', 'ENSG00000233852': 'ENSG00000236088', 'ENSG00000256923': nan, 'ENSG00000289830': 'ENSG00000287092', 'ENSG00000289486': 'ENSG00000288852', 'ENSG00000263677': 'ENSG00000260372', 'ENSG00000286329': 'ENSG00000242828', 'ENSG00000258831': 'ENSG00000258476', 'ENSG00000288816': 'ENSG00000227634', 'ENSG00000235047': 'ENSG00000289349', 'ENSG00000188525': 'ENSG00000289033', 'ENSG00000228353': 'ENSG00000229672', 'ENSG00000239216': 'ENSG00000226172', 'ENSG00000290721': 'ENSG00000167562', 'ENSG00000283648': 'ENSG00000287636', 'ENSG00000248346': 'ENSG00000248764', 'ENSG00000291055': 'ENSG00000291079', 'ENSG00000289620': 'ENSG00000223511', 'ENSG00000286472': 'ENSG00000230725', 'ENSG00000232749': 'ENSG00000290551', 'ENSG00000285622': nan, 'ENSG00000283907': 'ENSG00000224910', 'ENSG00000287649': 'ENSG00000243295', 'ENSG00000286087': 'ENSG00000234265', 'ENSG00000251144': 'ENSG00000251670', 'ENSG00000274444': 'ENSG00000259460', 'ENSG00000235934': 'ENSG00000234350', 'ENSG00000234677': 'ENSG00000287768', 'ENSG00000260095': 'ENSG00000260874', 'ENSG00000273729': 'ENSG00000246548', 'ENSG00000272922': nan, 'ENSG00000258921': nan, 'ENSG00000272009': 'ENSG00000269293', 'ENSG00000286723': 'ENSG00000290555', 'ENSG00000270016': nan, 'ENSG00000272979': 'ENSG00000290089', 'ENSG00000290066': 'ENSG00000285847', 'ENSG00000260090': 'ENSG00000248764', 'ENSG00000259274': 'ENSG00000245534', 'ENSG00000259587': nan, 'ENSG00000261470': 'ENSG00000261749', 'ENSG00000248646': 'ENSG00000251185', 'ENSG00000244650': 'ENSG00000241131', 'ENSG00000287865': 'ENSG00000228521', 'ENSG00000290384': 'ENSG00000282508', 'ENSG00000289541': 'ENSG00000256357', 'ENSG00000290449': 'ENSG00000290920', 'ENSG00000232680': 'ENSG00000288731', 'ENSG00000249008': 'ENSG00000287544', 'ENSG00000287788': 'ENSG00000288761', 'ENSG00000272971': 'ENSG00000229953', 'ENSG00000261386': 'ENSG00000259804', 'ENSG00000276269': nan, 'ENSG00000265091': 'ENSG00000264575', 'ENSG00000249708': nan, 'ENSG00000286501': 'ENSG00000243550', 'ENSG00000286603': 'ENSG00000287281', 'ENSG00000241520': 'ENSG00000232485', 'ENSG00000231883': 'ENSG00000223598', 'ENSG00000291011': 'ENSG00000232827', 'ENSG00000290709': 'ENSG00000196696', 'ENSG00000244063': 'ENSG00000228857', 'ENSG00000276348': 'ENSG00000277350', 'ENSG00000254095': 'ENSG00000253377', 'ENSG00000287386': 'ENSG00000257319', 'ENSG00000272592': 'ENSG00000233643', 'ENSG00000228538': 'ENSG00000229621', 'ENSG00000287127': 'ENSG00000246145', 'ENSG00000289082': 'ENSG00000288886', 'ENSG00000260030': nan, 'ENSG00000249463': 'ENSG00000251598', 'ENSG00000287868': 'ENSG00000286782', 'ENSG00000266957': 'ENSG00000167220', 'ENSG00000233005': 'ENSG00000231204', 'ENSG00000250158': 'ENSG00000153113', 'ENSG00000287884': 'ENSG00000205790', 'ENSG00000289840': nan, 'ENSG00000237899': 'ENSG00000272145', 'ENSG00000275636': 'ENSG00000248508', 'ENSG00000272953': 'ENSG00000273084', 'ENSG00000278514': 'ENSG00000214432', 'ENSG00000278626': nan, 'ENSG00000287313': 'ENSG00000235009', 'ENSG00000249492': 'ENSG00000248554', 'ENSG00000286825': 'ENSG00000288044', 'ENSG00000233408': 'ENSG00000230471', 'ENSG00000246331': 'ENSG00000285517', 'ENSG00000273363': 'ENSG00000224812', 'ENSG00000271259': nan, 'ENSG00000229912': 'ENSG00000235126', 'ENSG00000261462': 'ENSG00000307585', 'ENSG00000260183': 'ENSG00000259867', 'ENSG00000251613': 'ENSG00000249085', 'ENSG00000231140': 'ENSG00000224038', 'ENSG00000258088': 'ENSG00000258077', 'ENSG00000290396': 'ENSG00000290394', 'ENSG00000267115': 'ENSG00000266916', 'ENSG00000260517': 'ENSG00000103472', 'ENSG00000253844': 'ENSG00000228801', 'ENSG00000256542': 'ENSG00000256943', 'ENSG00000289036': 'ENSG00000288782', 'ENSG00000228561': 'ENSG00000228221', 'ENSG00000289994': 'ENSG00000286610', 'ENSG00000241280': 'ENSG00000214407', 'ENSG00000284685': 'ENSG00000103472', 'ENSG00000259209': 'ENSG00000259768', 'ENSG00000254619': 'ENSG00000254508', 'ENSG00000268615': 'ENSG00000233901', 'ENSG00000290969': 'ENSG00000290718', 'ENSG00000261222': 'ENSG00000182352', 'ENSG00000257454': 'ENSG00000258053', 'ENSG00000289917': 'ENSG00000259717', 'ENSG00000290784': 'ENSG00000225880', 'ENSG00000278107': 'ENSG00000264278', 'ENSG00000244268': 'ENSG00000288787', 'ENSG00000273289': 'ENSG00000197182', 'ENSG00000249335': 'ENSG00000249352', 'ENSG00000226277': nan, 'ENSG00000264334': 'ENSG00000265843', 'ENSG00000270147': 'ENSG00000269921', 'ENSG00000225058': 'ENSG00000224187', 'ENSG00000249184': 'ENSG00000251249', 'ENSG00000289531': 'ENSG00000214900', 'ENSG00000286189': 'ENSG00000180769', 'ENSG00000225643': 'ENSG00000157978', 'ENSG00000287729': 'ENSG00000238123', 'ENSG00000254039': 'ENSG00000248954', 'ENSG00000256694': 'ENSG00000256540', 'ENSG00000272736': 'ENSG00000272975', 'ENSG00000248533': 'ENSG00000248587', 'ENSG00000238102': nan, 'ENSG00000289135': 'ENSG00000273265', 'ENSG00000256101': 'ENSG00000215241', 'ENSG00000249159': 'ENSG00000245729', 'ENSG00000289455': 'ENSG00000225930', 'ENSG00000264790': 'ENSG00000265374', 'ENSG00000286292': 'ENSG00000271646', 'ENSG00000231212': 'ENSG00000204802', 'ENSG00000274312': 'ENSG00000277987', 'ENSG00000258302': 'ENSG00000270344', 'ENSG00000282021': 'ENSG00000253982', 'ENSG00000257711': nan, 'ENSG00000289413': 'ENSG00000288958', 'ENSG00000261445': 'ENSG00000290413', 'ENSG00000289147': 'ENSG00000264672', 'ENSG00000258918': 'ENSG00000259130', 'ENSG00000289242': 'ENSG00000253214', 'ENSG00000233906': 'ENSG00000283982', 'ENSG00000264078': 'ENSG00000235790', 'ENSG00000228008': 'ENSG00000230698', 'ENSG00000272515': nan, 'ENSG00000272240': 'ENSG00000288985', 'ENSG00000233987': 'ENSG00000237222', 'ENSG00000253985': 'ENSG00000250387', 'ENSG00000287368': 'ENSG00000230074', 'ENSG00000247810': 'ENSG00000261761', 'ENSG00000287316': 'ENSG00000236213', 'ENSG00000260983': 'ENSG00000286841', 'ENSG00000289206': 'ENSG00000177738', 'ENSG00000223675': 'ENSG00000293271', 'ENSG00000286997': 'ENSG00000267207', 'ENSG00000290101': 'ENSG00000233942', 'ENSG00000248311': 'ENSG00000248973', 'ENSG00000288982': nan, 'ENSG00000272304': 'ENSG00000249413', 'ENSG00000271788': 'ENSG00000177738', 'ENSG00000286572': 'ENSG00000176754', 'ENSG00000235271': 'ENSG00000244625', 'ENSG00000239674': 'ENSG00000290475', 'ENSG00000266588': 'ENSG00000266013', 'ENSG00000257918': 'ENSG00000257545', 'ENSG00000287875': 'ENSG00000293612', 'ENSG00000253584': 'ENSG00000251574', 'ENSG00000288002': 'ENSG00000245729', 'ENSG00000276075': 'ENSG00000259804', 'ENSG00000224228': 'ENSG00000224000', 'ENSG00000254587': 'ENSG00000256684', 'ENSG00000264080': 'ENSG00000266602', 'ENSG00000229628': 'ENSG00000237471', 'ENSG00000260163': 'ENSG00000286971', 'ENSG00000289411': 'ENSG00000277332', 'ENSG00000236856': 'ENSG00000233684', 'ENSG00000287411': 'ENSG00000230423', 'ENSG00000235852': 'ENSG00000228509', 'ENSG00000277423': nan, 'ENSG00000258844': 'ENSG00000257585', 'ENSG00000229160': 'ENSG00000227292', 'ENSG00000253444': 'ENSG00000282142', 'ENSG00000224532': 'ENSG00000226281

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [45]:
var_ensg

,gene_inputs,ensembl_inputs,ensembl_gene_id,gene_symbol,original_index
index,,,,,
0,DDX11L2,None,NaN,NaN,DDX11L2
1,MIR1302-2HG,None,NaN,NaN,MIR1302-2HG
2,FAM138A,None,NaN,NaN,FAM138A
3,,ENSG00000290826,ENSG00000290826,None,ENSG00000290826
4,OR4F5,None,NaN,NaN,OR4F5
...,...,...,...,...,...
38601,,ENSG00000277836,ENSG00000277836,NaN,ENSG00000277836
38602,,ENSG00000278633,ENSG00000278633,NaN,ENSG00000278633
38603,,ENSG00000276017,ENSG00000276017,NaN,ENSG00000276017
38604,,ENSG00000278817,ENSG00000278817,NaN,ENSG00000278817
38605,,ENSG00000277196,ENSG00000277196,NaN,ENSG00000277196

# Compile final gene symbols and ensg ids from the two mappings

In [46]:
var_df_clean = var_symb.merge(var_ensg, left_on='original_index', right_on='original_index', suffixes=('_symb', '_ensg'))
var_df_clean = var_df_clean.drop(columns=['gene_inputs_symb', 'gene_inputs_ensg', 'ensembl_inputs_symb', 'ensembl_inputs_ensg'])
var_df_clean['clean_gene_symbol'] = None
var_df_clean['clean_ensg_id'] = None

ensg_starts_mask = var_df_clean['original_index'].str.startswith('ENSG')

# if original id starts with ENSG - assign ensg mapping
var_df_clean.loc[ensg_starts_mask, 'clean_gene_symbol'] = var_df_clean.loc[ensg_starts_mask, 'gene_symbol_ensg']
var_df_clean.loc[ensg_starts_mask, 'clean_ensg_id'] = var_df_clean.loc[ensg_starts_mask, 'ensembl_gene_id_ensg']

# if not, assign symb mapping
var_df_clean.loc[~ensg_starts_mask, 'clean_gene_symbol'] = var_df_clean.loc[~ensg_starts_mask, 'gene_symbol_symb']
var_df_clean.loc[~ensg_starts_mask, 'clean_ensg_id'] = var_df_clean.loc[~ensg_starts_mask, 'ensembl_gene_id_symb']

# replace missing ensg with original index
var_df_clean.loc[var_df_clean['clean_ensg_id'].isna() & ensg_starts_mask, 'clean_ensg_id'] = var_df_clean.loc[var_df_clean['clean_ensg_id'].isna() & ensg_starts_mask, 'original_index']

var_df_clean = var_df_clean.rename(columns={'clean_gene_symbol':'gene_symbol', 'clean_ensg_id':'ensembl_gene_id'})[['ensembl_gene_id', 'gene_symbol']]

var_df_clean.index.name = 'index'

var_df_clean

       ensembl_gene_id  gene_symbol
index
0      ENSG00000310539      DDX11L2
1      ENSG00000243485  MIR1302-2HG
2      ENSG00000237613      FAM138A
3      ENSG00000290826         None
4      ENSG00000186092        OR4F5
...                ...          ...
38601  ENSG00000277836          NaN
38602  ENSG00000278633          NaN
38603  ENSG00000276017          NaN
38604  ENSG00000278817          NaN
38605  ENSG00000277196          NaN

[38606 rows x 2 columns]

In [47]:
# assign fixed genes back to var
cur_data.adata.var = var_df_clean

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Validate var metadata

In [48]:
cur_data.validate_data(slot='var')

       ensembl_gene_id  gene_symbol
index
0      ENSG00000310539      DDX11L2
1      ENSG00000243485  MIR1302-2HG
2      ENSG00000237613      FAM138A
3      ENSG00000290826         None
4      ENSG00000186092        OR4F5
...                ...          ...
38601  ENSG00000277836          NaN
38602  ENSG00000278633          NaN
38603  ENSG00000276017          NaN
38604  ENSG00000278817          NaN
38605  ENSG00000277196          NaN

[38606 rows x 2 columns]

# Save the dataset

In [49]:
cur_data.save_curated_data_h5ad()

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/orion_2025_hek293t_curated.h5ad

In [50]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/orion_2025_hek293t_curated_metadata.parquet

# Upload to BigQuery

In [51]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/orion_2025_hek293t_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

Staging table: loading `.parquet` file ../curated/parquet/orion_2025_hek293t_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...

Staging table: loaded 4534299 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [52]:
!gcloud storage cp ../curated/h5ad/orion_2025_hek293t_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/orion_2025_hek293t_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/orion_2025_hek293t_curated.h5ad

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

⠛

⠹

⠼

⠶

⠧

⠏

Average throughput: 879.4MiB/s