# Import

In [1]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

import logging
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("curation.log"),
        logging.StreamHandler(),  # keep console output too
    ],
    force=True,
)

# Download data

In [2]:
noncurated_path = "../non_curated/h5ad/replogle_2022_k562_gw_raw.h5ad"
download_file(
    url="https://ndownloader.figshare.com/files/35775507",
    dest_path=noncurated_path
)

2026-04-23 11:52:17,838 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): ndownloader.figshare.com:443
2026-04-23 11:52:17,911 DEBUG urllib3.connectionpool: https://ndownloader.figshare.com:443 "GET /files/35775507 HTTP/1.1" 302 0
2026-04-23 11:52:17,913 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): s3-eu-west-1.amazonaws.com:443
2026-04-23 11:52:18,170 DEBUG urllib3.connectionpool: https://s3-eu-west-1.amazonaws.com:443 "GET /ptemp-plus-8475456492/35775507/K562_gwps_raw_singlecell_01.h5ad?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA3OGA3B5WLN3GODUZ/20260423/eu-west-1/s3/aws4_request&X-Amz-Date=20260423T105217Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=af480a31af7f00290a6b1646e0249f08bed27fd7c04ff9738b8f9f97a433fc03 HTTP/1.1" 200 65830941948

Downloaded https://ndownloader.figshare.com/files/35775507 to ../non_curated/h5ad/replogle_2022_k562_gw_raw.h5ad

# Initialise the dataset object

In [6]:
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/replogle_2022_k562_gw_raw.h5ad

In [7]:
cur_data.adata.obs

,gem_group,gene,gene_id,transcript,gene_transcript,sgID_AB,mitopercent,UMI_count,z_gemgroup_UMI,core_scale_factor,core_adjusted_UMI_count
cell_barcode,,,,,,,,,,,
AAACCCAAGAAACCAT-157,157,CTSC,ENSG00000109861,P1P2,1946_CTSC_P1P2_ENSG00000109861,CTSC_-_88070848.23-P1P2|CTSC_-_88070918.23-P1P2,0.088177,14709.0,0.470687,1.051176,13992.900391
AAACCCAAGAAACCAT-207,207,CWC25,ENSG00000273559,P1P2,1973_CWC25_P1P2_ENSG00000273559,CWC25_+_36981555.23-P1P2|CWC25_+_36981567.23-P1P2,0.114342,16162.0,0.824790,1.074744,15038.004883
AAACCCAAGAAACCAT-29,29,PDE4DIP,ENSG00000178104,ENST00000313431.9,6168_PDE4DIP_ENST00000313431.9_ENSG00000178104,PDE4DIP_+_144932474.23-ENST00000313431.9|PDE4D...,0.107157,33297.0,2.627126,1.472444,22613.423828
AAACCCAAGAAAGCGA-149,149,ZZEF1,ENSG00000074755,P1P2,10745_ZZEF1_P1P2_ENSG00000074755,ZZEF1_+_4046247.23-P1P2|ZZEF1_+_4046255.23-P1P2,0.143107,7435.0,0.918149,0.480401,15476.669922
AAACCCAAGAAATCCA-172,172,SNAPIN,ENSG00000143553,P1P2,8210_SNAPIN_P1P2_ENSG00000143553,SNAPIN_+_153631238.23-P1P2|SNAPIN_-_153631252....,0.130754,7755.0,-0.230920,0.695649,11147.856445
...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGTCTTTCCAA-201,201,SCRIB,ENSG00000180900,P1P2,7706_SCRIB_P1P2_ENSG00000180900,SCRIB_-_144897465.23-P1P2|SCRIB_-_144897339.23...,0.115868,11867.0,-0.441665,1.151834,10302.698242
TTTGTTGTCTTTCGAT-79,79,CADM4,ENSG00000105767,P1P2,1151_CADM4_P1P2_ENSG00000105767,CADM4_+_44143915.23-P1P2|CADM4_+_44143932.23-P1P2,0.094454,6437.0,-1.208969,0.935249,6882.660156
TTTGTTGTCTTTCTAG-218,218,SLC4A7,ENSG00000033867,P1P2,8098_SLC4A7_P1P2_ENSG00000033867,SLC4A7_+_27525847.23-P1P2|SLC4A7_+_27525631.23...,0.170080,11377.0,-0.109167,1.000028,11376.682617
TTTGTTGTCTTTGCGC-169,169,TMEM131,ENSG00000075568,P1P2,8997_TMEM131_P1P2_ENSG00000075568,TMEM131_-_98612356.23-P1P2|TMEM131_-_98612239....,0.103772,10658.0,-0.358464,1.023092,10417.442383
TTTGTTGTCTTTGCGC-213,213,SRP14,ENSG00000140319,P1P2,8413_SRP14_P1P2_ENSG00000140319,SRP14_+_40331287.23-P1P2|SRP14_-_40330986.23-P1P2,0.124624,18287.0,0.284907,1.398296,13078.065430

# OBS slot curation

### Add cell barcodes to the obs slot

In [8]:
cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.astype(str)

print(cur_data.adata.obs[['cell_barcode']].head())

                              cell_barcode
cell_barcode
AAACCCAAGAAACCAT-157  AAACCCAAGAAACCAT-157
AAACCCAAGAAACCAT-207  AAACCCAAGAAACCAT-207
AAACCCAAGAAACCAT-29    AAACCCAAGAAACCAT-29
AAACCCAAGAAAGCGA-149  AAACCCAAGAAAGCGA-149
AAACCCAAGAAATCCA-172  AAACCCAAGAAATCCA-172

### Show unique perturbations

In [9]:
cur_data.show_unique(slot = 'obs', column = 'sgID_AB')

Unique values in adata.obs.sgID_AB: 11187
--------------------------------------------------
{'A1BG_+_58858964.23-P1|A1BG_-_58858788.23-P1',
 'A1BG_-_58864840.23-P2|A1BG_-_58864822.23-P2',
 'AAAS_-_53715438.23-P1P2|AAAS_+_53715355.23-P1P2',
 'AACS_+_125549983.23-P1P2|AACS_-_125550169.23-P1P2',
 'AAED1_-_99417574.23-P1P2|AAED1_+_99417525.23-P1P2',
 'AAGAB_-_67546997.23-P1P2|AAGAB_-_67546928.23-P1P2',
 'AAK1_-_69870791.23-P1P2|AAK1_-_69870794.23-P1P2',
 'AAMDC_-_77532236.23-P1P2|AAMDC_-_77532222.23-P1P2',
 'AAMP_+_219134851.23-P1P2|AAMP_+_219134841.23-P1P2',
 'AAR2_-_34824434.23-P1P2|AAR2_+_34824488.23-P1P2',
 'AARS2_+_44281027.23-P1P2|AARS2_+_44281044.23-P1P2',
 'AARSD1_+_41132061.23-P2|AARSD1_-_41132037.23-P2',
 'AARSD1_-_41116425.23-P1|AARSD1_+_41116412.23-P1',
 'AARS_+_70323362.23-P1P2|AARS_-_70323332.23-P1P2',
 'AASDHPPT_+_105948405.23-P1P2|AASDHPPT_+_105948450.23-P1P2',
 'AASDH_-_57253588.23-P1P2|AASDH_+_57253570.23-P1P2',
 'AATF_-_35306286.23-P1P2|AATF_-_35306346.23-P1P2',
 'ABCA7_+_1041311.23-P2|ABCA7_-_1041459.23-P2',
 'ABCA7_-_1040133.23-P1|ABCA7_+_1040185.23-P1',
 'ABCA8_+_66951401.23-P1P2|ABCA8_-_66951525.23-P1P2',
 'ABCB10_+_229694285.23-P1P2|ABCB10_-_229694297.23-P1P2',
 'ABCB6_-_220083604.23-P1P2|ABCB6_+_220083613.23-P1P2',
 'ABCB7_-_74376019.23-P1P2|ABCB7_+_74375885.23-P1P2',
 'ABCB8_-_150725551.23-P1P2|ABCB8_-_150725580.23-P1P2',
 'ABCB9_+_123450970.23-P1|ABCB9_-_123450999.23-P1',
 'ABCB9_-_123465699.23-P2|ABCB9_-_123465738.23-P2',
 'ABCC10_+_43395315.23-P1P2|ABCC10_-_43395343.23-P1P2',
 'ABCC1_+_16043647.23-P1P2|ABCC1_+_16043482.23-P1P2',
 'ABCC4_+_95953430.23-P1P2|ABCC4_+_95953641.23-P1P2',
 'ABCC5_-_183735467.23-P1P2|ABCC5_+_183735648.23-P1P2',
 'ABCD3_+_94884002.23-P1P2|ABCD3_+_94884032.23-P1P2',
 'ABCD4_+_74769611.23-P1P2|ABCD4_-_74769729.23-P1P2',
 'ABCE1_-_146019502.23-P1P2|ABCE1_-_146019516.23-P1P2',
 'ABCF1_+_30539238.23-P1|ABCF1_+_30539469.23-P1',
 'ABCF1_-_30546354.23-P2|ABCF1_-_30546344.23-P2',
 'ABCF2_+_150924287.23-P1P2|ABCF2_+_150924236.23-P1P2',
 'ABCF3_-_183903991.23-P1P2|ABCF3_-_183904021.23-P1P2',
 'ABCG1_-_43639282.23-P1P2|ABCG1_+_43639503.23-P1P2',
 'ABHD10_-_111697914.23-P1P2|ABHD10_-_111697877.23-P1P2',
 'ABHD11_-_73153094.23-P1P2|ABHD11_+_73152963.23-P1P2',
 'ABHD12_+_25371393.23-P1P2|ABHD12_+_25371436.23-P1P2',
 'ABHD13_+_108871155.23-P1P2|ABHD13_+_108870795.23-P1P2',
 'ABHD14A_+_52009255.23-P1P2|ABHD14A_+_52009194.23-P1P2',
 'ABHD14B_+_52017350.23-P2|ABHD14B_-_52016965.23-P2',
 'ABHD14B_-_52007985.23-P1|ABHD14B_-_52008040.23-P1',
 'ABHD16A_-_31670764.23-P1P2|ABHD16A_+_31670831.23-P1P2',
 'ABHD17A_-_1885483.23-P1P2|ABHD17A_+_1885470.23-P1P2',
 'ABHD17B_+_74526089.23-P1P2|ABHD17B_+_74525862.23-P1P2',
 'ABHD2_-_89631760.23-P1P2|ABHD2_-_89631738.23-P1P2',
 'ABHD3_-_19284770.23-P1P2|ABHD3_+_19284534.23-P1P2',
 'ABHD5_-_43732464.23-P1P2|ABHD5_-_43732422.23-P1P2',
 'ABHD6_+_58223718.23-P1P2|ABHD6_-_58223594.23-P1P2',
 'ABHD8_-_17414201.23-P1P2|ABHD8_-_17414169.23-P1P2',
 'ABI1_-_27149837.23-P1P2|ABI1_-_27149855.23-P1P2',
 'ABI2_-_204193288.23-P1P2|ABI2_+_204193079.23-P1P2',
 'ABL1_-_133589228.23-ENST00000372348.2|ABL1_-_133589216.23-ENST00000372348.2',
 'ABL2_+_179111875.23-P1|ABL2_-_179112151.23-P1',
 'ABL2_+_179198340.23-P2|ABL2_+_179198740.23-P2',
 'ABO_+_136150601.23-P1|ABO_+_136150587.23-P1',
 'ABO_-_136130921.23-P2|ABO_-_136130959.23-P2',
 'ABRACL_+_139349876.23-P1P2|ABRACL_+_139349879.23-P1P2',
 'ABR_+_1083212.23-P1P2|ABR_+_1082862.23-P1P2',
 'ABT1_-_26597263.23-P1P2|ABT1_+_26597412.23-P1P2',
 'ACAA1_-_38178575.23-P1P2|ACAA1_+_38178488.23-P1P2',
 'ACAA2_-_47339855.23-P1P2|ACAA2_-_47339858.23-P1P2',
 'ACACA_-_35716041.23-P1P2|ACACA_-_35716002.23-P1P2',
 'ACAD10_-_112123907.23-P1P2|ACAD10_-_112123894.23-P1P2',
 'ACAD8_-_134123507.23-P1P2|ACAD8_-_134123448.23-P1P2',
 'ACAD9_-_128598508.23-P1P2|ACAD9_-_128598499.23-P1P2',
 'ACADM_-_76190475.23-P1P2|ACADM_+_76190432.23-P1P2',
 'ACADSB_-_124768552.23-P1P2|ACADSB_+_124768710.23-P1P2',
 'ACADS_-_121163671.23-P1P2|ACADS_+_121163685.23-P1P2',
 'ACADVL_-_7123283.23-P1P2|ACADVL_-_7123242.23-P1P2',
 'ACAP2_+_195163707.23-P1P2|ACAP2_+_195163701.23-P1P2',
 'ACAP3_+_1243258.23-P1P2|ACAP3_+_1243337.23-P1P2',
 'ACAT1_+_107992310.23-P1P2|ACAT1_+_107992321.23-P1P2',
 'ACAT2_-_160183054.23-P1P2|ACAT2_-_160183042.23-P1P2',
 'ACBD3_-_226374411.23-P1P2|ACBD3_+_226374366.23-P1P2',
 'ACBD5_+_27529701.23-P1P2|ACBD5_+_27529710.23-P1P2',
 'ACBD6_+_180471319.23-P1P2|ACBD6_+_180471354.23-P1P2',
 'ACCS_+_44088091.23-P1P2|ACCS_-_44088090.23-P1P2',
 'ACD_-_67694143.23-P1P2|ACD_+_67694124.23-P1P2',
 'ACER3_-_76572003.23-P1P2|ACER3_-_76571978.23-P1P2',
 'ACIN1_-_23540292.23-P2|ACIN1_-_23540730.23-P2',
 'ACIN1_-_23564284.23-P1|ACIN1_+_23563962.23-P1',
 'ACLY_-_40075227.23-P1P2|ACLY_+_40075121.23-P1P2',
 'ACO1_+_32384680.23-P1P2|ACO1_-_32384733.23-P1P2',
 'ACO2_+_41865228.23-P1P2|ACO2_+_41865345.23-P1P2',
 'ACOT12_-_80689897.23-P1P2|ACOT12_+_80689672.23-P1P2',
 'ACOT13_-_24667371.23-P1P2|ACOT13_-_24667329.23-P1P2',
 'ACOT7_-_6453406.23-P1P2|ACOT7_-_6453369.23-P1P2',
 'ACOT8_-_44486001.23-P1P2|ACOT8_-_44485992.23-P1P2',
 'ACOT9_+_23761360.23-P1P2|ACOT9_-_23761316.23-P1P2',
 'ACOX1_-_73975196.23-P1P2|ACOX1_-_73975193.23-P1P2',
 'ACP1_-_264970.23-P1P2|ACP1_-_264967.23-P1P2',
 'ACP2_+_47270332.23-P1P2|ACP2_+_47270309.23-P1P2',
 'ACP5_-_11688064.23-P1|ACP5_-_11688455.23-P1',
 'ACP5_-_11689771.23-P2|ACP5_-_11689727.23-P2',
 'ACSF3_+_89160267.23-P1P2|ACSF3_-_89160263.23-P1P2',
 'ACSL1_+_185747071.23-P1P2|ACSL1_+_185747074.23-P1P2',
 'ACSL3_-_223726162.23-P1P2|ACSL3_-_223725828.23-P1P2',
 'ACSL4_-_108976106.23-P1P2|ACSL4_-_108976456.23-P1P2',
 'ACSM3_+_20775331.23-P1P2|ACSM3_+_20775412.23-P1P2',
 'ACSS2_-_33464845.23-P1P2|ACSS2_-_33464420.23-P1P2',
 'ACTB_-_5570191.23-P1P2|ACTB_+_5570130.23-P1P2',
 'ACTG1_-_79479788.23-P1P2|ACTG1_-_79479780.23-P1P2',
 'ACTL6A_-_179280784.23-P1P2|ACTL6A_+_179280755.23-P1P2',
 'ACTN1_-_69445956.23-P1P2|ACTN1_-_69445944.23-P1P2',
 'ACTN4_-_39138358.23-P1P2|ACTN4_-_39138303.23-P1P2',
 'ACTR10_+_58666892.23-P1P2|ACTR10_+_58666925.23-P1P2',
 'ACTR1A_+_104262452.23-P1P2|ACTR1A_+_104262449.23-P1P2',
 'ACTR1B_-_98280407.23-P1P2|ACTR1B_+_98280464.23-P1P2',
 'ACTR2_-_65454971.23-P1P2|ACTR2_-_65454953.23-P1P2',
 'ACTR3B_-_152456898.23-P1P2|ACTR3B_-_152456932.23-P1P2',
 'ACTR3C_+_150020638.23-P1P2|ACTR3C_+_150020641.23-P1P2',
 'ACTR3_+_114648069.23-P1P2|ACTR3_+_114648124.23-P1P2',
 'ACTR5_-_37377178.23-P1P2|ACTR5_+_37377152.23-P1P2',
 'ACTR6_-_100594606.23-P1P2|ACTR6_-_100594617.23-P1P2',
 'ACTR8_+_53916142.23-P1P2|ACTR8_+_53916157.23-P1P2',
 'ACVR1B_-_52345530.23-P1P2|ACVR1B_+_52345561.23-P1P2',
 'ACVR2B_+_38495339.23-P1P2|ACVR2B_+_38495606.23-P1P2',
 'ACY1_-_52017547.23-P1P2|ACY1_-_52017631.23-P1P2',
 'ACYP1_-_75530711.23-P1|ACYP1_-_75530695.23-P1',
 'ACYP1_-_75536179.23-P2|ACYP1_-_75536194.23-P2',
 'ACYP2_-_54342821.23-P1P2|ACYP2_+_54342748.23-P1P2',
 'ADAL_-_43623140.23-P1P2|ADAL_-_43623106.23-P1P2',
 'ADAM10_+_59041886.23-P1P2|ADAM10_-_59041703.23-P1P2',
 'ADAM15_+_155023841.23-P1P2|ADAM15_+_155023860.23-P1P2',
 'ADAM17_-_9695930.23-P1P2|ADAM17_+_9695837.23-P1P2',
 'ADAM9_-_38854499.23-P1P2|ADAM9_-_38854561.23-P1P2',
 'ADAMTS14_-_72432303.23-P1P2|ADAMTS14_-_72432297.23-P1P2',
 'ADAMTS3_-_73434891.23-P1P2|ADAMTS3_-_73434871.23-P1P2',
 'ADAMTSL4_-_150521934.23-P1P2|ADAMTSL4_+_150521916.23-P1P2',
 'ADARB1_-_46494561.23-P1P2|ADARB1_+_46494897.23-P1P2',
 'ADAR_-_154580658.23-P1|ADAR_-_154580605.23-P1',
 'ADAR_-_154599983.23-P2|ADAR_+_154600408.23-P2',
 'ADAT1_+_75657125.23-P1P2|ADAT1_+_75656919.23-P1P2',
 'ADAT2_-_143771826.23-P1P2|ADAT2_+_143771740.23-P1P2',
 'ADAT3_+_1907955.23-P2|ADAT3_+_1908004.23-P2',
 'ADAT3_-_1905438.23-P1|ADAT3_+_1905424.23-P1',
 'ADA_+_43280285.23-P1P2|ADA_+_43280282.23-P1P2',
 'ADCK2_+_140372748.23-P1P2|ADCK2_+_140372768.23-P1P2',
 'ADCK3_-_227128046.23-P1P2|ADCK3_-_227128055.23-P1P2',
 'ADCK4_+_41222752.23-P1P2|ADCK4_-_41222769.23-P1P2',
 'ADCK5_+_145597793.23-P1P2|ADCK5_-_145597781.23-P1P2',
 'ADCY3_-_25143044.23-P1P2|ADCY3_-_25142849.23-P1P2',
 'ADCY7_-_50300524.23-P1P2|ADCY7_-_50300498.23-P1P2',
 'ADD1_-_2845605.23-P1P2|ADD1_-_2845599.23-P1P2',
 'ADD2_+_70995263.23-P1P2|ADD2_+_70995300.23-P1P2',
 'ADD3_-_111767767.23-P1P2|ADD3_-_111767783.23-P1P2',
 'ADH5_+_100009821.23-P1P2|ADH5_+_100009684.23-P1P2',
 'ADI1_+_3523275.23-P1P2|ADI1_-_3523293.23-P1P2',
 'ADIPOR1_+_202927394.23-P1P2|ADIPOR1_-_202927375.23-P1P2',
 'ADIPOR2_-_1800242.23-P1P2|ADIPOR2_-_1800278.23-P1P2',
 'ADK_-_75911025.23-P2|ADK_-_75911021.23-P2',
 'ADK_-_75936578.23-P1|ADK_+_75936517.23-P1',
 'ADNP2_-_77867648.23-P1P2|ADNP2_-_77867365.23-P1P2',
 'ADNP_+_49547361.23-P1P2|ADNP_-_49547707.23-P1P2',
 'ADORA2B_-_15848791.23-P1P2|ADORA2B_+_15848650.23-P1P2',
 'ADO_-_64564781.23-P1P2|ADO_-_64564623.23-P1P2',
 'ADPGK_+_73076082.23-P1P2|ADPGK_+_73076066.23-P1P2',
 'ADPRHL2_+_36554555.23-P1P2|ADPRHL2_-_36554523.23-P1P2',
 'ADRBK1_-_67033953.23-P1P2|ADRBK1_+_67033933.23-P1P2',
 'ADRBK2_+_25960616.23-P1P2|ADRBK2_-_25960625.23-P1P2',
 'ADRM1_+_60878013.23-P1P2|ADRM1_-_60878073.23-P1P2',
 'ADSL_-_40742737.23-P1P2|ADSL_-_40742729.23-P1P2',
 'ADSS_-_244615160.23-P1P2|ADSS_-_244615191.23-P1P2',
 'ADTRP_-_11779009.23-P1P2|ADTRP_-_11778993.23-P1P2',
 'AEBP1_+_44143999.23-P1P2|AEBP1_+_44144026.23-P1P2',
 'AEBP2_+_19592658.23-P1P2|AEBP2_+_19592704.23-P1P2',
 'AEN_-_89164606.23-P1P2|AEN_-_89164638.23-P1P2',
 'AES_-_3062479.23-P1P2|AES_-_3062476.23-P1P2',
 'AFF1_+_87856192.23-P1P2|AFF1_-_87856182.23-P1P2',
 'AFF4_-_132299252.23-P1P2|AFF4_+_132299267.23-P1P2',
 'AFG3L2_-_12377212.23-P1P2|AFG3L2_-_12377232.23-P1P2',
 'AFMID_+_76183477.23-P1P2|AFMID_+_76183490.23-P1P2',
 'AFTPH_-_64751594.23-P1P2|AFTPH_-_64751572.23-P1P2',
 'AGAP1_+_236403013.23-P1P2|AGAP1_-_236402788.23-P1P2',
 'AGAP3_-_150783602.23-P1P2|AGAP3_+_150783556.23-P1P2',
 'AGA_+_178363535.23-P1P2|AGA_-_178363567.23-P1P2',
 'AGBL5_+_27274578.23-P1|AGBL5_+_27274969.23-P1',
 'AGBL5_+_27276183.23-P2|AGBL5_+_27275965.23-P2',
 'AGFG1_-_228336893.23-P1P2|AGFG1_-_228336896.23-P1P2',
 'AGFG2_-_100136951.23-P1P2|AGFG2_-_100136848.23-P1P2',
 'AGGF1_+_76326273.23-P1P2|AGGF1_+_76326308.23-P1P2',
 'AGK_-_141251386.23-P1P2|AGK_-_141251280.23-P1P2',
 'AGL_-_100315679.23-P1P2|AGL_-_100315704.23-P1P2',
 'AGO1_-_36349067.23-P1P2|AGO1_-_36349041.23-P1P2',
 'AGO2_-_141645534.23-P1P2|AGO2_+_141645724.23-P1P2',
 'AGO3_+_36396775.23-P1P2|AGO3_-_36396745.23-P1P2',
 'AGPAT1_+_32143853.23-P1|AGPAT1_+_32143856.23-P1',
 'AGPAT1_+_32144829.23-P2|AGPAT1_+_32145529.23-P2',
 'AGPAT2_+_139581621.23-P1P2|AGPAT2_-_139581678.23-P1P2',
 'AGPAT3_+_45285114.23-P1P2|AGPAT3_+_45285099.23-P1P2',
 'AGPAT4_+_161694832.23-P1P2|AGPAT4_-_161695108.23-P1P2',
 'AGPAT5_+_6566209.23-P1P2|AGPAT5_+_6566173.23-P1P2',
 'AGPS_-_178257526.23-P1P2|AGPS_-_178257523.23-P1P2',
 'AGRN_+_955534.23-P1P2|AGRN_+_955472.23-P1P2',
 'AGTRAP_+_11796247.23-P1P2|AGTRAP_+_11796254.23-P1P2',
 'AHCTF1_-_247095134.23-P1P2|AHCTF1_+_247094988.23-P1P2',
 'AHCYL1_-_110527422.23-P1|AHCYL1_-_110527436.23-P1',
 'AHCYL1_-_110546765.23-P2|AHCYL1_+_110546691.23-P2',
 'AHCY_-_32891145.23-P1P2|AHCY_-_32890950.23-P1P2',
 'AHDC1_+_27930650.23-P1P2|AHDC1_+_27930664.23-P1P2',
 'AHI1_-_135818658.23-P1P2|AHI1_-_135818819.23-P1P2',
 'AHNAK_+_62313083.23-P2|AHNAK_+_62313086.23-P2',
 'AHNAK_-_62314257.23-P1|AHNAK_-_62314203.23-P1',
 'AHRR_+_321892.23-P1P2|AHRR_+_322709.23-P1P2',
 'AHR_-_17338343.23-P1P2|AHR_+_17338317.23-P1P2',
 'AHSA1_-_77924482.23-P1P2|AHSA1_-_77924875.23-P1P2',
 'AHSA2_+_61404654.23-P1P2|AHSA2_+_61404634.23-P1P2',
 'AHSP_-_31539252.23-P1P2|AHSP_+_31539439.23-P1P2',
 'AIDA_-_222885963.23-P1P2|AIDA_-_222885496.23-P1P2',
 'AIF1_+_31583079.23-P1P2|AIF1_-_31583032.23-P1P2',
 'AIFM1_-_129299770.23-P1P2|AIFM1_+_129299638.23-P1P2',
 'AIFM2_+_71892557.23-P1P2|AIFM2_+_71892542.23-P1P2',
 'AIG1_+_143382079.23-P1P2|AIG1_+_143382050.23-P1P2',
 'AIM1_-_106960473.23-P1P2|AIM1_-_106960486.23-P1P2',
 'AIMP1_+_107237731.23-P1P2|AIMP1_+_107237742.23-P1P2',
 'AIMP2_+_6048922.23-P1P2|AIMP2_-_6048940.23-P1P2',
 'AIP_+_67250544.23-P1P2|AIP_-_67250576.23-P1P2',
 'AIRE_-_45705829.23-P1P2|AIRE_+_45705833.23-P1P2',
 'AK1_-_130639906.23-P1P2|AK1_+_130639940.23-P1P2',
 'AK2_+_33502475.23-P1P2|AK2_+_33502042.23-P1P2',
 'AK3_-_4741156.23-P1P2|AK3_-_4741205.23-P1P2',
 'AK4_-_65613902.23-P1P2|AK4_+_65613321.23-P1P2',
 'AKAP11_+_42846479.23-P1P2|AKAP11_+_42846688.23-P1P2',
 'AKAP13_+_85923863.23-P1P2|AKAP13_+_85923876.23-P1P2',
 'AKAP17A_+_1710540.23-P1P2|AKAP17A_-_1710549.23-P1P2',
 'AKAP1_-_55162653.23-P1P2|AKAP1_-_55162661.23-P1P2',
 'AKAP8L_-_15529435.23-P1P2|AKAP8L_-_15529375.23-P1P2',
 'AKAP8_+_15490555.23-P1P2|AKAP8_+_15490566.23-P1P2',
 'AKAP9_+_91570225.23-P1P2|AKAP9_+_91570248.23-P1P2',
 'AKIP1_-_8932793.23-P1P2|AKIP1_-_8932799.23-P1P2',
 'AKIRIN1_+_39456935.23-P1P2|AKIRIN1_-_39457004.23-P1P2',
 'AKIRIN2_-_88411464.23-P1P2|AKIRIN2_+_88411936.23-P1P2',
 'AKNA_+_117150220.23-P1|AKNA_+_117150244.23-P1',
 'AKNA_+_117160706.23-P2|AKNA_+_117160729.23-P2',
 'AKR1A1_+_46016701.23-P1P2|AKR1A1_-_46016592.23-P1P2',
 'AKR1C1_+_5005615.23-P1P2|AKR1C1_+_5005619.23-P1P2',
 'AKR1C2_-_5046012.23-P1|AKR1C2_+_5046039.23-P1',
 'AKR1C2_-_5060075.23-P2|AKR1C2_+_5059865.23-P2',
 'AKR1E2_+_4868442.23-P1P2|AKR1E2_+_4868462.23-P1P2',
 'AKR7A2_-_19638583.23-P1P2|AKR7A2_-_19638512.23-P1P2',
 'AKT1S1_+_50379848.23-P1P2|AKT1S1_+_50379851.23-P1P2',
 'AKT1_+_105261633.23-P1P2|AKT1_+_105262011.23-P1P2',
 'AKT2_+_40791298.23-P1P2|AKT2_-_40791096.23-P1P2',
 'ALAD_+_116163528.23-P1P2|ALAD_-_116163505.23-P1P2',
 'ALAS1_+_52232365.23-P1P2|ALAS1_-_52232170.23-P1P2',
 'ALAS2_-_55057349.23-P1P2|ALAS2_+_55057338.23-P1P2',
 'ALDH16A1_+_49956535.23-P1P2|ALDH16A1_-_49956532.23-P1P2',
 'ALDH18A1_+_97416133.23-P1P2|ALDH18A1_+_97416448.23-P1P2',
 'ALDH1A1_-_75567941.23-P1P2|ALDH1A1_-_75567897.23-P1P2',
 'ALDH1A2_-_58357877.23-P1P2|ALDH1A2_+_58357872.23-P1P2',
 'ALDH1B1_+_38392764.23-P1P2|ALDH1B1_+_38392957.23-P1P2',
 'ALDH2_+_112204799.23-P1P2|ALDH2_+_112204778.23-P1P2',
 'ALDH4A1_-_19228972.23-P1P2|ALDH4A1_-_19229032.23-P1P2',
 'ALDH5A1_+_24495207.23-P1P2|ALDH5A1_+_24495537.23-P1P2',
 'ALDH9A1_-_165667740.23-P1P2|ALDH9A1_-_165667800.23-P1P2',
 'ALDOA_+_30077139.23-P1P2|ALDOA_+_30077177.23-P1P2',
 'ALDOC_+_26903892.23-P1P2|ALDOC_-_26903885.23-P1P2',
 'ALG11_+_52586530.23-P1P2|ALG11_-_52586543.23-P1P2',
 'ALG12_+_50312054.23-P1P2|ALG12_-_50312053.23-P1P2',
 'ALG13_+_110924898.23-P1P2|ALG13_+_110924465.23-P1P2',
 'ALG14_+_95538155.23-P1P2|ALG14_+_95538302.23-P1P2',
 'ALG1L_-_125655482.23-ENST00000340333.3|ALG1L_-_125655452.23-ENST00000340333.3',
 'ALG1_+_5122098.23-P1P2|ALG1_+_5121857.23-P1P2',
 'ALG2_-_101984133.23-P1P2|ALG2_+_101984159.23-P1P2',
 'ALG3_-_183966701.23-P1P2|ALG3_+_183966721.23-P1P2',
 'ALG5_+_37573440.23-P1P2|ALG5_-_37573057.23-P1P2',
 'ALG6_+_63833373.23-P1P2|ALG6_-_63833380.23-P1P2',
 'ALG8_+_77850627.23-P1P2|ALG8_-_77850641.23-P1P2',
 'ALG9_-_111742019.23-P1P2|ALG9_+_111742236.23-P1P2',
 'ALKBH2_+_109531250.23-P1P2|ALKBH2_+_109531240.23-P1P2',
 'ALKBH3_-_43902421.23-P1P2|ALKBH3_+_43902434.23-P1P2',
 'ALKBH4_-_102105260.23-P1P2|ALKBH4_-_102105269.23-P1P2',
 'ALKBH5_-_18087161.23-P1P2|ALKBH5_-_18087178.23-P1P2',
 'ALKBH6_+_36505031.23-P1P2|ALKBH6_+_36505140.23-P1P2',
 'ALKBH7_+_6372803.23-P1P2|ALKBH7_+_6372823.23-P1P2',
 'ALKBH8_+_107436405.23-P1P2|ALKBH8_+_107436425.23-P1P2',
 'ALMS1_+_73612991.23-P1P2|ALMS1_-_73612999.23-P1P2',
 'ALS2_+_202645584.23-P1P2|ALS2_-_202645613.23-P1P2',
 'ALX1_+_85674007.23-P1P2|ALX1_+_85674064.23-P1P2',
 'ALX3_-_110613186.23-P1P2|ALX3_-_110613212.23-P1P2',
 'ALX4_-_44331565.23-P1P2|ALX4_-_44331571.23-P1P2',
 'ALYREF_-_79849458.23-P1P2|ALYREF_-_79849452.23-P1P2',
 'AMBRA1_+_46615541.23-P1P2|AMBRA1_-_46615538.23-P1P2',
 'AMD1_-_111196001.23-P1P2|AMD1_-_111196005.23-P1P2',
 'AMDHD2_-_2570401.23-P1P2|AMDHD2_+_2570434.23-P1P2',
 'AMFR_+_56459315.23-P1P2|AMFR_-_56459192.23-P1P2',
 'AMHR2_+_53818923.23-P1P2|AMHR2_+_53819137.23-P1P2',
 'AMH_+_2248626.23-P1P2|AMH_-_2248783.23-P1P2',
 'AMMECR1_+_109561105.23-P1P2|AMMECR1_+_109560923.23-P1P2',
 'AMN1_-_31881933.23-P1P2|AMN1_-_31881912.23-P1P2',
 'AMOTL1_-_94501700.23-P1P2|AMOTL1_-_94501686.23-P1P2',
 'AMPD2_+_110163780.23-P2|AMPD2_-_110163800.23-P2',
 'AMPD2_-_110162501.23-P1|AMPD2_+_110162524.23-P1',
 'AMPD3_-_10476823.23-P1P2|AMPD3_-_10476980.23-P1P2',
 'AMZ2_-_66244231.23-P1P2|AMZ2_-_66244242.23-P1P2',
 'ANAPC10_+_146019314.23-P1P2|ANAPC10_+_146019317.23-P1P2',
 'ANAPC11_-_79849637.23-P1P2|ANAPC11_+_79849685.23-P1P2',
 'ANAPC13_-_134204795.23-P1P2|ANAPC13_+_134204787.23-P1P2',
 'ANAPC15_+_71823713.23-P1P2|ANAPC15_-_71823727.23-P1P2',
 'ANAPC16_+_73975790.23-P1P2|ANAPC16_+_73975820.23-P1P2',
 'ANAPC1_-_112641691.23-P1P2|ANAPC1_-_112641707.23-P1P2',
 'ANAPC2_+_140082989.23-P1P2|ANAPC2_+_140082980.23-P1P2',
 'ANAPC4_+_25378934.23-P1P2|ANAPC4_-_25378954.23-P1P2',
 'ANAPC5_+_121790181.23-P1P2|ANAPC5_-_121790201.23-P1P2',
 'ANAPC7_-_110841548.23-P1P2|ANAPC7_+_110841268.23-P1P2',
 'ANGEL2_+_213188508.23-P1P2|ANGEL2_+_213188808.23-P1P2',
 'ANGPT1_+_108510112.23-P1P2|ANGPT1_+_108510118.23-P1P2',
 'ANHX_+_133812391.23-P1P2|ANHX_+_133812402.23-P1P2',
 'ANK1_-_41655052.23-P1P2|ANK1_-_41655095.23-P1P2',
 'ANK3_+_62149513.23-P1P2|ANK3_+_62149538.23-P1P2',
 'ANKFY1_+_4166925.23-P1P2|ANKFY1_-_4167096.23-P1P2',
 'ANKHD1_+_139781466.23-P1P2|ANKHD1_-_139781454.23-P1P2',
 'ANKIB1_-_91875700.23-P1P2|ANKIB1_+_91875590.23-P1P2',
 'ANKLE1_-_17392727.23-P1P2|ANKLE1_+_17392722.23-P1P2',
 'ANKLE2_+_133338375.23-P1P2|ANKLE2_+_133338404.23-P1P2',
 'ANKMY1_+_241497155.23-P1P2|ANKMY1_+_241497400.23-P1P2',
 'ANKMY2_+_16685345.23-P1P2|ANKMY2_-_16685324.23-P1P2',
 'ANKRA2_+_72861001.23-P1P2|ANKRA2_-_72861459.23-P1P2',
 'ANKRD10_+_111567378.23-P1P2|ANKRD10_-_111567334.23-P1P2',
 'ANKRD11_+_89556932.23-P1P2|ANKRD11_-_89556765.23-P1P2',
 'ANKRD12_-_9136808.23-P1P2|ANKRD12_+_9137050.23-P1P2',
 'ANKRD13A_+_110437696.23-P1P2|ANKRD13A_+_110437230.23-P1P2',
 'ANKRD13B_+_27920377.23-P1P2|ANKRD13B_+_27920172.23-P1P2',
 'ANKRD13C_+_70820351.23-P1P2|ANKRD13C_-_70820382.23-P1P2',
 'ANKRD13D_+_67056813.23-P1P2|ANKRD13D_-_67056373.23-P1P2',
 'ANKRD16_+_5931865.23-P1P2|ANKRD16_+_5931814.23-P1P2',
 'ANKRD17_+_74124528.23-P1P2|ANKRD17_+_74124315.23-P1P2',
 'ANKRD26_-_27389221.23-P1P2|ANKRD26_+_27389387.23-P1P2',
 'ANKRD27_+_33166026.23-P1P2|ANKRD27_+_33166056.23-P1P2',
 'ANKRD28_-_15839402.23-P1P2|ANKRD28_+_15839382.23-P1P2',
 'ANKRD33B_+_10564429.23-P1P2|ANKRD33B_+_10564449.23-P1P2',
 'ANKRD36C_-_96657460.23-P1P2|ANKRD36C_-_96657464.23-P1P2',
 'ANKRD36_+_97779467.23-P1P2|ANKRD36_-_97779499.23-P1P2',
 'ANKRD39_+_97523562.23-P1P2|ANKRD39_-_97523708.23-P1P2',
 'ANKRD40_+_48785164.23-P1P2|ANKRD40_+_48785242.23-P1P2',
 'ANKRD46_-_101571968.23-P1P2|ANKRD46_-_101571982.23-P1P2',
 'ANKRD49_+_94226755.23-P1P2|ANKRD49_-_94226994.23-P1P2',
 'ANKRD52_-_56652125.23-P1P2|ANKRD52_-_56651964.23-P1P2',
 'ANKRD54_+_38240313.23-P1P2|ANKRD54_+_38240316.23-P1P2',
 'ANKRD9_-_102976042.23-P1P2|ANKRD9_+_102976027.23-P1P2',
 'ANKS1A_+_34857078.23-P1P2|ANKS1A_+_34857121.23-P1P2',
 'ANKS3_+_4784206.23-P1P2|ANKS3_+_4784180.23-P1P2',
 'ANKS6_+_101558408.23-P1P2|ANKS6_-_101558384.23-P1P2',
 'ANKZF1_+_220094583.23-P1P2|ANKZF1_+_220094518.23-P1P2',
 'ANLN_-_36429483.23-P1P2|ANLN_+_36429487.23-P1P2',
 'ANO10_-_43663459.23-P1P2|ANO10_-_43663456.23-P1P2',
 'ANO6_-_45609917.23-P1P2|ANO6_-_45609946.23-P1P2',
 'ANP32A_-_69112836.23-P1P2|ANP32A_-_69113252.23-P1P2',
 'ANP32B_+_100745631.23-P1P2|ANP32B_-_100745885.23-P1P2',
 'ANP32E_+_150208436.23-P1P2|ANP32E_-_150208476.23-P1P2',
 'ANTXR2_-_80994347.23-P1P2|ANTXR2_+_80994354.23-P1P2',
 'ANXA11_-_81965250.23-P1P2|ANXA11_-_81965296.23-P1P2',
 'ANXA1_-_75766840.23-P1P2|ANXA1_+_75766778.23-P1P2',
 'ANXA2R_-_43040242.23-P1P2|ANXA2R_-_43040188.23-P1P2',
 'ANXA2_-_60690116.23-P1P2|ANXA2_-_60690106.23-P1P2',
 'ANXA3_+_79472940.23-P1P2|ANXA3_-_79472946.23-P1P2',
 'ANXA4_-_69969324.23-P1P2|ANXA4_+_69969241.23-P1P2',
 'ANXA5_-_122618118.23-P1P2|ANXA5_-_122618086.23-P1P2',
 'ANXA6_-_150537278.23-P1P2|ANXA6_+_150537317.23-P1P2',
 'ANXA7_+_75173793.23-P1P2|ANXA7_-_75173729.23-P1P2',

### Rename `sgID_AB` to `perturbation_name`

In [10]:
cur_data.rename_columns(slot = 'obs', name_dict = {'sgID_AB': 'perturbation_name'})

Renamed columns in adata.obs: {'sgID_AB': 'perturbation_name'}

### Add guide RNA information

In [11]:
# download the guide RNA spreadsheet
download_file(
    url="https://ars.els-cdn.com/content/image/1-s2.0-S0092867422005979-mmc1.xlsx",
    dest_path="../supplementary/replogle_2022_guide_info.xlsx"
)

# read in the guide RNA spreadsheet
# guides for the K562 essential day 6 library are in "TabB_K562_day6_library"
guide_info_df = pd.read_excel("../supplementary/replogle_2022_guide_info.xlsx", sheet_name="TabA_K562_day8_library")

# create perturbation_name column in guide_info_df
guide_info_df['perturbation_name'] = guide_info_df['sgID_A'] + '|' + guide_info_df['sgID_B']
# replace commas with hyphens in perturbation_name
guide_info_df['perturbation_name'] = guide_info_df['perturbation_name'].str.replace(',', '-')
# check that all perturbation names in cur_data are in guide_info_df
print(f"All perturbation names in cur_data are in guide_info_df: {cur_data.adata.obs['perturbation_name'].isin(guide_info_df['perturbation_name']).all()}")
# create guide_sequence column in guide_info_df
guide_info_df['guide_sequence'] = guide_info_df['targeting sequence A'] + '|' + guide_info_df['targeting sequence B']
# subset for necessary columns
guide_info_df = guide_info_df[['perturbation_name', 'guide_sequence']]
# merge cur_data.adata.obs with guide_info_df on perturbation_name
cur_data.adata.obs = cur_data.adata.obs.merge(guide_info_df, on='perturbation_name', how='left')
# check that there are no missing guide sequences
print(f"Number of missing guide sequences: {cur_data.adata.obs['guide_sequence'].isna().sum()}")

File ../supplementary/replogle_2022_guide_info.xlsx already exists. Skipping download.
All perturbation names in cur_data are in guide_info_df: True

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

Number of missing guide sequences: 0

### Standardise perturbation targets

In [12]:
cur_data.standardize_genes(
    slot='obs',
    input_column='gene',
    input_column_type='gene_symbol',
    multiple_entries=False
)

Mapping gene symbols: 100%|██████████████████████████████████| 9867/9867 [00:00<00:00, 25539.50it/s]

--------------------------------------------------
Successfully mapped 9862 out of 9867 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['non-targeting', 'AC015871.1', 'MTRNR2L1', 'AC118549.1', 'MTRNR2L8']
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Add `perturbed_target_number` column

In [13]:
cur_data.count_entries(
    slot='obs',
    input_column='perturbed_target_symbol',
    count_column_name='perturbed_target_number',
    sep='|'
)

Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [14]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

In [15]:
cur_data.show_obs(['perturbation_name', 'perturbed_target_chromosome_encoding'])

Observation data:
DataFrame shape: (1989578, 2)
--------------------------------------------------
                                         perturbation_name  \
index
0          CTSC_-_88070848.23-P1P2|CTSC_-_88070918.23-P1P2
1        CWC25_+_36981555.23-P1P2|CWC25_+_36981567.23-P1P2
2        PDE4DIP_+_144932474.23-ENST00000313431.9|PDE4D...
3          ZZEF1_+_4046247.23-P1P2|ZZEF1_+_4046255.23-P1P2
4        SNAPIN_+_153631238.23-P1P2|SNAPIN_-_153631252....
...                                                    ...
1989573  SCRIB_-_144897465.23-P1P2|SCRIB_-_144897339.23...
1989574  CADM4_+_44143915.23-P1P2|CADM4_+_44143932.23-P1P2
1989575  SLC4A7_+_27525847.23-P1P2|SLC4A7_+_27525631.23...
1989576  TMEM131_-_98612356.23-P1P2|TMEM131_-_98612239....
1989577  SRP14_+_40331287.23-P1P2|SRP14_-_40330986.23-P1P2

         perturbed_target_chromosome_encoding
index
0                                          11
1                                          17
2                                           1
3                                          17
4                                           1
...                                       ...
1989573                                     8
1989574                                    19
1989575                                     3
1989576                                     2
1989577                                    15

[1989578 rows x 2 columns]
--------------------------------------------------

### Add metadata

In [16]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        "dataset_id": cur_data.dataset_id,
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        # perturbation type
        "perturbation_type_label": "CRISPRi",
        "perturbation_type_id": None,
        "data_modality": "Perturb-seq",
        "significant": None,
        "significance_criteria": None,
        "score_interpretation": None,

        # treatment
        "treatment_label": None,
        "treatment_id": None,
        # replicates
        "technical_replicate": None,
        "biological_replicate": None,
        # model system
        "model_system_label": "cell_line",
        "model_system_id": None,
        "tissue": "blood",
        "cell_line_label": "K 562 cell",
        "cell_type_label": "lymphoblast",
        "disease_label": "chronic myelogenous leukemia, BCR-ABL1 positive",

        "timepoint": "P8DT0H0M0S",
        "species": "Homo sapiens",
        "sex_label": "female",
        "sex_id": None,
        "developmental_stage_label": "adult",
        "developmental_stage_id": None,

        "study_title": "Mapping information-rich genotype-phenotype landscapes with genome-scale Perturb-seq",
        "study_uri": "https://doi.org/10.1016/j.cell.2022.05.013",
        "study_year": 2022,
        "first_author": "Joseph M Replogle",
        "last_author": "Jonathan S Weissman",

        "experiment_title": "K562 day 8 essential-scale Perturb-seq experiment",
        "experiment_summary": """
            K562 chronic myeloid leukemia cells were transduced with a sgRNA library targeting genes expressed in K562 cells, transcription factors as detailed in Lambert et al. (2018) and Cancer Dependency Map common essential genes.
            A total of 9,866 genes were targeted.
            Cells were sampled at day 8 after lentiviral transduction.
            Multiplexed CRISPRi library containing two distinct guides targeting the same gene were used.
            """,

        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],

        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",

        "library_generation_method_id": None,
        "library_generation_method_label": "dCas9-KRAB",

        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "lentivirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",

        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",

        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",

        "library_name": "custom",
        "library_uri": None,

        "library_format_id": None,
        "library_format_label": "pooled",

        "library_scope_id": None,
        "library_scope_label": "focused",

        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "inhibition",

        "library_manufacturer": "Weissman Lab",
        "library_lentiviral_generation": "3",
        "library_grnas_per_target": "2",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()),
        "library_total_variants": None,

        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",

        "readout_type_id": None,
        "readout_type_label": "transcriptomic",

        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",

        "method_name_id": None,
        "method_name_label": "Perturb-seq",

        "method_uri": None,

        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "10x Genomics Single Cell 3-prime v3",

        "sequencing_platform_id": None,
        "sequencing_platform_label": "Ultima Genomics UG100",

        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",

        "software_counts_id": None,
        "software_counts_label": "CellRanger",

        "software_analysis_id": None,
        "software_analysis_label": "custom",

        "reference_genome_id": None,
        "reference_genome_label": "GRCh38",
        
        "license_label": "CC BY 4.0",
        "license_id": "SWO:1000065",

        "associated_datasets": json.dumps([
            {
                "dataset_accession": "K562_gwps_raw_bulk_01",
                "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774443",
                "dataset_description": "Raw, pseudo-bulk expression data for genes expressed at >0.01 UMI per cell",
                "dataset_file_name": "K562_gwps_raw_bulk_01.h5ad",
            },
            {
                "dataset_accession": "K562_gwps_normalized_bulk_01",
                "dataset_uri": "https://plus.figshare.com/ndownloader/files/35773217",
                "dataset_description": "Gemgroup Z-normalized pseudo-bulk expression data for genes expressed at >0.01 UMI per cell",
                "dataset_file_name": "K562_gwps_normalized_bulk_01.h5ad",
            },
            {
                "dataset_accession": "K562_gwps_raw_singlecell_01",
                "dataset_uri": "https://plus.figshare.com/ndownloader/files/35775507",
                "dataset_description": "Raw, single-cell expression data for genes expressed at >0.01 UMI per cell",
                "dataset_file_name": "K562_gwps_raw_singlecell_01.h5ad",
            },
            {
                "dataset_accession": "K562_gwps_normalized_singlecell_01",
                "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774440",
                "dataset_description": "Gemgroup Z-normalized single-cell expression data for genes expressed at >0.01 UMI per cell",
                "dataset_file_name": "K562_gwps_normalized_singlecell_01.h5ad",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column treatment_label added to adata.obs
Column treatment_id added to adata.obs
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_type_label added to adata.obs
Column disease_label added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_manufacturer added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

In [17]:
cur_data.adata.obs

,gene_id,guide_sequence,gene,transcript,z_gemgroup_UMI,cell_barcode,gem_group,UMI_count,core_adjusted_UMI_count,core_scale_factor,...,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,reference_genome_id,reference_genome_label,license_label,license_id,associated_datasets
index,,,,,,,,,,,,,,,,,,,,,
0,ENSG00000109861,GGCCCAGCACCCATGCTGCA|GTAGCGGTGAGTCCACCACG,CTSC,P1P2,0.470687,AAACCCAAGAAACCAT-157,157,14709.0,13992.900391,1.051176,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
1,ENSG00000273559,GTCTAGAGCGGTGGTGAAAC|GCCGGAAGTGACCTCTAGAG,CWC25,P1P2,0.824790,AAACCCAAGAAACCAT-207,207,16162.0,15038.004883,1.074744,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
2,ENSG00000178104,GGGCGCGCAGCGGTACCTAG|GGAGCCGGAAGCCCGCTGAC,PDE4DIP,ENST00000313431.9,2.627126,AAACCCAAGAAACCAT-29,29,33297.0,22613.423828,1.472444,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
3,ENSG00000074755,GGCTGCTGTCGGAGGTTGAC|GGCCCGCCAGCTGCTGTCGG,ZZEF1,P1P2,0.918149,AAACCCAAGAAAGCGA-149,149,7435.0,15476.669922,0.480401,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
4,ENSG00000143553,GGTCCCTGCCCCCGATACAG|GGGTTCCGCCGCTGTATCGG,SNAPIN,P1P2,-0.230920,AAACCCAAGAAATCCA-172,172,7755.0,11147.856445,0.695649,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989573,ENSG00000180900,GCGGTAGATCTCCTCCGGCA|GCTGCCGCCGGAGGAATCAC,SCRIB,P1P2,-0.441665,TTTGTTGTCTTTCCAA-201,201,11867.0,10302.698242,1.151834,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
1989574,ENSG00000105767,GCCGGGCCCGGCGCTTCCAG|GGGCGGCGGCACCATGGGCC,CADM4,P1P2,-1.208969,TTTGTTGTCTTTCGAT-79,79,6437.0,6882.660156,0.935249,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
1989575,ENSG00000033867,GAGCTTCAGGTTCCACGCCG|GGTACCGTAGCGGCCGTCAC,SLC4A7,P1P2,-0.109167,TTTGTTGTCTTTCTAG-218,218,11377.0,11376.682617,1.000028,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
1989576,ENSG00000075568,GACAAGCAGTCGGAGCGGAG|GGCGGCGCCGGGAGCGACAA,TMEM131,P1P2,-0.358464,TTTGTTGTCTTTGCGC-169,169,10658.0,10417.442383,1.023092,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."
1989577,ENSG00000140319,GGTTGGAGAGCGAGCAGGTA|GACAGGGTGGGGAAAGGTAG,SRP14,P1P2,0.284907,TTTGTTGTCTTTGCGC-213,213,18287.0,13078.065430,1.398296,...,barcode sequencing,None,CellRanger,None,custom,None,GRCh38,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""..."

### Curate replicate information

In [18]:
cur_data.adata.obs['technical_replicate'] = cur_data.adata.obs['gem_group'].astype(str)

### Curate tissue information

In [19]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower     ontology_id
0        blood              blood      blood  UBERON:0000178
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [20]:
cur_data.standardize_ontology(
    input_column='cell_type_label',
    column_type='term_name',
    ontology_type='cell_type',
    overwrite=True
)

Mapped 1 cell_type ontology terms from `cell_type_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower   name_lower ontology_id
0  lymphoblast        lymphoblast  lymphoblast  CL:0017005
--------------------------------------------------
Overwriting column cell_type_label in adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell line information

In [21]:
cur_data.standardize_ontology(
    input_column='cell_line_label',
    column_type='term_name',
    ontology_type='cell_line',
    overwrite=True
)

Mapped 1 cell_line ontology terms from `cell_line_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower  name_lower  ontology_id
0   K 562 cell         k 562 cell  k 562 cell  CLO:0007050
--------------------------------------------------
Overwriting column cell_line_label in adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [22]:
cur_data.standardize_ontology(
    input_column='disease_label',
    column_type='term_name',
    ontology_type='disease',
    overwrite=True
)

Mapped 1 disease ontology terms from `disease_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
                                      input_column  \
0  chronic myelogenous leukemia, BCR-ABL1 positive

                                input_column_lower  \
0  chronic myelogenous leukemia, bcr-abl1 positive

                                        name_lower    ontology_id
0  chronic myelogenous leukemia, bcr-abl1 positive  MONDO:0011996
--------------------------------------------------
Overwriting column disease_label in adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Match schema column order

In [23]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [24]:
cur_data.validate_data(slot='obs', verbose=True)

2026-04-23 13:27:31,571 DEBUG curation_tools.curation_tools: Applying dtype casting on adata.obs for columns: ['dataset_id', 'sample_id', 'cell_barcode', 'data_modality', 'significant', 'significance_criteria', 'perturbation_name', 'perturbed_target_coord', 'perturbed_target_chromosome', 'perturbed_target_chromosome_encoding', 'perturbed_target_number', 'perturbed_target_ensg', 'perturbed_target_symbol', 'perturbed_target_biotype', 'guide_sequence', 'perturbation_type_label', 'perturbation_type_id', 'timepoint', 'treatment_label', 'treatment_id', 'technical_replicate', 'biological_replicate', 'model_system_label', 'model_system_id', 'species', 'tissue_label', 'tissue_id', 'cell_type_label', 'cell_type_id', 'cell_line_label', 'cell_line_id', 'sex_label', 'sex_id', 'developmental_stage_label', 'developmental_stage_id', 'disease_label', 'disease_id', 'study_title', 'study_uri', 'study_year', 'first_author', 'last_author', 'experiment_title', 'experiment_summary', 'number_of_perturbed_targets', 'number_of_perturbed_samples', 'library_generation_type_id', 'library_generation_type_label', 'library_generation_method_id', 'library_generation_method_label', 'enzyme_delivery_method_id', 'enzyme_delivery_method_label', 'library_delivery_method_id', 'library_delivery_method_label', 'enzyme_integration_state_id', 'enzyme_integration_state_label', 'library_integration_state_id', 'library_integration_state_label', 'enzyme_expression_control_id', 'enzyme_expression_control_label', 'library_expression_control_id', 'library_expression_control_label', 'library_name', 'library_uri', 'library_format_id', 'library_format_label', 'library_scope_id', 'library_scope_label', 'library_perturbation_type_id', 'library_perturbation_type_label', 'library_manufacturer', 'library_lentiviral_generation', 'library_grnas_per_target', 'library_total_grnas', 'library_total_variants', 'readout_dimensionality_id', 'readout_dimensionality_label', 'readout_type_id', 'readout_type_label', 'readout_technology_id', 'readout_technology_label', 'method_name_id', 'method_name_label', 'method_uri', 'sequencing_library_kit_id', 'sequencing_library_kit_label', 'sequencing_platform_id', 'sequencing_platform_label', 'sequencing_strategy_id', 'sequencing_strategy_label', 'software_counts_id', 'software_counts_label', 'software_analysis_id', 'software_analysis_label', 'score_interpretation', 'reference_genome_id', 'reference_genome_label', 'associated_datasets', 'license_label', 'license_id']
2026-04-23 13:28:19,798 INFO curation_tools.curation_tools: adata.obs is valid according to the obs_schema.
2026-04-23 13:28:19,818 DEBUG curation_tools.curation_tools: Validated adata.obs preview (shape=(1989578, 100)):
                  dataset_id sample_id          cell_barcode data_modality significant significance_criteria                                                                  perturbation_name      perturbed_target_coord perturbed_target_chromosome  perturbed_target_chromosome_encoding  perturbed_target_number perturbed_target_ensg perturbed_target_symbol perturbed_target_biotype                             guide_sequence perturbation_type_label perturbation_type_id   timepoint treatment_label treatment_id technical_replicate biological_replicate model_system_label model_system_id       species tissue_label       tissue_id cell_type_label cell_type_id cell_line_label cell_line_id sex_label sex_id developmental_stage_label developmental_stage_id                                    disease_label     disease_id                                                                           study_title                                   study_uri  study_year       first_author          last_author                                   experiment_title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                experiment_summary number_of_perturbed_targets number_of_perturbed_samples library_generation_type_id library_generation_type_label library_generation_method_id library_generation_method_label enzyme_delivery_method_id enzyme_delivery_method_label library_delivery_method_id library_delivery_method_label enzyme_integration_state_id enzyme_integration_state_label library_integration_state_id library_integration_state_label enzyme_expression_control_id    enzyme_expression_control_label library_expression_control_id   library_expression_control_label library_name library_uri library_format_id library_format_label library_scope_id library_scope_label library_perturbation_type_id library_perturbation_type_label library_manufacturer library_lentiviral_generation library_grnas_per_target library_total_grnas  library_total_variants readout_dimensionality_id readout_dimensionality_label readout_type_id readout_type_label readout_technology_id readout_technology_label method_name_id method_name_label method_uri sequencing_library_kit_id         sequencing_library_kit_label sequencing_platform_id sequencing_platform_label sequencing_strategy_id sequencing_strategy_label software_counts_id software_counts_label software_analysis_id software_analysis_label score_interpretation reference_genome_id reference_genome_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 associated_datasets license_label   license_id
0  replogle_2022_k562_gw_raw         1  AAACCCAAGAAACCAT-157   Perturb-seq        <NA>                  <NA>                                    CTSC_-_88070848.23-P1P2|CTSC_-_88070918.23-P1P2  chr11:88265069-88359684;-1                          11                                    11                        1       ENSG00000109861                    CTSC           protein_coding  GGCCCAGCACCCATGCTGCA|GTAGCGGTGAGTCCACCACG                 CRISPRi                 <NA>  P8DT0H0M0S            <NA>         <NA>                 157                 <NA>          cell_line            <NA>  Homo sapiens        blood  UBERON:0000178     lymphoblast   CL:0017005      K 562 cell  CLO:0007050    female   <NA>                     adult                   <NA>  chronic myelogenous leukemia, BCR-ABL1 positive  MONDO:0011996  Mapping information-rich genotype-phenotype landscapes with genome-scale Perturb-seq  https://doi.org/10.1016/j.cell.2022.05.013        2022  Joseph M Replogle  Jonathan S Weissman  K562 day 8 essential-scale Perturb-seq experiment  \n            K562 chronic myeloid leukemia cells were transduced with a sgRNA library targeting genes expressed in K562 cells, transcription factors as detailed in Lambert et al. (2018) and Cancer Dependency Map common essential genes.\n            A total of 9,866 genes were targeted.\n            Cells were sampled at day 8 after lentiviral transduction.\n            Multiplexed CRISPRi library containing two distinct guides targeting the same gene were used.\n                                    9861                     1989578                EFO:0022868                    endogenous                         <NA>                      dCas9-KRAB                      <NA>      lentivirus transduction                       <NA>       lentivirus transduction                        <NA>       random locus integration                         <NA>        random locus integration                         <NA>  constitutive transgene expression                          <NA>  constitutive transgene expression       custom        <NA>              <NA>               pooled             <NA>             focused                         <NA>                      inhibition         Weissman Lab                             3                        2               22308                    <NA>                      <NA>       high-dimensional assay            <NA>     transcriptomic                  <NA>      single-cell rna-seq           <NA>       Perturb-seq       <NA>                      <NA>  10x Genomics Single Cell 3-prime v3                   <NA>     Ultima Genomics UG100                   <NA>        barcode sequencing               <NA>            CellRanger                 <NA>                  custom                 <NA>                <NA>                 GRCh38  [{"dataset_accession": "K562_gwps_raw_bulk_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774443", "dataset_description": "Raw, pseudo-bulk expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_raw_bulk_01.h5ad"}, {"dataset_accession": "K562_gwps_normalized_bulk_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35773217", "dataset_description": "Gemgroup Z-normalized pseudo-bulk expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_normalized_bulk_01.h5ad"}, {"dataset_accession": "K562_gwps_raw_singlecell_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35775507", "dataset_description": "Raw, single-cell expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_raw_singlecell_01.h5ad"}, {"dataset_accession": "K562_gwps_normalized_singlecell_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774440", "dataset_description": "Gemgroup Z-normalized single-cell expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_normalized_singlecell_01.h5ad"}]     CC BY 4.0  SWO:1000065
1  replogle_2022_k562_gw_raw         2  AAACCCAAGAAACCAT-207   Perturb-seq        <NA>                  <NA>                                  CWC25_+_36981555.23-P1P2|CWC25_+_36981567.23-P1P2  chr17:38800441-38825646;-1                          17                                    17                        1       ENSG00000273559                   CWC25           protein_coding  GTCTAGAGCGGTGGTGAAAC|GCCGGAAGTGACCTCTAGAG                 CRISPRi                 <NA>  P8DT0H0M0S            <NA>         <NA>                 207                 <NA>          cell_line            <NA>  Homo sapiens        blood  UBERON:0000178     lymphoblast   CL:0017005      K 562 cell  CLO:0007050    female   <NA>                     adult                   <NA>  chronic myelogenous leukemia, BCR-ABL1 positive  MONDO:0011996  Mapping information-rich genotype-phenotype landscapes with genome-scale Perturb-seq  https://doi.org/10.1016/j.cell.2022.05.013        2022  Joseph M Replogle  Jonathan S Weissman  K562 day 8 essential-scale Perturb-seq experiment  \n            K562 chronic myeloid leukemia cells were transduced with a sgRNA library targeting genes expressed in K562 cells, transcription factors as detailed in Lambert et al. (2018) and Cancer Dependency Map common essential genes.\n            A total of 9,866 genes were targeted.\n            Cells were sampled at day 8 after lentiviral transduction.\n            Multiplexed CRISPRi library containing two distinct guides targeting the same gene were used.\n                                    9861                     1989578                EFO:0022868                    endogenous                         <NA>                      dCas9-KRAB                      <NA>      lentivirus transduction                       <NA>       lentivirus transduction                        <NA>       random locus integration                         <NA>        random locus integration                         <NA>  constitutive transgene expression                          <NA>  constitutive transgene expression       custom        <NA>              <NA>               pooled             <NA>             focused                         <NA>                      inhibition         Weissman Lab                             3                        2               22308                    <NA>                      <NA>       high-dimensional assay            <NA>     transcriptomic                  <NA>      single-cell rna-seq           <NA>       Perturb-seq       <NA>                      <NA>  10x Genomics Single Cell 3-prime v3                   <NA>     Ultima Genomics UG100                   <NA>        barcode sequencing               <NA>            CellRanger                 <NA>                  custom                 <NA>                <NA>                 GRCh38  [{"dataset_accession": "K562_gwps_raw_bulk_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774443", "dataset_description": "Raw, pseudo-bulk expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_raw_bulk_01.h5ad"}, {"dataset_accession": "K562_gwps_normalized_bulk_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35773217", "dataset_description": "Gemgroup Z-normalized pseudo-bulk expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_normalized_bulk_01.h5ad"}, {"dataset_accession": "K562_gwps_raw_singlecell_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35775507", "dataset_description": "Raw, single-cell expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_raw_singlecell_01.h5ad"}, {"dataset_accession": "K562_gwps_normalized_singlecell_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774440", "dataset_description": "Gemgroup Z-normalized single-cell expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_normalized_singlecell_01.h5ad"}]     CC BY 4.0  SWO:1000065
2  replogle_2022_k562_gw_raw         3   AAACCCAAGAAACCAT-29   Perturb-seq        <NA>                  <NA>  PDE4DIP_+_144932474.23-ENST00000313431.9|PDE4DIP_+_144932182.23-ENST00000313431.9  chr1:148808140-149048286;1                           1                                     1                        1       ENSG00000178104                 PDE4DIP           protein_coding  GGGCGCGCAGCGGTACCTAG|GGAGCCGGAAGCCCGCTGAC                 CRISPRi                 <NA>  P8DT0H0M0S            <NA>         <NA>                  29                 <NA>          cell_line            <NA>  Homo sapiens        blood  UBERON:0000178     lymphoblast   CL:0017005      K 562 cell  CLO:0007050    female   <NA>                     adult                   <NA>  chronic myelogenous leukemia, BCR-ABL1 positive  MONDO:0011996  Mapping information-rich genotype-phenotype landscapes with genome-scale Perturb-seq  https://doi.org/10.1016/j.cell.2022.05.013        2022  Joseph M Replogle  Jonathan S Weissman  K562 day 8 essential-scale Perturb-seq experiment  \n            K562 chronic myeloid leukemia cells were transduced with a sgRNA library targeting genes expressed in K562 cells, transcription factors as detailed in Lambert et al. (2018) and Cancer Dependency Map common essential genes.\n            A total of 9,866 genes were targeted.\n            Cells were sampled at day 8 after lentiviral transduction.\n            Multiplexed CRISPRi library containing two distinct guides targeting the same gene were used.\n                                    9861                     1989578                EFO:0022868                    endogenous                         <NA>                      dCas9-KRAB                      <NA>      lentivirus transduction                       <NA>       lentivirus transduction                        <NA>       random locus integration                         <NA>        random locus integration                         <NA>  constitutive transgene expression                          <NA>  constitutive transgene expression       custom        <NA>              <NA>               pooled             <NA>             focused                         <NA>                      inhibition         Weissman Lab                             3                        2               22308                    <NA>                      <NA>       high-dimensional assay            <NA>     transcriptomic                  <NA>      single-cell rna-seq           <NA>       Perturb-seq       <NA>                      <NA>  10x Genomics Single Cell 3-prime v3                   <NA>     Ultima Genomics UG100                   <NA>        barcode sequencing               <NA>            CellRanger                 <NA>                  custom                 <NA>                <NA>                 GRCh38  [{"dataset_accession": "K562_gwps_raw_bulk_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774443", "dataset_description": "Raw, pseudo-bulk expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_raw_bulk_01.h5ad"}, {"dataset_accession": "K562_gwps_normalized_bulk_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35773217", "dataset_description": "Gemgroup Z-normalized pseudo-bulk expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_normalized_bulk_01.h5ad"}, {"dataset_accession": "K562_gwps_raw_singlecell_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35775507", "dataset_description": "Raw, single-cell expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_raw_singlecell_01.h5ad"}, {"dataset_accession": "K562_gwps_normalized_singlecell_01", "dataset_uri": "https://plus.figshare.com/ndownloader/files/35774440", "dataset_description": "Gemgroup Z-normalized single-cell expression data for genes expressed at >0.01 UMI per cell", "dataset_file_name": "K562_gwps_normalized_singlecell_01.h5ad"}]     CC BY 4.0  SWO:1000065

,dataset_id,sample_id,cell_barcode,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,replogle_2022_k562_gw_raw,1,AAACCCAAGAAACCAT-157,Perturb-seq,<NA>,<NA>,CTSC_-_88070848.23-P1P2|CTSC_-_88070918.23-P1P2,chr11:88265069-88359684;-1,11,11,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
1,replogle_2022_k562_gw_raw,2,AAACCCAAGAAACCAT-207,Perturb-seq,<NA>,<NA>,CWC25_+_36981555.23-P1P2|CWC25_+_36981567.23-P1P2,chr17:38800441-38825646;-1,17,17,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
2,replogle_2022_k562_gw_raw,3,AAACCCAAGAAACCAT-29,Perturb-seq,<NA>,<NA>,PDE4DIP_+_144932474.23-ENST00000313431.9|PDE4D...,chr1:148808140-149048286;1,1,1,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
3,replogle_2022_k562_gw_raw,4,AAACCCAAGAAAGCGA-149,Perturb-seq,<NA>,<NA>,ZZEF1_+_4046247.23-P1P2|ZZEF1_+_4046255.23-P1P2,chr17:4004445-4143628;-1,17,17,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
4,replogle_2022_k562_gw_raw,5,AAACCCAAGAAATCCA-172,Perturb-seq,<NA>,<NA>,SNAPIN_+_153631238.23-P1P2|SNAPIN_-_153631252....,chr1:153658696-153663930;1,1,1,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989573,replogle_2022_k562_gw_raw,1989574,TTTGTTGTCTTTCCAA-201,Perturb-seq,<NA>,<NA>,SCRIB_-_144897465.23-P1P2|SCRIB_-_144897339.23...,chr8:143790920-143815773;-1,8,8,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
1989574,replogle_2022_k562_gw_raw,1989575,TTTGTTGTCTTTCGAT-79,Perturb-seq,<NA>,<NA>,CADM4_+_44143915.23-P1P2|CADM4_+_44143932.23-P1P2,chr19:43622366-43639850;-1,19,19,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
1989575,replogle_2022_k562_gw_raw,1989576,TTTGTTGTCTTTCTAG-218,Perturb-seq,<NA>,<NA>,SLC4A7_+_27525847.23-P1P2|SLC4A7_+_27525631.23...,chr3:27372723-27484451;-1,3,3,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
1989576,replogle_2022_k562_gw_raw,1989577,TTTGTTGTCTTTGCGC-169,Perturb-seq,<NA>,<NA>,TMEM131_-_98612356.23-P1P2|TMEM131_-_98612239....,chr2:97756333-97996226;-1,2,2,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065
1989577,replogle_2022_k562_gw_raw,1989578,TTTGTTGTCTTTGCGC-213,Perturb-seq,<NA>,<NA>,SRP14_+_40331287.23-P1P2|SRP14_-_40330986.23-P1P2,chr15:40035690-40039181;-1,15,15,...,<NA>,CellRanger,<NA>,custom,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""K562_gwps_raw_bulk_01""...",CC BY 4.0,SWO:1000065

In [25]:
cur_data.adata.obs[['library_total_grnas', 'library_total_variants']]

        library_total_grnas  library_total_variants
0                     22308                    <NA>
1                     22308                    <NA>
2                     22308                    <NA>
3                     22308                    <NA>
4                     22308                    <NA>
...                     ...                     ...
1989573               22308                    <NA>
1989574               22308                    <NA>
1989575               22308                    <NA>
1989576               22308                    <NA>
1989577               22308                    <NA>

[1989578 rows x 2 columns]

In [26]:
cur_data.show_obs(['perturbation_name', 'perturbed_target_symbol', 'perturbed_target_ensg', 'perturbed_target_coord'])

Observation data:
DataFrame shape: (1989578, 4)
--------------------------------------------------
                                         perturbation_name  \
0          CTSC_-_88070848.23-P1P2|CTSC_-_88070918.23-P1P2
1        CWC25_+_36981555.23-P1P2|CWC25_+_36981567.23-P1P2
2        PDE4DIP_+_144932474.23-ENST00000313431.9|PDE4D...
3          ZZEF1_+_4046247.23-P1P2|ZZEF1_+_4046255.23-P1P2
4        SNAPIN_+_153631238.23-P1P2|SNAPIN_-_153631252....
...                                                    ...
1989573  SCRIB_-_144897465.23-P1P2|SCRIB_-_144897339.23...
1989574  CADM4_+_44143915.23-P1P2|CADM4_+_44143932.23-P1P2
1989575  SLC4A7_+_27525847.23-P1P2|SLC4A7_+_27525631.23...
1989576  TMEM131_-_98612356.23-P1P2|TMEM131_-_98612239....
1989577  SRP14_+_40331287.23-P1P2|SRP14_-_40330986.23-P1P2

        perturbed_target_symbol perturbed_target_ensg  \
0                          CTSC       ENSG00000109861
1                         CWC25       ENSG00000273559
2                       PDE4DIP       ENSG00000178104
3                         ZZEF1       ENSG00000074755
4                        SNAPIN       ENSG00000143553
...                         ...                   ...
1989573                   SCRIB       ENSG00000180900
1989574                   CADM4       ENSG00000105767
1989575                  SLC4A7       ENSG00000033867
1989576                 TMEM131       ENSG00000075568
1989577                   SRP14       ENSG00000140319

              perturbed_target_coord
0         chr11:88265069-88359684;-1
1         chr17:38800441-38825646;-1
2         chr1:148808140-149048286;1
3           chr17:4004445-4143628;-1
4         chr1:153658696-153663930;1
...                              ...
1989573  chr8:143790920-143815773;-1
1989574   chr19:43622366-43639850;-1
1989575    chr3:27372723-27484451;-1
1989576    chr2:97756333-97996226;-1
1989577   chr15:40035690-40039181;-1

[1989578 rows x 4 columns]
--------------------------------------------------

# VAR slot curation

### Standardise genes

In [27]:
cur_data.show_var()

Variable data:
DataFrame shape: (8248, 12)
--------------------------------------------------
                  gene_name         chr   start      end           class  \
gene_id
ENSG00000237491   LINC01409        chr1  778747   810065  gene_version10
ENSG00000228794   LINC01128        chr1  825138   868202   gene_version9
ENSG00000188976       NOC2L        chr1  944203   959309  gene_version11
ENSG00000187961      KLHL17        chr1  960584   965719  gene_version14
ENSG00000188290        HES4        chr1  998962  1000172  gene_version10
...                     ...         ...     ...      ...             ...
ENSG00000198727      MT-CYB        chrM   14747    15887   gene_version2
ENSG00000278704  BX004987.1  GL000009.2   56140    58376   gene_version1
ENSG00000278384  AL354822.1  GL000218.1   51867    54893   gene_version1
ENSG00000271254  AC240274.1  KI270711.1    4612    29626   gene_version6
ENSG00000276345  AC004556.3  KI270721.1    2585    11802   gene_version1

                strand  length  in_matrix        mean        std        cv  \
gene_id
ENSG00000237491      +   31318       True    0.116626   0.349971  3.000803
ENSG00000228794      +   43064       True    0.182850   0.437274  2.391434
ENSG00000188976      -   15106       True    1.415674   1.397208  0.986957
ENSG00000187961      +    5135       True    0.105599   0.330678  3.131439
ENSG00000188290      -    1210       True    0.242700   0.550596  2.268630
...                ...     ...        ...         ...        ...       ...
ENSG00000198727      +    1140       True  116.549202  59.102600  0.507104
ENSG00000278704      -    2236       True    0.195008   0.455099  2.333745
ENSG00000278384      -    3026       True    0.190869   0.450850  2.362089
ENSG00000271254      -   25014       True    0.163767   0.427101  2.607982
ENSG00000276345      +    9217       True    0.295477   0.575876  1.948971

                      fano
gene_id
ENSG00000237491   1.050194
ENSG00000228794   1.045713
ENSG00000188976   1.378984
ENSG00000187961   1.035497
ENSG00000188290   1.249098
...                    ...
ENSG00000198727  29.971182
ENSG00000278704   1.062085
ENSG00000278384   1.064948
ENSG00000271254   1.113872
ENSG00000276345   1.122365

[8248 rows x 12 columns]
--------------------------------------------------

In [28]:
cur_data.create_columns(
    slot = 'var',
    col_dict={'gene_ensembl_id': cur_data.adata.var.index},
    overwrite=True
)

Column gene_ensembl_id added to adata.var

In [29]:
cur_data.standardize_genes(
    slot="var",
    input_column="gene_ensembl_id",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

2026-04-23 13:28:51,546 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rest.ensembl.org:443

Missing Ensembl IDs: ['ENSG00000283633', 'ENSG00000255823', 'ENSG00000112096', 'ENSG00000278384', 'ENSG00000228434', 'ENSG00000278704', 'ENSG00000239467', 'ENSG00000235111', 'ENSG00000276345', 'ENSG00000271109', 'ENSG00000215067', 'ENSG00000215271', 'ENSG00000233937', 'ENSG00000287263', 'ENSG00000130723', 'ENSG00000272316', 'ENSG00000269028', 'ENSG00000264920', 'ENSG00000148362', 'ENSG00000271254']; attempting to fetch latest IDs...

2026-04-23 13:28:52,038 DEBUG urllib3.connectionpool: https://rest.ensembl.org:443 "POST /archive/id HTTP/1.1" 200 4001

Fetched latest Ensembl IDs: {'ENSG00000283633': 'ENSG00000290418', 'ENSG00000255823': nan, 'ENSG00000112096': 'ENSG00000291237', 'ENSG00000228434': 'ENSG00000290758', 'ENSG00000239467': 'ENSG00000204334', 'ENSG00000235111': 'ENSG00000188511', 'ENSG00000271109': 'ENSG00000267767', 'ENSG00000215067': 'ENSG00000267532', 'ENSG00000215271': 'ENSG00000290292', 'ENSG00000233937': nan, 'ENSG00000287263': 'ENSG00000177738', 'ENSG00000130723': nan, 'ENSG00000272316': 'ENSG00000290555', 'ENSG00000269028': nan, 'ENSG00000264920': 'ENSG00000234494', 'ENSG00000148362': 'ENSG00000310560'}
--------------------------------------------------
Successfully mapped 8248 out of 8248 Ensembl IDs.
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Validate var metadata

In [30]:
cur_data.validate_data(slot='var')

2026-04-23 13:28:53,273 INFO curation_tools.curation_tools: adata.var is valid according to the var_schema.
2026-04-23 13:28:53,282 DEBUG curation_tools.curation_tools: Validated adata.var preview (shape=(8248, 2)):
       ensembl_gene_id gene_symbol
index
0      ENSG00000237491   LINC01409
1      ENSG00000228794   LINC01128
2      ENSG00000188976       NOC2L
3      ENSG00000187961      KLHL17
4      ENSG00000188290        HES4

       ensembl_gene_id gene_symbol
index
0      ENSG00000237491   LINC01409
1      ENSG00000228794   LINC01128
2      ENSG00000188976       NOC2L
3      ENSG00000187961      KLHL17
4      ENSG00000188290        HES4
...                ...         ...
8243   ENSG00000198727      MT-CYB
8244   ENSG00000278704         NaN
8245   ENSG00000278384         NaN
8246   ENSG00000271254         NaN
8247   ENSG00000276345         NaN

[8248 rows x 2 columns]

# Save the dataset

In [31]:
cur_data.save_curated_data_h5ad()

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)
... storing 'dataset_id' as categorical
... storing 'data_modality' as categorical
... storing 'significance_criteria' as categorical
... storing 'perturbation_name' as categorical
... storing 'perturbed_target_coord' as categorical
... storing 'perturbed_target_chromosome' as categorical
... storing 'perturbed_target_ensg' as categorical
... storing 'perturbed_target_symbol' as categorical
... storing 'perturbed_target_biotype' as categorical
... storing 'guide_sequence' as categorical
... storing 'perturbation_type_label' as categorical
... storing 'perturbation_type_id' as categorical
... storing 'timepoint' as categorical
... storing 'treatment_label' as categorical
... storing 'treatment_id' as categorical
... storing 'technical_replicate' as categorical
... storing 'biological_replicate' as categorical
... storing 'model_system_label' as categorical
... storing 'model_system_id' as categorical
... storing 'species' as categorical
... storing 'tissue_label' as categorical
... storing 'tissue_id' as categorical
... storing 'cell_type_label' as categorical
... storing 'cell_type_id' as categorical
... storing 'cell_line_label' as categorical
... storing 'cell_line_id' as categorical
... storing 'sex_label' as categorical
... storing 'sex_id' as categorical
... storing 'developmental_stage_label' as categorical
... storing 'developmental_stage_id' as categorical
... storing 'disease_label' as categorical
... storing 'disease_id' as categorical
... storing 'study_title' as categorical
... storing 'study_uri' as categorical
... storing 'first_author' as categorical
... storing 'last_author' as categorical
... storing 'experiment_title' as categorical
... storing 'experiment_summary' as categorical
... storing 'number_of_perturbed_targets' as categorical
... storing 'number_of_perturbed_samples' as categorical
... storing 'library_generation_type_id' as categorical
... storing 'library_generation_type_label' as categorical
... storing 'library_generation_method_id' as categorical
... storing 'library_generation_method_label' as categorical
... storing 'enzyme_delivery_method_id' as categorical
... storing 'enzyme_delivery_method_label' as categorical
... storing 'library_delivery_method_id' as categorical
... storing 'library_delivery_method_label' as categorical
... storing 'enzyme_integration_state_id' as categorical
... storing 'enzyme_integration_state_label' as categorical
... storing 'library_integration_state_id' as categorical
... storing 'library_integration_state_label' as categorical
... storing 'enzyme_expression_control_id' as categorical
... storing 'enzyme_expression_control_label' as categorical
... storing 'library_expression_control_id' as categorical
... storing 'library_expression_control_label' as categorical
... storing 'library_name' as categorical
... storing 'library_uri' as categorical
... storing 'library_format_id' as categorical
... storing 'library_format_label' as categorical
... storing 'library_scope_id' as categorical
... storing 'library_scope_label' as categorical
... storing 'library_perturbation_type_id' as categorical
... storing 'library_perturbation_type_label' as categorical
... storing 'library_manufacturer' as categorical
... storing 'library_lentiviral_generation' as categorical
... storing 'library_grnas_per_target' as categorical
... storing 'library_total_grnas' as categorical
... storing 'readout_dimensionality_id' as categorical
... storing 'readout_dimensionality_label' as categorical
... storing 'readout_type_id' as categorical
... storing 'readout_type_label' as categorical
... storing 'readout_technology_id' as categorical
... storing 'readout_technology_label' as categorical
... storing 'method_name_id' as categorical
... storing 'method_name_label' as categorical
... storing 'method_uri' as categorical
... storing 'sequencing_library_kit_id' as categorical
... storing 'sequencing_library_kit_label' as categorical
... storing 'sequencing_platform_id' as categorical
... storing 'sequencing_platform_label' as categorical
... storing 'sequencing_strategy_id' as categorical
... storing 'sequencing_strategy_label' as categorical
... storing 'software_counts_id' as categorical
... storing 'software_counts_label' as categorical
... storing 'software_analysis_id' as categorical
... storing 'software_analysis_label' as categorical
... storing 'score_interpretation' as categorical
... storing 'reference_genome_id' as categorical
... storing 'reference_genome_label' as categorical
... storing 'associated_datasets' as categorical
... storing 'license_label' as categorical
... storing 'license_id' as categorical
... storing 'ensembl_gene_id' as categorical
... storing 'gene_symbol' as categorical
2026-04-23 13:29:45,402 DEBUG h5py._conv: Creating converter from 5 to 3

✅ Curated h5ad data saved to ../curated/h5ad/replogle_2022_k562_gw_raw_curated.h5ad

In [32]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/replogle_2022_k562_gw_raw_curated_metadata.parquet

# Upload to BigQuery

In [33]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/replogle_2022_k562_gw_raw_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

2026-04-23 13:39:50,526 DEBUG google.auth._default: Checking '' for explicit credentials as part of auth process...
2026-04-23 13:39:50,527 DEBUG google.auth._default: Checking Cloud SDK credentials as part of auth process...
2026-04-23 13:39:53,138 DEBUG google.auth._default: Checking '' for explicit credentials as part of auth process...
2026-04-23 13:39:53,139 DEBUG google.auth._default: Checking Cloud SDK credentials as part of auth process...
2026-04-23 13:39:53,859 DEBUG google.cloud.bigquery.opentelemetry_tracing: This service is instrumented using OpenTelemetry. OpenTelemetry or one of its components could not be imported; please add compatible versions of opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data.
2026-04-23 13:39:53,861 DEBUG urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2026-04-23 13:39:53,864 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): oauth2.googleapis.com:443
2026-04-23 13:39:53,919 DEBUG urllib3.connectionpool: https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2026-04-23 13:39:53,922 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): bigquery.googleapis.com:443
2026-04-23 13:39:54,136 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata?prettyPrint=false HTTP/1.1" 200 None

Staging table: loading `.parquet` file ../curated/parquet/replogle_2022_k562_gw_raw_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...

2026-04-23 13:39:54,634 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /upload/bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?uploadType=resumable HTTP/1.1" 200 0
2026-04-23 13:39:55,788 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "PUT /upload/bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?uploadType=resumable&upload_id=AMNfjG1nARsLyagZEvruK_yZfk0Rc7G2UFMoZguvnH3uoJTuhy0BbiiYl6P0cwABtoAP93-EOETckrM7rSSQ-ydG_3rdqTCXpk9mZu-0ft_Sa24 HTTP/1.1" 200 14124
2026-04-23 13:39:55,949 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/6f408826-2d43-4619-94f3-144c45ebee62?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:39:56,738 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/6f408826-2d43-4619-94f3-144c45ebee62?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:39:57,467 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/6f408826-2d43-4619-94f3-144c45ebee62?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:39:57,971 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/6f408826-2d43-4619-94f3-144c45ebee62?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:00,789 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/6f408826-2d43-4619-94f3-144c45ebee62?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:04,014 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/6f408826-2d43-4619-94f3-144c45ebee62?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:07,522 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/6f408826-2d43-4619-94f3-144c45ebee62?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:07,684 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata_staging?prettyPrint=false HTTP/1.1" 200 None

Staging table: loaded 1989578 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

2026-04-23 13:40:09,241 DEBUG urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2026-04-23 13:40:09,244 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): oauth2.googleapis.com:443
2026-04-23 13:40:09,297 DEBUG urllib3.connectionpool: https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2026-04-23 13:40:09,298 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): bigquery.googleapis.com:443
2026-04-23 13:40:09,679 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:09,834 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/d44934d3-855e-469e-8fa2-4b71dfeb0f9d?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:09,982 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/d44934d3-855e-469e-8fa2-4b71dfeb0f9d?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:10,116 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/d44934d3-855e-469e-8fa2-4b71dfeb0f9d?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:10,435 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:10,559 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/acdf93c0-4b2d-447f-80ae-bcdb2694c838?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:10,698 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/acdf93c0-4b2d-447f-80ae-bcdb2694c838?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:10,810 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/acdf93c0-4b2d-447f-80ae-bcdb2694c838?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:11,423 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:11,503 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/48ec6a27-0813-4644-b793-5f1b1511ba7a?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:21,487 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/48ec6a27-0813-4644-b793-5f1b1511ba7a?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:21,641 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/48ec6a27-0813-4644-b793-5f1b1511ba7a?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:26,914 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/48ec6a27-0813-4644-b793-5f1b1511ba7a?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:27,016 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/48ec6a27-0813-4644-b793-5f1b1511ba7a?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None

Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

2026-04-23 13:40:27,244 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata?prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:27,424 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata?prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:27,959 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs?prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:28,076 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/ef84df7e-72bf-4ac4-bfe4-dc67beda124d?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:38,052 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/ef84df7e-72bf-4ac4-bfe4-dc67beda124d?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:38,095 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/ef84df7e-72bf-4ac4-bfe4-dc67beda124d?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:38,792 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/queries/ef84df7e-72bf-4ac4-bfe4-dc67beda124d?maxResults=0&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:38,923 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/prj-ext-dev-pertcat-437314/jobs/ef84df7e-72bf-4ac4-bfe4-dc67beda124d?projection=full&location=europe-west2&prettyPrint=false HTTP/1.1" 200 None
2026-04-23 13:40:39,064 DEBUG urllib3.connectionpool: https://bigquery.googleapis.com:443 "DELETE /bigquery/v2/projects/prj-ext-dev-pertcat-437314/datasets/perturb_seq/tables/metadata_staging?prettyPrint=false HTTP/1.1" 204 0

Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [35]:
!gcloud storage cp ../curated/h5ad/replogle_2022_k562_gw_raw_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/replogle_2022_k562_gw_raw_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/replogle_2022_k562_gw_raw_curated.h5ad
  Completed files 32/1 | 61.6GiB/61.6GiB | 184.3MiB/s

Average throughput: 305.1MiB/s