In [1]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("curation.log"),
        logging.StreamHandler(),  # keep console output too
    ],
    force=True,
)
# show all columns
pd.set_option('display.max_columns', None)

# Download data

In [2]:
# data
download_file(
    url="https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE247599&format=file",
    dest_path='../non_curated/song_2025_jurkat_hiv.tar',
    unarchive=True
)
# guide-cell mapping
download_file(
    url="https://raw.githubusercontent.com/davidliwei/PS/refs/heads/main/datasets/HIV_Perturb-seq/BARCODE_H13Ld2EGFP.txt",
    dest_path='../supplementary/song_2025_jurkat_hiv/BARCODE_H13Ld2EGFP.txt',
    unarchive=False
)

Downloaded https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE247599&format=file to ../non_curated/song_2025_jurkat_hiv.tar
File ../supplementary/song_2025_jurkat_hiv/BARCODE_H13Ld2EGFP.txt already exists. Skipping download.

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Data is in three sets of files (mtx, barcodes, features) for each of the three conditions (NoDrug, LRA-Negative (no HIV expression)) and LRA-Positive (HIV expression).

In [17]:
import scanpy as sc
import scipy.io
import anndata as ad
import numpy as np

DATA_DIR = "../non_curated"

samples = {
    "LRA-Positive": "GSM7897841_JKLAT-LRA-Positive",
    "LRA-Negative": "GSM7897842_JKLAT-LRA-Negative",
    "NoDrug":       "GSM7897843_JKLAT-NoDrug",
}

def read_10x_mtx(data_dir, prefix):
    matrix   = scipy.io.mmread(f"{data_dir}/{prefix}_matrix.mtx.gz").T.tocsr()
    barcodes = pd.read_csv(f"{data_dir}/{prefix}_barcodes.tsv.gz", header=None)[0]
    features = pd.read_csv(
        f"{data_dir}/{prefix}_features.tsv.gz",
        sep="\t", header=None,
        names=["gene_id", "gene_name", "feature_type"],
    )
    obs = pd.DataFrame(index=barcodes)
    var = features.set_index("gene_id")
    return ad.AnnData(X=matrix, obs=obs, var=var)

adatas = {}
for condition, prefix in samples.items():
    adata = read_10x_mtx(DATA_DIR, prefix)
    adata.obs["condition"] = condition
    adatas[condition] = adata
    print(f"{condition}: {adata.shape}")

adata = ad.concat(adatas.values(), label="condition", keys=adatas.keys())
adata.var = adatas["LRA-Positive"].var  # restore var metadata lost during concat
print("\nConcatenated:", adata)

LRA-Positive: (2617899, 36636)
LRA-Negative: (2784659, 36636)
NoDrug: (2830966, 36636)

Concatenated: AnnData object with n_obs × n_vars = 8233524 × 36636
    obs: 'condition'
    var: 'gene_name', 'feature_type'

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/.venv/lib/python3.12/site-packages/anndata/_core/anndata.py:1791: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [18]:
# add cell barcode to obs
adata.obs['cell_barcode'] = adata.obs_names + '_' + adata.obs['condition'].astype(str)
adata.obs[['cell_barcode']]

                                       cell_barcode
0
AAACCCAAGAAACACT-1  AAACCCAAGAAACACT-1_LRA-Positive
AAACCCAAGAAACCAT-1  AAACCCAAGAAACCAT-1_LRA-Positive
AAACCCAAGAAACCCA-1  AAACCCAAGAAACCCA-1_LRA-Positive
AAACCCAAGAAACCCG-1  AAACCCAAGAAACCCG-1_LRA-Positive
AAACCCAAGAAACTAC-1  AAACCCAAGAAACTAC-1_LRA-Positive
...                                             ...
TTTGTTGTCTTTCTTC-1        TTTGTTGTCTTTCTTC-1_NoDrug
TTTGTTGTCTTTGATC-1        TTTGTTGTCTTTGATC-1_NoDrug
TTTGTTGTCTTTGCAT-1        TTTGTTGTCTTTGCAT-1_NoDrug
TTTGTTGTCTTTGCGC-1        TTTGTTGTCTTTGCGC-1_NoDrug
TTTGTTGTCTTTGCTA-1        TTTGTTGTCTTTGCTA-1_NoDrug

[8233524 rows x 1 columns]

In [19]:
adata.obs

                       condition                     cell_barcode
0
AAACCCAAGAAACACT-1  LRA-Positive  AAACCCAAGAAACACT-1_LRA-Positive
AAACCCAAGAAACCAT-1  LRA-Positive  AAACCCAAGAAACCAT-1_LRA-Positive
AAACCCAAGAAACCCA-1  LRA-Positive  AAACCCAAGAAACCCA-1_LRA-Positive
AAACCCAAGAAACCCG-1  LRA-Positive  AAACCCAAGAAACCCG-1_LRA-Positive
AAACCCAAGAAACTAC-1  LRA-Positive  AAACCCAAGAAACTAC-1_LRA-Positive
...                          ...                              ...
TTTGTTGTCTTTCTTC-1        NoDrug        TTTGTTGTCTTTCTTC-1_NoDrug
TTTGTTGTCTTTGATC-1        NoDrug        TTTGTTGTCTTTGATC-1_NoDrug
TTTGTTGTCTTTGCAT-1        NoDrug        TTTGTTGTCTTTGCAT-1_NoDrug
TTTGTTGTCTTTGCGC-1        NoDrug        TTTGTTGTCTTTGCGC-1_NoDrug
TTTGTTGTCTTTGCTA-1        NoDrug        TTTGTTGTCTTTGCTA-1_NoDrug

[8233524 rows x 2 columns]

In [20]:
adata.var

                              gene_name          feature_type
gene_id
ENSG00000243485             MIR1302-2HG       Gene Expression
ENSG00000237613                 FAM138A       Gene Expression
ENSG00000186092                   OR4F5       Gene Expression
ENSG00000238009              AL627309.1       Gene Expression
ENSG00000239945              AL627309.3       Gene Expression
...                                 ...                   ...
HSPD0000052096   HSPD0000052096_MAP3K14  CRISPR Guide Capture
HSPD0000052097   HSPD0000052097_MAP3K14  CRISPR Guide Capture
HSPD0000073810      HSPD0000073810_BRD4  CRISPR Guide Capture
HSPD0000073811      HSPD0000073811_BRD4  CRISPR Guide Capture
HSPD0000073812      HSPD0000073812_BRD4  CRISPR Guide Capture

[36636 rows x 2 columns]

# Add available guide information to adata.obs

In [21]:
guide_map_df = pd.read_csv("../supplementary/song_2025_jurkat_hiv/BARCODE_H13Ld2EGFP.txt", sep="\t")
guide_map_df['cell_barcode'] = guide_map_df['cell'].str.split('_').str[1]
guide_map_df['cell_barcode'] = guide_map_df['cell_barcode'] + '_' + guide_map_df['cell'].str.split('_').str[0].map({
    'pos': 'LRA-Positive',
    'nes': 'LRA-Negative',
    'nodrug': 'NoDrug'
})
# some cells have multiple guides - group by cell barcode and aggregate barcode, gene, sgrna together, separated by '|'
# then remove the cells with multiple guides
guide_map_df = guide_map_df.groupby('cell_barcode').agg({
    'barcode': lambda x: '|'.join(x),
    'gene': lambda x: '|'.join(x),
    'sgrna': lambda x: '|'.join(x)
}).reset_index()
# filter out cells with multiple guides
guide_map_df = guide_map_df[~guide_map_df['sgrna'].str.contains('\\|')]
# standardise controls
guide_map_df['gene'] = (
    guide_map_df['barcode']
    .replace(r'NegativeControl\d+', 'control_nontargeting', regex=True)
    .replace('HScontrol-AAVS1', 'control_gsh'))
# clean gene names
guide_map_df['gene'] = guide_map_df['gene'].str.split('-').str[1].fillna(guide_map_df['gene'])
# rename cols
guide_map_df = guide_map_df.rename(columns={'barcode': 'perturbation_name', 'sgrna': 'guide_sequence'})
guide_map_df

,cell_barcode,perturbation_name,gene,guide_sequence
0,AAACCCAAGCTTGTTG-1_NoDrug,HSPD0000033202-PRKCA,PRKCA,TTGTGAACGTTCATATCGC
1,AAACCCAAGGGTGGGA-1_LRA-Positive,HSPD0000046601-NELFE,NELFE,CCGGGAACGGGACAGGGAT
2,AAACCCAAGGTTCCGC-1_NoDrug,HSPD0000018545-HDAC2,HDAC2,ACAACAGATCGTGTAATGA
3,AAACCCAAGGTTGGAC-1_NoDrug,HSPD0000052097-MAP3K14,MAP3K14,CCACTTTCCGCAGAACACA
4,AAACCCACAGCTGTGC-1_LRA-Negative,HSPD0000002159-BIRC2,BIRC2,TGAAGACATCTCTTCATCG
...,...,...,...,...
21873,TTTGTTGGTGGTTTAC-1_LRA-Positive,HScontrol-AAVS1,control_gsh,GGGGCCACTAGGGACAGGAT
21874,TTTGTTGGTTCAGGTT-1_LRA-Positive,HSPD0000005747-CCNT1,CCNT1,TGGGTCGTGTTGTGACCAT
21876,TTTGTTGTCTCGCGTT-1_NoDrug,HSPD0000046601-NELFE,NELFE,CCGGGAACGGGACAGGGAT
21877,TTTGTTGTCTCTCCGA-1_LRA-Negative,HSPD0000028138-NFKBIA,NFKBIA,TGGACGACCGCCACGACAG
21878,TTTGTTGTCTGCAGCG-1_LRA-Positive,HSPD0000002160-BIRC2,BIRC2,ACTCATTGCATAACTGTAG

In [22]:
# merge guide map with adata.obs; 
adata.obs = adata.obs.merge(guide_map_df, on='cell_barcode', how='left')
adata = adata[~adata.obs['guide_sequence'].isna()].copy()  # filter out cells without guide assignment

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [23]:
adata.obs

,condition,cell_barcode,perturbation_name,gene,guide_sequence
457,LRA-Positive,AAACCCAAGGGTGGGA-1_LRA-Positive,HSPD0000046601-NELFE,NELFE,CCGGGAACGGGACAGGGAT
1193,LRA-Positive,AAACCCACAGGTTCGC-1_LRA-Positive,HSPD0000018544-HDAC2,HDAC2,GACTGATATGGCTGTTAAT
1503,LRA-Positive,AAACCCAGTAGGTAGC-1_LRA-Positive,HSPD0000002160-BIRC2,BIRC2,ACTCATTGCATAACTGTAG
1585,LRA-Positive,AAACCCAGTCACCACG-1_LRA-Positive,HSPD0000033203-PRKCA,PRKCA,AGGGGGCGGATTTACCTAA
1931,LRA-Positive,AAACCCAGTTAACAGA-1_LRA-Positive,HSPD0000033201-PRKCA,PRKCA,AAGCCCGTTTGGATCCATA
...,...,...,...,...,...
8231140,NoDrug,TTTGTTGAGTTATGGA-1_NoDrug,HSPD0000052097-MAP3K14,MAP3K14,CCACTTTCCGCAGAACACA
8231425,NoDrug,TTTGTTGCACATACTG-1_NoDrug,HSPD0000005747-CCNT1,CCNT1,TGGGTCGTGTTGTGACCAT
8232103,NoDrug,TTTGTTGGTATAGCTC-1_NoDrug,HSPD0000028140-NFKBIA,NFKBIA,GAAGTGATCCGCCAGGTGA
8232401,NoDrug,TTTGTTGGTGATTCAC-1_NoDrug,HSPD0000002159-BIRC2,BIRC2,TGAAGACATCTCTTCATCG
8233387,NoDrug,TTTGTTGTCTCGCGTT-1_NoDrug,HSPD0000046601-NELFE,NELFE,CCGGGAACGGGACAGGGAT

# Save to a non-curated h5ad file

In [24]:
adata.write_h5ad("../non_curated/h5ad/song_2025_jurkat_hiv.h5ad")
del(adata, guide_map_df, adatas)

... storing 'perturbation_name' as categorical
... storing 'gene' as categorical
... storing 'guide_sequence' as categorical

... storing 'gene_name' as categorical
... storing 'feature_type' as categorical

# Initialise the dataset object

In [25]:
noncurated_path = "../non_curated/h5ad/song_2025_jurkat_hiv.h5ad"
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/song_2025_jurkat_hiv.h5ad

In [26]:
cur_data.adata.obs

,condition,cell_barcode,perturbation_name,gene,guide_sequence
457,LRA-Positive,AAACCCAAGGGTGGGA-1_LRA-Positive,HSPD0000046601-NELFE,NELFE,CCGGGAACGGGACAGGGAT
1193,LRA-Positive,AAACCCACAGGTTCGC-1_LRA-Positive,HSPD0000018544-HDAC2,HDAC2,GACTGATATGGCTGTTAAT
1503,LRA-Positive,AAACCCAGTAGGTAGC-1_LRA-Positive,HSPD0000002160-BIRC2,BIRC2,ACTCATTGCATAACTGTAG
1585,LRA-Positive,AAACCCAGTCACCACG-1_LRA-Positive,HSPD0000033203-PRKCA,PRKCA,AGGGGGCGGATTTACCTAA
1931,LRA-Positive,AAACCCAGTTAACAGA-1_LRA-Positive,HSPD0000033201-PRKCA,PRKCA,AAGCCCGTTTGGATCCATA
...,...,...,...,...,...
8231140,NoDrug,TTTGTTGAGTTATGGA-1_NoDrug,HSPD0000052097-MAP3K14,MAP3K14,CCACTTTCCGCAGAACACA
8231425,NoDrug,TTTGTTGCACATACTG-1_NoDrug,HSPD0000005747-CCNT1,CCNT1,TGGGTCGTGTTGTGACCAT
8232103,NoDrug,TTTGTTGGTATAGCTC-1_NoDrug,HSPD0000028140-NFKBIA,NFKBIA,GAAGTGATCCGCCAGGTGA
8232401,NoDrug,TTTGTTGGTGATTCAC-1_NoDrug,HSPD0000002159-BIRC2,BIRC2,TGAAGACATCTCTTCATCG
8233387,NoDrug,TTTGTTGTCTCGCGTT-1_NoDrug,HSPD0000046601-NELFE,NELFE,CCGGGAACGGGACAGGGAT

### Standardise perturbation targets

In [27]:
cur_data.standardize_genes(
    slot='obs',
    input_column='gene',
    input_column_type='gene_symbol',
    multiple_entries=False
)

Mapping gene symbols: 100%|███████████████████████████████████████| 12/12 [00:00<00:00, 9807.41it/s]

--------------------------------------------------
Successfully mapped 12 out of 12 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: []
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Add `perturbed_target_number` column

In [28]:
cur_data.count_entries(
    slot='obs',
    input_column='perturbed_target_symbol',
    count_column_name='perturbed_target_number',
    sep='|'
)

Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number

### Encode chromosomes as integers

In [29]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

In [30]:
cur_data.adata.obs

,cell_barcode,guide_sequence,gene,perturbation_name,condition,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding
index,,,,,,,,,,,,,
0,AAACCCAAGGGTGGGA-1_LRA-Positive,CCGGGAACGGGACAGGGAT,NELFE,HSPD0000046601-NELFE,LRA-Positive,ENSG00000204356,NELFE,protein_coding,chr6:31952087-31959038;-1,6,457,1,6
1,AAACCCACAGGTTCGC-1_LRA-Positive,GACTGATATGGCTGTTAAT,HDAC2,HSPD0000018544-HDAC2,LRA-Positive,ENSG00000196591,HDAC2,protein_coding,chr6:113933028-114011308;-1,6,1193,1,6
2,AAACCCAGTAGGTAGC-1_LRA-Positive,ACTCATTGCATAACTGTAG,BIRC2,HSPD0000002160-BIRC2,LRA-Positive,ENSG00000110330,BIRC2,protein_coding,chr11:102347208-102378680;1,11,1503,1,11
3,AAACCCAGTCACCACG-1_LRA-Positive,AGGGGGCGGATTTACCTAA,PRKCA,HSPD0000033203-PRKCA,LRA-Positive,ENSG00000154229,PRKCA,protein_coding,chr17:66302613-66810743;1,17,1585,1,17
4,AAACCCAGTTAACAGA-1_LRA-Positive,AAGCCCGTTTGGATCCATA,PRKCA,HSPD0000033201-PRKCA,LRA-Positive,ENSG00000154229,PRKCA,protein_coding,chr17:66302613-66810743;1,17,1931,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19875,TTTGTTGAGTTATGGA-1_NoDrug,CCACTTTCCGCAGAACACA,MAP3K14,HSPD0000052097-MAP3K14,NoDrug,ENSG00000006062,MAP3K14,protein_coding,chr17:45263119-45317112;-1,17,8231140,1,17
19876,TTTGTTGCACATACTG-1_NoDrug,TGGGTCGTGTTGTGACCAT,CCNT1,HSPD0000005747-CCNT1,NoDrug,ENSG00000129315,CCNT1,protein_coding,chr12:48688458-48716998;-1,12,8231425,1,12
19877,TTTGTTGGTATAGCTC-1_NoDrug,GAAGTGATCCGCCAGGTGA,NFKBIA,HSPD0000028140-NFKBIA,NoDrug,ENSG00000100906,NFKBIA,protein_coding,chr14:35401079-35404749;-1,14,8232103,1,14
19878,TTTGTTGGTGATTCAC-1_NoDrug,TGAAGACATCTCTTCATCG,BIRC2,HSPD0000002159-BIRC2,NoDrug,ENSG00000110330,BIRC2,protein_coding,chr11:102347208-102378680;1,11,8232401,1,11
19879,TTTGTTGTCTCGCGTT-1_NoDrug,CCGGGAACGGGACAGGGAT,NELFE,HSPD0000046601-NELFE,NoDrug,ENSG00000204356,NELFE,protein_coding,chr6:31952087-31959038;-1,6,8233387,1,6

### Add treatment information

In [31]:
cur_data.adata.obs['treatment_label'] = cur_data.adata.obs['condition'].map({
    'LRA-Positive': 'HIV infection|phorbol 13-acetate 12-myristate|ionomycin',
    'LRA-Negative': 'HIV infection|phorbol 13-acetate 12-myristate|ionomycin',
    'NoDrug': 'HIV infection|dimethyl sulfoxide'
})

cur_data.adata.obs['treatment_id'] = cur_data.adata.obs['condition'].map({
    'LRA-Positive': 'EFO:0000764|CHEBI:37537|CHEBI:63954',
    'LRA-Negative': 'EFO:0000764|CHEBI:37537|CHEBI:63954',
    'NoDrug': 'EFO:0000764|CHEBI:28262'
})

### Add metadata

In [32]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        "dataset_id": cur_data.dataset_id,
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        # perturbation type
        "perturbation_type_label": "CRISPRn",
        "perturbation_type_id": None,
        "data_modality": "Perturb-seq",
        "significant": None,
        "significance_criteria": None,
        "score_interpretation": None,

        "technical_replicate": None,
        "biological_replicate": None,
        # treatment
        # "treatment_label": None,
        # "treatment_id": None,
        # model system
        "model_system_label": "cell_line",
        "model_system_id": None,
        "tissue": "blood",
        "cell_line_label": "JURKAT cell",
        "cell_type_label": "T cell",
        "disease_label": "T-cell childhood acute lymphocytic leukemia|HIV infectious disease",
        "disease_id": "MONDO:0000871|MONDO:0005109",

        "timepoint": "P7DT16H0M0S",
        "species": "Homo sapiens",
        "sex_label": "male",
        "sex_id": None,
        "developmental_stage_label": "adolescent",
        "developmental_stage_id": None,

        "study_title": "Decoding heterogeneous single-cell perturbation responses",
        "study_uri": "https://doi.org/10.1038/s41556-025-01626-9",
        "study_year": 2025,
        "first_author": "Bicna Song",
        "last_author": "Wei Li",

        "experiment_title": "Focused CRISPRn Perturb-seq of HIV latency regulators in Jurkat HIV model cell line under three conditions: DMSO-treated, PMA/I GFP⁺ (HIV reactivated), PMA/I GFP⁻ (HIV latent)",
        "experiment_summary": """
            A focused Perturb-seq screen targeting 10 known regulators of HIV transcription was performed in a latently infected Jurkat T-cell model.
            Cells were cultured for 7 days, after which they were subjected to either DMSO or phorbol 13-acetate 12-myristate/ionomycin (PMA/I) treatment.
            After 16 hours of treatment, PMA/I-treated cells were sorted into GFP-positive (HIV reactivated) and GFP-negative (HIV latent) populations, and all three conditions were profiled by single-cell RNA-seq.
            """,

        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_coord'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],

        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",

        "library_generation_method_label": "SpCas9",
        "library_generation_method_id": "EFO:0022876",

        "enzyme_delivery_method_label": "lentivirus transduction",
        "enzyme_delivery_method_id": None,

        "library_delivery_method_label": "lentivirus transduction",
        "library_delivery_method_id": None,

        "enzyme_integration_state_label": "random locus integration",
        "enzyme_integration_state_id": None,

        "library_integration_state_label": "random locus integration",
        "library_integration_state_id": None,

        "enzyme_expression_control_label": "constitutive transgene expression",
        "enzyme_expression_control_id": None,

        "library_expression_control_label": "constitutive transgene expression",
        "library_expression_control_id": None,

        "library_name": "custom",
        "library_uri": None,

        "library_format_label": "pooled",
        "library_format_id": None,

        "library_scope_label": "focused",
        "library_scope_id": None,

        "library_perturbation_type_label": "knockout",
        "library_perturbation_type_id": None,

        "library_manufacturer": "Wei Li lab",
        "library_lentiviral_generation": "2",
        "library_grnas_per_target": "3",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()),
        "library_total_variants": None,

        "readout_dimensionality_label": "high-dimensional assay",
        "readout_dimensionality_id": None,

        "readout_type_label": "transcriptomic",
        "readout_type_id": None,

        "readout_technology_label": "single-cell rna-seq",
        "readout_technology_id": None,

        "method_name_label": "Perturb-seq",
        "method_name_id": None,

        "method_uri": None,

        "sequencing_library_kit_label": "10x Genomics Single Cell 3-prime",
        "sequencing_library_kit_id": None,

        "sequencing_platform_label": "Illumina NovaSeq 6000",
        "sequencing_platform_id": None,

        "sequencing_strategy_label": "barcode sequencing",
        "sequencing_strategy_id": None,

        "software_counts_label": "CellRanger",
        "software_counts_id": None,

        "software_analysis_label": "Seurat",
        "software_analysis_id": None,

        "reference_genome_label": "GRCh38",
        "reference_genome_id": None,
        
        "license_label": "CC BY 4.0",
        "license_id": "SWO:1000065",

        "associated_datasets": json.dumps([
            {
                "dataset_accession": "GSE247599",
                "dataset_uri": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE247599",
                "dataset_description": "Raw counts; matrix.mtx, features.tsv, barcodes.tsv",
                "dataset_file_name": "GSE247599_RAW.tar",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_type_label added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_format_label added to adata.obs
Column library_format_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_manufacturer added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_technology_label added to adata.obs
Column readout_technology_id added to adata.obs
Column method_name_label added to adata.obs
Column method_name_id added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_analysis_label added to adata.obs
Column software_analysis_id added to adata.obs
Column reference_genome_label added to adata.obs
Column reference_genome_id added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

In [33]:
cur_data.adata.obs

,cell_barcode,guide_sequence,gene,perturbation_name,condition,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding,treatment_label,treatment_id,dataset_id,sample_id,perturbation_type_label,perturbation_type_id,data_modality,significant,significance_criteria,score_interpretation,technical_replicate,biological_replicate,model_system_label,model_system_id,tissue,cell_line_label,cell_type_label,disease_label,disease_id,timepoint,species,sex_label,sex_id,developmental_stage_label,developmental_stage_id,study_title,study_uri,study_year,first_author,last_author,experiment_title,experiment_summary,number_of_perturbed_targets,number_of_perturbed_samples,library_generation_type_id,library_generation_type_label,library_generation_method_label,library_generation_method_id,enzyme_delivery_method_label,enzyme_delivery_method_id,library_delivery_method_label,library_delivery_method_id,enzyme_integration_state_label,enzyme_integration_state_id,library_integration_state_label,library_integration_state_id,enzyme_expression_control_label,enzyme_expression_control_id,library_expression_control_label,library_expression_control_id,library_name,library_uri,library_format_label,library_format_id,library_scope_label,library_scope_id,library_perturbation_type_label,library_perturbation_type_id,library_manufacturer,library_lentiviral_generation,library_grnas_per_target,library_total_grnas,library_total_variants,readout_dimensionality_label,readout_dimensionality_id,readout_type_label,readout_type_id,readout_technology_label,readout_technology_id,method_name_label,method_name_id,method_uri,sequencing_library_kit_label,sequencing_library_kit_id,sequencing_platform_label,sequencing_platform_id,sequencing_strategy_label,sequencing_strategy_id,software_counts_label,software_counts_id,software_analysis_label,software_analysis_id,reference_genome_label,reference_genome_id,license_label,license_id,associated_datasets
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,AAACCCAAGGGTGGGA-1_LRA-Positive,CCGGGAACGGGACAGGGAT,NELFE,HSPD0000046601-NELFE,LRA-Positive,ENSG00000204356,NELFE,protein_coding,chr6:31952087-31959038;-1,6,457,1,6,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,song_2025_jurkat_hiv,1,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
1,AAACCCACAGGTTCGC-1_LRA-Positive,GACTGATATGGCTGTTAAT,HDAC2,HSPD0000018544-HDAC2,LRA-Positive,ENSG00000196591,HDAC2,protein_coding,chr6:113933028-114011308;-1,6,1193,1,6,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,song_2025_jurkat_hiv,2,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
2,AAACCCAGTAGGTAGC-1_LRA-Positive,ACTCATTGCATAACTGTAG,BIRC2,HSPD0000002160-BIRC2,LRA-Positive,ENSG00000110330,BIRC2,protein_coding,chr11:102347208-102378680;1,11,1503,1,11,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,song_2025_jurkat_hiv,3,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
3,AAACCCAGTCACCACG-1_LRA-Positive,AGGGGGCGGATTTACCTAA,PRKCA,HSPD0000033203-PRKCA,LRA-Positive,ENSG00000154229,PRKCA,protein_coding,chr17:66302613-66810743;1,17,1585,1,17,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,song_2025_jurkat_hiv,4,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
4,AAACCCAGTTAACAGA-1_LRA-Positive,AAGCCCGTTTGGATCCATA,PRKCA,HSPD0000033201-PRKCA,LRA-Positive,ENSG00000154229,PRKCA,protein_coding,chr17:66302613-66810743;1,17,1931,1,17,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,song_2025_jurkat_hiv,5,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19875,TTTGTTGAGTTATGGA-1_NoDrug,CCACTTTCCGCAGAACACA,MAP3K14,HSPD0000052097-MAP3K14,NoDrug,ENSG00000006062,MAP3K14,protein_coding,chr17:45263119-45317112;-1,17,8231140,1,17,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,song_2025_jurkat_hiv,19876,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
19876,TTTGTTGCACATACTG-1_NoDrug,TGGGTCGTGTTGTGACCAT,CCNT1,HSPD0000005747-CCNT1,NoDrug,ENSG00000129315,CCNT1,protein_coding,chr12:48688458-48716998;-1,12,8231425,1,12,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,song_2025_jurkat_hiv,19877,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
19877,TTTGTTGGTATAGCTC-1_NoDrug,GAAGTGATCCGCCAGGTGA,NFKBIA,HSPD0000028140-NFKBIA,NoDrug,ENSG00000100906,NFKBIA,protein_coding,chr14:35401079-35404749;-1,14,8232103,1,14,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,song_2025_jurkat_hiv,19878,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
19878,TTTGTTGGTGATTCAC-1_NoDrug,TGAAGACATCTCTTCATCG,BIRC2,HSPD0000002159-BIRC2,NoDrug,ENSG00000110330,BIRC2,protein_coding,chr11:102347208-102378680;1,11,8232401,1,11,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,song_2025_jurkat_hiv,19879,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."
19879,TTTGTTGTCTCGCGTT-1_NoDrug,CCGGGAACGGGACAGGGAT,NELFE,HSPD0000046601-NELFE,NoDrug,ENSG00000204356,NELFE,protein_coding,chr6:31952087-31959038;-1,6,8233387,1,6,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,song_2025_jurkat_hiv,19880,CRISPRn,None,Perturb-seq,None,None,None,None,None,cell_line,None,blood,JURKAT cell,T cell,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,P7DT16H0M0S,Homo sapiens,male,None,adolescent,None,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,SpCas9,EFO:0022876,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,None,custom,None,pooled,None,focused,None,knockout,None,Wei Li lab,2,3,34,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,10x Genomics Single Cell 3-prime,None,Illumina NovaSeq 6000,None,barcode sequencing,None,CellRanger,None,Seurat,None,GRCh38,None,CC BY 4.0,SWO:1000065,"[{""dataset_accession"": ""GSE247599"", ""dataset_u..."

### Curate tissue information

In [34]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower     ontology_id
0        blood              blood      blood  UBERON:0000178
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [35]:
cur_data.standardize_ontology(
    input_column='cell_type_label',
    column_type='term_name',
    ontology_type='cell_type',
    overwrite=True
)

Mapped 1 cell_type ontology terms from `cell_type_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower name_lower ontology_id
0       T cell             t cell     t cell  CL:0000084
--------------------------------------------------
Overwriting column cell_type_label in adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell line information

In [36]:
cur_data.standardize_ontology(
    input_column='cell_line_label',
    column_type='term_name',
    ontology_type='cell_line',
    overwrite=True
)

Mapped 1 cell_line ontology terms from `cell_line_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
  input_column input_column_lower   name_lower  ontology_id
0  JURKAT cell        jurkat cell  jurkat cell  CLO:0007043
--------------------------------------------------
Overwriting column cell_line_label in adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [37]:
# cur_data.standardize_ontology(
#     input_column='disease_label',
#     column_type='term_name',
#     ontology_type='disease',
#     overwrite=True
# )

### Match schema column order

In [38]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [39]:
cur_data.validate_data(slot='obs', verbose=True)

2026-04-27 14:31:59,585 INFO curation_tools.curation_tools: adata.obs is valid according to the obs_schema.

,dataset_id,sample_id,cell_barcode,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,guide_sequence,perturbation_type_label,perturbation_type_id,timepoint,treatment_label,treatment_id,technical_replicate,biological_replicate,model_system_label,model_system_id,species,tissue_label,tissue_id,cell_type_label,cell_type_id,cell_line_label,cell_line_id,sex_label,sex_id,developmental_stage_label,developmental_stage_id,disease_label,disease_id,study_title,study_uri,study_year,first_author,last_author,experiment_title,experiment_summary,number_of_perturbed_targets,number_of_perturbed_samples,library_generation_type_id,library_generation_type_label,library_generation_method_id,library_generation_method_label,enzyme_delivery_method_id,enzyme_delivery_method_label,library_delivery_method_id,library_delivery_method_label,enzyme_integration_state_id,enzyme_integration_state_label,library_integration_state_id,library_integration_state_label,enzyme_expression_control_id,enzyme_expression_control_label,library_expression_control_id,library_expression_control_label,library_name,library_uri,library_format_id,library_format_label,library_scope_id,library_scope_label,library_perturbation_type_id,library_perturbation_type_label,library_manufacturer,library_lentiviral_generation,library_grnas_per_target,library_total_grnas,library_total_variants,readout_dimensionality_id,readout_dimensionality_label,readout_type_id,readout_type_label,readout_technology_id,readout_technology_label,method_name_id,method_name_label,method_uri,sequencing_library_kit_id,sequencing_library_kit_label,sequencing_platform_id,sequencing_platform_label,sequencing_strategy_id,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,song_2025_jurkat_hiv,1,AAACCCAAGGGTGGGA-1_LRA-Positive,Perturb-seq,<NA>,<NA>,HSPD0000046601-NELFE,chr6:31952087-31959038;-1,6,6,1,ENSG00000204356,NELFE,protein_coding,CCGGGAACGGGACAGGGAT,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
1,song_2025_jurkat_hiv,2,AAACCCACAGGTTCGC-1_LRA-Positive,Perturb-seq,<NA>,<NA>,HSPD0000018544-HDAC2,chr6:113933028-114011308;-1,6,6,1,ENSG00000196591,HDAC2,protein_coding,GACTGATATGGCTGTTAAT,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
2,song_2025_jurkat_hiv,3,AAACCCAGTAGGTAGC-1_LRA-Positive,Perturb-seq,<NA>,<NA>,HSPD0000002160-BIRC2,chr11:102347208-102378680;1,11,11,1,ENSG00000110330,BIRC2,protein_coding,ACTCATTGCATAACTGTAG,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
3,song_2025_jurkat_hiv,4,AAACCCAGTCACCACG-1_LRA-Positive,Perturb-seq,<NA>,<NA>,HSPD0000033203-PRKCA,chr17:66302613-66810743;1,17,17,1,ENSG00000154229,PRKCA,protein_coding,AGGGGGCGGATTTACCTAA,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
4,song_2025_jurkat_hiv,5,AAACCCAGTTAACAGA-1_LRA-Positive,Perturb-seq,<NA>,<NA>,HSPD0000033201-PRKCA,chr17:66302613-66810743;1,17,17,1,ENSG00000154229,PRKCA,protein_coding,AAGCCCGTTTGGATCCATA,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|phorbol 13-acetate 12-myristate|...,EFO:0000764|CHEBI:37537|CHEBI:63954,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19875,song_2025_jurkat_hiv,19876,TTTGTTGAGTTATGGA-1_NoDrug,Perturb-seq,<NA>,<NA>,HSPD0000052097-MAP3K14,chr17:45263119-45317112;-1,17,17,1,ENSG00000006062,MAP3K14,protein_coding,CCACTTTCCGCAGAACACA,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
19876,song_2025_jurkat_hiv,19877,TTTGTTGCACATACTG-1_NoDrug,Perturb-seq,<NA>,<NA>,HSPD0000005747-CCNT1,chr12:48688458-48716998;-1,12,12,1,ENSG00000129315,CCNT1,protein_coding,TGGGTCGTGTTGTGACCAT,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
19877,song_2025_jurkat_hiv,19878,TTTGTTGGTATAGCTC-1_NoDrug,Perturb-seq,<NA>,<NA>,HSPD0000028140-NFKBIA,chr14:35401079-35404749;-1,14,14,1,ENSG00000100906,NFKBIA,protein_coding,GAAGTGATCCGCCAGGTGA,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
19878,song_2025_jurkat_hiv,19879,TTTGTTGGTGATTCAC-1_NoDrug,Perturb-seq,<NA>,<NA>,HSPD0000002159-BIRC2,chr11:102347208-102378680;1,11,11,1,ENSG00000110330,BIRC2,protein_coding,TGAAGACATCTCTTCATCG,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065
19879,song_2025_jurkat_hiv,19880,TTTGTTGTCTCGCGTT-1_NoDrug,Perturb-seq,<NA>,<NA>,HSPD0000046601-NELFE,chr6:31952087-31959038;-1,6,6,1,ENSG00000204356,NELFE,protein_coding,CCGGGAACGGGACAGGGAT,CRISPRn,<NA>,P7DT16H0M0S,HIV infection|dimethyl sulfoxide,EFO:0000764|CHEBI:28262,<NA>,<NA>,cell_line,<NA>,Homo sapiens,blood,UBERON:0000178,T cell,CL:0000084,JURKAT cell,CLO:0007043,male,<NA>,adolescent,<NA>,T-cell childhood acute lymphocytic leukemia|HI...,MONDO:0000871|MONDO:0005109,Decoding heterogeneous single-cell perturbatio...,https://doi.org/10.1038/s41556-025-01626-9,2025,Bicna Song,Wei Li,Focused CRISPRn Perturb-seq of HIV latency reg...,\n A focused Perturb-seq screen tar...,12,19880,EFO:0022868,endogenous,EFO:0022876,SpCas9,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,knockout,Wei Li lab,2,3,34,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,10x Genomics Single Cell 3-prime,<NA>,Illumina NovaSeq 6000,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,Seurat,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""GSE247599"", ""dataset_u...",CC BY 4.0,SWO:1000065

# VAR slot curation

### Standardise genes

In [40]:
cur_data.show_var()

Variable data:
DataFrame shape: (36636, 2)
--------------------------------------------------
                              gene_name          feature_type
gene_id
ENSG00000243485             MIR1302-2HG       Gene Expression
ENSG00000237613                 FAM138A       Gene Expression
ENSG00000186092                   OR4F5       Gene Expression
ENSG00000238009              AL627309.1       Gene Expression
ENSG00000239945              AL627309.3       Gene Expression
...                                 ...                   ...
HSPD0000052096   HSPD0000052096_MAP3K14  CRISPR Guide Capture
HSPD0000052097   HSPD0000052097_MAP3K14  CRISPR Guide Capture
HSPD0000073810      HSPD0000073810_BRD4  CRISPR Guide Capture
HSPD0000073811      HSPD0000073811_BRD4  CRISPR Guide Capture
HSPD0000073812      HSPD0000073812_BRD4  CRISPR Guide Capture

[36636 rows x 2 columns]
--------------------------------------------------

In [41]:
# Keep only feature_type == Gene Expression
cur_data.adata = cur_data.adata[:, cur_data.adata.var['feature_type'] == 'Gene Expression'].copy()

In [42]:
cur_data.create_columns(
    slot = 'var',
    col_dict={'gene_ensembl_id': cur_data.adata.var.index},
    overwrite=True
)

Column gene_ensembl_id added to adata.var

In [43]:
cur_data.standardize_genes(
    slot="var",
    input_column="gene_ensembl_id",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

Missing Ensembl IDs: ['ENSG00000261757', 'ENSG00000228434', 'ENSG00000273403', 'ENSG00000253369', 'ENSG00000228008', 'ENSG00000286996', 'ENSG00000257603', 'ENSG00000273363', 'ENSG00000273164', 'ENSG00000272240', 'ENSG00000240401', 'ENSG00000280710', 'ENSG00000266450', 'ENSG00000263698', 'ENSG00000225655', 'ENSG00000238202', 'ENSG00000274367', 'ENSG00000261462', 'ENSG00000264334', 'ENSG00000253960', 'ENSG00000256694', 'ENSG00000240355', 'ENSG00000249860', 'ENSG00000224745', 'ENSG00000243944', 'ENSG00000269873', 'ENSG00000272482', 'ENSG00000250284', 'ENSG00000288019', 'ENSG00000251218', 'ENSG00000236673', 'ENSG00000112096', 'ENSG00000250046', 'ENSG00000274897', 'ENSG00000255028', 'ENSG00000261720', 'ENSG00000261737', 'ENSG00000230641', 'ENSG00000269899', 'ENSG00000276471', 'ENSG00000276631', 'ENSG00000255507', 'ENSG00000272948', 'ENSG00000261438', 'ENSG00000239332', 'ENSG00000232749', 'ENSG00000258631', 'ENSG00000233844', 'ENSG00000264920', 'ENSG00000255272', 'ENSG00000272196', 'ENSG00000259376', 'ENSG00000273123', 'ENSG00000273729', 'ENSG00000286919', 'ENSG00000235665', 'ENSG00000287101', 'ENSG00000286228', 'ENSG00000234166', 'ENSG00000256001', 'ENSG00000274652', 'ENSG00000263081', 'H13Ld2EGFP', 'ENSG00000285108', 'ENSG00000248942', 'ENSG00000230506', 'ENSG00000261386', 'ENSG00000233776', 'ENSG00000254619', 'ENSG00000256101', 'ENSG00000285719', 'ENSG00000223675', 'ENSG00000228561', 'ENSG00000280767', 'ENSG00000263443', 'ENSG00000188525', 'ENSG00000287346', 'ENSG00000273388', 'ENSG00000261490', 'ENSG00000227220', 'ENSG00000272650', 'ENSG00000244268', 'ENSG00000225986', 'ENSG00000257613', 'ENSG00000241990', 'ENSG00000231173', 'ENSG00000258861', 'ENSG00000274792', 'ENSG00000223797', 'ENSG00000235209', 'ENSG00000236129', 'ENSG00000253983', 'ENSG00000272040', 'ENSG00000227683', 'ENSG00000233509', 'ENSG00000272541', 'ENSG00000251678', 'ENSG00000228353', 'ENSG00000235736', 'ENSG00000282965', 'ENSG00000243135', 'ENSG00000264608', 'ENSG00000235111', 'ENSG00000260409', 'ENSG00000251506', 'ENSG00000287837', 'ENSG00000267034', 'ENSG00000261797', 'ENSG00000224739', 'ENSG00000277559', 'ENSG00000270019', 'ENSG00000264212', 'ENSG00000272732', 'ENSG00000258301', 'ENSG00000267279', 'ENSG00000203520', 'ENSG00000288380', 'ENSG00000244650', 'ENSG00000287941', 'ENSG00000269072', 'ENSG00000233799', 'ENSG00000263464', 'ENSG00000261305', 'ENSG00000283689', 'ENSG00000285875', 'ENSG00000273496', 'ENSG00000226079', 'ENSG00000250481', 'ENSG00000285766', 'ENSG00000249731', 'ENSG00000224228', 'ENSG00000260071', 'ENSG00000225916', 'ENSG00000259166', 'ENSG00000256739', 'ENSG00000286397', 'ENSG00000236996', 'ENSG00000272923', 'ENSG00000272583', 'ENSG00000272070', 'ENSG00000226380', 'ENSG00000286293', 'ENSG00000250551', 'ENSG00000279949', 'ENSG00000286906', 'ENSG00000287865', 'ENSG00000287811', 'ENSG00000263508', 'ENSG00000267327', 'ENSG00000263574', 'ENSG00000238358', 'ENSG00000286571', 'ENSG00000224167', 'ENSG00000236263', 'ENSG00000238042', 'ENSG00000213029', 'ENSG00000227925', 'ENSG00000274744', 'ENSG00000255945', 'ENSG00000270154', 'ENSG00000250686', 'ENSG00000229401', 'ENSG00000268810', 'ENSG00000287350', 'ENSG00000273373', 'ENSG00000271259', 'ENSG00000250511', 'ENSG00000250777', 'ENSG00000232386', 'ENSG00000255145', 'ENSG00000255644', 'ENSG00000277196', 'ENSG00000214970', 'ENSG00000261120', 'ENSG00000249381', 'ENSG00000235047', 'ENSG00000287753', 'ENSG00000286213', 'ENSG00000285584', 'ENSG00000286931', 'ENSG00000233200', 'ENSG00000204282', 'ENSG00000182912', 'ENSG00000249684', 'ENSG00000227029', 'ENSG00000204398', 'ENSG00000286079', 'ENSG00000223458', 'ENSG00000273138', 'ENSG00000259222', 'ENSG00000238102', 'ENSG00000229191', 'ENSG00000278266', 'ENSG00000272444', 'ENSG00000257962', 'ENSG00000250567', 'ENSG00000276345', 'ENSG00000287858', 'ENSG00000222022', 'ENSG00000256257', 'ENSG00000239216', 'ENSG00000273837', 'ENSG00000285808', 'ENSG00000261773', 'ENSG00000271815', 'ENSG00000270040', 'ENSG00000272218', 'ENSG00000235815', 'ENSG00000228393', 'ENSG00000227917', 'ENSG00000255325', 'ENSG00000275636', 'ENSG00000283648', 'ENSG00000268333', 'ENSG00000286494', 'ENSG00000267406', 'ENSG00000228113', 'ENSG00000286111', 'ENSG00000240875', 'ENSG00000239674', 'ENSG00000239462', 'ENSG00000259939', 'ENSG00000286351', 'ENSG00000235578', 'ENSG00000250156', 'ENSG00000286859', 'ENSG00000258170', 'ENSG00000224525', 'ENSG00000226403', 'ENSG00000226240', 'ENSG00000228216', 'ENSG00000231255', 'ENSG00000258600', 'ENSG00000273888', 'ENSG00000260780', 'ENSG00000203441', 'ENSG00000264660', 'ENSG00000266588', 'ENSG00000272009', 'ENSG00000250060', 'ENSG00000267388', 'ENSG00000272564', 'ENSG00000286542', 'ENSG00000273466', 'ENSG00000288002', 'ENSG00000225489', 'ENSG00000233840', 'ENSG00000258921', 'ENSG00000256050', 'ENSG00000264078', 'ENSG00000286292', 'ENSG00000206129', 'ENSG00000259582', 'ENSG00000276269', 'ENSG00000236839', 'ENSG00000275216', 'ENSG00000246331', 'ENSG00000249463', 'ENSG00000258785', 'ENSG00000267637', 'ENSG00000253400', 'ENSG00000224247', 'ENSG00000242375', 'ENSG00000240996', 'ENSG00000277352', 'ENSG00000235795', 'ENSG00000272465', 'ENSG00000286827', 'ENSG00000259664', 'ENSG00000270038', 'ENSG00000258473', 'ENSG00000249492', 'ENSG00000277501', 'ENSG00000253842', 'ENSG00000204683', 'ENSG00000273374', 'ENSG00000233415', 'ENSG00000260759', 'ENSG00000251532', 'ENSG00000240440', 'ENSG00000286854', 'ENSG00000268509', 'ENSG00000271751', 'ENSG00000286825', 'ENSG00000257477', 'ENSG00000254364', 'ENSG00000251314', 'ENSG00000241772', 'ENSG00000253235', 'ENSG00000255328', 'ENSG00000235934', 'ENSG00000230427', 'ENSG00000169789', 'ENSG00000232949', 'ENSG00000260030', 'ENSG00000237513', 'ENSG00000251652', 'ENSG00000278626', 'ENSG00000234936', 'ENSG00000270188', 'ENSG00000234677', 'ENSG00000264072', 'ENSG00000229352', 'ENSG00000256045', 'ENSG00000249837', 'ENSG00000253414', 'ENSG00000278198', 'ENSG00000277203', 'ENSG00000261650', 'ENSG00000231877', 'ENSG00000227021', 'ENSG00000286329', 'ENSG00000262558', 'ENSG00000287875', 'ENSG00000275294', 'ENSG00000267316', 'ENSG00000223704', 'ENSG00000286603', 'ENSG00000233214', 'ENSG00000256222', 'ENSG00000241912', 'ENSG00000260095', 'ENSG00000237563', 'ENSG00000286633', 'ENSG00000250410', 'ENSG00000259761', 'ENSG00000248311', 'ENSG00000233906', 'ENSG00000249166', 'ENSG00000250957', 'ENSG00000267697', 'ENSG00000253737', 'ENSG00000264080', 'ENSG00000233005', 'ENSG00000215271', 'ENSG00000272267', 'ENSG00000215159', 'ENSG00000274956', 'ENSG00000255015', 'ENSG00000280273', 'ENSG00000273733', 'ENSG00000234296', 'ENSG00000257164', 'ENSG00000278084', 'ENSG00000272519', 'ENSG00000286824', 'ENSG00000254290', 'ENSG00000272746', 'ENSG00000238158', 'ENSG00000256374', 'ENSG00000254427', 'ENSG00000258918', 'ENSG00000260276', 'ENSG00000276256', 'ENSG00000278674', 'ENSG00000272593', 'ENSG00000267105', 'ENSG00000130723', 'ENSG00000250446', 'ENSG00000254420', 'ENSG00000234306', 'ENSG00000258386', 'ENSG00000230090', 'ENSG00000223795', 'ENSG00000214955', 'ENSG00000277010', 'ENSG00000287906', 'ENSG00000239801', 'ENSG00000236166', 'ENSG00000261159', 'ENSG00000287702', 'ENSG00000236451', 'ENSG00000259274', 'ENSG00000233517', 'ENSG00000280987', 'ENSG00000249159', 'ENSG00000254744', 'ENSG00000233937', 'ENSG00000283907', 'ENSG00000223379', 'ENSG00000254651', 'ENSG00000254138', 'ENSG00000236740', 'ENSG00000273771', 'ENSG00000286504', 'ENSG00000259760', 'ENSG00000262292', 'ENSG00000239265', 'ENSG00000287139', 'ENSG00000276348', 'ENSG00000182230', 'ENSG00000287361', 'ENSG00000246627', 'ENSG00000256686', 'ENSG00000255160', 'ENSG00000273486', 'ENSG00000241792', 'ENSG00000234902', 'ENSG00000273211', 'ENSG00000225329', 'ENSG00000282080', 'ENSG00000251044', 'ENSG00000250310', 'ENSG00000230649', 'ENSG00000228951', 'ENSG00000231212', 'ENSG00000131484', 'ENSG00000237845', 'ENSG00000182584', 'ENSG00000229458', 'ENSG00000233970', 'ENSG00000286420', 'ENSG00000260183', 'ENSG00000176659', 'ENSG00000269986', 'ENSG00000255944', 'ENSG00000270114', 'ENSG00000235242', 'ENSG00000287649', 'ENSG00000285759', 'ENSG00000272316', 'ENSG00000262031', 'ENSG00000272354', 'ENSG00000254927', 'ENSG00000251144', 'ENSG00000276251', 'ENSG00000237422', 'ENSG00000258844', 'ENSG00000286761', 'ENSG00000281920', 'ENSG00000272382', 'ENSG00000280374', 'ENSG00000235245', 'ENSG00000278011', 'ENSG00000277856', 'ENSG00000272840', 'ENSG00000233852', 'ENSG00000286189', 'ENSG00000272872', 'ENSG00000273203', 'ENSG00000286564', 'ENSG00000285782', 'ENSG00000278878', 'ENSG00000271409', 'ENSG00000276867', 'ENSG00000286723', 'ENSG00000276649', 'ENSG00000257725', 'ENSG00000274828', 'ENSG00000257226', 'ENSG00000225643', 'ENSG00000285447', 'ENSG00000260581', 'ENSG00000237975', 'ENSG00000248103', 'ENSG00000248202', 'ENSG00000286997', 'ENSG00000272592', 'ENSG00000272922', 'ENSG00000253844', 'ENSG00000257194', 'ENSG00000260182', 'ENSG00000275249', 'ENSG00000244260', 'ENSG00000255817', 'ENSG00000237585', 'ENSG00000231140', 'ENSG00000214732', 'ENSG00000258949', 'ENSG00000250360', 'ENSG00000258131', 'ENSG00000251679', 'ENSG00000233256', 'ENSG00000258081', 'ENSG00000257183', 'ENSG00000249604', 'ENSG00000224959', 'ENSG00000287263', 'ENSG00000274031', 'ENSG00000234134', 'ENSG00000277999', 'ENSG00000282440', 'ENSG00000264443', 'ENSG00000286164', 'ENSG00000268674', 'ENSG00000240224', 'ENSG00000239467', 'ENSG00000253878', 'ENSG00000256271', 'ENSG00000223469', 'ENSG00000232597', 'ENSG00000286087', 'ENSG00000286977', 'ENSG00000231633', 'ENSG00000267058', 'ENSG00000224758', 'ENSG00000258196', 'ENSG00000231575', 'ENSG00000255169', 'ENSG00000287388', 'ENSG00000285535', 'ENSG00000226747', 'ENSG00000250415', 'ENSG00000229151', 'ENSG00000231846', 'ENSG00000271973', 'ENSG00000232680', 'ENSG00000274312', 'ENSG00000234405', 'ENSG00000259594', 'ENSG00000262890', 'ENSG00000259730', 'ENSG00000270147', 'ENSG00000273890', 'ENSG00000257454', 'ENSG00000255823', 'ENSG00000233029', 'ENSG00000228906', 'ENSG00000203812', 'ENSG00000212978', 'ENSG00000267420', 'ENSG00000266490', 'ENSG00000280095', 'ENSG00000266893', 'ENSG00000283255', 'ENSG00000253872', 'ENSG00000286755', 'ENSG00000250237', 'ENSG00000241572', 'ENSG00000254757', 'ENSG00000226376', 'ENSG00000270604', 'ENSG00000259126', 'ENSG00000268262', 'ENSG00000253671', 'ENSG00000235215', 'ENSG00000261775', 'ENSG00000228538', 'ENSG00000258831', 'ENSG00000244952', 'ENSG00000234698', 'ENSG00000272468', 'ENSG00000249203', 'ENSG00000269900', 'ENSG00000253197', 'ENSG00000232295', 'ENSG00000254028', 'ENSG00000268423', 'ENSG00000261193', 'ENSG00000287368', 'ENSG00000240240', 'ENSG00000267776', 'ENSG00000254836', 'ENSG00000226277', 'ENSG00000287868', 'ENSG00000232196', 'ENSG00000261039', 'ENSG00000247810', 'ENSG00000286534', 'ENSG00000233143', 'ENSG00000273923', 'ENSG00000284930', 'ENSG00000287116', 'ENSG00000229694', 'ENSG00000273119', 'ENSG00000251379', 'ENSG00000287523', 'ENSG00000261350', 'ENSG00000266908', 'ENSG00000258414', 'ENSG00000243179', 'ENSG00000288055', 'ENSG00000277836', 'ENSG00000139656', 'ENSG00000272369', 'ENSG00000244247', 'ENSG00000285933', 'ENSG00000272953', 'ENSG00000236716', 'ENSG00000237133', 'ENSG00000286778', 'ENSG00000287440', 'ENSG00000257711', 'ENSG00000256892', 'ENSG00000229912', 'ENSG00000256542', 'ENSG00000234998', 'ENSG00000287944', 'ENSG00000274902', 'ENSG00000250431', 'ENSG00000275063', 'ENSG00000287712', 'ENSG00000271156', 'ENSG00000249984', 'ENSG00000237838', 'ENSG00000224884', 'ENSG00000260951', 'ENSG00000232056', 'ENSG00000285922', 'ENSG00000273038', 'ENSG00000283504', 'ENSG00000288111', 'ENSG00000269926', 'ENSG00000235450', 'ENSG00000278817', 'ENSG00000276017', 'ENSG00000287438', 'ENSG00000272049', 'ENSG00000272030', 'ENSG00000267131', 'ENSG00000285155', 'ENSG00000271109', 'ENSG00000225640', 'ENSG00000277400', 'ENSG00000264067', 'ENSG00000276814', 'ENSG00000233408', 'ENSG00000286499', 'ENSG00000261502', 'ENSG00000229881', 'ENSG00000286501', 'ENSG00000249708', 'ENSG00000260793', 'ENSG00000237327', 'ENSG00000286687', 'ENSG00000267537', 'ENSG00000228255', 'ENSG00000236412', 'ENSG00000264790', 'ENSG00000271895', 'ENSG00000276075', 'ENSG00000235852', 'ENSG00000271911', 'ENSG00000278923', 'ENSG00000261218', 'ENSG00000183791', 'ENSG00000227192', 'ENSG00000273301', 'ENSG00000258885', 'ENSG00000244620', 'ENSG00000236008', 'ENSG00000229964', 'ENSG00000232294', 'ENSG00000260100', 'ENSG00000254814', 'ENSG00000241280', 'ENSG00000204805', 'ENSG00000287729', 'ENSG00000232325', 'ENSG00000272146', 'ENSG00000259444', 'ENSG00000286817', 'ENSG00000254095', 'ENSG00000248787', 'ENSG00000239407', 'ENSG00000226751', 'ENSG00000279987', 'ENSG00000254306', 'ENSG00000283517', 'ENSG00000258998', 'ENSG00000260163', 'ENSG00000261273', 'ENSG00000258642', 'ENSG00000287387', 'ENSG00000259306', 'ENSG00000253891', 'ENSG00000287313', 'ENSG00000269933', 'ENSG00000268355', 'ENSG00000272440', 'ENSG00000272085', 'ENSG00000262668', 'ENSG00000226377', 'ENSG00000236948', 'ENSG00000287884', 'ENSG00000229463', 'ENSG00000265671', 'ENSG00000260470', 'ENSG00000287798', 'ENSG00000272880', 'ENSG00000287974', 'ENSG00000280560', 'ENSG00000148362', 'ENSG00000287411', 'ENSG00000285399', 'ENSG00000226078', 'ENSG00000257322', 'ENSG00000265174', 'ENSG00000285424', 'ENSG00000258216', 'ENSG00000256427', 'ENSG00000248753', 'ENSG00000272370', 'ENSG00000244693', 'ENSG00000237262', 'ENSG00000257879', 'ENSG00000258772', 'ENSG00000267399', 'ENSG00000233818', 'ENSG00000280366', 'ENSG00000287708', 'ENSG00000267636', 'ENSG00000269888', 'ENSG00000275232', 'ENSG00000146521', 'ENSG00000241770', 'ENSG00000270394', 'ENSG00000248346', 'ENSG00000270105', 'ENSG00000241180', 'ENSG00000259436', 'ENSG00000284824', 'ENSG00000236938', 'ENSG00000248991', 'ENSG00000283886', 'ENSG00000286080', 'ENSG00000230836', 'ENSG00000262039', 'ENSG00000248533', 'ENSG00000286439', 'ENSG00000263264', 'ENSG00000276854', 'ENSG00000257277', 'ENSG00000278927', 'ENSG00000234141', 'ENSG00000279159', 'ENSG00000286462', 'ENSG00000223910', 'ENSG00000232411', 'ENSG00000286895', 'ENSG00000274307', 'ENSG00000251336', 'ENSG00000287577', 'ENSG00000269391', 'ENSG00000277423', 'ENSG00000232243', 'ENSG00000256287', 'ENSG00000256923', 'ENSG00000266002', 'ENSG00000225836', 'ENSG00000271904', 'ENSG00000230699', 'ENSG00000258028', 'ENSG00000273765', 'ENSG00000234223', 'ENSG00000223821', 'ENSG00000251399', 'ENSG00000223811', 'ENSG00000259123', 'ENSG00000232311', 'ENSG00000267517', 'ENSG00000236262', 'ENSG00000271870', 'ENSG00000282111', 'ENSG00000249091', 'ENSG00000286475', 'ENSG00000237352', 'ENSG00000234283', 'ENSG00000228139', 'ENSG00000225790', 'ENSG00000267243', 'ENSG00000261439', 'ENSG00000250234', 'ENSG00000286815', 'ENSG00000259618', 'ENSG00000235337', 'ENSG00000270178', 'ENSG00000225085', 'ENSG00000286599', 'ENSG00000263388', 'ENSG00000259995', 'ENSG00000253988', 'ENSG00000248359', 'ENSG00000253444', 'ENSG00000225742', 'ENSG00000253484', 'ENSG00000253381', 'ENSG00000231566', 'ENSG00000265943', 'ENSG00000228106', 'ENSG00000273370', 'ENSG00000232692', 'ENSG00000224532', 'ENSG00000267643', 'ENSG00000266957', 'ENSG00000249988', 'ENSG00000268615', 'ENSG00000248371', 'ENSG00000233376', 'ENSG00000224819', 'ENSG00000271955', 'ENSG00000229628', 'ENSG00000226822', 'ENSG00000259604', 'ENSG00000288436', 'ENSG00000258407', 'ENSG00000283440', 'ENSG00000260141', 'ENSG00000270672', 'ENSG00000286699', 'ENSG00000261666', 'ENSG00000234229', 'ENSG00000228452', 'ENSG00000287176', 'ENSG00000231979', 'ENSG00000253859', 'ENSG00000253762', 'ENSG00000273181', 'ENSG00000287211', 'ENSG00000259762', 'ENSG00000253139', 'ENSG00000243220', 'ENSG00000267683', 'ENSG00000286572', 'ENSG00000215067', 'ENSG00000170152', 'ENSG00000232034', 'ENSG00000276397', 'ENSG00000238266', 'ENSG00000277761', 'ENSG00000227920', 'ENSG00000276790', 'ENSG00000286265', 'ENSG00000287569', 'ENSG00000229454', 'ENSG00000259359', 'ENSG00000263688', 'ENSG00000258137', 'ENSG00000261445', 'ENSG00000258808', 'ENSG00000286133', 'ENSG00000255279', 'ENSG00000250670', 'ENSG00000287954', 'ENSG00000241520', 'ENSG00000269028', 'ENSG00000250948', 'ENSG00000253584', 'ENSG00000286622', 'ENSG00000249069', 'ENSG00000260060', 'ENSG00000282021', 'ENSG00000262089', 'ENSG00000237548', 'ENSG00000268050', 'ENSG00000223808', 'ENSG00000258345', 'ENSG00000257715', 'ENSG00000287316', 'ENSG00000283003', 'ENSG00000261222', 'ENSG00000230525', 'ENSG00000225932', 'ENSG00000250418', 'ENSG00000237954', 'ENSG00000237899', 'ENSG00000255479', 'ENSG00000272308', 'ENSG00000261135', 'ENSG00000254740', 'ENSG00000268364', 'ENSG00000248671', 'ENSG00000237359', 'ENSG00000283480', 'ENSG00000288101', 'ENSG00000250174', 'ENSG00000230205', 'ENSG00000225163', 'ENSG00000274175', 'ENSG00000235491', 'ENSG00000234083', 'ENSG00000249335', 'ENSG00000270195', 'ENSG00000225393', 'ENSG00000262180', 'ENSG00000271792', 'ENSG00000231616', 'ENSG00000232754', 'ENSG00000251613', 'ENSG00000258927', 'ENSG00000238009', 'ENSG00000179082', 'ENSG00000286978', 'ENSG00000274791', 'ENSG00000248240', 'ENSG00000235994', 'ENSG00000235271', 'ENSG00000273576', 'ENSG00000242753', 'ENSG00000273481', 'ENSG00000249008', 'ENSG00000248432', 'ENSG00000263316', 'ENSG00000277475', 'ENSG00000241475', 'ENSG00000251518', 'ENSG00000260487', 'ENSG00000265964', 'ENSG00000244545', 'ENSG00000261190', 'ENSG00000222030', 'ENSG00000230565', 'ENSG00000287622', 'ENSG00000258088', 'ENSG00000259209', 'ENSG00000248518', 'ENSG00000237356', 'ENSG00000272971', 'ENSG00000285769', 'ENSG00000287686', 'ENSG00000286915', 'ENSG00000278514', 'ENSG00000284700', 'ENSG00000236714', 'ENSG00000183729', 'ENSG00000266248', 'ENSG00000259616', 'ENSG00000273748', 'ENSG00000232636', 'ENSG00000249638', 'ENSG00000254695', 'ENSG00000234177', 'ENSG00000277050', 'ENSG00000253115', 'ENSG00000272567', 'ENSG00000257654', 'ENSG00000224204', 'ENSG00000272341', 'ENSG00000258302', 'ENSG00000265717', 'ENSG00000224342', 'ENSG00000233536', 'ENSG00000278704', 'ENSG00000250078', 'ENSG00000276250', 'ENSG00000248646', 'ENSG00000250012', 'ENSG00000275557', 'ENSG00000259998', 'ENSG00000285191', 'ENSG00000261470', 'ENSG00000263331', 'ENSG00000254561', 'ENSG00000260923', 'ENSG00000260517', 'ENSG00000236856', 'ENSG00000270157', 'ENSG00000228503', 'ENSG00000267115', 'ENSG00000266601', 'ENSG00000239446', 'ENSG00000270055', 'ENSG00000253931', 'ENSG00000228135', 'ENSG00000286911', 'ENSG00000230381', 'ENSG00000248461', 'ENSG00000236501', 'ENSG00000276760', 'ENSG00000278955', 'ENSG00000286362', 'ENSG00000259855', 'ENSG00000287843', 'ENSG00000282863', 'ENSG00000286601', 'ENSG00000270030', 'ENSG00000263588', 'ENSG00000267702', 'ENSG00000282887', 'ENSG00000272551', 'ENSG00000277901', 'ENSG00000253774', 'ENSG00000287400', 'ENSG00000233213', 'ENSG00000231128', 'ENSG00000263677', 'ENSG00000265975', 'ENSG00000274847', 'ENSG00000272755', 'ENSG00000249483', 'ENSG00000242396', 'ENSG00000287127', 'ENSG00000261068', 'ENSG00000287824', 'ENSG00000286863', 'ENSG00000286519', 'ENSG00000251654', 'ENSG00000275869', 'ENSG00000285656', 'ENSG00000184258', 'ENSG00000231305', 'ENSG00000227902', 'ENSG00000286374', 'ENSG00000275560', 'ENSG00000227011', 'ENSG00000234810', 'ENSG00000233987', 'ENSG00000253766', 'ENSG00000258265', 'ENSG00000241636', 'ENSG00000224481', 'ENSG00000261044', 'ENSG00000258092', 'ENSG00000231883', 'ENSG00000272940', 'ENSG00000286889', 'ENSG00000269894', 'ENSG00000273554', 'ENSG00000244063', 'ENSG00000227540', 'ENSG00000259255', 'ENSG00000286941', 'ENSG00000228334', 'ENSG00000250716', 'ENSG00000227305', 'ENSG00000251416', 'ENSG00000254180', 'ENSG00000250158', 'ENSG00000262227', 'ENSG00000233193', 'ENSG00000260461', 'ENSG00000287614', 'ENSG00000288046', 'ENSG00000224218', 'ENSG00000241317', 'ENSG00000272644', 'ENSG00000286016', 'ENSG00000231054', 'ENSG00000287168', 'ENSG00000286330', 'ENSG00000271254', 'ENSG00000236886', 'ENSG00000228890', 'ENSG00000259298', 'ENSG00000259820', 'ENSG00000233342', 'ENSG00000278633', 'ENSG00000283633', 'ENSG00000272736', 'ENSG00000237940', 'ENSG00000287564', 'ENSG00000260090', 'ENSG00000287248', 'ENSG00000286511', 'ENSG00000254039', 'ENSG00000272979', 'ENSG00000254115', 'ENSG00000286472', 'ENSG00000267787', 'ENSG00000228421', 'ENSG00000249125', 'ENSG000002614

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Replace missing gene symbols with original gene names

In [44]:
cur_data.adata.var['gene_symbol'] = cur_data.adata.var['gene_symbol'].fillna(cur_data.adata.var['gene_name'])

### Remove non ENSG entries from ensembl_gene_id column

In [45]:
cur_data.adata.var.loc[~cur_data.adata.var['ensembl_gene_id'].str.startswith('ENSG'), 'ensembl_gene_id'] = np.nan

### Validate var metadata

In [46]:
cur_data.validate_data(slot='var')

2026-04-27 14:32:37,108 INFO curation_tools.curation_tools: adata.var is valid according to the var_schema.

       ensembl_gene_id  gene_symbol
index
0      ENSG00000243485  MIR1302-2HG
1      ENSG00000237613      FAM138A
2      ENSG00000186092        OR4F5
3      ENSG00000241860   AL627309.1
4      ENSG00000239945   AL627309.3
...                ...          ...
36597  ENSG00000278633   AC023491.2
36598  ENSG00000276017   AC007325.1
36599  ENSG00000278817   AC007325.4
36600  ENSG00000277196   AC007325.2
36601              NaN   H13Ld2EGFP

[36602 rows x 2 columns]

# Save the dataset

In [47]:
cur_data.save_curated_data_h5ad()

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)
... storing 'dataset_id' as categorical

... storing 'data_modality' as categorical
... storing 'significance_criteria' as categorical
... storing 'perturbation_name' as categorical
... storing 'perturbed_target_coord' as categorical
... storing 'perturbed_target_chromosome' as categorical
... storing 'perturbed_target_ensg' as categorical
... storing 'perturbed_target_symbol' as categorical
... storing 'perturbed_target_biotype' as categorical
... storing 'guide_sequence' as categorical
... storing 'perturbation_type_label' as categorical
... storing 'perturbation_type_id' as categorical
... storing 'timepoint' as categorical
... storing 'treatment_label' as categorical
... storing 'treatment_id' as categorical
... storing 'technical_replicate' as categorical
... storing 'biological_replicate' as categorical
... storing 'model_system_label' as categorical
... storing 'model_system_id' as categorical
... storing 'species' as categorical
... storing 'tissue_label' as categorical
... storing 'tissue_id' as categorical
... storing 'cell_type_label' as categorical
... storing 'cell_type_id' as categorical
... storing 'cell_line_label' as categorical
... storing 'cell_line_id' as categorical
... storing 'sex_label' as categorical
... storing 'sex_id' as categorical
... storing 'developmental_stage_label' as categorical
... storing 'developmental_stage_id' as categorical
... storing 'disease_label' as categorical
... storing 'disease_id' as categorical
... storing 'study_title' as categorical
... storing 'study_uri' as categorical
... storing 'first_author' as categorical
... storing 'last_author' as categorical
... storing 'experiment_title' as categorical
... storing 'experiment_summary' as categorical
... storing 'number_of_perturbed_targets' as categorical
... storing 'number_of_perturbed_samples' as categorical
... storing 'library_generation_type_id' as categorical
... storing 'library_generation_type_label' as categorical
... storing 'library_generation_method_id' as categorical
... storing 'library_generation_method_label' as categorical
... storing 'enzyme_delivery_method_id' as categorical
... storing 'enzyme_delivery_method_label' as categorical
... storing 'library_delivery_method_id' as categorical
... storing 'library_delivery_method_label' as categorical
... storing 'enzyme_integration_state_id' as categorical
... storing 'enzyme_integration_state_label' as categorical
... storing 'library_integration_state_id' as categorical
... storing 'library_integration_state_label' as categorical
... storing 'enzyme_expression_control_id' as categorical
... storing 'enzyme_expression_control_label' as categorical
... storing 'library_expression_control_id' as categorical
... storing 'library_expression_control_label' as categorical
... storing 'library_name' as categorical
... storing 'library_uri' as categorical
... storing 'library_format_id' as categorical
... storing 'library_format_label' as categorical
... storing 'library_scope_id' as categorical
... storing 'library_scope_label' as categorical
... storing 'library_perturbation_type_id' as categorical
... storing 'library_perturbation_type_label' as categorical
... storing 'library_manufacturer' as categorical
... storing 'library_lentiviral_generation' as categorical
... storing 'library_grnas_per_target' as categorical
... storing 'library_total_grnas' as categorical
... storing 'readout_dimensionality_id' as categorical
... storing 'readout_dimensionality_label' as categorical
... storing 'readout_type_id' as categorical
... storing 'readout_type_label' as categorical
... storing 'readout_technology_id' as categorical
... storing 'readout_technology_label' as categorical
... storing 'method_name_id' as categorical
... storing 'method_name_label' as categorical
... storing 'method_uri' as categorical
... storing 'sequencing_library_kit_id' as categorical
... storing 'sequencing_library_kit_label' as categorical
... storing 'sequencing_platform_id' as categorical
... storing 'sequencing_platform_label' as categorical
... storing 'sequencing_strategy_id' as categorical
... storing 'sequencing_strategy_label' as categorical
... storing 'software_counts_id' as categorical
... storing 'software_counts_label' as categorical
... storing 'software_analysis_id' as categorical
... storing 'software_analysis_label' as categorical
... storing 'score_interpretation' as categorical
... storing 'reference_genome_id' as categorical
... storing 'reference_genome_label' as categorical
... storing 'associated_datasets' as categorical
... storing 'license_label' as categorical
... storing 'license_id' as categorical
... storing 'ensembl_gene_id' as categorical
... storing 'gene_symbol' as categorical

✅ Curated h5ad data saved to ../curated/h5ad/song_2025_jurkat_hiv_curated.h5ad

In [51]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/song_2025_jurkat_hiv_curated_metadata.parquet

# Upload to BigQuery

In [52]:
upload_parquet_to_bq(
    parquet_path='../curated/parquet/song_2025_jurkat_hiv_curated_metadata.parquet',
    bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
    bq_table_name='metadata',
    key_columns=['dataset_id', 'sample_id'],
    verbose=True
)

Staging table: loading `.parquet` file ../curated/parquet/song_2025_jurkat_hiv_curated_metadata.parquet to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging...
Staging table: loaded 19880 rows to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.perturb_seq.metadata with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.perturb_seq.metadata_staging

# Upload to GC Storage

In [53]:
!gcloud storage cp ../curated/h5ad/song_2025_jurkat_hiv_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://../curated/h5ad/song_2025_jurkat_hiv_curated.h5ad to gs://perturbation-catalogue-lake/perturbseq/curated/song_2025_jurkat_hiv_curated.h5ad
  Completed files 24/1 | 1.1GiB/1.1GiB | 323.6MiB/s

Average throughput: 290.8MiB/s