# Import

In [1]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("curation.log"),
        logging.StreamHandler(),  # keep console output too
    ],
    force=True,
)
# show all columns
pd.set_option('display.max_columns', None)

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/.venv/lib/python3.12/site-packages/pandera/_pandas_deprecated.py:157: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

# Download data

In [10]:
# !aws s3 cp --no-sign-request s3://genome-scale-tcell-perturb-seq/marson2025_data/D1_Rest.assigned_guide.h5ad ../non_curated/h5ad/zhu_2025_D1_rest_cl.h5ad
# !mv /content/PerturbationCatalogue/data_exploration/Perturbseq/non_curated/h5ad/D1_Rest.assigned_guide.h5ad /content/PerturbationCatalogue/data_exploration/Perturbseq/non_curated/h5ad/zhu_2025_pseudobulk.h5ad

UsageError: Line magic function `%aws` not found.

In [14]:
!pwd

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/Perturbseq/curation_notebooks

# Initialise the dataset object

In [15]:
noncurated_path = '../non_curated/h5ad/zhu_2025_D1_rest_cl.h5ad'
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/zhu_2025_D1_rest_cl.h5ad

In [21]:
cur_data.adata.obs

,lane_id,n_genes_by_counts,total_counts,pct_counts_mt,top_guide_UMI_counts,guide_id,perturbed_gene_name,perturbed_gene_id,guide_type,PuroR,guide_group,low_quality,cell_barcode,perturbation_name
AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L08,1953,2969.0,0.269451,NaN,NaN,NaN,NaN,NaN,2.100727,no sgRNA,False,AAACAAGCAAACCGGTATGTTGAC-1,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08
AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L08,4576,13363.0,1.017735,22.0,NTC-461,NTC,NTC,non-targeting,1.431987,targeting single sgRNA,False,AAACAAGCAAATACCGATGTTGAC-1,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08
AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L08,1890,3016.0,0.397878,9.0,PLA2G10-2,PLA2G10,ENSG00000069764,targeting,1.209989,targeting single sgRNA,False,AAACAAGCAAATCACGATGTTGAC-1,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08
AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L08,5070,16130.0,0.440174,10.0,ATXN7L3-1,ATXN7L3,ENSG00000087152,targeting,1.015303,targeting single sgRNA,False,AAACAAGCAACAAAGAAACGGGAA-1,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08
AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L08,4881,13876.0,0.317094,102.0,EVI5-1,EVI5,ENSG00000067208,targeting,2.463184,targeting single sgRNA,False,AAACAAGCAACAAAGAACTTTAGG-1,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L21,2725,5182.0,0.135083,NaN,NaN,NaN,NaN,NaN,1.451924,no sgRNA,False,TTTGTGAGTTGTGACTAACGGGAA-1,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21
TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L21,4145,10171.0,0.304788,NaN,NaN,NaN,NaN,NaN,1.466352,no sgRNA,False,TTTGTGAGTTGTGACTATGTTGAC-1,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21
TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L21,3504,9302.0,0.225758,NaN,NaN,NaN,NaN,NaN,0.000000,no sgRNA,False,TTTGTGAGTTTAACCAAGTAGGCT-1,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21
TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L21,2624,4919.0,0.203293,25.0,KIF18A-2,KIF18A,ENSG00000121621,targeting,1.492056,targeting single sgRNA,False,TTTGTGAGTTTCGCCTACTTTAGG-1,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21
TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21_CD4i_R1_D1_Rest_CD4i_R1_Ultima,CD4i_R1L21,3231,6540.0,0.030581,42.0,ZNF442-2,ZNF442,ENSG00000198342,targeting,2.538781,targeting single sgRNA,False,TTTGTGAGTTTGTTGAAACGGGAA-1,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21

In [20]:
cur_data.adata.var

                        gene_ids    feature_types  genome gene_name     mt
ENSG00000000003  ENSG00000000003  Gene Expression  GRCh38    TSPAN6  False
ENSG00000000005  ENSG00000000005  Gene Expression  GRCh38      TNMD  False
ENSG00000000419  ENSG00000000419  Gene Expression  GRCh38      DPM1  False
ENSG00000000457  ENSG00000000457  Gene Expression  GRCh38     SCYL3  False
ENSG00000000460  ENSG00000000460  Gene Expression  GRCh38  C1orf112  False
...                          ...              ...     ...       ...    ...
ENSG00000291122  ENSG00000291122  Gene Expression  GRCh38  CASTOR3P  False
ENSG00000291135  ENSG00000291135  Gene Expression  GRCh38   FCGR1BP  False
ENSG00000291145  ENSG00000291145  Gene Expression  GRCh38   PPP5D1P  False
ENSG00000291237  ENSG00000291237  Gene Expression  GRCh38      SOD2  False
CUSTOM001_PuroR  CUSTOM001_PuroR  Gene Expression  GRCh38     PuroR  False

[18130 rows x 5 columns]

# OBS slot curation

### Since for multi-guide perturbations the identities of said guides are unknown, we are filtering out these cells.

In [18]:
print(f"Number of cells before filtering: {cur_data.adata.n_obs}")
cur_data.adata = cur_data.adata[cur_data.adata.obs['guide_id'] != 'multi_sgRNA']
print(f"Number of cells after filtering: {cur_data.adata.n_obs}")

Number of cells before filtering: 3074496
Number of cells after filtering: 2548393

### Add `index` as `perturbation_name`

In [19]:
cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.str.split('_').str[0]
cur_data.adata.obs['perturbation_name'] = cur_data.adata.obs['cell_barcode'] +'_'+cur_data.adata.obs['lane_id'].astype(str)

/tmp/ipykernel_2509942/2231587657.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.str.split('_').str[0]

### Show unique perturbations

In [ ]:
cur_data.show_unique(slot = 'obs', column = 'perturbation_name')

### Add guide RNA information

In [23]:
# download the guide RNA spreadsheet
download_file(
    url="https://raw.githubusercontent.com/emdann/GWT_perturbseq_analysis_2025/refs/heads/master/metadata/suppl_tables/sgrna_library_metadata.suppl_table.csv",
    dest_path="../supplementary/zhu_2025_guide_info.csv"
)
# read in the guide RNA info csv
guide_info_df = pd.read_csv("../supplementary/zhu_2025_guide_info.csv")

guide_info_df = guide_info_df[['sgRNA', 'seq']]

guide_info_df['sgRNA'] = guide_info_df['sgRNA'].str.replace('1-Jun','JUN-1').str.replace('2-Jun','JUN-2')

guide_info_df = guide_info_df.rename(columns={'seq': 'guide_sequence', 'sgRNA':'guide_id'})

guide_info_df

Downloaded https://raw.githubusercontent.com/emdann/GWT_perturbseq_analysis_2025/refs/heads/master/metadata/suppl_tables/sgrna_library_metadata.suppl_table.csv to ../supplementary/zhu_2025_guide_info.csv

        guide_id        guide_sequence
0        ARMC5-1  CTGCCTCGCGCAGCTCGCGG
1         DDB1-1  GGAGTTCGCTGCGCGCTGTT
2       FNDC10-1  TGCCCGCTCCCCGCGATCCC
3         RORC-1  TCTGTGGGGCCCTGTCCATG
4      SLC35F6-1  GAACAGCTGGTACTTGGTCC
...          ...                   ...
26499    NTC-988  TTTCAGGCTACGGGCGCGGG
26500    NTC-989  TTTCCCATGATCATTTAGTG
26501    NTC-990  TTTCGCCCAAGAGGCTTGGG
26502    NTC-991  TTTCGTGCCGATGTAACACA
26503    NTC-992  TTTGGGTTTATCCGCCCCCA

[26504 rows x 2 columns]

In [24]:
print("Number of overlapping guides with cur_data:")
cur_data.adata.obs['guide_id'].isin(guide_info_df['guide_id'].to_list()).value_counts()

Number of overlapping guides with cur_data:

guide_id
True     1754014
False     794379
Name: count, dtype: int64

In [25]:
# merge cur_data.adata.obs with guide_info_df
cur_data.adata.obs = cur_data.adata.obs.merge(guide_info_df, on='guide_id', how='left')
# check that there are no missing guide sequences
print(f"Number of missing guide sequences: {cur_data.adata.obs['guide_sequence'].isna().sum()}")

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

Number of missing guide sequences: 794379

In [28]:
cur_data.adata.obs

,lane_id,n_genes_by_counts,total_counts,pct_counts_mt,top_guide_UMI_counts,guide_id,perturbed_gene_name,perturbed_gene_id,guide_type,PuroR,guide_group,low_quality,cell_barcode,perturbation_name,guide_sequence
0,CD4i_R1L08,1953,2969.0,0.269451,NaN,NaN,control_casonly,control_casonly,NaN,2.100727,no sgRNA,False,AAACAAGCAAACCGGTATGTTGAC-1,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,NaN
1,CD4i_R1L08,4576,13363.0,1.017735,22.0,NTC-461,control_nontargeting,control_nontargeting,non-targeting,1.431987,targeting single sgRNA,False,AAACAAGCAAATACCGATGTTGAC-1,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,TGGGAATTCCTCGGCCGATT
2,CD4i_R1L08,1890,3016.0,0.397878,9.0,PLA2G10-2,PLA2G10,ENSG00000069764,targeting,1.209989,targeting single sgRNA,False,AAACAAGCAAATCACGATGTTGAC-1,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,GGGTGCTGCAGGGCCACCGG
3,CD4i_R1L08,5070,16130.0,0.440174,10.0,ATXN7L3-1,ATXN7L3,ENSG00000087152,targeting,1.015303,targeting single sgRNA,False,AAACAAGCAACAAAGAAACGGGAA-1,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,GAGCGCGTGCATCTGCCCCG
4,CD4i_R1L08,4881,13876.0,0.317094,102.0,EVI5-1,EVI5,ENSG00000067208,targeting,2.463184,targeting single sgRNA,False,AAACAAGCAACAAAGAACTTTAGG-1,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,GGAGGAACCAGCTGGCCAGC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548388,CD4i_R1L21,2725,5182.0,0.135083,NaN,NaN,control_casonly,control_casonly,NaN,1.451924,no sgRNA,False,TTTGTGAGTTGTGACTAACGGGAA-1,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,NaN
2548389,CD4i_R1L21,4145,10171.0,0.304788,NaN,NaN,control_casonly,control_casonly,NaN,1.466352,no sgRNA,False,TTTGTGAGTTGTGACTATGTTGAC-1,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,NaN
2548390,CD4i_R1L21,3504,9302.0,0.225758,NaN,NaN,control_casonly,control_casonly,NaN,0.000000,no sgRNA,False,TTTGTGAGTTTAACCAAGTAGGCT-1,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,NaN
2548391,CD4i_R1L21,2624,4919.0,0.203293,25.0,KIF18A-2,KIF18A,ENSG00000121621,targeting,1.492056,targeting single sgRNA,False,TTTGTGAGTTTCGCCTACTTTAGG-1,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,AGGCGGACATTAAAGTGAAG
2548392,CD4i_R1L21,3231,6540.0,0.030581,42.0,ZNF442-2,ZNF442,ENSG00000198342,targeting,2.538781,targeting single sgRNA,False,TTTGTGAGTTTGTTGAAACGGGAA-1,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,GCTGGCAGCGGGGAACCTTG

In [27]:
# change perturbed_gene_id from categorical to string
cur_data.adata.obs['perturbed_gene_id'] = cur_data.adata.obs['perturbed_gene_id'].astype(str)
cur_data.adata.obs['perturbed_gene_name'] = cur_data.adata.obs['perturbed_gene_name'].astype(str)

cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_id'].isin(['NTC']), 'perturbed_gene_id'] = 'control_nontargeting'
cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_name'].isin(['NTC']), 'perturbed_gene_name'] = 'control_nontargeting'

cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_id'].isna(), 'perturbed_gene_id'] = 'control_casonly'
cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_name'].isna(), 'perturbed_gene_name'] = 'control_casonly'

### Standardise perturbation targets

In [29]:
cur_data.standardize_genes(
    slot='obs',
    input_column='perturbed_gene_id',
    input_column_type='ensembl_gene_id',
    multiple_entries=False,
    # remove_version=True,
    # version_sep='.'
)

Missing Ensembl IDs: ['AKAP2', 'ENSG00000277796', 'LUZP6', 'ENSG00000203812', 'ENSG00000255823', 'ENSG00000182230', 'ENSG00000148362', 'ENSG00000232196', 'OCLM', 'ENSG00000256618', 'SEPT6', 'U2AF1L5', 'SMIM11B', 'SGK494']; attempting to fetch latest IDs...
Fetched latest Ensembl IDs: {'ENSG00000277796': 'ENSG00000293545', 'ENSG00000203812': 'ENSG00000288825', 'ENSG00000255823': nan, 'ENSG00000182230': nan, 'ENSG00000148362': 'ENSG00000310560', 'ENSG00000232196': nan, 'ENSG00000256618': nan}
--------------------------------------------------
Successfully mapped 12101 out of 12101 Ensembl IDs.
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [30]:
cur_data.adata.obs

,top_guide_UMI_counts,PuroR,guide_id,perturbed_gene_name,guide_sequence,guide_group,n_genes_by_counts,perturbation_name,perturbed_gene_id,total_counts,cell_barcode,lane_id,low_quality,pct_counts_mt,guide_type,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index
index,,,,,,,,,,,,,,,,,,,,,
0,NaN,2.100727,NaN,control_casonly,NaN,no sgRNA,1953,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,control_casonly,2969.0,AAACAAGCAAACCGGTATGTTGAC-1,CD4i_R1L08,False,0.269451,NaN,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,0
1,22.0,1.431987,NTC-461,control_nontargeting,TGGGAATTCCTCGGCCGATT,targeting single sgRNA,4576,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,control_nontargeting,13363.0,AAACAAGCAAATACCGATGTTGAC-1,CD4i_R1L08,False,1.017735,non-targeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,1
2,9.0,1.209989,PLA2G10-2,PLA2G10,GGGTGCTGCAGGGCCACCGG,targeting single sgRNA,1890,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,ENSG00000069764,3016.0,AAACAAGCAAATCACGATGTTGAC-1,CD4i_R1L08,False,0.397878,targeting,ENSG00000069764,PLA2G10,protein_coding,chr16:14672548-14694308;-1,16,2
3,10.0,1.015303,ATXN7L3-1,ATXN7L3,GAGCGCGTGCATCTGCCCCG,targeting single sgRNA,5070,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,ENSG00000087152,16130.0,AAACAAGCAACAAAGAAACGGGAA-1,CD4i_R1L08,False,0.440174,targeting,ENSG00000087152,ATXN7L3,protein_coding,chr17:44191805-44200961;-1,17,3
4,102.0,2.463184,EVI5-1,EVI5,GGAGGAACCAGCTGGCCAGC,targeting single sgRNA,4881,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,ENSG00000067208,13876.0,AAACAAGCAACAAAGAACTTTAGG-1,CD4i_R1L08,False,0.317094,targeting,ENSG00000067208,EVI5,protein_coding,chr1:92508696-92792416;-1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548388,NaN,1.451924,NaN,control_casonly,NaN,no sgRNA,2725,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,control_casonly,5182.0,TTTGTGAGTTGTGACTAACGGGAA-1,CD4i_R1L21,False,0.135083,NaN,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,2548388
2548389,NaN,1.466352,NaN,control_casonly,NaN,no sgRNA,4145,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,control_casonly,10171.0,TTTGTGAGTTGTGACTATGTTGAC-1,CD4i_R1L21,False,0.304788,NaN,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,2548389
2548390,NaN,0.000000,NaN,control_casonly,NaN,no sgRNA,3504,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,control_casonly,9302.0,TTTGTGAGTTTAACCAAGTAGGCT-1,CD4i_R1L21,False,0.225758,NaN,control_casonly,control_casonly,control_casonly,control_casonly,control_casonly,2548390
2548391,25.0,1.492056,KIF18A-2,KIF18A,AGGCGGACATTAAAGTGAAG,targeting single sgRNA,2624,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,ENSG00000121621,4919.0,TTTGTGAGTTTCGCCTACTTTAGG-1,CD4i_R1L21,False,0.203293,targeting,ENSG00000121621,KIF18A,protein_coding,chr11:28020618-28108183;-1,11,2548391
2548392,42.0,2.538781,ZNF442-2,ZNF442,GCTGGCAGCGGGGAACCTTG,targeting single sgRNA,3231,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,ENSG00000198342,6540.0,TTTGTGAGTTTGTTGAAACGGGAA-1,CD4i_R1L21,False,0.030581,targeting,ENSG00000198342,ZNF442,protein_coding,chr19:12345944-12365905;-1,19,2548392

# Manually replace some genes

In [31]:
# define genes to replace in the cur_data.adata.obs
genes_to_replace = cur_data.adata.obs[cur_data.adata.obs['perturbed_target_symbol'].isna()]['perturbed_gene_name'].drop_duplicates().to_list()
# define columns to replace
cols_to_replace = ['perturbed_target_ensg',	'perturbed_target_symbol',	'perturbed_target_biotype',	'perturbed_target_coord',	'perturbed_target_chromosome']
# define mapping dict for renaming columns in gene_ont for replacement
gene_ont_col_mapping = {
    'ensembl_gene_id':'perturbed_target_ensg',
    'gene_symbol':'perturbed_target_symbol',
    'biotype':'perturbed_target_biotype',
    'gene_coord':'perturbed_target_coord',
    'chromosome_name':'perturbed_target_chromosome'
}
# loop through genes and fill in the missing cols
for replacement_gene in genes_to_replace:
    if replacement_gene in cur_data.gene_ont['synonym'].values:
        # subset gene_ont and get values for replacement
        replacement = (
            cur_data.gene_ont.rename(columns=gene_ont_col_mapping)
            .loc[cur_data.gene_ont['synonym'].isin([replacement_gene]), cols_to_replace]
        )[cols_to_replace].values[0]
        # replace values in cur_data.adata.obs with the values from gene_ont
        cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_name'].isin([replacement_gene]), cols_to_replace] = replacement
        print(f"Replaced {replacement_gene} with {replacement}")
    else:
        print(f"No replacement found for {replacement_gene}")

No replacement found for MTRNR2L1
No replacement found for FAM153B
No replacement found for AKAP2
Replaced SEPT6 with ['ENSG00000125354' 'SEPTIN6' 'protein_coding'
 'chrX:119615724-119693949;-1' 'X']
No replacement found for SMIM11B
No replacement found for MTRNR2L4
No replacement found for LUZP6
No replacement found for OCLM
Replaced SGK494 with ['ENSG00000167524' 'RSKR' 'protein_coding' 'chr17:28455752-28614197;-1'
 '17']
No replacement found for U2AF1L5
No replacement found for CCL3L1
No replacement found for MTRNR2L8

In [32]:
# replace non-mapped perturbed_target_symbol with original gene symbols
cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_target_symbol'].isna(), 'perturbed_target_symbol'] = cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_target_symbol'].isna(), 'perturbed_gene_name'].values

In [33]:
# replace entries in perturbed_target_ensg that are not ENSEMBL ids with NA
cur_data.adata.obs.loc[(~cur_data.adata.obs['perturbed_target_ensg'].str.startswith('ENSG')) & (cur_data.adata.obs['perturbed_target_ensg'] != 'control_nontargeting'), 'perturbed_target_ensg'] = pd.NA

In [34]:
cur_data.adata.obs

,top_guide_UMI_counts,PuroR,guide_id,perturbed_gene_name,guide_sequence,guide_group,n_genes_by_counts,perturbation_name,perturbed_gene_id,total_counts,cell_barcode,lane_id,low_quality,pct_counts_mt,guide_type,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index
index,,,,,,,,,,,,,,,,,,,,,
0,NaN,2.100727,NaN,control_casonly,NaN,no sgRNA,1953,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,control_casonly,2969.0,AAACAAGCAAACCGGTATGTTGAC-1,CD4i_R1L08,False,0.269451,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,0
1,22.0,1.431987,NTC-461,control_nontargeting,TGGGAATTCCTCGGCCGATT,targeting single sgRNA,4576,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,control_nontargeting,13363.0,AAACAAGCAAATACCGATGTTGAC-1,CD4i_R1L08,False,1.017735,non-targeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,1
2,9.0,1.209989,PLA2G10-2,PLA2G10,GGGTGCTGCAGGGCCACCGG,targeting single sgRNA,1890,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,ENSG00000069764,3016.0,AAACAAGCAAATCACGATGTTGAC-1,CD4i_R1L08,False,0.397878,targeting,ENSG00000069764,PLA2G10,protein_coding,chr16:14672548-14694308;-1,16,2
3,10.0,1.015303,ATXN7L3-1,ATXN7L3,GAGCGCGTGCATCTGCCCCG,targeting single sgRNA,5070,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,ENSG00000087152,16130.0,AAACAAGCAACAAAGAAACGGGAA-1,CD4i_R1L08,False,0.440174,targeting,ENSG00000087152,ATXN7L3,protein_coding,chr17:44191805-44200961;-1,17,3
4,102.0,2.463184,EVI5-1,EVI5,GGAGGAACCAGCTGGCCAGC,targeting single sgRNA,4881,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,ENSG00000067208,13876.0,AAACAAGCAACAAAGAACTTTAGG-1,CD4i_R1L08,False,0.317094,targeting,ENSG00000067208,EVI5,protein_coding,chr1:92508696-92792416;-1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548388,NaN,1.451924,NaN,control_casonly,NaN,no sgRNA,2725,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,control_casonly,5182.0,TTTGTGAGTTGTGACTAACGGGAA-1,CD4i_R1L21,False,0.135083,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548388
2548389,NaN,1.466352,NaN,control_casonly,NaN,no sgRNA,4145,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,control_casonly,10171.0,TTTGTGAGTTGTGACTATGTTGAC-1,CD4i_R1L21,False,0.304788,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548389
2548390,NaN,0.000000,NaN,control_casonly,NaN,no sgRNA,3504,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,control_casonly,9302.0,TTTGTGAGTTTAACCAAGTAGGCT-1,CD4i_R1L21,False,0.225758,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548390
2548391,25.0,1.492056,KIF18A-2,KIF18A,AGGCGGACATTAAAGTGAAG,targeting single sgRNA,2624,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,ENSG00000121621,4919.0,TTTGTGAGTTTCGCCTACTTTAGG-1,CD4i_R1L21,False,0.203293,targeting,ENSG00000121621,KIF18A,protein_coding,chr11:28020618-28108183;-1,11,2548391
2548392,42.0,2.538781,ZNF442-2,ZNF442,GCTGGCAGCGGGGAACCTTG,targeting single sgRNA,3231,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,ENSG00000198342,6540.0,TTTGTGAGTTTGTTGAAACGGGAA-1,CD4i_R1L21,False,0.030581,targeting,ENSG00000198342,ZNF442,protein_coding,chr19:12345944-12365905;-1,19,2548392

### Add `perturbed_target_number` column

In [35]:
# cur_data.count_entries(
#     slot='obs',
#     input_column='perturbed_target_ensg',
#     count_column_name='perturbed_target_number',
#     sep='|'
# )
cur_data.adata.obs['perturbed_target_number'] = 1

### Encode chromosomes as integers

In [36]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

In [38]:
cur_data.adata.obs[['perturbation_name', 'perturbed_target_chromosome_encoding']]

,perturbation_name,perturbed_target_chromosome_encoding
index,,
0,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,0
1,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,0
2,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,16
3,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,17
4,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,1
...,...,...
2548388,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,0
2548389,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,0
2548390,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,0
2548391,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,11
2548392,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,19

In [40]:
cur_data.adata.obs

,top_guide_UMI_counts,PuroR,guide_id,perturbed_gene_name,guide_sequence,guide_group,n_genes_by_counts,perturbation_name,perturbed_gene_id,total_counts,cell_barcode,lane_id,low_quality,pct_counts_mt,guide_type,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding
index,,,,,,,,,,,,,,,,,,,,,,,
0,NaN,2.100727,NaN,control_casonly,NaN,no sgRNA,1953,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,control_casonly,2969.0,AAACAAGCAAACCGGTATGTTGAC-1,CD4i_R1L08,False,0.269451,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,0,1,0
1,22.0,1.431987,NTC-461,control_nontargeting,TGGGAATTCCTCGGCCGATT,targeting single sgRNA,4576,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,control_nontargeting,13363.0,AAACAAGCAAATACCGATGTTGAC-1,CD4i_R1L08,False,1.017735,non-targeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,1,1,0
2,9.0,1.209989,PLA2G10-2,PLA2G10,GGGTGCTGCAGGGCCACCGG,targeting single sgRNA,1890,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,ENSG00000069764,3016.0,AAACAAGCAAATCACGATGTTGAC-1,CD4i_R1L08,False,0.397878,targeting,ENSG00000069764,PLA2G10,protein_coding,chr16:14672548-14694308;-1,16,2,1,16
3,10.0,1.015303,ATXN7L3-1,ATXN7L3,GAGCGCGTGCATCTGCCCCG,targeting single sgRNA,5070,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,ENSG00000087152,16130.0,AAACAAGCAACAAAGAAACGGGAA-1,CD4i_R1L08,False,0.440174,targeting,ENSG00000087152,ATXN7L3,protein_coding,chr17:44191805-44200961;-1,17,3,1,17
4,102.0,2.463184,EVI5-1,EVI5,GGAGGAACCAGCTGGCCAGC,targeting single sgRNA,4881,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,ENSG00000067208,13876.0,AAACAAGCAACAAAGAACTTTAGG-1,CD4i_R1L08,False,0.317094,targeting,ENSG00000067208,EVI5,protein_coding,chr1:92508696-92792416;-1,1,4,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548388,NaN,1.451924,NaN,control_casonly,NaN,no sgRNA,2725,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,control_casonly,5182.0,TTTGTGAGTTGTGACTAACGGGAA-1,CD4i_R1L21,False,0.135083,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548388,1,0
2548389,NaN,1.466352,NaN,control_casonly,NaN,no sgRNA,4145,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,control_casonly,10171.0,TTTGTGAGTTGTGACTATGTTGAC-1,CD4i_R1L21,False,0.304788,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548389,1,0
2548390,NaN,0.000000,NaN,control_casonly,NaN,no sgRNA,3504,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,control_casonly,9302.0,TTTGTGAGTTTAACCAAGTAGGCT-1,CD4i_R1L21,False,0.225758,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548390,1,0
2548391,25.0,1.492056,KIF18A-2,KIF18A,AGGCGGACATTAAAGTGAAG,targeting single sgRNA,2624,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,ENSG00000121621,4919.0,TTTGTGAGTTTCGCCTACTTTAGG-1,CD4i_R1L21,False,0.203293,targeting,ENSG00000121621,KIF18A,protein_coding,chr11:28020618-28108183;-1,11,2548391,1,11
2548392,42.0,2.538781,ZNF442-2,ZNF442,GCTGGCAGCGGGGAACCTTG,targeting single sgRNA,3231,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,ENSG00000198342,6540.0,TTTGTGAGTTTGTTGAAACGGGAA-1,CD4i_R1L21,False,0.030581,targeting,ENSG00000198342,ZNF442,protein_coding,chr19:12345944-12365905;-1,19,2548392,1,19

### Curate replicates

In [41]:
cur_data.adata.obs = cur_data.adata.obs.rename(columns={'lane_id':'technical_replicate'})

### Add metadata

In [43]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        "dataset_id": cur_data.dataset_id,
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        # perturbation type
        "perturbation_type_label": "CRISPRi",
        "perturbation_type_id": None,
        "data_modality": "Perturb-seq",
        "significant": None,
        "significance_criteria": None,
        "score_interpretation": None,

        # treatment
        "treatment_label": "untreated control",
        "treatment_id": "NCIT:C184729",
        # replicates
        # "technical_replicate": None,
        "biological_replicate": "D1_CE0008162",
        # model system
        "model_system_label": "primary_cell",
        "model_system_id": None,
        "tissue": "lymphoid tissue",
        "cell_line_label": None,
        "cell_line_id": None,
        "cell_type_label": "CD4-positive, alpha-beta T cell",
        "disease_label": "healthy",
        "disease_id": None,

        "timepoint": "P12DT8H0M0S",
        "species": "Homo sapiens",
        "sex_label": "female",
        "sex_id": None,
        "developmental_stage_label": "adult",
        "developmental_stage_id": None,

        "study_title": "Genome-scale perturb-seq in primary human CD4+ T cells maps context-specific regulators of T cell programs and human immune traits",
        "study_uri": "https://doi.org/10.64898/2025.12.23.696273",
        "study_year": 2025,
        "first_author": "Ronghui Zhu",
        "last_author": "Alexander Marson",

        "experiment_title": "Perturb-seq of primary human CD4-positive T cells for patient D1_CE0008162 under resting conditions",
        "experiment_summary": """
            Isolated human CD4-positive cells from four healthy donors were stimulated with ImmunoCult CD3/CD28/CD2 activator and sequentially transduced with dCas9-KRAB-Zim3 lentivirus (next morning after stimulation) and a Perturb-seq guide library (next afternoon after stimulation, MOI 0.2).
            The library consisted all genes expressed in human CD4+ T cells, all transcription factors annotated in the Lambert et al. (2018) and non-targeting controls totalling 12,748 genes.
            The gRNA sequences were selected from hCRISPRiv2 and Dolcetto libraries.
            On day 12, cells were split into three conditions:
            (1) Rest - cells were left for 8 hr without stimulation;
            (2) Stim8hr - cells were stimulated with ImmunoCult CD3/CD28/CD2 activator for 8 hr;
            (3) Stim48hr - cells were stimulated with ImmunoCult CD3/CD28/CD2 activator for 48 hr.
            Cells were harvested, fixed, stored using GEM-X Flex Sample Preparation v2 Kit and sequenced using GEM-X Flex Gene Expression Human n-plex kit converted into Ultima compatible libraries for sequencing on the Ultima Genomics UG100.
            """,

        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_symbol'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],

        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",

        "library_generation_method_id": None,
        "library_generation_method_label": "dCas9-KRAB-Zim3",

        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "lentivirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",

        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",

        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",

        "library_name": "custom",
        "library_uri": None,

        "library_format_id": None,
        "library_format_label": "pooled",

        "library_scope_id": None,
        "library_scope_label": "focused",

        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "inhibition",

        "library_manufacturer": "Marson lab",
        "library_lentiviral_generation": "2",
        "library_grnas_per_target": "2",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()),
        "library_total_variants": None,

        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",

        "readout_type_id": None,
        "readout_type_label": "transcriptomic",

        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",

        "method_name_id": None,
        "method_name_label": "Perturb-seq",

        "method_uri": None,

        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "GEM-X Flex Gene Expression Human n-plex kit",

        "sequencing_platform_id": None,
        "sequencing_platform_label": "Ultima Genomics UG100",

        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",

        "software_counts_id": None,
        "software_counts_label": "CellRanger",

        "software_analysis_id": None,
        "software_analysis_label": "scanpy",

        "reference_genome_id": None,
        "reference_genome_label": "GRCh38",

        "license_label": "MIT License",
        "license_id": "SWO:9000074",

        "associated_datasets": json.dumps([
            {
                "dataset_accession": "Primary Human CD4+ T Cell Perturb-seq",
                "dataset_uri": "s3://genome-scale-tcell-perturb-seq/marson2025_data/D1_Rest.assigned_guide.h5ad",
                "dataset_description": "Cell expression profiles for cells from donor D1_CE0008162 under resting conditions.",
                "dataset_file_name": "D1_Rest.assigned_guide.h5ad.h5ad",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column treatment_label added to adata.obs
Column treatment_id added to adata.obs
Column biological_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_line_id added to adata.obs
Column cell_type_label added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_manufacturer added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

In [44]:
cur_data.adata.obs

,top_guide_UMI_counts,PuroR,guide_id,perturbed_gene_name,guide_sequence,guide_group,n_genes_by_counts,perturbation_name,perturbed_gene_id,total_counts,cell_barcode,technical_replicate,low_quality,pct_counts_mt,guide_type,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding,dataset_id,sample_id,perturbation_type_label,perturbation_type_id,data_modality,significant,significance_criteria,score_interpretation,treatment_label,treatment_id,biological_replicate,model_system_label,model_system_id,tissue,cell_line_label,cell_line_id,cell_type_label,disease_label,disease_id,timepoint,species,sex_label,sex_id,developmental_stage_label,developmental_stage_id,study_title,study_uri,study_year,first_author,last_author,experiment_title,experiment_summary,number_of_perturbed_targets,number_of_perturbed_samples,library_generation_type_id,library_generation_type_label,library_generation_method_id,library_generation_method_label,enzyme_delivery_method_id,enzyme_delivery_method_label,library_delivery_method_id,library_delivery_method_label,enzyme_integration_state_id,enzyme_integration_state_label,library_integration_state_id,library_integration_state_label,enzyme_expression_control_id,enzyme_expression_control_label,library_expression_control_id,library_expression_control_label,library_name,library_uri,library_format_id,library_format_label,library_scope_id,library_scope_label,library_perturbation_type_id,library_perturbation_type_label,library_manufacturer,library_lentiviral_generation,library_grnas_per_target,library_total_grnas,library_total_variants,readout_dimensionality_id,readout_dimensionality_label,readout_type_id,readout_type_label,readout_technology_id,readout_technology_label,method_name_id,method_name_label,method_uri,sequencing_library_kit_id,sequencing_library_kit_label,sequencing_platform_id,sequencing_platform_label,sequencing_strategy_id,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,reference_genome_id,reference_genome_label,license_label,license_id,associated_datasets
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,NaN,2.100727,NaN,control_casonly,NaN,no sgRNA,1953,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,control_casonly,2969.0,AAACAAGCAAACCGGTATGTTGAC-1,CD4i_R1L08,False,0.269451,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,0,1,0,zhu_2025_D1_rest_cl,1,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
1,22.0,1.431987,NTC-461,control_nontargeting,TGGGAATTCCTCGGCCGATT,targeting single sgRNA,4576,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,control_nontargeting,13363.0,AAACAAGCAAATACCGATGTTGAC-1,CD4i_R1L08,False,1.017735,non-targeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,1,1,0,zhu_2025_D1_rest_cl,2,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2,9.0,1.209989,PLA2G10-2,PLA2G10,GGGTGCTGCAGGGCCACCGG,targeting single sgRNA,1890,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,ENSG00000069764,3016.0,AAACAAGCAAATCACGATGTTGAC-1,CD4i_R1L08,False,0.397878,targeting,ENSG00000069764,PLA2G10,protein_coding,chr16:14672548-14694308;-1,16,2,1,16,zhu_2025_D1_rest_cl,3,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
3,10.0,1.015303,ATXN7L3-1,ATXN7L3,GAGCGCGTGCATCTGCCCCG,targeting single sgRNA,5070,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,ENSG00000087152,16130.0,AAACAAGCAACAAAGAAACGGGAA-1,CD4i_R1L08,False,0.440174,targeting,ENSG00000087152,ATXN7L3,protein_coding,chr17:44191805-44200961;-1,17,3,1,17,zhu_2025_D1_rest_cl,4,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
4,102.0,2.463184,EVI5-1,EVI5,GGAGGAACCAGCTGGCCAGC,targeting single sgRNA,4881,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,ENSG00000067208,13876.0,AAACAAGCAACAAAGAACTTTAGG-1,CD4i_R1L08,False,0.317094,targeting,ENSG00000067208,EVI5,protein_coding,chr1:92508696-92792416;-1,1,4,1,1,zhu_2025_D1_rest_cl,5,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548388,NaN,1.451924,NaN,control_casonly,NaN,no sgRNA,2725,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,control_casonly,5182.0,TTTGTGAGTTGTGACTAACGGGAA-1,CD4i_R1L21,False,0.135083,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548388,1,0,zhu_2025_D1_rest_cl,2548389,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2548389,NaN,1.466352,NaN,control_casonly,NaN,no sgRNA,4145,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,control_casonly,10171.0,TTTGTGAGTTGTGACTATGTTGAC-1,CD4i_R1L21,False,0.304788,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548389,1,0,zhu_2025_D1_rest_cl,2548390,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2548390,NaN,0.000000,NaN,control_casonly,NaN,no sgRNA,3504,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,control_casonly,9302.0,TTTGTGAGTTTAACCAAGTAGGCT-1,CD4i_R1L21,False,0.225758,NaN,NaN,control_casonly,control_casonly,control_casonly,control_casonly,2548390,1,0,zhu_2025_D1_rest_cl,2548391,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2548391,25.0,1.492056,KIF18A-2,KIF18A,AGGCGGACATTAAAGTGAAG,targeting single sgRNA,2624,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,ENSG00000121621,4919.0,TTTGTGAGTTTCGCCTACTTTAGG-1,CD4i_R1L21,False,0.203293,targeting,ENSG00000121621,KIF18A,protein_coding,chr11:28020618-28108183;-1,11,2548391,1,11,zhu_2025_D1_rest_cl,2548392,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2548392,42.0,2.538781,ZNF442-2,ZNF442,GCTGGCAGCGGGGAACCTTG,targeting single sgRNA,3231,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,ENSG00000198342,6540.0,TTTGTGAGTTTGTTGAAACGGGAA-1,CD4i_R1L21,False,0.030581,targeting,ENSG00000198342,ZNF442,protein_coding,chr19:12345944-12365905;-1,19,2548392,1,19,zhu_2025_D1_rest_cl,2548393,CRISPRi,None,Perturb-seq,None,None,None,untreated control,NCIT:C184729,D1_CE0008162,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P12DT8H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,23255,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."

### Curate tissue information

In [45]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
      input_column input_column_lower       name_lower     ontology_id
0  lymphoid tissue    lymphoid tissue  lymphoid tissue  UBERON:0001744
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [46]:
cur_data.standardize_ontology(
    input_column='cell_type_label',
    column_type='term_name',
    ontology_type='cell_type',
    overwrite=True
)

Mapped 1 cell_type ontology terms from `cell_type_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
                      input_column               input_column_lower  \
0  CD4-positive, alpha-beta T cell  cd4-positive, alpha-beta t cell

                        name_lower ontology_id
0  cd4-positive, alpha-beta t cell  CL:0000624
--------------------------------------------------
Overwriting column cell_type_label in adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [47]:
cur_data.standardize_ontology(
    input_column='disease_label',
    column_type='term_name',
    ontology_type='disease',
    overwrite=True
)

Warning: No disease ontology terms could be mapped from `disease_label` column to ontology terms. Map the terms manually or check the input column for errors.

### Match schema column order

In [48]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [49]:
cur_data.validate_data(slot='obs', verbose=True)

2026-02-12 13:17:41,180 INFO curation_tools.curation_tools: adata.obs is valid according to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,guide_sequence,perturbation_type_label,perturbation_type_id,timepoint,treatment_label,treatment_id,technical_replicate,biological_replicate,model_system_label,model_system_id,species,tissue_label,tissue_id,cell_type_label,cell_type_id,cell_line_label,cell_line_id,sex_label,sex_id,developmental_stage_label,developmental_stage_id,disease_label,disease_id,study_title,study_uri,study_year,first_author,last_author,experiment_title,experiment_summary,number_of_perturbed_targets,number_of_perturbed_samples,library_generation_type_id,library_generation_type_label,library_generation_method_id,library_generation_method_label,enzyme_delivery_method_id,enzyme_delivery_method_label,library_delivery_method_id,library_delivery_method_label,enzyme_integration_state_id,enzyme_integration_state_label,library_integration_state_id,library_integration_state_label,enzyme_expression_control_id,enzyme_expression_control_label,library_expression_control_id,library_expression_control_label,library_name,library_uri,library_format_id,library_format_label,library_scope_id,library_scope_label,library_perturbation_type_id,library_perturbation_type_label,library_manufacturer,library_lentiviral_generation,library_grnas_per_target,library_total_grnas,library_total_variants,readout_dimensionality_id,readout_dimensionality_label,readout_type_id,readout_type_label,readout_technology_id,readout_technology_label,method_name_id,method_name_label,method_uri,sequencing_library_kit_id,sequencing_library_kit_label,sequencing_platform_id,sequencing_platform_label,sequencing_strategy_id,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,zhu_2025_D1_rest_cl,1,Perturb-seq,<NA>,<NA>,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,control_casonly,control_casonly,0,1,<NA>,control_casonly,control_casonly,<NA>,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
1,zhu_2025_D1_rest_cl,2,Perturb-seq,<NA>,<NA>,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,control_nontargeting,control_nontargeting,0,1,control_nontargeting,control_nontargeting,control_nontargeting,TGGGAATTCCTCGGCCGATT,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2,zhu_2025_D1_rest_cl,3,Perturb-seq,<NA>,<NA>,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,chr16:14672548-14694308;-1,16,16,1,ENSG00000069764,PLA2G10,protein_coding,GGGTGCTGCAGGGCCACCGG,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
3,zhu_2025_D1_rest_cl,4,Perturb-seq,<NA>,<NA>,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,chr17:44191805-44200961;-1,17,17,1,ENSG00000087152,ATXN7L3,protein_coding,GAGCGCGTGCATCTGCCCCG,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
4,zhu_2025_D1_rest_cl,5,Perturb-seq,<NA>,<NA>,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,chr1:92508696-92792416;-1,1,1,1,ENSG00000067208,EVI5,protein_coding,GGAGGAACCAGCTGGCCAGC,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548388,zhu_2025_D1_rest_cl,2548389,Perturb-seq,<NA>,<NA>,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,control_casonly,control_casonly,0,1,<NA>,control_casonly,control_casonly,<NA>,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548389,zhu_2025_D1_rest_cl,2548390,Perturb-seq,<NA>,<NA>,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,control_casonly,control_casonly,0,1,<NA>,control_casonly,control_casonly,<NA>,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548390,zhu_2025_D1_rest_cl,2548391,Perturb-seq,<NA>,<NA>,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,control_casonly,control_casonly,0,1,<NA>,control_casonly,control_casonly,<NA>,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548391,zhu_2025_D1_rest_cl,2548392,Perturb-seq,<NA>,<NA>,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,chr11:28020618-28108183;-1,11,11,1,ENSG00000121621,KIF18A,protein_coding,AGGCGGACATTAAAGTGAAG,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548392,zhu_2025_D1_rest_cl,2548393,Perturb-seq,<NA>,<NA>,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,chr19:12345944-12365905;-1,19,19,1,ENSG00000198342,ZNF442,protein_coding,GCTGGCAGCGGGGAACCTTG,CRISPRi,<NA>,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,23255,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074

# VAR slot curation

### Standardise genes

In [55]:
cur_data.adata.var

,feature_types,mt,genome,gene_ids,gene_name,ensembl_gene_id,gene_symbol,original_index
index,,,,,,,,
0,Gene Expression,False,GRCh38,ENSG00000000003,TSPAN6,ENSG00000000003,TSPAN6,ENSG00000000003
1,Gene Expression,False,GRCh38,ENSG00000000005,TNMD,ENSG00000000005,TNMD,ENSG00000000005
2,Gene Expression,False,GRCh38,ENSG00000000419,DPM1,ENSG00000000419,DPM1,ENSG00000000419
3,Gene Expression,False,GRCh38,ENSG00000000457,SCYL3,ENSG00000000457,SCYL3,ENSG00000000457
4,Gene Expression,False,GRCh38,ENSG00000000460,C1orf112,ENSG00000000460,FIRRM,ENSG00000000460
...,...,...,...,...,...,...,...,...
18125,Gene Expression,False,GRCh38,ENSG00000291122,CASTOR3P,ENSG00000291122,CASTOR3P,ENSG00000291122
18126,Gene Expression,False,GRCh38,ENSG00000291135,FCGR1BP,ENSG00000291135,FCGR1BP,ENSG00000291135
18127,Gene Expression,False,GRCh38,ENSG00000291145,PPP5D1P,ENSG00000291145,PPP5D1P,ENSG00000291145
18128,Gene Expression,False,GRCh38,ENSG00000291237,SOD2,ENSG00000291237,SOD2,ENSG00000291237
18129,Gene Expression,False,GRCh38,CUSTOM001_PuroR,PuroR,NaN,PuroR,CUSTOM001_PuroR

In [51]:
cur_data.standardize_genes(
    slot="var",
    input_column="gene_ids",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

Missing Ensembl IDs: ['ENSG00000148362', 'ENSG00000139656', 'CUSTOM001_PuroR']; attempting to fetch latest IDs...
Fetched latest Ensembl IDs: {'ENSG00000148362': 'ENSG00000310560', 'ENSG00000139656': 'ENSG00000226519'}
--------------------------------------------------
Successfully mapped 18130 out of 18130 Ensembl IDs.
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [52]:
# replace gene symbols that are NOT ENSG with original provided gene symbol
cur_data.adata.var.loc[(cur_data.adata.var['gene_symbol'].isna()) &
 (~cur_data.adata.var['gene_name'].str.startswith('ENSG')), 'gene_symbol'] = cur_data.adata.var.loc[(cur_data.adata.var['gene_symbol'].isna()) &
 (~cur_data.adata.var['gene_name'].str.startswith('ENSG')), 'gene_name']

In [54]:
cur_data.adata.var.loc[cur_data.adata.var['ensembl_gene_id'] == 'CUSTOM001_PuroR', 'ensembl_gene_id'] = None

### Validate var metadata

In [56]:
cur_data.validate_data(slot='var')

2026-02-12 13:24:29,161 INFO curation_tools.curation_tools: adata.var is valid according to the var_schema.

       ensembl_gene_id gene_symbol
index
0      ENSG00000000003      TSPAN6
1      ENSG00000000005        TNMD
2      ENSG00000000419        DPM1
3      ENSG00000000457       SCYL3
4      ENSG00000000460       FIRRM
...                ...         ...
18125  ENSG00000291122    CASTOR3P
18126  ENSG00000291135     FCGR1BP
18127  ENSG00000291145     PPP5D1P
18128  ENSG00000291237        SOD2
18129              NaN       PuroR

[18130 rows x 2 columns]

# Save the dataset

In [62]:
# Use 'object' to force standard Python strings (NumPy compatible)
cur_data.adata.obs.index = cur_data.adata.obs.index.astype("object")

# It is safer to do the same for the var index just in case
cur_data.adata.var.index = cur_data.adata.var.index.astype("object")

In [76]:
import pandas as pd
import numpy as np

def convert_arrow_to_object(df):
    """
    Recursively converts all Arrow-backed string columns and categories 
    in a DataFrame to standard Python objects (numpy-compatible).
    """
    # 1. Fix Index
    if "arrow" in str(df.index.dtype).lower() or isinstance(df.index.dtype, pd.StringDtype):
        df.index = df.index.astype("object")
        
    for col in df.columns:
        col_dtype = df[col].dtype
        
        # 2. Fix Categorical Columns
        if isinstance(col_dtype, pd.CategoricalDtype):
            if "arrow" in str(col_dtype.categories.dtype).lower() or \
               isinstance(col_dtype.categories.dtype, pd.StringDtype):
                # Convert categories to object
                new_categories = df[col].cat.categories.astype("object")
                df[col] = df[col].cat.rename_categories(new_categories)
        
        # 3. Fix Standard String/Arrow Columns (e.g., sample_id)
        elif "arrow" in str(col_dtype).lower() or isinstance(col_dtype, pd.StringDtype):
            df[col] = df[col].astype("object")

# --- Apply the fix ---

print("Cleaning obs...")
convert_arrow_to_object(cur_data.adata.obs)

print("Cleaning var...")
convert_arrow_to_object(cur_data.adata.var)

Cleaning obs...
Cleaning var...

In [85]:
import pandas as pd
import numpy as np

def clean_adata_for_saving(adata):
    # 1. Fix Index
    adata.obs.index = adata.obs.index.astype("object")
    adata.var.index = adata.var.index.astype("object")
    
    for df in [adata.obs, adata.var]:
        for col in df.columns:
            # --- Fix 1: Convert Arrow/StringDtype to Object ---
            if "arrow" in str(df[col].dtype).lower() or isinstance(df[col].dtype, pd.StringDtype):
                df[col] = df[col].astype("object")
            
            # --- Fix 2: Handle Object columns with NaNs ---
            # If a column is object type and has NaNs, it will break h5py.
            # We convert these to 'category', which handles NaNs gracefully.
            if df[col].dtype == "object":
                if df[col].isnull().any():
                    print(f"Converting mixed-type column '{col}' to categorical...")
                    df[col] = df[col].astype("category")

            # --- Fix 3: Ensure Categories are Standard Objects ---
            # If we created a categorical, ensure its internal list of categories is not Arrow
            if isinstance(df[col].dtype, pd.CategoricalDtype):
                if df[col].cat.categories.dtype != "object":
                    new_cats = df[col].cat.categories.astype("object")
                    df[col] = df[col].cat.rename_categories(new_cats)

# Apply the comprehensive fix
clean_adata_for_saving(cur_data.adata)

Converting mixed-type column 'significant' to categorical...

In [86]:
cur_data.adata.obs['dataset_id'].dtype

CategoricalDtype(categories=['zhu_2025_D1_rest_cl'], ordered=False, categories_dtype=object)

In [87]:
cur_data.adata.obs['significant'].dtype

CategoricalDtype(categories=[], ordered=False, categories_dtype=object)

In [88]:
cur_data.adata.obs['significant']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
2548388    NaN
2548389    NaN
2548390    NaN
2548391    NaN
2548392    NaN
Name: significant, Length: 2548393, dtype: category
Categories (0, object): []

In [89]:
cur_data.adata.obs

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,guide_sequence,perturbation_type_label,perturbation_type_id,timepoint,treatment_label,treatment_id,technical_replicate,biological_replicate,model_system_label,model_system_id,species,tissue_label,tissue_id,cell_type_label,cell_type_id,cell_line_label,cell_line_id,sex_label,sex_id,developmental_stage_label,developmental_stage_id,disease_label,disease_id,study_title,study_uri,study_year,first_author,last_author,experiment_title,experiment_summary,number_of_perturbed_targets,number_of_perturbed_samples,library_generation_type_id,library_generation_type_label,library_generation_method_id,library_generation_method_label,enzyme_delivery_method_id,enzyme_delivery_method_label,library_delivery_method_id,library_delivery_method_label,enzyme_integration_state_id,enzyme_integration_state_label,library_integration_state_id,library_integration_state_label,enzyme_expression_control_id,enzyme_expression_control_label,library_expression_control_id,library_expression_control_label,library_name,library_uri,library_format_id,library_format_label,library_scope_id,library_scope_label,library_perturbation_type_id,library_perturbation_type_label,library_manufacturer,library_lentiviral_generation,library_grnas_per_target,library_total_grnas,library_total_variants,readout_dimensionality_id,readout_dimensionality_label,readout_type_id,readout_type_label,readout_technology_id,readout_technology_label,method_name_id,method_name_label,method_uri,sequencing_library_kit_id,sequencing_library_kit_label,sequencing_platform_id,sequencing_platform_label,sequencing_strategy_id,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,zhu_2025_D1_rest_cl,1,Perturb-seq,NaN,NaN,AAACAAGCAAACCGGTATGTTGAC-1_CD4i_R1L08,control_casonly,control_casonly,0,1,NaN,control_casonly,control_casonly,NaN,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
1,zhu_2025_D1_rest_cl,2,Perturb-seq,NaN,NaN,AAACAAGCAAATACCGATGTTGAC-1_CD4i_R1L08,control_nontargeting,control_nontargeting,0,1,control_nontargeting,control_nontargeting,control_nontargeting,TGGGAATTCCTCGGCCGATT,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2,zhu_2025_D1_rest_cl,3,Perturb-seq,NaN,NaN,AAACAAGCAAATCACGATGTTGAC-1_CD4i_R1L08,chr16:14672548-14694308;-1,16,16,1,ENSG00000069764,PLA2G10,protein_coding,GGGTGCTGCAGGGCCACCGG,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
3,zhu_2025_D1_rest_cl,4,Perturb-seq,NaN,NaN,AAACAAGCAACAAAGAAACGGGAA-1_CD4i_R1L08,chr17:44191805-44200961;-1,17,17,1,ENSG00000087152,ATXN7L3,protein_coding,GAGCGCGTGCATCTGCCCCG,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
4,zhu_2025_D1_rest_cl,5,Perturb-seq,NaN,NaN,AAACAAGCAACAAAGAACTTTAGG-1_CD4i_R1L08,chr1:92508696-92792416;-1,1,1,1,ENSG00000067208,EVI5,protein_coding,GGAGGAACCAGCTGGCCAGC,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L08,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548388,zhu_2025_D1_rest_cl,2548389,Perturb-seq,NaN,NaN,TTTGTGAGTTGTGACTAACGGGAA-1_CD4i_R1L21,control_casonly,control_casonly,0,1,NaN,control_casonly,control_casonly,NaN,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548389,zhu_2025_D1_rest_cl,2548390,Perturb-seq,NaN,NaN,TTTGTGAGTTGTGACTATGTTGAC-1_CD4i_R1L21,control_casonly,control_casonly,0,1,NaN,control_casonly,control_casonly,NaN,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548390,zhu_2025_D1_rest_cl,2548391,Perturb-seq,NaN,NaN,TTTGTGAGTTTAACCAAGTAGGCT-1_CD4i_R1L21,control_casonly,control_casonly,0,1,NaN,control_casonly,control_casonly,NaN,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548391,zhu_2025_D1_rest_cl,2548392,Perturb-seq,NaN,NaN,TTTGTGAGTTTCGCCTACTTTAGG-1_CD4i_R1L21,chr11:28020618-28108183;-1,11,11,1,ENSG00000121621,KIF18A,protein_coding,AGGCGGACATTAAAGTGAAG,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2548392,zhu_2025_D1_rest_cl,2548393,Perturb-seq,NaN,NaN,TTTGTGAGTTTGTTGAAACGGGAA-1_CD4i_R1L21,chr19:12345944-12365905;-1,19,19,1,ENSG00000198342,ZNF442,protein_coding,GCTGGCAGCGGGGAACCTTG,CRISPRi,NaN,P12DT8H0M0S,untreated control,NCIT:C184729,CD4i_R1L21,D1_CE0008162,primary_cell,NaN,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,NaN,NaN,female,NaN,adult,NaN,healthy,NaN,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,12101,2548393,EFO:0022868,endogenous,NaN,dCas9-KRAB-Zim3,NaN,lentivirus transduction,NaN,lentivirus transduction,NaN,random locus integration,NaN,random locus integration,NaN,constitutive transgene expression,NaN,constitutive transgene expression,custom,NaN,NaN,pooled,NaN,focused,NaN,inhibition,Marson lab,2,2,23255,<NA>,NaN,high-dimensional assay,NaN,transcriptomic,NaN,single-cell rna-seq,NaN,Perturb-seq,NaN,NaN,GEM-X Flex Gene Expression Human n-plex kit,NaN,Ultima Genomics UG100,NaN,barcode sequencing,NaN,CellRanger,NaN,scanpy,NaN,NaN,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074

In [90]:
cur_data.save_curated_data_h5ad()

✅ Curated h5ad data saved to ../curated/h5ad/zhu_2025_D1_rest_cl_curated.h5ad

In [91]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/zhu_2025_D1_rest_cl_curated_metadata.parquet

# Upload to BigQuery

In [95]:
# upload_parquet_to_bq(
#     parquet_path='../curated/parquet/zhu_2025_D1_rest_cl_curated_metadata.parquet',
#     bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
#     bq_table_name='metadata',
#     key_columns=['dataset_id', 'sample_id'],
#     verbose=True
# )

# Upload to GC Storage

In [94]:
!gcloud storage cp ../curated/h5ad/zhu_2025_D1_rest_cl_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/

/bin/sh: line 1: gcloud: command not found