# Import

In [2]:
import pandas as pd
import json

from curation_tools.curation_tools import (
    CuratedDataset,
    ObsSchema,
    VarSchema,
    Experiment,
    download_file,
    upload_parquet_to_bq
)

import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("curation.log"),
        logging.StreamHandler(),  # keep console output too
    ],
    force=True,
)
# show all columns
pd.set_option('display.max_columns', None)

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/.venv/lib/python3.12/site-packages/pandera/_pandas_deprecated.py:157: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

# Download data

Download the data from AWS as such:

`!aws s3 cp --no-sign-request s3://genome-scale-tcell-perturb-seq/marson2025_data/{name_of_the_file}.h5ad ..aa/non_curated/h5ad/{name_of_the_file}.h5ad`

# Initialise the dataset object

In [3]:
noncurated_path = '../non_curated/h5ad/zhu_2025_D3_stim48hr_cl.h5ad'
cur_data = CuratedDataset(
    obs_schema=ObsSchema,
    var_schema=VarSchema,
    exp_metadata_schema=Experiment,
    noncurated_path=noncurated_path
)

cur_data.load_data()

Loading data from ../non_curated/h5ad/zhu_2025_D3_stim48hr_cl.h5ad

In [4]:
cur_data.adata.obs

,lane_id,n_genes_by_counts,total_counts,pct_counts_mt,top_guide_UMI_counts,guide_id,perturbed_gene_name,perturbed_gene_id,guide_type,PuroR,guide_group,low_quality
AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L32,5101,12866.0,1.375719,NaN,NaN,NaN,NaN,NaN,3.134436,no sgRNA,False
AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L32,5994,23121.0,0.047576,297.0,ALX3-2,ALX3,ENSG00000156150,targeting,3.277925,targeting single sgRNA,False
AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L32,3575,7659.0,0.287244,21.0,FAM210B-1,FAM210B,ENSG00000124098,targeting,3.827360,targeting single sgRNA,False
AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L32,2795,5204.0,0.153728,155.0,NTC-846,NTC,NTC,non-targeting,1.744745,targeting single sgRNA,False
AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L32,6745,30883.0,0.777127,931.0,GATA1-1,GATA1,ENSG00000102145,targeting,3.230057,targeting single sgRNA,False
...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L48,3075,7043.0,0.070992,528.0,IFRD1-2,IFRD1,ENSG00000006652,targeting,2.604208,targeting single sgRNA,False
TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L48,3497,7250.0,0.358621,75.0,GALNT1-1,GALNT1,ENSG00000141429,targeting,1.620248,targeting single sgRNA,False
TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L48,3687,7890.0,0.088720,47.0,CTSK-1,CTSK,ENSG00000143387,targeting,2.911565,targeting single sgRNA,False
TTTGTGAGTTTCCTCAACTACTCA-1_CD4i_R2L48_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L48,6563,30182.0,0.566563,428.0,multi_sgRNA,NaN,NaN,targeting,2.565821,multi sgRNA,False
TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48_CD4i_R2_D3_Stim48hr_CD4i_R2_Ultima,CD4i_R2L48,5306,15622.0,0.307259,120.0,LIN28B-1,LIN28B,ENSG00000187772,targeting,3.133394,targeting single sgRNA,False

In [5]:
cur_data.adata.var

                        gene_ids    feature_types  genome gene_name     mt
CUSTOM001_PuroR  CUSTOM001_PuroR  Gene Expression  GRCh38     PuroR  False
ENSG00000000003  ENSG00000000003  Gene Expression  GRCh38    TSPAN6  False
ENSG00000000005  ENSG00000000005  Gene Expression  GRCh38      TNMD  False
ENSG00000000419  ENSG00000000419  Gene Expression  GRCh38      DPM1  False
ENSG00000000457  ENSG00000000457  Gene Expression  GRCh38     SCYL3  False
...                          ...              ...     ...       ...    ...
ENSG00000291110  ENSG00000291110  Gene Expression  GRCh38   TRIM16L  False
ENSG00000291122  ENSG00000291122  Gene Expression  GRCh38  CASTOR3P  False
ENSG00000291135  ENSG00000291135  Gene Expression  GRCh38   FCGR1BP  False
ENSG00000291145  ENSG00000291145  Gene Expression  GRCh38   PPP5D1P  False
ENSG00000291237  ENSG00000291237  Gene Expression  GRCh38      SOD2  False

[18130 rows x 5 columns]

# OBS slot curation

### Since for multi-guide perturbations the identities of said guides are unknown, we are filtering out these cells.

In [6]:
print(f"Number of cells before filtering: {cur_data.adata.n_obs}")
cur_data.adata = cur_data.adata[cur_data.adata.obs['guide_id'] != 'multi_sgRNA']
print(f"Number of cells after filtering: {cur_data.adata.n_obs}")

Number of cells before filtering: 2607532
Number of cells after filtering: 2160401

### Add `index` as `perturbation_name`

In [7]:
cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.str.split('_').str[0]
cur_data.adata.obs['perturbation_name'] = cur_data.adata.obs['cell_barcode'] +'_'+cur_data.adata.obs['lane_id'].astype(str)

/tmp/ipykernel_124898/2231587657.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  cur_data.adata.obs['cell_barcode'] = cur_data.adata.obs.index.str.split('_').str[0]

### Show unique perturbations

In [8]:
cur_data.show_unique(slot = 'obs', column = 'perturbation_name')

Unique values in adata.obs.perturbation_name: 2160401
--------------------------------------------------
{'AAACAAGCAAACAAGAACTACTCA-1_CD4i_R2L29',
 'AAACAAGCAAACAAGAACTACTCA-1_CD4i_R2L46',
 'AAACAAGCAAACAAGAAGAGGCAA-1_CD4i_R2L43',
 'AAACAAGCAAACAATCACTACTCA-1_CD4i_R2L37',
 'AAACAAGCAAACAATCAGAGGCAA-1_CD4i_R2L30',
 'AAACAAGCAAACAATCAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCAAACAATCAGTGAGTG-1_CD4i_R2L30',
 'AAACAAGCAAACACGCACTACTCA-1_CD4i_R2L33',
 'AAACAAGCAAACACGCAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCAAACACGCAGTGAGTG-1_CD4i_R2L28',
 'AAACAAGCAAACACGCAGTGAGTG-1_CD4i_R2L35',
 'AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32',
 'AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L41',
 'AAACAAGCAAACCCAAAGAGGCAA-1_CD4i_R2L27',
 'AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L27',
 'AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32',
 'AAACAAGCAAACCGGTACTACTCA-1_CD4i_R2L29',
 'AAACAAGCAAACCGGTAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCAAACCGTAAGAGGCAA-1_CD4i_R2L34',
 'AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32',
 'AAACAAGCAAACCTGAAGAGGCAA-1_CD4i_R2L48',
 'AAACAAGCAAACGGGAACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAAACGGTCACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAAACGGTCAGTGAGTG-1_CD4i_R2L31',
 'AAACAAGCAAACGGTCAGTGAGTG-1_CD4i_R2L48',
 'AAACAAGCAAACTGGCACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAAACTGGCAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCAAACTGGCAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCAAACTTCCACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAAACTTCCACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAAACTTCCACTACTCA-1_CD4i_R2L29',
 'AAACAAGCAAACTTCCAGAGGCAA-1_CD4i_R2L31',
 'AAACAAGCAAACTTCCAGAGGCAA-1_CD4i_R2L35',
 'AAACAAGCAAACTTGGACAGTCTG-1_CD4i_R2L42',
 'AAACAAGCAAACTTGGACTACTCA-1_CD4i_R2L39',
 'AAACAAGCAAACTTGGAGAGGCAA-1_CD4i_R2L39',
 'AAACAAGCAAACTTGGAGTGAGTG-1_CD4i_R2L34',
 'AAACAAGCAAACTTGGAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCAAAGAACAACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAAAGAACAACAGTCTG-1_CD4i_R2L42',
 'AAACAAGCAAAGAACAACAGTCTG-1_CD4i_R2L44',
 'AAACAAGCAAAGAACAAGTGAGTG-1_CD4i_R2L44',
 'AAACAAGCAAAGACCCACTACTCA-1_CD4i_R2L30',
 'AAACAAGCAAAGACCCAGAGGCAA-1_CD4i_R2L42',
 'AAACAAGCAAAGACCCAGTGAGTG-1_CD4i_R2L44',
 'AAACAAGCAAAGCCTAACTACTCA-1_CD4i_R2L47',
 'AAACAAGCAAAGGGATACAGTCTG-1_CD4i_R2L43',
 'AAACAAGCAAAGGGATACTACTCA-1_CD4i_R2L43',
 'AAACAAGCAAAGGTAAACAGTCTG-1_CD4i_R2L40',
 'AAACAAGCAAAGGTAAAGAGGCAA-1_CD4i_R2L35',
 'AAACAAGCAAAGTGCCACAGTCTG-1_CD4i_R2L44',
 'AAACAAGCAAAGTGCCAGAGGCAA-1_CD4i_R2L29',
 'AAACAAGCAAAGTGCCAGAGGCAA-1_CD4i_R2L46',
 'AAACAAGCAAAGTGCCAGTGAGTG-1_CD4i_R2L35',
 'AAACAAGCAAATAACCACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCAAATAAGGACAGTCTG-1_CD4i_R2L27',
 'AAACAAGCAAATAAGGACAGTCTG-1_CD4i_R2L30',
 'AAACAAGCAAATAAGGACTACTCA-1_CD4i_R2L27',
 'AAACAAGCAAATAAGGACTACTCA-1_CD4i_R2L28',
 'AAACAAGCAAATAAGGAGAGGCAA-1_CD4i_R2L27',
 'AAACAAGCAAATAAGGAGAGGCAA-1_CD4i_R2L34',
 'AAACAAGCAAATAAGGAGAGGCAA-1_CD4i_R2L42',
 'AAACAAGCAAATAAGGAGTGAGTG-1_CD4i_R2L33',
 'AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32',
 'AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCAAATAGGAACTACTCA-1_CD4i_R2L30',
 'AAACAAGCAAATAGGAACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAAATAGGAAGAGGCAA-1_CD4i_R2L30',
 'AAACAAGCAAATAGGAAGAGGCAA-1_CD4i_R2L39',
 'AAACAAGCAAATATGCAGAGGCAA-1_CD4i_R2L48',
 'AAACAAGCAAATCACGACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAAATCACGACAGTCTG-1_CD4i_R2L41',
 'AAACAAGCAAATCACGAGAGGCAA-1_CD4i_R2L29',
 'AAACAAGCAAATCACGAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCAAATGACTACTACTCA-1_CD4i_R2L29',
 'AAACAAGCAAATGACTACTACTCA-1_CD4i_R2L42',
 'AAACAAGCAACAAGCCACAGTCTG-1_CD4i_R2L33',
 'AAACAAGCAACAAGCCACAGTCTG-1_CD4i_R2L45',
 'AAACAAGCAACAAGCCACTACTCA-1_CD4i_R2L28',
 'AAACAAGCAACAAGTTACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAACAAGTTACTACTCA-1_CD4i_R2L38',
 'AAACAAGCAACAAGTTAGTGAGTG-1_CD4i_R2L38',
 'AAACAAGCAACAAGTTAGTGAGTG-1_CD4i_R2L40',
 'AAACAAGCAACAGAGGACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCAACAGAGGACTACTCA-1_CD4i_R2L27',
 'AAACAAGCAACAGAGGACTACTCA-1_CD4i_R2L29',
 'AAACAAGCAACAGAGGAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCAACAGCACACAGTCTG-1_CD4i_R2L25',
 'AAACAAGCAACAGCACACAGTCTG-1_CD4i_R2L30',
 'AAACAAGCAACAGCACACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAACAGCACACTACTCA-1_CD4i_R2L45',
 'AAACAAGCAACAGCACAGAGGCAA-1_CD4i_R2L45',
 'AAACAAGCAACAGCACAGTGAGTG-1_CD4i_R2L43',
 'AAACAAGCAACAGCACAGTGAGTG-1_CD4i_R2L45',
 'AAACAAGCAACAGCTAAGAGGCAA-1_CD4i_R2L34',
 'AAACAAGCAACAGCTAAGTGAGTG-1_CD4i_R2L28',
 'AAACAAGCAACAGGCTACAGTCTG-1_CD4i_R2L31',
 'AAACAAGCAACAGGCTACAGTCTG-1_CD4i_R2L37',
 'AAACAAGCAACAGGCTACAGTCTG-1_CD4i_R2L41',
 'AAACAAGCAACAGGCTACAGTCTG-1_CD4i_R2L45',
 'AAACAAGCAACAGGCTACTACTCA-1_CD4i_R2L31',
 'AAACAAGCAACAGGCTAGAGGCAA-1_CD4i_R2L31',
 'AAACAAGCAACAGGCTAGAGGCAA-1_CD4i_R2L45',
 'AAACAAGCAACAGGCTAGTGAGTG-1_CD4i_R2L34',
 'AAACAAGCAACAGGGAAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAACATAGTACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCAACATAGTACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCAACATAGTACTACTCA-1_CD4i_R2L48',
 'AAACAAGCAACATAGTAGAGGCAA-1_CD4i_R2L36',
 'AAACAAGCAACATAGTAGAGGCAA-1_CD4i_R2L48',
 'AAACAAGCAACATAGTAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCAACATGATAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCAACCATTCACAGTCTG-1_CD4i_R2L31',
 'AAACAAGCAACCATTCACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAACCATTCACTACTCA-1_CD4i_R2L35',
 'AAACAAGCAACCATTCAGTGAGTG-1_CD4i_R2L28',
 'AAACAAGCAACCCTATACAGTCTG-1_CD4i_R2L43',
 'AAACAAGCAACCCTATACTACTCA-1_CD4i_R2L34',
 'AAACAAGCAACCCTATACTACTCA-1_CD4i_R2L43',
 'AAACAAGCAACCCTATAGAGGCAA-1_CD4i_R2L34',
 'AAACAAGCAACCCTATAGAGGCAA-1_CD4i_R2L39',
 'AAACAAGCAACCGGATACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAACCGGATACTACTCA-1_CD4i_R2L33',
 'AAACAAGCAACCGGATAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32',
 'AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L46',
 'AAACAAGCAACCGTAAAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCAACCGTGGACTACTCA-1_CD4i_R2L33',
 'AAACAAGCAACCGTGGAGTGAGTG-1_CD4i_R2L29',
 'AAACAAGCAACCTCGCACAGTCTG-1_CD4i_R2L33',
 'AAACAAGCAACCTGTTACAGTCTG-1_CD4i_R2L32',
 'AAACAAGCAACCTTGTACAGTCTG-1_CD4i_R2L34',
 'AAACAAGCAACCTTGTAGTGAGTG-1_CD4i_R2L41',
 'AAACAAGCAACGACTAACTACTCA-1_CD4i_R2L28',
 'AAACAAGCAACGACTAACTACTCA-1_CD4i_R2L45',
 'AAACAAGCAACTAAACACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAACTAAACACTACTCA-1_CD4i_R2L35',
 'AAACAAGCAACTAAACACTACTCA-1_CD4i_R2L38',
 'AAACAAGCAACTAGTGACAGTCTG-1_CD4i_R2L38',
 'AAACAAGCAACTAGTGAGAGGCAA-1_CD4i_R2L44',
 'AAACAAGCAACTAGTGAGTGAGTG-1_CD4i_R2L28',
 'AAACAAGCAACTATCCAGTGAGTG-1_CD4i_R2L28',
 'AAACAAGCAACTGTTCACAGTCTG-1_CD4i_R2L37',
 'AAACAAGCAACTGTTCACAGTCTG-1_CD4i_R2L44',
 'AAACAAGCAACTGTTCACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAACTGTTCAGAGGCAA-1_CD4i_R2L27',
 'AAACAAGCAACTGTTCAGTGAGTG-1_CD4i_R2L48',
 'AAACAAGCAACTTAGGACAGTCTG-1_CD4i_R2L29',
 'AAACAAGCAACTTAGGACAGTCTG-1_CD4i_R2L44',
 'AAACAAGCAACTTAGGACTACTCA-1_CD4i_R2L29',
 'AAACAAGCAACTTCGTACAGTCTG-1_CD4i_R2L41',
 'AAACAAGCAAGAAATGAGAGGCAA-1_CD4i_R2L30',
 'AAACAAGCAAGAAATGAGAGGCAA-1_CD4i_R2L41',
 'AAACAAGCAAGAAATGAGTGAGTG-1_CD4i_R2L32',
 'AAACAAGCAAGAACAAACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAAGAACAAACTACTCA-1_CD4i_R2L32',
 'AAACAAGCAAGAACAAAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCAAGACATTACTACTCA-1_CD4i_R2L46',
 'AAACAAGCAAGACATTAGTGAGTG-1_CD4i_R2L36',
 'AAACAAGCAAGATAAGACTACTCA-1_CD4i_R2L34',
 'AAACAAGCAAGATAAGAGTGAGTG-1_CD4i_R2L33',
 'AAACAAGCAAGATGCCACTACTCA-1_CD4i_R2L42',
 'AAACAAGCAAGATGCCAGAGGCAA-1_CD4i_R2L31',
 'AAACAAGCAAGATGCCAGAGGCAA-1_CD4i_R2L40',
 'AAACAAGCAAGATGCCAGTGAGTG-1_CD4i_R2L38',
 'AAACAAGCAAGATGCCAGTGAGTG-1_CD4i_R2L40',
 'AAACAAGCAAGATGCCAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCAAGATGCCAGTGAGTG-1_CD4i_R2L48',
 'AAACAAGCAAGCCACGACAGTCTG-1_CD4i_R2L37',
 'AAACAAGCAAGCCACGACAGTCTG-1_CD4i_R2L44',
 'AAACAAGCAAGCCACGAGAGGCAA-1_CD4i_R2L28',
 'AAACAAGCAAGCCACGAGAGGCAA-1_CD4i_R2L37',
 'AAACAAGCAAGCCACGAGTGAGTG-1_CD4i_R2L31',
 'AAACAAGCAAGCCACGAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCAAGCCTAAACTACTCA-1_CD4i_R2L35',
 'AAACAAGCAAGCCTAAAGAGGCAA-1_CD4i_R2L43',
 'AAACAAGCAAGCCTAAAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCAAGCCTCCACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCAAGCCTCCACAGTCTG-1_CD4i_R2L40',
 'AAACAAGCAAGCCTCCACAGTCTG-1_CD4i_R2L42',
 'AAACAAGCAAGCGAAGAGTGAGTG-1_CD4i_R2L29',
 'AAACAAGCAAGCGAAGAGTGAGTG-1_CD4i_R2L35',
 'AAACAAGCAAGCGATCACAGTCTG-1_CD4i_R2L27',
 'AAACAAGCAAGCGATCACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAAGCGATCACTACTCA-1_CD4i_R2L39',
 'AAACAAGCAAGCGATCAGAGGCAA-1_CD4i_R2L41',
 'AAACAAGCAAGCGATCAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAAGCTAATACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCAAGCTAATACTACTCA-1_CD4i_R2L37',
 'AAACAAGCAAGCTAATAGAGGCAA-1_CD4i_R2L25',
 'AAACAAGCAAGCTAATAGAGGCAA-1_CD4i_R2L48',
 'AAACAAGCAAGCTATGACAGTCTG-1_CD4i_R2L26',
 'AAACAAGCAAGCTATGACTACTCA-1_CD4i_R2L30',
 'AAACAAGCAAGCTATGAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAAGCTATGAGTGAGTG-1_CD4i_R2L30',
 'AAACAAGCAAGCTCAAACAGTCTG-1_CD4i_R2L27',
 'AAACAAGCAAGCTCAAACAGTCTG-1_CD4i_R2L34',
 'AAACAAGCAAGCTCAAACTACTCA-1_CD4i_R2L34',
 'AAACAAGCAAGCTCAAAGAGGCAA-1_CD4i_R2L27',
 'AAACAAGCAAGCTCAAAGAGGCAA-1_CD4i_R2L32',
 'AAACAAGCAAGCTCAAAGTGAGTG-1_CD4i_R2L27',
 'AAACAAGCAAGCTCAAAGTGAGTG-1_CD4i_R2L32',
 'AAACAAGCAAGCTCAAAGTGAGTG-1_CD4i_R2L34',
 'AAACAAGCAAGCTTTCACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAAGGAATAACAGTCTG-1_CD4i_R2L30',
 'AAACAAGCAAGGAATAACAGTCTG-1_CD4i_R2L37',
 'AAACAAGCAAGGAATAACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCAAGGAATAACTACTCA-1_CD4i_R2L47',
 'AAACAAGCAAGGAATAAGAGGCAA-1_CD4i_R2L37',
 'AAACAAGCAAGGAATAAGTGAGTG-1_CD4i_R2L30',
 'AAACAAGCAAGGCCATACAGTCTG-1_CD4i_R2L46',
 'AAACAAGCAAGGCCATACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAAGGCCATAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCAAGGCCTGACAGTCTG-1_CD4i_R2L27',
 'AAACAAGCAAGGCCTGACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAAGGCCTGACTACTCA-1_CD4i_R2L46',
 'AAACAAGCAAGGCCTGAGAGGCAA-1_CD4i_R2L46',
 'AAACAAGCAAGGCGTTACAGTCTG-1_CD4i_R2L45',
 'AAACAAGCAAGGCGTTACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCAAGGCTTAACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCAAGGCTTAACTACTCA-1_CD4i_R2L32',
 'AAACAAGCAAGGCTTAAGAGGCAA-1_CD4i_R2L32',
 'AAACAAGCAAGGCTTAAGAGGCAA-1_CD4i_R2L46',
 'AAACAAGCAAGGCTTAAGTGAGTG-1_CD4i_R2L38',
 'AAACAAGCAAGGGTCTACAGTCTG-1_CD4i_R2L43',
 'AAACAAGCAAGGGTCTAGAGGCAA-1_CD4i_R2L26',
 'AAACAAGCAAGGTGCTACAGTCTG-1_CD4i_R2L31',
 'AAACAAGCAAGGTGCTACAGTCTG-1_CD4i_R2L38',
 'AAACAAGCAAGGTGCTACAGTCTG-1_CD4i_R2L40',
 'AAACAAGCAAGGTGCTACTACTCA-1_CD4i_R2L37',
 'AAACAAGCAAGGTGCTACTACTCA-1_CD4i_R2L46',
 'AAACAAGCAAGGTGCTAGAGGCAA-1_CD4i_R2L32',
 'AAACAAGCAAGGTGCTAGTGAGTG-1_CD4i_R2L40',
 'AAACAAGCAAGGTGTCAGAGGCAA-1_CD4i_R2L36',
 'AAACAAGCAAGGTGTCAGAGGCAA-1_CD4i_R2L43',
 'AAACAAGCAAGGTTATAGAGGCAA-1_CD4i_R2L36',
 'AAACAAGCAAGGTTATAGTGAGTG-1_CD4i_R2L29',
 'AAACAAGCAAGTCGCGACAGTCTG-1_CD4i_R2L28',
 'AAACAAGCAAGTCGCGAGAGGCAA-1_CD4i_R2L39',
 'AAACAAGCAAGTCGCGAGTGAGTG-1_CD4i_R2L41',
 'AAACAAGCAAGTGCACACAGTCTG-1_CD4i_R2L28',
 'AAACAAGCAAGTGCACACAGTCTG-1_CD4i_R2L31',
 'AAACAAGCAAGTGCACACAGTCTG-1_CD4i_R2L38',
 'AAACAAGCAAGTGCACACAGTCTG-1_CD4i_R2L41',
 'AAACAAGCAAGTGCACACTACTCA-1_CD4i_R2L28',
 'AAACAAGCAAGTGCACACTACTCA-1_CD4i_R2L36',
 'AAACAAGCAAGTGCACAGAGGCAA-1_CD4i_R2L28',
 'AAACAAGCAAGTGCACAGAGGCAA-1_CD4i_R2L41',
 'AAACAAGCAAGTGGCTAGTGAGTG-1_CD4i_R2L43',
 'AAACAAGCAAGTTAACAGAGGCAA-1_CD4i_R2L37',
 'AAACAAGCAAGTTAACAGTGAGTG-1_CD4i_R2L38',
 'AAACAAGCAAGTTCCTACAGTCTG-1_CD4i_R2L31',
 'AAACAAGCAAGTTCCTACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAAGTTGCAAGAGGCAA-1_CD4i_R2L39',
 'AAACAAGCAAGTTGCAAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAAGTTGCAAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCAAGTTGGCACAGTCTG-1_CD4i_R2L29',
 'AAACAAGCAAGTTGGCACAGTCTG-1_CD4i_R2L38',
 'AAACAAGCAAGTTGGCACAGTCTG-1_CD4i_R2L45',
 'AAACAAGCAAGTTGGCAGAGGCAA-1_CD4i_R2L29',
 'AAACAAGCAAGTTTCCACTACTCA-1_CD4i_R2L43',
 'AAACAAGCAATAACCGACAGTCTG-1_CD4i_R2L44',
 'AAACAAGCAATAACCGAGAGGCAA-1_CD4i_R2L42',
 'AAACAAGCAATAAGGAACAGTCTG-1_CD4i_R2L25',
 'AAACAAGCAATAAGGAAGAGGCAA-1_CD4i_R2L32',
 'AAACAAGCAATAAGGAAGTGAGTG-1_CD4i_R2L41',
 'AAACAAGCAATACCCTACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCAATACCCTACTACTCA-1_CD4i_R2L34',
 'AAACAAGCAATACCCTAGTGAGTG-1_CD4i_R2L34',
 'AAACAAGCAATACTGGACTACTCA-1_CD4i_R2L45',
 'AAACAAGCAATAGAAGACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCAATAGAAGACAGTCTG-1_CD4i_R2L38',
 'AAACAAGCAATAGAAGAGAGGCAA-1_CD4i_R2L29',
 'AAACAAGCAATAGAAGAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCAATAGAAGAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCAATAGAGAACAGTCTG-1_CD4i_R2L44',
 'AAACAAGCAATAGAGAACTACTCA-1_CD4i_R2L46',
 'AAACAAGCAATAGAGAAGAGGCAA-1_CD4i_R2L26',
 'AAACAAGCAATAGAGAAGTGAGTG-1_CD4i_R2L32',
 'AAACAAGCAATAGCTGACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAATAGCTGAGAGGCAA-1_CD4i_R2L31',
 'AAACAAGCAATAGCTGAGAGGCAA-1_CD4i_R2L37',
 'AAACAAGCAATATGCGACAGTCTG-1_CD4i_R2L26',
 'AAACAAGCAATATGCGACTACTCA-1_CD4i_R2L26',
 'AAACAAGCAATATGCGAGAGGCAA-1_CD4i_R2L32',
 'AAACAAGCAATATGCGAGAGGCAA-1_CD4i_R2L42',
 'AAACAAGCAATATGCGAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAATATGCGAGTGAGTG-1_CD4i_R2L32',
 'AAACAAGCAATATGCGAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCAATATGGTACTACTCA-1_CD4i_R2L48',
 'AAACAAGCAATCAAACACTACTCA-1_CD4i_R2L27',
 'AAACAAGCAATCAAACAGTGAGTG-1_CD4i_R2L27',
 'AAACAAGCAATCAAGTACTACTCA-1_CD4i_R2L28',
 'AAACAAGCAATCATCCAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCAATCCACTACAGTCTG-1_CD4i_R2L41',
 'AAACAAGCAATCCACTAGTGAGTG-1_CD4i_R2L41',
 'AAACAAGCAATCGTGAACTACTCA-1_CD4i_R2L30',
 'AAACAAGCAATCGTGAAGAGGCAA-1_CD4i_R2L30',
 'AAACAAGCAATCGTTCACAGTCTG-1_CD4i_R2L30',
 'AAACAAGCAATCGTTCAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCAATCGTTCAGTGAGTG-1_CD4i_R2L29',
 'AAACAAGCAATGAATCACAGTCTG-1_CD4i_R2L37',
 'AAACAAGCAATGAATCAGTGAGTG-1_CD4i_R2L35',
 'AAACAAGCAATGAGCCACAGTCTG-1_CD4i_R2L27',
 'AAACAAGCAATGAGCCACAGTCTG-1_CD4i_R2L45',
 'AAACAAGCAATGAGCCACTACTCA-1_CD4i_R2L36',
 'AAACAAGCAATGAGCCACTACTCA-1_CD4i_R2L42',
 'AAACAAGCAATGAGCCAGAGGCAA-1_CD4i_R2L45',
 'AAACAAGCAATGAGCCAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCAATGGATTACAGTCTG-1_CD4i_R2L32',
 'AAACAAGCAATGGATTACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAATGGATTAGAGGCAA-1_CD4i_R2L44',
 'AAACAAGCAATGGCCGAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAATGGGAGACAGTCTG-1_CD4i_R2L25',
 'AAACAAGCAATGGGAGAGAGGCAA-1_CD4i_R2L28',
 'AAACAAGCAATGGGAGAGAGGCAA-1_CD4i_R2L35',
 'AAACAAGCAATGGGAGAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAATGTTCCACAGTCTG-1_CD4i_R2L46',
 'AAACAAGCAATTAGACACAGTCTG-1_CD4i_R2L27',
 'AAACAAGCAATTAGACACAGTCTG-1_CD4i_R2L38',
 'AAACAAGCAATTAGACACAGTCTG-1_CD4i_R2L48',
 'AAACAAGCAATTAGACACTACTCA-1_CD4i_R2L27',
 'AAACAAGCAATTAGACACTACTCA-1_CD4i_R2L32',
 'AAACAAGCAATTAGACACTACTCA-1_CD4i_R2L48',
 'AAACAAGCAATTAGACAGTGAGTG-1_CD4i_R2L38',
 'AAACAAGCAATTAGACAGTGAGTG-1_CD4i_R2L48',
 'AAACAAGCAATTAGCGACAGTCTG-1_CD4i_R2L34',
 'AAACAAGCAATTAGCGACTACTCA-1_CD4i_R2L36',
 'AAACAAGCAATTAGGTACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCAATTAGGTACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCAATTAGGTACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCAATTAGGTACTACTCA-1_CD4i_R2L30',
 'AAACAAGCAATTAGGTACTACTCA-1_CD4i_R2L44',
 'AAACAAGCAATTAGGTAGAGGCAA-1_CD4i_R2L34',
 'AAACAAGCAATTCGGAACAGTCTG-1_CD4i_R2L34',
 'AAACAAGCAATTCGGAACTACTCA-1_CD4i_R2L26',
 'AAACAAGCAATTCGGAAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCAATTCGGAAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCAATTCGGAAGTGAGTG-1_CD4i_R2L27',
 'AAACAAGCAATTGAACAGTGAGTG-1_CD4i_R2L31',
 'AAACAAGCAATTGCGAACTACTCA-1_CD4i_R2L45',
 'AAACAAGCAATTGCGAAGAGGCAA-1_CD4i_R2L45',
 'AAACAAGCAATTGCGAAGTGAGTG-1_CD4i_R2L25',
 'AAACAAGCACAAATACACAGTCTG-1_CD4i_R2L41',
 'AAACAAGCACAAATACACTACTCA-1_CD4i_R2L25',
 'AAACAAGCACAAATACAGAGGCAA-1_CD4i_R2L25',
 'AAACAAGCACAAATACAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCACAACAATACTACTCA-1_CD4i_R2L35',
 'AAACAAGCACAACATGAGAGGCAA-1_CD4i_R2L32',
 'AAACAAGCACAAGCGTACAGTCTG-1_CD4i_R2L31',
 'AAACAAGCACAAGCGTACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCACAAGCGTAGTGAGTG-1_CD4i_R2L32',
 'AAACAAGCACAAGCGTAGTGAGTG-1_CD4i_R2L46',
 'AAACAAGCACAATACGACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCACAATACGAGTGAGTG-1_CD4i_R2L29',
 'AAACAAGCACAATAGTACAGTCTG-1_CD4i_R2L32',
 'AAACAAGCACAATAGTACTACTCA-1_CD4i_R2L44',
 'AAACAAGCACAATAGTACTACTCA-1_CD4i_R2L47',
 'AAACAAGCACAATAGTAGTGAGTG-1_CD4i_R2L29',
 'AAACAAGCACAATAGTAGTGAGTG-1_CD4i_R2L38',
 'AAACAAGCACAATCGAACTACTCA-1_CD4i_R2L43',
 'AAACAAGCACAATCGAAGAGGCAA-1_CD4i_R2L37',
 'AAACAAGCACAATCGAAGAGGCAA-1_CD4i_R2L47',
 'AAACAAGCACAATGGCACAGTCTG-1_CD4i_R2L33',
 'AAACAAGCACAATGGCAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCACACAAATAGAGGCAA-1_CD4i_R2L36',
 'AAACAAGCACACAAATAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCACACCCACACAGTCTG-1_CD4i_R2L25',
 'AAACAAGCACACCCACACTACTCA-1_CD4i_R2L25',
 'AAACAAGCACACCCACAGTGAGTG-1_CD4i_R2L25',
 'AAACAAGCACACTAAGACTACTCA-1_CD4i_R2L39',
 'AAACAAGCACACTAAGAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCACACTAAGAGAGGCAA-1_CD4i_R2L47',
 'AAACAAGCACACTGGGACTACTCA-1_CD4i_R2L44',
 'AAACAAGCACACTGGGAGTGAGTG-1_CD4i_R2L44',
 'AAACAAGCACAGCAACAGAGGCAA-1_CD4i_R2L45',
 'AAACAAGCACAGCCAGACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCACAGCCAGAGTGAGTG-1_CD4i_R2L35',
 'AAACAAGCACATAAACAGAGGCAA-1_CD4i_R2L47',
 'AAACAAGCACATAAACAGTGAGTG-1_CD4i_R2L38',
 'AAACAAGCACATAAACAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCACATAAGTACAGTCTG-1_CD4i_R2L31',
 'AAACAAGCACATAAGTACTACTCA-1_CD4i_R2L29',
 'AAACAAGCACATAAGTAGAGGCAA-1_CD4i_R2L29',
 'AAACAAGCACATAAGTAGTGAGTG-1_CD4i_R2L35',
 'AAACAAGCACATAAGTAGTGAGTG-1_CD4i_R2L46',
 'AAACAAGCACATACCTACAGTCTG-1_CD4i_R2L32',
 'AAACAAGCACATACCTAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCACATACCTAGTGAGTG-1_CD4i_R2L30',
 'AAACAAGCACATAGATACTACTCA-1_CD4i_R2L48',
 'AAACAAGCACATAGATAGAGGCAA-1_CD4i_R2L26',
 'AAACAAGCACATAGATAGTGAGTG-1_CD4i_R2L25',
 'AAACAAGCACATAGATAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCACATAGTGACAGTCTG-1_CD4i_R2L29',
 'AAACAAGCACATAGTGACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCACATAGTGACTACTCA-1_CD4i_R2L41',
 'AAACAAGCACATAGTGAGAGGCAA-1_CD4i_R2L29',
 'AAACAAGCACATAGTGAGAGGCAA-1_CD4i_R2L41',
 'AAACAAGCACATAGTGAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCACATGAATACTACTCA-1_CD4i_R2L44',
 'AAACAAGCACATGAATAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCACATGAATAGTGAGTG-1_CD4i_R2L25',
 'AAACAAGCACATGCTTACTACTCA-1_CD4i_R2L39',
 'AAACAAGCACATGCTTAGAGGCAA-1_CD4i_R2L39',
 'AAACAAGCACATGCTTAGAGGCAA-1_CD4i_R2L44',
 'AAACAAGCACATGCTTAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCACATTCGTAGTGAGTG-1_CD4i_R2L31',
 'AAACAAGCACATTCGTAGTGAGTG-1_CD4i_R2L40',
 'AAACAAGCACATTGAGAGAGGCAA-1_CD4i_R2L36',
 'AAACAAGCACATTGAGAGTGAGTG-1_CD4i_R2L36',
 'AAACAAGCACATTGTCACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCACATTGTCACTACTCA-1_CD4i_R2L26',
 'AAACAAGCACATTGTCAGAGGCAA-1_CD4i_R2L26',
 'AAACAAGCACATTGTCAGAGGCAA-1_CD4i_R2L39',
 'AAACAAGCACATTGTCAGTGAGTG-1_CD4i_R2L26',
 'AAACAAGCACATTGTCAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCACCAACAAACAGTCTG-1_CD4i_R2L38',
 'AAACAAGCACCAACAAACAGTCTG-1_CD4i_R2L47',
 'AAACAAGCACCAACAAAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCACCAACAAAGAGGCAA-1_CD4i_R2L47',
 'AAACAAGCACCACACCACAGTCTG-1_CD4i_R2L37',
 'AAACAAGCACCACATTAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCACCAGCCTACAGTCTG-1_CD4i_R2L32',
 'AAACAAGCACCAGCCTACAGTCTG-1_CD4i_R2L33',
 'AAACAAGCACCAGCCTACAGTCTG-1_CD4i_R2L36',
 'AAACAAGCACCAGCCTACTACTCA-1_CD4i_R2L25',
 'AAACAAGCACCAGCCTACTACTCA-1_CD4i_R2L32',
 'AAACAAGCACCAGCCTACTACTCA-1_CD4i_R2L39',
 'AAACAAGCACCAGCCTAGAGGCAA-1_CD4i_R2L25',
 'AAACAAGCACCAGCCTAGAGGCAA-1_CD4i_R2L36',
 'AAACAAGCACCAGCCTAGTGAGTG-1_CD4i_R2L30',
 'AAACAAGCACCAGCCTAGTGAGTG-1_CD4i_R2L33',
 'AAACAAGCACCAGCCTAGTGAGTG-1_CD4i_R2L36',
 'AAACAAGCACCAGCCTAGTGAGTG-1_CD4i_R2L44',
 'AAACAAGCACCAGCTCACAGTCTG-1_CD4i_R2L29',
 'AAACAAGCACCATCATACTACTCA-1_CD4i_R2L25',
 'AAACAAGCACCATCATACTACTCA-1_CD4i_R2L41',
 'AAACAAGCACCATCATAGAGGCAA-1_CD4i_R2L41',
 'AAACAAGCACCATCATAGAGGCAA-1_CD4i_R2L45',
 'AAACAAGCACCATCATAGTGAGTG-1_CD4i_R2L34',
 'AAACAAGCACCATCATAGTGAGTG-1_CD4i_R2L45',
 'AAACAAGCACCATCCAAGAGGCAA-1_CD4i_R2L35',
 'AAACAAGCACCATCCAAGAGGCAA-1_CD4i_R2L42',
 'AAACAAGCACCATCCAAGTGAGTG-1_CD4i_R2L35',
 'AAACAAGCACCGGCAAACAGTCTG-1_CD4i_R2L41',
 'AAACAAGCACCGGCAAACTACTCA-1_CD4i_R2L38',
 'AAACAAGCACCGGCAAAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCACCGGTAGACAGTCTG-1_CD4i_R2L40',
 'AAACAAGCACCGTTTGAGAGGCAA-1_CD4i_R2L28',
 'AAACAAGCACCGTTTGAGTGAGTG-1_CD4i_R2L37',
 'AAACAAGCACCTAAAGACAGTCTG-1_CD4i_R2L42',
 'AAACAAGCACCTAAAGACTACTCA-1_CD4i_R2L29',
 'AAACAAGCACCTAACTACTACTCA-1_CD4i_R2L38',
 'AAACAAGCACCTAACTAGAGGCAA-1_CD4i_R2L27',
 'AAACAAGCACCTAACTAGAGGCAA-1_CD4i_R2L33',
 'AAACAAGCACCTAACTAGAGGCAA-1_CD4i_R2L38',
 'AAACAAGCACCTAACTAGTGAGTG-1_CD4i_R2L27',
 'AAACAAGCACCTAAGAAGAGGCAA-1_CD4i_R2L45',
 'AAACAAGCACCTACTGACTACTCA-1_CD4i_R2L33',
 'AAACAAGCACCTTACGAGAGGCAA-1_CD4i_R2L34',
 'AAACAAGCACCTTACGAGAGGCAA-1_CD4i_R2L43',
 'AAACAAGCACCTTACGAGTGAGTG-1_CD4i_R2L43',
 'AAACAAGCACCTTACGAGTGAGTG-1_CD4i_R2L47',
 'AAACAAGCACCTTCAGACAGTCTG-1_CD4i_R2L37',
 'AAACAAGCACCTTCAGACAGTCTG-1_CD4i_R2L39',
 'AAACAAGCACCTTCAGAGTGAGTG-1_CD4i_R2L39',
 'AAACAAGCACCTTCTCACAGTCTG-1_CD4i_R2L35',
 'AAACAAGCACCTTCTCACAGTCTG-1_CD4i_R2L40',
 'AAACAAGCACCTTCTCACTACTCA-1_CD4i_R2L40',
 'AAACAAGCACCTTCTCACTACTCA-1_CD4i_R2L42',
 'AAACAAGCACCTTCTCAGTGAGTG-1_CD4i_R2L42',
 'AAACAAGCACCTTTGGACAGTCTG-1_CD4i_R2L26',
 'AAACAAGCACCTTTGGACTACTCA-1_CD4i_R2L40',

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

'CACTTGATCGAGAGAAAGTGAGTG-1_CD4i_R2L36',
 'CACTTGATCGAGAGAAAGTGAGTG-1_CD4i_R2L44',
 'CACTTGATCGAGCTAGACAGTCTG-1_CD4i_R2L32',
 'CACTTGATCGAGCTAGAGAGGCAA-1_CD4i_R2L28',
 'CACTTGATCGAGGCACACTACTCA-1_CD4i_R2L25',
 'CACTTGATCGAGGCACAGAGGCAA-1_CD4i_R2L29',
 'CACTTGATCGAGGCACAGTGAGTG-1_CD4i_R2L29',
 'CACTTGATCGAGGCACAGTGAGTG-1_CD4i_R2L35',
 'CACTTGATCGAGGCGTACTACTCA-1_CD4i_R2L42',
 'CACTTGATCGAGGCGTAGTGAGTG-1_CD4i_R2L36',
 'CACTTGATCGAGGTTGACAGTCTG-1_CD4i_R2L47',
 'CACTTGATCGAGGTTGAGAGGCAA-1_CD4i_R2L40',
 'CACTTGATCGAGGTTGAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCGATATAGACTACTCA-1_CD4i_R2L26',
 'CACTTGATCGATATAGACTACTCA-1_CD4i_R2L33',
 'CACTTGATCGATATAGAGAGGCAA-1_CD4i_R2L34',
 'CACTTGATCGATATAGAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCGATATAGAGTGAGTG-1_CD4i_R2L39',
 'CACTTGATCGATATGAACAGTCTG-1_CD4i_R2L41',
 'CACTTGATCGATATGAACTACTCA-1_CD4i_R2L30',
 'CACTTGATCGATATGAACTACTCA-1_CD4i_R2L41',
 'CACTTGATCGATATTCACAGTCTG-1_CD4i_R2L34',
 'CACTTGATCGATATTCACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCGATATTCACTACTCA-1_CD4i_R2L34',
 'CACTTGATCGATATTCACTACTCA-1_CD4i_R2L47',
 'CACTTGATCGATATTCAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCGATATTCAGTGAGTG-1_CD4i_R2L47',
 'CACTTGATCGATGAACACTACTCA-1_CD4i_R2L48',
 'CACTTGATCGATGAACAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGATTAAGACAGTCTG-1_CD4i_R2L31',
 'CACTTGATCGATTAAGAGAGGCAA-1_CD4i_R2L27',
 'CACTTGATCGATTAAGAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCGATTAAGAGTGAGTG-1_CD4i_R2L32',
 'CACTTGATCGATTACTAGAGGCAA-1_CD4i_R2L34',
 'CACTTGATCGATTATCACTACTCA-1_CD4i_R2L36',
 'CACTTGATCGATTATCACTACTCA-1_CD4i_R2L37',
 'CACTTGATCGATTATCAGAGGCAA-1_CD4i_R2L36',
 'CACTTGATCGATTATCAGTGAGTG-1_CD4i_R2L48',
 'CACTTGATCGATTCTGACTACTCA-1_CD4i_R2L47',
 'CACTTGATCGATTCTGAGAGGCAA-1_CD4i_R2L47',
 'CACTTGATCGATTCTGAGTGAGTG-1_CD4i_R2L46',
 'CACTTGATCGATTGAAACAGTCTG-1_CD4i_R2L33',
 'CACTTGATCGATTGAAACTACTCA-1_CD4i_R2L27',
 'CACTTGATCGATTGAAAGAGGCAA-1_CD4i_R2L33',
 'CACTTGATCGATTGAAAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGATTGAAAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCGATTGGGACAGTCTG-1_CD4i_R2L44',
 'CACTTGATCGATTGGGACTACTCA-1_CD4i_R2L25',
 'CACTTGATCGATTGGGACTACTCA-1_CD4i_R2L36',
 'CACTTGATCGCAAATAAGAGGCAA-1_CD4i_R2L38',
 'CACTTGATCGCAAATAAGAGGCAA-1_CD4i_R2L43',
 'CACTTGATCGCAAATAAGAGGCAA-1_CD4i_R2L44',
 'CACTTGATCGCAAATAAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGCAAATAAGTGAGTG-1_CD4i_R2L39',
 'CACTTGATCGCACACTACAGTCTG-1_CD4i_R2L26',
 'CACTTGATCGCACACTACAGTCTG-1_CD4i_R2L48',
 'CACTTGATCGCACACTACTACTCA-1_CD4i_R2L41',
 'CACTTGATCGCACACTACTACTCA-1_CD4i_R2L44',
 'CACTTGATCGCACACTAGAGGCAA-1_CD4i_R2L26',
 'CACTTGATCGCACACTAGAGGCAA-1_CD4i_R2L44',
 'CACTTGATCGCACACTAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGCAGCAAACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCGCAGCAAACAGTCTG-1_CD4i_R2L41',
 'CACTTGATCGCAGCAAAGAGGCAA-1_CD4i_R2L46',
 'CACTTGATCGCAGCAAAGTGAGTG-1_CD4i_R2L41',
 'CACTTGATCGCAGGACACAGTCTG-1_CD4i_R2L34',
 'CACTTGATCGCAGGACACAGTCTG-1_CD4i_R2L48',
 'CACTTGATCGCAGGACACTACTCA-1_CD4i_R2L25',
 'CACTTGATCGCAGGACAGAGGCAA-1_CD4i_R2L25',
 'CACTTGATCGCAGGACAGTGAGTG-1_CD4i_R2L29',
 'CACTTGATCGCAGGACAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCGCAGGACAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCGCAGGACAGTGAGTG-1_CD4i_R2L43',
 'CACTTGATCGCAGGACAGTGAGTG-1_CD4i_R2L48',
 'CACTTGATCGCATTTGACAGTCTG-1_CD4i_R2L28',
 'CACTTGATCGCCTAACACAGTCTG-1_CD4i_R2L29',
 'CACTTGATCGCCTAACAGTGAGTG-1_CD4i_R2L38',
 'CACTTGATCGCCTAGTACAGTCTG-1_CD4i_R2L46',
 'CACTTGATCGCCTAGTAGAGGCAA-1_CD4i_R2L27',
 'CACTTGATCGCCTAGTAGAGGCAA-1_CD4i_R2L41',
 'CACTTGATCGCCTATAACAGTCTG-1_CD4i_R2L47',
 'CACTTGATCGCCTATAACTACTCA-1_CD4i_R2L40',
 'CACTTGATCGCCTATAACTACTCA-1_CD4i_R2L41',
 'CACTTGATCGCCTATAAGAGGCAA-1_CD4i_R2L31',
 'CACTTGATCGCCTATAAGAGGCAA-1_CD4i_R2L32',
 'CACTTGATCGCCTATAAGTGAGTG-1_CD4i_R2L41',
 'CACTTGATCGCCTATAAGTGAGTG-1_CD4i_R2L46',
 'CACTTGATCGCCTCGAACAGTCTG-1_CD4i_R2L47',
 'CACTTGATCGCCTCGAACTACTCA-1_CD4i_R2L46',
 'CACTTGATCGCCTCGAAGTGAGTG-1_CD4i_R2L28',
 'CACTTGATCGCCTCTCACAGTCTG-1_CD4i_R2L37',
 'CACTTGATCGCCTCTCACAGTCTG-1_CD4i_R2L48',
 'CACTTGATCGCCTCTCAGTGAGTG-1_CD4i_R2L32',
 'CACTTGATCGCCTCTCAGTGAGTG-1_CD4i_R2L44',
 'CACTTGATCGCCTGCAACAGTCTG-1_CD4i_R2L37',
 'CACTTGATCGCCTGCAAGAGGCAA-1_CD4i_R2L29',
 'CACTTGATCGCGAAATACTACTCA-1_CD4i_R2L40',
 'CACTTGATCGCGAAATAGTGAGTG-1_CD4i_R2L38',
 'CACTTGATCGCGAGTAACTACTCA-1_CD4i_R2L25',
 'CACTTGATCGCGAGTAACTACTCA-1_CD4i_R2L30',
 'CACTTGATCGCGAGTAACTACTCA-1_CD4i_R2L45',
 'CACTTGATCGCGCATTACAGTCTG-1_CD4i_R2L42',
 'CACTTGATCGCGGAACACAGTCTG-1_CD4i_R2L37',
 'CACTTGATCGCGGAACACAGTCTG-1_CD4i_R2L43',
 'CACTTGATCGCGGAACACTACTCA-1_CD4i_R2L27',
 'CACTTGATCGCGGAACACTACTCA-1_CD4i_R2L48',
 'CACTTGATCGCGGAACAGAGGCAA-1_CD4i_R2L27',
 'CACTTGATCGCGGAACAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCGCGGATAACTACTCA-1_CD4i_R2L27',
 'CACTTGATCGCGGATAAGAGGCAA-1_CD4i_R2L34',
 'CACTTGATCGCGGATAAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGCGGATAAGTGAGTG-1_CD4i_R2L48',
 'CACTTGATCGCGTTACAGAGGCAA-1_CD4i_R2L38',
 'CACTTGATCGCGTTACAGAGGCAA-1_CD4i_R2L42',
 'CACTTGATCGCGTTCGACAGTCTG-1_CD4i_R2L32',
 'CACTTGATCGCGTTCGACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCGCGTTCGACAGTCTG-1_CD4i_R2L47',
 'CACTTGATCGCGTTCGACTACTCA-1_CD4i_R2L48',
 'CACTTGATCGCGTTCGAGAGGCAA-1_CD4i_R2L31',
 'CACTTGATCGCGTTCGAGAGGCAA-1_CD4i_R2L37',
 'CACTTGATCGCTATATACTACTCA-1_CD4i_R2L45',
 'CACTTGATCGCTATATAGAGGCAA-1_CD4i_R2L40',
 'CACTTGATCGCTATATAGTGAGTG-1_CD4i_R2L30',
 'CACTTGATCGCTATATAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCGCTATATAGTGAGTG-1_CD4i_R2L41',
 'CACTTGATCGCTCAGTACTACTCA-1_CD4i_R2L27',
 'CACTTGATCGCTCAGTACTACTCA-1_CD4i_R2L34',
 'CACTTGATCGCTCAGTAGAGGCAA-1_CD4i_R2L45',
 'CACTTGATCGCTTCAAACAGTCTG-1_CD4i_R2L29',
 'CACTTGATCGCTTCAAACTACTCA-1_CD4i_R2L43',
 'CACTTGATCGCTTCAAAGAGGCAA-1_CD4i_R2L43',
 'CACTTGATCGCTTCAAAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGCTTCAAAGTGAGTG-1_CD4i_R2L44',
 'CACTTGATCGCTTCAAAGTGAGTG-1_CD4i_R2L48',
 'CACTTGATCGCTTCGGACAGTCTG-1_CD4i_R2L42',
 'CACTTGATCGCTTCGGACTACTCA-1_CD4i_R2L36',
 'CACTTGATCGCTTGACACAGTCTG-1_CD4i_R2L43',
 'CACTTGATCGCTTGACACAGTCTG-1_CD4i_R2L47',
 'CACTTGATCGCTTGACACTACTCA-1_CD4i_R2L43',
 'CACTTGATCGCTTGACAGAGGCAA-1_CD4i_R2L34',
 'CACTTGATCGCTTGACAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCGCTTGACAGTGAGTG-1_CD4i_R2L47',
 'CACTTGATCGCTTGCGACAGTCTG-1_CD4i_R2L29',
 'CACTTGATCGCTTGCGAGAGGCAA-1_CD4i_R2L45',
 'CACTTGATCGCTTGGTACTACTCA-1_CD4i_R2L35',
 'CACTTGATCGCTTGGTACTACTCA-1_CD4i_R2L44',
 'CACTTGATCGCTTGGTAGTGAGTG-1_CD4i_R2L36',
 'CACTTGATCGCTTGGTAGTGAGTG-1_CD4i_R2L38',
 'CACTTGATCGGCTAAGACAGTCTG-1_CD4i_R2L44',
 'CACTTGATCGGCTAAGACTACTCA-1_CD4i_R2L42',
 'CACTTGATCGGCTAAGAGAGGCAA-1_CD4i_R2L42',
 'CACTTGATCGGCTAGAACAGTCTG-1_CD4i_R2L30',
 'CACTTGATCGGCTAGAACTACTCA-1_CD4i_R2L30',
 'CACTTGATCGGCTAGAAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGGCTAGAAGTGAGTG-1_CD4i_R2L28',
 'CACTTGATCGGCTAGAAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCGGGACTAAGAGGCAA-1_CD4i_R2L27',
 'CACTTGATCGGGACTAAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCGGGATGCACTACTCA-1_CD4i_R2L44',
 'CACTTGATCGGGATGCAGAGGCAA-1_CD4i_R2L26',
 'CACTTGATCGGGATGCAGAGGCAA-1_CD4i_R2L41',
 'CACTTGATCGGGCAACACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCGGGCAACAGAGGCAA-1_CD4i_R2L36',
 'CACTTGATCGGGCAGTACAGTCTG-1_CD4i_R2L33',
 'CACTTGATCGGGCAGTAGAGGCAA-1_CD4i_R2L26',
 'CACTTGATCGGGCAGTAGAGGCAA-1_CD4i_R2L28',
 'CACTTGATCGGGCAGTAGAGGCAA-1_CD4i_R2L39',
 'CACTTGATCGGGCAGTAGTGAGTG-1_CD4i_R2L28',
 'CACTTGATCGGGCAGTAGTGAGTG-1_CD4i_R2L35',
 'CACTTGATCGGTAAACACAGTCTG-1_CD4i_R2L38',
 'CACTTGATCGGTAAACAGAGGCAA-1_CD4i_R2L25',
 'CACTTGATCGGTAAACAGAGGCAA-1_CD4i_R2L31',
 'CACTTGATCGGTAAACAGAGGCAA-1_CD4i_R2L44',
 'CACTTGATCGGTAACGACAGTCTG-1_CD4i_R2L29',
 'CACTTGATCGGTAACGACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCGGTAACGACTACTCA-1_CD4i_R2L31',
 'CACTTGATCGGTAACGACTACTCA-1_CD4i_R2L35',
 'CACTTGATCGGTAAGTACTACTCA-1_CD4i_R2L29',
 'CACTTGATCGGTAAGTACTACTCA-1_CD4i_R2L44',
 'CACTTGATCGGTAAGTACTACTCA-1_CD4i_R2L48',
 'CACTTGATCGGTAAGTAGAGGCAA-1_CD4i_R2L36',
 'CACTTGATCGGTAAGTAGAGGCAA-1_CD4i_R2L39',
 'CACTTGATCGGTAAGTAGAGGCAA-1_CD4i_R2L46',
 'CACTTGATCGGTACCTACAGTCTG-1_CD4i_R2L26',
 'CACTTGATCGGTACCTACAGTCTG-1_CD4i_R2L27',
 'CACTTGATCGGTACCTACAGTCTG-1_CD4i_R2L38',
 'CACTTGATCGGTACCTACTACTCA-1_CD4i_R2L37',
 'CACTTGATCGGTACCTACTACTCA-1_CD4i_R2L47',
 'CACTTGATCGGTACCTAGAGGCAA-1_CD4i_R2L26',
 'CACTTGATCGGTACCTAGAGGCAA-1_CD4i_R2L38',
 'CACTTGATCGGTACGAACAGTCTG-1_CD4i_R2L37',
 'CACTTGATCGGTACGAACTACTCA-1_CD4i_R2L28',
 'CACTTGATCGGTACGAACTACTCA-1_CD4i_R2L37',
 'CACTTGATCGGTACGAAGAGGCAA-1_CD4i_R2L29',
 'CACTTGATCGGTACGAAGTGAGTG-1_CD4i_R2L36',
 'CACTTGATCGGTCAAGACAGTCTG-1_CD4i_R2L41',
 'CACTTGATCGGTCAAGACTACTCA-1_CD4i_R2L35',
 'CACTTGATCGGTTATTAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCGGTTCCGACAGTCTG-1_CD4i_R2L36',
 'CACTTGATCGGTTCCGACAGTCTG-1_CD4i_R2L39',
 'CACTTGATCGGTTCCGACAGTCTG-1_CD4i_R2L42',
 'CACTTGATCGGTTCCGAGAGGCAA-1_CD4i_R2L39',
 'CACTTGATCGGTTCCGAGAGGCAA-1_CD4i_R2L45',
 'CACTTGATCGTAAAGCACTACTCA-1_CD4i_R2L47',
 'CACTTGATCGTAACCCACAGTCTG-1_CD4i_R2L33',
 'CACTTGATCGTAACCCACTACTCA-1_CD4i_R2L32',
 'CACTTGATCGTAACCCAGAGGCAA-1_CD4i_R2L47',
 'CACTTGATCGTAACCCAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCGTAACTTACTACTCA-1_CD4i_R2L29',
 'CACTTGATCGTAACTTACTACTCA-1_CD4i_R2L45',
 'CACTTGATCGTAACTTAGAGGCAA-1_CD4i_R2L31',
 'CACTTGATCGTAGTTTACAGTCTG-1_CD4i_R2L42',
 'CACTTGATCGTAGTTTAGAGGCAA-1_CD4i_R2L42',
 'CACTTGATCGTAGTTTAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCGTAGTTTAGTGAGTG-1_CD4i_R2L41',
 'CACTTGATCGTCAACCACAGTCTG-1_CD4i_R2L25',
 'CACTTGATCGTCAACCACTACTCA-1_CD4i_R2L26',
 'CACTTGATCGTCAATTACTACTCA-1_CD4i_R2L30',
 'CACTTGATCGTCAATTACTACTCA-1_CD4i_R2L35',
 'CACTTGATCGTCAATTACTACTCA-1_CD4i_R2L38',
 'CACTTGATCGTCAATTAGTGAGTG-1_CD4i_R2L35',
 'CACTTGATCGTCCATAACTACTCA-1_CD4i_R2L28',
 'CACTTGATCGTCCATAAGTGAGTG-1_CD4i_R2L28',
 'CACTTGATCGTCCCGAACAGTCTG-1_CD4i_R2L40',
 'CACTTGATCGTCCCGAACTACTCA-1_CD4i_R2L25',
 'CACTTGATCGTCCCGAAGTGAGTG-1_CD4i_R2L36',
 'CACTTGATCGTCCCGAAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCGTGATGGACAGTCTG-1_CD4i_R2L31',
 'CACTTGATCGTGATGGACTACTCA-1_CD4i_R2L27',
 'CACTTGATCGTGATGGACTACTCA-1_CD4i_R2L31',
 'CACTTGATCGTGATGGAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCGTGATTTACAGTCTG-1_CD4i_R2L28',
 'CACTTGATCGTTAACTACAGTCTG-1_CD4i_R2L44',
 'CACTTGATCGTTAACTACAGTCTG-1_CD4i_R2L48',
 'CACTTGATCGTTAACTACTACTCA-1_CD4i_R2L39',
 'CACTTGATCGTTAACTACTACTCA-1_CD4i_R2L48',
 'CACTTGATCGTTAACTAGAGGCAA-1_CD4i_R2L34',
 'CACTTGATCGTTAACTAGAGGCAA-1_CD4i_R2L39',
 'CACTTGATCGTTAACTAGAGGCAA-1_CD4i_R2L47',
 'CACTTGATCGTTAACTAGTGAGTG-1_CD4i_R2L38',
 'CACTTGATCGTTAGGGACTACTCA-1_CD4i_R2L25',
 'CACTTGATCGTTAGGGAGAGGCAA-1_CD4i_R2L47',
 'CACTTGATCGTTAGGGAGTGAGTG-1_CD4i_R2L41',
 'CACTTGATCGTTAGGGAGTGAGTG-1_CD4i_R2L43',
 'CACTTGATCGTTATGTACTACTCA-1_CD4i_R2L37',
 'CACTTGATCGTTATGTAGAGGCAA-1_CD4i_R2L40',
 'CACTTGATCGTTCGTAACAGTCTG-1_CD4i_R2L38',
 'CACTTGATCGTTCGTAACAGTCTG-1_CD4i_R2L44',
 'CACTTGATCGTTCGTAACTACTCA-1_CD4i_R2L41',
 'CACTTGATCGTTCGTAACTACTCA-1_CD4i_R2L46',
 'CACTTGATCGTTCGTAAGTGAGTG-1_CD4i_R2L38',
 'CACTTGATCGTTCGTAAGTGAGTG-1_CD4i_R2L41',
 'CACTTGATCGTTGCACACAGTCTG-1_CD4i_R2L31',
 'CACTTGATCGTTGCACACAGTCTG-1_CD4i_R2L46',
 'CACTTGATCGTTGCACAGAGGCAA-1_CD4i_R2L31',
 'CACTTGATCGTTGCACAGTGAGTG-1_CD4i_R2L39',
 'CACTTGATCTAACCATACAGTCTG-1_CD4i_R2L31',
 'CACTTGATCTAACCATACTACTCA-1_CD4i_R2L37',
 'CACTTGATCTAACCATACTACTCA-1_CD4i_R2L44',
 'CACTTGATCTAACCTGACAGTCTG-1_CD4i_R2L38',
 'CACTTGATCTAACCTGACAGTCTG-1_CD4i_R2L39',
 'CACTTGATCTAACCTGACTACTCA-1_CD4i_R2L44',
 'CACTTGATCTAACCTGAGAGGCAA-1_CD4i_R2L39',
 'CACTTGATCTAACTACACAGTCTG-1_CD4i_R2L45',
 'CACTTGATCTAACTACAGAGGCAA-1_CD4i_R2L37',
 'CACTTGATCTAACTACAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTAAGTAGACAGTCTG-1_CD4i_R2L32',
 'CACTTGATCTAAGTAGACTACTCA-1_CD4i_R2L28',
 'CACTTGATCTAAGTAGACTACTCA-1_CD4i_R2L32',
 'CACTTGATCTAAGTAGAGAGGCAA-1_CD4i_R2L27',
 'CACTTGATCTAAGTAGAGAGGCAA-1_CD4i_R2L29',
 'CACTTGATCTAAGTAGAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCTAAGTAGAGTGAGTG-1_CD4i_R2L29',
 'CACTTGATCTAAGTCTACAGTCTG-1_CD4i_R2L30',
 'CACTTGATCTAAGTCTAGAGGCAA-1_CD4i_R2L43',
 'CACTTGATCTAAGTCTAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTAATCACACAGTCTG-1_CD4i_R2L25',
 'CACTTGATCTAATCACACAGTCTG-1_CD4i_R2L30',
 'CACTTGATCTAATCACACTACTCA-1_CD4i_R2L30',
 'CACTTGATCTAATCACACTACTCA-1_CD4i_R2L45',
 'CACTTGATCTAATCACAGAGGCAA-1_CD4i_R2L30',
 'CACTTGATCTAATCACAGTGAGTG-1_CD4i_R2L31',
 'CACTTGATCTAATCGTACAGTCTG-1_CD4i_R2L34',
 'CACTTGATCTAATCGTACAGTCTG-1_CD4i_R2L40',
 'CACTTGATCTAATGAGACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCTAATGGAACAGTCTG-1_CD4i_R2L46',
 'CACTTGATCTAATGGAACTACTCA-1_CD4i_R2L26',
 'CACTTGATCTAATGGAACTACTCA-1_CD4i_R2L37',
 'CACTTGATCTAATGGAAGTGAGTG-1_CD4i_R2L37',
 'CACTTGATCTAATTGCACAGTCTG-1_CD4i_R2L33',
 'CACTTGATCTAATTGCACTACTCA-1_CD4i_R2L29',
 'CACTTGATCTAATTGCAGAGGCAA-1_CD4i_R2L42',
 'CACTTGATCTAATTGCAGTGAGTG-1_CD4i_R2L29',
 'CACTTGATCTAATTGCAGTGAGTG-1_CD4i_R2L42',
 'CACTTGATCTACTACGACAGTCTG-1_CD4i_R2L37',
 'CACTTGATCTACTACGACAGTCTG-1_CD4i_R2L39',
 'CACTTGATCTACTACGACTACTCA-1_CD4i_R2L33',
 'CACTTGATCTACTACGACTACTCA-1_CD4i_R2L37',
 'CACTTGATCTACTACGACTACTCA-1_CD4i_R2L38',
 'CACTTGATCTACTACGACTACTCA-1_CD4i_R2L45',
 'CACTTGATCTAGCCTAACAGTCTG-1_CD4i_R2L40',
 'CACTTGATCTAGCCTAACTACTCA-1_CD4i_R2L31',
 'CACTTGATCTAGCCTAACTACTCA-1_CD4i_R2L38',
 'CACTTGATCTAGCCTAACTACTCA-1_CD4i_R2L40',
 'CACTTGATCTAGCCTAACTACTCA-1_CD4i_R2L43',
 'CACTTGATCTAGCCTAAGAGGCAA-1_CD4i_R2L40',
 'CACTTGATCTAGCCTAAGAGGCAA-1_CD4i_R2L43',
 'CACTTGATCTAGCCTAAGTGAGTG-1_CD4i_R2L29',
 'CACTTGATCTAGCCTAAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCTAGCCTAAGTGAGTG-1_CD4i_R2L43',
 'CACTTGATCTAGTTACACTACTCA-1_CD4i_R2L44',
 'CACTTGATCTAGTTACAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCTAGTTACAGTGAGTG-1_CD4i_R2L43',
 'CACTTGATCTAGTTACAGTGAGTG-1_CD4i_R2L44',
 'CACTTGATCTATCACGACAGTCTG-1_CD4i_R2L29',
 'CACTTGATCTATCACGACTACTCA-1_CD4i_R2L29',
 'CACTTGATCTATCACGAGAGGCAA-1_CD4i_R2L42',
 'CACTTGATCTATCACGAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTATCGGCACAGTCTG-1_CD4i_R2L27',
 'CACTTGATCTATCGGCAGAGGCAA-1_CD4i_R2L25',
 'CACTTGATCTATCGGCAGTGAGTG-1_CD4i_R2L25',
 'CACTTGATCTATCTGGACAGTCTG-1_CD4i_R2L36',
 'CACTTGATCTATCTGGACTACTCA-1_CD4i_R2L44',
 'CACTTGATCTATCTGGAGTGAGTG-1_CD4i_R2L44',
 'CACTTGATCTATGGCCACAGTCTG-1_CD4i_R2L25',
 'CACTTGATCTATGGCCACTACTCA-1_CD4i_R2L47',
 'CACTTGATCTATTGACACAGTCTG-1_CD4i_R2L43',
 'CACTTGATCTATTGCGACAGTCTG-1_CD4i_R2L30',
 'CACTTGATCTATTGGTACAGTCTG-1_CD4i_R2L30',
 'CACTTGATCTCAAACTACAGTCTG-1_CD4i_R2L31',
 'CACTTGATCTCAAACTACAGTCTG-1_CD4i_R2L33',
 'CACTTGATCTCAAACTACAGTCTG-1_CD4i_R2L48',
 'CACTTGATCTCAAACTACTACTCA-1_CD4i_R2L36',
 'CACTTGATCTCAAACTACTACTCA-1_CD4i_R2L46',
 'CACTTGATCTCAAACTACTACTCA-1_CD4i_R2L48',
 'CACTTGATCTCAAACTAGAGGCAA-1_CD4i_R2L31',
 'CACTTGATCTCAAGAAAGTGAGTG-1_CD4i_R2L39',
 'CACTTGATCTCACAATAGAGGCAA-1_CD4i_R2L27',
 'CACTTGATCTCACAATAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCTCACCGGACAGTCTG-1_CD4i_R2L38',
 'CACTTGATCTCACCGGACTACTCA-1_CD4i_R2L36',
 'CACTTGATCTCACCGGAGTGAGTG-1_CD4i_R2L38',
 'CACTTGATCTCACCTTAGTGAGTG-1_CD4i_R2L29',
 'CACTTGATCTCACCTTAGTGAGTG-1_CD4i_R2L37',
 'CACTTGATCTCACTAGACAGTCTG-1_CD4i_R2L26',
 'CACTTGATCTCACTAGACAGTCTG-1_CD4i_R2L39',
 'CACTTGATCTCACTAGACAGTCTG-1_CD4i_R2L46',
 'CACTTGATCTCACTAGACTACTCA-1_CD4i_R2L39',
 'CACTTGATCTCACTAGAGAGGCAA-1_CD4i_R2L26',
 'CACTTGATCTCACTAGAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTCACTAGAGTGAGTG-1_CD4i_R2L39',
 'CACTTGATCTCACTAGAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCTCAGCACACTACTCA-1_CD4i_R2L41',
 'CACTTGATCTCAGCTAACAGTCTG-1_CD4i_R2L36',
 'CACTTGATCTCAGCTAACTACTCA-1_CD4i_R2L33',
 'CACTTGATCTCAGCTAACTACTCA-1_CD4i_R2L36',
 'CACTTGATCTCAGCTAAGAGGCAA-1_CD4i_R2L36',
 'CACTTGATCTCAGCTAAGAGGCAA-1_CD4i_R2L45',
 'CACTTGATCTCCATCTACAGTCTG-1_CD4i_R2L34',
 'CACTTGATCTCCATCTACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCTCCATCTACAGTCTG-1_CD4i_R2L43',
 'CACTTGATCTCCATCTACTACTCA-1_CD4i_R2L32',
 'CACTTGATCTCCATCTACTACTCA-1_CD4i_R2L34',
 'CACTTGATCTCCATCTAGAGGCAA-1_CD4i_R2L30',
 'CACTTGATCTCCATCTAGAGGCAA-1_CD4i_R2L35',
 'CACTTGATCTCCATCTAGTGAGTG-1_CD4i_R2L48',
 'CACTTGATCTCGCCTCACTACTCA-1_CD4i_R2L42',
 'CACTTGATCTCTATGGACAGTCTG-1_CD4i_R2L41',
 'CACTTGATCTCTATGGACAGTCTG-1_CD4i_R2L46',
 'CACTTGATCTCTATGGACTACTCA-1_CD4i_R2L26',
 'CACTTGATCTCTATGGAGAGGCAA-1_CD4i_R2L40',
 'CACTTGATCTCTATGGAGTGAGTG-1_CD4i_R2L33',
 'CACTTGATCTCTATGGAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCTCTCGCCACTACTCA-1_CD4i_R2L46',
 'CACTTGATCTCTCGCCAGAGGCAA-1_CD4i_R2L38',
 'CACTTGATCTGCCATAAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTGGAAACAGAGGCAA-1_CD4i_R2L36',
 'CACTTGATCTGGAAACAGAGGCAA-1_CD4i_R2L42',
 'CACTTGATCTGGAACGACTACTCA-1_CD4i_R2L30',
 'CACTTGATCTGGAACGAGAGGCAA-1_CD4i_R2L32',
 'CACTTGATCTGGAACGAGTGAGTG-1_CD4i_R2L30',
 'CACTTGATCTGGAACGAGTGAGTG-1_CD4i_R2L32',
 'CACTTGATCTGGCCATACAGTCTG-1_CD4i_R2L33',
 'CACTTGATCTGGCCCAACAGTCTG-1_CD4i_R2L46',
 'CACTTGATCTGGCCCAACAGTCTG-1_CD4i_R2L48',
 'CACTTGATCTGGCCCAAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCTGGCCCAAGTGAGTG-1_CD4i_R2L25',
 'CACTTGATCTGGCCCAAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTGGCTACACAGTCTG-1_CD4i_R2L34',
 'CACTTGATCTGGCTACACAGTCTG-1_CD4i_R2L35',
 'CACTTGATCTGGCTACACTACTCA-1_CD4i_R2L34',
 'CACTTGATCTGGGAATACAGTCTG-1_CD4i_R2L28',
 'CACTTGATCTGGGAATACTACTCA-1_CD4i_R2L36',
 'CACTTGATCTGGGAATACTACTCA-1_CD4i_R2L39',
 'CACTTGATCTGGGAATAGTGAGTG-1_CD4i_R2L28',
 'CACTTGATCTGGGAATAGTGAGTG-1_CD4i_R2L39',
 'CACTTGATCTGGTCTAACTACTCA-1_CD4i_R2L47',
 'CACTTGATCTGGTCTAAGAGGCAA-1_CD4i_R2L47',
 'CACTTGATCTGGTCTAAGTGAGTG-1_CD4i_R2L32',
 'CACTTGATCTGTCAATACAGTCTG-1_CD4i_R2L32',
 'CACTTGATCTGTCAATACTACTCA-1_CD4i_R2L32',
 'CACTTGATCTGTCAATAGTGAGTG-1_CD4i_R2L28',
 'CACTTGATCTGTCAATAGTGAGTG-1_CD4i_R2L34',
 'CACTTGATCTGTCAATAGTGAGTG-1_CD4i_R2L46',
 'CACTTGATCTGTCAGCACAGTCTG-1_CD4i_R2L37',
 'CACTTGATCTGTCAGCACTACTCA-1_CD4i_R2L25',
 'CACTTGATCTGTCAGCAGAGGCAA-1_CD4i_R2L37',
 'CACTTGATCTGTGACCACTACTCA-1_CD4i_R2L41',
 'CACTTGATCTGTGACCAGAGGCAA-1_CD4i_R2L33',
 'CACTTGATCTGTGACCAGTGAGTG-1_CD4i_R2L29',
 'CACTTGATCTGTGACCAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCTGTGACCAGTGAGTG-1_CD4i_R2L45',
 'CACTTGATCTGTGATTACTACTCA-1_CD4i_R2L40',
 'CACTTGATCTGTGATTACTACTCA-1_CD4i_R2L43',
 'CACTTGATCTGTGATTAGAGGCAA-1_CD4i_R2L46',
 'CACTTGATCTGTGATTAGTGAGTG-1_CD4i_R2L36',
 'CACTTGATCTGTGATTAGTGAGTG-1_CD4i_R2L43',
 'CACTTGATCTGTGCACACAGTCTG-1_CD4i_R2L38',
 'CACTTGATCTGTGCACAGAGGCAA-1_CD4i_R2L38',
 'CACTTGATCTTAAGCTACTACTCA-1_CD4i_R2L26',
 'CACTTGATCTTAAGCTAGAGGCAA-1_CD4i_R2L26',
 'CACTTGATCTTAAGCTAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTTAAGGAAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCTTAAGGAAGTGAGTG-1_CD4i_R2L46',
 'CACTTGATCTTAATGCACAGTCTG-1_CD4i_R2L27',
 'CACTTGATCTTAATGCACTACTCA-1_CD4i_R2L27',
 'CACTTGATCTTAATGCACTACTCA-1_CD4i_R2L41',
 'CACTTGATCTTAATGCACTACTCA-1_CD4i_R2L42',
 'CACTTGATCTTACTCCACAGTCTG-1_CD4i_R2L41',
 'CACTTGATCTTACTCCAGAGGCAA-1_CD4i_R2L30',
 'CACTTGATCTTACTCCAGTGAGTG-1_CD4i_R2L37',
 'CACTTGATCTTACTCCAGTGAGTG-1_CD4i_R2L48',
 'CACTTGATCTTCAAGTACAGTCTG-1_CD4i_R2L30',
 'CACTTGATCTTCAAGTACTACTCA-1_CD4i_R2L34',
 'CACTTGATCTTCAAGTAGAGGCAA-1_CD4i_R2L40',
 'CACTTGATCTTCGCCCACTACTCA-1_CD4i_R2L27',
 'CACTTGATCTTCGCCCACTACTCA-1_CD4i_R2L29',
 'CACTTGATCTTCGCCCAGAGGCAA-1_CD4i_R2L33',
 'CACTTGATCTTCGCCCAGAGGCAA-1_CD4i_R2L46',
 'CACTTGATCTTCGCCCAGAGGCAA-1_CD4i_R2L48',
 'CACTTGATCTTCGCCCAGTGAGTG-1_CD4i_R2L46',
 'CACTTGATCTTGAAAGAGTGAGTG-1_CD4i_R2L40',
 'CACTTGATCTTGAAGAACAGTCTG-1_CD4i_R2L26',
 'CACTTGATCTTGAAGAAGTGAGTG-1_CD4i_R2L26',
 'CACTTGATCTTGAATCACTACTCA-1_CD4i_R2L35',
 'CACTTGATCTTGAATCACTACTCA-1_CD4i_R2L36',
 'CACTTGATCTTGAATCACTACTCA-1_CD4i_R2L42',
 'CACTTGATCTTGAGGGACTACTCA-1_CD4i_R2L43',
 'CACTTGATCTTGAGGGAGAGGCAA-1_CD4i_R2L34',
 'CACTTGATCTTGAGGGAGTGAGTG-1_CD4i_R2L43',
 'CACTTGATCTTGATCGACAGTCTG-1_CD4i_R2L31',
 'CACTTGATCTTGATCGACAGTCTG-1_CD4i_R2L43',
 'CACTTGATCTTGATCGACTACTCA-1_CD4i_R2L38',
 'CACTTGATCTTGATCGAGAGGCAA-1_CD4i_R2L31',
 'CACTTGATCTTGATCGAGTGAGTG-1_CD4i_R2L43',
 'CACTTGATCTTTAAGCACAGTCTG-1_CD4i_R2L31',
 'CACTTGATCTTTAAGCACTACTCA-1_CD4i_R2L29',
 'CACTTGATCTTTAAGCACTACTCA-1_CD4i_R2L33',
 'CACTTGATCTTTAAGCAGTGAGTG-1_CD4i_R2L31',
 'CACTTGATCTTTAGCGACAGTCTG-1_CD4i_R2L32',
 'CACTTGATCTTTAGCGACAGTCTG-1_CD4i_R2L34',
 'CACTTGATCTTTAGCGACTACTCA-1_CD4i_R2L34',
 'CACTTGATCTTTAGCGACTACTCA-1_CD4i_R2L46',
 'CACTTGATCTTTAGCGAGAGGCAA-1_CD4i_R2L32',
 'CACTTGATCTTTAGCGAGAGGCAA-1_CD4i_R2L34',
 'CACTTGATCTTTGGATACTACTCA-1_CD4i_R2L45',
 'CACTTGATCTTTGGATAGTGAGTG-1_CD4i_R2L27',
 'CACTTGATCTTTGGTGACAGTCTG-1_CD4i_R2L28',
 'CACTTGATCTTTGGTGACAGTCTG-1_CD4i_R2L30',
 'CACTTGATCTTTGGTGACAGTCTG-1_CD4i_R2L32',
 'CACTTTACAAACAAGAACAGTCTG-1_CD4i_R2L29',
 'CACTTTACAAACAAGAACTACTCA-1_CD4i_R2L39',
 'CACTTTACAAACAAGAAGTGAGTG-1_CD4i_R2L40',
 'CACTTTACAAACAATCACAGTCTG-1_CD4i_R2L29',
 'CACTTTACAAACAATCACAGTCTG-1_CD4i_R2L48',
 'CACTTTACAAACAATCACTACTCA-1_CD4i_R2L29',

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

,
 'GATTAGTCATAGGCGTACTACTCA-1_CD4i_R2L41',
 'GATTAGTCATAGGGTCACAGTCTG-1_CD4i_R2L48',
 'GATTAGTCATAGGGTCACTACTCA-1_CD4i_R2L25',
 'GATTAGTCATAGGGTCACTACTCA-1_CD4i_R2L26',
 'GATTAGTCATATAGGTACAGTCTG-1_CD4i_R2L26',
 'GATTAGTCATATAGGTACAGTCTG-1_CD4i_R2L29',
 'GATTAGTCATATAGGTACTACTCA-1_CD4i_R2L42',
 'GATTAGTCATATAGGTAGTGAGTG-1_CD4i_R2L31',
 'GATTAGTCATATCGCTACAGTCTG-1_CD4i_R2L44',
 'GATTAGTCATATCGCTACTACTCA-1_CD4i_R2L36',
 'GATTAGTCATATCGCTAGAGGCAA-1_CD4i_R2L44',
 'GATTAGTCATATCGCTAGTGAGTG-1_CD4i_R2L33',
 'GATTAGTCATATGGTGACAGTCTG-1_CD4i_R2L40',
 'GATTAGTCATATGGTGAGAGGCAA-1_CD4i_R2L32',
 'GATTAGTCATATGGTGAGAGGCAA-1_CD4i_R2L41',
 'GATTAGTCATATTTCGACTACTCA-1_CD4i_R2L27',
 'GATTAGTCATCAAGCAACAGTCTG-1_CD4i_R2L25',
 'GATTAGTCATCAAGCAACAGTCTG-1_CD4i_R2L46',
 'GATTAGTCATCAAGCAAGAGGCAA-1_CD4i_R2L45',
 'GATTAGTCATCAAGCAAGTGAGTG-1_CD4i_R2L46',
 'GATTAGTCATCAAGTGACAGTCTG-1_CD4i_R2L26',
 'GATTAGTCATCAAGTGACTACTCA-1_CD4i_R2L43',
 'GATTAGTCATCAATCCACAGTCTG-1_CD4i_R2L36',
 'GATTAGTCATCAATCCACTACTCA-1_CD4i_R2L36',
 'GATTAGTCATCAATCCACTACTCA-1_CD4i_R2L41',
 'GATTAGTCATCAATCCAGAGGCAA-1_CD4i_R2L41',
 'GATTAGTCATCACAGAACTACTCA-1_CD4i_R2L28',
 'GATTAGTCATCACAGAAGAGGCAA-1_CD4i_R2L40',
 'GATTAGTCATCACGAAACAGTCTG-1_CD4i_R2L45',
 'GATTAGTCATCACGAAAGAGGCAA-1_CD4i_R2L35',
 'GATTAGTCATCACGAAAGAGGCAA-1_CD4i_R2L40',
 'GATTAGTCATCACGAAAGTGAGTG-1_CD4i_R2L45',
 'GATTAGTCATCACGCCACTACTCA-1_CD4i_R2L46',
 'GATTAGTCATCACGCCAGAGGCAA-1_CD4i_R2L47',
 'GATTAGTCATCACGCCAGTGAGTG-1_CD4i_R2L47',
 'GATTAGTCATCAGGACAGTGAGTG-1_CD4i_R2L26',
 'GATTAGTCATCAGGTAACTACTCA-1_CD4i_R2L47',
 'GATTAGTCATCAGGTAAGTGAGTG-1_CD4i_R2L39',
 'GATTAGTCATCATAGGACAGTCTG-1_CD4i_R2L47',
 'GATTAGTCATCATAGGAGAGGCAA-1_CD4i_R2L31',
 'GATTAGTCATCATCACACAGTCTG-1_CD4i_R2L26',
 'GATTAGTCATCATCACACAGTCTG-1_CD4i_R2L45',
 'GATTAGTCATCATCACACTACTCA-1_CD4i_R2L44',
 'GATTAGTCATCATCACACTACTCA-1_CD4i_R2L45',
 'GATTAGTCATCATCACACTACTCA-1_CD4i_R2L46',
 'GATTAGTCATCATCACAGAGGCAA-1_CD4i_R2L39',
 'GATTAGTCATCATCACAGTGAGTG-1_CD4i_R2L34',
 'GATTAGTCATCATCACAGTGAGTG-1_CD4i_R2L41',
 'GATTAGTCATCATGCTACTACTCA-1_CD4i_R2L30',
 'GATTAGTCATCATGCTACTACTCA-1_CD4i_R2L31',
 'GATTAGTCATCATGTCACAGTCTG-1_CD4i_R2L47',
 'GATTAGTCATCATGTCACTACTCA-1_CD4i_R2L34',
 'GATTAGTCATCATGTCAGAGGCAA-1_CD4i_R2L47',
 'GATTAGTCATCCAAGAACAGTCTG-1_CD4i_R2L43',
 'GATTAGTCATCCAAGAACTACTCA-1_CD4i_R2L43',
 'GATTAGTCATCCACCAACAGTCTG-1_CD4i_R2L26',
 'GATTAGTCATCCACCAACTACTCA-1_CD4i_R2L45',
 'GATTAGTCATCCACCAAGAGGCAA-1_CD4i_R2L45',
 'GATTAGTCATCCACCAAGTGAGTG-1_CD4i_R2L45',
 'GATTAGTCATCCCAATACAGTCTG-1_CD4i_R2L28',
 'GATTAGTCATCCCAATACTACTCA-1_CD4i_R2L41',
 'GATTAGTCATCCCAATAGTGAGTG-1_CD4i_R2L29',
 'GATTAGTCATCCCTCTACTACTCA-1_CD4i_R2L40',
 'GATTAGTCATCCGCTAACAGTCTG-1_CD4i_R2L28',
 'GATTAGTCATCCGCTAACTACTCA-1_CD4i_R2L28',
 'GATTAGTCATCCGCTAAGAGGCAA-1_CD4i_R2L28',
 'GATTAGTCATCCGCTAAGTGAGTG-1_CD4i_R2L28',
 'GATTAGTCATCCGTCAAGAGGCAA-1_CD4i_R2L42',
 'GATTAGTCATCCGTCAAGTGAGTG-1_CD4i_R2L26',
 'GATTAGTCATCCTTGGACTACTCA-1_CD4i_R2L46',
 'GATTAGTCATCGAACAACAGTCTG-1_CD4i_R2L25',
 'GATTAGTCATCGAACAACAGTCTG-1_CD4i_R2L27',
 'GATTAGTCATCGAACAACAGTCTG-1_CD4i_R2L40',
 'GATTAGTCATCGAACAAGTGAGTG-1_CD4i_R2L27',
 'GATTAGTCATCGATAGACAGTCTG-1_CD4i_R2L29',
 'GATTAGTCATCGATAGACAGTCTG-1_CD4i_R2L33',
 'GATTAGTCATCGATAGAGAGGCAA-1_CD4i_R2L25',
 'GATTAGTCATCGATAGAGAGGCAA-1_CD4i_R2L33',
 'GATTAGTCATCGATAGAGTGAGTG-1_CD4i_R2L29',
 'GATTAGTCATCGGGCAAGAGGCAA-1_CD4i_R2L48',
 'GATTAGTCATCGGGCAAGTGAGTG-1_CD4i_R2L48',
 'GATTAGTCATCGTTCGACAGTCTG-1_CD4i_R2L39',
 'GATTAGTCATCGTTCGACTACTCA-1_CD4i_R2L39',
 'GATTAGTCATCTATCAACAGTCTG-1_CD4i_R2L30',
 'GATTAGTCATCTATCAACTACTCA-1_CD4i_R2L30',
 'GATTAGTCATCTATCAAGAGGCAA-1_CD4i_R2L41',
 'GATTAGTCATCTATCAAGTGAGTG-1_CD4i_R2L40',
 'GATTAGTCATCTATGCACAGTCTG-1_CD4i_R2L36',
 'GATTAGTCATCTATGCAGAGGCAA-1_CD4i_R2L30',
 'GATTAGTCATCTATGCAGAGGCAA-1_CD4i_R2L33',
 'GATTAGTCATCTATGCAGAGGCAA-1_CD4i_R2L36',
 'GATTAGTCATCTATGCAGAGGCAA-1_CD4i_R2L46',
 'GATTAGTCATGAAGCCACAGTCTG-1_CD4i_R2L31',
 'GATTAGTCATGAAGCCACAGTCTG-1_CD4i_R2L46',
 'GATTAGTCATGAAGCCACTACTCA-1_CD4i_R2L35',
 'GATTAGTCATGACCAAACAGTCTG-1_CD4i_R2L34',
 'GATTAGTCATGACCAAAGTGAGTG-1_CD4i_R2L26',
 'GATTAGTCATGACCAAAGTGAGTG-1_CD4i_R2L34',
 'GATTAGTCATGAGCTAACAGTCTG-1_CD4i_R2L42',
 'GATTAGTCATGAGCTAACTACTCA-1_CD4i_R2L37',
 'GATTAGTCATGAGCTAAGAGGCAA-1_CD4i_R2L33',
 'GATTAGTCATGAGCTAAGTGAGTG-1_CD4i_R2L42',
 'GATTAGTCATGCAATGACTACTCA-1_CD4i_R2L25',
 'GATTAGTCATGCAATGAGAGGCAA-1_CD4i_R2L25',
 'GATTAGTCATGCAATGAGTGAGTG-1_CD4i_R2L31',
 'GATTAGTCATGCCTCAACTACTCA-1_CD4i_R2L47',
 'GATTAGTCATGCGCAGACTACTCA-1_CD4i_R2L26',
 'GATTAGTCATGCGCAGACTACTCA-1_CD4i_R2L29',
 'GATTAGTCATGCGCAGAGTGAGTG-1_CD4i_R2L26',
 'GATTAGTCATGCGCCTACAGTCTG-1_CD4i_R2L31',
 'GATTAGTCATGCGCCTACAGTCTG-1_CD4i_R2L46',
 'GATTAGTCATGCGCCTACTACTCA-1_CD4i_R2L30',
 'GATTAGTCATGCGCCTAGAGGCAA-1_CD4i_R2L28',
 'GATTAGTCATGCGCCTAGAGGCAA-1_CD4i_R2L46',
 'GATTAGTCATGCGCCTAGTGAGTG-1_CD4i_R2L38',
 'GATTAGTCATGCGGATACTACTCA-1_CD4i_R2L44',
 'GATTAGTCATGCGGATAGAGGCAA-1_CD4i_R2L31',
 'GATTAGTCATGCTCCAACAGTCTG-1_CD4i_R2L33',
 'GATTAGTCATGCTCCAAGTGAGTG-1_CD4i_R2L42',
 'GATTAGTCATGGATTGACAGTCTG-1_CD4i_R2L39',
 'GATTAGTCATGGCCGAACTACTCA-1_CD4i_R2L27',
 'GATTAGTCATGGCCGAAGTGAGTG-1_CD4i_R2L28',
 'GATTAGTCATGGCGCAACAGTCTG-1_CD4i_R2L28',
 'GATTAGTCATGGCGCAACAGTCTG-1_CD4i_R2L29',
 'GATTAGTCATGGCGCAACAGTCTG-1_CD4i_R2L47',
 'GATTAGTCATGGCGCAAGAGGCAA-1_CD4i_R2L36',
 'GATTAGTCATGGCGCAAGAGGCAA-1_CD4i_R2L47',
 'GATTAGTCATGGCGCAAGTGAGTG-1_CD4i_R2L47',
 'GATTAGTCATGGCTAAACAGTCTG-1_CD4i_R2L34',
 'GATTAGTCATGGCTAAACTACTCA-1_CD4i_R2L34',
 'GATTAGTCATGGCTAAAGAGGCAA-1_CD4i_R2L42',
 'GATTAGTCATGGCTTTACTACTCA-1_CD4i_R2L39',
 'GATTAGTCATGGCTTTAGTGAGTG-1_CD4i_R2L28',
 'GATTAGTCATGGCTTTAGTGAGTG-1_CD4i_R2L39',
 'GATTAGTCATGGGTTAACTACTCA-1_CD4i_R2L48',
 'GATTAGTCATGGTCAAACAGTCTG-1_CD4i_R2L46',
 'GATTAGTCATGGTCAAACTACTCA-1_CD4i_R2L30',
 'GATTAGTCATGTGGCGACTACTCA-1_CD4i_R2L38',
 'GATTAGTCATGTGGCGAGTGAGTG-1_CD4i_R2L28',
 'GATTAGTCATGTGGGTACTACTCA-1_CD4i_R2L36',
 'GATTAGTCATGTGGGTAGAGGCAA-1_CD4i_R2L25',
 'GATTAGTCATGTGGGTAGAGGCAA-1_CD4i_R2L41',
 'GATTAGTCATGTTTCAAGTGAGTG-1_CD4i_R2L37',
 'GATTAGTCATTACACCACTACTCA-1_CD4i_R2L38',
 'GATTAGTCATTACACCAGAGGCAA-1_CD4i_R2L38',
 'GATTAGTCATTACTCAAGTGAGTG-1_CD4i_R2L31',
 'GATTAGTCATTACTTGACTACTCA-1_CD4i_R2L41',
 'GATTAGTCATTACTTGAGAGGCAA-1_CD4i_R2L29',
 'GATTAGTCATTACTTGAGAGGCAA-1_CD4i_R2L48',
 'GATTAGTCATTACTTGAGTGAGTG-1_CD4i_R2L44',
 'GATTAGTCATTACTTGAGTGAGTG-1_CD4i_R2L45',
 'GATTAGTCATTACTTGAGTGAGTG-1_CD4i_R2L48',
 'GATTAGTCATTAGCGAACTACTCA-1_CD4i_R2L38',
 'GATTAGTCATTAGCGAAGAGGCAA-1_CD4i_R2L42',
 'GATTAGTCATTAGCGAAGTGAGTG-1_CD4i_R2L38',
 'GATTAGTCATTAGCGAAGTGAGTG-1_CD4i_R2L42',
 'GATTAGTCATTAGTGGACTACTCA-1_CD4i_R2L36',
 'GATTAGTCATTAGTGGAGAGGCAA-1_CD4i_R2L25',
 'GATTAGTCATTAGTGGAGTGAGTG-1_CD4i_R2L25',
 'GATTAGTCATTAGTGGAGTGAGTG-1_CD4i_R2L33',
 'GATTAGTCATTCAACCACAGTCTG-1_CD4i_R2L37',
 'GATTAGTCATTCAACCACTACTCA-1_CD4i_R2L39',
 'GATTAGTCATTCAACCACTACTCA-1_CD4i_R2L46',
 'GATTAGTCATTCAACCAGAGGCAA-1_CD4i_R2L46',
 'GATTAGTCATTCAACCAGTGAGTG-1_CD4i_R2L46',
 'GATTAGTCATTCAGGAACAGTCTG-1_CD4i_R2L29',
 'GATTAGTCATTCAGGAACTACTCA-1_CD4i_R2L25',
 'GATTAGTCATTCAGGAAGTGAGTG-1_CD4i_R2L36',
 'GATTAGTCATTCATGCACTACTCA-1_CD4i_R2L35',
 'GATTAGTCATTCATGCAGTGAGTG-1_CD4i_R2L35',
 'GATTAGTCATTCCTGGAGAGGCAA-1_CD4i_R2L30',
 'GATTAGTCATTCCTTTAGAGGCAA-1_CD4i_R2L27',
 'GATTAGTCATTCCTTTAGAGGCAA-1_CD4i_R2L44',
 'GATTAGTCATTCGGTTACAGTCTG-1_CD4i_R2L27',
 'GATTAGTCATTCGGTTAGTGAGTG-1_CD4i_R2L28',
 'GATTAGTCATTCTGTAACAGTCTG-1_CD4i_R2L26',
 'GATTAGTCATTCTGTAACTACTCA-1_CD4i_R2L39',
 'GATTAGTCATTCTGTAACTACTCA-1_CD4i_R2L44',
 'GATTAGTCATTCTGTAAGTGAGTG-1_CD4i_R2L48',
 'GATTAGTCATTGAACGAGTGAGTG-1_CD4i_R2L44',
 'GATTAGTCATTGAAGTAGAGGCAA-1_CD4i_R2L39',
 'GATTAGTCATTGAAGTAGAGGCAA-1_CD4i_R2L43',
 'GATTAGTCATTGAAGTAGTGAGTG-1_CD4i_R2L44',
 'GATTAGTCATTGACTCACAGTCTG-1_CD4i_R2L30',
 'GATTAGTCATTGACTCACAGTCTG-1_CD4i_R2L43',
 'GATTAGTCATTGACTCAGAGGCAA-1_CD4i_R2L30',
 'GATTAGTCATTGAGATACAGTCTG-1_CD4i_R2L47',
 'GATTAGTCATTGAGATACTACTCA-1_CD4i_R2L28',
 'GATTAGTCATTGCATCACAGTCTG-1_CD4i_R2L27',
 'GATTAGTCATTGCATCACTACTCA-1_CD4i_R2L27',
 'GATTAGTCATTGCCCAACAGTCTG-1_CD4i_R2L37',
 'GATTAGTCATTGCCCAACAGTCTG-1_CD4i_R2L39',
 'GATTAGTCATTGCCCAACTACTCA-1_CD4i_R2L31',
 'GATTAGTCATTGCCCAAGAGGCAA-1_CD4i_R2L28',
 'GATTAGTCATTGCCCAAGAGGCAA-1_CD4i_R2L39',
 'GATTAGTCATTGCGCCACAGTCTG-1_CD4i_R2L42',
 'GATTAGTCATTGCGCCACTACTCA-1_CD4i_R2L25',
 'GATTAGTCATTGCGCCACTACTCA-1_CD4i_R2L42',
 'GATTAGTCATTGCGCCAGAGGCAA-1_CD4i_R2L45',
 'GATTAGTCATTGCGCCAGTGAGTG-1_CD4i_R2L41',
 'GATTAGTCATTGCGCCAGTGAGTG-1_CD4i_R2L45',
 'GATTAGTCATTGGACAACAGTCTG-1_CD4i_R2L43',
 'GATTAGTCATTGGGTAACTACTCA-1_CD4i_R2L32',
 'GATTAGTCATTGGGTAACTACTCA-1_CD4i_R2L34',
 'GATTAGTCATTGGGTAAGAGGCAA-1_CD4i_R2L38',
 'GATTAGTCATTGGGTAAGTGAGTG-1_CD4i_R2L25',
 'GATTAGTCATTGGGTAAGTGAGTG-1_CD4i_R2L45',
 'GATTAGTCATTGTACCACAGTCTG-1_CD4i_R2L33',
 'GATTAGTCATTGTACCAGAGGCAA-1_CD4i_R2L33',
 'GATTAGTCATTGTACCAGTGAGTG-1_CD4i_R2L43',
 'GATTAGTCATTGTGAGACTACTCA-1_CD4i_R2L31',
 'GATTAGTCATTGTGAGACTACTCA-1_CD4i_R2L32',
 'GATTAGTCATTGTGAGACTACTCA-1_CD4i_R2L44',
 'GATTAGTCATTGTGAGAGAGGCAA-1_CD4i_R2L31',
 'GATTAGTCATTGTGAGAGAGGCAA-1_CD4i_R2L32',
 'GATTAGTCATTGTGAGAGTGAGTG-1_CD4i_R2L43',
 'GATTAGTCATTGTGAGAGTGAGTG-1_CD4i_R2L44',
 'GATTAGTCATTTAGCCACTACTCA-1_CD4i_R2L36',
 'GATTAGTCATTTAGCCAGAGGCAA-1_CD4i_R2L27',
 'GATTAGTCATTTATCGACAGTCTG-1_CD4i_R2L44',
 'GATTAGTCATTTATCGACTACTCA-1_CD4i_R2L48',
 'GATTAGTCATTTCGACAGAGGCAA-1_CD4i_R2L35',
 'GATTAGTCATTTCGACAGTGAGTG-1_CD4i_R2L35',
 'GATTAGTCATTTCGACAGTGAGTG-1_CD4i_R2L42',
 'GATTAGTCATTTCGCGACTACTCA-1_CD4i_R2L35',
 'GATTAGTCATTTCGCGAGTGAGTG-1_CD4i_R2L48',
 'GATTAGTCATTTCTTCACAGTCTG-1_CD4i_R2L38',
 'GATTAGTCATTTGCTAAGAGGCAA-1_CD4i_R2L46',
 'GATTAGTCATTTGCTAAGTGAGTG-1_CD4i_R2L46',
 'GATTAGTCATTTGGAGACAGTCTG-1_CD4i_R2L25',
 'GATTAGTCATTTGGAGACTACTCA-1_CD4i_R2L25',
 'GATTAGTCATTTGGAGACTACTCA-1_CD4i_R2L26',
 'GATTAGTCATTTGGAGACTACTCA-1_CD4i_R2L37',
 'GATTAGTCATTTGGAGACTACTCA-1_CD4i_R2L41',
 'GATTAGTCATTTGGAGAGAGGCAA-1_CD4i_R2L26',
 'GATTAGTCATTTGGAGAGTGAGTG-1_CD4i_R2L33',
 'GATTAGTCATTTGGAGAGTGAGTG-1_CD4i_R2L37',
 'GATTAGTCATTTGGCTACTACTCA-1_CD4i_R2L32',
 'GATTAGTCATTTGGCTACTACTCA-1_CD4i_R2L34',
 'GATTAGTCATTTGGCTACTACTCA-1_CD4i_R2L35',
 'GATTAGTCATTTGGCTACTACTCA-1_CD4i_R2L40',
 'GATTAGTCATTTGGCTACTACTCA-1_CD4i_R2L44',
 'GATTAGTCATTTGGCTAGTGAGTG-1_CD4i_R2L34',
 'GATTAGTCATTTGGGAACTACTCA-1_CD4i_R2L41',
 'GATTAGTCATTTGGGAAGAGGCAA-1_CD4i_R2L41',
 'GATTAGTCATTTGTTGACAGTCTG-1_CD4i_R2L35',
 'GATTATCTCAAACCAAACTACTCA-1_CD4i_R2L29',
 'GATTATCTCAAACCAAAGAGGCAA-1_CD4i_R2L28',
 'GATTATCTCAAACCAAAGTGAGTG-1_CD4i_R2L40',
 'GATTATCTCAAACCAAAGTGAGTG-1_CD4i_R2L45',
 'GATTATCTCAAACCGGACAGTCTG-1_CD4i_R2L33',
 'GATTATCTCAAACTTCAGAGGCAA-1_CD4i_R2L26',
 'GATTATCTCAAACTTCAGAGGCAA-1_CD4i_R2L32',
 'GATTATCTCAAACTTCAGAGGCAA-1_CD4i_R2L42',
 'GATTATCTCAAAGGCTACAGTCTG-1_CD4i_R2L38',
 'GATTATCTCAAAGGCTAGAGGCAA-1_CD4i_R2L48',
 'GATTATCTCAAAGGCTAGTGAGTG-1_CD4i_R2L39',
 'GATTATCTCAAAGGCTAGTGAGTG-1_CD4i_R2L40',
 'GATTATCTCAAAGGCTAGTGAGTG-1_CD4i_R2L47',
 'GATTATCTCAAAGGGAACAGTCTG-1_CD4i_R2L39',
 'GATTATCTCAAAGGGAACTACTCA-1_CD4i_R2L39',
 'GATTATCTCAAAGGGAACTACTCA-1_CD4i_R2L40',
 'GATTATCTCAAAGGGAAGAGGCAA-1_CD4i_R2L47',
 'GATTATCTCAAAGGGAAGTGAGTG-1_CD4i_R2L40',
 'GATTATCTCAACATTCACAGTCTG-1_CD4i_R2L37',
 'GATTATCTCAACATTCACTACTCA-1_CD4i_R2L37',
 'GATTATCTCAACATTCAGAGGCAA-1_CD4i_R2L28',
 'GATTATCTCAACATTCAGTGAGTG-1_CD4i_R2L44',
 'GATTATCTCAACCAAAACAGTCTG-1_CD4i_R2L37',
 'GATTATCTCAACCAAAACAGTCTG-1_CD4i_R2L42',
 'GATTATCTCAACCAAAAGAGGCAA-1_CD4i_R2L38',
 'GATTATCTCAACCAAAAGTGAGTG-1_CD4i_R2L37',
 'GATTATCTCAACCAAAAGTGAGTG-1_CD4i_R2L45',
 'GATTATCTCAACCGCTACTACTCA-1_CD4i_R2L27',
 'GATTATCTCAACCGCTAGAGGCAA-1_CD4i_R2L32',
 'GATTATCTCAACCGCTAGAGGCAA-1_CD4i_R2L33',
 'GATTATCTCAACCGCTAGTGAGTG-1_CD4i_R2L32',
 'GATTATCTCAACCGGAACAGTCTG-1_CD4i_R2L46',
 'GATTATCTCAACCTATACTACTCA-1_CD4i_R2L27',
 'GATTATCTCAACCTATAGAGGCAA-1_CD4i_R2L45',
 'GATTATCTCAACCTATAGTGAGTG-1_CD4i_R2L35',
 'GATTATCTCAACCTCAACAGTCTG-1_CD4i_R2L33',
 'GATTATCTCAACCTCAACAGTCTG-1_CD4i_R2L43',
 'GATTATCTCAACCTCAAGAGGCAA-1_CD4i_R2L37',
 'GATTATCTCAACCTCAAGAGGCAA-1_CD4i_R2L40',
 'GATTATCTCAACCTCAAGTGAGTG-1_CD4i_R2L27',
 'GATTATCTCAACCTCAAGTGAGTG-1_CD4i_R2L33',
 'GATTATCTCAACTGTTACAGTCTG-1_CD4i_R2L43',
 'GATTATCTCAACTGTTAGAGGCAA-1_CD4i_R2L28',
 'GATTATCTCAACTTGTACAGTCTG-1_CD4i_R2L29',
 'GATTATCTCAAGATGCACAGTCTG-1_CD4i_R2L39',
 'GATTATCTCAAGATGCACAGTCTG-1_CD4i_R2L40',
 'GATTATCTCAAGATGCACAGTCTG-1_CD4i_R2L44',
 'GATTATCTCAAGATGCACTACTCA-1_CD4i_R2L46',
 'GATTATCTCAAGATGCAGAGGCAA-1_CD4i_R2L30',
 'GATTATCTCAAGATGCAGTGAGTG-1_CD4i_R2L30',
 'GATTATCTCAAGATGCAGTGAGTG-1_CD4i_R2L46',
 'GATTATCTCAAGCCAGACAGTCTG-1_CD4i_R2L45',
 'GATTATCTCAAGCCAGAGTGAGTG-1_CD4i_R2L48',
 'GATTATCTCAAGCGATACTACTCA-1_CD4i_R2L36',
 'GATTATCTCAAGCGATACTACTCA-1_CD4i_R2L48',
 'GATTATCTCAAGCTCCAGTGAGTG-1_CD4i_R2L46',
 'GATTATCTCAAGGGCCACTACTCA-1_CD4i_R2L36',
 'GATTATCTCAAGGGCCAGTGAGTG-1_CD4i_R2L36',
 'GATTATCTCAAGGGTTACAGTCTG-1_CD4i_R2L35',
 'GATTATCTCAAGGGTTACTACTCA-1_CD4i_R2L35',
 'GATTATCTCAAGGGTTAGAGGCAA-1_CD4i_R2L37',
 'GATTATCTCAAGGGTTAGAGGCAA-1_CD4i_R2L47',
 'GATTATCTCAAGTTAGAGTGAGTG-1_CD4i_R2L33',
 'GATTATCTCAAGTTTCACAGTCTG-1_CD4i_R2L29',
 'GATTATCTCAAGTTTCACAGTCTG-1_CD4i_R2L35',
 'GATTATCTCAAGTTTCACTACTCA-1_CD4i_R2L30',
 'GATTATCTCAAGTTTCAGTGAGTG-1_CD4i_R2L35',
 'GATTATCTCAAGTTTCAGTGAGTG-1_CD4i_R2L42',
 'GATTATCTCAATACAGACTACTCA-1_CD4i_R2L30',
 'GATTATCTCAATACAGAGAGGCAA-1_CD4i_R2L37',
 'GATTATCTCAATCCTGAGTGAGTG-1_CD4i_R2L48',
 'GATTATCTCAATCGCCACTACTCA-1_CD4i_R2L30',
 'GATTATCTCAATCGCCACTACTCA-1_CD4i_R2L39',
 'GATTATCTCAATCGCCACTACTCA-1_CD4i_R2L41',
 'GATTATCTCAATCGCCAGAGGCAA-1_CD4i_R2L41',
 'GATTATCTCAATCGCCAGAGGCAA-1_CD4i_R2L46',
 'GATTATCTCAATCGCCAGTGAGTG-1_CD4i_R2L29',
 'GATTATCTCAATCGCCAGTGAGTG-1_CD4i_R2L39',
 'GATTATCTCAATGGGTACAGTCTG-1_CD4i_R2L48',
 'GATTATCTCAATGGGTAGTGAGTG-1_CD4i_R2L34',
 'GATTATCTCAATGGGTAGTGAGTG-1_CD4i_R2L48',
 'GATTATCTCAATGTGAACAGTCTG-1_CD4i_R2L44',
 'GATTATCTCAATGTGAACTACTCA-1_CD4i_R2L35',
 'GATTATCTCAATGTGAACTACTCA-1_CD4i_R2L39',
 'GATTATCTCAATGTGAAGAGGCAA-1_CD4i_R2L30',
 'GATTATCTCAATGTGAAGAGGCAA-1_CD4i_R2L32',
 'GATTATCTCAATGTGAAGAGGCAA-1_CD4i_R2L36',
 'GATTATCTCAATGTGAAGTGAGTG-1_CD4i_R2L29',
 'GATTATCTCAATGTGAAGTGAGTG-1_CD4i_R2L30',
 'GATTATCTCAATGTGAAGTGAGTG-1_CD4i_R2L44',
 'GATTATCTCAATGTTCACAGTCTG-1_CD4i_R2L33',
 'GATTATCTCAATGTTCACAGTCTG-1_CD4i_R2L35',
 'GATTATCTCAATGTTCACTACTCA-1_CD4i_R2L33',
 'GATTATCTCAATGTTCACTACTCA-1_CD4i_R2L35',
 'GATTATCTCAATGTTCAGTGAGTG-1_CD4i_R2L36',
 'GATTATCTCAATGTTCAGTGAGTG-1_CD4i_R2L43',
 'GATTATCTCAATTGGAACTACTCA-1_CD4i_R2L46',
 'GATTATCTCAATTTGCACAGTCTG-1_CD4i_R2L42',
 'GATTATCTCAATTTGCACTACTCA-1_CD4i_R2L27',
 'GATTATCTCAATTTGCAGAGGCAA-1_CD4i_R2L30',
 'GATTATCTCAATTTGCAGTGAGTG-1_CD4i_R2L30',
 'GATTATCTCACAAAGCACAGTCTG-1_CD4i_R2L31',
 'GATTATCTCACAAAGCACTACTCA-1_CD4i_R2L31',
 'GATTATCTCACAAAGCACTACTCA-1_CD4i_R2L39',
 'GATTATCTCACAAAGCAGAGGCAA-1_CD4i_R2L30',
 'GATTATCTCACAAAGCAGAGGCAA-1_CD4i_R2L38',
 'GATTATCTCACAAATGACAGTCTG-1_CD4i_R2L38',
 'GATTATCTCACAAATGACAGTCTG-1_CD4i_R2L44',
 'GATTATCTCACAAATGAGAGGCAA-1_CD4i_R2L25',
 'GATTATCTCACAAATGAGTGAGTG-1_CD4i_R2L25',
 'GATTATCTCACAAATGAGTGAGTG-1_CD4i_R2L35',
 'GATTATCTCACAACAAACAGTCTG-1_CD4i_R2L26',
 'GATTATCTCACAACAAACAGTCTG-1_CD4i_R2L46',
 'GATTATCTCACAACAAAGAGGCAA-1_CD4i_R2L41',
 'GATTATCTCACAACAAAGTGAGTG-1_CD4i_R2L41',
 'GATTATCTCACAAGCGAGTGAGTG-1_CD4i_R2L33',
 'GATTATCTCACAATGAACAGTCTG-1_CD4i_R2L29',
 'GATTATCTCACAATGAAGAGGCAA-1_CD4i_R2L29',
 'GATTATCTCACAATGAAGTGAGTG-1_CD4i_R2L45',
 'GATTATCTCACACAAAACTACTCA-1_CD4i_R2L41',
 'GATTATCTCACACAAAAGAGGCAA-1_CD4i_R2L27',
 'GATTATCTCACACAAAAGAGGCAA-1_CD4i_R2L39',
 'GATTATCTCACACAAAAGTGAGTG-1_CD4i_R2L27',
 'GATTATCTCACACAAAAGTGAGTG-1_CD4i_R2L41',
 'GATTATCTCACAGCCTACAGTCTG-1_CD4i_R2L43',
 'GATTATCTCACAGCCTACTACTCA-1_CD4i_R2L43',
 'GATTATCTCACAGCCTAGAGGCAA-1_CD4i_R2L33',
 'GATTATCTCACAGCCTAGTGAGTG-1_CD4i_R2L29',
 'GATTATCTCACAGGATACAGTCTG-1_CD4i_R2L48',
 'GATTATCTCACAGGATAGAGGCAA-1_CD4i_R2L38',
 'GATTATCTCACAGGATAGTGAGTG-1_CD4i_R2L38',
 'GATTATCTCACAGGGCACAGTCTG-1_CD4i_R2L25',
 'GATTATCTCACAGGGCACTACTCA-1_CD4i_R2L25',
 'GATTATCTCACAGGGCACTACTCA-1_CD4i_R2L45',
 'GATTATCTCACAGGGCAGTGAGTG-1_CD4i_R2L39',
 'GATTATCTCACATTACAGAGGCAA-1_CD4i_R2L46',
 'GATTATCTCACATTCGAGAGGCAA-1_CD4i_R2L30',
 'GATTATCTCACATTCGAGAGGCAA-1_CD4i_R2L47',
 'GATTATCTCACATTCGAGTGAGTG-1_CD4i_R2L47',
 'GATTATCTCACCACACACTACTCA-1_CD4i_R2L34',
 'GATTATCTCACCACACAGAGGCAA-1_CD4i_R2L44',
 'GATTATCTCACCACACAGTGAGTG-1_CD4i_R2L34',
 'GATTATCTCACCAGCTACTACTCA-1_CD4i_R2L26',
 'GATTATCTCACCAGCTACTACTCA-1_CD4i_R2L33',
 'GATTATCTCACCAGGAACAGTCTG-1_CD4i_R2L29',
 'GATTATCTCACCAGGAACTACTCA-1_CD4i_R2L33',
 'GATTATCTCACCAGGAAGTGAGTG-1_CD4i_R2L29',
 'GATTATCTCACCAGGAAGTGAGTG-1_CD4i_R2L31',
 'GATTATCTCACCAGGAAGTGAGTG-1_CD4i_R2L46',
 'GATTATCTCACCATATACAGTCTG-1_CD4i_R2L41',
 'GATTATCTCACCATATACAGTCTG-1_CD4i_R2L47',
 'GATTATCTCACCATATACTACTCA-1_CD4i_R2L26',
 'GATTATCTCACCATATAGAGGCAA-1_CD4i_R2L47',
 'GATTATCTCACCATATAGTGAGTG-1_CD4i_R2L47',
 'GATTATCTCACCATATAGTGAGTG-1_CD4i_R2L48',
 'GATTATCTCACCCTGGACAGTCTG-1_CD4i_R2L25',
 'GATTATCTCACCCTGGAGAGGCAA-1_CD4i_R2L25',
 'GATTATCTCACCTAATACAGTCTG-1_CD4i_R2L27',
 'GATTATCTCACCTGTAACAGTCTG-1_CD4i_R2L26',
 'GATTATCTCACCTGTAAGTGAGTG-1_CD4i_R2L37',
 'GATTATCTCACCTTTCACAGTCTG-1_CD4i_R2L32',
 'GATTATCTCACCTTTCACAGTCTG-1_CD4i_R2L42',
 'GATTATCTCACCTTTCACTACTCA-1_CD4i_R2L32',
 'GATTATCTCACCTTTCAGAGGCAA-1_CD4i_R2L33',
 'GATTATCTCACCTTTCAGAGGCAA-1_CD4i_R2L43',
 'GATTATCTCACCTTTCAGTGAGTG-1_CD4i_R2L25',
 'GATTATCTCACCTTTCAGTGAGTG-1_CD4i_R2L32',
 'GATTATCTCACGAACGACAGTCTG-1_CD4i_R2L26',
 'GATTATCTCACGAACGACAGTCTG-1_CD4i_R2L30',
 'GATTATCTCACGAACGACAGTCTG-1_CD4i_R2L45',
 'GATTATCTCACGAACGACTACTCA-1_CD4i_R2L47',
 'GATTATCTCACGAACGAGAGGCAA-1_CD4i_R2L26',
 'GATTATCTCACGAACGAGAGGCAA-1_CD4i_R2L30',
 'GATTATCTCACGAACGAGAGGCAA-1_CD4i_R2L35',
 'GATTATCTCACGGACAAGAGGCAA-1_CD4i_R2L40',
 'GATTATCTCACGGACAAGTGAGTG-1_CD4i_R2L40',
 'GATTATCTCACGGACAAGTGAGTG-1_CD4i_R2L42',
 'GATTATCTCACGTTATACAGTCTG-1_CD4i_R2L33',
 'GATTATCTCACGTTATACAGTCTG-1_CD4i_R2L47',
 'GATTATCTCACGTTATACTACTCA-1_CD4i_R2L25',
 'GATTATCTCACGTTATACTACTCA-1_CD4i_R2L33',
 'GATTATCTCACGTTATAGAGGCAA-1_CD4i_R2L34',
 'GATTATCTCACGTTATAGTGAGTG-1_CD4i_R2L30',
 'GATTATCTCACGTTCAACAGTCTG-1_CD4i_R2L36',
 'GATTATCTCACGTTCAACAGTCTG-1_CD4i_R2L43',
 'GATTATCTCACGTTCAAGAGGCAA-1_CD4i_R2L36',
 'GATTATCTCACTAATCACAGTCTG-1_CD4i_R2L28',
 'GATTATCTCACTAATCAGAGGCAA-1_CD4i_R2L27',
 'GATTATCTCACTAATCAGTGAGTG-1_CD4i_R2L31',
 'GATTATCTCACTAATCAGTGAGTG-1_CD4i_R2L34',
 'GATTATCTCACTAGGGACAGTCTG-1_CD4i_R2L45',
 'GATTATCTCACTAGGGAGAGGCAA-1_CD4i_R2L29',
 'GATTATCTCACTAGGGAGAGGCAA-1_CD4i_R2L45',
 'GATTATCTCACTATACACTACTCA-1_CD4i_R2L45',
 'GATTATCTCACTATACAGTGAGTG-1_CD4i_R2L46',
 'GATTATCTCACTATGTAGAGGCAA-1_CD4i_R2L41',
 'GATTATCTCACTCGCGAGTGAGTG-1_CD4i_R2L31',
 'GATTATCTCACTGTCAACTACTCA-1_CD4i_R2L33',
 'GATTATCTCACTGTCAACTACTCA-1_CD4i_R2L44',
 'GATTATCTCACTGTCAAGTGAGTG-1_CD4i_R2L33',
 'GATTATCTCACTTCGAACAGTCTG-1_CD4i_R2L26',
 'GATTATCTCACTTCGAACTACTCA-1_CD4i_R2L43',
 'GATTATCTCACTTCGAAGAGGCAA-1_CD4i_R2L26',
 'GATTATCTCACTTCGAAGAGGCAA-1_CD4i_R2L43',
 'GATTATCTCACTTCGAAGTGAGTG-1_CD4i_R2L29',
 'GATTATCTCAGCACAGACAGTCTG-1_CD4i_R2L38',
 'GATTATCTCAGCACAGACTACTCA-1_CD4i_R2L38',
 'GATTATCTCAGCACAGAGAGGCAA-1_CD4i_R2L38',
 'GATTATCTCAGCACCTACAGTCTG-1_CD4i_R2L39',
 'GATTATCTCAGCACCTACTACTCA-1_CD4i_R2L34',
 'GATTATCTCAGCACGAACAGTCTG-1_CD4i_R2L33',
 'GATTATCTCAGCACGAACAGTCTG-1_CD4i_R2L35',
 'GATTATCTCAGCACGAACAGTCTG-1_CD4i_R2L39',
 'GATTATCTCAGCACGAACTACTCA-1_CD4i_R2L32',
 'GATTATCTCAGCACGAACTACTCA-1_CD4i_R2L33',
 'GATTATCTCAGCACGAAGTGAGTG-1_CD4i_R2L28',
 'GATTATCTCAGCACGAAGTGAGTG-1_CD4i_R2L39',
 'GATTATCTCAGCATGGACTACTCA-1_CD4i_R2L35',
 'GATTATCTCAGCCCTGACAGTCTG-1_CD4i_R2L42',
 'GATTATCTCAGCCCTGACTACTCA-1_CD4i_R2L38',
 'GATTATCTCAGCCTTAAGTGAGTG-1_CD4i_R2L39',
 'GATTATCTCAGCGAATACAGTCTG-1_CD4i_R2L42',
 'GATTATCTCAGCGAATAGTGAGTG-1_CD4i_R2L41',
 'GATTATCTCAGGCAATACAGTCTG-1_CD4i_R2L25',
 'GATTATCTCAGGCAATACAGTCTG-1_CD4i_R2L32',
 'GATTATCTCAGGCAATAGAGGCAA-1_CD4i_R2L32',
 'GATTATCTCAGGCAATAGAGGCAA-1_CD4i_R2L39',
 'GATTATCTCAGGCAATAGTGAGTG-1_CD4i_R2L32',
 'GATTATCTCAGGCAATAGTGAGTG-1_CD4i_R2L42',
 'GATTATCTCAGGCATGACAGTCTG-1_CD4i_R2L41',

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

'TATGGTGCATGACCAAACTACTCA-1_CD4i_R2L27',
 'TATGGTGCATGACCAAACTACTCA-1_CD4i_R2L40',
 'TATGGTGCATGACCAAAGTGAGTG-1_CD4i_R2L37',
 'TATGGTGCATGAGCTAACTACTCA-1_CD4i_R2L46',
 'TATGGTGCATGAGCTAACTACTCA-1_CD4i_R2L48',
 'TATGGTGCATGAGCTAAGAGGCAA-1_CD4i_R2L29',
 'TATGGTGCATGAGCTAAGAGGCAA-1_CD4i_R2L36',
 'TATGGTGCATGAGCTAAGAGGCAA-1_CD4i_R2L46',
 'TATGGTGCATGAGGGAACAGTCTG-1_CD4i_R2L33',
 'TATGGTGCATGAGGGAACTACTCA-1_CD4i_R2L33',
 'TATGGTGCATGAGGGAAGTGAGTG-1_CD4i_R2L35',
 'TATGGTGCATGAGGGAAGTGAGTG-1_CD4i_R2L48',
 'TATGGTGCATGCAATGAGTGAGTG-1_CD4i_R2L28',
 'TATGGTGCATGCAATGAGTGAGTG-1_CD4i_R2L43',
 'TATGGTGCATGCCTCAACAGTCTG-1_CD4i_R2L32',
 'TATGGTGCATGCCTCAACTACTCA-1_CD4i_R2L25',
 'TATGGTGCATGCGCAGACAGTCTG-1_CD4i_R2L45',
 'TATGGTGCATGCGCAGACTACTCA-1_CD4i_R2L28',
 'TATGGTGCATGCGCAGAGAGGCAA-1_CD4i_R2L28',
 'TATGGTGCATGCGCAGAGTGAGTG-1_CD4i_R2L28',
 'TATGGTGCATGCGCCTACAGTCTG-1_CD4i_R2L46',
 'TATGGTGCATGCGGATACAGTCTG-1_CD4i_R2L36',
 'TATGGTGCATGCGGATACTACTCA-1_CD4i_R2L35',
 'TATGGTGCATGCGGATAGAGGCAA-1_CD4i_R2L33',
 'TATGGTGCATGCGGATAGTGAGTG-1_CD4i_R2L25',
 'TATGGTGCATGCTCCAACAGTCTG-1_CD4i_R2L31',
 'TATGGTGCATGCTCCAACAGTCTG-1_CD4i_R2L33',
 'TATGGTGCATGCTCCAACTACTCA-1_CD4i_R2L37',
 'TATGGTGCATGCTCCAAGTGAGTG-1_CD4i_R2L33',
 'TATGGTGCATGGATTGACTACTCA-1_CD4i_R2L37',
 'TATGGTGCATGGATTGAGTGAGTG-1_CD4i_R2L33',
 'TATGGTGCATGGCCGAACAGTCTG-1_CD4i_R2L31',
 'TATGGTGCATGGCCGAACTACTCA-1_CD4i_R2L31',
 'TATGGTGCATGGCCGAAGTGAGTG-1_CD4i_R2L43',
 'TATGGTGCATGGCGCAACAGTCTG-1_CD4i_R2L26',
 'TATGGTGCATGGCGCAAGTGAGTG-1_CD4i_R2L26',
 'TATGGTGCATGGCGCAAGTGAGTG-1_CD4i_R2L42',
 'TATGGTGCATGGCTTTACAGTCTG-1_CD4i_R2L26',
 'TATGGTGCATGGCTTTACAGTCTG-1_CD4i_R2L38',
 'TATGGTGCATGGCTTTACAGTCTG-1_CD4i_R2L39',
 'TATGGTGCATGGCTTTACTACTCA-1_CD4i_R2L34',
 'TATGGTGCATGGCTTTACTACTCA-1_CD4i_R2L44',
 'TATGGTGCATGGCTTTAGAGGCAA-1_CD4i_R2L30',
 'TATGGTGCATGGGTTAACAGTCTG-1_CD4i_R2L30',
 'TATGGTGCATGGGTTAACTACTCA-1_CD4i_R2L31',
 'TATGGTGCATGGGTTAAGAGGCAA-1_CD4i_R2L46',
 'TATGGTGCATGGGTTAAGTGAGTG-1_CD4i_R2L48',
 'TATGGTGCATGGTCAAAGAGGCAA-1_CD4i_R2L29',
 'TATGGTGCATGGTCAAAGAGGCAA-1_CD4i_R2L30',
 'TATGGTGCATGTGGCGAGAGGCAA-1_CD4i_R2L44',
 'TATGGTGCATGTGGGTACTACTCA-1_CD4i_R2L46',
 'TATGGTGCATGTTTCAACAGTCTG-1_CD4i_R2L40',
 'TATGGTGCATGTTTCAACTACTCA-1_CD4i_R2L38',
 'TATGGTGCATTACACCACAGTCTG-1_CD4i_R2L39',
 'TATGGTGCATTACACCACTACTCA-1_CD4i_R2L28',
 'TATGGTGCATTACACCAGAGGCAA-1_CD4i_R2L28',
 'TATGGTGCATTACACCAGAGGCAA-1_CD4i_R2L39',
 'TATGGTGCATTACTCAACAGTCTG-1_CD4i_R2L45',
 'TATGGTGCATTACTCAAGAGGCAA-1_CD4i_R2L40',
 'TATGGTGCATTACTCAAGAGGCAA-1_CD4i_R2L45',
 'TATGGTGCATTACTTGACAGTCTG-1_CD4i_R2L26',
 'TATGGTGCATTACTTGACAGTCTG-1_CD4i_R2L27',
 'TATGGTGCATTACTTGAGAGGCAA-1_CD4i_R2L26',
 'TATGGTGCATTACTTGAGAGGCAA-1_CD4i_R2L47',
 'TATGGTGCATTAGCGAACAGTCTG-1_CD4i_R2L28',
 'TATGGTGCATTAGCGAACTACTCA-1_CD4i_R2L28',
 'TATGGTGCATTAGTGGACAGTCTG-1_CD4i_R2L33',
 'TATGGTGCATTAGTGGACTACTCA-1_CD4i_R2L43',
 'TATGGTGCATTAGTGGAGAGGCAA-1_CD4i_R2L38',
 'TATGGTGCATTAGTGGAGTGAGTG-1_CD4i_R2L41',
 'TATGGTGCATTAGTGGAGTGAGTG-1_CD4i_R2L47',
 'TATGGTGCATTCAACCAGTGAGTG-1_CD4i_R2L29',
 'TATGGTGCATTCAACCAGTGAGTG-1_CD4i_R2L42',
 'TATGGTGCATTCAGGAACTACTCA-1_CD4i_R2L26',
 'TATGGTGCATTCAGGAACTACTCA-1_CD4i_R2L35',
 'TATGGTGCATTCAGGAACTACTCA-1_CD4i_R2L37',
 'TATGGTGCATTCAGGAAGAGGCAA-1_CD4i_R2L37',
 'TATGGTGCATTCAGGAAGTGAGTG-1_CD4i_R2L26',
 'TATGGTGCATTCATGCACAGTCTG-1_CD4i_R2L29',
 'TATGGTGCATTCATGCACAGTCTG-1_CD4i_R2L47',
 'TATGGTGCATTCATGCACTACTCA-1_CD4i_R2L40',
 'TATGGTGCATTCATGCACTACTCA-1_CD4i_R2L47',
 'TATGGTGCATTCATGCAGAGGCAA-1_CD4i_R2L40',
 'TATGGTGCATTCCTGGACAGTCTG-1_CD4i_R2L35',
 'TATGGTGCATTCCTGGACTACTCA-1_CD4i_R2L27',
 'TATGGTGCATTCCTGGACTACTCA-1_CD4i_R2L42',
 'TATGGTGCATTCCTGGAGAGGCAA-1_CD4i_R2L35',
 'TATGGTGCATTCCTGGAGAGGCAA-1_CD4i_R2L42',
 'TATGGTGCATTCCTGGAGTGAGTG-1_CD4i_R2L42',
 'TATGGTGCATTCCTTTACAGTCTG-1_CD4i_R2L43',
 'TATGGTGCATTCCTTTAGAGGCAA-1_CD4i_R2L40',
 'TATGGTGCATTCGGTTAGAGGCAA-1_CD4i_R2L37',
 'TATGGTGCATTCTGTAACTACTCA-1_CD4i_R2L37',
 'TATGGTGCATTCTGTAAGAGGCAA-1_CD4i_R2L37',
 'TATGGTGCATTGAACGACAGTCTG-1_CD4i_R2L38',
 'TATGGTGCATTGAACGAGAGGCAA-1_CD4i_R2L38',
 'TATGGTGCATTGAAGTACAGTCTG-1_CD4i_R2L38',
 'TATGGTGCATTGAAGTACTACTCA-1_CD4i_R2L38',
 'TATGGTGCATTGAAGTAGAGGCAA-1_CD4i_R2L42',
 'TATGGTGCATTGACTCAGAGGCAA-1_CD4i_R2L26',
 'TATGGTGCATTGACTCAGAGGCAA-1_CD4i_R2L41',
 'TATGGTGCATTGAGATACTACTCA-1_CD4i_R2L36',
 'TATGGTGCATTGAGATAGAGGCAA-1_CD4i_R2L27',
 'TATGGTGCATTGAGATAGAGGCAA-1_CD4i_R2L36',
 'TATGGTGCATTGAGATAGTGAGTG-1_CD4i_R2L47',
 'TATGGTGCATTGCATCACAGTCTG-1_CD4i_R2L36',
 'TATGGTGCATTGCATCACTACTCA-1_CD4i_R2L36',
 'TATGGTGCATTGCATCAGTGAGTG-1_CD4i_R2L36',
 'TATGGTGCATTGCCGCACAGTCTG-1_CD4i_R2L29',
 'TATGGTGCATTGCCGCAGTGAGTG-1_CD4i_R2L29',
 'TATGGTGCATTGCCTGAGAGGCAA-1_CD4i_R2L30',
 'TATGGTGCATTGCCTGAGTGAGTG-1_CD4i_R2L39',
 'TATGGTGCATTGGACAACTACTCA-1_CD4i_R2L44',
 'TATGGTGCATTGGACAAGTGAGTG-1_CD4i_R2L44',
 'TATGGTGCATTGGGTAACAGTCTG-1_CD4i_R2L39',
 'TATGGTGCATTGTACCAGTGAGTG-1_CD4i_R2L39',
 'TATGGTGCATTGTGAGACTACTCA-1_CD4i_R2L43',
 'TATGGTGCATTGTGTCACTACTCA-1_CD4i_R2L44',
 'TATGGTGCATTGTGTCACTACTCA-1_CD4i_R2L45',
 'TATGGTGCATTGTGTCAGAGGCAA-1_CD4i_R2L36',
 'TATGGTGCATTGTGTCAGTGAGTG-1_CD4i_R2L41',
 'TATGGTGCATTGTGTCAGTGAGTG-1_CD4i_R2L45',
 'TATGGTGCATTTATCGACAGTCTG-1_CD4i_R2L39',
 'TATGGTGCATTTATCGACTACTCA-1_CD4i_R2L37',
 'TATGGTGCATTTATCGAGTGAGTG-1_CD4i_R2L37',
 'TATGGTGCATTTCGACACAGTCTG-1_CD4i_R2L30',
 'TATGGTGCATTTCGACACTACTCA-1_CD4i_R2L47',
 'TATGGTGCATTTCGACACTACTCA-1_CD4i_R2L48',
 'TATGGTGCATTTCGACAGAGGCAA-1_CD4i_R2L36',
 'TATGGTGCATTTCGCGACAGTCTG-1_CD4i_R2L26',
 'TATGGTGCATTTCGCGACTACTCA-1_CD4i_R2L38',
 'TATGGTGCATTTGGAGACTACTCA-1_CD4i_R2L28',
 'TATGGTGCATTTGGCTAGAGGCAA-1_CD4i_R2L29',
 'TATGGTGCATTTGGGAACAGTCTG-1_CD4i_R2L39',
 'TATGGTGCATTTGGGAAGTGAGTG-1_CD4i_R2L28',
 'TATGGTGCATTTGGGAAGTGAGTG-1_CD4i_R2L39',
 'TATGGTGCATTTGTTGACAGTCTG-1_CD4i_R2L39',
 'TATGTCCCAAACAAGAACAGTCTG-1_CD4i_R2L38',
 'TATGTCCCAAACAAGAACTACTCA-1_CD4i_R2L38',
 'TATGTCCCAAACAAGAAGTGAGTG-1_CD4i_R2L45',
 'TATGTCCCAAACAATCACTACTCA-1_CD4i_R2L30',
 'TATGTCCCAAACAATCACTACTCA-1_CD4i_R2L38',
 'TATGTCCCAAACAATCAGAGGCAA-1_CD4i_R2L38',
 'TATGTCCCAAACAATCAGTGAGTG-1_CD4i_R2L38',
 'TATGTCCCAAACACGCACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAAACACGCACTACTCA-1_CD4i_R2L41',
 'TATGTCCCAAACACGCACTACTCA-1_CD4i_R2L44',
 'TATGTCCCAAACACGCAGAGGCAA-1_CD4i_R2L27',
 'TATGTCCCAAACACGCAGTGAGTG-1_CD4i_R2L30',
 'TATGTCCCAAACACGCAGTGAGTG-1_CD4i_R2L41',
 'TATGTCCCAAACCCAAACAGTCTG-1_CD4i_R2L31',
 'TATGTCCCAAACCCAAACAGTCTG-1_CD4i_R2L37',
 'TATGTCCCAAACCCAAACTACTCA-1_CD4i_R2L48',
 'TATGTCCCAAACCCAAAGAGGCAA-1_CD4i_R2L31',
 'TATGTCCCAAACCCAAAGAGGCAA-1_CD4i_R2L35',
 'TATGTCCCAAACCCAAAGTGAGTG-1_CD4i_R2L37',
 'TATGTCCCAAACCCAAAGTGAGTG-1_CD4i_R2L48',
 'TATGTCCCAAACCGGTAGAGGCAA-1_CD4i_R2L46',
 'TATGTCCCAAACCTGAACAGTCTG-1_CD4i_R2L32',
 'TATGTCCCAAACCTGAACTACTCA-1_CD4i_R2L32',
 'TATGTCCCAAACGGGAACAGTCTG-1_CD4i_R2L28',
 'TATGTCCCAAACGGGAACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAAACGGTCACAGTCTG-1_CD4i_R2L45',
 'TATGTCCCAAACTGGCACAGTCTG-1_CD4i_R2L28',
 'TATGTCCCAAACTGGCACTACTCA-1_CD4i_R2L28',
 'TATGTCCCAAACTGGCACTACTCA-1_CD4i_R2L39',
 'TATGTCCCAAACTGGCAGAGGCAA-1_CD4i_R2L39',
 'TATGTCCCAAACTGGCAGTGAGTG-1_CD4i_R2L37',
 'TATGTCCCAAACTTCCACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAAACTTCCACTACTCA-1_CD4i_R2L32',
 'TATGTCCCAAACTTCCACTACTCA-1_CD4i_R2L42',
 'TATGTCCCAAACTTCCAGTGAGTG-1_CD4i_R2L32',
 'TATGTCCCAAACTTCCAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAAACTTGGACAGTCTG-1_CD4i_R2L37',
 'TATGTCCCAAACTTGGACAGTCTG-1_CD4i_R2L43',
 'TATGTCCCAAACTTGGAGAGGCAA-1_CD4i_R2L43',
 'TATGTCCCAAACTTGGAGTGAGTG-1_CD4i_R2L26',
 'TATGTCCCAAACTTGGAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCAAACTTGGAGTGAGTG-1_CD4i_R2L37',
 'TATGTCCCAAAGACCCACAGTCTG-1_CD4i_R2L39',
 'TATGTCCCAAAGACCCACAGTCTG-1_CD4i_R2L45',
 'TATGTCCCAAAGACCCACTACTCA-1_CD4i_R2L43',
 'TATGTCCCAAAGACCCAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAAAGCCTAACAGTCTG-1_CD4i_R2L29',
 'TATGTCCCAAAGCCTAACTACTCA-1_CD4i_R2L38',
 'TATGTCCCAAAGCCTAAGTGAGTG-1_CD4i_R2L42',
 'TATGTCCCAAAGCTCAACAGTCTG-1_CD4i_R2L28',
 'TATGTCCCAAAGCTCAACAGTCTG-1_CD4i_R2L30',
 'TATGTCCCAAAGCTCAACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAAAGCTCAACTACTCA-1_CD4i_R2L45',
 'TATGTCCCAAAGCTCAAGAGGCAA-1_CD4i_R2L35',
 'TATGTCCCAAAGGGATACAGTCTG-1_CD4i_R2L34',
 'TATGTCCCAAAGGGATACTACTCA-1_CD4i_R2L29',
 'TATGTCCCAAAGGGATAGAGGCAA-1_CD4i_R2L25',
 'TATGTCCCAAAGGGATAGAGGCAA-1_CD4i_R2L32',
 'TATGTCCCAAAGGGATAGTGAGTG-1_CD4i_R2L29',
 'TATGTCCCAAAGGTAAAGAGGCAA-1_CD4i_R2L44',
 'TATGTCCCAAAGGTAAAGTGAGTG-1_CD4i_R2L31',
 'TATGTCCCAAAGGTAAAGTGAGTG-1_CD4i_R2L37',
 'TATGTCCCAAAGTGCCAGAGGCAA-1_CD4i_R2L45',
 'TATGTCCCAAATAACCACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAAATAACCAGAGGCAA-1_CD4i_R2L38',
 'TATGTCCCAAATAACCAGTGAGTG-1_CD4i_R2L38',
 'TATGTCCCAAATAACCAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAAATAAGGAGAGGCAA-1_CD4i_R2L36',
 'TATGTCCCAAATAAGGAGAGGCAA-1_CD4i_R2L47',
 'TATGTCCCAAATAAGGAGTGAGTG-1_CD4i_R2L36',
 'TATGTCCCAAATACCGAGAGGCAA-1_CD4i_R2L28',
 'TATGTCCCAAATACCGAGTGAGTG-1_CD4i_R2L28',
 'TATGTCCCAAATACCGAGTGAGTG-1_CD4i_R2L30',
 'TATGTCCCAAATAGGAACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAAATAGGAACTACTCA-1_CD4i_R2L45',
 'TATGTCCCAAATAGGAAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAAATATGCACTACTCA-1_CD4i_R2L48',
 'TATGTCCCAAATCACGAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAAATCACGAGTGAGTG-1_CD4i_R2L47',
 'TATGTCCCAAATGACTAGAGGCAA-1_CD4i_R2L47',
 'TATGTCCCAAATGACTAGTGAGTG-1_CD4i_R2L26',
 'TATGTCCCAACAAAGAACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAACAAAGAACTACTCA-1_CD4i_R2L29',
 'TATGTCCCAACAAAGAAGAGGCAA-1_CD4i_R2L33',
 'TATGTCCCAACAAAGAAGAGGCAA-1_CD4i_R2L48',
 'TATGTCCCAACAAGTTACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAACAAGTTACTACTCA-1_CD4i_R2L35',
 'TATGTCCCAACAAGTTACTACTCA-1_CD4i_R2L37',
 'TATGTCCCAACAAGTTACTACTCA-1_CD4i_R2L45',
 'TATGTCCCAACAAGTTAGTGAGTG-1_CD4i_R2L48',
 'TATGTCCCAACAGAGGACTACTCA-1_CD4i_R2L25',
 'TATGTCCCAACAGAGGAGTGAGTG-1_CD4i_R2L25',
 'TATGTCCCAACAGAGGAGTGAGTG-1_CD4i_R2L28',
 'TATGTCCCAACAGCACACTACTCA-1_CD4i_R2L40',
 'TATGTCCCAACAGCACAGTGAGTG-1_CD4i_R2L40',
 'TATGTCCCAACAGCTAACTACTCA-1_CD4i_R2L48',
 'TATGTCCCAACAGCTAAGAGGCAA-1_CD4i_R2L36',
 'TATGTCCCAACAGGCTACAGTCTG-1_CD4i_R2L25',
 'TATGTCCCAACAGGCTACAGTCTG-1_CD4i_R2L28',
 'TATGTCCCAACAGGCTACTACTCA-1_CD4i_R2L28',
 'TATGTCCCAACAGGCTACTACTCA-1_CD4i_R2L42',
 'TATGTCCCAACAGGCTAGTGAGTG-1_CD4i_R2L36',
 'TATGTCCCAACAGGCTAGTGAGTG-1_CD4i_R2L44',
 'TATGTCCCAACAGGGAACAGTCTG-1_CD4i_R2L45',
 'TATGTCCCAACAGGGAACTACTCA-1_CD4i_R2L45',
 'TATGTCCCAACATAGTACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAACATAGTAGAGGCAA-1_CD4i_R2L27',
 'TATGTCCCAACCATTCACAGTCTG-1_CD4i_R2L37',
 'TATGTCCCAACCATTCACAGTCTG-1_CD4i_R2L39',
 'TATGTCCCAACCATTCAGAGGCAA-1_CD4i_R2L33',
 'TATGTCCCAACCCTATACTACTCA-1_CD4i_R2L43',
 'TATGTCCCAACCCTATAGAGGCAA-1_CD4i_R2L43',
 'TATGTCCCAACCGGATACTACTCA-1_CD4i_R2L47',
 'TATGTCCCAACCGTAAACAGTCTG-1_CD4i_R2L26',
 'TATGTCCCAACCGTAAACTACTCA-1_CD4i_R2L35',
 'TATGTCCCAACCGTAAAGTGAGTG-1_CD4i_R2L38',
 'TATGTCCCAACCGTGGACAGTCTG-1_CD4i_R2L40',
 'TATGTCCCAACCGTGGACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAACCGTGGACTACTCA-1_CD4i_R2L36',
 'TATGTCCCAACCTCGCACTACTCA-1_CD4i_R2L33',
 'TATGTCCCAACCTCGCACTACTCA-1_CD4i_R2L40',
 'TATGTCCCAACCTCGCAGAGGCAA-1_CD4i_R2L42',
 'TATGTCCCAACCTGTTAGTGAGTG-1_CD4i_R2L30',
 'TATGTCCCAACCTTGTAGAGGCAA-1_CD4i_R2L31',
 'TATGTCCCAACGACTAACAGTCTG-1_CD4i_R2L28',
 'TATGTCCCAACGTTAGACTACTCA-1_CD4i_R2L37',
 'TATGTCCCAACGTTAGAGAGGCAA-1_CD4i_R2L33',
 'TATGTCCCAACGTTAGAGTGAGTG-1_CD4i_R2L31',
 'TATGTCCCAACTAAGTACTACTCA-1_CD4i_R2L30',
 'TATGTCCCAACTAGTGACAGTCTG-1_CD4i_R2L25',
 'TATGTCCCAACTAGTGACTACTCA-1_CD4i_R2L34',
 'TATGTCCCAACTATCCAGAGGCAA-1_CD4i_R2L46',
 'TATGTCCCAACTTAGGACTACTCA-1_CD4i_R2L46',
 'TATGTCCCAACTTAGGAGTGAGTG-1_CD4i_R2L31',
 'TATGTCCCAACTTAGGAGTGAGTG-1_CD4i_R2L46',
 'TATGTCCCAACTTCGTACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAACTTCGTACAGTCTG-1_CD4i_R2L39',
 'TATGTCCCAACTTCGTACTACTCA-1_CD4i_R2L30',
 'TATGTCCCAACTTCGTAGAGGCAA-1_CD4i_R2L30',
 'TATGTCCCAACTTCGTAGAGGCAA-1_CD4i_R2L35',
 'TATGTCCCAACTTCGTAGTGAGTG-1_CD4i_R2L31',
 'TATGTCCCAACTTGTCACTACTCA-1_CD4i_R2L36',
 'TATGTCCCAAGAAATGACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAAGAAATGAGAGGCAA-1_CD4i_R2L42',
 'TATGTCCCAAGAAATGAGTGAGTG-1_CD4i_R2L42',
 'TATGTCCCAAGAACAAAGAGGCAA-1_CD4i_R2L28',
 'TATGTCCCAAGATGCCAGAGGCAA-1_CD4i_R2L34',
 'TATGTCCCAAGATGCCAGAGGCAA-1_CD4i_R2L36',
 'TATGTCCCAAGATGCCAGTGAGTG-1_CD4i_R2L48',
 'TATGTCCCAAGCCACGACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAAGCCAGTACAGTCTG-1_CD4i_R2L26',
 'TATGTCCCAAGCCAGTACAGTCTG-1_CD4i_R2L34',
 'TATGTCCCAAGCCAGTACTACTCA-1_CD4i_R2L28',
 'TATGTCCCAAGCCAGTAGAGGCAA-1_CD4i_R2L26',
 'TATGTCCCAAGCCAGTAGAGGCAA-1_CD4i_R2L28',
 'TATGTCCCAAGCCAGTAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAAGCCTAAACTACTCA-1_CD4i_R2L47',
 'TATGTCCCAAGCGAAGACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAAGCGAAGACAGTCTG-1_CD4i_R2L39',
 'TATGTCCCAAGCGAAGACTACTCA-1_CD4i_R2L35',
 'TATGTCCCAAGCGATCACAGTCTG-1_CD4i_R2L40',
 'TATGTCCCAAGCGATCAGTGAGTG-1_CD4i_R2L44',
 'TATGTCCCAAGCTAATACAGTCTG-1_CD4i_R2L30',
 'TATGTCCCAAGCTAATACAGTCTG-1_CD4i_R2L46',
 'TATGTCCCAAGCTAATACTACTCA-1_CD4i_R2L36',
 'TATGTCCCAAGCTAATAGAGGCAA-1_CD4i_R2L47',
 'TATGTCCCAAGCTAATAGTGAGTG-1_CD4i_R2L30',
 'TATGTCCCAAGCTAATAGTGAGTG-1_CD4i_R2L46',
 'TATGTCCCAAGCTATGACAGTCTG-1_CD4i_R2L27',
 'TATGTCCCAAGCTATGACTACTCA-1_CD4i_R2L41',
 'TATGTCCCAAGCTATGAGAGGCAA-1_CD4i_R2L41',
 'TATGTCCCAAGCTATGAGTGAGTG-1_CD4i_R2L27',
 'TATGTCCCAAGCTCAAACAGTCTG-1_CD4i_R2L40',
 'TATGTCCCAAGCTCAAAGAGGCAA-1_CD4i_R2L44',
 'TATGTCCCAAGCTTTCACAGTCTG-1_CD4i_R2L43',
 'TATGTCCCAAGCTTTCACTACTCA-1_CD4i_R2L28',
 'TATGTCCCAAGCTTTCAGAGGCAA-1_CD4i_R2L43',
 'TATGTCCCAAGCTTTCAGAGGCAA-1_CD4i_R2L45',
 'TATGTCCCAAGCTTTCAGTGAGTG-1_CD4i_R2L43',
 'TATGTCCCAAGGAATAACTACTCA-1_CD4i_R2L48',
 'TATGTCCCAAGGCCATACAGTCTG-1_CD4i_R2L38',
 'TATGTCCCAAGGCCATACAGTCTG-1_CD4i_R2L41',
 'TATGTCCCAAGGCCATACTACTCA-1_CD4i_R2L38',
 'TATGTCCCAAGGCCATAGAGGCAA-1_CD4i_R2L32',
 'TATGTCCCAAGGCCATAGAGGCAA-1_CD4i_R2L34',
 'TATGTCCCAAGGCCATAGAGGCAA-1_CD4i_R2L36',
 'TATGTCCCAAGGCCATAGTGAGTG-1_CD4i_R2L41',
 'TATGTCCCAAGGCGTTACAGTCTG-1_CD4i_R2L25',
 'TATGTCCCAAGGCGTTACAGTCTG-1_CD4i_R2L42',
 'TATGTCCCAAGGCGTTACTACTCA-1_CD4i_R2L42',
 'TATGTCCCAAGGCGTTAGAGGCAA-1_CD4i_R2L25',
 'TATGTCCCAAGGCGTTAGAGGCAA-1_CD4i_R2L36',
 'TATGTCCCAAGGCGTTAGTGAGTG-1_CD4i_R2L25',
 'TATGTCCCAAGGCGTTAGTGAGTG-1_CD4i_R2L36',
 'TATGTCCCAAGGCTTAAGAGGCAA-1_CD4i_R2L33',
 'TATGTCCCAAGGCTTAAGAGGCAA-1_CD4i_R2L47',
 'TATGTCCCAAGGCTTAAGTGAGTG-1_CD4i_R2L28',
 'TATGTCCCAAGGCTTAAGTGAGTG-1_CD4i_R2L47',
 'TATGTCCCAAGGGTCTACTACTCA-1_CD4i_R2L35',
 'TATGTCCCAAGGGTCTAGAGGCAA-1_CD4i_R2L26',
 'TATGTCCCAAGGGTCTAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCAAGGTGCTACAGTCTG-1_CD4i_R2L31',
 'TATGTCCCAAGGTGCTACAGTCTG-1_CD4i_R2L42',
 'TATGTCCCAAGGTGCTAGAGGCAA-1_CD4i_R2L40',
 'TATGTCCCAAGGTGCTAGAGGCAA-1_CD4i_R2L44',
 'TATGTCCCAAGGTGCTAGTGAGTG-1_CD4i_R2L32',
 'TATGTCCCAAGGTGCTAGTGAGTG-1_CD4i_R2L40',
 'TATGTCCCAAGGTGTCACTACTCA-1_CD4i_R2L29',
 'TATGTCCCAAGGTTATACAGTCTG-1_CD4i_R2L31',
 'TATGTCCCAAGGTTATACAGTCTG-1_CD4i_R2L37',
 'TATGTCCCAAGGTTATACAGTCTG-1_CD4i_R2L40',
 'TATGTCCCAAGGTTATACTACTCA-1_CD4i_R2L31',
 'TATGTCCCAAGGTTATACTACTCA-1_CD4i_R2L35',
 'TATGTCCCAAGGTTATACTACTCA-1_CD4i_R2L44',
 'TATGTCCCAAGGTTATAGAGGCAA-1_CD4i_R2L31',
 'TATGTCCCAAGTGCACACTACTCA-1_CD4i_R2L46',
 'TATGTCCCAAGTGCACAGTGAGTG-1_CD4i_R2L40',
 'TATGTCCCAAGTGCACAGTGAGTG-1_CD4i_R2L46',
 'TATGTCCCAAGTGGCTAGAGGCAA-1_CD4i_R2L27',
 'TATGTCCCAAGTGGCTAGTGAGTG-1_CD4i_R2L40',
 'TATGTCCCAAGTTCCTAGTGAGTG-1_CD4i_R2L42',
 'TATGTCCCAAGTTGCAAGAGGCAA-1_CD4i_R2L32',
 'TATGTCCCAAGTTGCAAGTGAGTG-1_CD4i_R2L47',
 'TATGTCCCAAGTTGGCACAGTCTG-1_CD4i_R2L25',
 'TATGTCCCAAGTTGGCACTACTCA-1_CD4i_R2L25',
 'TATGTCCCAAGTTGGCAGAGGCAA-1_CD4i_R2L38',
 'TATGTCCCAAGTTGGCAGAGGCAA-1_CD4i_R2L44',
 'TATGTCCCAAGTTGGCAGTGAGTG-1_CD4i_R2L25',
 'TATGTCCCAAGTTGGCAGTGAGTG-1_CD4i_R2L46',
 'TATGTCCCAAGTTTCCACAGTCTG-1_CD4i_R2L37',
 'TATGTCCCAAGTTTCCACAGTCTG-1_CD4i_R2L46',
 'TATGTCCCAAGTTTCCAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAATAACCGAGAGGCAA-1_CD4i_R2L28',
 'TATGTCCCAATAACCGAGTGAGTG-1_CD4i_R2L36',
 'TATGTCCCAATAAGCTACTACTCA-1_CD4i_R2L43',
 'TATGTCCCAATAAGCTAGAGGCAA-1_CD4i_R2L43',
 'TATGTCCCAATAAGCTAGTGAGTG-1_CD4i_R2L45',
 'TATGTCCCAATAAGGAAGTGAGTG-1_CD4i_R2L32',
 'TATGTCCCAATACCCTACAGTCTG-1_CD4i_R2L34',
 'TATGTCCCAATACCCTACAGTCTG-1_CD4i_R2L41',
 'TATGTCCCAATACCCTACTACTCA-1_CD4i_R2L41',
 'TATGTCCCAATACCCTAGAGGCAA-1_CD4i_R2L26',
 'TATGTCCCAATACCCTAGAGGCAA-1_CD4i_R2L34',
 'TATGTCCCAATACCCTAGTGAGTG-1_CD4i_R2L34',
 'TATGTCCCAATACCCTAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCAATACTGGACTACTCA-1_CD4i_R2L30',
 'TATGTCCCAATACTGGACTACTCA-1_CD4i_R2L34',
 'TATGTCCCAATACTGGAGTGAGTG-1_CD4i_R2L34',
 'TATGTCCCAATAGAAGACTACTCA-1_CD4i_R2L35',
 'TATGTCCCAATAGAGAAGAGGCAA-1_CD4i_R2L48',
 'TATGTCCCAATAGCTGACTACTCA-1_CD4i_R2L41',
 'TATGTCCCAATAGCTGAGTGAGTG-1_CD4i_R2L36',
 'TATGTCCCAATATGCGACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAATATGCGACAGTCTG-1_CD4i_R2L41',
 'TATGTCCCAATATGCGACAGTCTG-1_CD4i_R2L46',
 'TATGTCCCAATATGCGACTACTCA-1_CD4i_R2L28',
 'TATGTCCCAATATGCGAGAGGCAA-1_CD4i_R2L28',
 'TATGTCCCAATCAAACACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAATCAAACAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCAATCAAGTACTACTCA-1_CD4i_R2L28',
 'TATGTCCCAATCAAGTACTACTCA-1_CD4i_R2L46',
 'TATGTCCCAATCAAGTAGAGGCAA-1_CD4i_R2L40',
 'TATGTCCCAATCAAGTAGAGGCAA-1_CD4i_R2L46',
 'TATGTCCCAATCAAGTAGTGAGTG-1_CD4i_R2L40',
 'TATGTCCCAATCATCCACTACTCA-1_CD4i_R2L38',
 'TATGTCCCAATCCACTACTACTCA-1_CD4i_R2L44',
 'TATGTCCCAATCGTTCACAGTCTG-1_CD4i_R2L35',
 'TATGTCCCAATCGTTCAGAGGCAA-1_CD4i_R2L47',
 'TATGTCCCAATGAATCACTACTCA-1_CD4i_R2L26',
 'TATGTCCCAATGAGCCAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCAATGGATTACAGTCTG-1_CD4i_R2L27',
 'TATGTCCCAATGGATTACAGTCTG-1_CD4i_R2L39',
 'TATGTCCCAATGGATTACTACTCA-1_CD4i_R2L33',
 'TATGTCCCAATGGATTAGAGGCAA-1_CD4i_R2L27',
 'TATGTCCCAATGGATTAGAGGCAA-1_CD4i_R2L31',
 'TATGTCCCAATGGATTAGAGGCAA-1_CD4i_R2L39',
 'TATGTCCCAATGGATTAGTGAGTG-1_CD4i_R2L27',
 'TATGTCCCAATGGATTAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCAATGGATTAGTGAGTG-1_CD4i_R2L39',
 'TATGTCCCAATGGATTAGTGAGTG-1_CD4i_R2L48',
 'TATGTCCCAATGGCCGACAGTCTG-1_CD4i_R2L25',
 'TATGTCCCAATGGCCGACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAATGGCCGAGAGGCAA-1_CD4i_R2L27',
 'TATGTCCCAATGGCCGAGAGGCAA-1_CD4i_R2L47',
 'TATGTCCCAATGGGAGACAGTCTG-1_CD4i_R2L27',
 'TATGTCCCAATGGGAGACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAATGGGAGACTACTCA-1_CD4i_R2L32',
 'TATGTCCCAATGGGAGACTACTCA-1_CD4i_R2L37',
 'TATGTCCCAATGGGAGAGAGGCAA-1_CD4i_R2L38',
 'TATGTCCCAATGGGAGAGAGGCAA-1_CD4i_R2L46',
 'TATGTCCCAATGGGAGAGTGAGTG-1_CD4i_R2L40',
 'TATGTCCCAATGTGGCACAGTCTG-1_CD4i_R2L28',
 'TATGTCCCAATGTGGCAGAGGCAA-1_CD4i_R2L28',
 'TATGTCCCAATGTGGCAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCAATGTTCCACAGTCTG-1_CD4i_R2L45',
 'TATGTCCCAATGTTCCACTACTCA-1_CD4i_R2L27',
 'TATGTCCCAATGTTCCACTACTCA-1_CD4i_R2L48',
 'TATGTCCCAATGTTCCAGTGAGTG-1_CD4i_R2L27',
 'TATGTCCCAATGTTCCAGTGAGTG-1_CD4i_R2L48',
 'TATGTCCCAATTAGACACTACTCA-1_CD4i_R2L34',
 'TATGTCCCAATTAGACAGAGGCAA-1_CD4i_R2L30',
 'TATGTCCCAATTAGACAGTGAGTG-1_CD4i_R2L26',
 'TATGTCCCAATTAGCGAGAGGCAA-1_CD4i_R2L27',
 'TATGTCCCAATTAGCGAGAGGCAA-1_CD4i_R2L35',
 'TATGTCCCAATTAGCGAGTGAGTG-1_CD4i_R2L38',
 'TATGTCCCAATTCGGAAGAGGCAA-1_CD4i_R2L41',
 'TATGTCCCAATTGAACAGTGAGTG-1_CD4i_R2L27',
 'TATGTCCCAATTGAGTACAGTCTG-1_CD4i_R2L36',
 'TATGTCCCAATTGAGTAGAGGCAA-1_CD4i_R2L36',
 'TATGTCCCAATTGAGTAGAGGCAA-1_CD4i_R2L37',
 'TATGTCCCAATTGCGAACAGTCTG-1_CD4i_R2L39',
 'TATGTCCCAATTGCGAAGAGGCAA-1_CD4i_R2L46',
 'TATGTCCCAATTGCGAAGTGAGTG-1_CD4i_R2L27',
 'TATGTCCCAATTGCGAAGTGAGTG-1_CD4i_R2L42',
 'TATGTCCCACAACAATACTACTCA-1_CD4i_R2L44',
 'TATGTCCCACAACATGAGAGGCAA-1_CD4i_R2L38',
 'TATGTCCCACAAGCGTAGTGAGTG-1_CD4i_R2L26',
 'TATGTCCCACAATACGACAGTCTG-1_CD4i_R2L33',
 'TATGTCCCACAATACGACTACTCA-1_CD4i_R2L33',
 'TATGTCCCACAATACGAGAGGCAA-1_CD4i_R2L33',
 'TATGTCCCACAATAGTAGAGGCAA-1_CD4i_R2L35',
 'TATGTCCCACAATAGTAGTGAGTG-1_CD4i_R2L35',
 'TATGTCCCACAATCGAACTACTCA-1_CD4i_R2L25',
 'TATGTCCCACAATCGAACTACTCA-1_CD4i_R2L32',
 'TATGTCCCACAATCGAACTACTCA-1_CD4i_R2L38',
 'TATGTCCCACAATCGAACTACTCA-1_CD4i_R2L46',
 'TATGTCCCACAATCGAAGAGGCAA-1_CD4i_R2L25',
 'TATGTCCCACAATCGAAGAGGCAA-1_CD4i_R2L26',
 'TATGTCCCACAATCGAAGAGGCAA-1_CD4i_R2L30',
 'TATGTCCCACAATGGCACAGTCTG-1_CD4i_R2L44',
 'TATGTCCCACAATGGCAGAGGCAA-1_CD4i_R2L30',
 'TATGTCCCACACAAATAGTGAGTG-1_CD4i_R2L48',
 'TATGTCCCACACCCACACAGTCTG-1_CD4i_R2L47',
 'TATGTCCCACACCCACACTACTCA-1_CD4i_R2L39',
 'TATGTCCCACACCCACAGAGGCAA-1_CD4i_R2L40',
 'TATGTCCCACACCCACAGAGGCAA-1_CD4i_R2L43',
 'TATGTCCCACACCCACAGTGAGTG-1_CD4i_R2L40',
 'TATGTCCCACACCCACAGTGAGTG-1_CD4i_R2L43',
 'TATGTCCCACACCCACAGTGAGTG-1_CD4i_R2L46',

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

,
 'TTTGCGGGTTCACCAGAGAGGCAA-1_CD4i_R2L28',
 'TTTGCGGGTTCACCAGAGAGGCAA-1_CD4i_R2L32',
 'TTTGCGGGTTCACCAGAGTGAGTG-1_CD4i_R2L38',
 'TTTGCGGGTTCACCTCACAGTCTG-1_CD4i_R2L36',
 'TTTGCGGGTTCACCTCACAGTCTG-1_CD4i_R2L42',
 'TTTGCGGGTTCACCTCACTACTCA-1_CD4i_R2L27',
 'TTTGCGGGTTCACTCCACAGTCTG-1_CD4i_R2L45',
 'TTTGCGGGTTCACTCCACTACTCA-1_CD4i_R2L25',
 'TTTGCGGGTTCACTCCAGAGGCAA-1_CD4i_R2L28',
 'TTTGCGGGTTCACTCCAGAGGCAA-1_CD4i_R2L45',
 'TTTGCGGGTTCACTCCAGAGGCAA-1_CD4i_R2L46',
 'TTTGCGGGTTCACTCCAGTGAGTG-1_CD4i_R2L25',
 'TTTGCGGGTTCATTAGACTACTCA-1_CD4i_R2L26',
 'TTTGCGGGTTCATTAGACTACTCA-1_CD4i_R2L28',
 'TTTGCGGGTTCATTAGAGAGGCAA-1_CD4i_R2L37',
 'TTTGCGGGTTCATTGAAGAGGCAA-1_CD4i_R2L30',
 'TTTGCGGGTTCCAGCAACAGTCTG-1_CD4i_R2L47',
 'TTTGCGGGTTCCAGCAACTACTCA-1_CD4i_R2L43',
 'TTTGCGGGTTCCGCAAAGAGGCAA-1_CD4i_R2L46',
 'TTTGCGGGTTCCGCAAAGAGGCAA-1_CD4i_R2L47',
 'TTTGCGGGTTCCGCAAAGTGAGTG-1_CD4i_R2L46',
 'TTTGCGGGTTCCGGGTACAGTCTG-1_CD4i_R2L26',
 'TTTGCGGGTTCCGGGTACAGTCTG-1_CD4i_R2L34',
 'TTTGCGGGTTCCGGGTACTACTCA-1_CD4i_R2L34',
 'TTTGCGGGTTCCGGGTAGAGGCAA-1_CD4i_R2L26',
 'TTTGCGGGTTCCGGGTAGTGAGTG-1_CD4i_R2L38',
 'TTTGCGGGTTCCGTGAAGTGAGTG-1_CD4i_R2L42',
 'TTTGCGGGTTCCTTCAACAGTCTG-1_CD4i_R2L27',
 'TTTGCGGGTTCCTTCAACAGTCTG-1_CD4i_R2L45',
 'TTTGCGGGTTCCTTCAAGTGAGTG-1_CD4i_R2L25',
 'TTTGCGGGTTCCTTCAAGTGAGTG-1_CD4i_R2L39',
 'TTTGCGGGTTCCTTTGACAGTCTG-1_CD4i_R2L41',
 'TTTGCGGGTTCCTTTGAGAGGCAA-1_CD4i_R2L32',
 'TTTGCGGGTTCGAATCACTACTCA-1_CD4i_R2L42',
 'TTTGCGGGTTCGAATCAGAGGCAA-1_CD4i_R2L33',
 'TTTGCGGGTTCGAATCAGAGGCAA-1_CD4i_R2L42',
 'TTTGCGGGTTCGAATCAGTGAGTG-1_CD4i_R2L33',
 'TTTGCGGGTTCGATGTACTACTCA-1_CD4i_R2L36',
 'TTTGCGGGTTCGGTATAGAGGCAA-1_CD4i_R2L30',
 'TTTGCGGGTTCGGTATAGTGAGTG-1_CD4i_R2L30',
 'TTTGCGGGTTCGGTCAACAGTCTG-1_CD4i_R2L32',
 'TTTGCGGGTTCTCAAAAGAGGCAA-1_CD4i_R2L35',
 'TTTGCGGGTTCTGGCAACTACTCA-1_CD4i_R2L25',
 'TTTGCGGGTTCTGGCAACTACTCA-1_CD4i_R2L41',
 'TTTGCGGGTTCTGGCAACTACTCA-1_CD4i_R2L48',
 'TTTGCGGGTTCTGGCAAGAGGCAA-1_CD4i_R2L27',
 'TTTGCGGGTTCTGGCAAGAGGCAA-1_CD4i_R2L28',
 'TTTGCGGGTTCTGGCAAGAGGCAA-1_CD4i_R2L48',
 'TTTGCGGGTTCTTACTACAGTCTG-1_CD4i_R2L26',
 'TTTGCGGGTTCTTACTACAGTCTG-1_CD4i_R2L37',
 'TTTGCGGGTTCTTACTACTACTCA-1_CD4i_R2L33',
 'TTTGCGGGTTCTTACTACTACTCA-1_CD4i_R2L37',
 'TTTGCGGGTTCTTGAAACTACTCA-1_CD4i_R2L35',
 'TTTGCGGGTTCTTGAAACTACTCA-1_CD4i_R2L46',
 'TTTGCGGGTTCTTGAAAGAGGCAA-1_CD4i_R2L46',
 'TTTGCGGGTTGACCCAACAGTCTG-1_CD4i_R2L29',
 'TTTGCGGGTTGACCCAACAGTCTG-1_CD4i_R2L46',
 'TTTGCGGGTTGACCCAAGAGGCAA-1_CD4i_R2L30',
 'TTTGCGGGTTGACCCAAGTGAGTG-1_CD4i_R2L30',
 'TTTGCGGGTTGACCCAAGTGAGTG-1_CD4i_R2L45',
 'TTTGCGGGTTGAGCTTAGAGGCAA-1_CD4i_R2L30',
 'TTTGCGGGTTGAGCTTAGTGAGTG-1_CD4i_R2L30',
 'TTTGCGGGTTGAGGACACAGTCTG-1_CD4i_R2L34',
 'TTTGCGGGTTGAGGACACAGTCTG-1_CD4i_R2L44',
 'TTTGCGGGTTGAGGACACAGTCTG-1_CD4i_R2L48',
 'TTTGCGGGTTGAGGACACTACTCA-1_CD4i_R2L34',
 'TTTGCGGGTTGAGGACACTACTCA-1_CD4i_R2L44',
 'TTTGCGGGTTGAGGACAGAGGCAA-1_CD4i_R2L40',
 'TTTGCGGGTTGAGTCTAGTGAGTG-1_CD4i_R2L33',
 'TTTGCGGGTTGCACGCAGAGGCAA-1_CD4i_R2L30',
 'TTTGCGGGTTGCACGCAGTGAGTG-1_CD4i_R2L30',
 'TTTGCGGGTTGCACTGACAGTCTG-1_CD4i_R2L47',
 'TTTGCGGGTTGCACTGAGAGGCAA-1_CD4i_R2L30',
 'TTTGCGGGTTGCGAAAACAGTCTG-1_CD4i_R2L43',
 'TTTGCGGGTTGCGCTAACAGTCTG-1_CD4i_R2L33',
 'TTTGCGGGTTGCGCTAACAGTCTG-1_CD4i_R2L38',
 'TTTGCGGGTTGCGCTAACAGTCTG-1_CD4i_R2L45',
 'TTTGCGGGTTGCGCTAACTACTCA-1_CD4i_R2L33',
 'TTTGCGGGTTGCGCTAACTACTCA-1_CD4i_R2L38',
 'TTTGCGGGTTGCGCTAAGAGGCAA-1_CD4i_R2L33',
 'TTTGCGGGTTGCGCTAAGTGAGTG-1_CD4i_R2L45',
 'TTTGCGGGTTGCTGTGACAGTCTG-1_CD4i_R2L26',
 'TTTGCGGGTTGGAGCGAGAGGCAA-1_CD4i_R2L31',
 'TTTGCGGGTTGGAGCGAGTGAGTG-1_CD4i_R2L31',
 'TTTGCGGGTTGGATAGAGAGGCAA-1_CD4i_R2L38',
 'TTTGCGGGTTGGATGAACAGTCTG-1_CD4i_R2L44',
 'TTTGCGGGTTGGATGAAGAGGCAA-1_CD4i_R2L48',
 'TTTGCGGGTTGGATGAAGTGAGTG-1_CD4i_R2L44',
 'TTTGCGGGTTGGCGAGACAGTCTG-1_CD4i_R2L28',
 'TTTGCGGGTTGGCGAGACTACTCA-1_CD4i_R2L28',
 'TTTGCGGGTTGGCGAGACTACTCA-1_CD4i_R2L29',
 'TTTGCGGGTTGGCGAGACTACTCA-1_CD4i_R2L32',
 'TTTGCGGGTTGGGCGAACTACTCA-1_CD4i_R2L38',
 'TTTGCGGGTTGGGCGAAGAGGCAA-1_CD4i_R2L37',
 'TTTGCGGGTTGGGCGAAGAGGCAA-1_CD4i_R2L44',
 'TTTGCGGGTTGGGCGAAGTGAGTG-1_CD4i_R2L37',
 'TTTGCGGGTTGGTTACACAGTCTG-1_CD4i_R2L48',
 'TTTGCGGGTTGGTTACACTACTCA-1_CD4i_R2L48',
 'TTTGCGGGTTGGTTACAGAGGCAA-1_CD4i_R2L30',
 'TTTGCGGGTTGGTTACAGTGAGTG-1_CD4i_R2L45',
 'TTTGCGGGTTGGTTACAGTGAGTG-1_CD4i_R2L48',
 'TTTGCGGGTTGGTTTAAGTGAGTG-1_CD4i_R2L46',
 'TTTGCGGGTTGTCAGTACAGTCTG-1_CD4i_R2L40',
 'TTTGCGGGTTGTCAGTACTACTCA-1_CD4i_R2L42',
 'TTTGCGGGTTGTCAGTACTACTCA-1_CD4i_R2L48',
 'TTTGCGGGTTGTCATAACTACTCA-1_CD4i_R2L35',
 'TTTGCGGGTTGTCATAACTACTCA-1_CD4i_R2L42',
 'TTTGCGGGTTGTCCAGACAGTCTG-1_CD4i_R2L42',
 'TTTGCGGGTTGTCCAGACTACTCA-1_CD4i_R2L26',
 'TTTGCGGGTTGTCCAGAGAGGCAA-1_CD4i_R2L32',
 'TTTGCGGGTTGTCCAGAGTGAGTG-1_CD4i_R2L42',
 'TTTGCGGGTTGTGACTAGTGAGTG-1_CD4i_R2L43',
 'TTTGCGGGTTGTGAGAACAGTCTG-1_CD4i_R2L47',
 'TTTGCGGGTTGTGAGAAGAGGCAA-1_CD4i_R2L46',
 'TTTGCGGGTTGTTCCCACAGTCTG-1_CD4i_R2L31',
 'TTTGCGGGTTGTTCCCACAGTCTG-1_CD4i_R2L38',
 'TTTGCGGGTTGTTCCCACAGTCTG-1_CD4i_R2L40',
 'TTTGCGGGTTGTTCCCACTACTCA-1_CD4i_R2L26',
 'TTTGCGGGTTGTTCCCAGAGGCAA-1_CD4i_R2L31',
 'TTTGCGGGTTGTTCCCAGAGGCAA-1_CD4i_R2L38',
 'TTTGCGGGTTGTTCCCAGTGAGTG-1_CD4i_R2L31',
 'TTTGCGGGTTGTTCCCAGTGAGTG-1_CD4i_R2L38',
 'TTTGCGGGTTGTTGGTACAGTCTG-1_CD4i_R2L35',
 'TTTGCGGGTTGTTGGTACAGTCTG-1_CD4i_R2L44',
 'TTTGCGGGTTGTTGGTAGAGGCAA-1_CD4i_R2L35',
 'TTTGCGGGTTGTTGGTAGAGGCAA-1_CD4i_R2L36',
 'TTTGCGGGTTGTTGGTAGTGAGTG-1_CD4i_R2L29',
 'TTTGCGGGTTGTTGGTAGTGAGTG-1_CD4i_R2L37',
 'TTTGCGGGTTGTTGTAAGAGGCAA-1_CD4i_R2L29',
 'TTTGCGGGTTGTTGTAAGAGGCAA-1_CD4i_R2L37',
 'TTTGCGGGTTGTTTAGACAGTCTG-1_CD4i_R2L35',
 'TTTGCGGGTTGTTTAGACTACTCA-1_CD4i_R2L28',
 'TTTGCGGGTTGTTTAGAGAGGCAA-1_CD4i_R2L33',
 'TTTGCGGGTTGTTTAGAGTGAGTG-1_CD4i_R2L35',
 'TTTGCGGGTTGTTTAGAGTGAGTG-1_CD4i_R2L39',
 'TTTGCGGGTTGTTTGAAGTGAGTG-1_CD4i_R2L42',
 'TTTGCGGGTTTACCGGACTACTCA-1_CD4i_R2L34',
 'TTTGCGGGTTTACCGGAGAGGCAA-1_CD4i_R2L37',
 'TTTGCGGGTTTACTGAAGAGGCAA-1_CD4i_R2L33',
 'TTTGCGGGTTTACTGAAGTGAGTG-1_CD4i_R2L33',
 'TTTGCGGGTTTAGTTGACTACTCA-1_CD4i_R2L26',
 'TTTGCGGGTTTATCGAAGTGAGTG-1_CD4i_R2L34',
 'TTTGCGGGTTTATGGCACAGTCTG-1_CD4i_R2L48',
 'TTTGCGGGTTTATGGCAGTGAGTG-1_CD4i_R2L48',
 'TTTGCGGGTTTCACCCACAGTCTG-1_CD4i_R2L36',
 'TTTGCGGGTTTCACCCACAGTCTG-1_CD4i_R2L45',
 'TTTGCGGGTTTCACCCACAGTCTG-1_CD4i_R2L46',
 'TTTGCGGGTTTCACCCACTACTCA-1_CD4i_R2L28',
 'TTTGCGGGTTTCACCCAGAGGCAA-1_CD4i_R2L28',
 'TTTGCGGGTTTCACCCAGTGAGTG-1_CD4i_R2L25',
 'TTTGCGGGTTTCACCCAGTGAGTG-1_CD4i_R2L47',
 'TTTGCGGGTTTCAGGTACAGTCTG-1_CD4i_R2L26',
 'TTTGCGGGTTTCAGGTACAGTCTG-1_CD4i_R2L43',
 'TTTGCGGGTTTCCAAAACAGTCTG-1_CD4i_R2L25',
 'TTTGCGGGTTTCCAAAACTACTCA-1_CD4i_R2L34',
 'TTTGCGGGTTTCCACCACAGTCTG-1_CD4i_R2L29',
 'TTTGCGGGTTTCCACCACAGTCTG-1_CD4i_R2L45',
 'TTTGCGGGTTTCCACCACTACTCA-1_CD4i_R2L29',
 'TTTGCGGGTTTCCACCACTACTCA-1_CD4i_R2L35',
 'TTTGCGGGTTTCCACCAGTGAGTG-1_CD4i_R2L44',
 'TTTGCGGGTTTCCTCAACAGTCTG-1_CD4i_R2L27',
 'TTTGCGGGTTTCCTCAACAGTCTG-1_CD4i_R2L30',
 'TTTGCGGGTTTCCTCAACTACTCA-1_CD4i_R2L28',
 'TTTGCGGGTTTCCTCAAGAGGCAA-1_CD4i_R2L28',
 'TTTGCGGGTTTCCTCAAGAGGCAA-1_CD4i_R2L48',
 'TTTGCGGGTTTCCTGCACAGTCTG-1_CD4i_R2L38',
 'TTTGCGGGTTTCCTGCAGTGAGTG-1_CD4i_R2L42',
 'TTTGCGGGTTTCGCCTACAGTCTG-1_CD4i_R2L27',
 'TTTGCGGGTTTCGCCTACAGTCTG-1_CD4i_R2L36',
 'TTTGCGGGTTTGACTAACTACTCA-1_CD4i_R2L31',
 'TTTGCGGGTTTGACTAACTACTCA-1_CD4i_R2L33',
 'TTTGCGGGTTTGACTAAGTGAGTG-1_CD4i_R2L27',
 'TTTGCGGGTTTGAGCTACAGTCTG-1_CD4i_R2L47',
 'TTTGCGGGTTTGAGCTACTACTCA-1_CD4i_R2L31',
 'TTTGCGGGTTTGAGCTACTACTCA-1_CD4i_R2L47',
 'TTTGCGGGTTTGAGCTAGAGGCAA-1_CD4i_R2L41',
 'TTTGCGGGTTTGAGCTAGAGGCAA-1_CD4i_R2L43',
 'TTTGCGGGTTTGCAACACAGTCTG-1_CD4i_R2L42',
 'TTTGCGGGTTTGCAACACAGTCTG-1_CD4i_R2L48',
 'TTTGCGGGTTTGCAACAGTGAGTG-1_CD4i_R2L41',
 'TTTGCGGGTTTGCAACAGTGAGTG-1_CD4i_R2L42',
 'TTTGCGGGTTTGCATAACAGTCTG-1_CD4i_R2L32',
 'TTTGCGGGTTTGCATAACAGTCTG-1_CD4i_R2L35',
 'TTTGCGGGTTTGCATAACTACTCA-1_CD4i_R2L36',
 'TTTGCGGGTTTGCATAAGAGGCAA-1_CD4i_R2L36',
 'TTTGCGGGTTTGCATAAGTGAGTG-1_CD4i_R2L25',
 'TTTGCGGGTTTGCATAAGTGAGTG-1_CD4i_R2L38',
 'TTTGCGGGTTTGCTCCAGAGGCAA-1_CD4i_R2L29',
 'TTTGCGGGTTTGCTCCAGAGGCAA-1_CD4i_R2L32',
 'TTTGCGGGTTTGCTCCAGTGAGTG-1_CD4i_R2L42',
 'TTTGCGGGTTTGGGCCACAGTCTG-1_CD4i_R2L47',
 'TTTGCGGGTTTGGGCCAGAGGCAA-1_CD4i_R2L27',
 'TTTGCGGGTTTGTAGCACTACTCA-1_CD4i_R2L47',
 'TTTGCGGGTTTGTAGCAGTGAGTG-1_CD4i_R2L35',
 'TTTGCGGGTTTGTCAAACTACTCA-1_CD4i_R2L29',
 'TTTGCGGGTTTGTCCCACAGTCTG-1_CD4i_R2L32',
 'TTTGCGGGTTTGTCCCACAGTCTG-1_CD4i_R2L46',
 'TTTGCGGGTTTGTCCCACTACTCA-1_CD4i_R2L39',
 'TTTGCGGGTTTGTCCCAGAGGCAA-1_CD4i_R2L36',
 'TTTGCGGGTTTGTTGAACTACTCA-1_CD4i_R2L45',
 'TTTGCGGGTTTGTTGAAGAGGCAA-1_CD4i_R2L25',
 'TTTGCGGGTTTGTTGAAGAGGCAA-1_CD4i_R2L33',
 'TTTGCGGGTTTGTTGAAGTGAGTG-1_CD4i_R2L25',
 'TTTGCGGGTTTGTTGAAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCAAACCAAAGTGAGTG-1_CD4i_R2L38',
 'TTTGCTCTCAAACCGGACAGTCTG-1_CD4i_R2L26',
 'TTTGCTCTCAAACCGGACAGTCTG-1_CD4i_R2L27',
 'TTTGCTCTCAAACCGGACAGTCTG-1_CD4i_R2L37',
 'TTTGCTCTCAAACCGGAGTGAGTG-1_CD4i_R2L27',
 'TTTGCTCTCAAACTTCACAGTCTG-1_CD4i_R2L35',
 'TTTGCTCTCAAACTTCACTACTCA-1_CD4i_R2L35',
 'TTTGCTCTCAAAGGCTACAGTCTG-1_CD4i_R2L47',
 'TTTGCTCTCAAAGGCTACTACTCA-1_CD4i_R2L38',
 'TTTGCTCTCAAAGGGAACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCAACATTCACAGTCTG-1_CD4i_R2L32',
 'TTTGCTCTCAACATTCAGAGGCAA-1_CD4i_R2L32',
 'TTTGCTCTCAACATTCAGAGGCAA-1_CD4i_R2L44',
 'TTTGCTCTCAACATTCAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCAACATTCAGTGAGTG-1_CD4i_R2L47',
 'TTTGCTCTCAACCAAAACAGTCTG-1_CD4i_R2L28',
 'TTTGCTCTCAACCAAAACTACTCA-1_CD4i_R2L33',
 'TTTGCTCTCAACCAAAACTACTCA-1_CD4i_R2L47',
 'TTTGCTCTCAACCAAAAGAGGCAA-1_CD4i_R2L35',
 'TTTGCTCTCAACCAAAAGTGAGTG-1_CD4i_R2L31',
 'TTTGCTCTCAACCGCTACAGTCTG-1_CD4i_R2L33',
 'TTTGCTCTCAACCGCTACTACTCA-1_CD4i_R2L25',
 'TTTGCTCTCAACCGCTACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCAACCGCTAGAGGCAA-1_CD4i_R2L25',
 'TTTGCTCTCAACCGCTAGTGAGTG-1_CD4i_R2L28',
 'TTTGCTCTCAACCGCTAGTGAGTG-1_CD4i_R2L38',
 'TTTGCTCTCAACCGGAAGTGAGTG-1_CD4i_R2L28',
 'TTTGCTCTCAACCTATAGAGGCAA-1_CD4i_R2L26',
 'TTTGCTCTCAACCTCAACAGTCTG-1_CD4i_R2L39',
 'TTTGCTCTCAACCTCAACAGTCTG-1_CD4i_R2L48',
 'TTTGCTCTCAACCTCAACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCAACCTCAACTACTCA-1_CD4i_R2L37',
 'TTTGCTCTCAACCTCAAGAGGCAA-1_CD4i_R2L28',
 'TTTGCTCTCAACCTCAAGAGGCAA-1_CD4i_R2L39',
 'TTTGCTCTCAACCTCAAGTGAGTG-1_CD4i_R2L34',
 'TTTGCTCTCAACCTCAAGTGAGTG-1_CD4i_R2L37',
 'TTTGCTCTCAACTGGGACAGTCTG-1_CD4i_R2L37',
 'TTTGCTCTCAACTGGGACAGTCTG-1_CD4i_R2L41',
 'TTTGCTCTCAACTGGGAGAGGCAA-1_CD4i_R2L37',
 'TTTGCTCTCAACTGGGAGAGGCAA-1_CD4i_R2L41',
 'TTTGCTCTCAACTTGTACAGTCTG-1_CD4i_R2L41',
 'TTTGCTCTCAACTTGTACTACTCA-1_CD4i_R2L43',
 'TTTGCTCTCAACTTGTAGAGGCAA-1_CD4i_R2L25',
 'TTTGCTCTCAACTTGTAGTGAGTG-1_CD4i_R2L31',
 'TTTGCTCTCAAGATGCACAGTCTG-1_CD4i_R2L38',
 'TTTGCTCTCAAGATGCAGAGGCAA-1_CD4i_R2L33',
 'TTTGCTCTCAAGATGCAGAGGCAA-1_CD4i_R2L38',
 'TTTGCTCTCAAGCCAGACAGTCTG-1_CD4i_R2L36',
 'TTTGCTCTCAAGCGATACAGTCTG-1_CD4i_R2L28',
 'TTTGCTCTCAAGCGATACAGTCTG-1_CD4i_R2L33',
 'TTTGCTCTCAAGCGATACAGTCTG-1_CD4i_R2L37',
 'TTTGCTCTCAAGCGATAGAGGCAA-1_CD4i_R2L44',
 'TTTGCTCTCAAGCGATAGTGAGTG-1_CD4i_R2L37',
 'TTTGCTCTCAAGCTCCACAGTCTG-1_CD4i_R2L33',
 'TTTGCTCTCAAGGGCCACAGTCTG-1_CD4i_R2L44',
 'TTTGCTCTCAAGGGTTACAGTCTG-1_CD4i_R2L26',
 'TTTGCTCTCAAGGGTTACAGTCTG-1_CD4i_R2L35',
 'TTTGCTCTCAAGGGTTAGAGGCAA-1_CD4i_R2L27',
 'TTTGCTCTCAAGGGTTAGTGAGTG-1_CD4i_R2L27',
 'TTTGCTCTCAAGGGTTAGTGAGTG-1_CD4i_R2L45',
 'TTTGCTCTCAAGGTACACTACTCA-1_CD4i_R2L44',
 'TTTGCTCTCAAGGTACACTACTCA-1_CD4i_R2L45',
 'TTTGCTCTCAAGGTACAGAGGCAA-1_CD4i_R2L40',
 'TTTGCTCTCAAGGTACAGAGGCAA-1_CD4i_R2L45',
 'TTTGCTCTCAAGGTACAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCAAGGTCGACAGTCTG-1_CD4i_R2L30',
 'TTTGCTCTCAAGGTCGACAGTCTG-1_CD4i_R2L35',
 'TTTGCTCTCAAGGTCGACAGTCTG-1_CD4i_R2L43',
 'TTTGCTCTCAAGGTCGAGAGGCAA-1_CD4i_R2L30',
 'TTTGCTCTCAAGGTCGAGTGAGTG-1_CD4i_R2L34',
 'TTTGCTCTCAAGGTCGAGTGAGTG-1_CD4i_R2L48',
 'TTTGCTCTCAAGGTGTACAGTCTG-1_CD4i_R2L26',
 'TTTGCTCTCAAGGTGTACTACTCA-1_CD4i_R2L26',
 'TTTGCTCTCAAGGTGTAGTGAGTG-1_CD4i_R2L29',
 'TTTGCTCTCAAGTTAGACAGTCTG-1_CD4i_R2L42',
 'TTTGCTCTCAAGTTAGACTACTCA-1_CD4i_R2L44',
 'TTTGCTCTCAAGTTAGAGTGAGTG-1_CD4i_R2L42',
 'TTTGCTCTCAAGTTAGAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCAAGTTTCAGAGGCAA-1_CD4i_R2L38',
 'TTTGCTCTCAATACAGACAGTCTG-1_CD4i_R2L28',
 'TTTGCTCTCAATACAGACAGTCTG-1_CD4i_R2L35',
 'TTTGCTCTCAATACAGACAGTCTG-1_CD4i_R2L48',
 'TTTGCTCTCAATACAGAGAGGCAA-1_CD4i_R2L35',
 'TTTGCTCTCAATACAGAGTGAGTG-1_CD4i_R2L34',
 'TTTGCTCTCAATCCTGAGAGGCAA-1_CD4i_R2L40',
 'TTTGCTCTCAATCGCCACAGTCTG-1_CD4i_R2L30',
 'TTTGCTCTCAATCGCCACTACTCA-1_CD4i_R2L30',
 'TTTGCTCTCAATGGGTACAGTCTG-1_CD4i_R2L36',
 'TTTGCTCTCAATGGGTAGAGGCAA-1_CD4i_R2L31',
 'TTTGCTCTCAATGGGTAGTGAGTG-1_CD4i_R2L36',
 'TTTGCTCTCAATGTGAAGAGGCAA-1_CD4i_R2L32',
 'TTTGCTCTCAATGTTCACTACTCA-1_CD4i_R2L26',
 'TTTGCTCTCAATTGGAACAGTCTG-1_CD4i_R2L40',
 'TTTGCTCTCAATTGGAACTACTCA-1_CD4i_R2L33',
 'TTTGCTCTCAATTGGAAGTGAGTG-1_CD4i_R2L33',
 'TTTGCTCTCAATTTGCAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCACAAACAACAGTCTG-1_CD4i_R2L34',
 'TTTGCTCTCACAAACAACTACTCA-1_CD4i_R2L34',
 'TTTGCTCTCACAAACAAGTGAGTG-1_CD4i_R2L26',
 'TTTGCTCTCACAAACAAGTGAGTG-1_CD4i_R2L34',
 'TTTGCTCTCACAAAGCACAGTCTG-1_CD4i_R2L32',
 'TTTGCTCTCACAAAGCACAGTCTG-1_CD4i_R2L43',
 'TTTGCTCTCACAAAGCACTACTCA-1_CD4i_R2L32',
 'TTTGCTCTCACAAAGCAGAGGCAA-1_CD4i_R2L32',
 'TTTGCTCTCACAAAGCAGTGAGTG-1_CD4i_R2L35',
 'TTTGCTCTCACAAATGACAGTCTG-1_CD4i_R2L44',
 'TTTGCTCTCACAAATGAGTGAGTG-1_CD4i_R2L30',
 'TTTGCTCTCACAAATGAGTGAGTG-1_CD4i_R2L41',
 'TTTGCTCTCACAACAAACAGTCTG-1_CD4i_R2L28',
 'TTTGCTCTCACAACAAAGTGAGTG-1_CD4i_R2L28',
 'TTTGCTCTCACAAGCGACAGTCTG-1_CD4i_R2L48',
 'TTTGCTCTCACAAGCGACTACTCA-1_CD4i_R2L39',
 'TTTGCTCTCACAATGAACAGTCTG-1_CD4i_R2L41',
 'TTTGCTCTCACAATGAACTACTCA-1_CD4i_R2L41',
 'TTTGCTCTCACAATGAACTACTCA-1_CD4i_R2L42',
 'TTTGCTCTCACAATGAAGTGAGTG-1_CD4i_R2L27',
 'TTTGCTCTCACAATGAAGTGAGTG-1_CD4i_R2L46',
 'TTTGCTCTCACACAAAAGTGAGTG-1_CD4i_R2L38',
 'TTTGCTCTCACAGATAACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCACAGATAAGAGGCAA-1_CD4i_R2L25',
 'TTTGCTCTCACAGATAAGAGGCAA-1_CD4i_R2L35',
 'TTTGCTCTCACAGATAAGTGAGTG-1_CD4i_R2L28',
 'TTTGCTCTCACAGCCTAGAGGCAA-1_CD4i_R2L42',
 'TTTGCTCTCACAGCCTAGTGAGTG-1_CD4i_R2L29',
 'TTTGCTCTCACAGGATACTACTCA-1_CD4i_R2L31',
 'TTTGCTCTCACAGGATACTACTCA-1_CD4i_R2L40',
 'TTTGCTCTCACAGGATAGTGAGTG-1_CD4i_R2L31',
 'TTTGCTCTCACAGGATAGTGAGTG-1_CD4i_R2L33',
 'TTTGCTCTCACAGGGCACAGTCTG-1_CD4i_R2L34',
 'TTTGCTCTCACAGGGCACTACTCA-1_CD4i_R2L35',
 'TTTGCTCTCACAGGGCAGAGGCAA-1_CD4i_R2L25',
 'TTTGCTCTCACATTACACAGTCTG-1_CD4i_R2L37',
 'TTTGCTCTCACATTACACAGTCTG-1_CD4i_R2L43',
 'TTTGCTCTCACATTACACTACTCA-1_CD4i_R2L37',
 'TTTGCTCTCACATTACACTACTCA-1_CD4i_R2L39',
 'TTTGCTCTCACATTACAGAGGCAA-1_CD4i_R2L39',
 'TTTGCTCTCACATTCGACTACTCA-1_CD4i_R2L44',
 'TTTGCTCTCACATTCGAGAGGCAA-1_CD4i_R2L39',
 'TTTGCTCTCACATTCGAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCACCACACACAGTCTG-1_CD4i_R2L31',
 'TTTGCTCTCACCACACACTACTCA-1_CD4i_R2L30',
 'TTTGCTCTCACCAGCTACAGTCTG-1_CD4i_R2L26',
 'TTTGCTCTCACCAGCTAGAGGCAA-1_CD4i_R2L26',
 'TTTGCTCTCACCAGCTAGAGGCAA-1_CD4i_R2L38',
 'TTTGCTCTCACCAGCTAGTGAGTG-1_CD4i_R2L48',
 'TTTGCTCTCACCAGGAACTACTCA-1_CD4i_R2L29',
 'TTTGCTCTCACCAGGAAGAGGCAA-1_CD4i_R2L32',
 'TTTGCTCTCACCAGGAAGTGAGTG-1_CD4i_R2L29',
 'TTTGCTCTCACCATATACTACTCA-1_CD4i_R2L26',
 'TTTGCTCTCACCCTCCACTACTCA-1_CD4i_R2L45',
 'TTTGCTCTCACCCTCCAGAGGCAA-1_CD4i_R2L33',
 'TTTGCTCTCACCCTCCAGTGAGTG-1_CD4i_R2L48',
 'TTTGCTCTCACCCTGGACAGTCTG-1_CD4i_R2L27',
 'TTTGCTCTCACCCTGGACAGTCTG-1_CD4i_R2L32',
 'TTTGCTCTCACCCTGGACTACTCA-1_CD4i_R2L27',
 'TTTGCTCTCACCCTGGAGAGGCAA-1_CD4i_R2L27',
 'TTTGCTCTCACCCTGGAGAGGCAA-1_CD4i_R2L43',
 'TTTGCTCTCACCCTGGAGTGAGTG-1_CD4i_R2L32',
 'TTTGCTCTCACCTAATACAGTCTG-1_CD4i_R2L33',
 'TTTGCTCTCACCTAATACTACTCA-1_CD4i_R2L33',
 'TTTGCTCTCACCTAATAGTGAGTG-1_CD4i_R2L33',
 'TTTGCTCTCACCTAATAGTGAGTG-1_CD4i_R2L43',
 'TTTGCTCTCACCTTTCACTACTCA-1_CD4i_R2L39',
 'TTTGCTCTCACCTTTCACTACTCA-1_CD4i_R2L44',
 'TTTGCTCTCACCTTTCAGAGGCAA-1_CD4i_R2L39',
 'TTTGCTCTCACCTTTCAGAGGCAA-1_CD4i_R2L48',
 'TTTGCTCTCACCTTTCAGTGAGTG-1_CD4i_R2L31',
 'TTTGCTCTCACGAACGACAGTCTG-1_CD4i_R2L30',
 'TTTGCTCTCACGAACGAGAGGCAA-1_CD4i_R2L25',
 'TTTGCTCTCACGGACAACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCACGGACAACTACTCA-1_CD4i_R2L42',
 'TTTGCTCTCACGGACAAGAGGCAA-1_CD4i_R2L42',
 'TTTGCTCTCACGGACAAGAGGCAA-1_CD4i_R2L45',
 'TTTGCTCTCACGGACAAGAGGCAA-1_CD4i_R2L48',
 'TTTGCTCTCACGGACAAGTGAGTG-1_CD4i_R2L46',
 'TTTGCTCTCACGTTCAAGTGAGTG-1_CD4i_R2L33',
 'TTTGCTCTCACTAATCACAGTCTG-1_CD4i_R2L27',
 'TTTGCTCTCACTAATCACAGTCTG-1_CD4i_R2L34',
 'TTTGCTCTCACTAATCACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCACTAATCACTACTCA-1_CD4i_R2L34',
 'TTTGCTCTCACTAATCAGAGGCAA-1_CD4i_R2L27',
 'TTTGCTCTCACTAATCAGAGGCAA-1_CD4i_R2L28',
 'TTTGCTCTCACTAATCAGAGGCAA-1_CD4i_R2L35',
 'TTTGCTCTCACTAGGGACTACTCA-1_CD4i_R2L45',
 'TTTGCTCTCACTAGGGAGAGGCAA-1_CD4i_R2L27',
 'TTTGCTCTCACTAGGGAGTGAGTG-1_CD4i_R2L45',
 'TTTGCTCTCACTATGTACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCACTATGTACTACTCA-1_CD4i_R2L39',
 'TTTGCTCTCACTATGTAGAGGCAA-1_CD4i_R2L39',
 'TTTGCTCTCACTATGTAGTGAGTG-1_CD4i_R2L47',
 'TTTGCTCTCACTCGCGACTACTCA-1_CD4i_R2L29',
 'TTTGCTCTCACTCGCGACTACTCA-1_CD4i_R2L45',
 'TTTGCTCTCACTCGCGAGAGGCAA-1_CD4i_R2L41',
 'TTTGCTCTCACTGTCAACAGTCTG-1_CD4i_R2L27',
 'TTTGCTCTCACTGTCAACAGTCTG-1_CD4i_R2L44',
 'TTTGCTCTCACTGTCAACTACTCA-1_CD4i_R2L26',
 'TTTGCTCTCACTGTCAACTACTCA-1_CD4i_R2L27',
 'TTTGCTCTCACTGTCAACTACTCA-1_CD4i_R2L34',
 'TTTGCTCTCACTGTCAAGAGGCAA-1_CD4i_R2L33',
 'TTTGCTCTCACTGTCAAGAGGCAA-1_CD4i_R2L34',
 'TTTGCTCTCACTGTCAAGAGGCAA-1_CD4i_R2L44',
 'TTTGCTCTCACTGTCAAGTGAGTG-1_CD4i_R2L34',
 'TTTGCTCTCACTGTCAAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCACTGTCAAGTGAGTG-1_CD4i_R2L48',
 'TTTGCTCTCACTTGATACAGTCTG-1_CD4i_R2L44',
 'TTTGCTCTCACTTGATACTACTCA-1_CD4i_R2L27',
 'TTTGCTCTCACTTGATAGAGGCAA-1_CD4i_R2L44',
 'TTTGCTCTCACTTGATAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCAGCACAGACTACTCA-1_CD4i_R2L37',
 'TTTGCTCTCAGCACAGAGAGGCAA-1_CD4i_R2L37',
 'TTTGCTCTCAGCACCTACTACTCA-1_CD4i_R2L30',
 'TTTGCTCTCAGCACCTAGTGAGTG-1_CD4i_R2L48',
 'TTTGCTCTCAGCACGAAGAGGCAA-1_CD4i_R2L35',
 'TTTGCTCTCAGCACGAAGAGGCAA-1_CD4i_R2L43',
 'TTTGCTCTCAGCATGGACAGTCTG-1_CD4i_R2L36',
 'TTTGCTCTCAGCATGGACTACTCA-1_CD4i_R2L27',
 'TTTGCTCTCAGCATGGAGAGGCAA-1_CD4i_R2L27',
 'TTTGCTCTCAGCCCTGACAGTCTG-1_CD4i_R2L39',
 'TTTGCTCTCAGCCCTGAGAGGCAA-1_CD4i_R2L25',
 'TTTGCTCTCAGCCCTGAGTGAGTG-1_CD4i_R2L25',
 'TTTGCTCTCAGCCTTAACAGTCTG-1_CD4i_R2L42',
 'TTTGCTCTCAGCCTTAAGAGGCAA-1_CD4i_R2L46',
 'TTTGCTCTCAGCCTTAAGTGAGTG-1_CD4i_R2L25',
 'TTTGCTCTCAGCCTTAAGTGAGTG-1_CD4i_R2L37',
 'TTTGCTCTCAGCCTTAAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCAGCCTTAAGTGAGTG-1_CD4i_R2L46',
 'TTTGCTCTCAGCGATGAGAGGCAA-1_CD4i_R2L42',
 'TTTGCTCTCAGCGATGAGTGAGTG-1_CD4i_R2L27',
 'TTTGCTCTCAGCGGGTACTACTCA-1_CD4i_R2L45',
 'TTTGCTCTCAGCGGGTAGAGGCAA-1_CD4i_R2L26',
 'TTTGCTCTCAGCGGGTAGTGAGTG-1_CD4i_R2L35',
 'TTTGCTCTCAGCTACCAGTGAGTG-1_CD4i_R2L38',
 'TTTGCTCTCAGGAGCCACTACTCA-1_CD4i_R2L28',
 'TTTGCTCTCAGGCAATACAGTCTG-1_CD4i_R2L26',
 'TTTGCTCTCAGGCAATACAGTCTG-1_CD4i_R2L38',
 'TTTGCTCTCAGGCAATACAGTCTG-1_CD4i_R2L44',
 'TTTGCTCTCAGGCAATAGAGGCAA-1_CD4i_R2L44',
 'TTTGCTCTCAGGCAATAGAGGCAA-1_CD4i_R2L46',
 'TTTGCTCTCAGGCATGACAGTCTG-1_CD4i_R2L33',
 'TTTGCTCTCAGGCATGAGTGAGTG-1_CD4i_R2L27',
 'TTTGCTCTCAGGCCAAAGTGAGTG-1_CD4i_R2L44',
 'TTTGCTCTCAGGCCTTACAGTCTG-1_CD4i_R2L26',
 'TTTGCTCTCAGGCCTTAGAGGCAA-1_CD4i_R2L27',
 'TTTGCTCTCAGGCCTTAGTGAGTG-1_CD4i_R2L26',
 'TTTGCTCTCAGGCCTTAGTGAGTG-1_CD4i_R2L46',
 'TTTGCTCTCAGGCTGAACAGTCTG-1_CD4i_R2L31',
 'TTTGCTCTCAGGCTGAACTACTCA-1_CD4i_R2L36',
 'TTTGCTCTCAGGCTGAAGTGAGTG-1_CD4i_R2L43',
 'TTTGCTCTCAGGGATTACAGTCTG-1_CD4i_R2L31',
 'TTTGCTCTCAGGGATTACAGTCTG-1_CD4i_R2L35',
 'TTTGCTCTCAGGGATTACTACTCA-1_CD4i_R2L27',
 'TTTGCTCTCAGGGATTACTACTCA-1_CD4i_R2L36',
 'TTTGCTCTCAGGGATTAGAGGCAA-1_CD4i_R2L40',
 'TTTGCTCTCAGGGCACACAGTCTG-1_CD4i_R2L30',
 'TTTGCTCTCAGGGCACACTACTCA-1_CD4i_R2L30',
 'TTTGCTCTCAGGTAACACAGTCTG-1_CD4i_R2L34',
 'TTTGCTCTCAGGTAACACAGTCTG-1_CD4i_R2L47',
 'TTTGCTCTCAGGTAACAGAGGCAA-1_CD4i_R2L29',
 'TTTGCTCTCAGGTAACAGAGGCAA-1_CD4i_R2L34',
 'TTTGCTCTCAGGTAGTACAGTCTG-1_CD4i_R2L38',
 'TTTGCTCTCAGGTAGTAGAGGCAA-1_CD4i_R2L31',
 'TTTGCTCTCAGGTAGTAGAGGCAA-1_CD4i_R2L33',
 'TTTGCTCTCAGGTAGTAGAGGCAA-1_CD4i_R2L46',
 'TTTGCTCTCAGGTAGTAGTGAGTG-1_CD4i_R2L46',
 'TTTGCTCTCAGGTCGAACAGTCTG-1_CD4i_R2L35',
 'TTTGCTCTCAGGTCGAAGTGAGTG-1_CD4i_R2L31',
 'TTTGCTCTCAGGTCGAAGTGAGTG-1_CD4i_R2L41',
 'TTTGCTCTCAGGTTAAACAGTCTG-1_CD4i_R2L47',
 'TTTGCTCTCAGGTTAAACTACTCA-1_CD4i_R2L48',
 'TTTGCTCTCAGGTTAAAGAGGCAA-1_CD4i_R2L39',
 'TTTGCTCTCAGGTTAAAGTGAGTG-1_CD4i_R2L38',
 'TTTGCTCTCAGGTTGGAGAGGCAA-1_CD4i_R2L48',

### Add guide RNA information

In [9]:
# download the guide RNA spreadsheet
download_file(
    url="https://raw.githubusercontent.com/emdann/GWT_perturbseq_analysis_2025/refs/heads/master/metadata/suppl_tables/sgrna_library_metadata.suppl_table.csv",
    dest_path="../supplementary/zhu_2025_guide_info.csv"
)
# read in the guide RNA info csv
guide_info_df = pd.read_csv("../supplementary/zhu_2025_guide_info.csv")

guide_info_df = guide_info_df[['sgRNA', 'seq']]

guide_info_df['sgRNA'] = guide_info_df['sgRNA'].str.replace('1-Jun','JUN-1').str.replace('2-Jun','JUN-2')

guide_info_df = guide_info_df.rename(columns={'seq': 'guide_sequence', 'sgRNA':'guide_id'})

guide_info_df

File ../supplementary/zhu_2025_guide_info.csv already exists. Skipping download.

        guide_id        guide_sequence
0        ARMC5-1  CTGCCTCGCGCAGCTCGCGG
1         DDB1-1  GGAGTTCGCTGCGCGCTGTT
2       FNDC10-1  TGCCCGCTCCCCGCGATCCC
3         RORC-1  TCTGTGGGGCCCTGTCCATG
4      SLC35F6-1  GAACAGCTGGTACTTGGTCC
...          ...                   ...
26499    NTC-988  TTTCAGGCTACGGGCGCGGG
26500    NTC-989  TTTCCCATGATCATTTAGTG
26501    NTC-990  TTTCGCCCAAGAGGCTTGGG
26502    NTC-991  TTTCGTGCCGATGTAACACA
26503    NTC-992  TTTGGGTTTATCCGCCCCCA

[26504 rows x 2 columns]

In [10]:
print("Number of overlapping guides with cur_data:")
cur_data.adata.obs['guide_id'].isin(guide_info_df['guide_id'].to_list()).value_counts()

Number of overlapping guides with cur_data:

guide_id
True     1896516
False     263885
Name: count, dtype: int64

In [11]:
# merge cur_data.adata.obs with guide_info_df
cur_data.adata.obs = cur_data.adata.obs.merge(guide_info_df, on='guide_id', how='left')
# check that there are no missing guide sequences
print(f"Number of missing guide sequences: {cur_data.adata.obs['guide_sequence'].isna().sum()}")

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

Number of missing guide sequences: 263885

In [12]:
cur_data.adata.obs

,lane_id,n_genes_by_counts,total_counts,pct_counts_mt,top_guide_UMI_counts,guide_id,perturbed_gene_name,perturbed_gene_id,guide_type,PuroR,guide_group,low_quality,cell_barcode,perturbation_name,guide_sequence
0,CD4i_R2L32,5101,12866.0,1.375719,NaN,NaN,NaN,NaN,NaN,3.134436,no sgRNA,False,AAACAAGCAAACCCAAACTACTCA-1,AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32,NaN
1,CD4i_R2L32,5994,23121.0,0.047576,297.0,ALX3-2,ALX3,ENSG00000156150,targeting,3.277925,targeting single sgRNA,False,AAACAAGCAAACCCAAAGTGAGTG-1,AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32,GGTGCAGGCCCCACGCGGAA
2,CD4i_R2L32,3575,7659.0,0.287244,21.0,FAM210B-1,FAM210B,ENSG00000124098,targeting,3.827360,targeting single sgRNA,False,AAACAAGCAAACCGTAAGTGAGTG-1,AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32,GCTGGGTCCGGCAGGCAGGG
3,CD4i_R2L32,2795,5204.0,0.153728,155.0,NTC-846,NTC,NTC,non-targeting,1.744745,targeting single sgRNA,False,AAACAAGCAAATACCGACAGTCTG-1,AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32,GGGTGGTCATTCTCTACTTG
4,CD4i_R2L32,6745,30883.0,0.777127,931.0,GATA1-1,GATA1,ENSG00000102145,targeting,3.230057,targeting single sgRNA,False,AAACAAGCAACCGTAAACAGTCTG-1,AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32,GGCAAGCTCAGTGTGATCCC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2160396,CD4i_R2L48,5621,18304.0,1.005245,134.0,TPBG-2,TPBG,ENSG00000146242,targeting,2.547603,targeting single sgRNA,False,TTTGTGAGTTGGGTTTAGAGGCAA-1,TTTGTGAGTTGGGTTTAGAGGCAA-1_CD4i_R2L48,GAACTCAGAGTTGGTTCTGG
2160397,CD4i_R2L48,3075,7043.0,0.070992,528.0,IFRD1-2,IFRD1,ENSG00000006652,targeting,2.604208,targeting single sgRNA,False,TTTGTGAGTTTACGACAGAGGCAA-1,TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48,AACAGAGTCGAGAAGCGGCG
2160398,CD4i_R2L48,3497,7250.0,0.358621,75.0,GALNT1-1,GALNT1,ENSG00000141429,targeting,1.620248,targeting single sgRNA,False,TTTGTGAGTTTACGACAGTGAGTG-1,TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48,GTCCAAGAGTACCCAAATCA
2160399,CD4i_R2L48,3687,7890.0,0.088720,47.0,CTSK-1,CTSK,ENSG00000143387,targeting,2.911565,targeting single sgRNA,False,TTTGTGAGTTTCCTCAACAGTCTG-1,TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48,GTATATATATAAATCATACA
2160400,CD4i_R2L48,5306,15622.0,0.307259,120.0,LIN28B-1,LIN28B,ENSG00000187772,targeting,3.133394,targeting single sgRNA,False,TTTGTGAGTTTGCATAACTACTCA-1,TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48,GCTCTCCGGCGGGCACGAGG

In [13]:
# change perturbed_gene_id from categorical to string
cur_data.adata.obs['perturbed_gene_id'] = cur_data.adata.obs['perturbed_gene_id'].astype(str)
cur_data.adata.obs['perturbed_gene_name'] = cur_data.adata.obs['perturbed_gene_name'].astype(str)

cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_id'].isin(['NTC']), 'perturbed_gene_id'] = 'control_nontargeting'
cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_name'].isin(['NTC']), 'perturbed_gene_name'] = 'control_nontargeting'

cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_id'].isna(), 'perturbed_gene_id'] = 'control_casonly'
cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_name'].isna(), 'perturbed_gene_name'] = 'control_casonly'

### Standardise perturbation targets

In [14]:
cur_data.standardize_genes(
    slot='obs',
    input_column='perturbed_gene_id',
    input_column_type='ensembl_gene_id',
    multiple_entries=False,
    # remove_version=True,
    # version_sep='.'
)

Missing Ensembl IDs: ['SGK494', 'AKAP2', 'ENSG00000277796', 'ENSG00000255823', 'ENSG00000182230', 'SEPT6', 'ENSG00000232196', 'SMIM11B', 'ENSG00000148362', 'LUZP6', 'ENSG00000203812', 'OCLM', 'ENSG00000256618']; attempting to fetch latest IDs...
Fetched latest Ensembl IDs: {'ENSG00000277796': 'ENSG00000293545', 'ENSG00000255823': nan, 'ENSG00000182230': nan, 'ENSG00000232196': nan, 'ENSG00000148362': 'ENSG00000310560', 'ENSG00000203812': 'ENSG00000288825', 'ENSG00000256618': nan}
--------------------------------------------------
Successfully mapped 11839 out of 11839 Ensembl IDs.
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [15]:
cur_data.adata.obs

,cell_barcode,n_genes_by_counts,PuroR,perturbed_gene_name,guide_id,total_counts,guide_group,lane_id,guide_type,perturbation_name,low_quality,guide_sequence,perturbed_gene_id,top_guide_UMI_counts,pct_counts_mt,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index
index,,,,,,,,,,,,,,,,,,,,,
0,AAACAAGCAAACCCAAACTACTCA-1,5101,3.134436,nan,NaN,12866.0,no sgRNA,CD4i_R2L32,NaN,AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32,False,NaN,nan,NaN,1.375719,nan,NaN,NaN,NaN,NaN,0
1,AAACAAGCAAACCCAAAGTGAGTG-1,5994,3.277925,ALX3,ALX3-2,23121.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32,False,GGTGCAGGCCCCACGCGGAA,ENSG00000156150,297.0,0.047576,ENSG00000156150,ALX3,protein_coding,chr1:110059870-110070672;-1,1,1
2,AAACAAGCAAACCGTAAGTGAGTG-1,3575,3.827360,FAM210B,FAM210B-1,7659.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32,False,GCTGGGTCCGGCAGGCAGGG,ENSG00000124098,21.0,0.287244,ENSG00000124098,FAM210B,protein_coding,chr20:56358974-56368663;1,20,2
3,AAACAAGCAAATACCGACAGTCTG-1,2795,1.744745,control_nontargeting,NTC-846,5204.0,targeting single sgRNA,CD4i_R2L32,non-targeting,AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32,False,GGGTGGTCATTCTCTACTTG,control_nontargeting,155.0,0.153728,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,3
4,AAACAAGCAACCGTAAACAGTCTG-1,6745,3.230057,GATA1,GATA1-1,30883.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32,False,GGCAAGCTCAGTGTGATCCC,ENSG00000102145,931.0,0.777127,ENSG00000102145,GATA1,protein_coding,chrX:48786540-48794311;1,X,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2160396,TTTGTGAGTTGGGTTTAGAGGCAA-1,5621,2.547603,TPBG,TPBG-2,18304.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTGGGTTTAGAGGCAA-1_CD4i_R2L48,False,GAACTCAGAGTTGGTTCTGG,ENSG00000146242,134.0,1.005245,ENSG00000146242,TPBG,protein_coding,chr6:82363206-82367420;1,6,2160396
2160397,TTTGTGAGTTTACGACAGAGGCAA-1,3075,2.604208,IFRD1,IFRD1-2,7043.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48,False,AACAGAGTCGAGAAGCGGCG,ENSG00000006652,528.0,0.070992,ENSG00000006652,IFRD1,protein_coding,chr7:112422887-112481017;1,7,2160397
2160398,TTTGTGAGTTTACGACAGTGAGTG-1,3497,1.620248,GALNT1,GALNT1-1,7250.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48,False,GTCCAAGAGTACCCAAATCA,ENSG00000141429,75.0,0.358621,ENSG00000141429,GALNT1,protein_coding,chr18:35580892-35713370;1,18,2160398
2160399,TTTGTGAGTTTCCTCAACAGTCTG-1,3687,2.911565,CTSK,CTSK-1,7890.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48,False,GTATATATATAAATCATACA,ENSG00000143387,47.0,0.088720,ENSG00000143387,CTSK,protein_coding,chr1:150794880-150809577;-1,1,2160399
2160400,TTTGTGAGTTTGCATAACTACTCA-1,5306,3.133394,LIN28B,LIN28B-1,15622.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48,False,GCTCTCCGGCGGGCACGAGG,ENSG00000187772,120.0,0.307259,ENSG00000187772,LIN28B,protein_coding,chr6:104936616-105083332;1,6,2160400

# Manually replace some genes

In [16]:
# define genes to replace in the cur_data.adata.obs
genes_to_replace = cur_data.adata.obs[cur_data.adata.obs['perturbed_target_symbol'].isna()]['perturbed_gene_name'].drop_duplicates().to_list()
# define columns to replace
cols_to_replace = ['perturbed_target_ensg',	'perturbed_target_symbol',	'perturbed_target_biotype',	'perturbed_target_coord',	'perturbed_target_chromosome']
# define mapping dict for renaming columns in gene_ont for replacement
gene_ont_col_mapping = {
    'ensembl_gene_id':'perturbed_target_ensg',
    'gene_symbol':'perturbed_target_symbol',
    'biotype':'perturbed_target_biotype',
    'gene_coord':'perturbed_target_coord',
    'chromosome_name':'perturbed_target_chromosome'
}
# loop through genes and fill in the missing cols
for replacement_gene in genes_to_replace:
    if replacement_gene in cur_data.gene_ont['synonym'].values:
        # subset gene_ont and get values for replacement
        replacement = (
            cur_data.gene_ont.rename(columns=gene_ont_col_mapping)
            .loc[cur_data.gene_ont['synonym'].isin([replacement_gene]), cols_to_replace]
        )[cols_to_replace].values[0]
        # replace values in cur_data.adata.obs with the values from gene_ont
        cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_gene_name'].isin([replacement_gene]), cols_to_replace] = replacement
        print(f"Replaced {replacement_gene} with {replacement}")
    else:
        print(f"No replacement found for {replacement_gene}")

No replacement found for nan
No replacement found for MTRNR2L8
No replacement found for AKAP2
No replacement found for FAM153B
No replacement found for OCLM
No replacement found for LUZP6
No replacement found for MTRNR2L1
Replaced SGK494 with ['ENSG00000167524' 'RSKR' 'protein_coding' 'chr17:28455752-28614197;-1'
 '17']
Replaced SEPT6 with ['ENSG00000125354' 'SEPTIN6' 'protein_coding'
 'chrX:119615724-119693949;-1' 'X']
No replacement found for CCL3L1
No replacement found for MTRNR2L4
No replacement found for SMIM11B

In [17]:
# replace non-mapped perturbed_target_symbol with original gene symbols
cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_target_symbol'].isna(), 'perturbed_target_symbol'] = cur_data.adata.obs.loc[cur_data.adata.obs['perturbed_target_symbol'].isna(), 'perturbed_gene_name'].values

In [18]:
# replace entries in perturbed_target_ensg that are not ENSEMBL ids with NA
cur_data.adata.obs.loc[(~cur_data.adata.obs['perturbed_target_ensg'].str.startswith('ENSG')) & (cur_data.adata.obs['perturbed_target_ensg'] != 'control_nontargeting'), 'perturbed_target_ensg'] = pd.NA

In [19]:
cur_data.adata.obs

,cell_barcode,n_genes_by_counts,PuroR,perturbed_gene_name,guide_id,total_counts,guide_group,lane_id,guide_type,perturbation_name,low_quality,guide_sequence,perturbed_gene_id,top_guide_UMI_counts,pct_counts_mt,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index
index,,,,,,,,,,,,,,,,,,,,,
0,AAACAAGCAAACCCAAACTACTCA-1,5101,3.134436,nan,NaN,12866.0,no sgRNA,CD4i_R2L32,NaN,AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32,False,NaN,nan,NaN,1.375719,<NA>,nan,NaN,NaN,NaN,0
1,AAACAAGCAAACCCAAAGTGAGTG-1,5994,3.277925,ALX3,ALX3-2,23121.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32,False,GGTGCAGGCCCCACGCGGAA,ENSG00000156150,297.0,0.047576,ENSG00000156150,ALX3,protein_coding,chr1:110059870-110070672;-1,1,1
2,AAACAAGCAAACCGTAAGTGAGTG-1,3575,3.827360,FAM210B,FAM210B-1,7659.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32,False,GCTGGGTCCGGCAGGCAGGG,ENSG00000124098,21.0,0.287244,ENSG00000124098,FAM210B,protein_coding,chr20:56358974-56368663;1,20,2
3,AAACAAGCAAATACCGACAGTCTG-1,2795,1.744745,control_nontargeting,NTC-846,5204.0,targeting single sgRNA,CD4i_R2L32,non-targeting,AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32,False,GGGTGGTCATTCTCTACTTG,control_nontargeting,155.0,0.153728,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,3
4,AAACAAGCAACCGTAAACAGTCTG-1,6745,3.230057,GATA1,GATA1-1,30883.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32,False,GGCAAGCTCAGTGTGATCCC,ENSG00000102145,931.0,0.777127,ENSG00000102145,GATA1,protein_coding,chrX:48786540-48794311;1,X,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2160396,TTTGTGAGTTGGGTTTAGAGGCAA-1,5621,2.547603,TPBG,TPBG-2,18304.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTGGGTTTAGAGGCAA-1_CD4i_R2L48,False,GAACTCAGAGTTGGTTCTGG,ENSG00000146242,134.0,1.005245,ENSG00000146242,TPBG,protein_coding,chr6:82363206-82367420;1,6,2160396
2160397,TTTGTGAGTTTACGACAGAGGCAA-1,3075,2.604208,IFRD1,IFRD1-2,7043.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48,False,AACAGAGTCGAGAAGCGGCG,ENSG00000006652,528.0,0.070992,ENSG00000006652,IFRD1,protein_coding,chr7:112422887-112481017;1,7,2160397
2160398,TTTGTGAGTTTACGACAGTGAGTG-1,3497,1.620248,GALNT1,GALNT1-1,7250.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48,False,GTCCAAGAGTACCCAAATCA,ENSG00000141429,75.0,0.358621,ENSG00000141429,GALNT1,protein_coding,chr18:35580892-35713370;1,18,2160398
2160399,TTTGTGAGTTTCCTCAACAGTCTG-1,3687,2.911565,CTSK,CTSK-1,7890.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48,False,GTATATATATAAATCATACA,ENSG00000143387,47.0,0.088720,ENSG00000143387,CTSK,protein_coding,chr1:150794880-150809577;-1,1,2160399
2160400,TTTGTGAGTTTGCATAACTACTCA-1,5306,3.133394,LIN28B,LIN28B-1,15622.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48,False,GCTCTCCGGCGGGCACGAGG,ENSG00000187772,120.0,0.307259,ENSG00000187772,LIN28B,protein_coding,chr6:104936616-105083332;1,6,2160400

### Add `perturbed_target_number` column

In [20]:
# cur_data.count_entries(
#     slot='obs',
#     input_column='perturbed_target_ensg',
#     count_column_name='perturbed_target_number',
#     sep='|'
# )
cur_data.adata.obs['perturbed_target_number'] = 1

### Encode chromosomes as integers

In [21]:
cur_data.chromosome_encoding()

Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.

In [22]:
cur_data.adata.obs[['perturbation_name', 'perturbed_target_chromosome_encoding']]

,perturbation_name,perturbed_target_chromosome_encoding
index,,
0,AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32,0
1,AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32,1
2,AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32,20
3,AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32,0
4,AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32,23
...,...,...
2160396,TTTGTGAGTTGGGTTTAGAGGCAA-1_CD4i_R2L48,6
2160397,TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48,7
2160398,TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48,18
2160399,TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48,1
2160400,TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48,6

In [23]:
cur_data.adata.obs

,cell_barcode,n_genes_by_counts,PuroR,perturbed_gene_name,guide_id,total_counts,guide_group,lane_id,guide_type,perturbation_name,low_quality,guide_sequence,perturbed_gene_id,top_guide_UMI_counts,pct_counts_mt,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding
index,,,,,,,,,,,,,,,,,,,,,,,
0,AAACAAGCAAACCCAAACTACTCA-1,5101,3.134436,nan,NaN,12866.0,no sgRNA,CD4i_R2L32,NaN,AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32,False,NaN,nan,NaN,1.375719,<NA>,nan,NaN,NaN,NaN,0,1,0
1,AAACAAGCAAACCCAAAGTGAGTG-1,5994,3.277925,ALX3,ALX3-2,23121.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32,False,GGTGCAGGCCCCACGCGGAA,ENSG00000156150,297.0,0.047576,ENSG00000156150,ALX3,protein_coding,chr1:110059870-110070672;-1,1,1,1,1
2,AAACAAGCAAACCGTAAGTGAGTG-1,3575,3.827360,FAM210B,FAM210B-1,7659.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32,False,GCTGGGTCCGGCAGGCAGGG,ENSG00000124098,21.0,0.287244,ENSG00000124098,FAM210B,protein_coding,chr20:56358974-56368663;1,20,2,1,20
3,AAACAAGCAAATACCGACAGTCTG-1,2795,1.744745,control_nontargeting,NTC-846,5204.0,targeting single sgRNA,CD4i_R2L32,non-targeting,AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32,False,GGGTGGTCATTCTCTACTTG,control_nontargeting,155.0,0.153728,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,3,1,0
4,AAACAAGCAACCGTAAACAGTCTG-1,6745,3.230057,GATA1,GATA1-1,30883.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32,False,GGCAAGCTCAGTGTGATCCC,ENSG00000102145,931.0,0.777127,ENSG00000102145,GATA1,protein_coding,chrX:48786540-48794311;1,X,4,1,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2160396,TTTGTGAGTTGGGTTTAGAGGCAA-1,5621,2.547603,TPBG,TPBG-2,18304.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTGGGTTTAGAGGCAA-1_CD4i_R2L48,False,GAACTCAGAGTTGGTTCTGG,ENSG00000146242,134.0,1.005245,ENSG00000146242,TPBG,protein_coding,chr6:82363206-82367420;1,6,2160396,1,6
2160397,TTTGTGAGTTTACGACAGAGGCAA-1,3075,2.604208,IFRD1,IFRD1-2,7043.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48,False,AACAGAGTCGAGAAGCGGCG,ENSG00000006652,528.0,0.070992,ENSG00000006652,IFRD1,protein_coding,chr7:112422887-112481017;1,7,2160397,1,7
2160398,TTTGTGAGTTTACGACAGTGAGTG-1,3497,1.620248,GALNT1,GALNT1-1,7250.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48,False,GTCCAAGAGTACCCAAATCA,ENSG00000141429,75.0,0.358621,ENSG00000141429,GALNT1,protein_coding,chr18:35580892-35713370;1,18,2160398,1,18
2160399,TTTGTGAGTTTCCTCAACAGTCTG-1,3687,2.911565,CTSK,CTSK-1,7890.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48,False,GTATATATATAAATCATACA,ENSG00000143387,47.0,0.088720,ENSG00000143387,CTSK,protein_coding,chr1:150794880-150809577;-1,1,2160399,1,1
2160400,TTTGTGAGTTTGCATAACTACTCA-1,5306,3.133394,LIN28B,LIN28B-1,15622.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48,False,GCTCTCCGGCGGGCACGAGG,ENSG00000187772,120.0,0.307259,ENSG00000187772,LIN28B,protein_coding,chr6:104936616-105083332;1,6,2160400,1,6

### Curate replicates

In [24]:
cur_data.adata.obs = cur_data.adata.obs.rename(columns={'lane_id':'technical_replicate'})

### Add metadata

In [25]:
cur_data.create_columns(
    overwrite=True,
    slot="obs",
    col_dict={
        "dataset_id": cur_data.dataset_id,
        "sample_id": range(1, cur_data.adata.obs.shape[0] + 1),
        # perturbation type
        "perturbation_type_label": "CRISPRi",
        "perturbation_type_id": None,
        "data_modality": "Perturb-seq",
        "significant": None,
        "significance_criteria": None,
        "score_interpretation": None,

        # treatment
        "treatment_label": "anti-CD3 antibody|anti-CD28 antibody|anti-CD2 antibody",
        "treatment_id": "EFO:0003317|EFO:0003304|NCIT:C184729",
        # replicates
        # "technical_replicate": None,
        "biological_replicate": "D3_CE0008678",
        # model system
        "model_system_label": "primary_cell",
        "model_system_id": None,
        "tissue": "lymphoid tissue",
        "cell_line_label": None,
        "cell_line_id": None,
        "cell_type_label": "CD4-positive, alpha-beta T cell",
        "disease_label": "healthy",
        "disease_id": None,

        "timepoint": "P14DT0H0M0S",
        "species": "Homo sapiens",
        "sex_label": "female",
        "sex_id": None,
        "developmental_stage_label": "adult",
        "developmental_stage_id": None,

        "study_title": "Genome-scale perturb-seq in primary human CD4+ T cells maps context-specific regulators of T cell programs and human immune traits",
        "study_uri": "https://doi.org/10.64898/2025.12.23.696273",
        "study_year": 2025,
        "first_author": "Ronghui Zhu",
        "last_author": "Alexander Marson",

        "experiment_title": "Perturb-seq of primary human CD4-positive T cells for patient D3_CE0008678, stimulated for 48hr with ImmunoCult CD3/CD28/CD2 activator",
        "experiment_summary": """
            Isolated human CD4-positive cells from four healthy donors were stimulated with ImmunoCult CD3/CD28/CD2 activator and sequentially transduced with dCas9-KRAB-Zim3 lentivirus (next morning after stimulation) and a Perturb-seq guide library (next afternoon after stimulation, MOI 0.2).
            The library consisted all genes expressed in human CD4+ T cells, all transcription factors annotated in the Lambert et al. (2018) and non-targeting controls totalling 12,748 genes.
            The gRNA sequences were selected from hCRISPRiv2 and Dolcetto libraries.
            On day 12, cells were split into three conditions:
            (1) Rest - cells were left for 8 hr without stimulation;
            (2) Stim8hr - cells were stimulated with ImmunoCult CD3/CD28/CD2 activator for 8 hr;
            (3) Stim48hr - cells were stimulated with ImmunoCult CD3/CD28/CD2 activator for 48 hr.
            Cells were harvested, fixed, stored using GEM-X Flex Sample Preparation v2 Kit and sequenced using GEM-X Flex Gene Expression Human n-plex kit converted into Ultima compatible libraries for sequencing on the Ultima Genomics UG100.
            """,

        "number_of_perturbed_targets": len(set(cur_data.adata.obs['perturbed_target_symbol'])),
        "number_of_perturbed_samples": cur_data.adata.obs.shape[0],

        "library_generation_type_id": "EFO:0022868",
        "library_generation_type_label": "endogenous",

        "library_generation_method_id": None,
        "library_generation_method_label": "dCas9-KRAB-Zim3",

        "enzyme_delivery_method_id": None,
        "enzyme_delivery_method_label": "lentivirus transduction",

        "library_delivery_method_id": None,
        "library_delivery_method_label": "lentivirus transduction",

        "enzyme_integration_state_id": None,
        "enzyme_integration_state_label": "random locus integration",

        "library_integration_state_id": None,
        "library_integration_state_label": "random locus integration",

        "enzyme_expression_control_id": None,
        "enzyme_expression_control_label": "constitutive transgene expression",

        "library_expression_control_id": None,
        "library_expression_control_label": "constitutive transgene expression",

        "library_name": "custom",
        "library_uri": None,

        "library_format_id": None,
        "library_format_label": "pooled",

        "library_scope_id": None,
        "library_scope_label": "focused",

        "library_perturbation_type_id": None,
        "library_perturbation_type_label": "inhibition",

        "library_manufacturer": "Marson lab",
        "library_lentiviral_generation": "2",
        "library_grnas_per_target": "2",
        "library_total_grnas": str(cur_data.adata.obs['guide_sequence'].str.split('|').explode().nunique()),
        "library_total_variants": None,

        "readout_dimensionality_id": None,
        "readout_dimensionality_label": "high-dimensional assay",

        "readout_type_id": None,
        "readout_type_label": "transcriptomic",

        "readout_technology_id": None,
        "readout_technology_label": "single-cell rna-seq",

        "method_name_id": None,
        "method_name_label": "Perturb-seq",

        "method_uri": None,

        "sequencing_library_kit_id": None,
        "sequencing_library_kit_label": "GEM-X Flex Gene Expression Human n-plex kit",

        "sequencing_platform_id": None,
        "sequencing_platform_label": "Ultima Genomics UG100",

        "sequencing_strategy_id": None,
        "sequencing_strategy_label": "barcode sequencing",

        "software_counts_id": None,
        "software_counts_label": "CellRanger",

        "software_analysis_id": None,
        "software_analysis_label": "scanpy",

        "reference_genome_id": None,
        "reference_genome_label": "GRCh38",

        "license_label": "MIT License",
        "license_id": "SWO:9000074",

        "associated_datasets": json.dumps([
            {
                "dataset_accession": "Primary Human CD4+ T Cell Perturb-seq",
                "dataset_uri": "s3://genome-scale-tcell-perturb-seq/marson2025_data/D3_Stim48hr.assigned_guide.h5ad",
                "dataset_description": "Cell expression profiles for cells from donor D3_CE0008678, stimulated for 48hr with ImmunoCult CD3/CD28/CD2 activator.",
                "dataset_file_name": "D3_Stim48hr.assigned_guide.h5ad",
            }
        ])
    }
)

Column dataset_id added to adata.obs
Column sample_id added to adata.obs
Column perturbation_type_label added to adata.obs
Column perturbation_type_id added to adata.obs
Column data_modality added to adata.obs
Column significant added to adata.obs
Column significance_criteria added to adata.obs
Column score_interpretation added to adata.obs
Column treatment_label added to adata.obs
Column treatment_id added to adata.obs
Column biological_replicate added to adata.obs
Column model_system_label added to adata.obs
Column model_system_id added to adata.obs
Column tissue added to adata.obs
Column cell_line_label added to adata.obs
Column cell_line_id added to adata.obs
Column cell_type_label added to adata.obs
Column disease_label added to adata.obs
Column disease_id added to adata.obs
Column timepoint added to adata.obs
Column species added to adata.obs
Column sex_label added to adata.obs
Column sex_id added to adata.obs
Column developmental_stage_label added to adata.obs
Column developmental_stage_id added to adata.obs
Column study_title added to adata.obs
Column study_uri added to adata.obs
Column study_year added to adata.obs
Column first_author added to adata.obs
Column last_author added to adata.obs
Column experiment_title added to adata.obs
Column experiment_summary added to adata.obs
Column number_of_perturbed_targets added to adata.obs
Column number_of_perturbed_samples added to adata.obs
Column library_generation_type_id added to adata.obs
Column library_generation_type_label added to adata.obs
Column library_generation_method_id added to adata.obs
Column library_generation_method_label added to adata.obs
Column enzyme_delivery_method_id added to adata.obs
Column enzyme_delivery_method_label added to adata.obs
Column library_delivery_method_id added to adata.obs
Column library_delivery_method_label added to adata.obs
Column enzyme_integration_state_id added to adata.obs
Column enzyme_integration_state_label added to adata.obs
Column library_integration_state_id added to adata.obs
Column library_integration_state_label added to adata.obs
Column enzyme_expression_control_id added to adata.obs
Column enzyme_expression_control_label added to adata.obs
Column library_expression_control_id added to adata.obs
Column library_expression_control_label added to adata.obs
Column library_name added to adata.obs
Column library_uri added to adata.obs
Column library_format_id added to adata.obs
Column library_format_label added to adata.obs
Column library_scope_id added to adata.obs
Column library_scope_label added to adata.obs
Column library_perturbation_type_id added to adata.obs
Column library_perturbation_type_label added to adata.obs
Column library_manufacturer added to adata.obs
Column library_lentiviral_generation added to adata.obs
Column library_grnas_per_target added to adata.obs
Column library_total_grnas added to adata.obs
Column library_total_variants added to adata.obs
Column readout_dimensionality_id added to adata.obs
Column readout_dimensionality_label added to adata.obs
Column readout_type_id added to adata.obs
Column readout_type_label added to adata.obs
Column readout_technology_id added to adata.obs
Column readout_technology_label added to adata.obs
Column method_name_id added to adata.obs
Column method_name_label added to adata.obs
Column method_uri added to adata.obs
Column sequencing_library_kit_id added to adata.obs
Column sequencing_library_kit_label added to adata.obs
Column sequencing_platform_id added to adata.obs
Column sequencing_platform_label added to adata.obs
Column sequencing_strategy_id added to adata.obs
Column sequencing_strategy_label added to adata.obs
Column software_counts_id added to adata.obs
Column software_counts_label added to adata.obs
Column software_analysis_id added to adata.obs
Column software_analysis_label added to adata.obs
Column reference_genome_id added to adata.obs
Column reference_genome_label added to adata.obs
Column license_label added to adata.obs
Column license_id added to adata.obs
Column associated_datasets added to adata.obs

In [26]:
cur_data.adata.obs

,cell_barcode,n_genes_by_counts,PuroR,perturbed_gene_name,guide_id,total_counts,guide_group,technical_replicate,guide_type,perturbation_name,low_quality,guide_sequence,perturbed_gene_id,top_guide_UMI_counts,pct_counts_mt,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,perturbed_target_coord,perturbed_target_chromosome,original_index,perturbed_target_number,perturbed_target_chromosome_encoding,dataset_id,sample_id,perturbation_type_label,perturbation_type_id,data_modality,significant,significance_criteria,score_interpretation,treatment_label,treatment_id,biological_replicate,model_system_label,model_system_id,tissue,cell_line_label,cell_line_id,cell_type_label,disease_label,disease_id,timepoint,species,sex_label,sex_id,developmental_stage_label,developmental_stage_id,study_title,study_uri,study_year,first_author,last_author,experiment_title,experiment_summary,number_of_perturbed_targets,number_of_perturbed_samples,library_generation_type_id,library_generation_type_label,library_generation_method_id,library_generation_method_label,enzyme_delivery_method_id,enzyme_delivery_method_label,library_delivery_method_id,library_delivery_method_label,enzyme_integration_state_id,enzyme_integration_state_label,library_integration_state_id,library_integration_state_label,enzyme_expression_control_id,enzyme_expression_control_label,library_expression_control_id,library_expression_control_label,library_name,library_uri,library_format_id,library_format_label,library_scope_id,library_scope_label,library_perturbation_type_id,library_perturbation_type_label,library_manufacturer,library_lentiviral_generation,library_grnas_per_target,library_total_grnas,library_total_variants,readout_dimensionality_id,readout_dimensionality_label,readout_type_id,readout_type_label,readout_technology_id,readout_technology_label,method_name_id,method_name_label,method_uri,sequencing_library_kit_id,sequencing_library_kit_label,sequencing_platform_id,sequencing_platform_label,sequencing_strategy_id,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,reference_genome_id,reference_genome_label,license_label,license_id,associated_datasets
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,AAACAAGCAAACCCAAACTACTCA-1,5101,3.134436,nan,NaN,12866.0,no sgRNA,CD4i_R2L32,NaN,AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32,False,NaN,nan,NaN,1.375719,<NA>,nan,NaN,NaN,NaN,0,1,0,zhu_2025_D3_stim48hr_cl,1,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
1,AAACAAGCAAACCCAAAGTGAGTG-1,5994,3.277925,ALX3,ALX3-2,23121.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32,False,GGTGCAGGCCCCACGCGGAA,ENSG00000156150,297.0,0.047576,ENSG00000156150,ALX3,protein_coding,chr1:110059870-110070672;-1,1,1,1,1,zhu_2025_D3_stim48hr_cl,2,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2,AAACAAGCAAACCGTAAGTGAGTG-1,3575,3.827360,FAM210B,FAM210B-1,7659.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32,False,GCTGGGTCCGGCAGGCAGGG,ENSG00000124098,21.0,0.287244,ENSG00000124098,FAM210B,protein_coding,chr20:56358974-56368663;1,20,2,1,20,zhu_2025_D3_stim48hr_cl,3,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
3,AAACAAGCAAATACCGACAGTCTG-1,2795,1.744745,control_nontargeting,NTC-846,5204.0,targeting single sgRNA,CD4i_R2L32,non-targeting,AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32,False,GGGTGGTCATTCTCTACTTG,control_nontargeting,155.0,0.153728,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,control_nontargeting,3,1,0,zhu_2025_D3_stim48hr_cl,4,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
4,AAACAAGCAACCGTAAACAGTCTG-1,6745,3.230057,GATA1,GATA1-1,30883.0,targeting single sgRNA,CD4i_R2L32,targeting,AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32,False,GGCAAGCTCAGTGTGATCCC,ENSG00000102145,931.0,0.777127,ENSG00000102145,GATA1,protein_coding,chrX:48786540-48794311;1,X,4,1,23,zhu_2025_D3_stim48hr_cl,5,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2160396,TTTGTGAGTTGGGTTTAGAGGCAA-1,5621,2.547603,TPBG,TPBG-2,18304.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTGGGTTTAGAGGCAA-1_CD4i_R2L48,False,GAACTCAGAGTTGGTTCTGG,ENSG00000146242,134.0,1.005245,ENSG00000146242,TPBG,protein_coding,chr6:82363206-82367420;1,6,2160396,1,6,zhu_2025_D3_stim48hr_cl,2160397,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2160397,TTTGTGAGTTTACGACAGAGGCAA-1,3075,2.604208,IFRD1,IFRD1-2,7043.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48,False,AACAGAGTCGAGAAGCGGCG,ENSG00000006652,528.0,0.070992,ENSG00000006652,IFRD1,protein_coding,chr7:112422887-112481017;1,7,2160397,1,7,zhu_2025_D3_stim48hr_cl,2160398,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2160398,TTTGTGAGTTTACGACAGTGAGTG-1,3497,1.620248,GALNT1,GALNT1-1,7250.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48,False,GTCCAAGAGTACCCAAATCA,ENSG00000141429,75.0,0.358621,ENSG00000141429,GALNT1,protein_coding,chr18:35580892-35713370;1,18,2160398,1,18,zhu_2025_D3_stim48hr_cl,2160399,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2160399,TTTGTGAGTTTCCTCAACAGTCTG-1,3687,2.911565,CTSK,CTSK-1,7890.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48,False,GTATATATATAAATCATACA,ENSG00000143387,47.0,0.088720,ENSG00000143387,CTSK,protein_coding,chr1:150794880-150809577;-1,1,2160399,1,1,zhu_2025_D3_stim48hr_cl,2160400,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."
2160400,TTTGTGAGTTTGCATAACTACTCA-1,5306,3.133394,LIN28B,LIN28B-1,15622.0,targeting single sgRNA,CD4i_R2L48,targeting,TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48,False,GCTCTCCGGCGGGCACGAGG,ENSG00000187772,120.0,0.307259,ENSG00000187772,LIN28B,protein_coding,chr6:104936616-105083332;1,6,2160400,1,6,zhu_2025_D3_stim48hr_cl,2160401,CRISPRi,None,Perturb-seq,None,None,None,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,D3_CE0008678,primary_cell,None,lymphoid tissue,None,None,"CD4-positive, alpha-beta T cell",healthy,None,P14DT0H0M0S,Homo sapiens,female,None,adult,None,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,None,dCas9-KRAB-Zim3,None,lentivirus transduction,None,lentivirus transduction,None,random locus integration,None,random locus integration,None,constitutive transgene expression,None,constitutive transgene expression,custom,None,None,pooled,None,focused,None,inhibition,Marson lab,2,2,21186,None,None,high-dimensional assay,None,transcriptomic,None,single-cell rna-seq,None,Perturb-seq,None,None,GEM-X Flex Gene Expression Human n-plex kit,None,Ultima Genomics UG100,None,barcode sequencing,None,CellRanger,None,scanpy,None,GRCh38,MIT License,SWO:9000074,"[{""dataset_accession"": ""Primary Human CD4+ T C..."

### Curate tissue information

In [27]:
cur_data.standardize_ontology(
    input_column='tissue',
    column_type='term_name',
    ontology_type='tissue',
    overwrite=True
)

Mapped 1 tissue ontology terms from `tissue` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
      input_column input_column_lower       name_lower     ontology_id
0  lymphoid tissue    lymphoid tissue  lymphoid tissue  UBERON:0001744
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate cell type information

In [28]:
cur_data.standardize_ontology(
    input_column='cell_type_label',
    column_type='term_name',
    ontology_type='cell_type',
    overwrite=True
)

Mapped 1 cell_type ontology terms from `cell_type_label` column to ontology terms
DataFrame shape: (1, 4)
--------------------------------------------------
                      input_column               input_column_lower  \
0  CD4-positive, alpha-beta T cell  cd4-positive, alpha-beta t cell

                        name_lower ontology_id
0  cd4-positive, alpha-beta t cell  CL:0000624
--------------------------------------------------
Overwriting column cell_type_label in adata.obs

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

### Curate disease information

In [29]:
cur_data.standardize_ontology(
    input_column='disease_label',
    column_type='term_name',
    ontology_type='disease',
    overwrite=True
)

Warning: No disease ontology terms could be mapped from `disease_label` column to ontology terms. Map the terms manually or check the input column for errors.

### Match schema column order

In [30]:
cur_data.match_schema_columns(slot='obs')

Matched columns of adata.obs to the obs_schema.

### Validate obs metadata

In [31]:
cur_data.validate_data(slot='obs', verbose=True)

2026-02-18 10:13:54,965 INFO curation_tools.curation_tools: adata.obs is valid according to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,perturbed_target_ensg,perturbed_target_symbol,perturbed_target_biotype,guide_sequence,perturbation_type_label,perturbation_type_id,timepoint,treatment_label,treatment_id,technical_replicate,biological_replicate,model_system_label,model_system_id,species,tissue_label,tissue_id,cell_type_label,cell_type_id,cell_line_label,cell_line_id,sex_label,sex_id,developmental_stage_label,developmental_stage_id,disease_label,disease_id,study_title,study_uri,study_year,first_author,last_author,experiment_title,experiment_summary,number_of_perturbed_targets,number_of_perturbed_samples,library_generation_type_id,library_generation_type_label,library_generation_method_id,library_generation_method_label,enzyme_delivery_method_id,enzyme_delivery_method_label,library_delivery_method_id,library_delivery_method_label,enzyme_integration_state_id,enzyme_integration_state_label,library_integration_state_id,library_integration_state_label,enzyme_expression_control_id,enzyme_expression_control_label,library_expression_control_id,library_expression_control_label,library_name,library_uri,library_format_id,library_format_label,library_scope_id,library_scope_label,library_perturbation_type_id,library_perturbation_type_label,library_manufacturer,library_lentiviral_generation,library_grnas_per_target,library_total_grnas,library_total_variants,readout_dimensionality_id,readout_dimensionality_label,readout_type_id,readout_type_label,readout_technology_id,readout_technology_label,method_name_id,method_name_label,method_uri,sequencing_library_kit_id,sequencing_library_kit_label,sequencing_platform_id,sequencing_platform_label,sequencing_strategy_id,sequencing_strategy_label,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,zhu_2025_D3_stim48hr_cl,1,Perturb-seq,<NA>,<NA>,AAACAAGCAAACCCAAACTACTCA-1_CD4i_R2L32,<NA>,<NA>,0,1,<NA>,nan,<NA>,<NA>,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L32,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
1,zhu_2025_D3_stim48hr_cl,2,Perturb-seq,<NA>,<NA>,AAACAAGCAAACCCAAAGTGAGTG-1_CD4i_R2L32,chr1:110059870-110070672;-1,1,1,1,ENSG00000156150,ALX3,protein_coding,GGTGCAGGCCCCACGCGGAA,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L32,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2,zhu_2025_D3_stim48hr_cl,3,Perturb-seq,<NA>,<NA>,AAACAAGCAAACCGTAAGTGAGTG-1_CD4i_R2L32,chr20:56358974-56368663;1,20,20,1,ENSG00000124098,FAM210B,protein_coding,GCTGGGTCCGGCAGGCAGGG,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L32,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
3,zhu_2025_D3_stim48hr_cl,4,Perturb-seq,<NA>,<NA>,AAACAAGCAAATACCGACAGTCTG-1_CD4i_R2L32,control_nontargeting,control_nontargeting,0,1,control_nontargeting,control_nontargeting,control_nontargeting,GGGTGGTCATTCTCTACTTG,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L32,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
4,zhu_2025_D3_stim48hr_cl,5,Perturb-seq,<NA>,<NA>,AAACAAGCAACCGTAAACAGTCTG-1_CD4i_R2L32,chrX:48786540-48794311;1,X,23,1,ENSG00000102145,GATA1,protein_coding,GGCAAGCTCAGTGTGATCCC,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L32,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2160396,zhu_2025_D3_stim48hr_cl,2160397,Perturb-seq,<NA>,<NA>,TTTGTGAGTTGGGTTTAGAGGCAA-1_CD4i_R2L48,chr6:82363206-82367420;1,6,6,1,ENSG00000146242,TPBG,protein_coding,GAACTCAGAGTTGGTTCTGG,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L48,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2160397,zhu_2025_D3_stim48hr_cl,2160398,Perturb-seq,<NA>,<NA>,TTTGTGAGTTTACGACAGAGGCAA-1_CD4i_R2L48,chr7:112422887-112481017;1,7,7,1,ENSG00000006652,IFRD1,protein_coding,AACAGAGTCGAGAAGCGGCG,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L48,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2160398,zhu_2025_D3_stim48hr_cl,2160399,Perturb-seq,<NA>,<NA>,TTTGTGAGTTTACGACAGTGAGTG-1_CD4i_R2L48,chr18:35580892-35713370;1,18,18,1,ENSG00000141429,GALNT1,protein_coding,GTCCAAGAGTACCCAAATCA,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L48,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2160399,zhu_2025_D3_stim48hr_cl,2160400,Perturb-seq,<NA>,<NA>,TTTGTGAGTTTCCTCAACAGTCTG-1_CD4i_R2L48,chr1:150794880-150809577;-1,1,1,1,ENSG00000143387,CTSK,protein_coding,GTATATATATAAATCATACA,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L48,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074
2160400,zhu_2025_D3_stim48hr_cl,2160401,Perturb-seq,<NA>,<NA>,TTTGTGAGTTTGCATAACTACTCA-1_CD4i_R2L48,chr6:104936616-105083332;1,6,6,1,ENSG00000187772,LIN28B,protein_coding,GCTCTCCGGCGGGCACGAGG,CRISPRi,<NA>,P14DT0H0M0S,anti-CD3 antibody|anti-CD28 antibody|anti-CD2 ...,EFO:0003317|EFO:0003304|NCIT:C184729,CD4i_R2L48,D3_CE0008678,primary_cell,<NA>,Homo sapiens,lymphoid tissue,UBERON:0001744,"CD4-positive, alpha-beta T cell",CL:0000624,<NA>,<NA>,female,<NA>,adult,<NA>,healthy,<NA>,Genome-scale perturb-seq in primary human CD4+...,https://doi.org/10.64898/2025.12.23.696273,2025,Ronghui Zhu,Alexander Marson,Perturb-seq of primary human CD4-positive T ce...,\n Isolated human CD4-positive cell...,11839,2160401,EFO:0022868,endogenous,<NA>,dCas9-KRAB-Zim3,<NA>,lentivirus transduction,<NA>,lentivirus transduction,<NA>,random locus integration,<NA>,random locus integration,<NA>,constitutive transgene expression,<NA>,constitutive transgene expression,custom,<NA>,<NA>,pooled,<NA>,focused,<NA>,inhibition,Marson lab,2,2,21186,<NA>,<NA>,high-dimensional assay,<NA>,transcriptomic,<NA>,single-cell rna-seq,<NA>,Perturb-seq,<NA>,<NA>,GEM-X Flex Gene Expression Human n-plex kit,<NA>,Ultima Genomics UG100,<NA>,barcode sequencing,<NA>,CellRanger,<NA>,scanpy,<NA>,<NA>,GRCh38,"[{""dataset_accession"": ""Primary Human CD4+ T C...",MIT License,SWO:9000074

# VAR slot curation

### Standardise genes

In [32]:
cur_data.adata.var

                        gene_ids    feature_types  genome gene_name     mt
CUSTOM001_PuroR  CUSTOM001_PuroR  Gene Expression  GRCh38     PuroR  False
ENSG00000000003  ENSG00000000003  Gene Expression  GRCh38    TSPAN6  False
ENSG00000000005  ENSG00000000005  Gene Expression  GRCh38      TNMD  False
ENSG00000000419  ENSG00000000419  Gene Expression  GRCh38      DPM1  False
ENSG00000000457  ENSG00000000457  Gene Expression  GRCh38     SCYL3  False
...                          ...              ...     ...       ...    ...
ENSG00000291110  ENSG00000291110  Gene Expression  GRCh38   TRIM16L  False
ENSG00000291122  ENSG00000291122  Gene Expression  GRCh38  CASTOR3P  False
ENSG00000291135  ENSG00000291135  Gene Expression  GRCh38   FCGR1BP  False
ENSG00000291145  ENSG00000291145  Gene Expression  GRCh38   PPP5D1P  False
ENSG00000291237  ENSG00000291237  Gene Expression  GRCh38      SOD2  False

[18130 rows x 5 columns]

In [33]:
cur_data.standardize_genes(
    slot="var",
    input_column="gene_ids",
    input_column_type="ensembl_gene_id",
    remove_version=False,
    multiple_entries=False
)

Missing Ensembl IDs: ['ENSG00000148362', 'ENSG00000139656', 'CUSTOM001_PuroR']; attempting to fetch latest IDs...
Fetched latest Ensembl IDs: {'ENSG00000148362': 'ENSG00000310560', 'ENSG00000139656': 'ENSG00000226519'}
--------------------------------------------------
Successfully mapped 18130 out of 18130 Ensembl IDs.
--------------------------------------------------

/homes/zakirov/.local/share/uv/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [34]:
# replace gene symbols that are NOT ENSG with original provided gene symbol
cur_data.adata.var.loc[(cur_data.adata.var['gene_symbol'].isna()) &
 (~cur_data.adata.var['gene_name'].str.startswith('ENSG')), 'gene_symbol'] = cur_data.adata.var.loc[(cur_data.adata.var['gene_symbol'].isna()) &
 (~cur_data.adata.var['gene_name'].str.startswith('ENSG')), 'gene_name']

In [35]:
cur_data.adata.var.loc[cur_data.adata.var['ensembl_gene_id'] == 'CUSTOM001_PuroR', 'ensembl_gene_id'] = None

### Validate var metadata

In [36]:
cur_data.validate_data(slot='var')

2026-02-18 10:16:41,356 INFO curation_tools.curation_tools: adata.var is valid according to the var_schema.

       ensembl_gene_id gene_symbol
index
0                 None       PuroR
1      ENSG00000000003      TSPAN6
2      ENSG00000000005        TNMD
3      ENSG00000000419        DPM1
4      ENSG00000000457       SCYL3
...                ...         ...
18125  ENSG00000291110     TRIM16L
18126  ENSG00000291122    CASTOR3P
18127  ENSG00000291135     FCGR1BP
18128  ENSG00000291145     PPP5D1P
18129  ENSG00000291237        SOD2

[18130 rows x 2 columns]

# Save the dataset

In [37]:
cur_data.save_curated_data_h5ad()

/nfs/production/mfreeberg/perturb-seq/aleks/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)
... storing 'dataset_id' as categorical
... storing 'data_modality' as categorical
... storing 'significance_criteria' as categorical
... storing 'perturbed_target_coord' as categorical
... storing 'perturbed_target_chromosome' as categorical
... storing 'perturbed_target_ensg' as categorical
... storing 'perturbed_target_symbol' as categorical
... storing 'perturbed_target_biotype' as categorical
... storing 'guide_sequence' as categorical
... storing 'perturbation_type_label' as categorical
... storing 'perturbation_type_id' as categorical
... storing 'timepoint' as categorical
... storing 'treatment_label' as categorical
... storing 'treatment_id' as categorical
... storing 'technical_replicate' as categorical
... storing 'biological_replicate' as categorical
... storing 'model_system_label' as categorical
... storing 'model_system_id' as categorical
... storing 'species' as categorical
... storing 'tissue_label' as categorical
... storing 'tissue_id' as categorical
... storing 'cell_type_label' as categorical
... storing 'cell_type_id' as categorical
... storing 'cell_line_label' as categorical
... storing 'cell_line_id' as categorical
... storing 'sex_label' as categorical
... storing 'sex_id' as categorical
... storing 'developmental_stage_label' as categorical
... storing 'developmental_stage_id' as categorical
... storing 'disease_label' as categorical
... storing 'disease_id' as categorical
... storing 'study_title' as categorical
... storing 'study_uri' as categorical
... storing 'first_author' as categorical
... storing 'last_author' as categorical
... storing 'experiment_title' as categorical
... storing 'experiment_summary' as categorical
... storing 'number_of_perturbed_targets' as categorical
... storing 'number_of_perturbed_samples' as categorical
... storing 'library_generation_type_id' as categorical
... storing 'library_generation_type_label' as categorical
... storing 'library_generation_method_id' as categorical
... storing 'library_generation_method_label' as categorical
... storing 'enzyme_delivery_method_id' as categorical
... storing 'enzyme_delivery_method_label' as categorical
... storing 'library_delivery_method_id' as categorical
... storing 'library_delivery_method_label' as categorical
... storing 'enzyme_integration_state_id' as categorical
... storing 'enzyme_integration_state_label' as categorical
... storing 'library_integration_state_id' as categorical
... storing 'library_integration_state_label' as categorical
... storing 'enzyme_expression_control_id' as categorical
... storing 'enzyme_expression_control_label' as categorical
... storing 'library_expression_control_id' as categorical
... storing 'library_expression_control_label' as categorical
... storing 'library_name' as categorical
... storing 'library_uri' as categorical
... storing 'library_format_id' as categorical
... storing 'library_format_label' as categorical
... storing 'library_scope_id' as categorical
... storing 'library_scope_label' as categorical
... storing 'library_perturbation_type_id' as categorical
... storing 'library_perturbation_type_label' as categorical
... storing 'library_manufacturer' as categorical
... storing 'library_lentiviral_generation' as categorical
... storing 'library_grnas_per_target' as categorical
... storing 'library_total_grnas' as categorical
... storing 'readout_dimensionality_id' as categorical
... storing 'readout_dimensionality_label' as categorical
... storing 'readout_type_id' as categorical
... storing 'readout_type_label' as categorical
... storing 'readout_technology_id' as categorical
... storing 'readout_technology_label' as categorical
... storing 'method_name_id' as categorical
... storing 'method_name_label' as categorical
... storing 'method_uri' as categorical
... storing 'sequencing_library_kit_id' as categorical
... storing 'sequencing_library_kit_label' as categorical
... storing 'sequencing_platform_id' as categorical
... storing 'sequencing_platform_label' as categorical
... storing 'sequencing_strategy_id' as categorical
... storing 'sequencing_strategy_label' as categorical
... storing 'software_counts_id' as categorical
... storing 'software_counts_label' as categorical
... storing 'software_analysis_id' as categorical
... storing 'software_analysis_label' as categorical
... storing 'score_interpretation' as categorical
... storing 'reference_genome_id' as categorical
... storing 'reference_genome_label' as categorical
... storing 'associated_datasets' as categorical
... storing 'license_label' as categorical
... storing 'license_id' as categorical
... storing 'ensembl_gene_id' as categorical
... storing 'gene_symbol' as categorical

✅ Curated h5ad data saved to ../curated/h5ad/zhu_2025_D3_stim48hr_cl_curated.h5ad

In [38]:
cur_data.save_curated_data_parquet(split_metadata=True, save_metadata_only=True)

✅ Metadata saved to ../curated/parquet/zhu_2025_D3_stim48hr_cl_curated_metadata.parquet

# Upload to BigQuery

In [ ]:
# upload_parquet_to_bq(
#     parquet_path='../curated/parquet/zhu_2025_D1_rest_cl_curated_metadata.parquet',
#     bq_dataset_id='prj-ext-dev-pertcat-437314.perturb_seq',
#     bq_table_name='metadata',
#     key_columns=['dataset_id', 'sample_id'],
#     verbose=True
# )

# Upload to GC Storage

In [ ]:
# !gcloud storage cp ../curated/h5ad/zhu_2025_D3_stim48hr_cl_curated.h5ad gs://perturbation-catalogue-lake/perturbseq/curated/