# Import

In [1]:
from pathlib import Path
import pandas as pd

from curation_tools.biogrid_curation_tools import (
    process_biogrid_screen,
    compare_metadata_biogrid
)

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/.venv/lib/python3.12/site-packages/pandera/_pandas_deprecated.py:157: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

📝 Define the id of the Biogrid paper and paths/directories

In [2]:
gc_fname = "25307932" # PMID of the Biogrid paper

data_dir = Path("../supplementary/temp/biogrid/data")
biogrid_metadata_path = Path("../../text_extraction/biogrid_curated_metadata.csv")
curated_gemini_dir = Path("../../text_extraction/curated_gemini")
non_curated_h5ad_dir = Path("../non_curated/h5ad")
curated_parquet_dir = Path("../curated/parquet")
crispr_studies_path = Path("../crispr_studies.xlsx")

# BigQuery dataset id
bq_dataset_id = "prj-ext-dev-pertcat-437314.crispr"

Read metadata files

In [3]:
gc_metadata_df = pd.read_json(curated_gemini_dir / f"{gc_fname}.json")
gc_metadata_df = gc_metadata_df.set_index("gemini_" + gc_metadata_df.index.astype(str))
bg_metadata_all = pd.read_csv(biogrid_metadata_path)
bg_metadata_df = bg_metadata_all[bg_metadata_all["SOURCE_ID"] == gc_fname]
all_screen_ids = bg_metadata_df["#SCREEN_ID"].values

crispr_studies_df = pd.read_excel(crispr_studies_path)

print(f"Screen ids in the study:\n{all_screen_ids}")

Screen ids in the study:
[   5    6 1161 1162]

📝 Select the `screen_id` to analyse from above

📝 Define `index_prefix`

In [ ]:
biogrid_screen_id = "biogrid_5" # biogrid screen id to analyse - select from above
gemini_id = "gemini_2" # corresponding gemini id - examine the comparison table below to identify the correct gemini id

Create the comparison table between Biogrid and Gemini-curated metadata

**Manually examine the potential discrepancies to validate the curation process!**

In [ ]:
compare_metadata_biogrid(
    bg_metadata_df=bg_metadata_df,
    gc_metadata_df=gc_metadata_df,
    biogrid_screen_id=biogrid_screen_id,
    gemini_id=gemini_id # gemini id - None to see all gemini entries
)

Use the data from the comparison table, biogrid page of the screen and the original study to update the `crispr_studies.xlsx` file.

Then run the cell below to process the Biogrid screen and upload to BigQuery.

In [4]:
for dataset_id in crispr_studies_df['dataset_id']:
    print(f"Processing dataset_id: {dataset_id}")
    biogrid_screen_path = (data_dir / f"BIOGRID-ORCS-SCREEN_{dataset_id.lstrip('biogrid_')}-1.1.17.screen.tab.txt")
    curated_metadata_dict = crispr_studies_df[crispr_studies_df['dataset_id'] == dataset_id].to_dict(orient='records')[0]

    process_biogrid_screen(
        biogrid_dataset_id=dataset_id,
        biogrid_screen_path=biogrid_screen_path,
        biogrid_metadata_df=bg_metadata_all,
        curated_metadata_dict=curated_metadata_dict,
        non_curated_h5ad_dir=non_curated_h5ad_dir,
        upload_to_bq=True, # set to True to upload to BigQuery
        bq_dataset_id=bq_dataset_id,
        bq_metadata_table_name="metadata_upd",
        bq_data_table_name="data_upd",
        extra_data_columns = ['significant', 'significance_criteria', 'perturbed_target_symbol', 'perturbed_target_ensg']
    )

Processing dataset_id: biogrid_1161

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})

✅ Saved AnnData object to ../non_curated/h5ad/biogrid_1161.h5ad
Loading data from ../non_curated/h5ad/biogrid_1161.h5ad
Column perturbation_name has no NA entries in adata.obs

Mapping gene symbols: 100%|████████████████████████████████| 15964/15964 [00:00<00:00, 55380.56it/s]

--------------------------------------------------
Successfully mapped 15932 out of 15964 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['MTRNR2L7', 'GPR75-ASB3', 'MTRNR2L1', 'MTRNR2L2', 'MTRNR2L3', 'MTRNR2L4', 'MTRNR2L5', 'MTRNR2L6', 'MTRNR2L8', 'MTRNR2L9', 'MTRNR2L10', 'PHOSPHO2-KLHL23', 'TNFAIP8L2-SCNM1', 'SPHAR', 'AKAP2', 'TMEM155', 'LINC01599', 'FAM153B', '391322', '401052', 'PGBD3', 'CRIPAK', 'GSTT1', 'FLJ44635', 'PRY2', 'BAGE', 'CCL3L1', 'GTF2H2C_2', 'LUZP6', 'BAGE5', 'BAGE4', 'BAGE3']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_1161_A1BG,biogrid_1161,biogrid_1161_A1BG,CRISPR screen,False,-,biogrid_1161_A1BG,chr19:58345178-58353492;-1,19,19,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_NAT2,biogrid_1161,biogrid_1161_NAT2,CRISPR screen,False,-,biogrid_1161_NAT2,chr8:18391252-18401218;1,8,8,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_ADA,biogrid_1161,biogrid_1161_ADA,CRISPR screen,False,-,biogrid_1161_ADA,chr20:44584896-44652252;-1,20,20,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_CDH2,biogrid_1161,biogrid_1161_CDH2,CRISPR screen,False,-,biogrid_1161_CDH2,chr18:27932879-28177946;-1,18,18,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_AKT3,biogrid_1161,biogrid_1161_AKT3,CRISPR screen,False,-,biogrid_1161_AKT3,chr1:243488233-243851079;-1,1,1,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_1161_PTBP3,biogrid_1161,biogrid_1161_PTBP3,CRISPR screen,False,-,biogrid_1161_PTBP3,chr9:112215071-112333695;-1,9,9,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_KCNE2,biogrid_1161,biogrid_1161_KCNE2,CRISPR screen,False,-,biogrid_1161_KCNE2,chr21:34180729-34371381;1,21,21,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_DGCR2,biogrid_1161,biogrid_1161_DGCR2,CRISPR screen,False,-,biogrid_1161_DGCR2,chr22:19036280-19122461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_CASP8AP2,biogrid_1161,biogrid_1161_CASP8AP2,CRISPR screen,True,-,biogrid_1161_CASP8AP2,chr6:89829894-89874436;1,6,6,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074
biogrid_1161_SCO2,biogrid_1161,biogrid_1161_SCO2,CRISPR screen,False,-,biogrid_1161_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Positive rho score shows that inhibition of th...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 1-...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_1161_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_1161_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_1161_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_1161_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_1161_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_1161_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 15964 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_1161_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_1161_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 15964 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_5

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})

✅ Saved AnnData object to ../non_curated/h5ad/biogrid_5.h5ad
Loading data from ../non_curated/h5ad/biogrid_5.h5ad
Column perturbation_name has no NA entries in adata.obs

Mapping gene symbols: 100%|████████████████████████████████| 15964/15964 [00:00<00:00, 56051.62it/s]

--------------------------------------------------
Successfully mapped 15929 out of 15964 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['BAGE', 'GSTT1', 'CCL3L1', 'SPHAR', 'AKAP2', 'BAGE5', 'BAGE4', 'BAGE3', 'TMEM155', 'LINC01599', 'FAM153B', 'PGBD3', 'CRIPAK', 'LOC391322', 'FLJ44635', 'LOC401052', 'PRY2', 'LOC728392', 'GTF2H2C_2', 'LUZP6', 'LOC100130705', 'MTRNR2L7', 'GPR75-ASB3', 'MTRNR2L1', 'MTRNR2L2', 'MTRNR2L3', 'MTRNR2L4', 'MTRNR2L5', 'MTRNR2L6', 'MTRNR2L8', 'MTRNR2L9', 'MTRNR2L10', 'PHOSPHO2-KLHL23', 'ZNF664-RFLNA', 'TNFAIP8L2-SCNM1']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_5_A1BG,biogrid_5,biogrid_5_A1BG,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_A1BG,chr19:58345178-58353492;-1,19,19,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_A2M,biogrid_5,biogrid_5_A2M,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_A2M,chr12:9067664-9116229;-1,12,12,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_NAT1,biogrid_5,biogrid_5_NAT1,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_NAT1,chr8:18170399-18223739;1,8,8,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_NAT2,biogrid_5,biogrid_5_NAT2,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_NAT2,chr8:18391252-18401218;1,8,8,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_SERPINA3,biogrid_5,biogrid_5_SERPINA3,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_SERPINA3,chr14:94612377-94624645;1,14,14,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_5_PTGES3L-AARSD1,biogrid_5,biogrid_5_PTGES3L-AARSD1,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_PTGES3L-AARSD1,chr17:42950526-42980528;-1,17,17,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_PYURF,biogrid_5,biogrid_5_PYURF,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_PYURF,chr4:88520998-88523776;-1,4,4,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_CSAG2,biogrid_5,biogrid_5_CSAG2,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_CSAG2,chrX:152708261-152721661;-1,X,23,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_GAGE10,biogrid_5,biogrid_5_GAGE10,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_GAGE10,chrX:49303646-49319841;1,X,23,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074
biogrid_5_UPK3B,biogrid_5,biogrid_5_UPK3B,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_5_UPK3B,chr7:76510525-76516522;1,7,7,1,...,<NA>,custom,<NA>,custom,Inhibition of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 2-...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_5_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_5_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_5_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_5_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_5_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_5_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 15964 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_5_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_5_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 15964 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_2362
✅ Saved AnnData object to ../non_curated/h5ad/biogrid_2362.h5ad
Loading data from ../non_curated/h5ad/biogrid_2362.h5ad
Column perturbation_name has no NA entries in adata.obs

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})
Mapping gene symbols: 100%|██████████████████████████████████| 2839/2839 [00:00<00:00, 51705.76it/s]

--------------------------------------------------
Successfully mapped 2826 out of 2839 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['LOC100129636', 'MTRNR2L1', 'MTRNR2L6', 'LILRA3', 'GTPBP6_X', 'ASMT_X', 'ZBED1_X', 'LOC339862', 'CCL4L1', 'PRY2', 'LOC554223', 'LUZP6', 'PRY']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_2362_POM121C,biogrid_2362,biogrid_2362_POM121C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_POM121C,chr7:75416784-75486358;-1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_CTAGE4,biogrid_2362,biogrid_2362_CTAGE4,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_CTAGE4,chr7:144183466-144186080;1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_CXorf51A,biogrid_2362,biogrid_2362_CXorf51A,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_CXorf51A,chrX:146814106-146814744;-1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_TEX13C,biogrid_2362,biogrid_2362_TEX13C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_TEX13C,chrX:125319871-125325216;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_LOC100129636,biogrid_2362,biogrid_2362_LOC100129636,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_LOC100129636,<NA>,<NA>,0,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_2362_MED12,biogrid_2362,biogrid_2362_MED12,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_MED12,chrX:71118543-71144103;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_NUP153,biogrid_2362,biogrid_2362_NUP153,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_NUP153,chr6:17614707-17706935;-1,6,6,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_RBX1,biogrid_2362,biogrid_2362_RBX1,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_RBX1,chr22:40951277-40973539;1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_THOC1,biogrid_2362,biogrid_2362_THOC1,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_THOC1,chr18:214515-268053;-1,18,18,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074
biogrid_2362_SCO2,biogrid_2362,biogrid_2362_SCO2,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2362_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 1-PM...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_2362_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_2362_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_2362_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_2362_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_2362_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2362_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 2839 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_2362_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2362_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 5678 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_2363

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})

✅ Saved AnnData object to ../non_curated/h5ad/biogrid_2363.h5ad
Loading data from ../non_curated/h5ad/biogrid_2363.h5ad
Column perturbation_name has no NA entries in adata.obs

Mapping gene symbols: 100%|██████████████████████████████████| 2839/2839 [00:00<00:00, 54238.75it/s]

--------------------------------------------------
Successfully mapped 2826 out of 2839 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['LOC100129636', 'MTRNR2L1', 'MTRNR2L6', 'LILRA3', 'GTPBP6_X', 'ASMT_X', 'ZBED1_X', 'LOC339862', 'CCL4L1', 'PRY2', 'LOC554223', 'LUZP6', 'PRY']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_2363_POM121C,biogrid_2363,biogrid_2363_POM121C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_POM121C,chr7:75416784-75486358;-1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_CTAGE4,biogrid_2363,biogrid_2363_CTAGE4,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_CTAGE4,chr7:144183466-144186080;1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_CXorf51A,biogrid_2363,biogrid_2363_CXorf51A,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_CXorf51A,chrX:146814106-146814744;-1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_TEX13C,biogrid_2363,biogrid_2363_TEX13C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_TEX13C,chrX:125319871-125325216;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_LOC100129636,biogrid_2363,biogrid_2363_LOC100129636,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_LOC100129636,<NA>,<NA>,0,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_2363_MED12,biogrid_2363,biogrid_2363_MED12,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_MED12,chrX:71118543-71144103;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_NUP153,biogrid_2363,biogrid_2363_NUP153,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_NUP153,chr6:17614707-17706935;-1,6,6,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_RBX1,biogrid_2363,biogrid_2363_RBX1,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_RBX1,chr22:40951277-40973539;1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_THOC1,biogrid_2363,biogrid_2363_THOC1,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_THOC1,chr18:214515-268053;-1,18,18,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074
biogrid_2363_SCO2,biogrid_2363,biogrid_2363_SCO2,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2363_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 2-PM...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_2363_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_2363_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_2363_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_2363_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_2363_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2363_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 2839 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_2363_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2363_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 5678 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_2364
✅ Saved AnnData object to ../non_curated/h5ad/biogrid_2364.h5ad
Loading data from ../non_curated/h5ad/biogrid_2364.h5ad
Column perturbation_name has no NA entries in adata.obs

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})
Mapping gene symbols: 100%|██████████████████████████████████| 2839/2839 [00:00<00:00, 53044.68it/s]

--------------------------------------------------
Successfully mapped 2826 out of 2839 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['LOC100129636', 'MTRNR2L1', 'MTRNR2L6', 'LILRA3', 'GTPBP6_X', 'ASMT_X', 'ZBED1_X', 'LOC339862', 'CCL4L1', 'PRY2', 'LOC554223', 'LUZP6', 'PRY']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_2364_POM121C,biogrid_2364,biogrid_2364_POM121C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_POM121C,chr7:75416784-75486358;-1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_CTAGE4,biogrid_2364,biogrid_2364_CTAGE4,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_CTAGE4,chr7:144183466-144186080;1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_CXorf51A,biogrid_2364,biogrid_2364_CXorf51A,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_CXorf51A,chrX:146814106-146814744;-1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_TEX13C,biogrid_2364,biogrid_2364_TEX13C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_TEX13C,chrX:125319871-125325216;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_LOC100129636,biogrid_2364,biogrid_2364_LOC100129636,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_LOC100129636,<NA>,<NA>,0,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_2364_MED12,biogrid_2364,biogrid_2364_MED12,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_MED12,chrX:71118543-71144103;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_NUP153,biogrid_2364,biogrid_2364_NUP153,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_NUP153,chr6:17614707-17706935;-1,6,6,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_RBX1,biogrid_2364,biogrid_2364_RBX1,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_RBX1,chr22:40951277-40973539;1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_THOC1,biogrid_2364,biogrid_2364_THOC1,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_THOC1,chr18:214515-268053;-1,18,18,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074
biogrid_2364_SCO2,biogrid_2364,biogrid_2364_SCO2,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2364_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 3-PM...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_2364_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_2364_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_2364_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_2364_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_2364_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2364_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 2839 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_2364_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2364_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 5678 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_2365

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})

✅ Saved AnnData object to ../non_curated/h5ad/biogrid_2365.h5ad
Loading data from ../non_curated/h5ad/biogrid_2365.h5ad
Column perturbation_name has no NA entries in adata.obs

Mapping gene symbols: 100%|██████████████████████████████████| 2839/2839 [00:00<00:00, 60079.46it/s]

--------------------------------------------------
Successfully mapped 2826 out of 2839 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['LOC100129636', 'MTRNR2L1', 'MTRNR2L6', 'LILRA3', 'GTPBP6_X', 'ASMT_X', 'ZBED1_X', 'LOC339862', 'CCL4L1', 'PRY2', 'LOC554223', 'LUZP6', 'PRY']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_2365_POM121C,biogrid_2365,biogrid_2365_POM121C,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_POM121C,chr7:75416784-75486358;-1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_CTAGE4,biogrid_2365,biogrid_2365_CTAGE4,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_CTAGE4,chr7:144183466-144186080;1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_CXorf51A,biogrid_2365,biogrid_2365_CXorf51A,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_CXorf51A,chrX:146814106-146814744;-1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_TEX13C,biogrid_2365,biogrid_2365_TEX13C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_TEX13C,chrX:125319871-125325216;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_LOC100129636,biogrid_2365,biogrid_2365_LOC100129636,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_LOC100129636,<NA>,<NA>,0,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_2365_MED12,biogrid_2365,biogrid_2365_MED12,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_MED12,chrX:71118543-71144103;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_NUP153,biogrid_2365,biogrid_2365_NUP153,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_NUP153,chr6:17614707-17706935;-1,6,6,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_RBX1,biogrid_2365,biogrid_2365_RBX1,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_RBX1,chr22:40951277-40973539;1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_THOC1,biogrid_2365,biogrid_2365_THOC1,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_THOC1,chr18:214515-268053;-1,18,18,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074
biogrid_2365_SCO2,biogrid_2365,biogrid_2365_SCO2,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2365_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly enriched genes (positive CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 4-PM...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_2365_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_2365_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_2365_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_2365_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_2365_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2365_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 2839 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_2365_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2365_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 5678 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_2366
✅ Saved AnnData object to ../non_curated/h5ad/biogrid_2366.h5ad
Loading data from ../non_curated/h5ad/biogrid_2366.h5ad
Column perturbation_name has no NA entries in adata.obs

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})
Mapping gene symbols: 100%|██████████████████████████████████| 2839/2839 [00:00<00:00, 58245.67it/s]

--------------------------------------------------
Successfully mapped 2826 out of 2839 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['LOC100129636', 'MTRNR2L1', 'MTRNR2L6', 'LILRA3', 'GTPBP6_X', 'ASMT_X', 'ZBED1_X', 'LOC339862', 'CCL4L1', 'PRY2', 'LOC554223', 'LUZP6', 'PRY']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_2366_POM121C,biogrid_2366,biogrid_2366_POM121C,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_POM121C,chr7:75416784-75486358;-1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_CTAGE4,biogrid_2366,biogrid_2366_CTAGE4,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_CTAGE4,chr7:144183466-144186080;1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_CXorf51A,biogrid_2366,biogrid_2366_CXorf51A,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_CXorf51A,chrX:146814106-146814744;-1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_TEX13C,biogrid_2366,biogrid_2366_TEX13C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_TEX13C,chrX:125319871-125325216;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_LOC100129636,biogrid_2366,biogrid_2366_LOC100129636,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_LOC100129636,<NA>,<NA>,0,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_2366_MED12,biogrid_2366,biogrid_2366_MED12,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_MED12,chrX:71118543-71144103;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_NUP153,biogrid_2366,biogrid_2366_NUP153,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_NUP153,chr6:17614707-17706935;-1,6,6,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_RBX1,biogrid_2366,biogrid_2366_RBX1,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_RBX1,chr22:40951277-40973539;1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_THOC1,biogrid_2366,biogrid_2366_THOC1,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_THOC1,chr18:214515-268053;-1,18,18,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074
biogrid_2366_SCO2,biogrid_2366,biogrid_2366_SCO2,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2366_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 5-PM...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_2366_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_2366_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_2366_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_2366_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_2366_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2366_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 2839 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_2366_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2366_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 5678 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_2367
✅ Saved AnnData object to ../non_curated/h5ad/biogrid_2367.h5ad
Loading data from ../non_curated/h5ad/biogrid_2367.h5ad
Column perturbation_name has no NA entries in adata.obs

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})
Mapping gene symbols: 100%|██████████████████████████████████| 2839/2839 [00:00<00:00, 62607.81it/s]

--------------------------------------------------
Successfully mapped 2826 out of 2839 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['LOC100129636', 'MTRNR2L1', 'MTRNR2L6', 'LILRA3', 'GTPBP6_X', 'ASMT_X', 'ZBED1_X', 'LOC339862', 'CCL4L1', 'PRY2', 'LOC554223', 'LUZP6', 'PRY']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_2367_POM121C,biogrid_2367,biogrid_2367_POM121C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_POM121C,chr7:75416784-75486358;-1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_CTAGE4,biogrid_2367,biogrid_2367_CTAGE4,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_CTAGE4,chr7:144183466-144186080;1,7,7,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_CXorf51A,biogrid_2367,biogrid_2367_CXorf51A,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_CXorf51A,chrX:146814106-146814744;-1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_TEX13C,biogrid_2367,biogrid_2367_TEX13C,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_TEX13C,chrX:125319871-125325216;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_LOC100129636,biogrid_2367,biogrid_2367_LOC100129636,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_LOC100129636,<NA>,<NA>,0,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_2367_MED12,biogrid_2367,biogrid_2367_MED12,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_MED12,chrX:71118543-71144103;1,X,23,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_NUP153,biogrid_2367,biogrid_2367_NUP153,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_NUP153,chr6:17614707-17706935;-1,6,6,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_RBX1,biogrid_2367,biogrid_2367_RBX1,CRISPR screen,True,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_RBX1,chr22:40951277-40973539;1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_THOC1,biogrid_2367,biogrid_2367_THOC1,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_THOC1,chr18:214515-268053;-1,18,18,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074
biogrid_2367_SCO2,biogrid_2367,biogrid_2367_SCO2,CRISPR screen,False,CRISPR Score (CS) < -1.0 AND (FDR) < 0.05 OR (...,biogrid_2367_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Significantly depleted genes (negative CRSIPR ...,<NA>,<NA>,"[{""dataset_accession"": ""Panea RI (2019) - 6-PM...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_2367_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_2367_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_2367_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_2367_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_2367_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2367_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 2839 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_2367_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2367_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 5678 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_2373

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})

✅ Saved AnnData object to ../non_curated/h5ad/biogrid_2373.h5ad
Loading data from ../non_curated/h5ad/biogrid_2373.h5ad
Column perturbation_name has no NA entries in adata.obs

Mapping gene symbols: 100%|████████████████████████████████| 18044/18044 [00:00<00:00, 60285.91it/s]

--------------------------------------------------
Successfully mapped 17975 out of 18044 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['MTRNR2L6', 'GVQW1', 'LILRA3', 'AKAP2', 'PALM2', 'TMEM155', 'RP11-408E5.4', 'LINC01599', 'CTD-2616J11.4', 'AP003774.4', 'EIF2S3L', 'AC007431.1', 'RP11-389E17.1', 'AC016722.1', 'AC091801.1', 'PGBD3', 'C10orf126', 'CRIPAK', 'GSTT1', 'RP11-89N17.1', 'AC007040.11', 'PRR25', 'C16orf97', 'RP11-766F14.2', 'RP11-93B14.6', 'RP11-542P2.1', 'C8orf49', 'RP11-1220K2.2', 'LINC01590', 'AC016757.3', 'AC093802.1', 'RP11-422N16.3', 'AC018755.1', 'RP11-553A10.1', 'AP001816.1', 'SEPT9_1', 'SEPT10_1', 'SEPT1_1', 'MARCH11_1', 'MARCH2_1', 'SEPT7_1', 'SEPT3_1', 'MARCH7_1', 'MARCH1_1', 'MARCH4_1', 'MARCH5_1', 'SEPT6_1', 'MARCH6_1', 'SEPT12_1', 'SEPT5_1', 'MARCH10_1', 'SEPT14_1', 'MARC2_1', 'SEPT8_1', 'SEPT4_1', 'SEPT2_1', 'MARCH8_1', 'SEPT11_1', 'MARCH3_1', 'MARCH9_1', 'MARC1_1', 'SEP15_1', 'SMIM2', 'AC106876.2', 'FLJ27365', 'RP11-770J1.4', 'U82695.9', 'AC079612.1', 'CTD-2368P22.1']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

Validation errors for adata.obs: {
  "DATA": {
    "DATAFRAME_CHECK": [
      {
        "schema": "ObsSchema",
        "column": "software_analysis_label",
        "check": "isin(['custom', 'MAGeCK', 'Achilles', 'TRADE'])",

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_2373_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_2373_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_2373_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_2373_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_2373_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2373_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 18044 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_2373_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_2373_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 54132 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_6

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})

✅ Saved AnnData object to ../non_curated/h5ad/biogrid_6.h5ad
Loading data from ../non_curated/h5ad/biogrid_6.h5ad
Column perturbation_name has no NA entries in adata.obs

Mapping gene symbols: 100%|████████████████████████████████| 15965/15965 [00:00<00:00, 59495.81it/s]

--------------------------------------------------
Successfully mapped 15930 out of 15965 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['BAGE', 'GSTT1', 'CCL3L1', 'SPHAR', 'AKAP2', 'BAGE5', 'BAGE4', 'BAGE3', 'TMEM155', 'LINC01599', 'FAM153B', 'PGBD3', 'CRIPAK', 'LOC391322', 'FLJ44635', 'LOC401052', 'PRY2', 'LOC728392', 'GTF2H2C_2', 'LUZP6', 'LOC100130705', 'MTRNR2L7', 'GPR75-ASB3', 'MTRNR2L1', 'MTRNR2L2', 'MTRNR2L3', 'MTRNR2L4', 'MTRNR2L5', 'MTRNR2L6', 'MTRNR2L8', 'MTRNR2L9', 'MTRNR2L10', 'PHOSPHO2-KLHL23', 'ZNF664-RFLNA', 'TNFAIP8L2-SCNM1']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_6_A1BG,biogrid_6,biogrid_6_A1BG,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_A1BG,chr19:58345178-58353492;-1,19,19,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_A2M,biogrid_6,biogrid_6_A2M,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_A2M,chr12:9067664-9116229;-1,12,12,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_NAT1,biogrid_6,biogrid_6_NAT1,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_NAT1,chr8:18170399-18223739;1,8,8,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_NAT2,biogrid_6,biogrid_6_NAT2,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_NAT2,chr8:18391252-18401218;1,8,8,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_SERPINA3,biogrid_6,biogrid_6_SERPINA3,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_SERPINA3,chr14:94612377-94624645;1,14,14,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_6_PTGES3L-AARSD1,biogrid_6,biogrid_6_PTGES3L-AARSD1,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_PTGES3L-AARSD1,chr17:42950526-42980528;-1,17,17,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_PYURF,biogrid_6,biogrid_6_PYURF,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_PYURF,chr4:88520998-88523776;-1,4,4,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_CSAG2,biogrid_6,biogrid_6_CSAG2,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_CSAG2,chrX:152708261-152721661;-1,X,23,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_GAGE10,biogrid_6,biogrid_6_GAGE10,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_GAGE10,chrX:49303646-49319841;1,X,23,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074
biogrid_6_UPK3B,biogrid_6,biogrid_6_UPK3B,CRISPR screen,False,Gamma (normalized log2e/t) <= -0.1,biogrid_6_UPK3B,chr7:76510525-76516522;1,7,7,1,...,<NA>,custom,<NA>,custom,Activation of hit genes results in decreased f...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 3-...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_6_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_6_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_6_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_6_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_6_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_6_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 15965 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_6_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_6_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 15965 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Processing dataset_id: biogrid_1162

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/biogrid_curation_tools.py:293: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  OBS_df = OBS_df.replace({None: np.nan})

✅ Saved AnnData object to ../non_curated/h5ad/biogrid_1162.h5ad
Loading data from ../non_curated/h5ad/biogrid_1162.h5ad
Column perturbation_name has no NA entries in adata.obs

Mapping gene symbols: 100%|████████████████████████████████| 15965/15965 [00:00<00:00, 61494.18it/s]

--------------------------------------------------
Successfully mapped 15933 out of 15965 gene symbols.
--------------------------------------------------
Couldn't map gene symbols: ['MTRNR2L7', 'GPR75-ASB3', 'MTRNR2L1', 'MTRNR2L2', 'MTRNR2L3', 'MTRNR2L4', 'MTRNR2L5', 'MTRNR2L6', 'MTRNR2L8', 'MTRNR2L9', 'MTRNR2L10', 'PHOSPHO2-KLHL23', 'TNFAIP8L2-SCNM1', 'SPHAR', 'AKAP2', 'TMEM155', 'LINC01599', 'FAM153B', '391322', '401052', 'PGBD3', 'CRIPAK', 'GSTT1', 'FLJ44635', 'PRY2', 'BAGE', 'CCL3L1', 'GTF2H2C_2', 'LUZP6', 'BAGE5', 'BAGE4', 'BAGE3']
--------------------------------------------------
Counted entries in column perturbed_target_symbol of adata.obs and stored in perturbed_target_number
Chromosome encoding applied to perturbed_target_chromosome in adata.obs and stored as 'perturbed_target_chromosome_encoding'.
Column technical_replicate added to adata.obs
Column biological_replicate added to adata.obs
Matched columns of adata.obs to the obs_schema.

,dataset_id,sample_id,data_modality,significant,significance_criteria,perturbation_name,perturbed_target_coord,perturbed_target_chromosome,perturbed_target_chromosome_encoding,perturbed_target_number,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
index,,,,,,,,,,,,,,,,,,,,,
biogrid_1162_A1BG,biogrid_1162,biogrid_1162_A1BG,CRISPR screen,False,-,biogrid_1162_A1BG,chr19:58345178-58353492;-1,19,19,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_NAT2,biogrid_1162,biogrid_1162_NAT2,CRISPR screen,False,-,biogrid_1162_NAT2,chr8:18391252-18401218;1,8,8,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_ADA,biogrid_1162,biogrid_1162_ADA,CRISPR screen,False,-,biogrid_1162_ADA,chr20:44584896-44652252;-1,20,20,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_CDH2,biogrid_1162,biogrid_1162_CDH2,CRISPR screen,False,-,biogrid_1162_CDH2,chr18:27932879-28177946;-1,18,18,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_AKT3,biogrid_1162,biogrid_1162_AKT3,CRISPR screen,False,-,biogrid_1162_AKT3,chr1:243488233-243851079;-1,1,1,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
biogrid_1162_PTBP3,biogrid_1162,biogrid_1162_PTBP3,CRISPR screen,False,-,biogrid_1162_PTBP3,chr9:112215071-112333695;-1,9,9,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_KCNE2,biogrid_1162,biogrid_1162_KCNE2,CRISPR screen,False,-,biogrid_1162_KCNE2,chr21:34180729-34371381;1,21,21,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_DGCR2,biogrid_1162,biogrid_1162_DGCR2,CRISPR screen,False,-,biogrid_1162_DGCR2,chr22:19036280-19122461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_CASP8AP2,biogrid_1162,biogrid_1162_CASP8AP2,CRISPR screen,False,-,biogrid_1162_CASP8AP2,chr6:89829894-89874436;1,6,6,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074
biogrid_1162_SCO2,biogrid_1162,biogrid_1162_SCO2,CRISPR screen,False,-,biogrid_1162_SCO2,chr22:50523564-50526461;-1,22,22,1,...,<NA>,custom,<NA>,custom,Negative rho scores indicate activation of the...,<NA>,<NA>,"[{""dataset_accession"": ""Gilbert LA (2014) - 4-...",MIT License,SWO:9000074

/Users/zakirov/Documents/GitHub/PerturbationCatalogue/data_exploration/curation_tools/curation_tools.py:327: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adata.obs = adata.obs.fillna(value=np.nan)

✅ Curated h5ad data saved to ../curated/h5ad/biogrid_1162_curated.h5ad
✅ Metadata saved to ../curated/parquet/biogrid_1162_curated_metadata.parquet
Processing data...
Saving data to ../curated/parquet/biogrid_1162_curated_data.parquet...
✅ Data saved to ../curated/parquet/biogrid_1162_curated_data.parquet
Uploading metadata Parquet to BigQuery: ../curated/parquet/biogrid_1162_curated_metadata.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_1162_curated_metadata.parquet to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging...
Staging table: loaded 15965 rows to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.metadata_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.metadata_upd_staging
Uploading data Parquet to BigQuery: ../curated/parquet/biogrid_1162_curated_data.parquet
Staging table: loading `.parquet` file ../curated/parquet/biogrid_1162_curated_data.parquet to prj-ext-dev-pertcat-437314.crispr.data_upd_staging...
Staging table: loaded 15965 rows to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Staging table: added ingested_at timestamp column to prj-ext-dev-pertcat-437314.crispr.data_upd_staging
Merge completed: staging → prj-ext-dev-pertcat-437314.crispr.data_upd with type-safe casting.
Staging table: deleted prj-ext-dev-pertcat-437314.crispr.data_upd_staging

In [ ]:
crispr_studies_df